Repository mattermost/mattermost, pull requests merged in 2018-04, with the labels that each got.

#8559 MM-9967 Fixing DB load causing user logout.
  api4/context.go
  app/session.go
Labels: 2: Dev Review

#8549 Make channel mute command respond with and without ~ prefix
  app/command_mute.go
Labels: 2: Dev Review

#8528 Remove the index on Channels.DisplayName (v4.7)
  model/version.go
  store/sqlstore/channel_store.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8529 Remove the index on Channels.DisplayName (v4.8)
  model/version.go
  store/sqlstore/channel_store.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8556 MM-9944 Fix sanitization on websocket user edit events. (4.7)
  app/user.go
Labels: 3: Ready to Merge

#8557 MM-9944 Fix sanitization on websocket user edit events. (4.8)
  app/user.go
Labels: 3: Ready to Merge

#8554 MM-9999 Fix unwanted team invite_id in email invites. (4.7)
  api4/team_test.go
  app/email.go
  app/team.go
  app/team_test.go
Labels: 3: Ready to Merge

#8555 MM-9999 Fix unwanted team invite_id in email invites. (4.8)
  api4/team_test.go
  app/email.go
  app/team.go
  app/team_test.go
Labels: 3: Ready to Merge

#8570 translations PR 20180402
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, Localization

#8568 MM-9866 Fixing unit tests for Go 1.10
  Makefile
  api4/command_test.go
  api4/file_test.go
Labels: 3: Ready to Merge

#8572 Add missing timezone setting to app/diagnostics.go
  app/diagnostics.go
  model/config.go
Labels: 3: Ready to Merge

#8569 Minor text changes to /open, /join and /mute slash commands
  i18n/en.json
Labels: 3: Ready to Merge

#8582 uncomment 4.9 upgrade code
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8585 [MM-10046] Fix out of channel mentions for mentioned word with valid punctuations
  app/notification.go
  app/notification_test.go
Labels: 3: Ready to Merge

#8565 MM-8678: add CUD support for channel members via plugins
  app/channel.go
  app/channel_test.go
  app/plugin_api.go
  plugin/api.go
  plugin/plugintest/api.go
  plugin/rpcplugin/api.go
  plugin/rpcplugin/api_test.go
Labels: 3: Ready to Merge

#8573 Added additional unit tests for IE11 and compatibility mode
  web/web_test.go
Labels: 2: Dev Review

#8589 MM-8834: Changes separator between jobs message and details.
  jobs/jobs.go
Labels: 3: Ready to Merge

#8586 MM-9849 Added tracking of which settings are set through environment variables
  api4/system.go
  api4/system_test.go
  app/admin.go
  app/app.go
  app/config.go
  cmd/commands/config_flag_test.go
  cmd/commands/message_export_test.go
  glide.lock
  glide.yaml
  model/client4.go
  utils/config.go
  utils/config_test.go
  utils/mail_test.go
  vendor/github.com/spf13/viper/nohup.out
  vendor/github.com/spf13/viper/viper.go
Labels: 3: Ready to Merge

#8600 Merge release-4.9 to master
  app/notification.go
  app/notification_test.go
  glide.lock
  glide.yaml
  jobs/jobs.go
  vendor/github.com/minio/minio-go/api-put-object-multipart.go
  vendor/github.com/minio/minio-go/api-put-object.go
Labels: 2: Dev Review

#8607 MM-10036 Ensured correct handling of capitalized special mentions
  app/notification.go
  app/notification_test.go
Labels: 3: Ready to Merge

#8609 Fix mute channel when not a member and adding unit tests
  app/channel.go
  app/command_mute.go
  app/command_mute_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8606 translations PR 20180411
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8608 MM-8180 Improve error message for testing smtp connections
  app/admin.go
  i18n/en.json
Labels: 3: Ready to Merge

#8386 Add Auto Responder handler
  api4/status.go
  api4/user.go
  app/auto_responder.go
  app/auto_responder_test.go
  app/notification.go
  app/status.go
  config/default.json
  model/config.go
  model/post.go
  model/status.go
  utils/config.go
Labels: 3: Ready to Merge

#8592 Websocket custom dialer support
  model/websocket_client.go
Labels: 3: Ready to Merge

#8610 MM-9977: test config.SetDefaults leaves nothing nil
  model/config.go
  model/config_test.go
  model/utils.go
  model/utils_test.go
Labels: 2: Dev Review

#8613 Fixed the example text on CLI channel command
  cmd/commands/channel.go
Labels: 2: Dev Review

#8622 MM-8792 (4.8) Remove query to update channel extra_update_at field on user activation/deactivation
  app/user.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Ready to Merge

#8603 Removing user cache clear from SessionHasPermissionsTo
  app/authorization.go
Labels: 2: Dev Review

#8623 Merge release-4.9 into master
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#8625 Removing user cache clear from SessionHasPermissionsTo
  app/authorization.go
Labels: 3: Ready to Merge

#8628 Prevent disabling or modifying l4g logging filters
  app/app.go
  utils/config.go
Labels: 3: Ready to Merge

#8635 MM-9918: Trim trailing / from push proxy URL.
  app/notification.go
Labels: 2: Dev Review

#8629 add app shutdown to make sure the goroutines finish and all process are closed
  app/user.go
  cmd/commands/channel.go
  cmd/commands/command.go
  cmd/commands/import.go
  cmd/commands/ldap.go
  cmd/commands/license.go
  cmd/commands/message_export.go
  cmd/commands/reset.go
  cmd/commands/roles.go
  cmd/commands/sampledata.go
  cmd/commands/team.go
  cmd/commands/user.go
Labels: 3: Ready to Merge

#8643 MM-10169 Handle app errors in user autocomplete endpoint
  api4/user.go
Labels: 2: Dev Review

#8644 Ignore rolled log files
  .gitignore
Labels: 2: Dev Review

#8604 MM-9779: Incorporate a Token into the invitations system
  api/team.go
  api/user.go
  api/user_test.go
  api4/team.go
  api4/team_test.go
  api4/user.go
  api4/user_test.go
  app/email.go
  app/team.go
  app/team_test.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/client.go
  model/client4.go
Labels: 2: Dev Review

#8645 MM-10133 Suppress confusing personal access token message in invalid session error
  app/session.go
Labels: 3: Ready to Merge

#8588 MM-10007 Send an admin and regular WS events when a user is updated
  app/apptestlib.go
  app/user.go
  app/web_conn.go
  app/web_conn_test.go
  model/user.go
  model/user_test.go
  model/utils.go
  model/utils_test.go
  model/websocket_message.go
Labels: 3: Ready to Merge

#8602 MM-10089 Properly implement session deep copy
  model/session.go
  model/session_test.go
Labels: 2: Dev Review

#8357 MM-8796: Full implementation of "Schemes" in Store/Model/App layers.
  api/apitestlib.go
  api4/apitestlib.go
  api4/channel_test.go
  api4/team_test.go
  app/authorization.go
  app/channel.go
  app/channel_test.go
  app/scheme.go
  app/team.go
  i18n/en.json
  model/channel.go
  model/channel_member.go
  model/cluster_message.go
  model/role.go
  model/scheme.go
  model/team.go
  model/team_member.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier.go
  store/local_cache_supplier_roles.go
  store/local_cache_supplier_schemes.go
  store/redis_supplier_roles.go
  store/redis_supplier_schemes.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/role_supplier.go
  store/sqlstore/scheme_store_test.go
  store/sqlstore/scheme_supplier.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/team_store.go
  store/sqlstore/team_store_test.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/RoleStore.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/role_store.go
  store/storetest/scheme_store.go
  store/storetest/store.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#8659 Revert "MM-9770: rewrite getParentsPosts to improve performance (#8467)"
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 3: Ready to Merge

#8292 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: 3: Ready to Merge

#8677 modestly extend SQLite support
  store/sqlstore/supplier.go
Labels: 3: Ready to Merge

#8682 MM-10375 Fixing connected socket count
  api4/system_test.go
  app/web_hub.go
Labels: 2: Dev Review

#8685 Fixing some merge conflicts with structured logging.
  i18n/en.json
  store/sqlstore/supplier.go
Labels: 3: Ready to Merge

#8684 [MM-10354] Add feature to remove team icon
  api4/team.go
  api4/team_test.go
  app/team.go
  i18n/en.json
  model/client4.go
  store/sqlstore/team_store.go
Labels: 2: Dev Review

#8662 translations PR 20180424
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#8675 Add missing diagnostics for 4.10
  app/diagnostics.go
Labels: 3: Ready to Merge

#8691 Add stdlib log level interpreter for structured logger
  mlog/log.go
  mlog/stdlog.go
  mlog/stdlog_test.go
Labels: 2: Dev Review

#8631 MM-9072/MM-10185 Force-convert the encoding of OpenGraph metadata to UTF-8
  Gopkg.lock
  app/post.go
  app/post_test.go
  vendor/golang.org/x/net/html/charset/charset.go
  vendor/golang.org/x/text/encoding/charmap/charmap.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/charmap/tables.go
  vendor/golang.org/x/text/encoding/encoding.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/htmlindex/htmlindex.go
  vendor/golang.org/x/text/encoding/htmlindex/map.go
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/identifier.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/internal/internal.go
  vendor/golang.org/x/text/encoding/japanese/all.go
  vendor/golang.org/x/text/encoding/japanese/eucjp.go
  vendor/golang.org/x/text/encoding/japanese/iso2022jp.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/japanese/shiftjis.go
  vendor/golang.org/x/text/encoding/japanese/tables.go
  vendor/golang.org/x/text/encoding/korean/euckr.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/korean/tables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/all.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/hzgb2312.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/tables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/big5.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/tables.go
  vendor/golang.org/x/text/encoding/unicode/override.go
  vendor/golang.org/x/text/encoding/unicode/unicode.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/runes/cond.go
  vendor/golang.org/x/text/runes/runes.go
Labels: 2: Dev Review

#8694 Merge 4.9 code into master
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#8651 Upgrading minio-go library to 6.0.0
  Gopkg.lock
  Gopkg.toml
  utils/file_backend_s3.go
  vendor/github.com/minio/minio-go/Makefile
  vendor/github.com/minio/minio-go/README.md
  vendor/github.com/minio/minio-go/README_zh_CN.md
  vendor/github.com/minio/minio-go/api-compose-object.go
  vendor/github.com/minio/minio-go/api-get-object-file.go
  vendor/github.com/minio/minio-go/api-get-object.go
  vendor/github.com/minio/minio-go/api-get-options.go
  vendor/github.com/minio/minio-go/api-get-policy.go
  vendor/github.com/minio/minio-go/api-notification.go
  vendor/github.com/minio/minio-go/api-presigned.go
  vendor/github.com/minio/minio-go/api-put-bucket.go
  vendor/github.com/minio/minio-go/api-put-object-context.go
  vendor/github.com/minio/minio-go/api-put-object-copy.go
  vendor/github.com/minio/minio-go/api-put-object-encrypted.go
  vendor/github.com/minio/minio-go/api-put-object-multipart.go
  vendor/github.com/minio/minio-go/api-put-object-streaming.go
  vendor/github.com/minio/minio-go/api-put-object.go
  vendor/github.com/minio/minio-go/api-remove.go
  vendor/github.com/minio/minio-go/api-stat.go
  vendor/github.com/minio/minio-go/api.go
  vendor/github.com/minio/minio-go/appveyor.yml
  vendor/github.com/minio/minio-go/bucket-cache.go
  vendor/github.com/minio/minio-go/bucket-notification.go
  vendor/github.com/minio/minio-go/constants.go
  vendor/github.com/minio/minio-go/core.go
  vendor/github.com/minio/minio-go/functional_tests.go
  vendor/github.com/minio/minio-go/pkg/encrypt/cbc.go
  vendor/github.com/minio/minio-go/pkg/encrypt/interface.go
  vendor/github.com/minio/minio-go/pkg/encrypt/keys.go
  vendor/github.com/minio/minio-go/pkg/encrypt/server-side.go
  vendor/github.com/minio/minio-go/pkg/policy/bucket-policy-condition.go
  vendor/github.com/minio/minio-go/pkg/policy/bucket-policy.go
  vendor/github.com/minio/minio-go/pkg/s3signer/request-signature-v2.go
  vendor/github.com/minio/minio-go/retry.go
  vendor/github.com/minio/minio-go/transport.go
  vendor/github.com/minio/minio-go/utils.go
  vendor/golang.org/x/crypto/argon2/argon2.go
  vendor/golang.org/x/crypto/argon2/blake2b.go
  vendor/golang.org/x/crypto/argon2/blamka_amd64.go
  vendor/golang.org/x/crypto/argon2/blamka_amd64.s
  vendor/golang.org/x/crypto/argon2/blamka_generic.go
  vendor/golang.org/x/crypto/argon2/blamka_ref.go
  vendor/golang.org/x/crypto/blake2b/blake2b.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.go
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_generic.go
  vendor/golang.org/x/crypto/blake2b/blake2b_ref.go
  vendor/golang.org/x/crypto/blake2b/blake2x.go
  vendor/golang.org/x/crypto/blake2b/register.go
Labels: 3: Ready to Merge
