Repository mattermost/mattermost, pull requests merged in 2018-03, with the labels that each got.

#8140 [PLT-8024] Support LOGIN authentication method for SMTP
  utils/mail.go
  utils/mail_test.go
Labels: 3: Ready to Merge

#8389 Fix linux cap header structure
  plugin/rpcplugin/sandbox/sandbox_linux.go
Labels: 2: Dev Review

#8284 PLT-7567: Integration of Team Icons
  api4/team.go
  api4/team_test.go
  app/team.go
  i18n/en.json
  model/client4.go
  model/team.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Ready to Merge

#8373 Remove `go Publish(...)` idiom
  api/post.go
  api/websocket_test.go
  app/channel.go
  app/command_expand_collapse.go
  app/emoji.go
  app/post.go
  app/preference.go
  app/status.go
  app/team.go
  app/user.go
  wsapi/user.go
  wsapi/webrtc.go
Labels: 3: Ready to Merge

#8395 fix Mozilla typo
  templates/unsupported_browser.html
Labels: 3: Ready to Merge

#8371 MM-8604: emit config/license websocket events
  api4/system.go
  app/app.go
  app/config.go
  app/config_test.go
  model/websocket_message.go
Labels: 3: Ready to Merge

#8340 MM-9664 Add invalidation metrics for store caches
  api/channel_test.go
  api4/channel_test.go
  app/admin.go
  app/session.go
  einterfaces/metrics.go
  store/sqlstore/channel_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/post_store.go
  store/sqlstore/user_store.go
  store/sqlstore/webhook_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/FileInfoStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/WebhookStore.go
Labels: 3: Ready to Merge

#8408 Add preparatory upgrade code for 4.9
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8409 Uncomment upgrade code to 4.8
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#7427 [PLT-7574] Update and Simplify Compatibility Check and Replace UA Dependency
  web/web.go
  web/web_test.go
Labels: 2: Dev Review, Setup Test Server

#8412 MM-9731: Register additional gob types to support arrays and dicts in post props
  plugin/rpcplugin/api.go
  plugin/rpcplugin/api_test.go
Labels: 3: Ready to Merge

#8400 [PLT-7776] Render at-mentions by the teammate name display
  app/channel.go
Labels: 3: Ready to Merge

#8335 MM-8830 Consistent Incomming/Outgoing webhooks permissions
  api4/webhook.go
Labels: 2: Dev Review

#8275 XYZ-87: GlobalRelay DM Exports do not Include Channel Name
  app/channel.go
  app/channel_test.go
  store/sqlstore/compliance_store.go
  store/storetest/compliance_store.go
Labels: 3: Ready to Merge

#8420 Readding uasurfer library
  glide.lock
  glide.yaml
  vendor/github.com/avct/uasurfer/.gitignore
  vendor/github.com/avct/uasurfer/.travis.yml
  vendor/github.com/avct/uasurfer/LICENSE
  vendor/github.com/avct/uasurfer/README.md
  vendor/github.com/avct/uasurfer/browser.go
  vendor/github.com/avct/uasurfer/const_string.go
  vendor/github.com/avct/uasurfer/device.go
  vendor/github.com/avct/uasurfer/system.go
  vendor/github.com/avct/uasurfer/uasurfer.go
  vendor/github.com/avct/uasurfer/uasurfer_test.go
Labels: 3: Ready to Merge

#8387 General cleanup
  api/context.go
  api4/apitestlib.go
  api4/webhook.go
  app/apptestlib.go
  app/authorization.go
  app/auto_constants.go
  app/auto_posts.go
  app/channel.go
  app/server.go
  app/slackimport.go
  app/user.go
  cmd/platform/sampledata.go
  jobs/testworker.go
  model/authorization.go
  model/channel.go
  model/cluster_info.go
  model/config.go
  model/emoji.go
  model/ldap.go
  model/manifest.go
  model/manifest_test.go
  model/oauth.go
  model/saml.go
  model/search_params.go
  model/team.go
  model/user.go
  model/utils.go
  model/version.go
  store/layered_store_supplier.go
  utils/config.go
  utils/i18n.go
  utils/log.go
  utils/logger/log4go_json_writer.go
  utils/logger/logger.go
  utils/mail.go
Labels: 2: Dev Review

#8414 translations PR 20180306
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8418 MM-9742: Plugin sandbox fixes
  plugin/rpcplugin/sandbox/sandbox_linux.go
Labels: 3: Ready to Merge

#8393 Respect plugin manifest webapp bundle_path
  model/manifest.go
  plugin/pluginenv/environment.go
Labels: 2: Dev Review

#8304 MM-8840: Add GlobalRelay Configuration Settings
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 3: Ready to Merge

#8410 Moved team icon upgrade code to 4.9 since it didn't make it in for 4.8
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8423 T-8 Merge Release-4.8 into master
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  plugin/rpcplugin/api.go
  plugin/rpcplugin/api_test.go
  plugin/rpcplugin/sandbox/sandbox_linux.go
Labels: 3: Ready to Merge

#8181 MM-9274- Sort Users in Channel by status
  api4/apitestlib.go
  api4/user.go
  api4/user_test.go
  app/apptestlib.go
  app/server_test.go
  app/status.go
  app/status_test.go
  app/user.go
  app/user_test.go
  model/client4.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Ready to Merge

#8415 MM-8729 Remove query to update channel extra_update_at field on user activation/deactivation
  app/user.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/TeamStore.go
Labels: 3: Ready to Merge

#8424 MM-8839: Adds ChannelType to compliance-related model.
  model/compliance_post.go
  model/message_export.go
  store/sqlstore/compliance_store.go
  store/storetest/compliance_store.go
Labels: 3: Ready to Merge

#8426 MM-9296 Stopped sending out of channel mention warnings for system messages
  app/notification.go
Labels: 3: Ready to Merge

#8406 using inbucket docker image tag release-1.2.0 instead of latest
  Makefile
  build/Jenkinsfile
Labels: 3: Ready to Merge

#8428 [MM-9725] Slack compatibility code in webhooks captures incorrect text
  app/webhook.go
  app/webhook_test.go
Labels: 3: Ready to Merge

#8422 [MM-9720] Platform command to change user email address
  cmd/commands/user.go
  cmd/commands/user_test.go
Labels: 3: Ready to Merge

#8441 Adding new global relay settings to diagnostics and default.json
  app/diagnostics.go
  config/default.json
Labels: 2: Dev Review

#8435 Fix saml users.json parameter
  cmd/platform/user.go
Labels: 3: Ready to Merge

#8449 Merge release-4.8 into master
  app/notification.go
  cmd/commands/user.go
  plugin/rpcplugin/sandbox/sandbox_linux.go
Labels: 3: Ready to Merge

#8361 MM-9624 Better error handling for failed plugin activation
  app/plugin.go
  app/plugin_test.go
Labels: 3: Ready to Merge

#8447 Fix: Unused mkdocs.yml in root directory #8431
  mkdocs.yml
Labels: 2: Dev Review

#8453 update email test in the driver to be able to send the config in the body
  api4/system_test.go
  model/client4.go
Labels: 2: Dev Review

#8433 MM-9688: Better error message for plugin enabling in HA mode
  app/plugin.go
  i18n/en.json
Labels: 2: Dev Review

#8454 remove s3 region to be mandatory and fix when user call test s3 when the config is saved
  api4/system.go
  api4/system_test.go
  utils/file_backend_s3.go
  utils/file_backend_s3_test.go
Labels: 3: Ready to Merge

#8440 MM-9795: Fix theme chooser for non-EE builds
  utils/config.go
Labels: 3: Ready to Merge

#8457 Merge release-4.8 into master
  utils/config.go
Labels: 2: Dev Review

#8458 translations PR 20180314
  i18n/de.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8460 MM-9847 Add content type to API error response
  utils/api.go
Labels: 3: Ready to Merge

#8452 Isolating configuration, sending emails and connection to SMTP.
  utils/mail.go
  utils/mail_test.go
Labels: 3: Ready to Merge

#8466 Merge release-4.8 into master
  i18n/de.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  utils/api.go
Labels: 2: Dev Review

#8479 translations PR 20180319
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#8480 MM-9679: Add config for saml home realm discovery bypass
  config/default.json
  model/config.go
Labels: 2: Dev Review

#8486 MM-9715 Update log message about plugin sandboxing
  app/plugin.go
Labels: 3: Ready to Merge

#8485 Fixed missing error in log message
  app/session.go
Labels: 3: Ready to Merge

#8484 Receive the email date as parameter
  utils/mail.go
Labels: 3: Ready to Merge

#8488 Fix paging for GET /teams and GET /teams/{id}/members endpoints
  api4/team.go
  api4/team_test.go
Labels: 3: Ready to Merge

#8448 Fix various segfaults when running `go test` manually
  api/file_test.go
  api/user_test.go
  api4/apitestlib.go
  api4/oauth.go
  api4/plugin_test.go
  app/app.go
  app/auto_posts.go
  app/import_test.go
  app/saml.go
  app/user.go
  utils/config.go
  utils/html.go
  utils/i18n.go
  utils/license.go
  web/web.go
Labels: 2: Dev Review

#8185 Timezone feature
  api4/system.go
  api4/system_test.go
  api4/user_test.go
  app/app.go
  app/timezone.go
  cmd/commands/config_flag_test.go
  config/default.json
  config/timezones.json
  i18n/en.json
  model/client4.go
  model/config.go
  model/timezone.go
  model/user.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  utils/config_test.go
  utils/timezone.go
Labels: 2: Dev Review

#8490 MM-9804: emit defaults for all enterprise config
  utils/config.go
  utils/config_test.go
Labels: 2: Dev Review

#8491 Improved bulkload error handling
  app/config.go
  app/import.go
  cmd/commands/import.go
Labels: 3: Ready to Merge

#8499 Allow to get the team icon for open teams
  api4/team.go
Labels: 3: Ready to Merge

#8496 MM-9843: improve semantics around Forward80To443
  app/server.go
  i18n/en.json
Labels: 2: Dev Review

#8494 Changing the user-0 data to sysadmin and user-1 username to user-1
  Makefile
  cmd/commands/sampledata.go
Labels: 3: Ready to Merge

#8500 MM-9792: Send websocket event when users are activated / deactivated
  app/user.go
Labels: 2: Dev Review

#8507 Ignore blank role names in getRolesByName call.
  api4/role.go
  api4/role_test.go
Labels: 2: Dev Review

#8510 MM-9946 Adding go client support and basic unit tests for channel autocomplete.
  api4/channel_test.go
  model/client4.go
Labels: 2: Dev Review

#8478 Relax 4k post message limit
  api4/system.go
  app/app.go
  app/config.go
  app/config_test.go
  app/import.go
  app/import_test.go
  app/post.go
  app/post_test.go
  app/webhook.go
  app/webhook_test.go
  i18n/en.json
  model/post.go
  model/post_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Ready to Merge

#8516 Fix System wide oauth typo
  model/permission.go
Labels: 2: Dev Review

#8501 [GH-7775] Post a system message after a channel is converted from public to private
  api4/channel.go
  app/channel.go
  i18n/en.json
  model/post.go
Labels: 3: Ready to Merge

#8523 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#8521 fix typo in the pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Ready to Merge

#7713 [PLT-4340] Channel Mute and "/mute" command #7617
  api/command_mute_test.go
  app/channel.go
  app/command_mute.go
  app/notification.go
  app/notification_test.go
  i18n/en.json
  model/websocket_message.go
Labels: 3: Ready to Merge, Hacktoberfest

#8514 translations PR 20180326
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, Localization

#8532 Fix roles table ID max length so MySQL 5.6 doesn't fail.
  store/sqlstore/role_supplier.go
Labels: 2: Dev Review

#8531 Add SAML scoping IDP settings to diagnostics.go
  app/diagnostics.go
Labels: 3: Ready to Merge

#8520 Add unit test coverage for SqlStatusStore.GetAllFromTeam
  store/storetest/status_store.go
Labels: 2: Dev Review

#8530 Remove the index on Channels.DisplayName (master/v4.9)
  model/version.go
  store/sqlstore/channel_store.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#8537 Revert "add individual platform packaging targets (#8366)"
  Makefile
  build/release.mk
Labels: 2: Dev Review

#8560 Initialize timezone to a default state
  model/user.go
  model/user_test.go
Labels: 3: Ready to Merge
