Repository mattermost/mattermost, pull requests merged in 2018-07, with the labels that each got.

#9029 Add note on 5.0->4.10 downgrade in upgrade.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#9038 translations PR 20180702
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#9030 Adding RootId information to MessageExport
  model/message_export.go
  store/sqlstore/compliance_store.go
Labels: 3: Ready to Merge

#9032 Make sure diagnostic ID is loaded before client config.
  app/app.go
  cmd/mattermost/commands/server.go
Labels: 3: Ready to Merge, Awaiting Submitter Action

#9040 Uncomment upgrade for 5.1.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#9034 MM-11029 Adding plugin logging functionality.
  app/plugin_api.go
  mlog/global.go
  mlog/log.go
  mlog/stdlog.go
  mlog/sugar.go
  plugin/api.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/hclog_adapter.go
  plugin/interface_generator/main.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
  plugin/supervisor.go
Labels: 2: Dev Review

#9054 MM-11118: disallow deleting direct or group channels
  api4/channel.go
  api4/channel_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8955 MM-10766 - Replacing default profile image font
  app/user.go
  app/user_test.go
  config/default.json
  fonts/OFL.txt
  fonts/luximbi.ttf
  fonts/nunito-bold.ttf
  model/config.go
Labels: 3: Ready to Merge

#9052 MM-11125 Add back enable/disable WS events
  app/plugin.go
  app/plugin_install.go
  model/websocket_message.go
Labels: 2: Dev Review

#9051 MM-11106: Allow systeadmin webook to post to read only town square.
  app/webhook.go
  web/web_test.go
  web/webhook_test.go
Labels: 2: Dev Review

#9056 Release 5.1 daily merge 20180706
  api4/channel.go
  api4/channel_test.go
  app/user.go
  app/user_test.go
  app/webhook.go
  config/default.json
  fonts/OFL.txt
  fonts/luximbi.ttf
  fonts/nunito-bold.ttf
  i18n/en.json
  model/config.go
  web/web_test.go
  web/webhook_test.go
Labels: 3: Ready to Merge

#9043 MM-10703 Adding blank request context to plugin hooks for future use.
  Makefile
  app/plugin_commands.go
  app/plugin_requests.go
  app/plugin_test.go
  app/post.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/mock_api_test.go
  plugin/plugintest/hooks.go
  plugin/request_context.go
  plugin/supervisor_test.go
  web/context.go
Labels: 3: Ready to Merge

#9050 [MM-10754] Remove unnecessary command_test route
  api4/command.go
  api4/command_test.go
Labels: 3: Ready to Merge

#9022 Implementation of additional Plugin API Methods
  api4/channel_test.go
  app/channel.go
  app/plugin_api.go
  app/team.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/mock_api_test.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
Labels: 2: Dev Review

#9060 Blacklist System as Username
  model/user.go
  model/user_test.go
Labels: 2: Dev Review

#9062 MM-11110: Fixes CLI error message.
  cmd/mattermost/commands/channel.go
Labels: 3: Ready to Merge

#9061 Update custom url schemes error message to reflect what we actually support
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 3: Ready to Merge

#9063 MM-11120 Adding setting to disable email invitations and rate limiting.
  api4/team_test.go
  app/app.go
  app/command_invite_people.go
  app/email.go
  app/team.go
  cmd/mattermost/commands/user.go
  config/default.json
  i18n/en.json
  model/config.go
  utils/config.go
Labels: 3: Ready to Merge

#9070 MM-11227: Fix group msg slash command.
  app/channel.go
  app/command_groupmsg.go
  app/command_groupmsg_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9071 MM-11189: Do not close the connection abruptly on too big emojis
  api4/emoji.go
Labels: 2: Dev Review

#9073 MM-11228: Fix channel update/patch API endpoints.
  api4/channel.go
  api4/channel_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9074 MM-11229: Fix invite people slash command and add test case.
  app/command_invite_people.go
  app/command_invite_people_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9082 translations PR 20180709
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#9084 fix TestInvitePeopleProvider test
  app/command_invite_people_test.go
Labels: 3: Ready to Merge

#9086 Don't panic if plugin manifest does not have settings
  app/plugin_api.go
Labels: 2: Dev Review

#9047 Add preparatory upgrade code for 5.2.0
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#9088 Release 5.1 daily merge 20180710
  api4/channel.go
  api4/channel_test.go
  api4/emoji.go
  api4/team_test.go
  app/app.go
  app/apptestlib.go
  app/channel.go
  app/command_channel_header.go
  app/command_channel_header_test.go
  app/command_groupmsg.go
  app/command_groupmsg_test.go
  app/command_invite_people.go
  app/command_invite_people_test.go
  app/command_msg.go
  app/command_msg_test.go
  app/email.go
  app/team.go
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/user.go
  config/default.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  model/config.go
  model/config_test.go
  utils/config.go
Labels: 2: Dev Review

#9079 MM-11241: fix context site url header
  web/handlers.go
  web/saml.go
Labels: 3: Ready to Merge

#9085 Restore config after finisht the test case
  api4/commands_test.go
  api4/image_test.go
  api4/oauth_test.go
  api4/post_test.go
  api4/team_test.go
  api4/user_test.go
Labels: 3: Ready to Merge

#9049 push notifications follow teammate name display user or server setting
  app/notification.go
  model/user.go
Labels: 3: Ready to Merge

#9095 Deduplicating some code in app/status.go
  app/status.go
Labels: 3: Ready to Merge

#8745 [MM-10117] Add support to add/delete and enable/disable plugins via CLI
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  tests/test-config.json
Labels: 3: Ready to Merge

#9099 translations PR 20180711
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#9044 [MM-10830] Enhance Log Output from Permanent Delete
  app/user.go
Labels: 2: Dev Review

#9105 Add telemetry for ServiceSettings.EnableEmailInvitations
  app/diagnostics.go
Labels: 2: Dev Review

#9076 MM-11229: Backport to 4.10
  app/command_invite_people.go
  app/command_invite_people_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9075 MM-11229: Backport to 5.0
  app/command_invite_people.go
  app/command_invite_people_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9107 Release 5.1 daily merge 20180712
  api4/commands_test.go
  api4/image_test.go
  api4/oauth_test.go
  api4/post_test.go
  api4/team_test.go
  api4/user_test.go
  app/notification.go
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  model/user.go
  web/handlers.go
  web/saml.go
Labels: 2: Dev Review

#9102 Update privacy policy for v5.1
  build/PRIVACY_POLICY.md
Labels: 3: Ready to Merge

#9109 MM-11292: clean up plugins GoDoc
  app/plugin_commands.go
  app/plugin_install.go
  app/plugin_requests.go
  plugin/api.go
  plugin/client.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/context.go
  plugin/doc.go
  plugin/environment.go
  plugin/example_hello_world_test.go
  plugin/example_help_test.go
  plugin/hclog_adapter.go
  plugin/hooks.go
  plugin/http.go
  plugin/interface_generator/main.go
  plugin/io_rpc.go
  plugin/supervisor.go
  plugin/supervisor_test.go
  plugin/valid.go
Labels: 3: Ready to Merge

#8674 Add localized timestamp support for email notification
  app/notification.go
  app/notification_test.go
  model/user.go
Labels: 2: Dev Review

#9113 Release 5.1 daily merge 20180716
  build/PRIVACY_POLICY.md
Labels: 2: Dev Review

#9106 MM-11172: Don't allow reacting in read-only town square.
  api4/reaction_test.go
  app/reaction.go
  i18n/en.json
Labels: 2: Dev Review

#9114 add pre-package plugins to the MM package
  Makefile
  build/release.mk
Labels: 3: Ready to Merge

#9112 Merge consecutive text nodes when inspecting markdown
  utils/markdown/inlines.go
  utils/markdown/inspect.go
  utils/markdown/text_range_test.go
Labels: 3: Ready to Merge

#9101 MM-10254 Add plugin APIs for getting/updating user statuses
  api4/post.go
  api4/status.go
  api4/status_test.go
  api4/user_test.go
  api4/websocket_test.go
  app/apptestlib.go
  app/auto_responder.go
  app/auto_responder_test.go
  app/command_dnd.go
  app/command_online.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/status.go
  app/web_conn.go
  app/websocket_router.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/mock_api_test.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
Labels: 3: Ready to Merge

#9117 MM-11224 Make plugin IDs case insensitive
  api4/plugin_test.go
  app/plugin.go
  model/manifest.go
  model/manifest_test.go
Labels: 3: Ready to Merge

#9121 MM-11366: support a plugin bundle with multiple executables
  model/manifest.go
  model/manifest_test.go
  plugin/supervisor.go
Labels: 2: Dev Review

#9083 Do not close the connection abruptly on too big file uploads
  api4/brand.go
  api4/file.go
  api4/team.go
  api4/user.go
Labels: 2: Dev Review

#9094 MM-10699 Add channel renaming to CLI
  app/channel.go
  app/channel_test.go
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/channel_test.go
  tests/test-config.json
Labels: 3: Ready to Merge

#9123 translations PR 20180718
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#9129 Support for Embeded chat
  app/extension.go
  config/default.json
  i18n/en.json
  model/config.go
  model/oauth.go
  templates/complete_saml_extension_body.html
  web/saml.go
Labels: 3: Ready to Merge

#9128 MM-11349 Lock go-hclog and go-plugin dependencies to a revision
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/hashicorp/yamux/session.go
Labels: 2: Dev Review

#9127 Support `server`, deprecate `backend` in plugin manifest
  app/diagnostics.go
  model/manifest.go
  model/manifest_test.go
  model/plugins_response_test.go
  plugin/environment.go
Labels: 2: Dev Review

#9103 MM-11028 Adding some plugin tests.
  Makefile
  app/plugin_api_test.go
  app/plugin_hooks_test.go
  plugin/mock_api_test.go
  plugin/supervisor_test.go
Labels: 2: Dev Review

#9126 Fix invalid markdown text ranges
  utils/markdown/inlines.go
  utils/markdown/text_range_test.go
Labels: 2: Dev Review

#9125 MM-11389 Added diagnostics for FileSettings.Directory
  app/diagnostics.go
  model/config.go
Labels: 3: Ready to Merge

#9133 Temporarily comment out until MM-11108 to fix builds
  app/app_test.go
Labels: 3: Ready to Merge

#9131 Add missed plugin error translation
  app/plugin_statuses.go
  i18n/en.json
Labels: 2: Dev Review

#9124 Support attachments in post and replies - Bulk import
  app/import.go
  app/import_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9130 Using idiomatic error handling in channel store
  store/sqlstore/channel_store.go
Labels: 3: Ready to Merge

#9136 MM-11003: Global Relay Export Refactor
  cmd/mattermost/commands/message_export.go
  i18n/en.json
Labels: 3: Ready to Merge

#9134 make GetChannelByName take teamId first
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
Labels: 2: Dev Review

#8903 Break HTML blocks to individual strings
  app/email.go
  app/notification.go
  app/session.go
  i18n/en.json
  templates/deactivate_body.html
  templates/email_change_body.html
  templates/email_info.html
  templates/invite_body.html
  templates/mfa_change_body.html
  templates/password_change_body.html
  templates/post_body_full.html
  templates/reset_body.html
  templates/signin_change_body.html
  utils/html.go
  utils/html_test.go
Labels: 3: Ready to Merge

#9151 MM-11451 Added autolinking to Markdown parser
  utils/markdown/autolink.go
  utils/markdown/autolink_test.go
  utils/markdown/commonmark_test.go
  utils/markdown/html.go
  utils/markdown/inlines.go
  utils/markdown/markdown.go
Labels: 2: Dev Review

#9144 MM-10381: Change the file downloading API to stream file
  api4/file.go
  app/file.go
Labels: 2: Dev Review

#9148 fix plugin example docs
  plugin/example_hello_world_test.go
Labels: 3: Ready to Merge

#9141 added the custom icon and username for the outgoing webhook and its response
  api4/webhook_test.go
  app/webhook.go
  app/webhook_test.go
  i18n/en.json
  model/outgoing_webhook.go
  model/outgoing_webhook_test.go
  store/sqlstore/upgrade.go
  store/sqlstore/webhook_store.go
  store/storetest/webhook_store.go
Labels: 3: Ready to Merge

#9161 Fix plugin.ServeHTTP subpath
  app/plugin_requests.go
  app/plugin_test.go
Labels: 3: Ready to Merge

#9149 unpack prepacked plugins on plugins initialization
  api4/plugin.go
  app/plugin.go
  app/plugin_install.go
  cmd/mattermost/commands/plugin.go
  i18n/en.json
Labels: 3: Ready to Merge

#9146 MM-11243: Make Elasticsearch work after enabling without restart.
  app/app.go
  cmd/mattermost/commands/server.go
  einterfaces/elasticsearch.go
  i18n/en.json
Labels: 2: Dev Review

#9152 MM-11160 Adding proper CORS support.
  Gopkg.lock
  api4/apitestlib.go
  api4/cors_test.go
  app/server.go
  config/default.json
  model/config.go
  vendor/github.com/rs/cors/.travis.yml
  vendor/github.com/rs/cors/LICENSE
  vendor/github.com/rs/cors/README.md
  vendor/github.com/rs/cors/cors.go
  vendor/github.com/rs/cors/go.mod
  vendor/github.com/rs/cors/utils.go
Labels: 2: Dev Review

#9168 Fix file streaming to close files.
  api4/file.go
  app/file.go
  utils/file_backend_s3.go
Labels: 2: Dev Review

#9171 MM-11425: s/mlog/log/ in apiRPCClient
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/interface_generator/main.go
Labels: 2: Dev Review

#9167 MM-11431: handle plugin deadlocks
  app/plugin_deadlock_test.go
  app/plugin_hooks_test.go
  plugin/environment.go
  plugin/hooks.go
  plugin/supervisor.go
Labels: 3: Ready to Merge

#9176 Fix compile error caused by bad merge
  plugin/client_rpc.go
Labels: 2: Dev Review

#9178 MM-11393 Implement OAuth2 implicit grant flow
  api4/oauth.go
  api4/oauth_test.go
  app/oauth.go
  app/oauth_test.go
  model/authorize.go
  model/oauth.go
Labels: 2: Dev Review

#9164 Split notifications file into different files
  app/notification.go
  app/notification_email.go
  app/notification_email_test.go
  app/notification_push.go
  app/notification_push_test.go
  app/notification_test.go
Labels: 3: Ready to Merge

#9177 [MM-11464] Implement Plugin Login Hooks (closes #9157)
  app/login.go
  app/plugin_hooks_test.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/plugintest/hooks.go
Labels: 2: Dev Review

#9138 MM-11301: Validates listen address config value.
  model/config.go
  model/config_test.go
  model/utils.go
Labels: 2: Dev Review

#9187 Pr 9039
  api4/apitestlib.go
  api4/channel.go
  api4/channel_test.go
  api4/post.go
  api4/post_test.go
  api4/reaction_test.go
  app/authorization.go
  app/channel.go
  app/channel_test.go
  app/command_invite.go
  app/import.go
  app/import_test.go
  app/plugin_api.go
  app/post.go
  app/team.go
  app/user.go
  app/web_conn.go
  config/default.json
  manualtesting/manual_testing.go
  model/client4.go
  model/config.go
  model/search_params.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/example_help_test.go
  plugin/plugintest/api.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
  utils/config.go
Labels: 3: Ready to Merge

#9190 Save OAuth access token to DB for consistency with other flows
  app/oauth.go
Labels: 3: Ready to Merge

#9194 Add OAuth2 login hint for SAML
  api4/oauth.go
Labels: 2: Dev Review

#9182 gob register AppError for plugins
  plugin/client_rpc.go
Labels: 3: Ready to Merge

#9174 MM-10502: Only cluster master should run job schedulers.
  app/app.go
  app/cluster.go
  jobs/schedulers.go
  jobs/server.go
Labels: 2: Dev Review

#9184 Adding support for code split plugins.
  model/manifest.go
  plugin/environment.go
  web/static.go
Labels: 2: Dev Review

#9195 Migrate notification_push_test to table testing
  app/notification_push_test.go
Labels: 3: Ready to Merge

#9172 MM-11420: plugins: compute bundle hash on load
  app/plugin.go
  model/manifest.go
  model/manifest_test.go
  plugin/environment.go
  web/static.go
Labels: 3: Ready to Merge
