Repository mattermost/mattermost, pull requests merged in 2018-10, with the labels that each got.

#9488 #MM-12130 - Fix incorrect key in en.json and changes some translations from service terms to terms of service
  i18n/en.json
  model/service_terms.go
Labels: 3: Ready to Merge

#9494 MM-12110: Don't /invite or /kick deactivated users.
  app/command_invite.go
  app/command_invite_test.go
  app/command_remove.go
  app/command_remove_test.go
  i18n/en.json
Labels: 2: Dev Review

#9516 fix gofmt for go 1.11
  app/diagnostics.go
  model/command_response_test.go
  store/sqlstore/channel_store_experimental.go
  utils/markdown/html_entities.go
  web/handlers_test.go
Labels: 2: Dev Review

#9461 [MM-12264] if EnableLinkPreviews not enabled, do not execute function
  api4/system.go
  api4/system_test.go
Labels: 3: Ready to Merge

#9449 MM-12067: Add SetDefaultProfileImage to reset the user profile image to a generated one
  api4/user.go
  api4/user_test.go
  app/user.go
  app/user_test.go
  model/client4.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
Labels: 3: Ready to Merge

#9518 MM-10699: Disallow renaming direct and group message channels
  app/channel.go
  app/channel_test.go
  cmd/mattermost/commands/channel.go
  i18n/en.json
Labels: 3: Ready to Merge

#9512 [MM-12367] Added CLI command 'team search'
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
Labels: 3: Ready to Merge

#9520 translations PR 20181001
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#9519 MM-12193: remove auto unmarshalling
  app/plugin_api_test.go
  plugin/client.go
  plugin/client_rpc.go
  plugin/example_hello_world_test.go
  plugin/example_help_test.go
  plugin/hooks.go
Labels: 3: Ready to Merge

#9482 Set a proper HTTP user-agent header
  app/post.go
  services/httpservice/client.go
  services/httpservice/client_test.go
  services/httpservice/httpservice.go
  utils/testutils/mocked_http_service.go
Labels: 2: Dev Review

#9547 [GH-9486] Fix CMD Initilization Error Checks
  cmd/mattermost/commands/init.go
Labels: 2: Dev Review, Hacktoberfest

#9467 MM-11863 Add KVList method
  app/plugin_api.go
  app/plugin_key_value_store.go
  app/plugin_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
Labels: 2: Dev Review, Hacktoberfest

#9525 Add GetChannelMembers method to the plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9521 Move CustomServiceTermsEnabled to the correct table in diagnostics
  app/diagnostics.go
Labels: 3: Ready to Merge

#9554 Added missed translations
  i18n/en.json
Labels: 2: Dev Review

#9528 MM-12371 Add webhook list command
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 1: PM Review, 2: Dev Review, Hacktoberfest

#9531 MM-12357: Add CLI command "team list"
  cmd/mattermost/commands/command.go
Labels: 1: PM Review, 2: Dev Review, Hacktoberfest

#9567 Small fix in the webhook list error handling
  cmd/mattermost/commands/webhook.go
Labels: 3: Ready to Merge

#9515 MM-12251: Add flag to MoveChannel to remove all deactivated users.
  app/channel.go
  app/channel_test.go
  cmd/mattermost/commands/channel.go
  i18n/en.json
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Ready to Merge, CherryPickApproved

#9578 MM-8860: Bulk import email intervals (#8498)
  app/import_functions.go
  app/import_functions_test.go
  app/import_types.go
  app/import_validators.go
  app/import_validators_test.go
  model/preference.go
  model/user.go
Labels: 3: Ready to Merge, Hacktoberfest

#9581 Refactored to rename "service terms" to "terms of service"
  api4/api.go
  api4/service_terms.go
  api4/service_terms_test.go
  api4/terms_of_service.go
  api4/terms_of_service_test.go
  api4/user.go
  api4/user_test.go
  app/config.go
  app/diagnostics.go
  app/service_terms.go
  app/terms_of_service.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/service_terms.go
  model/terms_of_service.go
  model/terms_of_service_test.go
  model/user.go
  store/layered_store.go
  store/sqlstore/service_terms_store.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/terms_of_service_store.go
  store/sqlstore/terms_of_service_store_test.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TermsOfServiceStore.go
  store/storetest/service_terms_store.go
  store/storetest/store.go
  store/storetest/terms_of_service_store.go
  utils/config.go
Labels: 1: PM Review, 2: Dev Review, CherryPickCandidate

#9602 translations PR 20181009
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#9431 [MM-11864/MM-11865] Entries with Expiry / Delete All Keys for Plugin KV Store
  app/plugin.go
  app/plugin_api.go
  app/plugin_key_value_store.go
  jobs/interfaces/plugins_interface.go
  jobs/schedulers.go
  jobs/server.go
  jobs/workers.go
  model/job.go
  model/plugin_key_value.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  plugin/scheduler/plugin.go
  plugin/scheduler/scheduler.go
  plugin/scheduler/worker.go
  store/sqlstore/plugin_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 2: Dev Review, Hacktoberfest

#9601 MM-11905: delete plugin commands on removal
  app/plugin_commands_test.go
  app/plugin_hooks_test.go
  app/plugin_install.go
Labels: 2: Dev Review, CherryPickApproved

#9286 [APIv4] add getChannelMembersTimezone
  api4/channel.go
  api4/channel_test.go
  app/channel.go
  app/channel_test.go
  i18n/en.json
  model/client4.go
  model/user.go
  model/utils.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Ready to Merge

#9569 MM-12355: Add CLI command "command create"
  cmd/mattermost/commands/command.go
  cmd/mattermost/commands/command_test.go
Labels: 2: Dev Review, Hacktoberfest

#9587 [MM-12607] Migrate to idiomatic error handling in the file `app/saml…
  app/saml.go
Labels: 2: Dev Review, Hacktoberfest

#9593 [MM-12606] Migrate to idiomatic error handling in the file `app/role.…
  app/role.go
Labels: 2: Dev Review, Hacktoberfest

#9625 MM-12419: Flush channels from cache when deleted/restored.
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_experimental.go
Labels: 3: Ready to Merge, CherryPickApproved

#9652 GH-9629: Add GetPostThread() to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9649 GH-9632: Add GetPostsSince() to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9552 Add a delete brand image action on the APIv4
  api4/brand.go
  api4/brand_test.go
  app/brand.go
  model/client4.go
Labels: Hacktoberfest

#9558 [MM-12360] Created CLI command "config get" (#9534)
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 1: PM Review, 2: Dev Review, Hacktoberfest

#9646 GH-9606: Add GetChannelsForTeamForUser to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review, Hacktoberfest

#9651 GH-9631: Add GetPostsBefore() to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9658 Added TextArea (longstring) to the docs in manifest to be rendered in the documentation
  model/manifest.go
Labels: 3: Ready to Merge

#9565 [MM-12363] Added Team archive command to archive a team by name
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
Labels: Hacktoberfest

#9576 [MM-12536] Migrate to idiomatic error handling the file `app/user_age…
  app/user_agent.go
Labels: Hacktoberfest

#9590 [MM-12538] Migrate to idiomatic error handling the file `app/session.go`
  app/session.go
Labels: Hacktoberfest

#9666 MM-11905: deactivate plugins before unregistering
  app/plugin_install.go
Labels: 2: Dev Review, CherryPickApproved

#9641 Add GetEmojiByName method to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review, Hacktoberfest

#9564 [MM-12362] Add CLI command 'config show'
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 3: Ready to Merge, Hacktoberfest

#9566 MM-12368 Add create webhook-incoming command
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 3: Ready to Merge, Hacktoberfest

#9315 [MM-10861/10418] Allow configuration of TLS Version/Ciphers/Curves and HSTS via Config File [WIP]
  app/server.go
  app/server_test.go
  config/default.json
  i18n/en.json
  model/config.go
  tests/tls_test_cert.pem
  tests/tls_test_key.pem
  web/handlers.go
  web/handlers_test.go
Labels: 3: Ready to Merge

#9676 Migrate to idiomatic error handling in app/notification_email.go
  app/notification_email.go
Labels: 3: Ready to Merge, Hacktoberfest

#9616 Document minimum server version for plugin API methods
  plugin/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9644 GH-9607: Add GetTeamsForUser to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9643 GH-9608: Add GetUsersInChannel to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9665 Add GetFileLink method to plugin API
  app/plugin_api.go
  i18n/en.json
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review, Hacktoberfest

#9647 GH-9635: Add GetUsersByUsernames to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9689 MM-12670: Accept and use "" for user/pass AuthService in import/export.
  app/export_converters.go
  app/import_validators.go
  app/import_validators_test.go
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#9691 GH-9687: Migrate to idiomatic error handling in app/security_update_check.go
  app/security_update_check.go
Labels: 2: Dev Review, Hacktoberfest

#9708 GH-9703: Migrate to idiomatic error handling in app/websocket_router.go
  app/websocket_router.go
Labels: Hacktoberfest

#9650 GH-9630: Add GetPostsAfter() to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9594 GH-9583: Migrate to idiomatic error handling in app/preference.go
  app/preference.go
Labels: 3: Ready to Merge, Hacktoberfest

#9700 MM-12505: remove all things WebRTC
  api4/api.go
  api4/webrtc.go
  api4/webrtc_test.go
  app/diagnostics.go
  app/diagnostics_test.go
  app/session.go
  app/webrtc.go
  config/default.json
  i18n/en.json
  model/client4.go
  model/config.go
  model/license.go
  model/webrtc.go
  model/webrtc_test.go
  model/websocket_message.go
  tests/test-config.json
  utils/config.go
  wsapi/api.go
  wsapi/webrtc.go
Labels: 3: Ready to Merge, Tests: Not Needed

#9628 GH-9619 GetEmojiImage added to plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: Hacktoberfest

#9683 MM-12372 Add modify-incoming webhook command
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 2: Dev Review, Hacktoberfest

#9709 GH-9705: Migrate to idiomatic error handling in app/web_conn.go
  app/web_conn.go
Labels: Hacktoberfest

#9697 GH-9688: Migrate to idiomatic error handling in app/post.go
  app/post.go
Labels: Hacktoberfest

#9711 GH-9706: Migrate to idiomatic error handling in app/user.go
  app/user.go
Labels: Hacktoberfest

#9694 Migrate to idiomatic error handling in app/slackimport.go
  app/slackimport.go
Labels: 2: Dev Review, Hacktoberfest

#9553 MM-12356 Add cli command "command delete"
  app/command.go
  cmd/mattermost/commands/command.go
  cmd/mattermost/commands/command_test.go
Labels: Hacktoberfest

#9725 MM-12781 Fix display of timestamp on generic email. This is a regression.
  templates/post_body_generic.html
Labels: 2: Dev Review, CherryPickApproved

#9693 MM-11868/MM-12010/MM-12011/MM-12036 Improve post metadata structure
  app/post_metadata.go
  app/post_metadata_test.go
  model/post.go
  model/post_embed.go
  model/post_metadata.go
Labels: 3: Ready to Merge

#9696 MM-10987 Turn on ExperimentalLimitClientConfig by default and remove setting
  api4/system.go
  api4/system_test.go
  app/diagnostics.go
  config/default.json
  model/config.go
  tests/test-config.json
Labels: 3: Ready to Merge

#9724 MM-12459 Include User Notify Props in the Bulk Export
  app/export.go
  app/export_test.go
  model/user.go
Labels: 2: Dev Review, Hacktoberfest

#9656 GH-9617 Add plugin API for GetEmoji method
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: Hacktoberfest

#9738 Update Twitter Handle in Readme
  README.md
Labels: 3: Ready to Merge, Hacktoberfest

#9582 [MM-12361] Create CLI-command "config set" (#9535)
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: Hacktoberfest

#9701 GH-9685: Migrate to idiomatic error handling in app/team.go
  app/team.go
Labels: 2: Dev Review, Hacktoberfest

#9756 fix panic in TestUpdateUserAuth test
  api4/user_test.go
Labels: 2: Dev Review

#9754 MM-12768 Fixing race in plugin ServeHTTP
  plugin/client_rpc.go
Labels: 2: Dev Review

#9742 Fix for OOO bug that reply message does not get inserted consistently.
  app/auto_responder.go
  app/auto_responder_test.go
  app/notification.go
Labels: 2: Dev Review, Tests: Done

#9751 MM-12815: Clearly deprecated disused config settings.
  api4/command_test.go
  app/app.go
  app/app_test.go
  app/diagnostics.go
  cmd/mattermost/commands/test.go
  model/config.go
  utils/authorization.go
  utils/authorization_test.go
  utils/config.go
Labels: 3: Ready to Merge, Awaiting PR

#9774 [MM-12214] enable push notifications to use TPNS by default
  config/default.json
Labels: 3: Ready to Merge

#9753 translations PR 20181029
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#9664 GH-9611: Add GetChannelMembersByIds to Plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, Hacktoberfest

#9773 [MM-12461] Include the per-channel NotifyProps for Users in Bulk Export
  app/export_converters.go
  app/export_test.go
Labels: 2: Dev Review
