Repository mattermost/mattermost, pull requests merged in 2018-05, with the labels that each got.

#8696 translations PR 20180430
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#8692 MM-8622: improved plugin error handling
  app/plugin.go
  i18n/en.json
  mlog/log.go
  model/manifest.go
  plugin/pluginenv/environment.go
  plugin/pluginenv/environment_test.go
  plugin/rpcplugin/hooks.go
  plugin/rpcplugin/hooks_test.go
  plugin/rpcplugin/main.go
  plugin/rpcplugin/main_test.go
  plugin/rpcplugin/rpcplugintest/supervisor.go
  plugin/rpcplugin/sandbox/main_test.go
  plugin/rpcplugin/supervisor.go
  plugin/valid.go
  plugin/valid_test.go
Labels: 2: Dev Review

#8680 MM-10182 & MM-10183: Adds channel scheme and team scheme API endpoint.
  api4/channel.go
  api4/channel_test.go
  api4/team.go
  api4/team_test.go
  app/channel.go
  app/channel_test.go
  app/team.go
  app/team_test.go
  i18n/en.json
  model/client4.go
  model/scheme.go
Labels: 2: Dev Review, Awaiting PR

#8701 [MM-10415] Reorder checks for command invite
  app/command_invite.go
Labels: 3: Ready to Merge

#8695 MM-10628 Add inactive user count to analytics and fix client analytics function
  api4/system_test.go
  app/analytics.go
  model/client4.go
Labels: 3: Ready to Merge

#8615 MM-10140: API Implementation for Schemes related Endpoints
  api4/api.go
  api4/context.go
  api4/params.go
  api4/scheme.go
  api4/scheme_test.go
  app/scheme.go
  i18n/en.json
  model/client4.go
  model/scheme.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_schemes.go
  store/redis_supplier_schemes.go
  store/sqlstore/channel_store.go
  store/sqlstore/scheme_supplier.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/scheme_store.go
Labels: 2: Dev Review

#8712 Fix TestSendNotifications test
  app/notification_test.go
  utils/utils.go
Labels: 2: Dev Review

#8705 MM-10189 Fixed inconsistency when using environment variables for MessageExportSettings
  utils/config.go
  utils/config_test.go
Labels: 3: Ready to Merge

#8706 MM-10393: Fix for tracking active vs inactive users.
  app/diagnostics.go
Labels: 3: Ready to Merge

#8710 [MM-10200] Respect image orientation before saving height and width of FileInfo
  app/file.go
Labels: 3: Ready to Merge

#8721 Removes .vscode dir.
  .vscode/launch.json
Labels: 2: Dev Review

#8723 [MM-10433] Update permission of converting a channel from public to private to allow team admin
  api4/channel.go
  api4/channel_test.go
Labels: 3: Ready to Merge

#8711 MM-10319: Use normalized email for Saml (migration)
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#8700 Added missing i18n strings for files and email batching
  app/email_batching.go
  app/file.go
Labels: 3: Ready to Merge

#8728 Add IncrementClusterEventType function to metrics interface
  einterfaces/metrics.go
Labels: 2: Dev Review

#8724 Fix empty GOPATH behaviour in Makefile
  Makefile
Labels: 3: Ready to Merge

#8748 MM-10495 Updated user agent detection to match output of previous library
  app/login.go
  app/user_agent.go
  app/user_agent_test.go
Labels: 3: Ready to Merge

#8756 MM-4998 Adding LoginIdAttribute to allow LDAP users to change their login ID without losing their account
  Makefile
  api/user.go
  api4/user.go
  app/ldap.go
  app/login.go
  app/user.go
  cmd/commands/ldap.go
  config/default.json
  einterfaces/ldap.go
  i18n/en.json
  mlog/log.go
  model/config.go
  model/switch_request.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/AuditStore.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ClusterDiscoveryStore.go
  store/storetest/mocks/CommandStore.go
  store/storetest/mocks/CommandWebhookStore.go
  store/storetest/mocks/ComplianceStore.go
  store/storetest/mocks/EmojiStore.go
  store/storetest/mocks/FileInfoStore.go
  store/storetest/mocks/JobStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/LicenseStore.go
  store/storetest/mocks/OAuthStore.go
  store/storetest/mocks/PluginStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/mocks/ReactionStore.go
  store/storetest/mocks/RoleStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/StatusStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/SystemStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/TokenStore.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/WebhookStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#8666 Add Ping Timeout Signal for WebSocket Client
  model/websocket_client.go
Labels: 3: Ready to Merge

#8766 Attempt to fix hub nil panic
  app/web_hub.go
Labels: 2: Dev Review

#8770 Comment out problematic TestS3TestConnection test
  api4/system_test.go
Labels: 2: Dev Review

#8765 MM-10188: expect io.Reader in FileBackend.WriteFile
  api/emoji_test.go
  app/emoji.go
  app/file.go
  app/team.go
  app/user.go
  utils/file_backend.go
  utils/file_backend_local.go
  utils/file_backend_s3.go
  utils/file_backend_test.go
  utils/mail_test.go
Labels: 2: Dev Review

#8738 [MM-10458] Change system response to "Could not find the channel" - bug fix
  app/apptestlib.go
  app/command_invite.go
  app/command_invite_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8776 More potential panic fixes
  app/web_hub.go
Labels: 2: Dev Review

#8753 MM-10513: fix mlog-ing before initialization
  mlog/default.go
  mlog/global.go
  mlog/global_test.go
  mlog/log.go
Labels: 3: Ready to Merge

#8760 [MM-10533] Add notification when @user, @here, @all and @channel has colon ":" at the end
  app/notification.go
  app/notification_test.go
Labels: 3: Ready to Merge

#8772 [MM-9720] fix bugs when trying to change for a in use email and check the number of parameters
  cmd/commands/user.go
  cmd/commands/user_test.go
Labels: 3: Ready to Merge

#8762 MM-9739: deprecate the now unused Channels.ExtraUpdateAt
  i18n/en.json
  model/channel.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 2: Dev Review

#8744 MM-9728: Online migration for advanced permissions phase 2
  api4/channel_test.go
  api4/scheme_test.go
  api4/team_test.go
  app/app.go
  app/scheme.go
  i18n/en.json
  imports/placeholder.go
  jobs/interfaces/migrations_interface.go
  jobs/jobs.go
  jobs/jobs_watcher.go
  jobs/schedulers.go
  jobs/server.go
  jobs/workers.go
  migrations/advanced_permissions_phase_2.go
  migrations/migrations.go
  migrations/migrations_test.go
  migrations/migrationstestlib.go
  migrations/scheduler.go
  migrations/worker.go
  model/job.go
  model/migration.go
  store/sqlstore/channel_store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Ready to Merge

#8778 Set APIv4 401s to debug
  api4/context.go
Labels: 3: Ready to Merge

#8732 Updating NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#8774 translations PR 20180511
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8795 Merge 4.10 into master
  NOTICE.txt
  app/apptestlib.go
  app/command_invite.go
  app/command_invite_test.go
  app/notification.go
  app/notification_test.go
  app/web_hub.go
  cmd/commands/user.go
  cmd/commands/user_test.go
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  mlog/default.go
  mlog/global.go
  mlog/global_test.go
  mlog/log.go
  web/context.go
Labels: 2: Dev Review

#8689 [MM-10335] Update email notification subject line and contents for Group Messages
  app/notification.go
  app/notification_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8771 MM-10234: Make CLI roles command advanced-permissions aware.
  cmd/commands/roles.go
  cmd/commands/roles_test.go
Labels: 2: Dev Review

#8812 MM-10591: Well known error for all scheme endpoints pre-migration.
  api4/scheme_test.go
  app/scheme.go
  i18n/en.json
Labels: 2: Dev Review

#8811 MM-10615: Reset teams/channels to default scheme on delete scheme.
  api4/scheme_test.go
  i18n/en.json
  store/sqlstore/scheme_supplier.go
  store/storetest/scheme_store.go
Labels: 2: Dev Review

#8773 MM-10235: Make permissions reset CLI shcemes-aware.
  app/permissions.go
  i18n/en.json
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_schemes.go
  store/redis_supplier_schemes.go
  store/sqlstore/channel_store.go
  store/sqlstore/scheme_supplier.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#8804 MM-10606: License feature flag for custom schemes.
  api4/scheme.go
  api4/scheme_test.go
  model/license.go
  model/license_test.go
  utils/license.go
Labels: 3: Ready to Merge

#8787 MM-10264: Adds CLI command to import and export permissions.
  api4/channel_test.go
  api4/scheme_test.go
  api4/team_test.go
  app/apptestlib.go
  app/permissions.go
  app/permissions_test.go
  app/scheme.go
  cmd/commands/permissions.go
  cmd/commands/permissions_test.go
  model/scheme.go
  store/sqlstore/scheme_supplier.go
  store/storetest/channel_store.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#8769 MM-9983 Requiring SiteURL to be set.
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/server_test.go
  config/default.json
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 2: Dev Review

#8827 Fixing CMD docs
  cmd/mattermost/commands/root.go
  cmd/mattermost/commands/user.go
Labels: 2: Dev Review

#8826 MM-10659 Fixing TE login.
  app/login.go
Labels: 2: Dev Review

#8824 MM-10498 Skip cluster send when getting non-cached statuses
  app/status.go
Labels: 2: Dev Review

#8814 Refactors migrations check.
  api4/channel_test.go
  api4/scheme_test.go
  api4/team_test.go
  app/app.go
  app/scheme.go
Labels: 2: Dev Review

#8817 Change order of web endpoints
  web/web.go
Labels: 2: Dev Review

#8835 MM-10352: Add locking incoming webhooks to a single channel.
  app/webhook.go
  i18n/en.json
  model/incoming_webhook.go
  store/sqlstore/upgrade.go
  web/webhook_test.go
Labels: 2: Dev Review

#8840 [MM-10479] Remove license check when enforcing password requirements
  app/authentication.go
  model/license.go
  model/license_test.go
  utils/config.go
  utils/license.go
Labels: 3: Ready to Merge

#8843 MM-10649: soften Channels.ExtraUpdateAt deprecation
  model/channel.go
  store/storetest/channel_store.go
Labels: 3: Ready to Merge

#8799 allow tuning *IdleConn* for intra-cluster messages
  config/default.json
  model/config.go
Labels: Loadtest

#8737 MM-8622: Improved plugin error reporting
  api4/plugin.go
  app/app.go
  app/apptestlib.go
  app/cluster_discovery.go
  app/plugin.go
  app/plugin_test.go
  einterfaces/cluster.go
  i18n/en.json
  model/client4.go
  model/cluster_discovery.go
  model/plugin_status.go
  model/websocket_message.go
  plugin/pluginenv/environment.go
  plugin/pluginenv/environment_test.go
  plugin/rpcplugin/rpcplugintest/supervisor.go
  plugin/rpcplugin/supervisor.go
  plugin/supervisor.go
Labels: 3: Ready to Merge

#8751 [MM-10340] Add ExperimentalHideTownSquareinLHS in config setting
  app/diagnostics.go
  config/default.json
  model/config.go
  utils/config.go
Labels: 2: Dev Review

#8851 [MM-10645] Remove desktop duration notify props
  app/import.go
  app/import_test.go
  i18n/en.json
  model/user.go
Labels: 2: Dev Review

#8848 Add autogenerate scheme.name for new schemes without explicit name
  store/sqlstore/scheme_supplier.go
Labels: 2: Dev Review

#8828 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2: Dev Review

#8836 re-enabling TestSendMailUsingConfigAdvanced
  utils/mail.go
  utils/mail_test.go
Labels: 2: Dev Review

#8391 MM-8814: Remove implicit permission grants from post ownership.
  api4/post.go
  app/authorization.go
Labels: 2: Dev Review

#8699 [MM-1915] Add Deactivate Account - server side
  api4/user.go
  api4/user_test.go
  app/email.go
  config/default.json
  i18n/en.json
  model/config.go
  templates/deactivate_body.html
  utils/config.go
Labels: 3: Ready to Merge

#8798 [MM-10519] Send websocket event whenever the channel has changed it's type (public|private)
  api4/channel_test.go
  app/channel.go
  model/websocket_message.go
Labels: 3: Ready to Merge

#8842 Avoid emails if user status is OOO or post is an auto response
  app/notification.go
Labels: 3: Ready to Merge

#8855 Allow to update the teams scheme to default scheme
  api4/team.go
  api4/team_test.go
Labels: 2: Dev Review

#8869 fix bad merge
  utils/config.go
Labels: 3: Ready to Merge

#8860 MM-8853: Adding MANAGE_EMOJIS and MANAGE_OTHERS_EMOJIS permissions
  api4/apitestlib.go
  api4/emoji.go
  api4/emoji_test.go
  api4/role.go
  app/app.go
  app/app_test.go
  app/apptestlib.go
  app/permissions.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/server.go
  einterfaces/emoji.go
  i18n/en.json
  migrations/migrationstestlib.go
  model/permission.go
  store/sqlstore/upgrade.go
  web/web_test.go
Labels: 3: Ready to Merge

#8849 Avoid emails if user status is OOO or post is an auto response
  app/notification.go
Labels: 3: Ready to Merge

#8823 Add note about clearing caches when permissions reset CLI done.
  cmd/mattermost/commands/permissions.go
Labels: 3: Ready to Merge

#8864 translations PR 20180528
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#8805 Changelog link
  CHANGELOG.md
Labels: 3: Ready to Merge

#8818 Push notification styling improvements
  app/notification.go
  app/notification_test.go
  i18n/en.json
Labels: 2: Dev Review
