Repository mattermost/mattermost, pull requests merged in 2018-11, with the labels that each got.

#9785 Add link to Freenode
  README.md
Labels: 3: Ready to Merge

#9776 MM-12708: tack on signin_change when completing email to saml change
  web/saml.go
Labels: 3: Ready to Merge, CherryPickApproved

#9779 MM-12369 Add Create Outgoing Webhook Command
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 3: Ready to Merge, Hacktoberfest

#9772 [MM-12805] Remove ephemeral post after leaving a channel
  app/command_leave.go
  app/command_leave_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#9692 [MM-12462] Include favorite channels in bulk export
  app/export.go
  app/export_converters.go
  app/export_test.go
Labels: 2: Dev Review, Hacktoberfest

#9743 GH-9737: Allow setting min_server_version in plugin manifest
  Gopkg.lock
  Gopkg.toml
  model/manifest.go
  model/manifest_test.go
  plugin/environment.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: 3: Ready to Merge

#9750 Added GETEmojilist plugin api
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review, Hacktoberfest

#9734 MM-12355: Add CLI command "command create" revision
  cmd/mattermost/commands/command.go
  cmd/mattermost/commands/command_test.go
Labels: 3: Ready to Merge, Hacktoberfest

#9798 upgrade to 5.5
  model/version.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#9799 upgrade db to 5.5
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#9801 MM-12849 Fixing formatting.
  api4/terms_of_service.go
  api4/terms_of_service_test.go
  app/extension.go
  app/plugin_requests.go
  app/server_test.go
  app/webhook_test.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/webhook_test.go
  model/terms_of_service_test.go
  plugin/valid_test.go
  store/sqlstore/terms_of_service_store.go
  store/sqlstore/terms_of_service_store_test.go
  store/storetest/terms_of_service_store.go
  utils/testutils/mocked_http_service.go
Labels: 2: Dev Review

#9800 translations PR 20181105
  i18n/fr.json
  i18n/zh-TW.json
Labels: 2: Dev Review, Localization

#9806 MM-12849 Moving all non request scoped items to Server struct
  api4/user.go
  app/admin.go
  app/app.go
  app/app_test.go
  app/channel.go
  app/cluster.go
  app/command_echo.go
  app/compliance.go
  app/config.go
  app/config_test.go
  app/diagnostics.go
  app/email.go
  app/email_batching.go
  app/file.go
  app/job.go
  app/ldap.go
  app/license.go
  app/login.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/oauth.go
  app/options.go
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_requests.go
  app/plugin_statuses.go
  app/post.go
  app/post_test.go
  app/reaction.go
  app/role.go
  app/scheme.go
  app/server.go
  app/session.go
  app/session_test.go
  app/team.go
  app/timezone.go
  app/user.go
  app/web_conn.go
  app/web_hub.go
  app/webhook.go
  app/websocket_router.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/server.go
  migrations/scheduler.go
  migrations/worker.go
  plugin/scheduler/scheduler.go
  plugin/scheduler/worker.go
  web/saml.go
Labels: 2: Dev Review

#9797 MM-12829 Check message attachments for emojis for post metadata
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Ready to Merge

#9744 GH-9740: Add plugin methods to plugin API
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_statuses.go
  model/client4.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review

#9731 #146 Terms of Service Phase 2
  api4/terms_of_service.go
  api4/user.go
  api4/user_test.go
  app/diagnostics.go
  app/user.go
  app/user_terms_of_service.go
  app/user_terms_of_service_test.go
  app/user_test.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/terms_of_service.go
  model/user.go
  model/user_terms_of_Service_test.go
  model/user_terms_of_service.go
  store/layered_store.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/terms_of_service_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/sqlstore/user_terms_of_service.go
  store/sqlstore/user_terms_of_service_store_test.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/UserTermsOfServiceStore.go
  store/storetest/store.go
  store/storetest/user_terms_of_service.go
  utils/config.go
Labels: 3: Ready to Merge

#9782 Optimize searching for users on Postgres
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
Labels: 3: Ready to Merge, Hacktoberfest, Loadtest

#9780 Ignore "@" sign at the beginning of user searches
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review, Hacktoberfest

#9826 translations PR 20181112
  i18n/de.json
  i18n/ko.json
  i18n/ru.json
Labels: 3: Ready to Merge

#9827 [MM-12984] default text to SAML
  config/default.json
  model/saml.go
Labels: 3: Ready to Merge

#9775 Update handlers_test.go
  web/handlers_test.go
Labels: 3: Ready to Merge

#9707 [MM-11876] Add cursor to posts list such as next_post_id and previous_post_id
  api4/post.go
  api4/post_test.go
  app/post.go
  app/post_metadata.go
  model/post_list.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#9832 MM-13021 Fix warning logged when getting metadata for post without emojis
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Ready to Merge

#9828 MM-12818: Delete FileInfos when deleting the post they belong to.
  app/post.go
  app/post_test.go
Labels: 2: Dev Review

#9831 Add SetProfileImage for plugin API
  app/import_functions.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/user.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9837 Add GetTeamIcon plugin api method
  app/plugin_api.go
  app/plugin_api_test.go
  app/team.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9840 add SetTeamIcon plugin api
  app/plugin_api.go
  app/plugin_api_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9838 [MM-12476] Consistent paging arguments limit/offset vs page/perPage for plugin API
  app/channel_test.go
  app/plugin_api.go
  app/team_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9836 [MM-9938] Add support for multiple responses from a slash command
  app/command.go
  model/command_response.go
  model/command_response_test.go
Labels: 2: Dev Review

#9844 Remove *model.ChannelList from plugin API return parameter
  app/plugin_api.go
  app/plugin_api_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9818 MM-12974: guard app plugins with mutex
  app/channel.go
  app/diagnostics.go
  app/file.go
  app/login.go
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_requests.go
  app/plugin_statuses.go
  app/plugin_test.go
  app/post.go
  app/server.go
  app/team.go
Labels: 3: Ready to Merge

#9847 Add RemoveTeamIcon plugin api
  app/plugin_api.go
  app/plugin_api_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9819 Ensure unittest isolation
  Makefile
  api4/apitestlib.go
  api4/brand_test.go
  api4/channel_test.go
  api4/cluster_test.go
  api4/command_test.go
  api4/elasticsearch_test.go
  api4/emoji_test.go
  api4/file_test.go
  api4/job_test.go
  api4/ldap_test.go
  api4/oauth_test.go
  api4/plugin_test.go
  api4/post_test.go
  api4/reaction_test.go
  api4/role_test.go
  api4/saml_test.go
  api4/scheme_test.go
  api4/status_test.go
  api4/system_test.go
  api4/team_test.go
  api4/terms_of_service_test.go
  api4/user_test.go
  api4/webhook_test.go
  app/apptestlib.go
  app/channel_test.go
  app/web_conn_test.go
  cmd/mattermost/commands/command_test.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/team_test.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/webhook_test.go
  migrations/migrationstestlib.go
  store/layered_store.go
  store/local_cache_supplier.go
Labels: 2: Dev Review

#9848 add CreateDirectChannel plugin api
  app/plugin_api.go
  app/plugin_api_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#9859 Block to override post_type if already set
  model/slack_attachment.go
Labels: 3: Ready to Merge

#9863 Webhub race condition
  api4/apitestlib.go
  app/apptestlib.go
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
Labels: 3: Ready to Merge

#9851 GH-9846: Migrate to idiomatic error handling in model/client4.go
  model/client4.go
Labels: 2: Dev Review

#9841 MM-12957: Fix moving a channel with no members.
  app/channel.go
  app/channel_test.go
Labels: 3: Ready to Merge

#9861 Adds 'LDAP groups' feature flag.
  api4/group.go
  api4/ldap.go
  model/license.go
  model/license_test.go
  utils/license.go
Labels: 2: Dev Review

#9869 Remove comments about deprecating FileIds and HasReactions
  app/post_metadata.go
  model/post.go
Labels: 3: Ready to Merge

#9868 MM-11434 Only call PreparePostForClient once when creating a post
  api4/post.go
  app/notification.go
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 2: Dev Review

#9876 MM-11434 Only call PreparePostForClient once when creating a post
  api4/post.go
  app/notification.go
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Ready to Merge

#9830 [MM-12789] Clean up unused HTML templates
  app/email.go
  templates/signup_team_body.html
  templates/upgrade_30_body.html
  templates/username_change_body.html
Labels: 3: Ready to Merge

#9864 Add helper methods for SubmitDialog structs
  model/integration_action.go
  model/integration_action_test.go
Labels: 3: Ready to Merge

#9871 Moving app level migrations to its own file
  app/app.go
  app/migrations.go
Labels: 2: Dev Review, Awaiting Next Release

#9872 #132 Added some comments for API client
  api4/user_test.go
  model/client4.go
Labels: 2: Dev Review

#9879 Skip getting the post again when getting file metadata for a post
  api4/post.go
  app/post.go
  app/post_metadata.go
Labels: 2: Dev Review

#9804 [MM - 12370] Add cli command "webhook delete"
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 3: Ready to Merge

#9880 upgrade db to 5.6.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#9881 Add preparatory upgrade code for 5.7.0
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#9882 MM-13015 Remove metadata field from post when metadata is disabled
  app/post_metadata_test.go
  model/post.go
Labels: 3: Ready to Merge, CherryPickApproved

#9817 [MM-12452] Stop inserting hashed plugin keys
  app/plugin_key_value_store.go
  app/plugin_test.go
  model/plugin_key_value_test.go
Labels: 2: Dev Review, CherryPickApproved

#9894 MM-13208 Rename DisablePostMetadata setting to EnablePostMetadata and turn off by default
  app/diagnostics.go
  app/post_metadata.go
  app/post_metadata_test.go
  config/default.json
  model/config.go
Labels: 3: Ready to Merge, CherryPickApproved

#9891 MM-12648: Properly unescape OpenGraph metadata containing HTML entities.
  app/opengraph.go
  app/opengraph_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#9898 MM-13185: Fix Message Export config special case.
  api4/system.go
  api4/system_test.go
  model/config.go
  model/config_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#9865 Various unit test related improvements
  Makefile
  api4/apitestlib.go
  api4/system_test.go
  app/server_test.go
  build/Jenkinsfile
  model/manifest_test.go
  services/filesstore/filesstore_test.go
  services/mailservice/inbucket.go
  store/sqlstore/system_store.go
Labels: 3: Ready to Merge

#9890 MM-12837 Properly reuturning result from store function so failure is caught.
  store/sqlstore/preference_store.go
Labels: 3: Ready to Merge

#9883 MM-12881 Add license sku fields
  app/diagnostics.go
  app/license.go
  app/license_test.go
  model/license.go
  utils/license.go
Labels: 3: Ready to Merge, CherryPickApproved

#9899 Improving create-outgoing webhook command
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#9896 MM-12009 Resolve relative links in posts as the web app does
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#9867 Refactor Get/Create Direct Channel into one function
  api4/apitestlib.go
  api4/channel.go
  api4/post_test.go
  app/apptestlib.go
  app/channel.go
  app/channel_test.go
  app/command_msg.go
  app/command_mute_test.go
  app/import_functions_test.go
  app/notification_test.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/post.go
  app/webhook.go
  migrations/migrationstestlib.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge, CherryPickApproved

#9902 translations PR 20181128 (adds Ukrainian)
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#9905 MM-12368: Fixing webhook create incomming
  cmd/mattermost/commands/webhook.go
Labels: 3: Ready to Merge, CherryPickApproved

#9909 Adding make i18n-extract command to the makefile
  Makefile
Labels: 2: Dev Review

#9904 fix two page, perPage -> offset, limit mistranslations
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_key_value_store.go
  app/plugin_test.go
Labels: 2: Dev Review, CherryPickApproved

#9912 Fixing enterprise init order.
  app/enterprise.go
Labels: 2: Dev Review

#9793 [GH-9639] Add plugin API for SearchUsers method
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review

#9916 Fixing initalization order.
  app/server.go
Labels: 3: Ready to Merge

#9921 Fix name
  build/Jenkinsfile.pr
  build/docker-compose.yml
Labels: Work In Progress
