Repository mattermost/mattermost, pull requests merged in 2018-09, with the labels that each got.

#9333 MM-11693 Allow connections to /plugins for interactive message buttons.
  app/post.go
  app/post_test.go
  utils/httpclient.go
Labels: 3: Ready to Merge

#9288 [MM-11293] Fix Issues detected by Megacheck + New Make Target
  Makefile
  api4/channel_test.go
  api4/emoji_test.go
  api4/file_test.go
  api4/post_test.go
  api4/preference_test.go
  api4/role_test.go
  api4/status_test.go
  api4/team_test.go
  api4/user_test.go
  api4/webhook_test.go
  app/app.go
  app/auto_responder_test.go
  app/brand.go
  app/channel.go
  app/config_test.go
  app/diagnostics_test.go
  app/file.go
  app/import_functions.go
  app/notification_email.go
  app/permissions.go
  app/plugin_hooks_test.go
  app/session_test.go
  app/team.go
  cmd/mattermost/commands/permissions.go
  cmd/mattermost/commands/permissions_test.go
  model/config.go
  model/session_test.go
  model/user_test.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/environment.go
  plugin/interface_generator/main.go
  plugin/io_rpc.go
  plugin/supervisor.go
  store/sqlstore/channel_store.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
  store/storetest/channel_store.go
  store/storetest/command_store.go
  store/storetest/compliance_store.go
  store/storetest/job_store.go
  store/storetest/post_store.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
  store/storetest/webhook_store.go
  utils/config.go
  utils/i18n.go
  utils/jsonutils/json_test.go
  utils/mail.go
Labels: 2: Dev Review

#9346 Merge release-5.3-20180903124813
  app/post.go
  app/post_test.go
  utils/httpclient.go
Labels: 2: Dev Review

#9335 MM-11728: Avoid Archived channels editions throught Patch
  i18n/en.json
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 3: Ready to Merge

#9334 MM-11720: disable loading plugin specific config from the environment
  utils/config.go
  utils/config_test.go
Labels: 3: Ready to Merge

#9313 MM-11272 Add OpenGraph and image dimension metadata to posts
  api4/apitestlib.go
  api4/brand_test.go
  api4/file_test.go
  api4/openGraph.go
  api4/post_test.go
  api4/team_test.go
  api4/user_test.go
  app/app.go
  app/opengraph.go
  app/opengraph_test.go
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/post_test.go
  i18n/en.json
  model/post.go
  utils/testutils/testutils.go
Labels: 2: Dev Review

#9354 Uncomment upgrade for 5.3.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#9371 Release 5.3 daily merge 20180904
  i18n/en.json
  model/version.go
  store/sqlstore/channel_store.go
  store/sqlstore/upgrade.go
  store/storetest/channel_store.go
  utils/config.go
  utils/config_test.go
Labels: 2: Dev Review

#9355 Add preparatory upgrade code for 5.4.0
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, DO NOT MERGE

#9347 Fix typo
  plugin/client_rpc.go
Labels: 3: Ready to Merge

#9345 MM-11649: Fix caching issue in channel API endpoints.
  api4/channel.go
  model/channel.go
Labels: 3: Ready to Merge

#9379 MM-12007 Add max dimensions to emoji images
  api4/emoji_test.go
  app/emoji.go
  i18n/en.json
Labels: 2: Dev Review

#9381 MM-11882: Remove all users from a channel via CLI.
  cmd/mattermost/commands/channel.go
Labels: 2: Dev Review

#9382 Stop re-wrapping password reset email error in another error
  app/user.go
Labels: 2: Dev Review

#9387 Replace App.HTTPClient calls after merge
  app/opengraph.go
  app/post_metadata.go
  app/post_test.go
Labels: 3: Ready to Merge

#9383 MM-12012 Changing comparison method.
  api4/file.go
Labels: 3: Ready to Merge

#9390 Merge release-5.3-20180910141320
  api4/channel.go
  api4/file.go
  app/post.go
  model/channel.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#9373 MM-10677 memory fix to s3 upload
  utils/file_backend_s3.go
Labels: 3: Ready to Merge

#9391 MM-12007 Add max dimensions to emoji images (4.10)
  api4/emoji_test.go
  app/emoji.go
  i18n/en.json
Labels: 3: Ready to Merge

#9386 MM-12007 Add max dimensions to emoji images (5.1)
  api4/emoji_test.go
  app/emoji.go
  i18n/en.json
Labels: 3: Ready to Merge

#9385 MM-12007 Add max dimensions to emoji images (5.2)
  api4/emoji_test.go
  app/emoji.go
  i18n/en.json
Labels: 3: Ready to Merge

#9325 Minor grammar & spelling fixes
  i18n/en.json
Labels: 3: Ready to Merge

#9397 translations PR 20180911
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#9372 MM-11895: Don't crush user-provided GET parameters on slash command URLs
  api4/command_test.go
  app/command.go
Labels: 3: Ready to Merge

#9337 MM-11725: Add specific autocomplete endpoint for search autocomplete
  api4/channel.go
  app/channel.go
  model/client4.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Ready to Merge

#9401 Merge release-5.3-20180912130732
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  utils/file_backend_s3.go
Labels: 2: Dev Review

#9407 MM-12007 Add max dimensions to emoji images (5.3)
  api4/emoji_test.go
  app/emoji.go
  i18n/en.json
Labels: 3: Ready to Merge

#9349 MM-11886: materialize channel search
  app/app.go
  config/default.json
  model/config.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_experimental.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/supplier.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/SqlSupplier.go
Labels: 3: Ready to Merge

#9405 MM-11734: better plugin `error` handling
  app/plugin_hooks_test.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/interface_generator/main.go
Labels: 2: Dev Review

#9402 MM-10573 Add error page if user doesn't authorize Mattermost for OAuth
  api4/oauth.go
  api4/oauth_test.go
Labels: 2: Dev Review

#9414 Migrate to idiomatic error handling the second half to the app/channel.go
  app/channel.go
Labels: 3: Ready to Merge

#9341 fixing log messages
  app/import_functions.go
  app/notification.go
  app/notification_email.go
  cmd/mattermost/commands/server.go
Labels: 3: Ready to Merge

#9419 MM-11424 Extend bulk import to support themes across teams(#9305)
  app/import_functions.go
  app/import_functions_test.go
  app/import_test.go
  app/import_types.go
  app/import_validators.go
  app/import_validators_test.go
  model/preference.go
Labels: 2: Dev Review

#9420 MM-12045: Fix MFA for ldap accounts
  app/login.go
Labels: 2: Dev Review

#9351 [MM-11860]: Expose slack attachment parsing functions in the model package
  app/command.go
  app/post.go
  app/slackimport.go
  app/webhook.go
  model/slack_attachment.go
Labels: 2: Dev Review

#9418 disable EnablePublicChannelsMaterialization by default
  config/default.json
  model/config.go
Labels: 2: Dev Review

#9296 MM-11781: Basic Data Export Command Line.
  app/export.go
  app/export_converters.go
  app/import_types.go
  cmd/mattermost/commands/export.go
  cmd/mattermost/commands/export_test.go
  i18n/en.json
  model/channel.go
  model/channel_member.go
  model/post.go
  model/team.go
  model/team_member.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/post_store.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 3: Ready to Merge

#9343 MM-11700 Clean up handling of user display names for notifications
  app/import_functions.go
  app/import_functions_test.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/notification_test.go
  model/preference.go
Labels: 3: Ready to Merge

#9413 Migrate to idiomatic error handling the first half to the app/channel.go
  app/channel.go
Labels: 2: Dev Review

#9427 Revert "disable EnablePublicChannelsMaterialization by default (#9418)"
  config/default.json
  model/config.go
Labels: 3: Ready to Merge

#9384 Add ChannelId and TeamId to PostActionIntegrationRequest
  app/post.go
  app/post_test.go
  model/post.go
Labels: 3: Ready to Merge

#9428 translations PR 20180917
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#9435 Move file backend to its own service
  Makefile
  api4/system.go
  api4/team_test.go
  api4/user_test.go
  app/admin.go
  app/email.go
  app/file.go
  cmd/mattermost/commands/server.go
  scripts/license-check.sh
  services/filesstore/filesstore.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/mocks/FileBackend.go
  services/filesstore/s3store.go
  services/filesstore/s3store_test.go
  services/mailservice/inbucket.go
  services/mailservice/mail.go
  services/mailservice/mail_test.go
Labels: 2: Dev Review

#9438 MM-11582 Fail plugin activation if no web app and server component
  plugin/environment.go
Labels: 2: Dev Review

#9423 Idiomatic error handling for app/c*.go
  app/cluster_discovery.go
  app/compliance.go
  app/config.go
Labels: 3: Ready to Merge

#9439 MM-11935 Include webhook ID in debug log
  web/webhook.go
Labels: 3: Ready to Merge

#9447 MM-11707: Change the default setting for EDIT_OTHERS_POSTS
  api4/post_test.go
  api4/role.go
  app/app_test.go
  model/role.go
  store/storetest/scheme_store.go
Labels: 2: Dev Review

#9294 MM-11612 Add translation strings and add test case
  api4/user_test.go
  i18n/en.json
Labels: 2: Dev Review

#9448 Add missing dots (fixing compilation error on go 1.11)
  app/server.go
Labels: 2: Dev Review

#9433 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#9453 Adding arg spec to bulk export.
  cmd/mattermost/commands/export.go
Labels: 2: Dev Review, Tests: Not Needed

#9455 Migrate to idiomatic error handling app/a*.go and app/b*.go
  app/admin.go
  app/analytics.go
  app/audit.go
  app/authorization.go
  app/brand.go
Labels: 3: Ready to Merge

#9425 Adding paging to elasticsearch API
  api4/post.go
  api4/post_test.go
  app/post.go
  einterfaces/elasticsearch.go
  model/client4.go
  model/post.go
Labels: 3: Ready to Merge

#9348 MM-7188: Cleaning push notification on every read, not only on channel switch
  api4/channel.go
  api4/post.go
  app/app.go
  app/channel.go
  app/channel_test.go
  app/command_invite.go
  app/notification_push.go
  app/plugin_api.go
  app/post.go
  app/post_test.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
Labels: 3: Ready to Merge

#9422 Move HTTPService and ConfigService into services package
  app/app.go
  app/apptestlib.go
  app/http_service.go
  jobs/server.go
  jobs/workers.go
  services/configservice/configservice.go
  services/httpservice/client.go
  services/httpservice/client_test.go
  services/httpservice/httpservice.go
  utils/testutils/mocked_http_service.go
  utils/testutils/static_config_service.go
Labels: Awaiting PR

#9450 #MM-12130 changes for custom service terms
  Makefile
  api4/api.go
  api4/service_terms.go
  api4/service_terms_test.go
  api4/user.go
  api4/user_test.go
  app/admin.go
  app/app.go
  app/config.go
  app/diagnostics.go
  app/diagnostics_test.go
  app/service_terms.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/license.go
  model/service_terms.go
  model/service_terms_test.go
  model/session_test.go
  model/user.go
  store/layered_store.go
  store/sqlstore/service_terms_store.go
  store/sqlstore/service_terms_store_test.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/ServiceTermsStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/service_terms_store.go
  store/storetest/store.go
  store/storetest/user_store.go
  utils/config.go
  web/web_test.go
Labels: 2: Dev Review

#9454 translations PR 20180924
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#9444 ensure subpath redirect preserves query string correctly
  web/static.go
Labels: 3: Ready to Merge

#9477 Uncomment upgrade for 5.4.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#9478 MM-12339: When leave a channel the push notification can fail
  app/channel.go
Labels: 2: Dev Review

#9430 MM-11567: Autocomplete search in: for DMs and GMs
  api4/channel_test.go
  app/post.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_experimental.go
  store/storetest/channel_store.go
Labels: 3: Ready to Merge

#9473 Idiomatic error handling for app/import*.go
  app/import.go
  app/import_functions.go
  app/import_validators.go
Labels: 2: Dev Review

#9429 GH-9408: Add plugin API methode to return the current server version
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review

#9476 MM-12013: Fix post-permission checks to cascade for DM/GM channels.
  api4/apitestlib.go
  api4/post_test.go
  app/authorization.go
Labels: 2: Dev Review

#9468 Bump AuthorizeRequest State max length to 1024
  model/authorize.go
Labels: 2: Dev Review

#9475 MM-12080: Added some extra logging to cluster leader changed.
  app/app.go
  app/cluster.go
Labels: 2: Dev Review

#9495 Add EnablePublicChannelsMaterialization to diagnostics.go
  app/diagnostics.go
Labels: 3: Ready to Merge

#9481 MM-12192: autocompleteUsers: if a teamId is provided, require it to match the channel's team id
  api4/user.go
  api4/user_test.go
  i18n/en.json
Labels: 2: Dev Review

#9474 Idiomatic error handling for app/{job,license,login}.go
  app/job.go
  app/license.go
  app/login.go
Labels: 3: Ready to Merge

#9479 Add preparatory upgrade code for 5.5.0
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge
