Repository mattermost/mattermost, pull requests merged in 2018-02, with the labels that each got.

#8208 AllowEditPost and PostEditTimeLimit migration
  api/post_test.go
  api4/post_test.go
  app/app_test.go
  app/apptestlib.go
  app/post.go
  app/post_test.go
  config/default.json
  model/config.go
  model/role.go
  utils/authorization.go
Labels: 2: Dev Review

#8160 XYZ-51: Unit tests for and changes to SetRolePermissionsFromConfig.
  app/app.go
  app/app_test.go
  utils/authorization.go
  utils/authorization_test.go
  utils/policies-roles-mapping.json
Labels: 2: Dev Review

#8229 Remove license globals entirely
  api/apitestlib.go
  api/license.go
  api/license_test.go
  api/user.go
  api4/apitestlib.go
  api4/oauth_test.go
  api4/system.go
  app/admin.go
  app/app.go
  app/apptestlib.go
  app/config.go
  app/email.go
  app/file.go
  app/license.go
  app/license_test.go
  app/role.go
  app/session_test.go
  cmd/platform/jobserver.go
  jobs/server.go
  jobs/server_test.go
  utils/authorization.go
  utils/config.go
  utils/config_test.go
  utils/file_backend.go
  utils/file_backend_test.go
  utils/license.go
  utils/license_test.go
  utils/mail.go
  utils/mail_test.go
Labels: 2: Dev Review

#8230 Add /v4/image api
  api4/api.go
  api4/image.go
  api4/image_test.go
  utils/config.go
Labels: 2: Dev Review

#8238 Don't proxy same-site image urls
  app/post.go
  app/post_test.go
Labels: 3: Ready to Merge

#8233 ABC-228 Update GetPosts caching to work for non-60 limits
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#8235 XYZ-104: Can join a team with email invite link after regenerating the invite code
  api4/team_test.go
  app/email.go
  app/team.go
  app/team_test.go
  i18n/en.json
Labels: Setup Test Server

#8231 Add tests for the `platform server` command
  app/app.go
  cmd/platform/server.go
  cmd/platform/server_test.go
  jobs/jobs_watcher.go
Labels: 2: Dev Review

#8245 XYZ-73: Removes EnableOnlyAdminIntegrations.
  api/command_test.go
  api4/post_test.go
Labels: 2: Dev Review

#8237 XYZ-109: Mapping updates
  app/diagnostics.go
  model/config.go
  utils/authorization.go
  utils/authorization_test.go
  utils/config.go
  utils/policies-roles-mapping.json
Labels: 2: Dev Review

#8249 ABC-176 Prevent changing PluginSettings.EnableUploads through the API
  api/admin.go
  api/admin_test.go
  api4/system.go
  api4/system_test.go
Labels: 3: Ready to Merge

#8267 XYZ-78: Add note to upgrade code about advanced permissions migration.
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#8261 XYZ-111: Check max users per team on re-join after leave a team
  app/team.go
  app/team_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8255 translations PR 20180212
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8247 ICU-753 Remove special behaviour for group messages in generic push notifications
  app/notification.go
  app/notification_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8287 T3: Merge release-4.7 into master
  app/app.go
  app/post_test.go
  cmd/platform/server.go
  cmd/platform/server_test.go
Labels: 2: Dev Review

#8259 [Fix tests] Wait for goroutines to finish before shutting down server
  cmd/platform/server.go
Labels: 3: Ready to Merge

#8294 translations PR 20180215
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8289 XYZ-106: Compliance Export is not able to distinguish between two different file uploads that have the same file name
  utils/mail.go
  utils/mail_test.go
Labels: 2: Dev Review

#8274 XYZ-114 Adding mandatory membership to town-square in bulk-import
  app/import.go
Labels: 2: Dev Review

#8225 PLT-8723: Fix DeadLock on reactions insertions
  store/sqlstore/supplier_reactions.go
Labels: 2: Dev Review

#8296 Send systemd READY notification
  cmd/platform/server.go
  cmd/platform/server_test.go
Labels: 2: Dev Review

#7873 [PLT-539] Update incoming webhooks to accept multipart/form-data content
  api4/webhook.go
  i18n/en.json
  model/incoming_webhook.go
  web/web_test.go
Labels: 2: Dev Review

#8317 Always return non-nil client license
  app/license.go
Labels: 3: Ready to Merge

#8303 MM-9618: Don't change default role permissions for policy.
  api/channel_test.go
  api4/channel_test.go
  app/app_test.go
  utils/authorization.go
  utils/policies-roles-mapping.json
Labels: 2: Dev Review

#8300 MM-8827: Add reactions permissions
  api/reaction.go
  api4/reaction.go
  api4/reaction_test.go
  app/app_test.go
  model/permission.go
  model/role.go
Labels: 2: Dev Review

#8334 translations PR 20180220
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8305 Added t.Helper to CheckXStatus test functions
  api4/apitestlib.go
Labels: 2: Dev Review

#8326 MM-8825: Make consistent INVITE_USER and ADD_USER_TO_TEAM permissions checking
  api/team.go
Labels: 2: Dev Review

#8306 MM-9556 Added ability to upload files without a multipart request
  api/file.go
  api4/context.go
  api4/file.go
  api4/file_test.go
  api4/params.go
  app/file.go
  i18n/en.json
  model/client4.go
Labels: 3: Ready to Merge

#8293 MM-8710: Web Hub optimizations
  app/web_hub.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 2: Dev Review

#8332 MM-8747 Update error message when plugins are disabled
  i18n/en.json
Labels: 3: Ready to Merge

#8307 MM-8681 Adding config settings necessary for using CloudFront.
  api4/user.go
  app/config.go
  app/diagnostics.go
  app/login.go
  config/default.json
  i18n/en.json
  model/config.go
  utils/config.go
Labels: 3: Ready to Merge

#8263 Adding saml migration command
  cmd/platform/user.go
  einterfaces/account_migration.go
  i18n/en.json
Labels: 3: Ready to Merge

#8339 MM-9653 Change log level of 404s to DEBUG
  api4/context.go
Labels: 3: Ready to Merge

#8346 MM-8006 Fix push notification content for file only messages
  app/notification.go
  app/notification_test.go
  i18n/en.json
Labels: 3: Ready to Merge

#8343 Remove global site url
  api/user.go
  api4/user.go
  app/app.go
  app/config.go
  app/email.go
  app/ldap.go
  app/notification.go
  app/oauth.go
  app/team.go
  app/user.go
  utils/api.go
  utils/config.go
Labels: 2: Dev Review

#8352 MM-8684 Fall back to constructed URL for OAuth SSO if SiteURL not set
  app/oauth.go
Labels: 3: Ready to Merge

#8353 MM-8593 Default APIv3 to disabled for new installs
  api/apitestlib.go
  config/default.json
  utils/config.go
  web/web_test.go
Labels: 2: Dev Review

#8355 Fix scheduled task data race
  app/email_batching.go
  model/scheduled_task.go
  model/scheduled_task_test.go
Labels: 3: Ready to Merge

#8364 Merge release-4.7 into master
  api4/context.go
Labels: 2: Dev Review

#8360 MM-9623 Fix forward 80 to 443 to not bind on all interfaces.
  app/server.go
Labels: 3: Ready to Merge

#8366 Add packaging targets for individual platforms
  Makefile
  build/release.mk
Labels: 3: Ready to Merge

#8367 MM-9698 Fixing Minio with server side encryption.
  utils/file_backend_s3.go
  utils/file_backend_test.go
Labels: 2: Dev Review

#8379 Temporarily disable flaky TestSendMailUsingConfigAdvanced test
  utils/mail_test.go
Labels: 2: Dev Review

#8344 Fix prerequisites checker so 1.10 > 1.9
  scripts/prereq-check.sh
Labels: 3: Ready to Merge

#8381 Optimize LRU purging
  utils/lru.go
  utils/lru_test.go
Labels: 2: Dev Review

#8345 Simplification of a Channel Members query.
  store/sqlstore/channel_store.go
Labels: 3: Ready to Merge
