Repository mattermost/mattermost, pull requests merged in 2018-06, with the labels that each got.

#8894 MM-10757: Default roles from scheme should be keyed by name not ID.
  api4/scheme_test.go
  app/apptestlib.go
  app/permissions.go
  app/permissions_test.go
  store/sqlstore/scheme_supplier.go
  store/sqlstore/team_store.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#8895 MM-10760: Using master for any Exec call
  store/sqlstore/scheme_supplier.go
  store/sqlstore/system_store.go
Labels: 2: Dev Review

#8896 MM-10412: Adds deleteBy prop to posts.
  api4/post.go
  app/plugin_api.go
  app/post.go
  model/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#8882 Adding mlog to context.
  web/context.go
  web/handlers.go
Labels: 3: Ready to Merge

#8871 [MM-10718] Move custom branding to TE
  api4/brand_test.go
  app/app.go
  app/brand.go
  einterfaces/brand.go
  model/license.go
  model/license_test.go
  utils/config.go
  utils/license.go
Labels: 3: Ready to Merge

#8897 MM-10683 Remove plugin sandbox warning message
  app/plugin.go
Labels: 3: Ready to Merge

#8881 MM-10348 Adding experimental hardened mode.
  api4/user.go
  config/default.json
  model/config.go
  web/handlers.go
Labels: 3: Ready to Merge

#8902 MM-9547 Fixed invalid CustomUrlSchemes error message
  model/config.go
Labels: 3: Ready to Merge

#8901 MM-10597 Improved handling of punctuation around notifications
  app/notification.go
  app/notification_test.go
Labels: 3: Ready to Merge

#8909 translations PR 20180604
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge, Localization

#8914 Uncomment upgrade for 5.0.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#8918 disable Supervisor_PluginRepeatedlyCrash
  plugin/rpcplugin/rpcplugintest/supervisor.go
Labels: 2: Dev Review

#8917 use minio release instead of latest
  Makefile
Labels: 3: Ready to Merge

#8915 MM-6839: searching for paths relative to executable
  cmd/platform/main.go
  utils/config.go
  utils/config_test.go
Labels: 2: Dev Review

#8911 Add missing diagnostics
  app/diagnostics.go
Labels: 3: Ready to Merge

#8927 Relese5.0 merge master 20180607
  app/diagnostics.go
  app/notification.go
  model/push_notification.go
Labels: 2: Dev Review

#8854 MM-10688: allow client4 http keep-alive
  model/client4.go
Labels: 3: Ready to Merge

#8847 Get the count of the all system users at endpoint /users/stats
  api4/user.go
  api4/user_test.go
  app/user.go
  model/client4.go
  model/users_stats.go
Labels: 3: Ready to Merge

#8926 MM-10803: remove premature user sanitization on deactivation
  api4/apitestlib.go
  api4/user_test.go
  app/user.go
  app/user_test.go
Labels: 3: Ready to Merge

#8924 MM-10264: Adds system scheme to permissions import/export.
  app/permissions.go
  app/permissions_test.go
Labels: 3: Ready to Merge

#8935 Fix idempotency of scheme migrations.
  store/sqlstore/channel_store.go
  store/sqlstore/team_store.go
Labels: 3: Ready to Merge

#8938 MM-10790: Fix Slack Import logs that got broken in refactoring.
  app/slackimport.go
  i18n/en.json
Labels: 2: Dev Review

#8936 MM-10684: Show logs on Slack Import CLI.
  cmd/mattermost/commands/import.go
Labels: 2: Dev Review

#8939 Relese5.0 merge master 20180611
  store/sqlstore/channel_store.go
  store/sqlstore/team_store.go
Labels: 3: Ready to Merge

#8937 MM-10791: Don't try and generate thumbnails for non-images/svgs.
  app/import.go
Labels: 3: Ready to Merge

#8475 Prototype for CBA
  api4/user.go
  api4/user_test.go
  app/login.go
  app/login_test.go
  config/default.json
  model/client4.go
  model/config.go
  utils/config.go
Labels: 2: Dev Review

#8920 Add preparatory upgrade code for 5.1.0
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#8947 translations PR 20180613
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/pt-BR.json
  i18n/zh-CN.json
Labels: 3: Ready to Merge, Localization

#8943 MM-10863: Handle non-API errors with redirect to webapp
  web/handlers.go
  web/handlers_test.go
Labels: 3: Ready to Merge

#8948 MM-10769 Rename references to spf13/viper to mattermost/viper
  Gopkg.lock
  Gopkg.toml
  utils/config.go
  vendor/github.com/mattermost/viper/.gitignore
  vendor/github.com/mattermost/viper/.travis.yml
  vendor/github.com/mattermost/viper/LICENSE
  vendor/github.com/mattermost/viper/README.md
  vendor/github.com/mattermost/viper/flags.go
  vendor/github.com/mattermost/viper/util.go
  vendor/github.com/mattermost/viper/viper.go
Labels: 2: Dev Review

#8952 Release 5.0 merge to master 20180614 1
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/pt-BR.json
  i18n/zh-CN.json
  web/handlers.go
  web/handlers_test.go
Labels: 2: Dev Review

#8900 Update html2text lib to use the original repo
  Gopkg.lock
  NOTICE.txt
  utils/mail.go
  vendor/github.com/dimchansky/utfbom/.gitignore
  vendor/github.com/dimchansky/utfbom/.travis.yml
  vendor/github.com/dimchansky/utfbom/LICENSE
  vendor/github.com/dimchansky/utfbom/README.md
  vendor/github.com/dimchansky/utfbom/utfbom.go
  vendor/github.com/jaytaylor/html2text/.gitignore
  vendor/github.com/jaytaylor/html2text/.travis.yml
  vendor/github.com/jaytaylor/html2text/LICENSE
  vendor/github.com/jaytaylor/html2text/README.md
  vendor/github.com/jaytaylor/html2text/html2text.go
  vendor/github.com/mattermost/html2text/README.md
  vendor/github.com/mattermost/html2text/html2text.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.mkd
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/olekukonko/tablewriter/.gitignore
  vendor/github.com/olekukonko/tablewriter/.travis.yml
  vendor/github.com/olekukonko/tablewriter/LICENCE.md
  vendor/github.com/olekukonko/tablewriter/README.md
  vendor/github.com/olekukonko/tablewriter/csv.go
  vendor/github.com/olekukonko/tablewriter/table.go
  vendor/github.com/olekukonko/tablewriter/table_with_color.go
  vendor/github.com/olekukonko/tablewriter/util.go
  vendor/github.com/olekukonko/tablewriter/wrap.go
  vendor/github.com/ssor/bom/.travis.yml
  vendor/github.com/ssor/bom/LICENSE
  vendor/github.com/ssor/bom/README.md
  vendor/github.com/ssor/bom/bom.go
Labels: 3: Ready to Merge

#8956 Release 5.0 merge to master 20180615
  app/oauth.go
  i18n/en.json
  store/sqlstore/team_store.go
Labels: 2: Dev Review

#8940 Small translation fixes
  app/email.go
  app/email_batching.go
  i18n/en.json
Labels: 3: Ready to Merge

#8861 MM-6992 Added highlighting to elasticsearch results
  api4/post.go
  app/post.go
  einterfaces/elasticsearch.go
  i18n/en.json
  model/client4.go
  model/post_search_results.go
Labels: 3: Ready to Merge

#8959 Add missed translations
  api4/system_test.go
  api4/user.go
  i18n/en.json
  model/cluster_discovery.go
  model/config.go
  model/incoming_webhook.go
  store/sqlstore/cluster_discovery_store.go
  utils/file_backend.go
  utils/file_backend_local.go
  utils/file_backend_s3.go
Labels: 3: Ready to Merge

#8963 translations PR 20180619
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, Localization

#8928 MM-10233: Add scheme importing to bulk importer.
  app/apptestlib.go
  app/import.go
  app/import_test.go
  app/role.go
  app/scheme.go
  app/team.go
  i18n/en.json
  model/scheme.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_schemes.go
  store/redis_supplier_schemes.go
  store/sqlstore/scheme_supplier.go
  store/store.go
  store/storetest/mocks/AuditStore.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ClusterDiscoveryStore.go
  store/storetest/mocks/CommandStore.go
  store/storetest/mocks/CommandWebhookStore.go
  store/storetest/mocks/ComplianceStore.go
  store/storetest/mocks/EmojiStore.go
  store/storetest/mocks/FileInfoStore.go
  store/storetest/mocks/JobStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/LicenseStore.go
  store/storetest/mocks/OAuthStore.go
  store/storetest/mocks/PluginStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/mocks/ReactionStore.go
  store/storetest/mocks/RoleStore.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/StatusStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/SystemStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/TokenStore.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/WebhookStore.go
  store/storetest/scheme_store.go
Labels: 3: Ready to Merge

#8973 MM-10730 Added support for empty environment variables to viper
  Gopkg.lock
  Gopkg.toml
  utils/config_test.go
  vendor/github.com/mattermost/viper/flags_test.go
  vendor/github.com/mattermost/viper/overrides_test.go
  vendor/github.com/mattermost/viper/remote/remote.go
  vendor/github.com/mattermost/viper/util_test.go
  vendor/github.com/mattermost/viper/viper.go
  vendor/github.com/mattermost/viper/viper_test.go
Labels: 2: Dev Review

#8975 fix typo in en.json and remove trailing spaces
  i18n/en.json
  store/sqlstore/cluster_discovery_store.go
Labels: 2: Dev Review

#8977 Add back the ability to reply to push notifications in iOS
  app/notification.go
Labels: 3: Ready to Merge

#8970 Fixing mentionBg typo in import_test.go
  app/import_test.go
Labels: 2: Dev Review

#8967 MM-10425 Include active_channel in cluster update user status messages
  app/status.go
  model/status.go
  model/status_test.go
Labels: 2: Dev Review

#8968 MM-10370: serve subpath
  api4/file.go
  api4/oauth.go
  app/app.go
  app/server.go
  cmd/mattermost/commands/config.go
  utils/api.go
  utils/api_test.go
  utils/subpath.go
  utils/subpath_test.go
  web/context.go
  web/handlers.go
  web/static.go
  web/subpath_test.go
  web/web.go
Labels: 2: Dev Review

#8980 Using i18n extract to generate the i18n/en.json file
  i18n/en.json
Labels: 2: Dev Review

#8966 MM-8810: Add CSV Compliance export
  cmd/mattermost/commands/message_export.go
  cmd/mattermost/commands/message_export_test.go
  cmd/mattermost/commands/sampledata.go
  einterfaces/message_export.go
  i18n/en.json
  model/config.go
  model/message_export.go
  store/sqlstore/compliance_store.go
  utils/file_backend.go
  utils/file_backend_local.go
  utils/file_backend_s3.go
Labels: 3: Ready to Merge

#8983 MM-8716: Security Update Check URL should have recognisable name.
  app/security_update_check.go
Labels: 2: Dev Review

#8982 Fix plugins serving after subpath changes
  web/static.go
Labels: 3: Ready to Merge

#8976 MM-10570: Make permissions reset command clear custom role assignments.
  app/permissions.go
  i18n/en.json
  store/sqlstore/channel_store.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#9009 MM-11008: Fix translation and change the code to be auto-extracted
  app/channel.go
  i18n/en.json
Labels: 2: Dev Review

#8953 MM-10833: send down computed channel props
  api4/channel.go
  app/channel.go
  app/channel_test.go
  model/channel.go
  model/channel_mentions.go
  model/post.go
Labels: 3: Ready to Merge

#9010 MM-11034: Reply properly to incomming webhooks on errors
  web/handlers.go
  web/web.go
Labels: 3: Ready to Merge

#8972 Simplify oauth
  api4/oauth_test.go
  app/oauth.go
  einterfaces/oauthproviders.go
  model/gitlab/gitlab.go
Labels: 2: Dev Review

#9012 Lock bulk importing to master database node
  app/import.go
  store/layered_store.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
Labels: 2: Dev Review

#8998 translations PR 20180625
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#8999 MM-9674 Add plugin API for publishing custom WebSocket events
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
Labels: 3: Ready to Merge

#8984 MM-10910 fix join and open channel commands to work with tilde
  app/command_join.go
  app/command_join_test.go
Labels: 3: Ready to Merge

#8971 Gfycat integration
  config/default.json
  model/config.go
  utils/config.go
Labels: 2: Dev Review, Awaiting PR

#8988 MM-7088 Reset status to away after web conn disconnect if necessary
  app/session.go
  app/status.go
  app/web_conn.go
  app/web_hub.go
Labels: 2: Dev Review

#8987 Add english missed texts to i18n/en.json
  app/import.go
  i18n/en.json
  store/sqlstore/user_access_token_store.go
Labels: 3: Ready to Merge

#9004 MM - 10286: Make ConnMaxLifetime configurable
  app/diagnostics.go
  config/default.json
  i18n/en.json
  model/config.go
  store/sqlstore/supplier.go
  store/sqlstore/supplier_test.go
  store/storetest/docker.go
Labels: 3: Ready to Merge

#9017 MM-11036: subpath: rewrite manifest.json too
  utils/subpath.go
  utils/subpath_test.go
Labels: 3: Ready to Merge

#9015 remove redundant checks in build.mk
  build/release.mk
Labels: 3: Ready to Merge

#9018 MM-10980: Conditionally filters User json properties.
  api4/user.go
  api4/user_test.go
Labels: 3: Ready to Merge

#9028 Make import compatible with scheme-roles.
  app/import.go
  app/import_test.go
Labels: 3: Ready to Merge

#9019 MM-10972 Ignore | characters in postgres channel search
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 2: Dev Review
