Repository mattermost/mattermost, pull requests merged in 2019-05, with the labels that each got.

#10742 MM-15291: migrate commandStore.Delete to sync by default
  app/command.go
  store/sqlstore/command_store.go
  store/store.go
  store/storetest/command_store.go
  store/storetest/mocks/CommandStore.go
Labels: 3: Reviews Complete

#10773 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#10711 [MM-15192] Migrate "WebHook.AnalyticsOutgoingCount" to Sync by default
  app/analytics.go
  app/diagnostics.go
  store/sqlstore/webhook_store.go
  store/store.go
  store/storetest/mocks/WebhookStore.go
  store/storetest/webhook_store.go
Labels: 3: Reviews Complete

#10749 Remove outdated information from contributing file
  CONTRIBUTING.md
Labels: 3: Reviews Complete

#10784 Fixing flaky test in view members
  app/user_viewmembers_test.go
Labels: 2: Dev Review

#10778 MM-14139: Creating permissions for invite/promote/demote guests
  app/app_test.go
  app/permissions_migrations.go
  model/permission.go
  model/role.go
Labels: 2: Dev Review

#10493 [MM-12958] Support running two Mattermost instances on the same domain using subpaths
  api4/user.go
  api4/user_test.go
  app/login.go
  app/oauth.go
  app/oauth_test.go
  web/context.go
  web/handlers_test.go
Labels: 3: Reviews Complete

#10775 MM-14686 Send all image proxy requests through /api/v4/image
  api4/image.go
  api4/image_test.go
  app/post_metadata_test.go
  app/post_test.go
  services/imageproxy/atmos_camo.go
  services/imageproxy/atmos_camo_test.go
  services/imageproxy/imageproxy.go
  services/imageproxy/imageproxy_test.go
  services/imageproxy/local.go
  services/imageproxy/local_test.go
Labels: 3: Reviews Complete

#10672 [MM-14719] convert users to bots through cmd
  app/bot.go
  app/bot_test.go
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  model/bot.go
  model/bot_test.go
Labels: 2: Dev Review

#10739 MM-15288: Migrate CommandStore.Get to sync by default
  app/command.go
  app/webhook.go
  cmd/mattermost/commands/commandargs.go
  store/sqlstore/command_store.go
  store/store.go
  store/storetest/command_store.go
  store/storetest/mocks/CommandStore.go
Labels: 3: Reviews Complete

#10542 Adding EnsureBot plugin helper.
  Makefile
  plugin/api.go
  plugin/client.go
  plugin/client_rpc.go
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/plugintest/example_hello_user_test.go
  plugin/plugintest/helpers.go
Labels: 2: Dev Review

#10792 Adding invite guest api endpoint
  api4/team.go
  api4/team_test.go
  app/email.go
  app/team.go
  app/team_test.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/client4.go
  model/guest_invite.go
  store/sqlstore/tokens_store.go
  store/sqlstore/upgrade.go
  templates/invite_body.html
Labels: 3: Reviews Complete

#10704 MM 15185 - Migrate "WebHook.GetOutgoingByChannel" to Sync by default
  app/channel.go
  app/webhook.go
  store/sqlstore/webhook_store.go
  store/store.go
  store/storetest/mocks/WebhookStore.go
  store/storetest/webhook_store.go
Labels: 3: Reviews Complete, Awaiting Submitter Action

#10785 MM-15328 Fix panic in markdown link parsing
  utils/markdown/autolink.go
  utils/markdown/autolink_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10804 Change Channel.GetChannelUnread to sync
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#10741 MM-15290: Migrate commandStore.GetByTrigger to sync by default
  cmd/mattermost/commands/commandargs.go
  store/sqlstore/command_store.go
  store/store.go
  store/storetest/command_store.go
  store/storetest/mocks/CommandStore.go
Labels: 3: Reviews Complete

#10780 [MM-13033] Continue bulk import on large image error
  app/import.go
  app/import_functions.go
  app/import_test.go
Labels: 3: Reviews Complete

#10799 translations PR 20190506
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#10810 MM-15261: Do not remove bot accounts from teams or channels.
  store/sqlstore/group_supplier.go
  store/storetest/group_supplier.go
Labels: 3: Reviews Complete

#10781 [MM-13507] Plugin framework: auto-restart plugins that crash
  app/server.go
  config/default.json
  model/config.go
  plugin/environment.go
  plugin/health_check.go
  plugin/health_check_test.go
  plugin/supervisor.go
Labels: 2: Dev Review

#10732 [GH-10203] Import threads from Slack and some other small fixes
  app/slackimport.go
Labels: 2: Dev Review

#10813 Update team_test.go
  api4/team_test.go
  app/plugin_api_test.go
Labels: 3: Reviews Complete

#10812 [MM-15164] Add group commands
  cmd/mattermost/commands/group.go
  cmd/mattermost/commands/group_test.go
  store/sqlstore/group_supplier.go
Labels: 2: Dev Review

#10801 [MM-15193] Migrate "Emoji.Get" to Sync by default
  app/emoji.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 2: Dev Review

#10793 Support webapp to render post rapidly for bot without additional call for user/bot.
  app/post.go
Labels: 3: Reviews Complete

#10701 MM-15162: Changes for LDAP groups removals.
  api4/group.go
  api4/group_test.go
  api4/ldap.go
  app/group.go
  app/group_test.go
  app/ldap.go
  cmd/mattermost/commands/group.go
  einterfaces/ldap.go
  i18n/en.json
  model/client4.go
  model/group.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_groups.go
  store/redis_supplier_groups.go
  store/sqlstore/group_supplier.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  utils/merge_test.go
  web/params.go
Labels: 3: Reviews Complete

#10830 GH-10760: Migrate Post.Delete to sync by default
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10795 MM-14723: Add config flag for creating bots
  api4/bot.go
  api4/bot_test.go
  api4/user_test.go
  i18n/en.json
  model/config.go
Labels: 3: Reviews Complete

#10823 Tracking Push Notifications in a structured logger (notifications.log)
  api4/system.go
  app/app.go
  app/notification.go
  app/notification_push.go
  app/options.go
  app/server.go
  config/default.json
  i18n/en.json
  model/config.go
  model/push_notification.go
  store/layered_store.go
  store/sqlstore/notification_registry_store.go
  store/sqlstore/notification_registry_store_test.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/NotificationRegistryStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/notification_registry_store.go
  store/storetest/store.go
  utils/logger.go
Labels: 2: Dev Review

#10820 MM-15367 Do not try to render web app 404 error page when web server is disabled
  app/app.go
  web/web.go
Labels: 3: Reviews Complete

#10819 Log status code when failing to authenticate with OAuth provider
  app/oauth.go
  app/oauth_test.go
Labels: 3: Reviews Complete

#10836 MM-15320/MM-15518 When gzipping file responses add header for uncompressed content length
  api4/file.go
Labels: 3: Reviews Complete

#10808 MM-14722 - Don't let bots create other bot accounts
  api4/bot.go
  api4/bot_test.go
  app/plugin_api.go
  app/plugin_api_test.go
  i18n/en.json
  model/permission.go
Labels: 3: Reviews Complete

#10845 [MM-15493] Add Error and Help to reserved name list
  model/utils.go
Labels: 3: Reviews Complete

#10815 [MM-15356] Migrate "Channel.Update" to Sync by default
  api4/scheme_test.go
  app/channel.go
  app/import_functions.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#10824 10796 escaping file name to allow for special chars
  scripts/test.sh
Labels: 3: Reviews Complete

#10839 translations PR 20190513
  i18n/fr.json
  i18n/pl.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#10811 [MM-15297] Migrate "Preference.Get" to Sync by default #10721
  app/email_batching.go
  app/notification_email.go
  app/notification_push.go
  app/preference.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete

#10803 [GH-10800] convert bot account to user account
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  store/sqlstore/bot_store.go
  store/storetest/bot_store.go
Labels: 3: Reviews Complete

#10827 upgrade db to 5.11.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#10847 made the preference store GetCategory method sync
  app/import_test.go
  app/preference.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 2: Dev Review

#10826 update db to 5.11
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#10849 MM-14723: Add CreateBotAccounts to client.go
  config/client.go
Labels: 2: Dev Review

#10794 MM-14897: Changes to be able to add and remove groups from channels.
  api4/group.go
  api4/group_test.go
  app/group.go
  app/group_test.go
  cmd/mattermost/commands/group.go
  model/client4.go
  model/group.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_groups.go
  store/redis_supplier_groups.go
  store/sqlstore/group_supplier.go
  store/store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  web/params.go
Labels: 3: Reviews Complete

#10851 Adding default channels to users on promte from guest
  api4/user.go
  app/user.go
  app/user_test.go
Labels: 3: Reviews Complete

#10848 MM-13142 Replace mlog.Any with mlog.Err
  app/opengraph.go
  app/post_metadata.go
Labels: 3: Reviews Complete

#10837 Migrate FileInfo store to Sync by default
  api4/file_test.go
  app/file.go
  app/file_bench_test.go
  app/file_test.go
  app/import_functions.go
  app/import_test.go
  app/notification.go
  app/notification_email.go
  app/plugin_api_test.go
  app/post.go
  app/post_test.go
  app/slackimport.go
  app/user.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#10678 [MM-14751] Adds group_constrained filter to user list and search endpoints
  api4/user.go
  app/user.go
  app/user_viewmembers_test.go
  model/user_get.go
  model/user_search.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#10835 made the Restore and Delete store method to be sync
  app/channel.go
  cmd/mattermost/commands/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10853 MM-15632 DeleteEphemeralMessage to accept a `postId string`
  app/plugin_api.go
  app/post.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Reviews Complete

#10846 [MM-10768] Migrate "Channel.SaveDirectChannel" to Sync by default
  app/channel.go
  app/import.go
  app/import_functions.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#10829 Migrate Overwrite and GetMaxPostSize() in PostStore to sync by default
  app/import_functions.go
  app/post.go
  app/post_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review, 3: Reviews Complete

#10855 MM-15485: In-channel system behaviour for at-mentions and slash commands for group-constrained channels.
  api4/channel.go
  api4/team.go
  app/channel.go
  app/command_invite.go
  app/command_remove.go
  app/notification.go
  app/team.go
  cmd/mattermost/commands/group.go
  i18n/en.json
  model/channel.go
  model/team.go
Labels: 2: Dev Review

#10513 MM-11701 Log request ID for outgoing webhooks
  web/webhook.go
Labels: 2: Dev Review

#10492 MM-10867 Split GetExplicitMentions function to several smaller ones
  app/notification.go
  app/notification_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10790 Migrate Roles Layered store to Sync by default
  api4/role_test.go
  app/import_functions_test.go
  app/migrations.go
  app/permissions.go
  app/permissions_migrations.go
  app/role.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_roles.go
  store/redis_supplier_roles.go
  store/sqlstore/role_supplier.go
  store/sqlstore/scheme_supplier.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/RoleStore.go
  store/storetest/role_store.go
  store/storetest/scheme_store.go
Labels: 2: Dev Review

#10867 Add two missing bot settings to default.json
  config/default.json
Labels: 2: Dev Review

#10833 MM-14874 - Google SSO: Migrate user API endpoint from Google+ API to People API
  config/default.json
  tests/test-config.json
Labels: 3: Reviews Complete, Docs/Needed

#10860 [MM-15300] Migrate "Preference.PermanentDeleteByUser" to Sync by default
  app/user.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10869 MM-15494 Adding warning log when someone has configured a Mattermost push proxy with HTTP endpoint
  app/server.go
Labels: 2: Dev Review

#10895 Revert "MM-10867 Split GetExplicitMentions function to several smalle…
  app/notification.go
  app/notification_test.go
Labels: 2: Dev Review, CherryPick/Approved

#10658 [MM-15067] Permit Bot accounts to create user access tokens if Enable Personal Access Tokens set to "false"
  app/session.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10857 [MM-15641] Set stricter caching policy for file downloads
  api4/file.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10838 Migrate System store to Sync by default
  app/app.go
  app/config.go
  app/config_test.go
  app/diagnostics.go
  app/import_functions_test.go
  app/license.go
  app/migrations.go
  app/permissions.go
  app/permissions_migrations.go
  app/permissions_test.go
  app/scheme.go
  app/security_update_check.go
  migrations/migrations.go
  migrations/migrations_test.go
  migrations/worker.go
  store/sqlstore/supplier.go
  store/sqlstore/system_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
  store/store.go
  store/storetest/mocks/SystemStore.go
  store/storetest/system_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#10897 [MM-15497] Review error logging
  app/channel.go
  app/opengraph.go
  app/web_conn.go
Labels: 2: Dev Review

#10831 GH-10761: Migrate Post.Get to sync by default
  app/file.go
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
Labels: 2: Dev Review

#10844 [MM-15490] Rework default password requirements
  api4/apitestlib.go
  app/authentication.go
  app/helper_test.go
  cmd/mattermost/commands/cmdtestlib.go
  config/default.json
  model/config.go
  utils/password.go
  utils/password_test.go
  web/web_test.go
Labels: 2: Dev Review

#10904 MM-15707 include missing localized strings
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#10868 Add missing diagnostics for 5.12
  app/diagnostics.go
  app/diagnostics_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10906 MM-15728: Fixing not initialized SchemeGuest field on bulk indexing query
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10908 MM-14721 - Add an identifier for compliance exports when a message is posted by a bot account
  model/channel_member_history_result.go
  model/message_export.go
  store/sqlstore/channel_member_history_store.go
  templates/globalrelay_compliance_export.html
  templates/globalrelay_compliance_export_message.html
  templates/globalrelay_compliance_export_participant_row.html
Labels: 2: Dev Review

#10899 MM-15035: Read from file infos from master on post creation
  api4/post.go
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/post_test.go
  app/reaction.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10892 MM-15480: Add server support for Range on files
  api4/file.go
  app/file.go
  services/filesstore/filesstore.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
Labels: 3: Reviews Complete

#10910 MM-15741: Omit Reply-To email header if EmailSettings.ReplyToAddress …
  services/mailservice/mail.go
  services/mailservice/mail_test.go
Labels: 3: Reviews Complete

#10859 MM-15542 Change getPostsBefore/After to include all posts in each thread
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review, CherryPick/Approved

#10911 [MM-15503] Stop exposing plugin's SettingsSchema in api/v4/plugins/webapp
  api4/plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10875 MM-15662: Rename "CreateBotAccounts" config.json setting to "EnableBotAccountCreation"
  api4/bot.go
  api4/bot_test.go
  api4/user_test.go
  app/diagnostics.go
  config/client.go
  config/default.json
  model/config.go
Labels: 2: Dev Review, CherryPick/Approved

#10858 [MM-15305] Migrate Preference.CleanupFlagsBatch to Sync by default
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete, Do Not Merge

#10919 Fixing Elasticsearch indexing
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10876 Migrate User.PermanentDelete to Sync by default
  app/bot.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/bot_store.go
  store/storetest/mocks/UserStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#10920 Add support for tracing in LDAP
  model/config.go
Labels: 2: Dev Review

#10903 MM-15422: Adds new parameters for retrieving pages of channels.
  api4/channel.go
  app/channel.go
  app/channel_test.go
  i18n/en.json
  model/channel.go
  model/channel_search.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  web/params.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10907 [MM-15639] Add config setting to explicitly define which IP headers are trusted
  app/app.go
  app/plugin_requests.go
  app/ratelimit.go
  app/ratelimit_test.go
  app/server.go
  config/default.json
  model/config.go
  utils/utils.go
  utils/utils_test.go
  web/handlers.go
  web/web.go
Labels: 3: Reviews Complete, CherryPick/Approved, Docs/Needed

#10852 [MM-11287] Add support for plus sign and period/dot in custom URL schemes (#9155)
  model/config.go
  model/config_test.go
Labels: 3: Reviews Complete

#10866 [MM-15296] Migrate "Preference.Save" to Sync by default
  app/channel.go
  app/command_expand_collapse.go
  app/email_batching_test.go
  app/export_test.go
  app/import_functions.go
  app/oauth.go
  app/preference.go
  app/user.go
  store/sqlstore/preference_store.go
  store/sqlstore/preference_store_test.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/oauth_store.go
  store/storetest/post_store.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete

#10798 [MM-15370] Add /test post command to post a message as different user to a channel/team
  app/command_loadtest.go
Labels: 3: Reviews Complete

#10940 [MM-15304] Migrate "Preference.DeleteCategoryAndName" to Sync by default
  app/post.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete

#10871 MM-15354: Migrate Channel.Save to sync by default
  api4/scheme_test.go
  app/channel.go
  app/slackimport.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#10948 [MM-15803] Migrate "Session.AnalyticsSessionCount" to Sync by default
  app/analytics.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#10928 [MM-8421] Special PR to have parseImages return nil when format is tiff
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Reviews Complete

#10942 Migrate User.Update method to sync by default
  app/bot.go
  app/user.go
  model/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/bot_store.go
  store/storetest/channel_store.go
  store/storetest/mocks/UserStore.go
  store/storetest/post_store.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#10927 [MM-15303] Migrate "Preference.DeleteCategory" to Sync by default
  app/team.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete

#10954 MM-15796 Migrate "Session.GetSessionsWithActiveDeviceIds" to Sync by default
  app/notification_push.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#10945 [MM-15301] Migrate "Preference.IsFeatureEnabled" to Sync by default
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 2: Dev Review

#10946 Migrate Groups to not use the Layered store
  model/cluster_message.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier.go
  store/local_cache_supplier_groups.go
  store/redis_supplier_groups.go
  store/sqlstore/group_supplier.go
  store/sqlstore/supplier.go
Labels: 3: Reviews Complete

#10950 MM-15784: Prevents non-private channels from being group-constrained …
  cmd/mattermost/commands/group.go
  cmd/mattermost/commands/group_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10953 MM-15202 Preventing failed plugins webapp components from being served.
  plugin/environment.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10989 Trim leading and trailing spaces for search terms
  app/channel.go
  app/post.go
  app/user.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10925 [MM-15767] Limit exposure of any information about the user status on login failure
  api4/user.go
  api4/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10988 MM-15706: disable PluginHealthCheck_RPCPingFail test
  plugin/health_check_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10918 MM-15371: allow config show --json
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 3: Reviews Complete

#10993 MM-15845 migrating perm delete by channel to sync
  app/channel.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10962 [GH-10866] Preferrence.Save - Remove preference length return arg
  app/channel.go
  app/command_expand_collapse.go
  app/email_batching_test.go
  app/export_test.go
  app/import_functions.go
  app/oauth.go
  app/preference.go
  app/user.go
  store/sqlstore/preference_store.go
  store/sqlstore/preference_store_test.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/oauth_store.go
  store/storetest/post_store.go
  store/storetest/preference_store.go
Labels: 3: Reviews Complete

#10996 MM-15848 migrating getFlaggedPostsForTeam to sync by default
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10995 MM-15847 migrating getFlaggedPosts to sync by default
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10955 [MM-15194] Store: Migrate Emoji.Save to Sync as default #10642
  app/emoji.go
  app/helper_test.go
  app/import_functions.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 3: Reviews Complete

#10991 MM-15842 making post.update() sync by default
  app/file.go
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10992 MM-15843 migrating post.GetSingle() to sync by default
  app/integration_action.go
  app/integration_action_test.go
  app/plugin_hooks_test.go
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10994 MM-15846 migrating get posts to sync by default
  app/channel_test.go
  app/file.go
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11008 [MM-15637] Add Trace config option to the Elasticsearch block
  app/diagnostics.go
  model/config.go
Labels: 3: Reviews Complete

#10944 #10939 Migrate "Session.Save" to Sync by default
  app/oauth.go
  app/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/oauth_store.go
  store/storetest/session_store.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#10999 MM-15835: correct errors and content types for oauth api calls
  app/oauth.go
  web/handlers.go
  web/web.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10961 Adding Content-Type header to the OAuth complete endpoint
  api4/oauth.go
Labels: 3: Reviews Complete

#10998 Migrate Groups store to sync by default (GetGroups and Counts)
  app/group.go
  store/sqlstore/group_supplier.go
  store/store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/GroupStore.go
Labels: 3: Reviews Complete

#11009 Fix #10963: GetDirectPostParentsForExportAfter is sync now
  app/export.go
  app/export_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10990 MM-15794 Migrate "Session.Get" to Sync by default
  app/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/oauth_store.go
  store/storetest/session_store.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#11019 Change ES trace config type from boolean to string
  config/default.json
  model/config.go
Labels: 3: Reviews Complete

#11003 Migrate Store groups to sync by default (GroupSyncable methods)
  app/group.go
  store/sqlstore/group_supplier.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/GroupStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11024 MM-15956: consistent params for config migrate
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11011 Fix #10975. GetEtag is sync now
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review
