Repository mattermost/mattermost, pull requests merged in 2019-06, with the labels that each got.

#11027 MM-15777 Preventing bad email configuration from failing personal access token creation
  app/session.go
Labels: 3: Reviews Complete

#11038 [MM-15799] Migrate "Session.PermanentDeleteSessionsByUser" to Sync by default
  app/user.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#10926 Change the implementation of GetAll() in `preference_store.go` to ret…
  app/preference.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 2: Dev Review

#11010 Fix #10979. GetFlaggedPostsForChannel is sync now
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11017 [MM-15802] Migrate "Session.UpdateDeviceId" to Sync by default
  app/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#11029 Migrate "Post.GetParentsForExportAfter" to Sync by default #10965
  app/export.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#11025 MM-15882 Switching to new ci for prepackaged plugins and stripping alternate platform binaries.
  Makefile
  build/release.mk
Labels: 2: Dev Review, CherryPick/Approved

#11023 MM-15947: Prevents new user creation with invite link to group-constr…
  api4/user_test.go
  app/user.go
Labels: 2: Dev Review, CherryPick/Approved

#11040 MM-15819 Add Autolink as a prepackaged plugin
  Makefile
  build/release.mk
Labels: 3: Reviews Complete, CherryPick/Approved

#11048 Add welcomebot and aws-SNS to prepackaged plugins
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11043 Upgrading schema version to 5.12.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11044 Add jirav2 to prepackaged plugins.
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11042 MM-15820 Add github to prepackaged plugins.
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11041 MM-15817 Add custom-attributes as a bundled plugin
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#10483 [MM-13745] Add mattermost-plugin-nps to prepackaged
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11026 MM-15833 Add new pre-packaged plugins to telemetry diagnostics
  app/diagnostics.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11000 MM - 15795 Migrate "Session.GetSessions" to Sync by default
  app/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#10905 Add Slack corporate import ability
  app/slackimport.go
  app/slackimport_test.go
  tests/slack-import-test-direct-messages.json
  tests/slack-import-test-group-direct-messages.json
  tests/slack-import-test-private-channels.json
Labels: 3: Reviews Complete

#11021 [MM-15858] Migrate "Post.GetPostsCreatedAt" to Sync by default
  app/import_functions.go
  app/import_functions_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11034 [MM-15859] Migrate "Post.GetPostsByIds" to Sync by default
  app/import_test.go
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#10952 [MM-15836] Fix redirect after OAuth login
  api4/oauth.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11060 Issue 11030: fix HasFile to avoid false positives for no filename
  config/database_test.go
  config/file.go
  config/file_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10921 #10883 adding const error string DismissPostError to be returned by MessageWillBePosted
  app/post.go
  plugin/hooks.go
  store/sqlstore/post_store.go
Labels: 3: Reviews Complete

#11050 [MM-16005] Check listOfAllowedChannels to be a not nil empty slice
  app/user.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11037 [MM-15798] Migrate Session.RemoveAllSessions to Sync by default
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#10551 [MM-14400] Programmatically generate default.json
  Makefile
  build/Jenkinsfile.k8s
  build/Jenkinsfile.pr
  build/release.mk
  config/config_generator/generator/generator.go
  config/config_generator/main.go
  config/database_test.go
  config/default.go
  config/default.json
  config/default_test.go
  config/file_test.go
  config/memory_test.go
  model/config.go
  model/config_test.go
  services/filesstore/s3store.go
  testlib/resources.go
Labels: 2: Dev Review

#11046 MM-15864 - Made Post.GetRepliesForExport sync
  app/export.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11068 Mobile sessions to be excluded from idle timeout
  app/session.go
  app/session_test.go
Labels: 2: Dev Review

#11073 Update NPS plugin to 1.0.0-rc2
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11066 MM-16001 Adding bot description field to bot users.
  model/user.go
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11018 MM-15730: Send down the Position attribute mapping in client config.
  config/client.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11076 Bump prepackaged github version to 0.10.1
  Makefile
Labels: 3: Reviews Complete, CherryPick/Candidate

#11074 zoom v1.0.6 -> v1.0.7
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11075 Updated prepackaged Jira plugin version to 2.0.1
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11035 MM-15850/MM-15851 GetPosts Before/After sync by default
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11072 prepare upgrade to 5.13
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#11031 GH-10968 Migrate 'Post.GetPostsBatchForIndexing' to Sync by default
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11077 MM-16114 Preventing plugin startup failure if bot account already exists as regular user.
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
Labels: 2: Dev Review, CherryPick/Approved

#11033 GH-10967 Migrate Post.PermanentDeleteBatch to Sync by default
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Awaiting Submitter Action

#11099 Bump prepackaged github version to 0.10.2
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11051 [MM-15767] Mask errors in login flow only explicitly
  api4/user.go
  api4/user_test.go
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#11104 [MM-16160] Migrate Team.SearchByName to Sync by default
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11101 [MM-15302] Migrate `Preference.Delete` to Sync by default #10715
  app/oauth.go
  app/preference.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
Labels: 2: Dev Review

#11081 MM-14712 - Add support for signing SAML requests
  app/diagnostics.go
  model/config.go
Labels: 2: Dev Review

#11107 [MM-16159] Migrate "Team.GetByName" to Sync by default
  app/channel.go
  app/email_batching.go
  app/import_functions.go
  app/team.go
  cmd/mattermost/commands/teamargs.go
  output
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#10532 Truncate data from OpenGraph metadata
  app/post_metadata.go
  app/post_metadata_test.go
  model/link_metadata.go
  model/link_metadata_test.go
Labels: 2: Dev Review

#11113 Disable plugin health check process check test
  plugin/health_check_test.go
Labels: 2: Dev Review

#11112 MM-16154: Allow to have town-square in ExperimentalDefaultChannels
  app/channel.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11078 GH-10932 Migrate 'Session.UpdateLastActivityAt' to Sync by default
  app/session.go
  app/session_test.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 3: Reviews Complete

#11111 Migrate "Team.UpdateDisplayName" to Sync by default #11096
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#10917 MM-15325: Allowing to configure the device for detect the IP in HA clusters
  model/cluster_discovery.go
  model/cluster_discovery_test.go
  model/config.go
  model/utils.go
  model/utils_test.go
Labels: 3: Reviews Complete

#11012 Fix #10973. AnalyticsUserCountsWithPostsByDay is sync now
  app/analytics.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11058 MM-15889 Add unit tests for CSRF checks
  api4/oauth.go
  api4/user.go
  api4/user_test.go
  app/authentication.go
  app/login.go
  web/handlers.go
  web/handlers_test.go
  web/saml.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11013 Fix #10972. AnalyticsPostCountsByDay is sync now
  app/analytics.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11131 Bumped Jira to 2.0.2
  Makefile
Labels: 2: Dev Review, CherryPick/Approved

#11110 translations PR 20190611
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#11135 [MM-16242] Unmask Account Lock Message
  api4/user.go
  api4/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#10941 Migrating User Store VerifyEmail, GetByAuth and GetByEmail functions to sync by default
  api4/apitestlib.go
  api4/user_test.go
  api4/websocket_test.go
  app/auto_users.go
  app/oauth.go
  app/slackimport.go
  app/user.go
  cmd/mattermost/commands/roles_test.go
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/userargs.go
  manualtesting/manual_testing.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11139 [MM-16184] Migrate "Team.GetChannelUnreadsForTeam" to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11036 Migrate Post.GetOldest to Sync by default
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11015 MM-15801 Migrate "Session.UpdateRoles" to Sync by default
  app/user.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
Labels: 3: Reviews Complete

#11136 Bumped Jira to 2.0.3
  Makefile
Labels: CherryPick/Approved

#11142 Migrate `Team.GetMembers` to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11145 Migrate Team.GetMembersByIds to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11149 [MM-16179] Migrate Team.GetTotalMemberCount to Sync by default #11120
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11056 MM-15844: migrate post PermanentDeleteByUser to sync by default #10984
  app/user.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Awaiting Submitter Action

#11062 [MM-14727] Modified App.Bot.CreateBot to create a new post to the bot…
  app/bot.go
  app/bot_test.go
  i18n/en.json
  model/post.go
Labels: 3: Reviews Complete

#11147 MM-16277 Update NPS plugin to v1.0.0
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11137 [MM-16171] Migrate "Team.GetByInviteId" to Sync by default
  app/team.go
  app/user.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11156 MM-16295 Properly disabling plugins that are not marked as running.
  app/plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11105 Fix bots being unable to post when personal access tokens are disabled.
  api4/user_test.go
  app/session.go
  model/session.go
  store/sqlstore/upgrade.go
  web/context.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11069 [MM-15797] Migrate Session.Remove to Sync by default
  app/oauth.go
  app/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
Labels: 2: Dev Review

#11151 MM-16260: Upgrading goexif library
  go.mod
  go.sum
  vendor/github.com/rwcarlsen/goexif/exif/exif.go
  vendor/github.com/rwcarlsen/goexif/exif/readerAt.go
  vendor/github.com/rwcarlsen/goexif/tiff/tag.go
  vendor/github.com/rwcarlsen/goexif/tiff/tiff.go
  vendor/modules.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#11138 MM-16228 Remove DisablePostMetadata setting
  app/diagnostics.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/post_test.go
  config/client.go
  model/config.go
Labels: 2: Dev Review, CherryPick/Approved

#11180 Bumped Jira to 2.0.4
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11045 [MM-15841] Store: Migrate "Post.Save" to Sync by default
  api4/apitestlib.go
  app/import_functions.go
  app/post.go
  app/slackimport.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/preference_store.go
  store/storetest/reaction_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11181 [MM-16167] Migrate "Team.GetAllPrivateTeamPageListing" to Sync by def…
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11129 Migrate "Post.GetPostsSince" to Sync by default #10976
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11039 MM-15569 Fixes failing test on TestGetPostsForChannelAroundLastUnread
  api4/post.go
  api4/post_test.go
  app/plugin_api.go
  app/post.go
  i18n/en.json
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#11132 [MM-16173] Migrate Team.AnalyticsTeamCount to Sync by default #11126
  app/analytics.go
  app/diagnostics.go
  app/helper_test.go
  app/import_functions_test.go
  app/security_update_check.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11141 Migrate `Team.GetMember` to Sync by default
  api4/apitestlib.go
  app/channel.go
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11109 [MM-16163] Migrate "Team.SearchPrivate" to Sync by default
  app/team.go
  output
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11182 Migrate Bots store to sync by default
  app/bot.go
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  store/sqlstore/bot_store.go
  store/store.go
  store/storetest/bot_store.go
  store/storetest/group_supplier.go
  store/storetest/mocks/BotStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11184 Bumped Jira to 2.0.5
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11063 MM-14721 - Add an identifier for compliance exports when a message is posted by a bot account
  model/compliance_post.go
  model/message_export.go
  store/sqlstore/compliance_store.go
Labels: 2: Dev Review

#11179 Migrate POST.AnalyticsPostCount to Sync by default
  app/analytics.go
  app/diagnostics.go
  app/import_functions_test.go
  app/import_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11146 Migrate Team.GetActiveMembersCount to Sync by default
  app/team.go
  i18n/en.json
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11097 Migrate Channel.AnalyticsTypeCount to Sync by default
  app/analytics.go
  app/diagnostics.go
  app/helper_test.go
  app/import_functions_test.go
  app/import_test.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11140 Migrate `Team.UpdateMember` to Sync by default
  api4/apitestlib.go
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11191 Bumped Jira to 2.0.6
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11047 Ongoing changes to notification.go
  app/notification.go
  app/notification_test.go
Labels: 3: Reviews Complete, Awaiting Submitter Action

#11183 Migrate Jobs store to sync by default
  api4/job_test.go
  app/job.go
  app/job_test.go
  jobs/jobs.go
  jobs/jobs_watcher.go
  migrations/helper_test.go
  migrations/migrations.go
  migrations/migrations_test.go
  store/sqlstore/job_store.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
Labels: 3: Reviews Complete

#11106 GH-11085 Migrate Team.GetAllTeamPageListing to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11190 Migrate Team.PermanentDelete to Sync by default #11128
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11148 Migrate Team.GetTeamsForUser to Sync by default
  app/team.go
  store/sqlstore/session_store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#10873 MM-15498 - removed redundant post_edited event on reaction change
  app/reaction.go
Labels: 3: Reviews Complete

#11176 MM-16258: Adds new API endpoint + (App & Client & Store) to retrieve …
  api4/team.go
  api4/team_test.go
  app/group.go
  model/client4.go
  model/user.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  web/params.go
Labels: 2: Dev Review

#11207 Channel.GetMoreChannels to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11210 Channel.GetChannelCounts to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11202 Migrate Channel.GetByNames to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11186 MM-16224: Adds new API endpoint + (App & Client & Store) to retrieve the difference between the set of channel members and given group members.
  api4/channel.go
  api4/channel_test.go
  app/group.go
  model/client4.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
Labels: 2: Dev Review

#11201 [MM-16165] Migrate Team.GetAllPage to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
Labels: 2: Dev Review

#11205 Channel.GetDeleted to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11229 Migrates Channel.AutocompleteInTeam, Channel.SearchInTeam and Channel.SearchMore
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11197 Migrate Channel.GetChannelsByIds to Sync by default
  app/channel.go
  app/user.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11211 Channel.GetTeamChannels to sync by default
  app/channel.go
  app/team.go
  app/user.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11198 upgrade db to 5.13 and prepare upgrade to 5.14
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11233 MM-15788: Unmasks errors related to max team members and accounts.
  api4/user.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11065 [MM-15811] Adds fallback mechanism for elasticsearch queries
  app/channel.go
  app/config.go
  app/post.go
  app/user.go
Labels: 3: Reviews Complete

#11248 [MM-11224] Migrate "Channel.GetAllChannelMembersNotifyPropsForChannel" to Sync by default
  app/notification.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11238 Migrates Channel.PermanentDeleteMembersByChannel to sync by default
  app/channel.go
  cmd/mattermost/commands/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11134 Migrate Channel.GetChannelsBatchForIndexing to Sync by default
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11269 Migrate Channel.UserBelongsToChannels to Sync by default
  app/user.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11271 Migrates Channel.GetChannelMembersForExport to sync by default
  app/export.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11245 Migrate "Channel.RemoveMember" to Sync by default
  app/channel.go
  app/team.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11270 Migrate Channel.RemoveAllDeactivatedMembers to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11242 Migrate Channel.GetChannelMembersTimezones to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11199 [MM-16330] Migrate "Channel.GetForPost" to Sync by default
  app/authorization.go
  app/integration_action.go
  app/post.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11274 Migrates Channel.ClearAllCustomRoleAssignments to sync by default
  app/permissions.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11279 MM-16465 Only enable NPS plugin by default if diagnostics are enabled
  model/config.go
  model/config_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11289 [MM-16353] Migrate Channel.AnalyticsDeletedTypeCount to Sync by default
  app/diagnostics.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11287 [MM-11259] Migrate 'Channel.GetMembersByIds' to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11228 [MM-11227] Migrate "Channel.GetMembers" to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11235 [MM-16182] Migrate Team.GetTeamsForUserWithPagination to Sync by default #11117
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11204 Migrates Channel.GetChannels to sync by default
  app/channel.go
  app/team.go
  manualtesting/manual_testing.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11244 Migrate Channel.GetMemberForPost to Sync by default
  app/authorization.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11208 Channel.GetPublicChannelsForTeam to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11277 Migrate Channel.MigrateChannelMembers to Sync by default
  migrations/advanced_permissions_phase_2.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11313 Migrate Emoji.Delete to Sync by default
  app/emoji.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 2: Dev Review

#11187 Migrates Channel.GetByName to sync by default
  app/channel.go
  app/channel_test.go
  app/command_join.go
  app/command_msg.go
  app/command_mute.go
  app/import_functions.go
  app/slackimport.go
  app/team.go
  app/webhook.go
  cmd/mattermost/commands/channelargs.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11188 [MM-16161] Migrate Team.SearchAll to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11246 [MM-11222] Migrate 'Channel.GetMemberCount' to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11206 Channel.GetAllChannels to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11272 Migrates Channel.GetAllDirectChannelsForExportAfter to sync by default
  app/export.go
  app/export_test.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11290 Run go get commands explicitly without modules
  Makefile
Labels: 3: Reviews Complete

#11317 [MM-16485] Migrate UserAccessToken.GetAll to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 2: Dev Review

#11316 [MM-16484] Migrate UserAccessToken.Get to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#11267 [MM-16032] Add system ping endpoint health checks
  api4/system.go
  api4/system_test.go
  model/client4.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
Labels: 2: Dev Review

#11275 Migrates Channel.ResetAllChannelSchemes to sync by default
  app/permissions.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11082 MM-2954 - Add a separate post type for /me messages and update formatting
  api4/commands_test.go
  app/command_me.go
  app/command_me_test.go
  model/post.go
Labels: 3: Reviews Complete

#11321 [MM-11301] Migrate 'UserAccessToken.GetByToken' to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#11203 Migrates Channel.GetDeletedByName to sync by default
  app/slackimport.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11284 [MM-16411] tagging the docker image using the sha instead of the PR number
  build/Jenkinsfile.pr
Labels: 3: Reviews Complete

#11309 [MM-11306] Migrate 'UserAccessToken.Save' to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#11324 made the emoji store getByName method sync
  app/emoji.go
  app/import_functions.go
  app/import_functions_test.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 3: Reviews Complete

#11322 [MM-11300 ] Migrate 'UserAccessToken.GetByUser' to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 3: Reviews Complete

#11333 [MM-16490] Migrate UpdateTokenDisable to Sync by default
  app/session.go
  store/sqlstore/user_access_token_store.go
  store/store.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/user_access_token_store.go
Labels: 2: Dev Review

#11319 Migrate OAuth store to sync by default
  api4/oauth_test.go
  app/oauth.go
  app/oauth_test.go
  app/user.go
  store/sqlstore/oauth_store.go
  store/store.go
  store/storetest/mocks/OAuthStore.go
  store/storetest/oauth_store.go
Labels: 2: Dev Review

#11349 MM-16439: Print config ordered by key alphabetically for easy diff.
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/utils.go
  cmd/mattermost/commands/utils_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11239 translations PR 20190617
  i18n/es.json
  i18n/it.json
  i18n/ja.json
  i18n/pl.json
  i18n/ro.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 3: Reviews Complete
