Repository mattermost/mattermost, pull requests merged in 2019-08, with the labels that each got.

#11738 MM-17224 - Bulk export fails due to missing user
  app/export.go
  app/export_test.go
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#11758 Automated cherry pick of #11684
  app/plugin_hooks_test.go
Labels: AutomatedCherryPick/Done

#11757 Automated cherry pick of #11712
  app/webhook_test.go
Labels: AutomatedCherryPick/Done

#11756 Automated cherry pick of #11715
  store/storetest/channel_store.go
Labels: AutomatedCherryPick/Done

#11768 Automated cherry pick of #11738
  app/export.go
  app/export_test.go
Labels: AutomatedCherryPick/Done

#11736 MM-17411: fix err != nil check
  services/mfa/mfa.go
  services/mfa/mfa_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11766 MM-17426 Properly specify multiple Accept headers for post metadata
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11774 Automated cherry pick of #11766
  app/post_metadata.go
  app/post_metadata_test.go
Labels: AutomatedCherryPick/Done

#11609 Time Layer for measure the Store methods calls time
  Makefile
  app/server_app_adapters.go
  cmd/mattermost/commands/version.go
  einterfaces/metrics.go
  store/layer_generators/main.go
  store/layered_store.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
  store/timer_layer.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR, Docs/Needed

#11782 upgrade db to 5.14
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#10872 MM 7971 dockerhost -> localhost && docker -> docker-compose
  Makefile
  api4/apitestlib.go
  api4/system_test.go
  api4/team_test.go
  build/docker-compose.yml
  build/legacy.mk
  build/release.mk
  cmd/mattermost/commands/config.go
  config/database.go
  model/config.go
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
  services/filesstore/filesstore_test.go
  services/mailservice/inbucket.go
  store/storetest/settings.go
  tests/test-config.json
Labels: 3: Reviews Complete

#11737 MM-17117: Updates einterface for FirstLoginSync.
  einterfaces/ldap.go
  einterfaces/mocks/LdapInterface.go
Labels: 2: QA Review, CherryPick/Approved, Do Not Merge/Awaiting PR

#11772 Automated cherry pick of #11736
  services/mfa/mfa.go
  services/mfa/mfa_test.go
Labels: AutomatedCherryPick/Done

#11769 update sampledata users passwords
  Makefile
  cmd/mattermost/commands/sampledata.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11785 Tweak docker compose setup
  Makefile
  app/plugin_test.go
  build/Jenkinsfile.pr
  build/docker-compose.yml
  build/legacy.mk
Labels: 2: Dev Review

#11770 MM-16366 - Prevent attachment duplication on import
  app/import_functions.go
  app/import_functions_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11792 Automated cherry pick of #11770
  app/import_functions.go
  app/import_functions_test.go
Labels: AutomatedCherryPick/Done

#11598 [MM-16856] Allow account related mails to be sent with notifications disabled
  app/email.go
Labels: 3: Reviews Complete, Docs/Needed

#11800 [MM-17214] Use AddChannelMember method when registering a new guest
  app/user.go
Labels: 3: Reviews Complete

#11795 add docker-compose for ci
  Makefile
  build/Jenkinsfile.pr
  build/docker-compose.yml
  docker-compose.yml
Labels: 3: Reviews Complete

#11696 Invalidate Guest invites too on invalidate email invates
  app/team.go
  app/team_test.go
Labels: 3: Reviews Complete

#11697 Create direct message respect the user role (Guest/Normal user)
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/ChannelStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete

#11783 Enabling the release-5.14 migration and adding the 5.15 and 5.16 skel
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#11802 Update email templates for guest accounts
  app/email.go
  i18n/en.json
  templates/invite_body.html
Labels: 3: Reviews Complete

#11806 fix port extensions
  build/docker-compose.yml
  docker-compose.yaml
Labels: 3: Reviews Complete

#11790 MM-17496: Skip adding user to default channel (rather than failing) w…
  app/syncables.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11828 Automated cherry pick of #11790
  app/syncables.go
Labels: AutomatedCherryPick/Done

#11805 translations PR 20190805
  i18n/fr.json
  i18n/it.json
  i18n/ko.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/tr.json
Labels: 3: Reviews Complete

#11827 MM-17607: large [brand, team, profile] images crash the server
  app/brand.go
  app/team.go
  app/user.go
Labels: 2: Dev Review, CherryPick/Approved

#11809 Fix NPE when installing a plugin via URL
  api4/plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11807 Removed unncessary newline from i18n file
  i18n/en.json
Labels: 3: Reviews Complete

#11788 MM-17071 Extract and add tests for handling of out of channel mentions
  app/notification.go
  app/notification_test.go
Labels: 3: Reviews Complete

#11841 Includes 'i18n-extract' in 'make help' output.
  Makefile
Labels: 3: Reviews Complete

#11821 MM-16725 Respect env var overrides when setting config
  api4/apitestlib.go
  api4/config_test.go
  app/helper_test.go
  app/plugin_api_test.go
  config/common.go
  config/common_test.go
  config/database.go
  config/database_test.go
  config/file.go
  config/file_test.go
  config/memory.go
  config/memory_test.go
  migrations/helper_test.go
  model/config.go
  web/web_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11844 Automated cherry pick of #11821
  api4/apitestlib.go
  api4/config_test.go
  app/helper_test.go
  app/plugin_api_test.go
  config/common.go
  config/common_test.go
  config/database.go
  config/database_test.go
  config/file.go
  config/file_test.go
  config/memory.go
  config/memory_test.go
  migrations/helper_test.go
  model/config.go
  web/web_test.go
Labels: AutomatedCherryPick/Done

#11829 MM-17432: Removes deactivated users from the group member counts.
  store/sqlstore/group_store.go
  store/storetest/group_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11846 Automated cherry pick of #11829
  store/sqlstore/group_store.go
  store/storetest/group_store.go
Labels: AutomatedCherryPick/Done

#11810 Fix typos in en.json
  i18n/en.json
Labels: 3: Reviews Complete

#11839 Automated cherry pick of #11809
  api4/plugin.go
Labels: AutomatedCherryPick/Done

#11838 Updating prepackaged jira and adding antivirus.
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11847 Automated cherry pick of #11838
  Makefile
Labels: AutomatedCherryPick/Done

#11196 MM-11359: support excluding results from search
  app/post.go
  model/search_params.go
  model/search_params_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11836 Automated cherry pick of #11827
  app/brand.go
  app/team.go
  app/user.go
Labels: AutomatedCherryPick/Done

#11787 Automated cherry pick of #11769
  Makefile
  cmd/mattermost/commands/sampledata.go
Labels: AutomatedCherryPick/Done

#11837 MM-17438: allow attaching nouser files to posts
  api4/post_test.go
  app/plugin_api_test.go
  store/sqlstore/file_info_store.go
  store/storetest/file_info_store.go
Labels: CherryPick/Approved

#11834 MM-17412: update post incorrectly removing files
  api4/post.go
  api4/post_test.go
Labels: CherryPick/Approved

#11820 MM-17488: simplify plugin health check
  plugin/supervisor.go
Labels: CherryPick/Approved

#11819 MM-16378: revert plugin health check config removal
  app/diagnostics.go
  app/server.go
  mlog/log.go
  model/config.go
  plugin/health_check.go
  plugin/health_check_test.go
Labels: CherryPick/Approved, Tests/Done

#11866 Automated cherry pick of #11820
  plugin/supervisor.go
Labels: AutomatedCherryPick/Done

#11864 Automated cherry pick of #11837
  api4/post_test.go
  app/plugin_api_test.go
  store/sqlstore/file_info_store.go
  store/storetest/file_info_store.go
Labels: AutomatedCherryPick/Done

#11870 [MM-17758] Explicits the search configuration when using full text search in postgres
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11871 Automated cherry pick of #11870
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
Labels: AutomatedCherryPick/Done

#11867 Automated cherry pick of #11819
  app/diagnostics.go
  app/server.go
  mlog/log.go
  model/config.go
  plugin/health_check.go
  plugin/health_check_test.go
Labels: AutomatedCherryPick/Done

#11865 Automated cherry pick of #11834
  api4/post.go
  api4/post_test.go
Labels: AutomatedCherryPick/Done

#11825 MM-16888 - Fix canonical vs. migration mismatches
  app/import_types.go
  build/Jenkinsfile.pr
  model/scheme.go
  store/sqlstore/channel_store.go
  store/sqlstore/group_store.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, CherryPick/Approved

#11793 [MM-17213] Fix domain check when inviting guests and update user checks
  api4/team_test.go
  app/team.go
  app/user.go
  app/user_test.go
  i18n/en.json
Labels: 3: Reviews Complete

#11873 fix tmpfs usage
  Makefile
  build/docker-compose.common.yml
  build/docker-compose.yml
  docker-compose.yaml
Labels: 3: Reviews Complete

#11874 MM-17609 Add EnableSVGs setting
  app/diagnostics.go
  app/post_metadata.go
  app/post_metadata_test.go
  config/client.go
  model/config.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11868 translations PR 20190812
  i18n/de.json
  i18n/it.json
  i18n/ko.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 1: PM Review

#11877 Automated cherry pick of #11874
  app/diagnostics.go
  app/post_metadata.go
  app/post_metadata_test.go
  config/client.go
  model/config.go
Labels: AutomatedCherryPick/Done

#11849 [MM-17604] Fix websocket message not being broadcasted when a user automatically joins a channel
  app/channel.go
Labels: 2: Dev Review, 2: QA Review

#11880 version bump for custom-attributes-plugin
  Makefile
Labels: 2: Dev Review

#11327 GH-11192 Move non-API OAuth endpoints from api4 to web package
  api4/oauth.go
  api4/oauth_test.go
  web/handlers.go
  web/oauth.go
  web/oauth_test.go
  web/web.go
Labels: 3: Reviews Complete

#11882 Introduce gitlab prepackaged v1.0.0
  Makefile
Labels: CherryPick/Approved

#11886 Automated cherry pick of #11882
  Makefile
Labels: AutomatedCherryPick/Done

#11885 cherry pick of #11880
  Makefile
Labels: 2: Dev Review

#11884 Bump Jira Plugin version to v2.1.0
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11876 MM-17483 Add Pre-packaged plugins to telemetry
  app/diagnostics.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11888 Automated cherry pick of #11876
  app/diagnostics.go
Labels: AutomatedCherryPick/Done

#11891 Update diagnostics to fix gofmt issue
  app/diagnostics.go
Labels: 2: Dev Review, CherryPick/Approved

#11858 [MM-16677] New unsupported browser page
  i18n/en.json
  templates/unsupported_browser.html
  templates/unsupported_browser.js
  web/static.go
  web/unsupported_browser.go
  web/web.go
  web/web_test.go
Labels: 3: Reviews Complete, Setup Cloud Test Server

#11892 Automated cherry pick of #11891
  app/diagnostics.go
Labels: AutomatedCherryPick/Done

#11799 Fixing websockets updates for promote/demote
  app/user.go
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11860 Adds comments to include targets in 'make help'.
  Makefile
Labels: 3: Reviews Complete

#11879 [MM-17741] when converting bot to a user set the correct email.
  app/user.go
  app/user_test.go
Labels: 2: Dev Review, CherryPick/Approved

#11899 Automated cherry pick of #11879
  app/user.go
  app/user_test.go
Labels: AutomatedCherryPick/Done

#11895 MM-17492 Update error message for CustomURLSchemes setting
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#11789 MM-17071 Remove auto responder logic from App.SendNotifications
  app/auto_responder.go
  app/auto_responder_test.go
  app/notification.go
  app/post.go
  model/channel.go
Labels: 3: Reviews Complete

#11916 translations PR 20190819
  i18n/ko.json
  i18n/nl.json
  i18n/ru.json
  i18n/zh-CN.json
Labels: 3: Reviews Complete

#11722 Add SetToken function to NewAPIv4Client
  app/command_loadtest.go
  model/client4.go
  model/client4_test.go
Labels: 3: Reviews Complete

#11906 remove not used file
  build/Jenkinsfile.k8s
Labels: 3: Reviews Complete

#11905 update minio docker image
  build/docker-compose.common.yml
Labels: 3: Reviews Complete

#11901 bump dockerfile with latest mattermost package
  build/Dockerfile
Labels: 3: Reviews Complete

#11930 Automated cherry pick of #11901
  build/Dockerfile
Labels: AutomatedCherryPick/Done

#11794 [MM-17069] Api endpoint to unread a channel
  api4/post.go
  api4/post_test.go
  app/channel.go
  app/channel_test.go
  i18n/en.json
  model/channel_member.go
  model/client4.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11878 Initial cache migration to new layers system
  app/server_app_adapters.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier.go
  store/local_cache_supplier_reactions.go
  store/localcachelayer/layer.go
  store/localcachelayer/layer_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/reaction_layer.go
  store/localcachelayer/reaction_layer_test.go
  store/redis_supplier_reactions.go
  store/sqlstore/supplier.go
  store/sqlstore/supplier_reactions.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
Labels: 3: Reviews Complete

#11933 MM-17149 - Extend config.json for marketplace settings
  app/diagnostics.go
  model/config.go
Labels: 2: Dev Review

#11887 MM-17688 - Updated http timeout for plugin install from URL
  api4/plugin.go
  api4/plugin_test.go
Labels: CherryPick/Approved

#11938 Automated cherry pick of #11887
  api4/plugin.go
  api4/plugin_test.go
Labels: AutomatedCherryPick/Done

#11779 MM-17087 - Disable plugin on removal
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  i18n/en.json
  plugin/environment.go
Labels: 3: Reviews Complete, CherryPick/Approved, Setup HA Cloud Test Server

#11939 Automated cherry pick of #11779
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  i18n/en.json
  plugin/environment.go
Labels: AutomatedCherryPick/Done

#11723 Return POST_EMBED_LINK for links that are not images nor og
  app/post_metadata.go
  app/post_metadata_test.go
  model/post_embed.go
Labels: 3: Reviews Complete

#11851 [MM-17554] Health Check: improves enhanced health check with a DB write check.
  api4/system.go
  model/client4.go
Labels: 3: Reviews Complete

#11934 Add @ prefix for sender username in push notifications
  app/notification.go
  app/notification_test.go
  model/user.go
  model/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11943 Automated cherry pick of #11934
  app/notification.go
  app/notification_test.go
  model/user.go
  model/user_test.go
Labels: AutomatedCherryPick/Done

#11803 [MM-17200] Adds specific messages when guest is added or joins a channel
  app/channel.go
  i18n/en.json
  model/post.go
Labels: 2: Dev Review

#11937 [MM-17958] Add additional input validation for user creation
  api4/user.go
  api4/user_test.go
  model/user.go
Labels: CherryPick/Approved

#11970 Automated cherry pick of #11937
  api4/user.go
  api4/user_test.go
  model/user.go
Labels: AutomatedCherryPick/Done

#11670 MM-11102 Show channel links in notification emails
  app/notification_email.go
  app/notification_email_test.go
Labels: 3: Reviews Complete

#11972 Stop plugin healthchecks before shutting down plugins
  plugin/environment.go
  plugin/health_check.go
Labels: 3: Reviews Complete

#11898 [MM-17703] Diff config files
  Makefile
  scripts/diff-config.sh
Labels: 3: Reviews Complete

#11968 translations PR 20190826
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Area/Localization

#11989 Automated cherry pick of #11961
  app/notification.go
  app/notification_test.go
Labels: AutomatedCherryPick/Done

#11990 Remove @ sign from app.notification.subject.direct.full translation
  app/notification_email_test.go
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#11991 Automated cherry pick of #11990
  app/notification_email_test.go
  i18n/en.json
Labels: AutomatedCherryPick/Done

#11599 Add integrity check command to CLI
  cmd/mattermost/commands/integrity.go
  store/layered_store.go
  store/sqlstore/integrity.go
  store/sqlstore/integrity_test.go
  store/sqlstore/supplier.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
Labels: 3: Reviews Complete

#11995 Automated cherry pick of #11979
  app/helper_test.go
  app/notification_push.go
  app/notification_push_test.go
Labels: AutomatedCherryPick/Done

#11982 [MM-15886] Don't send {"status":"OK"} json response if mobile SSO login
  web/oauth.go
Labels: 2: Dev Review

#11992 translations PR 20190830
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Area/Localization
