Repository mattermost/mattermost, pull requests merged in 2019-11, with the labels that each got.

#12873 Migrate tests from store/storetest/status_store.go to use testify
  store/storetest/status_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#10296 [MM-12623] Create CLI command "config reset"
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#12968 Run unused against codebase
  api4/job_test.go
  config/export_test.go
  plugin/stringifier.go
  plugin/stringifier_test.go
  store/layered_store_hints.go
  store/local_cache_supplier.go
  store/localcachelayer/layer_test.go
  web/handlers.go
Labels: 2: Dev Review, QA Review Done, Tests/Not Needed

#12768 [MM-19798] Implement plugin signature verification
  api4/plugin.go
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_signature.go
  app/plugin_signature_test.go
  app/plugin_test.go
  cmd/mattermost/commands/plugin.go
  i18n/en.json
  model/marketplace_plugin.go
  tests/development-public-key.asc
  tests/development-public-key.gpg
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testpluginv2.tar.gz.sig
  vendor/golang.org/x/crypto/cast5/cast5.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/canonical_text.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/errors/errors.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/compressed.go
  vendor/golang.org/x/crypto/openpgp/packet/config.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/literal.go
  vendor/golang.org/x/crypto/openpgp/packet/ocfb.go
  vendor/golang.org/x/crypto/openpgp/packet/one_pass_signature.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/packet.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/reader.go
  vendor/golang.org/x/crypto/openpgp/packet/signature.go
  vendor/golang.org/x/crypto/openpgp/packet/signature_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetric_key_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/read.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/modules.txt
Labels: 2: Dev Review

#12935 MM-19663 | Migrate brand_test and cluster_test to testify
  api4/brand_test.go
  api4/cluster_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12983 MM-17549: support upgrading plugins
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
Labels: 3: Reviews Complete

#12684 Update en.json
  i18n/en.json
Labels: 3: Reviews Complete

#12947 Adjust govet settings and fix issues found by it
  .golangci.yml
  api4/user.go
  app/config.go
  app/session.go
  store/sqlstore/audit_store.go
  store/sqlstore/compliance_store.go
  store/sqlstore/emoji_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/group_store.go
  store/sqlstore/supplier_reactions.go
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete, QA Review Done

#11818 MM-16822 - Implement KVSetWithOptions
  app/plugin_api.go
  app/plugin_key_value_store.go
  app/plugin_test.go
  i18n/en.json
  model/plugin_kvset_options.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/helpers.go
  plugin/helpers_kv.go
  plugin/plugintest/api.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
Labels: 3: Reviews Complete, QA Review Done

#12732 [MM-19355] Migrate tests from "store/storetest/user_store.go"
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12912 Update minimum supported Safari version to 12
  web/web.go
  web/web_test.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#12991 Add gorilla/handlers dependency as it is used in enterprise version
  cmd/mattermost/main.go
  go.mod
Labels: QA Review Done

#12984 [CR-458] Enhance Logs Endpoint Message
  api4/system.go
  api4/system_test.go
Labels: 2: Dev Review, QA Review Done

#12829 Adding interplugin communication.
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_requests.go
  app/response_transfer.go
  plugin/api.go
  plugin/client_rpc.go
  plugin/context.go
  plugin/interface_generator/main.go
  plugin/plugintest/api.go
Labels: QA Review Done

#13004 translations PR 20191104
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: Reviews Complete, Tests/Not Needed

#12701 [MM-18676] Add tag annotations to plugin server API methods
  plugin/api.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#12156 MM-18068 Route integration actions to plugins without hitting the network
  app/integration_action.go
  app/integration_action_test.go
Labels: 3: Reviews Complete

#12913 Migrate tests from "store/storetest/emoji_store.go" to use testify
  store/storetest/emoji_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12675 [MM-19153] Add server version check in helper methods for plugins
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/helpers_kv.go
  plugin/helpers_kv_test.go
Labels: 3: Reviews Complete, QA Review Done

#12930 enable non-GOPATH testing with different mattermost-server folder name
  testlib/resources.go
  testlib/resources_test.go
  web/web_test.go
Labels: 3: Reviews Complete, QA Review Done

#12946 GH-12888 Modify api4/config_test.go to use testify
  api4/config_test.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#12736 Migrate tests from "store/storetest/webhook_store.go" to use testify
  store/storetest/webhook_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#13008 Bumped Zoom plugin to v1.1.2
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#13016 MM-19477: update manifest documentation example
  model/manifest.go
Labels: QA Review Done

#12899 convert `t.fatal` into require
  utils/lru_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12754 (fixed) Refactor app/status.go to use structured logging #12723
  app/status.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12877 Migrate tests from store/storetest/team_store.go to use testify
  store/storetest/team_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12986 MM-19766: Cannot create LDAP user via /api/v4/users
  api4/user.go
  api4/user_test.go
  model/user.go
Labels: 3: Reviews Complete, QA Review Done

#12979 Update minio
  build/docker-compose.common.yml
  go.mod
  go.sum
  vendor/github.com/minio/minio-go/v6/api-list.go
  vendor/github.com/minio/minio-go/v6/api-notification.go
  vendor/github.com/minio/minio-go/v6/api.go
  vendor/github.com/minio/minio-go/v6/go.sum
  vendor/modules.txt
Labels: 3: Reviews Complete

#13032 [GH-13031] Split tests into subtests or table testing for the file "https://github.com/mattermost/mattermost-server/blob/master/model/file_info_test.go"
  model/file_info_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13006 [MM-19629] Fix data race in server start goroutine
  cmd/mattermost/commands/server.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13024 Remove a potential tabnabbing attack in a template.
  templates/unsupported_browser.html
Labels: 2: Dev Review

#12731 Refactor "app/notification_email.go" to use structured logging #12726
  app/notification_email.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#12966 MM-18005: Improve display message when attempting to add an outsider to a group-synced team via new team invite flow
  app/command_invite_test.go
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#13023 Making private the sqlstore upgrade functions because nobody needs to call them from the outside
  store/sqlstore/supplier.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: QA Review Done, Tests/Not Needed

#12988 MM-19790: Remove randomness in oauth test AuthData.
  app/user_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#12995 MM-19337 Enable users to view archived channels
  api4/channel.go
  api4/channel_test.go
  app/channel.go
  model/client4.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done

#12686 MM - 19155 Change plugin helpers files to be golint complied
  Makefile
  plugin/helpers.go
  plugin/helpers_bots.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#13020 add stop-docker to stop make command
  Makefile
Labels: 3: Reviews Complete, QA Review Done

#13055 Fixed comments syntaxt in app config file
  app/config.go
Labels: 2: Dev Review

#13036 Simplifiying mail service API
  app/email.go
  services/mailservice/mail.go
  services/mailservice/mail_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13042 Fix typo in server_app_adapters.go
  app/server.go
  app/server_app_adapters.go
Labels: 3: Reviews Complete

#12902 Migrate tests from "api4/team_test.go" to use testify
  api4/apitestlib.go
  api4/team_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#12996 Fix typo by removing extra p in function name
  web/static.go
  web/unsupported_browser.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#12894 migrate test to use testify
  utils/license_test.go
  utils/urlencode_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#13054 Refactor more code to use testutils.WasCalled
  config/database_test.go
  config/file_test.go
  config/memory_test.go
  config/watcher_test.go
  utils/testutils/testutils.go
Labels: 3: Reviews Complete, QA Review Done

#13013 MM-19866: Remove Digest setting
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13061 upgrade db to 5.17
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete

#13081 [MM-20134] Consume and store single-signature for each plugin
  api4/plugin.go
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_signature.go
  app/plugin_signature_test.go
  app/plugin_test.go
  cmd/mattermost/commands/plugin_test.go
  i18n/en.json
  model/marketplace_plugin.go
Labels: 2: Dev Review

#12938 channel_test: use testify
  api4/channel_test.go
Labels: 3: Reviews Complete, AutoMerge, Hacktoberfest, Tests/Not Needed

#13053 MM-17508: Modifying config files causes compliance exports to run twice
  jobs/schedulers.go
  jobs/schedulers_test.go
Labels: 3: Reviews Complete, QA Review Done

#13083 MM-19630: marketplace: model ReleaseNotesURL
  model/marketplace_plugin.go
Labels: 3: Reviews Complete, AutoMerge

#13076 MM-20065: allow prepackaged plugin upgrade
  app/plugin.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_test.go
  i18n/en.json
Labels: 3: Reviews Complete

#12950 commands_test: use testify
  api4/commands_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#13060 upgrade db to 5.17
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete, AutoMerge

#13018 [MM-19309] Name Display Lock
  config/client.go
  model/config.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#12961 [MM-19740] Return error for non-system-admins/team admins/channel admins from the GET /api/v4/groups API endpoint response
  api4/group.go
  api4/group_test.go
  i18n/en.json
Labels: 3: Reviews Complete

#13062 MM-19609 - Add new prepackage configuration settings
  model/config.go
Labels: 3: Reviews Complete

#12153 [MM-17297] Extend EnsureBot helper to include bot images
  plugin/api.go
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/plugintest/helpers.go
Labels: 3: Reviews Complete, Demo Plugin Changes/Needed, QA Review Done

#13043 Fix typo in plugin package
  plugin/client_rpc.go
Labels: 3: Reviews Complete, AutoMerge

#12967 Migrate tests from "api4/user_test.go" to use testify
  api4/user_test.go
Labels: 2: Dev Review, Hacktoberfest, Tests/Not Needed

#12952 [MM-15270] Add Team.InviteId sanitization
  api4/team_test.go
  app/team.go
  app/team_test.go
  model/team.go
Labels: 3: Reviews Complete, QA Review Done

#13007 Deactivating and invalidating sessions of guest users on guest disable
  api4/user.go
  api4/user_test.go
  app/server.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/websocket_message.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#12539 [MM-16709] Add helper method for plugins using MessageHasBeenPosted
  model/bot.go
  model/bot_test.go
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/plugintest/helpers.go
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#12951 reaction_test: use testify require for fatal errors
  api4/reaction_test.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed

#13063 Remove fmt and vet checks from CI
  .circleci/config.yml
  Makefile
  build/Jenkinsfile.pr
  model/config_test.go
Labels: 3: Reviews Complete, QA Review Done

#13130 Remove GO111MODULE variable
  Makefile
Labels: 2: Dev Review, QA Review Done

#13138 [MM-19615] Signatures for prepackaged plugins
  build/release.mk
Labels: 3: Reviews Complete

#13086 MM-18517: Plugin Marketplace (Phase 2)
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_test.go
  i18n/en.json
  model/marketplace_plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13148 Automated cherry pick of #13086
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_test.go
  i18n/en.json
  model/marketplace_plugin.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13017 MM-16368 - Plugin Signing
  api4/plugin.go
  api4/plugin_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_public_keys.go
  app/plugin_signature.go
  app/plugin_signature_test.go
  app/plugin_test.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  config/migrate.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/marketplace_plugin.go
  model/utils.go
  services/marketplace/client.go
  tests/development-public-key.asc
  tests/development-public-key.gpg
  tests/test-public-key.plugin.gpg
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testpluginv2.tar.gz
  tests/testpluginv2.tar.gz.sig
  utils/utils.go
  utils/utils_test.go
  vendor/golang.org/x/crypto/cast5/cast5.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/canonical_text.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/errors/errors.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/compressed.go
  vendor/golang.org/x/crypto/openpgp/packet/config.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/literal.go
  vendor/golang.org/x/crypto/openpgp/packet/ocfb.go
  vendor/golang.org/x/crypto/openpgp/packet/one_pass_signature.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/packet.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/reader.go
  vendor/golang.org/x/crypto/openpgp/packet/signature.go
  vendor/golang.org/x/crypto/openpgp/packet/signature_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetric_key_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/read.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/modules.txt
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#13154 Automated cherry pick of #13137
  api4/system.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/notification_push_test.go
  app/notification_test.go
  i18n/en.json
  model/config.go
  model/push_notification.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13149 MM 17466 : Add custom post types to compliance exports
  store/sqlstore/compliance_store.go
  templates/globalrelay_compliance_export_message.html
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13125 [GH-13070] Migrate emojiIdCacheByName cache from store/sqlstore/emoji_store.go to the new store/localcachelayer
  model/cluster_message.go
  store/localcachelayer/emoji_layer.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/sqlstore/emoji_store.go
  store/storetest/emoji_store.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done, Tests/Not Needed

#13153 translations PR 20191118
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Area/Localization, AutoMerge

#12830 MM-18356: Adds ability to paginate channel search.
  api4/channel.go
  api4/channel_test.go
  app/channel.go
  model/channel.go
  model/channel_search.go
  model/client4.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete, Docs/Needed, QA Review Done

#13096 Remove megacheck from Makefile
  Makefile
Labels: 3: Reviews Complete, AutoMerge, Tests/Not Needed

#13141 Migrates the lastPostsCache from PostStore into cache layer
  model/cluster_message.go
  store/localcachelayer/layer.go
  store/localcachelayer/layer_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete, QA Review Done

#13180 [MM-20209] Invalidate channel members cache when promoting/demoting a guest
  app/user.go
  app/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#13185 MM-20347 Move ID Loaded Push Notifications to E20
  api4/system.go
  app/app.go
  app/enterprise.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/notification_push_test.go
  app/notification_test.go
  app/options.go
  app/server.go
  einterfaces/notification.go
  i18n/en.json
  model/license.go
  model/license_test.go
  model/push_notification.go
  utils/license.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13192 Automated cherry pick of #13185
  api4/system.go
  app/app.go
  app/enterprise.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/notification_push_test.go
  app/notification_test.go
  app/options.go
  app/server.go
  einterfaces/notification.go
  i18n/en.json
  model/license.go
  model/license_test.go
  model/push_notification.go
  utils/license.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13188 Fix bad merge into release-5.18
  .circleci/config.yml
  Makefile
  api4/reaction_test.go
  build/Jenkinsfile.pr
  model/cluster_message.go
  model/config_test.go
  store/localcachelayer/channel_layer.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/emoji_layer.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/emoji_store.go
  store/storetest/emoji_store.go
Labels: 3: Reviews Complete, QA Review Done

#13078 MM-19917: Removes use of unindexed Posts.EditAt field in compliance q…
  store/sqlstore/compliance_store.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13108 Fix error: Tests fail due to changes in MinIO default port
  api4/system_test.go
  services/filesstore/filesstore_test.go
  utils/markdown/autolink_test.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done, Tests/Not Needed

#13142 Pin golangCI to a specific version
  .circleci/config.yml
  .golangci.yml
  build/Jenkinsfile.pr
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13187 Automated cherry pick of #13180
  app/user.go
  app/user_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13143 Run golangci-lint on EE packages if present
  Makefile
Labels: 3: Reviews Complete, QA Review Done

#13091 [GH-13058] Migrate webhookCache from store/sqlstore/webhook_store.go to the new store/localcachelayer
  model/cluster_message.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/webhook_layer.go
  store/localcachelayer/webhook_layer_test.go
  store/sqlstore/webhook_store.go
Labels: 3: Reviews Complete, QA Review Done

#13133 Migrate profileByIdsCache cache to cache layer
  model/cluster_message.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13065 Fix naming for CLI plugin list command
  cmd/mattermost/commands/plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13214 Automated cherry pick of #13065
  cmd/mattermost/commands/plugin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#11631 MM-17006: An http 404 response code is returned when deleting a non existent plugin
  api4/plugin_test.go
  app/plugin.go
  app/plugin_statuses.go
Labels: AutoMerge, CherryPick/Approved, Docs/Needed, QA Review Done

#13216 Use predefined go command consistently
  Makefile
Labels: 3: Reviews Complete

#13181 MM-20305: Adds ability to choose whether deleted teams are included i…
  app/analytics.go
  app/diagnostics.go
  app/helper_test.go
  app/import_functions_test.go
  app/security_update_check.go
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
  store/timer_layer.go
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#13135 MM-20100: Migrate channelGuestCountsCache cache from store/sqlstore/channel_store.go to the new store/localcachelayer
  model/cluster_message.go
  store/localcachelayer/channel_layer.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/sqlstore/channel_store.go
  store/store.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13229 Automated cherry pick of #13181
  app/analytics.go
  app/diagnostics.go
  app/helper_test.go
  app/import_functions_test.go
  app/security_update_check.go
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
  store/timer_layer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13183 MM-19551: Add IsDefaultMarketplace to client config
  config/client.go
  config/client_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13155 MM-19980 Allowing user delete command to delete bot accounts.
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#13238 Automated cherry pick of #13183
  config/client.go
  config/client_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13239 Automated cherry pick of #13155
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13212 MM-8607 Add ability to turn off non-critical services when under load
  api4/apitestlib.go
  api4/channel.go
  api4/handlers.go
  api4/post.go
  api4/system.go
  api4/system_test.go
  api4/team.go
  api4/user.go
  app/busy.go
  app/busy_test.go
  app/server.go
  app/status.go
  i18n/en.json
  model/client4.go
  model/system.go
  model/system_test.go
  model/utils.go
  web/context.go
  web/handlers.go
  wsapi/user.go
  wsapi/websocket_handler.go
Labels: 3: Reviews Complete

#13156 MM-19956: Add edit and delete post message export tests.
  store/storetest/compliance_store.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#12910 MM-18357: Adds pagination to team search.
  api4/team.go
  api4/team_test.go
  app/plugin_api.go
  app/team.go
  cmd/mattermost/commands/team.go
  i18n/en.json
  model/client4.go
  model/team_search.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
Labels: 3: Reviews Complete, CherryPick/Approved, Docs/Needed, QA Review Done, Setup Cloud Test Server

#13191 [MM-19979] Stop sending new_user websocket event to guests
  api4/apitestlib.go
  api4/user_test.go
  app/web_conn.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13233 [MM-20725] Revert threads performance change on 5.18
  api4/post.go
  app/auto_posts.go
  app/channel_test.go
  app/command_loadtest.go
  app/file.go
  app/plugin_api.go
  app/post.go
  model/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13242 Fix the LDFLAGS references to use the version suffix
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#13243 Automated cherry pick of #13242
  Makefile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13164 [GH-13105] Migrate channelPinnedPostCountsCache cache from store/sqlstore/channel_store.go to the new store/localcachelayer
  model/cluster_message.go
  store/localcachelayer/channel_layer.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#12948 post_test: use testify
  api4/post_test.go
Labels: 3: Reviews Complete, AutoMerge, Hacktoberfest, Tests/Not Needed

#13075 Migrating team store cache to cache layer
  model/cluster_message.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/team_layer.go
  store/localcachelayer/team_layer_test.go
  store/sqlstore/supplier.go
  store/sqlstore/team_store.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done, Tests/Not Needed

#13041 plugin: fix InstallPlugin() API by manually creating RPC code
  app/plugin_api_test.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/interface_generator/main.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done
