Repository mattermost/mattermost, pull requests merged in 2019-03, with the labels that each got.

#10387 [MM-14375] Skip tutorial steps for sysadmin, user-1 and user-2 from generated sample data
  cmd/mattermost/commands/sampledata.go
Labels: 2: Dev Review

#10375 [MM-14333] Stricten external HTTP Calls to require that own IPs need to be explicitly whitelisted
  services/httpservice/client.go
  services/httpservice/client_test.go
  services/httpservice/httpservice.go
Labels: 3: Ready to Merge, CherryPickApproved

#10353 [MM-12667] Allow including deactivated users in bulk import and export
  app/export.go
  app/export_converters.go
  app/export_test.go
  app/import_functions.go
  app/import_functions_test.go
  app/import_test.go
  app/import_types.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 3: Ready to Merge, Hackfest

#10382 update go to 1.12
  Makefile
  README.md
  build/Dockerfile.buildenv
  build/Jenkinsfile.pr
  build/README.md
  mlog/global_test.go
  mlog/log.go
  mlog/testing.go
  scripts/prereq-check.sh
Labels: 2: Dev Review

#10356 [MM-14081] Disable checkMFA Endpoint by default and add tests for MFA login
  api4/user.go
  api4/user_test.go
  app/authentication.go
  config/default.json
  model/client4.go
  model/config.go
Labels: 1: PM Review, CherryPickApproved, DO NOT MERGE

#10258 MM-10516: Added support for PostActions in ephemeral posts
  api4/integration_action.go
  api4/integration_action_test.go
  api4/post.go
  app/config.go
  app/config_test.go
  app/integration_action.go
  app/plugin_api.go
  app/post.go
  app/server.go
  app/server_app_adapters.go
  model/client4.go
  model/integration_action.go
  model/system.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  utils/testutils/static_config_service.go
Labels: 2: Dev Review, Setup Test Server

#10400 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#10389 fix vettool; run vet on all available packages
  Makefile
  api4/user_test.go
  app/command_test.go
Labels: 3: Ready to Merge

#10393 MM-14357: Remove store call that can provoke dead locks
  app/import.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
Labels: 3: Ready to Merge, CherryPickApproved

#10401 explicitly configure DisableLegacyMFA for TestCheckUserMfa
  api4/user_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#10403 [MM-14300] Return 400 if a post is created with a child post as root
  app/post.go
  app/post_test.go
Labels: 2: Dev Review

#10378 MM-12393 Server side of bot accounts.
  Gopkg.lock
  api4/api.go
  api4/bot.go
  api4/bot_test.go
  api4/user.go
  api4/user_test.go
  app/analytics.go
  app/app_test.go
  app/authentication.go
  app/authorization.go
  app/bot.go
  app/bot_test.go
  app/diagnostics.go
  app/import_functions_test.go
  app/license.go
  app/login.go
  app/oauth.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/security_update_check.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/bot.go
  model/bot_test.go
  model/client4.go
  model/config.go
  model/permission.go
  model/role.go
  model/user.go
  model/user_count.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/layered_store.go
  store/sqlstore/bot_store.go
  store/sqlstore/bot_store_test.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/bot_store.go
  store/storetest/mocks/BotStore.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/UserStore.go
  store/storetest/store.go
  store/storetest/user_store.go
  vendor/github.com/mattermost/gorp/gorp.go
  web/context.go
  web/params.go
Labels: 2: Dev Review

#10083 [MM-12365] Create CLI command "team rename" (#9764)
  app/team.go
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
  store/sqlstore/team_store.go
Labels: 3: Ready to Merge, Hackfest

#10374 MM-14143 config cleanup final
  api4/apitestlib.go
  app/admin.go
  app/config.go
  app/helper_test.go
  app/saml.go
  app/server_test.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/server_test.go
  config/common.go
  config/common_test.go
  config/database.go
  config/database_test.go
  config/export_test.go
  config/file.go
  config/file_test.go
  config/main_test.go
  config/memory.go
  config/memory_test.go
  config/store.go
  config/store_test.go
  migrations/helper_test.go
  utils/fileutils/fileutils.go
  utils/fileutils/fileutils_test.go
  utils/license_test.go
  utils/utils.go
  web/web_test.go
Labels: 3: Ready to Merge

#10406 [MM-13694] Sets a default value for SiteName if empty
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 3: Ready to Merge

#10239 Split Emojis and Webhooks permissions
  api4/emoji.go
  api4/emoji_test.go
  api4/role.go
  api4/role_test.go
  api4/webhook.go
  api4/webhook_test.go
  app/app_test.go
  app/helper_test.go
  app/migrations.go
  app/permissions.go
  app/permissions_migrations.go
  app/permissions_migrations_test.go
  app/role.go
  app/server_app_adapters.go
  cmd/mattermost/commands/webhook_test.go
  model/permission.go
  model/role.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_roles.go
  store/redis_supplier_roles.go
  store/sqlstore/role_supplier.go
  store/store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/RoleStore.go
  store/storetest/role_store.go
  utils/authorization.go
  utils/policies-roles-mapping.json
Labels: 3: Ready to Merge, Awaiting PR

#10417 remove reference from jenkins
  codecov.yml
Labels: 3: Ready to Merge

#10262 Trigger mentions for keyword including multibyte characters in sentences
  app/notification.go
  app/notification_test.go
Labels: 3: Ready to Merge, Hackfest

#10420 Fixing emojis and webhooks permissions split
  cmd/mattermost/commands/init.go
  model/permission.go
Labels: 2: Dev Review

#10414 MM-14439: experimental restrict system admin
  api4/api.go
  api4/cluster.go
  api4/cluster_test.go
  api4/config.go
  api4/config_test.go
  api4/elasticsearch.go
  api4/elasticsearch_test.go
  api4/license.go
  api4/license_test.go
  api4/system.go
  api4/system_test.go
  app/admin.go
  app/config.go
  config/default.json
  i18n/en.json
  model/config.go
Labels: 3: Ready to Merge

#10422 MM-14481: Do not allow to edit or delete in archived channels
  app/post.go
  app/post_test.go
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#10248 [MM-4819] Add MinimumHashtagLength config
  app/diagnostics.go
  config/client.go
  config/default.json
  model/config.go
  tests/test-config.json
Labels: 3: Ready to Merge, Hackfest

#10428 remove stale bot in favor of mattermod
  .github/stale.yml
Labels: 1: PM Review, Awaiting PR

#10379 [MM-10199] Capture of stack traces into Mattermost logs
  app/server.go
  app/server_test.go
  mlog/log.go
Labels: 3: Ready to Merge, Hackfest

#10430 MM-14488: Autogenerate mention_keys on creation if mention_keys aren't provided
  app/import_functions.go
  app/import_functions_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#10426 MM-14415: Removes 'CanLeave' field.
  api4/group_test.go
  app/group_test.go
  app/syncables_test.go
  model/group_syncable.go
  store/sqlstore/group_supplier.go
  store/storetest/group_supplier.go
Labels: 3: Ready to Merge

#10435 [MM-14361] Initialise the translations before loading the config store
  app/server.go
  cmd/mattermost/commands/server.go
  utils/i18n.go
Labels: 2: Dev Review, CherryPickApproved

#10431 MM-13740 Add additional plugin APIs for NPS plugin
  app/plugin_api.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#10444 MM-14560 Changed local image proxy to be off by default
  config/default.json
  model/config.go
  model/config_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#10445 MM-14558 Downgrade warnings printed by post metadata to be debug messages
  app/post_metadata.go
Labels: 3: Ready to Merge, CherryPickApproved

#10451 [MM-14568] Activate Legacy MFA for release 5.9 by default
  config/default.json
Labels: 3: Ready to Merge, CherryPickApproved

#10427 MM-14335 Add telemetry for NPS plugin state
  app/diagnostics.go
Labels: 3: Ready to Merge

#10439 Address config startup issues
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/root.go
  cmd/mattermost/commands/server.go
Labels: 3: Ready to Merge

#10452 translations PR 20190314
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#10418 MM-12488: Accepts parameters to search and filter LDAP groups.
  api4/ldap.go
  app/ldap.go
  einterfaces/ldap.go
  model/group.go
  web/params.go
Labels: Awaiting PR

#10446 Removing unnused InviteSalt config
  api4/config_test.go
  config/common.go
  config/common_test.go
  config/default.json
  config/utils.go
  config/utils_test.go
  model/config.go
  tests/test-config.json
Labels: 3: Ready to Merge

#10455 [MM-13816] Fix MFA prompt not being shown for hardened mode
  api4/user.go
Labels: 3: Ready to Merge, CherryPickApproved

#10421 [MM 12464] Include DM/GM Channels and Their Posts in the Bulk Export
  app/export.go
  app/export_converters.go
  app/export_test.go
  model/channel.go
  model/channel_member.go
  model/post.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/post_store_test.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Ready to Merge

#10453 Improving default session timeout behavour.
  app/session.go
  app/session_test.go
  config/default.json
  model/config.go
Labels: 3: Ready to Merge, Docs: Needed

#10354 Adds elasticsearch to the user and channel autocompletion functions
  Makefile
  api4/user.go
  app/channel.go
  app/diagnostics.go
  app/team.go
  app/user.go
  config/default.json
  einterfaces/elasticsearch.go
  model/channel_search.go
  model/config.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  tests/test-config.json
  utils/utils.go
  utils/utils_test.go
Labels: 3: Ready to Merge

#10456 MM-14620 Specify parameter name for PluginAPI.GetUsers
  plugin/api.go
  plugin/client_rpc_generated.go
Labels: 3: Ready to Merge

#10459 MM-14532 Send "clear" notification to every other session
  api4/channel.go
  api4/post.go
  app/channel.go
  app/channel_test.go
  app/command_invite.go
  app/integration_action_test.go
  app/notification_push.go
  app/plugin_api.go
  app/post.go
  app/post_test.go
  app/syncables.go
  app/syncables_test.go
  store/sqlstore/user_store.go
Labels: 3: Ready to Merge

#10405 [MM-14254] Add elasticsearch initialisation to the cmd
  cmd/mattermost/commands/init.go
Labels: 3: Ready to Merge

#10450 MM-14416: Adds new fields to Channels and Teams for use by LDAP groups removals.
  model/channel.go
  model/channel_test.go
  model/team.go
  model/team_test.go
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#10466 [MM-14576] Add GetBundlePath method to Plugin API
  app/plugin_api.go
  app/plugin_api_test.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 3: Ready to Merge

#10309 Adding list/join public/private teams permissions
  api4/team.go
  api4/team_test.go
  app/app_test.go
  app/permissions_migrations.go
  app/permissions_migrations_test.go
  app/team.go
  i18n/en.json
  model/permission.go
  model/role.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Ready to Merge

#10434 [MM-14253] Adds channels and users to the bulk index process
  i18n/en.json
  model/user.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#10423 MM-14442: Merge function, to enable merging of configs
  config/common.go
  config/common_test.go
  config/export_test.go
  utils/merge.go
  utils/merge_test.go
Labels: 2: Dev Review

#10419 [MM-13341] Add an upgrade test to verify schema
  Makefile
  scripts/mattermost-mysql-5.0.sql
  scripts/mattermost-postgresql-5.0.sql
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
Labels: 3: Ready to Merge

#10475 MM-13621 Fixing incorrect json conversion for OwnerId
  model/bot.go
Labels: 2: Dev Review, Setup Test Server

#10468 translations PR 20190318
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#10480 MM-14652: Updates upgrade column type to match gorp.
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#10477 MM-14441: restrict system admin config
  api4/config.go
  api4/config_test.go
  config/common.go
  config/common_test.go
  config/export_test.go
  config/utils.go
  i18n/en.json
  model/config.go
  utils/merge.go
  utils/merge_test.go
Labels: 3: Ready to Merge

#10142 Update pull request template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review

#10495 MM-14626: Make license expiry checks behave how they are meant to.
  app/license.go
  app/license_test.go
Labels: 3: Ready to Merge

#10498 MM-14304 Fixing GetLDAPUserAttributes to work with SAML as well.
  app/plugin_api.go
Labels: 2: Dev Review

#10507 upgrade database to 5.10.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#10509 MM-14748: Allow to invalidate email invites
  api4/team.go
  app/team.go
  i18n/en.json
  store/sqlstore/tokens_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/TokenStore.go
Labels: 3: Ready to Merge, CherryPickApproved

#10510 prepare db upgrade to 5.11
  store/sqlstore/upgrade.go
Labels: 3: Ready to Merge

#10413 MM-11697: Environment overrides do not overwrite config.json on save
  config/common.go
  config/database_test.go
  config/environment.go
  config/file_test.go
Labels: 2: Dev Review

#10429 Build tooling enhancements
  Makefile
  build/Dockerfile.buildenv
  build/release.mk
Labels: 2: Dev Review, 3: Ready to Merge

#10504 [MM-14573] Toggle DisableLegacyMFA to true by default
  config/default.json
Labels: 3: Ready to Merge, CherryPickApproved

#10497 Setting bot accounts image to specific image.
  app/user.go
  model/bot_default_image.go
Labels: 3: Ready to Merge, CherryPickApproved

#10478 Returned User TermsOfService Data in Certain GetUser APIs To Be Used on Webapp for Decicion Making
  api4/user.go
  api4/user_test.go
  model/user.go
Labels: 3: Ready to Merge, CherryPickApproved

#10512 Update LICENSE.txt
  LICENSE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#10526 MM-14768: Switches field type from sql.NullBool to a bool pointer.
  model/channel.go
  model/channel_test.go
  model/team.go
  model/team_test.go
Labels: 3: Ready to Merge, CherryPickApproved

#10516 MM-14243: Remove any unused PERMANENT_DELETE_USER permission
  app/app_test.go
  app/permissions_migrations.go
  model/permission.go
  model/role.go
Labels: 3: Ready to Merge, CherryPickApproved
