Repository mattermost/mattermost, pull requests merged in 2019-07, with the labels that each got.

#11417 [MM-16568] Migrate "User.SearchInChannel" to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11367 [MM-16517] Migrate "Status.Get" to Sync by default
  Makefile
  app/status.go
  store/sqlstore/status_store.go
  store/store.go
  store/storetest/mocks/StatusStore.go
  store/storetest/status_store.go
Labels: 3: Reviews Complete

#11232 Migrates Channel.GetMembersForUserWithPagination to sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11474 [MM-16652] Migrate "User.ResetLastPictureUpdate" to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
Labels: 3: Reviews Complete

#11200 [Mm-7854] [Backend] Add an endpoint to revoke sessions from all users
  api4/user.go
  api4/user_test.go
  app/cluster_handlers.go
  app/session.go
  app/session_test.go
  model/client4.go
  model/cluster_message.go
  store/sqlstore/oauth_store.go
  store/store.go
  store/storetest/mocks/OAuthStore.go
  store/storetest/oauth_store.go
Labels: 3: Reviews Complete

#11484 [MM-16572] Migrate "User.AnalyticsGetSystemAdminCount" to Sync by default
  app/diagnostics.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11445 Migrating some GroupStore methods to sync by default
  app/group.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11282 Migrate TermsOfService and UserTermsOfService stores to sync by default
  app/terms_of_service.go
  app/user_terms_of_service.go
  store/sqlstore/terms_of_service_store.go
  store/sqlstore/user_terms_of_service.go
  store/store.go
  store/storetest/mocks/TermsOfServiceStore.go
  store/storetest/mocks/UserTermsOfServiceStore.go
  store/storetest/terms_of_service_store.go
  store/storetest/user_terms_of_service.go
Labels: 3: Reviews Complete

#11447 Migrating more GroupStore methods to sync by default
  app/group.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11420 Migrate 'User.GetProfilesNotInTeam' to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11491 [MM-16672] Migrate "User.GetSystemAdminProfiles" to Sync by default
  app/security_update_check.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11473 Migrate Channel.PermanentDeleteByTeam to Sync by default #11175
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11278 Migrate Channel.GetChannelsByScheme to Sync by default
  app/scheme.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11496 GH-11465 Migrate User.UpdateMfaSecret to Sync by default
  api4/user_test.go
  services/mfa/mfa.go
  services/mfa/mfa_test.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11315 Migrate Emoji.GetMultipleByName to Sync by default
  app/emoji.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 3: Reviews Complete

#11480 MM-16476 Update CLI channel list and search commands to show if a channel is private
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/channel_test.go
Labels: 3: Reviews Complete

#11358 Migrated TokenStore.RemoveAllTokensByType to Sync by default (#11345)
  app/team.go
  store/sqlstore/tokens_store.go
  store/store.go
  store/storetest/mocks/TokenStore.go
Labels: 3: Reviews Complete

#11402 [MM-14720] Add Posts Per Day Analytics and Number Posts Previous Day Functionality
  app/analytics.go
  app/diagnostics.go
  model/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11419 Migrate "User.AnalyticsActiveCount" to Sync by default
  app/analytics.go
  app/diagnostics.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
Labels: 3: Reviews Complete

#11444 [MM-16522] Migrate "Status.UpdateLastActivityAt" to Sync by default
  app/status.go
  store/sqlstore/status_store.go
  store/store.go
  store/storetest/mocks/StatusStore.go
  store/storetest/status_store.go
Labels: 2: Dev Review

#11488 [MM-16569] Migrate "User.SearchNotInChannel" to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11499 MM-16682 Update NPS plugin to 1.0.1
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11501 SyncStore: Migrate User.GetForLogin method to Sync
  app/login.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11443 [MM-16620] Properly handle analytics client life cycle
  app/diagnostics.go
  app/diagnostics_test.go
  app/server.go
Labels: 3: Reviews Complete

#11486 MM-11210 Add "GET /posts/unread" API to support landing on the last unread post
  api4/post.go
  api4/post_test.go
  app/post.go
  app/post_metadata.go
  i18n/en.json
  model/client4.go
  model/post_list.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  web/params.go
Labels: 3: Reviews Complete

#11508 Migrate User.GetEtagForProfiles to sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11489 Avoiding leaking users data through websockets for guest accounts
  app/login.go
  app/session.go
  app/session_test.go
  app/user.go
  app/web_conn.go
  i18n/en.json
  model/session.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
Labels: 3: Reviews Complete

#11510 Migrate User.GetProfileByIds to sync by default
  app/channel.go
  app/slack.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11513 Migrate User.GetAllProfiles to sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11509 Migrate User.GetEtagForAllProfiles to sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11487 [MM-16698] Rework membership validation in list command handler
  api4/command.go
  api4/command_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11493 GH-11469 Migrate User.UpdateLastPictureUpdate to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11478 [MM-15661] Create SendNotificationEmail and move config option check to it
  app/admin.go
  app/email.go
  app/email_batching.go
  app/notification_email.go
  app/plugin_api.go
  services/mailservice/mail.go
Labels: 3: Reviews Complete

#11483 [MM-16697] Rework validation of team and channel membership for webhook updates
  api4/webhook.go
  api4/webhook_test.go
Labels: 2: Dev Review, CherryPick/Approved

#11472 MM-12389 Update segment library to v3
  Makefile
  app/diagnostics.go
  app/server.go
  go.mod
  go.sum
  vendor/github.com/jehiah/go-strftime/README.md
  vendor/github.com/jehiah/go-strftime/strftime.go
  vendor/github.com/segmentio/analytics-go/.gitignore
  vendor/github.com/segmentio/analytics-go/.gitmodules
  vendor/github.com/segmentio/analytics-go/History.md
  vendor/github.com/segmentio/analytics-go/License.md
  vendor/github.com/segmentio/analytics-go/Makefile
  vendor/github.com/segmentio/analytics-go/Readme.md
  vendor/github.com/segmentio/analytics-go/alias.go
  vendor/github.com/segmentio/analytics-go/analytics.go
  vendor/github.com/segmentio/analytics-go/circle.yml
  vendor/github.com/segmentio/analytics-go/config.go
  vendor/github.com/segmentio/analytics-go/context.go
  vendor/github.com/segmentio/analytics-go/error.go
  vendor/github.com/segmentio/analytics-go/executor.go
  vendor/github.com/segmentio/analytics-go/group.go
  vendor/github.com/segmentio/analytics-go/identify.go
  vendor/github.com/segmentio/analytics-go/integrations.go
  vendor/github.com/segmentio/analytics-go/json.go
  vendor/github.com/segmentio/analytics-go/logger.go
  vendor/github.com/segmentio/analytics-go/message.go
  vendor/github.com/segmentio/analytics-go/page.go
  vendor/github.com/segmentio/analytics-go/properties.go
  vendor/github.com/segmentio/analytics-go/screen.go
  vendor/github.com/segmentio/analytics-go/timeout_15.go
  vendor/github.com/segmentio/analytics-go/timeout_16.go
  vendor/github.com/segmentio/analytics-go/track.go
  vendor/github.com/segmentio/analytics-go/traits.go
  vendor/modules.txt
Labels: 2: Dev Review

#11516 make user.Get all return []*model.User and *model.AppError
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11515 11460 user.get all profiles in channel
  app/channel.go
  app/notification.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11430 MM-16506: conditionally build go.mod for plugins
  plugin/main_test.go
  testlib/resources.go
  utils/test_files_compiler.go
Labels: 3: Reviews Complete

#11512 Migrate User.GetProfiles to sync by default
  app/channel.go
  app/command_loadtest.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11523 Migrate "User.GetProfilesByUsernames" to Sync by default
  app/notification.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11502 MM-8602: KV Store Json helper tweaks
  plugin/api.go
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/helpers_kv.go
  plugin/helpers_kv_test.go
  plugin/plugintest/helpers.go
Labels: 3: Reviews Complete

#11504 [MM-16719] Setting the MM_SQLSETTINGS_DATASOURCEREPLICAS environment variable breaks the server startup
  config/common.go
  config/database_test.go
  config/environment.go
  config/file_test.go
Labels: 2: Dev Review, CherryPick/Candidate

#11521 MM-16796: reduce plugin job interval to once per day
  plugin/scheduler/scheduler.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11423 MM-15452 - Add ability to override LHS icon for bot accounts
  api4/bot.go
  api4/bot_test.go
  app/bot.go
  app/user.go
  i18n/en.json
  model/client4.go
  tests/test.svg
Labels: 2: Dev Review

#11507 Migrate User.UpdateFailedPasswordAttempts to sync by default
  app/authentication.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11522 Migrate SchemeStore to sync by default
  app/import_functions_test.go
  app/migrations.go
  app/permissions.go
  app/scheme.go
  store/layered_store.go
  store/layered_store_supplier.go
  store/local_cache_supplier_schemes.go
  store/redis_supplier_schemes.go
  store/sqlstore/scheme_supplier.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/LayeredStoreDatabaseLayer.go
  store/storetest/mocks/LayeredStoreSupplier.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/scheme_store.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11559 [MM-16782] Migrate "Team.GetTeamMembersForExport" to Sync by default
  app/export.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11002 [MM-15854] Migrate "Post.Search" to Sync by default
  app/post.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
Labels: 3: Reviews Complete

#11506 Migrate User.ClearAllCustomRoleAssignments to sync by default
  app/permissions.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11561 Migrate "Team.UpdateLastTeamIconUpdate" to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11505 Migrate User.InferSystemInstallDate to sync by default
  app/config.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
Labels: 3: Reviews Complete

#11527 MM-16759: Fix flaky group-store test.
  store/storetest/group_store.go
Labels: 3: Reviews Complete

#11562 [MM-16781] Migrate "Team.GetAllForExportAfter" to Sync by default
  app/export.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11492 Allow to export global relay to zip
  cmd/mattermost/commands/export.go
  model/config.go
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#11581 [MM-16790] Migrate Plugin.Get to Sync by default
  app/plugin_key_value_store.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 3: Reviews Complete

#11477 MM-10982 Support relative links in interactive message buttons
  app/integration_action.go
  app/integration_action_test.go
Labels: 3: Reviews Complete

#11525 MM-16625: Set UpdateAt correctly on deleting profile pic.
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11528 MM-16543 Fix Elasticsearch only returning one page of results
  Makefile
  app/post.go
  app/post_test.go
  einterfaces/mocks/AccountMigrationInterface.go
  einterfaces/mocks/ClusterInterface.go
  einterfaces/mocks/ComplianceInterface.go
  einterfaces/mocks/DataRetentionInterface.go
  einterfaces/mocks/DataRetentionJobInterface.go
  einterfaces/mocks/ElasticsearchAggregatorInterface.go
  einterfaces/mocks/ElasticsearchIndexerInterface.go
  einterfaces/mocks/ElasticsearchInterface.go
  einterfaces/mocks/LdapInterface.go
  einterfaces/mocks/LdapSyncInterface.go
  einterfaces/mocks/MessageExportInterface.go
  einterfaces/mocks/MessageExportJobInterface.go
  einterfaces/mocks/MetricsInterface.go
  einterfaces/mocks/MfaInterface.go
  einterfaces/mocks/OauthProvider.go
  einterfaces/mocks/SamlInterface.go
  scripts/license-check.sh
Labels: 2: Dev Review

#11582 [MM-16794] Migrate Plugin.List to Sync by default
  app/plugin_key_value_store.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
Labels: 3: Reviews Complete

#11485 [MM-16315] Migrate Channel.PermanentDelete to Sync by default
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 2: Dev Review

#11579 [MM-16784] Sync GetUserTeamIds
  app/user.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
Labels: 3: Reviews Complete

#11517 [MM-16653] Migrate "User.UpdateUpdateAt" to Sync by default
  app/team.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11518 [MM-16574] Migrate "User.GetEtagForProfilesNotInTeam" to Sync by default
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11560 Migrate "Team.RemoveAllMembersByUser" to Sync by default
  app/user.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11482 Migrate User.Save to Sync by default
  app/bot.go
  app/slackimport.go
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/bot_store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/group_store.go
  store/storetest/mocks/UserStore.go
  store/storetest/post_store.go
  store/storetest/team_store.go
  store/storetest/terms_of_service_store.go
  store/storetest/user_access_token_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11563 [MM-16776] Migrate "Team.GetTeamsByScheme" to Sync by default
  app/scheme.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11103 [MM-16166] Migrate Team.GetAllPrivateTeamListing to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11564 GH-11550 Migrate "Team.ResetAllTeamSchemes" to Sync by default
  app/permissions.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11589 MM-16783 Migrate "Team.UserBelongsToTeams" to Sync by default
  app/user.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
Labels: 3: Reviews Complete

#11565 [MM-16772] Migrate Team.RemoveMember to Sync by default
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, Awaiting Submitter Action

#11495 GH-11466 Migrate User.UpdatePassword to Sync by default
  app/user.go
  cmd/mattermost/commands/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11592 Migrate Plugin.SaveOrUpdate to sync by default
  app/plugin_key_value_store.go
  app/plugin_test.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 3: Reviews Complete

#11595 Migrate CommandWebhook.Save to sync by default
  app/webhook.go
  store/sqlstore/command_webhook_store.go
  store/store.go
  store/storetest/command_webhook_store.go
  store/storetest/mocks/CommandWebhookStore.go
Labels: 2: Dev Review

#11583 [MM-16793] Migrate Plugin.DeleteAllExpired to Sync by default
  app/plugin_key_value_store.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 3: Reviews Complete

#11102 [MM-16168] Migrate Team.GetAllTeamListing to Sync by default
  app/team.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11594 Migrate CommandWebhook.Get to sync by default
  app/webhook.go
  store/sqlstore/command_webhook_store.go
  store/store.go
  store/storetest/command_webhook_store.go
  store/storetest/mocks/CommandWebhookStore.go
Labels: 3: Reviews Complete

#11100 [MM-16170] Migrate Team.GetTeamsByUserId to Sync by default
  app/file.go
  app/notification_email.go
  app/team.go
  app/user.go
  cmd/mattermost/commands/team_test.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11593 Migrate CommandWebhook.TryUse to sync by default
  app/webhook.go
  store/sqlstore/command_webhook_store.go
  store/store.go
  store/storetest/command_webhook_store.go
  store/storetest/mocks/CommandWebhookStore.go
Labels: 3: Reviews Complete

#11591 translations PR 20190708
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#11520 [MM-16667] Migrate User.GetByUsername to Sync by default #11453
  app/command_groupmsg.go
  app/command_invite.go
  app/command_msg.go
  app/command_remove.go
  app/import_functions.go
  app/user.go
  app/webhook.go
  cmd/mattermost/commands/userargs.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11584 [MM-16777] Migrate Team.MigrateTeamMembers to Sync by default
  migrations/advanced_permissions_phase_2.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review, 3: Reviews Complete

#11481 Allow to enable/disable guests and other extra config settings
  api4/role.go
  api4/role_test.go
  api4/team.go
  api4/team_test.go
  api4/user.go
  app/user.go
  app/user_test.go
  config/client.go
  i18n/en.json
  model/config.go
  model/license.go
  model/license_test.go
  utils/license.go
  web/context.go
Labels: 3: Reviews Complete

#11529 MM-16728 Fix mixup between stdout and stderr in CLI
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/export.go
  cmd/mattermost/commands/import.go
  cmd/mattermost/commands/output.go
Labels: 3: Reviews Complete

#11597 [MM-16792] Migrate Plugin.DeleteAllForPlugin to Sync by default
  app/plugin_key_value_store.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 2: Dev Review

#11566 [MM-16656] Migrate "User.UpdateMfaActive" to Sync by default
  api4/user_test.go
  services/mfa/mfa.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11497 Add progressive backoff function
  plugin/helpers_bots.go
  utils/backoff.go
  utils/backoff_test.go
Labels: 3: Reviews Complete

#11511 MM-16261 - Store Plugin in File Store
  api4/plugin.go
  api4/plugin_test.go
  app/plugin_install.go
  i18n/en.json
Labels: 3: Reviews Complete

#11415 add support for new slack post format and multiple attachments in slack importer
  app/slackimport.go
  app/slackimport_test.go
  tests/slack-import-test-posts.json
Labels: 2: Dev Review

#11604 [MM-16562] Migrate User.GetUnreadCountForChannel to Sync by default
  app/channel.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/CommandWebhookStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11587 Migrate "Team.ClearAllCustomRoleAssignments" to Sync by default
  app/permissions.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 2: Dev Review

#11601 MM-16872 - Extend Plugin API to set LHS bot icon
  api4/bot.go
  api4/bot_test.go
  app/bot.go
  app/bot_test.go
  app/plugin_api.go
  i18n/en.json
  model/client4.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review

#11610 [MM-16647] Fix issue with setting mention count
  app/notification.go
  app/notification_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11596 Config migrate SAML keys and certificates
  cmd/mattermost/commands/config.go
  config/migrate.go
  config/migrate_test.go
Labels: 3: Reviews Complete

#11585 [MM-15925] Add includeDeleted flag to GetForPost in FileInfoStore
  app/file.go
  app/notification.go
  app/notification_email.go
  app/post.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
Labels: 3: Reviews Complete

#11619 MM-16921 Fix getPostsSince caching no results (5.13)
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#11618 MM-16921 Fix getPostsSince caching invalid data
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 2: Dev Review

#11578 Managing correctly the guest channel leave behavior
  app/channel.go
  app/channel_test.go
  app/command_leave.go
  app/command_leave_test.go
  app/team.go
  app/user_test.go
  store/sqlstore/channel_store.go
Labels: 3: Reviews Complete

#11611 MM-16272 - Synchronize plugins across cluster
  api4/plugin_test.go
  app/cluster_handlers.go
  app/plugin_event.go
  app/plugin_install.go
  model/cluster_message.go
  model/plugin_event_data.go
  testlib/cluster.go
Labels: 2: Dev Review

#11531 GH-11530 - Go major and minor version validation.
  Makefile
Labels: 3: Reviews Complete

#11580 [MM-16791] Migrate Plugin.Delete to Sync by default
  app/plugin_key_value_store.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
Labels: 2: Dev Review

#11632 just to test the cherry pick
  README.md
Labels: CherryPick/Approved

#11633 test cherry pick again
  README.md
Labels: CherryPick/Approved

#11638 tst
  README.md
Labels: CherryPick/Approved

#11615 MM-16270 - Plugin Sync
  app/file.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_test.go
  i18n/en.json
  services/filesstore/localstore.go
Labels: 2: Dev Review

#11644 Removing FileStorePath from PluginEventData
  api4/plugin_test.go
  app/plugin_install.go
  model/plugin_event_data.go
Labels: 3: Reviews Complete

#11588 MM-16780 Migrate "Team.AnalyticsGetTeamCountForScheme" to Sync by default
  app/diagnostics.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete

#11586 [MM-16389] Add `icon_emoji` parameter to webhooks
  app/emoji.go
  app/import_functions.go
  app/import_functions_test.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/webhook.go
  app/webhook_test.go
  model/emoji.go
  model/incoming_webhook.go
  model/post.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
Labels: 3: Reviews Complete

#10898 Create CLI command "team modify" to modify team's privacy setting.
  app/team.go
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
Labels: 3: Reviews Complete

#11625 Added debug-server-headless to Makefile
  Makefile
Labels: 3: Reviews Complete

#11374 move dockerfile to server repo
  build/Dockerfile
  build/Jenkinsfile.branch
  build/Jenkinsfile.pr
  build/entrypoint.sh
Labels: 3: Reviews Complete

#11646 Adding guest counts for channel stats
  api4/channel.go
  app/channel.go
  app/plugin_api.go
  app/web_hub.go
  model/channel_stats.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11630 Enhance logging of CSRF Warning
  app/plugin_requests.go
  web/handlers.go
Labels: 3: Reviews Complete

#11614 MM-11931 Add support for AllowedUntrustedInternalConnections to be comma-separated
  api4/command_test.go
  api4/integration_action_test.go
  api4/openGraph_test.go
  api4/post_test.go
  app/integration_action_test.go
  app/webhook_test.go
  services/httpservice/client_test.go
  services/httpservice/httpservice.go
Labels: 3: Reviews Complete

#11648 MM-16797 Update NPS plugin to v1.0.2
  Makefile
Labels: 2: Dev Review

#11617 MM-16949 Fix posts returned from unread API when the two different list contains parent post and comments
  api4/post_test.go
  model/post_list.go
  model/post_list_test.go
Labels: 3: Reviews Complete

#11654 Fix plugin path
  app/plugin.go
  app/plugin_install.go
  i18n/en.json
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
Labels: 3: Reviews Complete

#11655 [MM-16744] Filter bots out of notifications for members not in channel
  app/notification.go
  model/user.go
  model/user_test.go
Labels: 2: Dev Review

#11650 MM-16389 - complement for emoji_icon issue
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Reviews Complete

#11624 [16331] Migrated Channel.SaveMember to sync by default (#11158)
  app/channel.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/post_store.go
  store/storetest/team_store.go
  store/storetest/user_store.go
Labels: 2: Dev Review

#11662 Improve DB performance on getPostsAround()
  store/sqlstore/post_store.go
Labels: 2: Dev Review, CherryPick/Approved

#11649 MM-17043 Downgrade OpenGraph logging to debug level
  app/opengraph.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11667 Automated cherry pick of #11657
  api4/plugin_test.go
  app/cluster_handlers.go
  app/file.go
  app/plugin.go
  app/plugin_event.go
  app/plugin_install.go
  app/plugin_test.go
  i18n/en.json
  model/cluster_message.go
  model/plugin_event_data.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
  testlib/cluster.go
Labels: AutomatedCherryPick/Done

#11664 MM-16825 Update NPS plugin to 1.0.3
  Makefile
Labels: 2: Dev Review, CherryPick/Approved

#11623 Migrate User.GetProfilesInChannelByStatus to Sync by default #11461
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11671 Automated cherry pick of #11664
  Makefile
Labels: AutomatedCherryPick/Done

#11651 MM-17029 Bumping pre-packaged plugin versions.
  Makefile
Labels: 3: Reviews Complete, CherryPick/Approved

#11425 [MM-16501] Delete user from Bot table when deleting user with mattermost CLI
  app/user.go
  app/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11658 [MM-16871] Remove bots from "Daily Active Users" and "Monthly Active Users"
  app/analytics.go
  app/diagnostics.go
  store/sqlstore/user_store.go
  store/sqlstore/user_store_test.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11673 Automated cherry pick of #11425
  app/user.go
  app/user_test.go
Labels: AutomatedCherryPick/Done

#11663 Automated cherry pick of #11662
  store/sqlstore/post_store.go
Labels: AutomatedCherryPick/Done, Do Not Merge

#11679 Improve DB performance on getPostsAround()
  store/sqlstore/post_store.go
Labels: 3: Reviews Complete

#11428 Guest accounts feature
  api4/channel.go
  api4/role.go
  api4/role_test.go
  api4/team.go
  api4/team_test.go
  api4/user.go
  app/app_test.go
  app/channel.go
  app/channel_test.go
  app/command_leave.go
  app/command_leave_test.go
  app/email.go
  app/login.go
  app/permissions_migrations.go
  app/plugin_api.go
  app/session.go
  app/session_test.go
  app/team.go
  app/team_test.go
  app/user.go
  app/user_test.go
  app/web_conn.go
  app/web_hub.go
  config/client.go
  i18n/en.json
  model/channel_stats.go
  model/client4.go
  model/config.go
  model/guest_invite.go
  model/license.go
  model/license_test.go
  model/permission.go
  model/role.go
  model/session.go
  store/sqlstore/channel_store.go
  store/sqlstore/session_store.go
  store/sqlstore/tokens_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  templates/invite_body.html
  utils/license.go
  web/context.go
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting PR, Setup Cloud Test Server

#11677 Add telemetry for new cluster settings
  app/diagnostics.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11686 Exposing enforce mfa in client config
  config/client.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11533 MM-12460 Fill the Theme field for team members on export
  app/export.go
Labels: 3: Reviews Complete

#11691 Fixing initial DMs/GMs load
  store/sqlstore/channel_store.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11689 no ticket: Show go compile output for embedded unit test plugins
  utils/test_files_compiler.go
Labels: 3: Reviews Complete

#11687 Automated cherry pick of #11677
  app/diagnostics.go
Labels: AutomatedCherryPick/Done

#11702 [MM-16278] Improve bulk export of posts
  app/export.go
  cmd/mattermost/commands/export.go
  store/sqlstore/post_store.go
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#11674 Automated cherry pick of #11658
  app/analytics.go
  app/diagnostics.go
  store/sqlstore/user_store.go
  store/sqlstore/user_store_test.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: AutomatedCherryPick/Done

#11710 Automated cherry pick of #11702
  app/export.go
  cmd/mattermost/commands/export.go
  store/sqlstore/post_store.go
Labels: AutomatedCherryPick/Done

#11685 [MM-16658] Migrate User.GetProfilesInChannel to Sync by default #11462
  app/user.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
Labels: 3: Reviews Complete

#11711 Fix pagination bug on LDAP groups users listing
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
Labels: 3: Reviews Complete, CherryPick/Approved

#11707 MM-16997: Simplified TestUploadFiles
  api4/file_test.go
  app/plugin_hooks_test.go
  tests/orientation_test_1_expected_preview.jpeg
  tests/orientation_test_1_expected_thumb.jpeg
  tests/orientation_test_2_expected_preview.jpeg
  tests/orientation_test_2_expected_thumb.jpeg
  tests/orientation_test_3_expected_preview.jpeg
  tests/orientation_test_3_expected_thumb.jpeg
  tests/orientation_test_4_expected_preview.jpeg
  tests/orientation_test_4_expected_thumb.jpeg
  tests/orientation_test_5_expected_preview.jpeg
  tests/orientation_test_5_expected_thumb.jpeg
  tests/orientation_test_6_expected_preview.jpeg
  tests/orientation_test_6_expected_thumb.jpeg
  tests/orientation_test_7_expected_preview.jpeg
  tests/orientation_test_7_expected_thumb.jpeg
  tests/orientation_test_8_expected_preview.jpeg
  tests/orientation_test_8_expected_thumb.jpeg
Labels: 3: Reviews Complete

#11709 MM-16935 - Flaky test: Elastic Search IndexChannel Error
  Makefile
  api4/apitestlib.go
  build/docker-compose.yml
Labels: 3: Reviews Complete, CherryPick/Approved

#11719 Automated cherry pick of #11709
  Makefile
  api4/apitestlib.go
  build/docker-compose.yml
Labels: AutomatedCherryPick/Done

#11705 MM-17053: avoid colliding with reserved team names
  store/storetest/channel_store.go
  store/storetest/post_store.go
  store/storetest/status_store.go
  store/storetest/team_store.go
Labels: 2: Dev Review, CherryPick/Approved

#11706 [MM-17194] Add search channels for user in case the user doesn't have the list channels permission
  api4/channel.go
  api4/channel_test.go
  app/channel.go
  app/channel_test.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete

#11716 Automated cherry pick of #11711
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
Labels: AutomatedCherryPick/Done

#11519 Removing unnecesary StoreResult usages to simplify the store code
  store/sqlstore/preference_store.go
Labels: 3: Reviews Complete
