Repository mattermost/mattermost, pull requests merged in 2020-12, with the labels that each got.

#16384 [MM-30908]: Change receiver name for (me *DndProvider) in app/slashcommands/command_dnd.go to be more idiomatic.
  app/slashcommands/command_dnd.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16385 [MM-30909]: Change receiver name for (me *KickProvider) and (me *RemoveProvider)in app/slashcommands/command_remove.go to be more idiomatic.
  app/slashcommands/command_remove.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16386 [MM-30910]: Change receiver name for (me *InitialLoad) in model/initial_load.go to be more idiomatic
  model/initial_load.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16301 [MM-30008] Add mmctl support for file imports
  api4/api.go
  api4/import_local.go
  api4/import_test.go
  api4/job_local.go
  api4/upload.go
  api4/upload_local.go
  api4/user_local.go
  app/import.go
  app/upload.go
  i18n/en.json
  model/upload_session.go
  store/sqlstore/upload_session_store.go
  store/storetest/upload_session_store.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16388 [MM-30912]: Change receiver name for (me *RenameProvider) in app/slashcommands/command_channel_rename.go to be more idiomatic.
  app/slashcommands/command_channel_rename.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16353 MM-30865 Invalid Participants handling on post delete in thread
  store/sqlstore/post_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#16407 MM-30970 Add Basic unreadMentions support for collapsed threads
  api4/user_test.go
  app/channel.go
  app/notification.go
  app/post.go
  app/user.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16285 Fix misspellings and enable misspell on ci
  .golangci.yml
  api4/channel_test.go
  api4/job_test.go
  app/app_iface.go
  app/channel.go
  app/license.go
  app/notification_push_test.go
  app/notification_test.go
  config/feature_flags.go
  config/store.go
  model/command_autocomplete.go
  model/command_autocomplete_test.go
  model/feature_flags.go
  model/role.go
  model/search_params_test.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  store/errors.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/post_store_test.go
  store/storetest/group_store.go
Labels: 4: Reviews Complete, release-note

#16439 Add miss translations 29
  i18n/en.json
Labels: release-note-none

#16437 Add miss translations 28
  i18n/en.json
Labels: release-note-none

#16420 Add GitLab.
  .gitlab-ci.yml
Labels: release-note-none

#16430 MM-30987- Fix race in setting clearNotify in Busy
  app/busy.go
  app/busy_test.go
Labels: 4: Reviews Complete, release-note-none

#16390 [MM-30914]: Change receiver name for (me *InviteProvider) in app/slashcommands/command_invite.go to be more idiomatic.
  app/slashcommands/command_invite.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16391 [MM-30915]: Change receiver name for (me *JoinProvider) in app/slashcommands/command_join.go to be more idiomatic.
  app/slashcommands/command_join.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16435 Automated cherry pick of #16353
  store/sqlstore/post_store.go
  store/storetest/thread_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16445 Cherrypick MM-30970 into 5.29
  app/channel.go
  app/notification.go
  app/post.go
  einterfaces/mocks/LdapInterface.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note

#16431 MM-30988 - Fix racy test ServerSystemdNotification
  app/server.go
  model/utils.go
  scripts/test.sh
Labels: 4: Reviews Complete, release-note-none

#16436 Automated cherry pick of #16395
  store/sqlstore/post_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16438 [MM-30981] Require Plugin name in manifest
  model/manifest.go
  model/manifest_test.go
Labels: 4: Reviews Complete, release-note-none

#16306 MM-27989 Remove experimental setting for data prefetch
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#16449 Fix mmctl and add manifest for 5.28
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: release-note-none

#16062 [MM-28422] Enable processing of import files through API
  api4/api.go
  api4/import.go
  api4/import_local.go
  api4/import_test.go
  api4/job_local.go
  api4/upload.go
  api4/upload_local.go
  api4/upload_test.go
  api4/user_local.go
  app/app.go
  app/app_iface.go
  app/enterprise.go
  app/file.go
  app/import.go
  app/import_functions.go
  app/import_test.go
  app/opentracing/opentracing_layer.go
  app/upload.go
  i18n/en.json
  imports/placeholder.go
  jobs/import_process/worker.go
  jobs/interfaces/import_process_interface.go
  jobs/jobs_watcher.go
  jobs/server.go
  jobs/workers.go
  model/client4.go
  model/config.go
  model/config_test.go
  model/job.go
  model/upload_session.go
  services/filesstore/filesstore.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
  store/sqlstore/upload_session_store.go
  store/storetest/upload_session_store.go
  tests/import_test.zip
  tests/testarchive.zip
  utils/archive.go
  utils/archive_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16250 [MM-30344] utils/markdown: fix index out of range
  utils/markdown/links.go
  utils/markdown/links_test.go
Labels: 4: Reviews Complete, release-note-none

#16440 Additional Config Store Cleanup
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/permissions.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/version.go
  config/database.go
  config/store.go
Labels: 3: QA Review, kind/bug, release-note

#16434 [MM-30973] Delinquent Account Emails: Possibility for duplicate emails to be sent
  model/system.go
Labels: 4: Reviews Complete, release-note-none

#16442 [MM-30984] Missing payment email on billing day if no CC is present
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/payment_failed_no_card_body.html
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note

#16454 Automated cherry pick of #16442
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/payment_failed_no_card_body.html
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16458 Automated cherry pick of #16361
  app/enterprise.go
  app/enterprise_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16343 MM-30818: Change to idiomatic receiver names for migrations.TestHelper
  migrations/helper_test.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Done, release-note-none

#16347 MM-30822: Change to idiomatic receiver names for model.PushNotification
  model/push_notification.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16389 [MM-30913]: Change receiver name for (me *CollapseProvider) in app/slashcommands/command_expand_collapse.go to be more idiomatic.
  app/slashcommands/command_expand_collapse.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16459 Automated cherry pick of #16353
  store/sqlstore/post_store.go
  store/storetest/thread_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16446 [MM-30982] Add filter metadata to Marketplace response
  model/marketplace_plugin.go
Labels: 4: Reviews Complete, release-note-none

#16460 Automated cherry pick of #16395
  store/sqlstore/post_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16478 MM-31082: Use a base path for test assets
  testlib/helper.go
Labels: 4: Reviews Complete, release-note-none

#16457 Lock CI from cloud/release-5.30
  .circleci/config.yml
Labels: AutoMerge, release-note-none

#16455 [MM-30467] app/import_functions: fix a bug while importing for two different teams
  app/import_functions.go
  app/import_functions_test.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, QA Deferred, release-note-none

#16491 Automated cherry pick of #16455
  app/import_functions.go
  app/import_functions_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16492 add missing translation strings
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#16490 Automated cherry pick of #16455
  app/import_functions.go
  app/import_functions_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16406 MM-30801: pre-package channel export plugin
  Makefile
  model/config.go
  model/config_test.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16304 MM-30558 - Add unreadReplies and unreadMentions to thread membership
  api4/api.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  app/user.go
  einterfaces/mocks/CloudInterface.go
  einterfaces/mocks/CloudJobInterface.go
  model/client4.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#16453 db: upgrade db to 5.30
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, kind/feature, release-note

#16428 Remove model.AppError from searchlayer/channel_layer.go
  store/searchlayer/channel_layer.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16488 Update Dockerfile
  build/Dockerfile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#16504 Automated cherry pick of #16488
  build/Dockerfile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16496 Automated cherry pick of #16406
  Makefile
  model/config.go
  model/config_test.go
  services/telemetry/telemetry.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16426 MM-30986 Move global logger init until after server logger fully configured
  app/server.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16480 cherry-pick-MM-30970-release-5.30
  api4/user_test.go
  app/channel.go
  app/notification.go
  app/post.go
  app/user.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note

#16448 MM-30708: Fix racy TestLdapConnect/STARTTLS_connection
  go.mod
  go.sum
  vendor/github.com/mattermost/ldap/conn.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#16510 Automated cherry pick of #16406
  Makefile
  model/config.go
  model/config_test.go
  services/telemetry/telemetry.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16506 Regenerating store mocks properly
  store/storetest/mocks/SqlStore.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#16479 [MM-31065]: Change receiver name for (me *MuteProvider) in app/slashcommands/command_mute.go to be more idiomatic
  app/slashcommands/command_mute.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16511 Translations update from Weblate
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#16512 Limit configuration database connections
  config/database.go
Labels: 4: Reviews Complete, release-note-none

#16481 [MM-31066]: Change receiver name for (me *ShrugProvider) in app/slashcommands/command_shrug.go to be more idiomatic
  app/slashcommands/command_shrug.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16364 Add Billing Permissions
  api4/cloud.go
  app/permissions_migrations.go
  model/migration.go
  model/permission.go
  testlib/store.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#16482 [MM-31067]: Change receiver name for (me *ClusterInfo) in model/cluster_info.go to be more idiomatic
  model/cluster_info.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16222 MM-27688-OpenId Connect
  api4/user.go
  app/app_iface.go
  app/oauth.go
  app/oauth_test.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
  config/client.go
  config/utils.go
  config/utils_test.go
  einterfaces/oauthproviders.go
  i18n/en.json
  model/access.go
  model/config.go
  model/config_test.go
  model/gitlab/gitlab.go
  model/license.go
  model/switch_request.go
  services/telemetry/telemetry.go
  utils/license.go
  web/oauth.go
  web/oauth_test.go
Labels: 3: QA Review, release-note

#16497 [MM-31076]: Change receiver name for (me *AnalyticsRow) in model/analytics_row.go to be more idiomatic
  model/analytics_row.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16498 [MM-31077]: Change receiver name for (me *CompliancePost) in model/compliance_post.go to be more idiomatic
  model/compliance_post.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16499 [MM-31078]: Change receiver name for (me *MfaSecret) in model/mfa_secret.go to be more idiomatic
  model/mfa_secret.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#15764 implement and use striped LRU cache to lower mutex contention
  api4/apitestlib.go
  api4/openGraph.go
  api4/system.go
  app/helper_test.go
  app/options.go
  app/post_metadata.go
  app/server.go
  app/slashcommands/helper_test.go
  migrations/helper_test.go
  services/cache/lru.go
  services/cache/lru_striped.go
  services/cache/lru_striped_bench_test.go
  services/cache/lru_striped_test.go
  services/cache/lru_test.go
  services/cache/mocks/Cache.go
  services/cache/mocks/Provider.go
  services/cache/provider.go
  services/cache/provider_test.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/file_info_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/layer_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer_test.go
  store/localcachelayer/reaction_layer_test.go
  store/localcachelayer/role_layer_test.go
  store/localcachelayer/scheme_layer_test.go
  store/localcachelayer/team_layer_test.go
  store/localcachelayer/terms_of_service_layer_test.go
  store/localcachelayer/user_layer_test.go
  store/localcachelayer/webhook_layer_test.go
  store/sqlstore/channel_store.go
  web/web_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note

#16494 [MM-31074]: Change receiver name for (me *ShortcutsProvider) in app/slashcommands/command_shortcuts.go to be more idiomatic
  app/slashcommands/command_shortcuts.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16495 [MM-31075]: Change receiver name for (me *DataRetentionPolicy) in model/data_retention_policy.go to be more idiomatic
  model/data_retention_policy.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16526 MM-30918 Fix product notice check when user setting is missing (#16396)
  app/product_notices.go
  app/product_notices_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#16189 [MM-30092] api4/image: add support for protocol rel. urls
  api4/image.go
  api4/image_test.go
Labels: 4: Reviews Complete, release-note

#16415 Add shared channels related configuration under a E20 license check
  config/client.go
  model/license.go
  model/license_test.go
  utils/license.go
Labels: 3: QA Review, 4: Reviews Complete, Setup Cloud Test Server, release-note

#16531 MM-31326: Fix Striped LRU to have minimum of 1 bucket
  app/server.go
  store/localcachelayer/layer.go
Labels: 4: Reviews Complete, release-note-none

#16483 [MM-31068]: Change receiver name for (me *ClusterStats) in model/cluster_stats.go to be more idiomatic
  model/cluster_stats.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16484 [MM-31069]: Change receiver name for (me *ClusterDiscoveryService) in app/cluster_discovery.go to be more idiomatic
  app/cluster_discovery.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16485 [MM-31070]: Change receiver name for (me *HeaderProvider) in app/slashcommands/command_channel_header.go to be more idiomatic
  app/slashcommands/command_channel_header.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16528 MM-31171 Fork OpenGraph library to handle bad HTML from YouTube
  go.mod
  go.sum
  vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
  vendor/modules.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16535 [MM-31200] Generate preview regardless of HasPreviewImage value
  api4/file_test.go
  app/file.go
  tests/testgif_expected_preview.jpg
  tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#16486 [MM-31071]: Change receiver name for (me *CodeProvider) in app/slashcommands/command_code.go to be more idiomatic
  app/slashcommands/command_code.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16487 [MM-31072]: Change receiver name for (me *groupmsgProvider) in app/slashcommands/command_groupmsg.go to be more idiomatic
  app/slashcommands/command_groupmsg.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16493 [MM-31073]: Change receiver name for (me *OnlineProvider) in app/slashcommands/command_online.go to be more idiomatic
  app/slashcommands/command_online.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16501 [MM-31079]: Change receiver name for (me *TestHelper) in api4/apitestlib.go to be more idiomatic
  api4/apitestlib.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16521 [MM-31080]: Change receiver name for (me *EchoProvider) in app/slashcommands/command_echo.go to be more idiomatic
  app/slashcommands/command_echo.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16522 [MM-31081]: Change receiver name for (me *MeProvider) in app/slashcommands/command_me.go to be more idiomatic
  app/slashcommands/command_me.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16387 [MM-30911]: Change receiver name for (me *TestHelper) in app/slashcommands/helper_test.go to be more idiomatic.
  app/slashcommands/helper_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16536 Automated cherry pick of #16535
  api4/file_test.go
  app/file.go
  tests/testgif_expected_preview.jpg
  tests/testgif_expected_thumbnail.jpg
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16235 MM-27312 Allow uploading 10 files per post
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  model/post.go
  scripts/mattermost-mysql-5.0.sql
  scripts/mattermost-postgresql-5.0.sql
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16542 MM-31323: Fix racy test TestHandleCommandResponsePost
  app/notification.go
  app/notification_push.go
Labels: 4: Reviews Complete, release-note-none

#16534 Automated cherry pick of #16528
  go.mod
  go.sum
  vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
  vendor/modules.txt
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16546 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#16443 [MM-31018] Update email address for admin advisor contact requests to support-advisor@mattermost.com
  app/app.go
  app/integration_action.go
  model/config.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16548 Enable circleci test only for master
  .circleci/config.yml
Labels: release-note-none

#16550 [MM-31357] Avoid returning empty appError when autocompleting users
  store/searchlayer/user_layer.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#16541 MM-3124: Fix racy test TestPluginPanicLogs
  app/plugin_test.go
Labels: 4: Reviews Complete, release-note-none

#16425 [MM-30016] Allows to create incoming and outgoing webhooks for a different user
  api4/webhook.go
  api4/webhook_local.go
  api4/webhook_test.go
Labels: 4: Reviews Complete, release-note

#16555 MM-31366 -update einterface mocks
  einterfaces/mocks/OauthProvider.go
Labels: 2: Dev Review, release-note-none

#16563 MM-30826: Sentry crash: nil deference in model.AuthorizeRequest
  web/oauth.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note-none

#16564 MM-28549: Bump up postgres version
  build/docker-compose.common.yml
Labels: release-note

#16452 Remove model.AppError from searchlayer/post_layer.go
  store/searchlayer/post_layer.go
Labels: 4: Reviews Complete, release-note-none

#16551 MM-31154 Add CI step to validate store mocks
  .circleci/config.yml
Labels: release-note-none

#16567 [MM-31394] Revert "Temporary fix for oauth on cloud beta (#16281)"
  app/oauth.go
  web/handlers.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16096 MM-30005: Require manage_system to patch system_admin role.
  api4/role.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#16508 [MM-30984] Change default footer for copyright in 2 emails
  app/email.go
  i18n/en.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, release-note-none

#16568 MM-31401 Add Shared flag to Channels table
  model/channel.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#16489 [MM-31085] Create a db init command to initialize the database
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/utils.go
  config/store.go
  config/utils.go
  config/utils_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#16571 Automated cherry pick of #16550
  store/searchlayer/user_layer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16572 Automated cherry pick of #16535
  api4/file_test.go
  app/file.go
  tests/testgif_expected_preview.jpg
  tests/testgif_expected_thumbnail.jpg
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16573 Automated cherry pick of #16528
  go.mod
  go.sum
  vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
  vendor/modules.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16574 MM-30836: Feature flag for remote cluster service
  app/server.go
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, release-note-none

#16539 [MM-30539] New renewal link logic
  NOTICE.txt
  api4/license.go
  app/license.go
  app/license_test.go
  i18n/en.json
  model/system.go
  tests/test-config.json
  vendor/github.com/dgrijalva/jwt-go/.gitignore
  vendor/github.com/dgrijalva/jwt-go/.travis.yml
  vendor/github.com/dgrijalva/jwt-go/LICENSE
  vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/dgrijalva/jwt-go/README.md
  vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  vendor/github.com/dgrijalva/jwt-go/claims.go
  vendor/github.com/dgrijalva/jwt-go/doc.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/errors.go
  vendor/github.com/dgrijalva/jwt-go/hmac.go
  vendor/github.com/dgrijalva/jwt-go/map_claims.go
  vendor/github.com/dgrijalva/jwt-go/none.go
  vendor/github.com/dgrijalva/jwt-go/parser.go
  vendor/github.com/dgrijalva/jwt-go/rsa.go
  vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
  vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/signing_method.go
  vendor/github.com/dgrijalva/jwt-go/token.go
Labels: 3: QA Review, release-note

#16576 MM-30450: Pre-pacakge Incident Management v1.2.0
  Makefile
Labels: 4: Reviews Complete, release-note

#16580 Update db schema version for MM-31401 and MM-27312
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#15841 Remove usages of AppError on filesstore service
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/file.go
  app/opentracing/opentracing_layer.go
  app/server.go
  i18n/en.json
  services/filesstore/filesstore.go
  services/filesstore/localstore.go
  services/filesstore/mocks/FileBackend.go
  services/filesstore/s3store.go
  services/filesstore/s3store_test.go
  services/mailservice/mail.go
Labels: 4: Reviews Complete, release-note-none

#16587 MM-31062: Rewrite empty string checks to be more idiomatic
  api4/channel.go
  api4/config_test.go
  api4/user.go
  app/channel.go
  app/command.go
  app/login.go
  app/notification.go
  app/notification_email.go
  app/oauth.go
  app/team.go
  app/user.go
  app/webhook.go
  model/command_webhook.go
  model/config.go
  model/file_info.go
  model/outgoing_webhook.go
  model/scheme.go
  model/search_params.go
  store/localcachelayer/role_layer.go
  store/localcachelayer/scheme_layer.go
  store/sqlstore/audit_store.go
  store/sqlstore/group_store.go
  store/sqlstore/user_store.go
  web/handlers.go
  web/saml.go
Labels: 4: Reviews Complete, release-note-none

#16585 [MM-31512] Downgrade 4xx and 501 errors to info/debug level
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#16584 [MM-31398] upgrade error level to critical in case of panic or os.Exit
  api4/apitestlib.go
  app/helper_test.go
  app/slashcommands/helper_test.go
  migrations/helper_test.go
  store/sqlstore/upgrade.go
  testlib/helper.go
Labels: 4: Reviews Complete, release-note-none

#16599 Include import_test.zip
  tests/import_test.zip
Labels: 2: Dev Review, release-note-none

#16591 Lock CI from cloud/release-5.31
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
  store/sqlstore/upgrade.go
Labels: release-note-none

#16592 Bump version
  build/Dockerfile
  store/sqlstore/upgrade.go
Labels: release-note-none

#16597 MM-31356: Add a minimum required version check for Postgres
  app/server.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/store.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
Labels: 4: Reviews Complete, release-note-none

#16556 [MM-30978] avoid parsing nil PostAction in SlackAttachments
  model/integration_action.go
  model/post.go
  model/post_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16603 MM-31511: Fix incorrect replace repo
  go.mod
  go.sum
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#16583 [MM-31359] remove duplicated error logs
  api4/job.go
  api4/websocket.go
  app/app.go
  app/auto_responder.go
  app/bot.go
  app/channel.go
  app/command.go
  app/ldap.go
  app/login.go
  app/notification.go
  app/oauth.go
  app/upload.go
  app/user.go
  model/session.go
  services/awsmeter/awsmeter.go
  services/mailservice/mail.go
  store/searchlayer/post_layer.go
  utils/html.go
  wsapi/status.go
Labels: 4: Reviews Complete, release-note-none

#16615 change allcaps to camel case
  api4/channel_test.go
  api4/emoji.go
  api4/file.go
  api4/file_test.go
  api4/job.go
  api4/openGraph.go
  api4/plugin.go
  api4/post_test.go
  api4/system.go
  api4/system_test.go
  api4/team.go
  api4/team_test.go
  app/server.go
  app/server_test.go
  app/slashcommands/command_mute.go
  app/slashcommands/command_offline.go
  app/slashcommands/command_online.go
  app/slashcommands/command_open.go
  app/slashcommands/command_remove.go
  app/slashcommands/command_search.go
  app/slashcommands/command_settings.go
  app/slashcommands/command_shortcuts.go
  app/slashcommands/command_shrug.go
  app/team.go
  app/team_test.go
  app/user.go
  app/user_test.go
  app/webhook.go
  migrations/worker.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  web/params.go
Labels: 4: Reviews Complete, release-note-none
