Repository mattermost/mattermost, pull requests merged in 2020-10, with the labels that each got.

#15585 MM-29011: Add feature flag for shared channels
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, AutoMerge, QA Deferred

#15688 bump the package placeholder to use the latest mm package release
  build/Dockerfile
Labels: 4: Reviews Complete, CherryPick/Approved

#15696 bump the package placeholder to use the latest mm package release (#1…
  build/Dockerfile
Labels: AutoMerge, Changelog/Not Needed, CherryPick/Done, Docs/Not Needed

#15660 MM-26719 Add unit tests for SessionHasPermissionToCategory
  app/authorization_test.go
Labels: 4: Reviews Complete

#15572 Rudder key and dataplane in Config with env vars
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15666 [MM-28211] API pass-thru to the CWS for getting subscription
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
Labels: 4: Reviews Complete, QA Review Done

#15659 MM-29033: Modify Test S3 connection to handle path prefix
  i18n/en.json
  services/filesstore/s3store.go
Labels: 4: Reviews Complete

#15694 [MM-28630] Add ping endpoint to local mode
  api4/api.go
  api4/system_local.go
  api4/system_test.go
Labels: 4: Reviews Complete

#15725 Remove `cloud_restrictable` from `PluginSettings.Enabled`
  model/config.go
Labels: 4: Reviews Complete

#15726 Automated cherry pick of #15725
  model/config.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15612 Bump app version to 5.30
  model/version.go
Labels: 4: Reviews Complete

#15689 [MM-28420] Fix possible panic during plugin installation
  app/plugin_install.go
  app/plugin_install_test.go
Labels: 4: Reviews Complete, QA Deferred

#15334 [MM-24753] Improves error message when plugin crashes during slash command
  app/plugin_commands.go
  app/plugin_commands_test.go
  i18n/en.json
  plugin/environment.go
  plugin/health_check.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15376 MM-27353 Mini image previews
  api4/file_test.go
  app/file.go
  app/post.go
  model/file_info.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#15735 Add healthcheck to docker-compose databases to easier debug
  build/docker-compose.common.yml
Labels: AutoMerge

#15736 [internal]: Validate response signature
  i18n/en.json
Labels: 4: Reviews Complete

#15746 Lock CI
  .circleci/config.yml
Labels: AutoMerge

#15737 [MM-29229] Set part size for S3 uploads to avoid excessive allocation
  services/filesstore/filesstore_test.go
  services/filesstore/s3store.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred

#15657 [MM-29174] fix: enable automatic emoji resize feature
  api4/emoji_test.go
  app/emoji.go
Labels: 4: Reviews Complete, QA Deferred

#15748 Automated cherry pick of #15737
  services/filesstore/filesstore_test.go
  services/filesstore/s3store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15747 MM-28720 Temporary fix for oauth on cloud beta
  .circleci/config.yml
  app/oauth.go
  web/handlers.go
Labels: 2: Dev Review

#15752 [GH-15742] Remove direct Store calls from the Api layer for the file api4/system.go
  api4/system.go
  app/app.go
  app/app_iface.go
  app/app_test.go
  app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, Hacktoberfest

#14659 MM-24948: Command webhook store squirrel refactor
  store/sqlstore/command_webhook_store.go
Labels: 4: Reviews Complete, AutoMerge, QA Deferred

#15504 ChannelStore migration Part 3
  app/channel.go
  app/channel_category.go
  app/channel_category_test.go
  app/export.go
  app/export_test.go
  app/permissions.go
  app/scheme.go
  app/syncables.go
  app/user.go
  i18n/en.json
  migrations/advanced_permissions_phase_2.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/channel_store_categories.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA Deferred

#15656 [MM-28217] Server API to serve up cloud customer information
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
Labels: 4: Reviews Complete, QA Review Done

#15718 Revert EN JSON changes
  api4/job_test.go
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#15783 Cherry pick of #15718
  api4/job_test.go
  i18n/en.json
Labels: AutoMerge

#15717 Automated cherry pick of #15572
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15436 [MM-27942] Request arch-specific plugin
  app/plugin.go
  model/marketplace_plugin.go
Labels: 4: Reviews Complete

#15790 Automated cherry pick of #15436
  app/plugin.go
  model/marketplace_plugin.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15791 Automated cherry pick of #15436
  app/plugin.go
  model/marketplace_plugin.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15789 Fix typos on 4 files: consecutive occurrences of 'the'
  app/plugin_install.go
  app/web_hub.go
  plugin/api.go
  utils/textgeneration.go
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest

#15807 [internal]: Added an error string for checking invalid time
  i18n/en.json
Labels: 4: Reviews Complete

#15756 MM-29264 Fix invalid server version handling / date constraint in InProduct Notices
  app/product_notices.go
  app/product_notices_test.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15817 Automated cherry pick of #15756
  app/product_notices.go
  app/product_notices_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15635 [MM-28810] channel_store_categories: check if object is nil after the query
  store/sqlstore/channel_store_categories.go
  store/storetest/channel_store.go
  store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, QA Deferred

#15819 [MM-29215] config/envrionment: fix a panic where a setting is not defined in model.Config
  config/environment.go
  config/environment_test.go
Labels: 4: Reviews Complete, QA Deferred

#15630 [MM-28885] app/plugin: check if plugin manifest has errors
  plugin/environment.go
  plugin/environment_test.go
Labels: 4: Reviews Complete, QA Deferred

#15821 [MM-29345] app/post_metadata: add a check to type casting
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 4: Reviews Complete, QA Deferred

#15754 Remove direct Store calls from the Api layer for the file api4/channe…
  api4/channel.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, Hacktoberfest, QA Deferred, hacktoberfest-accepted

#15857 [MM-28714] Add IsPaidTier to cloud Subscription type
  model/cloud.go
Labels: 2: Dev Review

#15840 MM-29400 Mark all current notices as viewed for newly created users
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/product_notices.go
  app/user.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15859 Automated cherry pick of #15840
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/product_notices.go
  app/user.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15858 MM-28540: Add missing config telemetry for 5.28 release.
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred

#15770 [MM-29273] Fix flaky test: TestUploadDataConcurrent
  app/upload.go
  app/upload_test.go
Labels: 4: Reviews Complete

#15861 Automated cherry pick of #15540
  api4/apitestlib.go
  api4/config_test.go
  app/helper_test.go
  cmd/mattermost/commands/cmdtestlib.go
  model/config.go
  services/mailservice/mail_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15860 Automated cherry pick of #15857
  model/cloud.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15559 [MM-28533] [MM-28532] [MM-28531] Fixes several bugs with sysconsole_write_usermanagement
  api4/user.go
  api4/user_test.go
  model/client4.go
  model/role.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15839 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed

#15806 Adding godocs for the 4 functions listed:
  store/sqlstore/team_store.go
Labels: 4: Reviews Complete, Hacktoberfest, Tests/Not Needed, hacktoberfest-accepted

#15900 MM-29354 - Remove pre-packaged incident response for v5.28
  Makefile
  go.tools.mod
  go.tools.sum
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 4: Reviews Complete, QA Deferred

#15667 added table of contents
  README.md
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#15908 Enable cloud billing
  api4/team_test.go
  model/config.go
Labels: 4: Reviews Complete

#15910 Normalize plugin path when s3 prefix is present
  app/plugin.go
Labels: 2: Dev Review, 3: QA Review, Setup HA Cloud Test Server

#15911 Automated cherry pick of #15910
  app/plugin.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15534 [MM-28638] Improve image thumbnail generation logic
  api4/file_test.go
  app/file.go
  app/image.go
  tests/10000x1.png
  tests/10000x1_expected_preview.jpeg
  tests/10000x1_expected_thumb.jpeg
  tests/1x10000.png
  tests/1x10000_expected_preview.jpeg
  tests/1x10000_expected_thumb.jpeg
Labels: 4: Reviews Complete

#15616 [MM-27277] Move away from storing uploaded files into memory
  app/file.go
  app/upload.go
  go.tools.sum
  i18n/en.json
Labels: 4: Reviews Complete

#15914 Updated README.md
  README.md
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#15683 MM-28702 - call InitEnterprise() to initialize Enterprise for cli
  cmd/mattermost/commands/init.go
Labels: 4: Reviews Complete, CherryPick/Candidate

#15916 MM-27454 - Added CWSUrl to Client Config
  config/client.go
Labels: 4: Reviews Complete

#15937 Automated cherry pick of #15916
  config/client.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15934 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#15935 Translations update from Weblate
  i18n/es.json
  i18n/pt-BR.json
  i18n/zh-CN.json
Labels: 2: Dev Review

#15751 Update file.go
  api4/file.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#15938 MM-29560 Correct Cloud detection in InProduct Notices
  app/product_notices.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15947 Automated cherry pick of #15938
  app/product_notices.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15909 Update golangci-lint to v1.31.0
  .circleci/config.yml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#15932 MM-29548: remove ability to update SAML admin filter settings
  model/config.go
Labels: 2: Dev Review, CherryPick/Approved

#15951 Post image schema fix (#15763)
  store/sqlstore/upgrade.go
Labels: 2: Dev Review

#15762 Added GoDoc for functions mentioned in Task 7 (#14004) team_store.go
  store/sqlstore/team_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none

#15862 [MM-29224] Fix bug where markdown image link doesn't show preview
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, kind/bug

#15958 [MM-29646] Add check for IsPaidTier, and don't send emails over limit for guest invites
  api4/team.go
  api4/team_test.go
Labels: 4: Reviews Complete, release-note-none

#15960 Automated cherry pick of #15958
  api4/team.go
  api4/team_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#15948 MM-29573: Reuse s3 client amongst all requests
  go.tools.mod
  go.tools.sum
  i18n/en.json
  services/filesstore/filesstore.go
  services/filesstore/s3store.go
Labels: 3: Reviews Complete, QA Deferred, release-note-none

#15878 MM-28249 Auto follow threads
  app/app_iface.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  i18n/en.json
  model/config.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/timerlayer/timerlayer.go
Labels: 3: Reviews Complete, release-note

#15972 on prem/cloud validation fixed
  model/product_notices.go
Labels: CherryPick/Approved, release-note-none

#15973 Automated cherry pick of #15972
  model/product_notices.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15955 MM-29572: Add Bifrost support to codebase
  services/filesstore/s3_overrides.go
  services/filesstore/s3store.go
Labels: 3: Reviews Complete, release-note-none

#15757 MM-28815: Message export query optimization.
  store/sqlstore/compliance_store.go
Labels: 3: Reviews Complete, CherryPick/Approved, release-note

#15988 [MM-29723] Added websocket event constant for updating the payment status for cloud
  model/websocket_message.go
Labels: 3: Reviews Complete, release-note-none

#15993 MMCTL download migration to S3 location
  scripts/download_mmctl_release.sh
Labels: release-note

#14975 Adds the release-note block to the PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review, Docs/Needed, kind/documentation, release-note

#16009 Automated cherry pick of #15988
  model/websocket_message.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16007 Skipping some telemetry tests on production builds
  services/telemetry/telemetry_test.go
Labels: release-note-none

#15990 [MM-29725] Add websocket event for when user activation status changes
  api4/user.go
  model/websocket_message.go
Labels: 4: Reviews Complete, release-note-none

#15426 [MM-28125] einterface/oauthprovide: return parsing errors
  app/oauth.go
  app/user.go
  einterfaces/oauthproviders.go
  model/gitlab/gitlab.go
  web/oauth_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred

#15989 bump incident response to v0.7.0 in cloud
  Makefile
Labels: 3: Reviews Complete, AutoMerge, release-note

#16011 Automated cherry pick of #15990
  api4/user.go
  model/websocket_message.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16014 Automated cherry pick of #15683
  cmd/mattermost/commands/init.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#15974 [MM-28218] API hookup for updating company info and address in MM app
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
Labels: 2: Dev Review, release-note-none

#16016 Automated cherry pick of #15426
  app/oauth.go
  app/user.go
  einterfaces/oauthproviders.go
  model/gitlab/gitlab.go
  web/oauth_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16013 Automated cherry pick of #15910
  app/plugin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#16032 Automated cherry pick of #15974
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16017 Automated cherry pick of #15334
  app/plugin_commands.go
  app/plugin_commands_test.go
  i18n/en.json
  plugin/environment.go
  plugin/health_check.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#16015 Automated cherry pick of #15543
  store/storetest/user_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16019 Translations update from Weblate
  i18n/ko.json
  i18n/nl.json
Labels: release-note-none

#16018 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#15753 [MM-24391] Render icon_emoji names surrounded by colons in incoming webhooks
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note

#16052 Translations update from Weblate (#16019)
  i18n/ko.json
  i18n/nl.json
Labels: release-note-none

#16047 MM-29747 Prepackage incidnet response 1.0 for cloud ga
  Makefile
Labels: 3: Reviews Complete, release-note

#16044 [MM-29731] Fix panic in saveUserTermsOfService
  api4/user.go
  api4/user_test.go
Labels: 4: Reviews Complete, QA Deferred

#16010 MM-29812: Fix a panic in auth code if GetChannel returns an error.
  app/authorization.go
  app/authorization_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note-none

#15933 MM-29522:fix typo in constant name
  app/ldap.go
  model/client4.go
  model/ldap.go
Labels: 3: Reviews Complete, release-note-none

#15936 MM-28882:ignore guest ldap sync
  einterfaces/ldap.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 3: Reviews Complete, release-note

#15959 DOPS-243: Add manifest.txt
  build/release.mk
Labels: release-note-none

#15625 Thread autoresponse posts with the post they are autoresponding to
  app/app_iface.go
  app/auto_responder.go
  app/auto_responder_test.go
  app/opentracing/opentracing_layer.go
  app/post.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#16063 Automated cherry pick of #15625
  app/app_iface.go
  app/auto_responder.go
  app/auto_responder_test.go
  app/opentracing/opentracing_layer.go
  app/post.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16058 [MM-29937] Don't allow email and contact name to be updated from the MM app
  model/cloud.go
Labels: 4: Reviews Complete, release-note-none

#16066 Automated cherry pick of #16058
  model/cloud.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#15949 MM-29525: Strip path_prefix from ListDirectory
  services/filesstore/s3store.go
Labels: 3: Reviews Complete, release-note-none

#16072 MM-22950: Remove supplier test
  store/sqlstore/supplier_test.go
Labels: 4: Reviews Complete, release-note-none

#15563 UserStore migration
  api4/user_test.go
  api4/user_viewmembers_test.go
  api4/websocket_test.go
  app/analytics.go
  app/authentication.go
  app/bot.go
  app/bot_test.go
  app/channel.go
  app/channel_test.go
  app/command.go
  app/config.go
  app/constants.go
  app/export.go
  app/import_functions.go
  app/integration_action.go
  app/license.go
  app/login.go
  app/notification.go
  app/notification_push.go
  app/oauth.go
  app/permissions.go
  app/post.go
  app/product_notices.go
  app/session.go
  app/slashcommands/auto_users.go
  app/slashcommands/command_groupmsg.go
  app/slashcommands/command_invite.go
  app/slashcommands/command_msg.go
  app/slashcommands/command_remove.go
  app/team.go
  app/user.go
  app/user_test.go
  app/webhook.go
  cmd/mattermost/commands/userargs.go
  i18n/en.json
  jobs/active_users/worker.go
  services/mfa/mfa.go
  services/mfa/mfa_test.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  services/slackimport/slackimport.go
  services/telemetry/telemetry.go
  store/constants.go
  store/localcachelayer/user_layer.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/user_layer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_store.go
  store/storetest/mocks/UserStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
  web/oauth_test.go
Labels: 4: Reviews Complete, QA Deferred

#15601 MM-27909: Add manage_shared_channels permission
  app/app_test.go
  app/permissions_migrations.go
  model/migration.go
  model/permission.go
  testlib/store.go
Labels: 3: Reviews Complete, release-note-none

#16064 [MM-29941] Fix nil dereference panic in SearchArchivedInTeam
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 3: Reviews Complete, release-note-none

#15727 [MM-29220] Adds a client function that retrieves the full status report
  model/client4.go
Labels: 4: Reviews Complete

#16082 upgrade DB to 5.29
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16056 [MM-29157] Cloud invoices logic
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
  web/context.go
  web/params.go
Labels: 2: QA Review, release-note-none

#16053 [MM-28363] User Limit Overage Warning Emails
  api4/user.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  templates/reached_user_limit_body.html
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#16083 Automated cherry pick of #16056
  api4/cloud.go
  einterfaces/cloud.go
  model/client4.go
  model/cloud.go
  web/context.go
  web/params.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16084 Automated cherry pick of #16053
  api4/user.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  templates/reached_user_limit_body.html
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16088 Automated cherry pick of #15913
  api4/plugin_test.go
  app/plugin.go
  model/marketplace_plugin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16031 [MM-29523] EmailVerified flag can be user as parameter
  api4/user_test.go
  model/user.go
Labels: 4: Reviews Complete, release-note-none

#16085 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none

#16086 Translations update from Weblate
  i18n/pt-BR.json
  i18n/ru.json
Labels: 2: Dev Review, release-note-none

#16060 [MM-29075] storetest/reaction_store: add sleep before updating entity
  store/storetest/reaction_store.go
Labels: 3: Reviews Complete, release-note-none

#16092 Automated cherry pick of #16031
  api4/user_test.go
  model/user.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#15996 Documents exported methods within SqlTeamStore methods
  store/sqlstore/team_store.go
Labels: 3: Reviews Complete, Hacktoberfest, Tests/Not Needed, hacktoberfest-accepted, release-note-none

#15880 [MM-29295] Fix data race in app.CreatePost()
  app/post.go
Labels: 3: Reviews Complete, release-note-none

#16101 Automated cherry pick of #15952
  Makefile
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16102 Automated cherry pick of #15993
  scripts/download_mmctl_release.sh
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16089 MM-28984: Add fallback text to push notification
  app/notification_push.go
  app/notification_push_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16106 Automated cherry pick of #15959
  build/release.mk
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16105 MMCTL is not being included in the package
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: 2: Dev Review, 2: Infra Review, release-note-none

#16108 Automated cherry pick of #16105
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16098 MM-29979: make websocket writes zero-alloc
  app/web_conn.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16110 Revert "MM-29979: make websocket writes zero-alloc"
  app/web_conn.go
Labels: 3: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16111 Added Subscription missing field for LastInvoice
  model/cloud.go
Labels: 3: Reviews Complete, release-note-none

#16112 Automated cherry pick of #16111
  model/cloud.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16118 Update Dockerfile to use 5.28.1
  build/Dockerfile
Labels: 3: Reviews Complete, AutoMerge, Changelog/Not Needed, CherryPick/Approved, Docs/Not Needed, release-note-none

#16168 Automated cherry pick of #16118
  build/Dockerfile
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16030 MM-29067 Add deterministic IDs for default sidebar categories
  api4/channel.go
  model/channel_sidebar.go
  model/channel_sidebar_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/upgrade.go
  store/storetest/channel_store_categories.go
  web/context.go
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#16117 MM-30041: Return correct error message for user save
  api4/apitestlib.go
  api4/user_test.go
  app/bot.go
  app/bot_test.go
  app/user.go
  app/user_test.go
  i18n/en.json
Labels: 3: Reviews Complete, release-note-none

#16081 upgrade DB to 5.29
  store/sqlstore/upgrade.go
Labels: release-note-none

#15994 MM-29703 Mark threads as read when channels are marked
  app/channel.go
  app/channel_test.go
  app/notification.go
  einterfaces/mocks/LdapInterface.go
  einterfaces/mocks/OauthProvider.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
  web/context_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, release-note-none

#16065 MM-28955 shared channels table
  go.mod
  go.sum
  i18n/en.json
  model/channel_shared.go
  model/channel_shared_test.go
  model/remote_cluster.go
  model/remote_cluster_test.go
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_shared_channels.go
  store/sqlstore/channel_store_shared_channels_test.go
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/remote_cluster_store_test.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/channel_store_shared_channels.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/RemoteClusterStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/remote_cluster_store.go
  store/storetest/store.go
  store/timerlayer/timerlayer.go
Labels: 3: Reviews Complete, release-note-none

#15765 GH-15624: Added plugin hooks for `ReationHasBeenAdded` and `ReactionHasBeenRemoved`
  app/plugin_hooks_test.go
  app/reaction.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
  plugin/plugintest/hooks.go
Labels: 4: Reviews Complete, Demo Plugin Changes/Done, Docs/Done, Hacktoberfest, hacktoberfest-accepted, release-note

#16183 Release 5.29 cherrypick Threads
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  einterfaces/mocks/LdapInterface.go
  einterfaces/mocks/OauthProvider.go
  i18n/en.json
  model/config.go
  model/thread.go
  model/utils.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/store.go
  store/sqlstore/supplier.go
  store/sqlstore/thread_store.go
  store/sqlstore/thread_store_test.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/store.go
  store/storetest/thread_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
  web/context_test.go
Labels: release-note-none

#16172 [MM-29978] storetest/team_store: fix flaky test for searching a short term
  store/storetest/team_store.go
Labels: 3: Reviews Complete, release-note-none
