Repository mattermost/mattermost, pull requests merged in 2020-08, with the labels that each got.

#15143 [MM-27293] Remove heap pre-allocation for file uploads
  api4/file.go
  app/file.go
Labels: 4: Reviews Complete

#15140 [MM-27281] Fix possible panic on server shutdown
  app/plugin.go
Labels: 4: Reviews Complete

#14549 [MM-24665] refactor team store to use squirrel
  go.tools.mod
  go.tools.sum
  i18n/en.json
  store/sqlstore/team_store.go
Labels: 4: Reviews Complete

#15019 MM-26836: Remove some app fields which cause race conditions
  app/app.go
  app/options.go
Labels: 4: Reviews Complete

#15149 [MM-27407] Return archived channels even if view archived config is false
  api4/channel_test.go
  app/channel.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15166 Fix empty string on app error
  app/user.go
  i18n/en.json
Labels: 4: Reviews Complete, Tests/Not Needed

#15100 MM-27178: Use FileSettings.Directory in export tool
  cmd/mattermost/commands/export.go
  config/utils.go
  i18n/en.json
  model/config.go
Labels: 4: Reviews Complete

#15182 Automated cherry pick of #15149
  api4/channel_test.go
  app/channel.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15017 RoleStore migration
  app/import_functions_test.go
  app/migrations.go
  app/permissions.go
  app/permissions_migrations.go
  app/role.go
  i18n/en.json
  store/localcachelayer/role_layer.go
  store/opentracinglayer/opentracinglayer.go
  store/sqlstore/role_store.go
  store/store.go
  store/storetest/mocks/RoleStore.go
  store/storetest/scheme_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge

#15165 MM-27184 deprecate model.SetExpireInDays to fix mobile logout bug
  .gitignore
  api4/user.go
  app/app_iface.go
  app/login.go
  app/oauth.go
  app/oauth_test.go
  app/opentracing/opentracing_layer.go
  app/session.go
  app/session_test.go
  model/session.go
  web/handlers_test.go
Labels: 4: Reviews Complete

#14884 [MM-24526] Filter * characters from the search terms in DB
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: 4: Reviews Complete

#15187 Automated cherry pick of #14972
  model/post.go
  model/post_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15155 MM-27412 Fixing /test command.
  app/auto_channels.go
  app/auto_environment.go
  app/auto_posts.go
  app/command_loadtest.go
Labels: 4: Reviews Complete

#15196 api4/bot: fix permission check in convert handler
  api4/bot.go
Labels: 4: Reviews Complete

#15194 Update "Enterprise E20" to "Enterprise Edition"
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, AutomatedCherryPick, CherryPick/Approved

#15193 [MM-27519] Guest User Invites not working in SAML only environment
  app/team.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#15204 Automated cherry pick of #15193
  app/team.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15205 Cherry pick of #15193
  app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed

#15203 Automated cherry pick of #15194
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15191 [MM-27194] Dont include users who have been deactivated in compliance report
  model/channel_member_history_result.go
  store/sqlstore/channel_member_history_store.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15199 MM-27574: Add Learn More text to Admin Advisor bot message
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#15209 Automated cherry pick of #15199
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15210 Automated cherry pick of #15100
  cmd/mattermost/commands/export.go
  config/utils.go
  i18n/en.json
  model/config.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15212 Cherry pick of #15191 release-5.26
  model/channel_member_history_result.go
  store/sqlstore/channel_member_history_store.go
Labels: Changelog/Not Needed, Docs/Not Needed

#15211 Automated cherry pick of #15100
  cmd/mattermost/commands/export.go
  config/utils.go
  i18n/en.json
  model/config.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15213 Cherry pick of #15191 release-5.25
  model/channel_member_history_result.go
  store/sqlstore/channel_member_history_store.go
Labels: Changelog/Not Needed, Docs/Not Needed

#15200 [MM-27376] api4/channel: add move channel to local mode
  api4/channel_local.go
  api4/channel_test.go
  app/channel.go
Labels: 4: Reviews Complete

#15207 MM-27575: Use index hints to prevent index_merge_intersection
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15219 Automated cherry pick of #15207
  store/sqlstore/post_store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15220 MM-27575: Use index hints to prevent index_merge_intersection (#15207)
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, AutoMerge

#15215 MM-27572 permissions regression
  app/authorization.go
  app/authorization_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#15222 Automated cherry pick of #15215
  app/authorization.go
  app/authorization_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15217 [MM-27485] Start required docker services before running tests
  Makefile
  config.mk
Labels: 4: Reviews Complete

#15218 MM-27508 - Fix slash commands
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete

#15221 [MM-27623] Add new session prop for oauth
  app/app_iface.go
  app/login.go
  app/opentracing/opentracing_layer.go
  app/session_test.go
  model/saml.go
  model/session.go
  model/session_test.go
  web/oauth.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15227 [MM-27623] Add new session prop for oauth (#15221)
  app/app_iface.go
  app/login.go
  app/opentracing_layer.go
  app/session_test.go
  model/saml.go
  model/session.go
  model/session_test.go
  web/oauth.go
Labels: Changelog/Not Needed, Docs/Not Needed

#15226 [MM-27623] [cherry-pick] Add new session prop for oauth (#15221)
  app/app_iface.go
  app/login.go
  app/opentracing/opentracing_layer.go
  app/session_test.go
  model/saml.go
  model/session.go
  model/session_test.go
  web/oauth.go
Labels: Changelog/Not Needed, Docs/Not Needed

#15216 MM-27040: Fix flaky tests due to same UpdateAt timestamp
  store/sqlstore/bot_store.go
  store/sqlstore/channel_store.go
  store/sqlstore/oauth_store.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete

#15201 [MM-27377] api4/team_local: add updateChannelPrivacy and restoreTeam to local mode
  api4/team_local.go
  api4/team_test.go
Labels: 4: Reviews Complete, QA Review Done

#14860 Moving slack importer into a service
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/slack.go
  services/slackimport/converters.go
  services/slackimport/main_test.go
  services/slackimport/parsers.go
  services/slackimport/slackimport.go
  services/slackimport/slackimport_test.go
Labels: 4: Reviews Complete

#14991 MM-26575: Move app initialization inside Websocket router out of handler
  app/server.go
  app/websocket_router.go
Labels: 4: Reviews Complete

#15123 First part of PostStore migration
  app/channel.go
  app/file.go
  app/import_functions.go
  app/integration_action.go
  app/integration_action_test.go
  app/post.go
  app/user.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge

#14954 Adding initial retry layer version
  app/server.go
  store/layer_generators/main.go
  store/layer_generators/retry_layer.go.tmpl
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/supplier_reactions.go
  store/store.go
  store/store_test.go
  store/storetest/reaction_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#14924 Migrating Team.SaveMember/SaveMultipleMembers into errors
  app/import_functions.go
  app/slashcommands/auto_users.go
  app/team.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/team_layer.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/group_store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/post_store.go
  store/storetest/team_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#14971 Pluginstore migration
  app/plugin_key_value_store.go
  app/plugin_test.go
  i18n/en.json
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/plugin_store.go
  store/store.go
  store/storetest/mocks/PluginStore.go
  store/storetest/plugin_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge

#15171 MM-27456: Use reflect-free serialization for hot structs
  Makefile
  go.mod
  go.sum
  go.tools.mod
  go.tools.sum
  model/serialized_gen.go
  model/session.go
  model/user.go
  services/cache/lru.go
  services/cache/lru_test.go
  store/localcachelayer/user_layer_test.go
  vendor/github.com/tinylib/msgp/.gitignore
  vendor/github.com/tinylib/msgp/.travis.yml
  vendor/github.com/tinylib/msgp/Makefile
  vendor/github.com/tinylib/msgp/README.md
  vendor/github.com/tinylib/msgp/gen/decode.go
  vendor/github.com/tinylib/msgp/gen/elem.go
  vendor/github.com/tinylib/msgp/gen/encode.go
  vendor/github.com/tinylib/msgp/gen/marshal.go
  vendor/github.com/tinylib/msgp/gen/size.go
  vendor/github.com/tinylib/msgp/gen/spec.go
  vendor/github.com/tinylib/msgp/gen/testgen.go
  vendor/github.com/tinylib/msgp/gen/unmarshal.go
  vendor/github.com/tinylib/msgp/main.go
  vendor/github.com/tinylib/msgp/parse/directives.go
  vendor/github.com/tinylib/msgp/parse/getast.go
  vendor/github.com/tinylib/msgp/parse/inline.go
  vendor/github.com/tinylib/msgp/printer/print.go
  vendor/github.com/ttacon/chalk/.gitignore
  vendor/github.com/ttacon/chalk/LICENSE
  vendor/github.com/ttacon/chalk/README.md
  vendor/github.com/ttacon/chalk/chalk.go
  vendor/github.com/ttacon/chalk/doc.go
  vendor/modules.txt
Labels: 4: Reviews Complete, AutoMerge

#15234 cmd/version: skip server start to get the current mattermost version
  cmd/mattermost/commands/version.go
Labels: 4: Reviews Complete

#14484 MM-24544: Fix crash in (*Status).ToClusterJson
  model/status.go
Labels: 4: Reviews Complete

#15238 MM-27735: Do not build test and other tools in CI
  .circleci/config.yml
  build/release.mk
Labels: 4: Reviews Complete

#15110 [MM-26837] attempt at fixing flaky test on mysql-5.6
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete

#14835 SystemStore migration to return plain errors
  app/app.go
  app/config.go
  app/diagnostics.go
  app/license.go
  app/permissions.go
  app/permissions_migrations.go
  app/server.go
  i18n/en.json
  migrations/migrations_test.go
  migrations/worker.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/system_store.go
  store/store.go
  store/storetest/mocks/SystemStore.go
  store/storetest/system_store.go
  store/timerlayer/timerlayer.go
  testlib/store.go
Labels: 4: Reviews Complete, AutoMerge

#15230 MM-27507: Propagate rate limit errors to client
  api4/team_local.go
  api4/team_test.go
  app/email.go
  app/email_test.go
  app/team.go
  cmd/mattermost/commands/user.go
  i18n/en.json
Labels: 4: Reviews Complete

#15202 [MM-25659] ability to permanent delete channel through client
  api4/channel.go
  api4/channel_local.go
  api4/channel_test.go
  app/channel.go
  i18n/en.json
  model/client4.go
  model/config.go
Labels: 4: Reviews Complete

#14820 Prefixing all enterprise translations with ent
  i18n/en.json
Labels: 4: Reviews Complete

#14587 Match Users Even When SAML (+other) Contains Mixed Case
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, CherryPick/Approved

#14928 [MM-25657] api4/config: add config migrate endpoint
  api4/config.go
  api4/config_local.go
  api4/config_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete

#15267 Automated cherry pick of #15155
  app/auto_channels.go
  app/auto_environment.go
  app/auto_posts.go
  app/command_loadtest.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15022 [MM-26033] app/email: remove a setting that blocks test email code.
  api4/system_test.go
  app/admin.go
Labels: 4: Reviews Complete

#15265 Automated cherry pick of #14484
  model/status.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15266 Automated cherry pick of #14587
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15269 Automated cherry pick of #15022
  api4/system_test.go
  app/admin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15264 Lock CI
  .circleci/config.yml
Labels: AutoMerge

#15242 [MM-27700] storetest/channel_store: fix flaky test for search too short term
  store/storetest/channel_store.go
Labels: 4: Reviews Complete

#15268 MM-27868 fix panic when user joins teams with default channels archived
  app/channel.go
Labels: 4: Reviews Complete

#15262 [MM-27836] Fix possible panic when patching config
  api4/config.go
  api4/config_test.go
Labels: 4: Reviews Complete

#14911 Fix the error message from get oldest entity in ES indexer
  i18n/en.json
Labels: 3: QA Review

#15275 Restrict the sampledata generation to not run without enough users for group channels
  cmd/mattermost/commands/sampledata.go
  cmd/mattermost/commands/sampledata_test.go
Labels: 4: Reviews Complete

#15279 Automated cherry pick of #15143
  api4/file.go
  app/file.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15280 Automated cherry pick of #15140
  app/plugin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15274 MM-27887: set traceback to crash from code
  cmd/mattermost/commands/server.go
Labels: 4: Reviews Complete

#15281 MM-27868 cherry pick
  app/channel.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed

#15282 Automated cherry pick of #15262
  api4/config.go
  api4/config_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15283 MM-27184 cherry pick
  .gitignore
  api4/user.go
  app/app_iface.go
  app/login.go
  app/oauth.go
  app/oauth_test.go
  app/opentracing/opentracing_layer.go
  app/session.go
  app/session_test.go
  model/session.go
  web/handlers_test.go
Labels: AutoMerge, Changelog/Not Needed, Docs/Not Needed

#15289 Automated cherry pick of #15001
  web/oauth.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15178 MM-27449: Compliance Jobs rerun after warning status
  cmd/mattermost/commands/export.go
  jobs/jobs.go
  jobs/schedulers_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/job_store.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved

#14823 [MM-25673] Upgrades and migrations to start using master gorp
  go.mod
  go.sum
  store/sqlstore/supplier.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/webhook_store.go
  vendor/github.com/mattermost/gorp/.travis.yml
  vendor/github.com/mattermost/gorp/Makefile
  vendor/github.com/mattermost/gorp/README.md
  vendor/github.com/mattermost/gorp/db.go
  vendor/github.com/mattermost/gorp/dialect_mysql.go
  vendor/github.com/mattermost/gorp/go.mod
  vendor/github.com/mattermost/gorp/go.sum
  vendor/github.com/mattermost/gorp/gorp.go
  vendor/github.com/mattermost/gorp/nulltypes.go
  vendor/github.com/mattermost/gorp/table.go
  vendor/github.com/mattermost/gorp/table_bindings.go
  vendor/github.com/mattermost/gorp/test_all.sh
  vendor/github.com/tinylib/msgp/.gitignore
  vendor/github.com/tinylib/msgp/.travis.yml
  vendor/github.com/tinylib/msgp/Makefile
  vendor/github.com/tinylib/msgp/README.md
  vendor/github.com/tinylib/msgp/gen/decode.go
  vendor/github.com/tinylib/msgp/gen/elem.go
  vendor/github.com/tinylib/msgp/gen/encode.go
  vendor/github.com/tinylib/msgp/gen/marshal.go
  vendor/github.com/tinylib/msgp/gen/size.go
  vendor/github.com/tinylib/msgp/gen/spec.go
  vendor/github.com/tinylib/msgp/gen/testgen.go
  vendor/github.com/tinylib/msgp/gen/unmarshal.go
  vendor/github.com/tinylib/msgp/main.go
  vendor/github.com/tinylib/msgp/parse/directives.go
  vendor/github.com/tinylib/msgp/parse/getast.go
  vendor/github.com/tinylib/msgp/parse/inline.go
  vendor/github.com/tinylib/msgp/printer/print.go
  vendor/github.com/ttacon/chalk/.gitignore
  vendor/github.com/ttacon/chalk/LICENSE
  vendor/github.com/ttacon/chalk/README.md
  vendor/github.com/ttacon/chalk/chalk.go
  vendor/github.com/ttacon/chalk/doc.go
  vendor/go.etcd.io/bbolt/README.md
  vendor/go.etcd.io/bbolt/freelist.go
  vendor/go.etcd.io/bbolt/node.go
  vendor/go.etcd.io/bbolt/page.go
  vendor/go.etcd.io/bbolt/tx.go
  vendor/go.etcd.io/bbolt/unsafe.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#15251 MM-27512: Use an authenticated user to bump up request rate limit
  Makefile
  build/release.mk
  scripts/get_latest_release.sh
Labels: 4: Reviews Complete

#15284 MM-27852:Enable picture update for SAML
  app/login.go
Labels: 4: Reviews Complete, CherryPick/Approved

#15299 Automated cherry pick of #15284
  app/login.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15297 MM-27930 - Cloud license feature
  model/license.go
  utils/license.go
Labels: 4: Reviews Complete

#15301 Automated cherry pick of #15284
  app/login.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15303 Automated cherry pick of #15284
  app/login.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15192 [MM-27367] fix ldap group decoding in client
  model/client4.go
Labels: 4: Reviews Complete

#15053 [MM-27022] Add marketplace endpoints to local mode
  api4/plugin_local.go
  api4/plugin_test.go
Labels: 4: Reviews Complete

#15277 db: upgrade db to 5.27
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete

#15276 image: bump default MM package to use release 5.26.0
  build/Dockerfile
Labels: 4: Reviews Complete

#15278 db: upgrade db to 5.27
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete

#15026 Rudder key and dataplane in Config
  app/diagnostics.go
  app/diagnostics_test.go
  app/server.go
Labels: 4: Reviews Complete

#15293 MM-27648: Fix a hub deadlock while revoking session
  app/session.go
  app/web_hub_test.go
Labels: 4: Reviews Complete, QA Deferred

#15197 [MM-27535] User invite limits for MM Cloud
  api4/team.go
  api4/team_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/team.go
  config/client.go
  go.mod
  go.sum
  go.tools.mod
  go.tools.sum
  i18n/en.json
  model/config.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/modules.txt
Labels: QA Review Done

#15271 MM-27883 - remove deep copies from the cache layer
  store/localcachelayer/channel_layer.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
Labels: 4: Reviews Complete, QA Deferred

#15314 Automated cherry pick of #15293
  app/session.go
  app/web_hub_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15228 MM-27525: Obscure Global Relay's SMTP password.
  config/utils.go
  model/config.go
Labels: 4: Reviews Complete

#15236 fileinfostore
  app/file.go
  app/notification.go
  app/post.go
  app/user.go
  i18n/en.json
  store/localcachelayer/file_info_layer.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#15250 jobstore
  app/job.go
  i18n/en.json
  jobs/jobs.go
  migrations/migrations.go
  migrations/migrations_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/job_store.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#15309 MM-27948: Use --depth=1 to clone git repos faster
  .circleci/config.yml
Labels: 4: Reviews Complete

#15241 Drain body to reuse tcp connection
  services/mailservice/inbucket.go
Labels: 4: Reviews Complete

#15330 Fix return nil
  config/file.go
  store/layer_generators/main.go
  store/layer_generators/opentracing_layer.go.tmpl
  store/layer_generators/retry_layer.go.tmpl
  store/layer_generators/timer_layer.go.tmpl
  store/retrylayer/retrylayer.go
Labels: QA Deferred

#15321 MM-23063: Fix flaky test TestTermsOfServiceStore
  store/storetest/terms_of_service_store.go
Labels: 4: Reviews Complete

#15331 MM-28043:NoRows error now being returned, handle in callers
  jobs/jobs.go
Labels: 2: Dev Review

#15335 cleanup error logging from user_store
  store/sqlstore/user_store.go
Labels: 4: Reviews Complete

#15341 [MM-27919] Allow i18n and resources to be loaded using an environment variable
  testlib/resources.go
  utils/i18n.go
Labels: 4: Reviews Complete, QA Deferred

#15342 [MM-27535] Change ExperimentalCloudUserLimit config to be base 10
  config/client.go
Labels: 2: Dev Review

#15320 [MM-27535] Change string to be more in-line with designs and the front end verbiage
  api4/team_test.go
  go.tools.sum
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#15338 Fix tests for no linux systems
  services/upgrader/upgrader_linux_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, Tests/Not Needed

#15345 Automated cherry pick of #15338
  services/upgrader/upgrader_linux_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#15343 Add functionality to update password with password hash
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  go.mod
  go.sum
  go.tools.mod
  go.tools.sum
  i18n/en.json
  model/client4.go
  vendor/go.etcd.io/bbolt/README.md
  vendor/go.etcd.io/bbolt/freelist.go
  vendor/go.etcd.io/bbolt/node.go
  vendor/go.etcd.io/bbolt/page.go
  vendor/go.etcd.io/bbolt/tx.go
  vendor/go.etcd.io/bbolt/unsafe.go
  vendor/modules.txt
Labels: 4: Reviews Complete

#15244 MM-27570,MM-27757 - Activate/Deactivate plugins concurrently
  app/plugin.go
  app/plugin_test.go
Labels: 4: Reviews Complete, QA Review Done

#15348 MM-27525: Sanitizes gifycat's and Oauth secrets.
  config/utils.go
  model/config.go
Labels: 4: Reviews Complete

#15346 [MM-28081] make test: ignore data directory while running make test
  Makefile
Labels: 4: Reviews Complete

#14573 [MM-24522] remove duplication in OR and IncludeDeletedChannels params for search
  app/post.go
  i18n/en.json
  model/search_params.go
  model/search_params_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete

#14966 [MM-25645] api4/user: add migrate_auth endpoints
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete

#15324 MM-27722 Make sidebar category validation silently reject bad channel IDs
  api4/channel_category.go
  api4/channel_category_test.go
  model/client4.go
Labels: 4: Reviews Complete
