Repository mattermost/mattermost, pull requests merged in 2020-01, with the labels that each got.

#13353 MM-20225: Fix notification badge count for All Activity
  app/notification_push.go
  app/notification_push_test.go
Labels: CherryPick/Approved, QA Review Done

#13545 Automated cherry pick of #13353
  app/notification_push.go
  app/notification_push_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13445 [MM-21359] Add extra permission check when updating an OAuth app
  api4/oauth.go
  api4/oauth_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#13551 Automated cherry pick of #13445
  api4/oauth.go
  api4/oauth_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13552 Automated cherry pick of #13445
  api4/oauth.go
  api4/oauth_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13231 [MM-16798] Add a Guest Accounts feature flag
  api4/role.go
  api4/team.go
  api4/user.go
  model/license.go
  model/license_test.go
  utils/license.go
Labels: 3: Reviews Complete, QA Review Done

#13555 Cherry pick of #13445
  api4/oauth.go
  api4/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13556 Cherry pick of #13445
  api4/oauth.go
  api4/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13557 Cherry pick of #13445
  api4/oauth.go
  api4/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13392 [MM-20029] Fix incorrect bot message
  app/command_invite.go
  app/command_invite_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13441 MM-21336: Improve channel rename restrictions
  app/channel.go
  app/channel_test.go
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#13558 Automated cherry pick of #13392
  app/command_invite.go
  app/command_invite_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13560 Automated cherry pick of #13441
  app/channel.go
  app/channel_test.go
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13562 [MM-21472] Fix Email to SAML migration
  api4/saml_test.go
  web/saml.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13567 Automated cherry pick of #13562
  api4/saml_test.go
  web/saml.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#12538 [MM-12374] Add CLI command for moving outgoing webhook
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
  i18n/en.json
Labels: Hacktoberfest, QA Review Done

#13537 MM-21396: fix duplicate channel cluster invalidations
  app/cluster_handlers.go
  app/web_hub.go
Labels: 3: Reviews Complete

#13526 MM-18384 - Migrate tests from "app/notification_test.go" to use testify
  app/notification_test.go
  go.sum
Labels: 3: Reviews Complete, Tests/Not Needed

#13359 MM-21008 Fix CLI nil pointer panic
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/channel_test.go
Labels: 3: Reviews Complete

#13434 [MM-20881] Server changes for new experimental channel sidebar setting
  app/diagnostics.go
  config/client.go
  model/config.go
Labels: 2: Dev Review

#13021 Gh 10166
  model/manifest.go
  plugin/helpers.go
  plugin/helpers_config.go
  plugin/helpers_config_test.go
  plugin/plugintest/helpers.go
Labels: 3: Reviews Complete, QA Review Done

#13561 Fix inconsistencies in variable names for struct methods
  app/notification.go
  app/slack.go
  app/web_conn.go
  go.mod
  model/access.go
  model/compliance.go
  model/config.go
  model/file_info.go
  model/guest_invite.go
  model/job.go
  model/post.go
  model/role.go
  model/team.go
  model/team_search.go
  model/user.go
  model/websocket_message.go
  plugin/client_rpc.go
  store/sqlstore/compliance_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/supplier.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete

#13579 Cherry pick of #13562
  api4/saml_test.go
  web/handlers.go
  web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13574 Don't lint EE code in TE CI
  .circleci/config.yml
  Makefile
  build/Jenkinsfile.pr
Labels: 2: Dev Review, 2: QA Review

#13332 MM-19628: Fix race in (*registeredPlugin).State access
  plugin/environment.go
Labels: 3: Reviews Complete

#12994 [MM-16700] Add InstallPluginFromUrl helper method
  plugin/helpers.go
  plugin/helpers_plugin.go
  plugin/helpers_plugin_test.go
  plugin/plugintest/helpers.go
Labels: QA Review Done

#13582 adding inconsistentReceiverName check to vet task
  Makefile
Labels: 3: Reviews Complete, Tests/Not Needed

#13581 Fixes #13580 : notification.log should be ignored in the gitignore
  .gitignore
Labels: 2: Dev Review, Tests/Not Needed

#13544 Golint fix config
  .golangci.yml
  config/client.go
  config/client_test.go
  config/config_generator/generator/generator.go
  config/database_test.go
  config/file.go
  config/memory.go
  config/migrate.go
  config/utils_test.go
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#13527 MM-21285: Remove environment overrides before config broadcast
  app/config.go
  config/common.go
  config/common_test.go
  config/store.go
Labels: 3: Reviews Complete, QA Review Done

#13447 upgrade DB to 5.19.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13437 MM-21334: Caching removed from post_store.go, remove caching test
  store/storetest/post_store.go
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved

#13549 Removing certain unneded cluster invalidation messages
  app/cluster_handlers.go
  app/web_hub.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done

#13569 MM-20627: Create SECURITY.md
  SECURITY.md
Labels: 2: Dev Review

#13591 Automated cherry pick of #13437
  store/storetest/post_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13592 GH-13570 Allow /static/plugins/* endpoint responses to be cached (except for 404s)
  web/static.go
  web/web_test.go
Labels: 3: Reviews Complete

#13578 Remove redundant in-line image tests
  tests/test-markdown-basics.md
Labels: 3: Reviews Complete

#13349 [MM-20804] Add "Unarchive Channel" option to the channel info screen
  api4/channel.go
  app/channel.go
  i18n/en.json
  model/post.go
  model/websocket_message.go
Labels: 3: Reviews Complete, QA Review Done

#13384 [MM 19840] Create a Cache Interface abstraction to support multiple cache backends
  api4/openGraph.go
  api4/system.go
  app/admin.go
  app/notification.go
  app/post_metadata.go
  app/server.go
  app/server_app_adapters.go
  app/status.go
  go.mod
  services/cache/cache.go
  services/cache/lru/lru.go
  services/cache/lru/lru_test.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/layer_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer_test.go
  store/localcachelayer/reaction_layer_test.go
  store/localcachelayer/role_layer_test.go
  store/localcachelayer/scheme_layer_test.go
  store/localcachelayer/team_layer_test.go
  store/localcachelayer/terms_of_service_layer_test.go
  store/localcachelayer/user_layer_test.go
  store/localcachelayer/webhook_layer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/user_store.go
  store/storetest/mocks/Cache.go
  store/storetest/mocks/CacheProvider.go
  store/storetest/store.go
Labels: 3: Reviews Complete, QA Review Done

#13573 translations PR 20200106
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Tests/Not Needed

#13601 MM-21368: Optimize MapStringsToQueryParams
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: 2: Dev Review

#13600 MM-21608: Remove buggy migration code
  app/server.go
Labels: 3: Reviews Complete, CherryPick/Approved

#13529 MM-21211: Optimize Channelstore.UpdateLastViewedAt
  store/sqlstore/channel_store.go
Labels: 3: Reviews Complete

#13605 Automated cherry pick of #13600
  app/server.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13217 Optimize queries and indexes on posts table
  store/sqlstore/post_store.go
Labels: 3: Reviews Complete

#13311 MM-20698: Add server support for getting SAML metadata and updating S…
  api4/saml.go
  api4/user_test.go
  app/saml.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/config_test.go
  model/saml.go
  tests/test-config.json
Labels: 3: Reviews Complete, QA Review Done

#13599 MM-21548: Fix Flakey Test
  store/storetest/channel_store.go
Labels: 3: Reviews Complete

#13522 MM-19274 - Migrate tests from "model/config_test.go" to use testify
  model/config_test.go
Labels: 3: Reviews Complete, Lifecycle/1:stale, QA Review Done

#13607 Convert store/storetest/compliance_store.go t.Fatal to require
  store/storetest/compliance_store.go
Labels: 2: Dev Review, Tests/Not Needed

#13361 MM-20644: Add users to teams as a SchemeAdmin based on a new configuration field on GroupTeams and GroupChannels records.
  api4/group.go
  api4/group_test.go
  app/channel.go
  app/channel_test.go
  app/group.go
  app/group_test.go
  app/team.go
  app/team_test.go
  model/client4.go
  model/group.go
  model/group_syncable.go
  store/sqlstore/channel_store.go
  store/sqlstore/group_store.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/TeamStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done

#13536 [GH-13073] Migrate profilesInChannelCache cache from store/sqlstore/user_store.go to the new store/localcachelayer
  app/cluster_handlers.go
  app/web_hub.go
  model/cluster_message.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
  store/sqlstore/user_store.go
Labels: 3: Reviews Complete, QA Review Done

#13540 MM-21229 - Customization > Site Name help text doesn't match text field behavior
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13538 MM-21356: Conditionally set user status online
  api4/post.go
  api4/post_test.go
Labels: 3: Reviews Complete

#13593 MM-21210: Add LRU cache for ChannelStore.GetMembersForUser
  model/cluster_message.go
  services/cache/cache.go
  services/cache/lru/lru.go
  store/localcachelayer/channel_layer.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/storetest/mocks/ChannelStore.go
Labels: 3: Reviews Complete, AutoMerge

#13572 MM-21520: Remove temporary databases after tests run
  config/migrate_test.go
  store/localcachelayer/layer_test.go
  store/sqlstore/store_test.go
Labels: 3: Reviews Complete, QA Review Done

#13534 [MM-20061] Add System Admin filter to both LDAP and SAML
  app/diagnostics.go
  app/user.go
  i18n/en.json
  model/config.go
  model/config_test.go
  model/user.go
Labels: 3: Reviews Complete, QA Review Done

#13543 MM-21102: Add ExperimentalSettings.UseNewSAMLLibrary to diagnostics
  app/diagnostics.go
  app/diagnostics_test.go
Labels: 3: Reviews Complete, QA Review Done

#13521 MM-19137 - Migrate tests from "model/post_test.go" to use testify
  model/post_test.go
Labels: 3: Reviews Complete, QA Review Done

#13362 [MM-17155] Changes to email notifications to support Deep Linking page
  app/notification_email.go
  app/notification_email_test.go
Labels: 3: Reviews Complete

#13425 [MM-21123] Add Labels to upstream Marketplace response
  api4/plugin_test.go
  app/plugin.go
  model/marketplace_plugin.go
Labels: 3: Reviews Complete

#13225 [MM-20706] Drop 26 character requirement from post action IDs
  api4/integration_action.go
  api4/integration_action_test.go
  web/context.go
Labels: 3: Reviews Complete, Demo Plugin Changes/Needed, Docs/Needed, QA Review Done

#13568 Fix issues found by golangci v1.22.2
  .golangci.yml
  store/layer_generators/main.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done

#13524 MM-19463 - Migrate tests from "web/webhook_test.go" to use testify
  web/webhook_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#12997 [MM-19720] Expose endpoint for config patch
  api4/config.go
  api4/config_test.go
  app/config.go
  model/client4.go
Labels: 3: Reviews Complete

#13372 MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent
  api4/team.go
  api4/team_test.go
  app/plugin_api.go
  app/team.go
  go.mod
  model/client4.go
  model/team_member.go
  plugin/api.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 2: Dev Review, 3: Reviews Complete, AutoMerge, QA Review Done

#13622 translations PR 20200113
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ro.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, AutoMerge

#13606 MM-21651 - Add additional reserved team name
  model/utils.go
Labels: 3: Reviews Complete, Docs/Needed, QA Review Done

#13615 bump alpine version and mm as well
  build/Dockerfile
Labels: 3: Reviews Complete

#13616 Thread fetching revert
  api4/post.go
  app/auto_posts.go
  app/channel_test.go
  app/command_loadtest.go
  app/file.go
  app/plugin_api.go
  app/post.go
  model/post.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/timer_layer.go
Labels: 3: Reviews Complete, QA Review Done

#13621 Update bundled plugins for v5.20
  Makefile
Labels: 3: Reviews Complete

#13620 [MM-21693] Make LocalCacheUserStore.Get/GetProfileByIds return a copy of the stored data
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#13449 MM-19606- Rework Prepackaged Plugins
  api4/apitestlib.go
  api4/plugin.go
  api4/plugin_test.go
  app/download.go
  app/helper_test.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_test.go
  build/release.mk
  go.mod
  go.sum
  i18n/en.json
  model/config.go
  model/marketplace_plugin.go
  plugin/environment.go
  tests/testplugin.tar.gz
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testplugin2.tar.gz
  tests/testplugin2.tar.gz.sig
  tests/testpluginv2.tar.gz
  tests/testpluginv2.tar.gz.sig
  vendor/github.com/h2non/go-is-svg/.editorconfig
  vendor/github.com/h2non/go-is-svg/.gitignore
  vendor/github.com/h2non/go-is-svg/.travis.yml
  vendor/github.com/h2non/go-is-svg/LICENSE
  vendor/github.com/h2non/go-is-svg/README.md
  vendor/github.com/h2non/go-is-svg/svg.go
  vendor/modules.txt
Labels: 3: Reviews Complete

#13627 MM-21481: Fixed several issues from user marshalling
  api4/user_test.go
  app/user.go
  app/web_conn.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 3: Reviews Complete, QA Review Done

#13517 MM-12773: Return error if ChannelMemberHistory record creation fails.
  app/channel.go
Labels: 3: Reviews Complete, QA Review Done

#13408 MM-19445 - Added version information to plugin diagnostics data
  app/diagnostics.go
  app/diagnostics_test.go
Labels: 1: PM Review, Tests/Not Needed

#13612 MM-21328: Fix KVCompareAndSet when new==old
  i18n/en.json
  store/sqlstore/plugin_store.go
  store/storetest/plugin_store.go
Labels: QA Review Done

#13420 GH-12702 v2: Add new command response parameter: "skip_slack_parsing".
  app/command.go
  app/command_code.go
  app/command_test.go
  model/command_response.go
  model/command_response_test.go
Labels: 3: Reviews Complete, QA Review Done

#13595 Respect HomepageURL in manifest for local plugins
  api4/plugin_test.go
  app/plugin.go
  tests/README.md
  tests/testplugin.tar.gz
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testplugin2.tar.gz
  tests/testplugin2.tar.gz.sig
Labels: 3: Reviews Complete, QA Review Done

#13639 Cherry pick of #13627
  api4/user_test.go
  app/user.go
  app/web_conn.go
  model/websocket_client.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13634 MM-21725 change to singular
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#13609 Add IsValid method to *Manifest struct
  app/plugin_install.go
  model/manifest.go
  model/manifest_test.go
  model/plugin_valid.go
  model/plugin_valid_test.go
Labels: 3: Reviews Complete

#13638 MM-21645: COALESCE(Bots.LastIconUpdate, 0)
  store/sqlstore/bot_store.go
  store/sqlstore/bot_store_test.go
  store/storetest/bot_store.go
Labels: CherryPick/Approved, QA Review Done

#13608 Convert store/storetest/post_store.go t.Fatal to assert/require
  store/storetest/post_store.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13613 golint fix
  .golangci.yml
  app/helper_test.go
  app/user_test.go
  cmd/mattermost/commands/cmdtestlib.go
  cmd/mattermost/commands/config_test.go
  config/database_test.go
  config/main_test.go
  config/migrate_test.go
  config/store_test.go
  imports/placeholder.go
  manualtesting/manual_testing.go
  manualtesting/test_autolink.go
  migrations/helper_test.go
  testlib/doc.go
  testlib/helper.go
Labels: 3: Reviews Complete, QA Review Done

#13432 MM-21157: Triggers role sync when a syncable is linked, unlinked, or updated.
  api4/group.go
  app/channel.go
  app/group.go
  app/syncables.go
  app/syncables_test.go
  app/team.go
  i18n/en.json
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/GroupStore.go
  store/timer_layer.go
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting PR, QA Review Done

#13640 MM-20345: Fixing etag problem not reloading all users when needed
  api4/user.go
  api4/user_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13633 MM-21374 - Fixed extracting icon for prepackaged and local plugins
  api4/plugin_test.go
  app/plugin.go
  tests/testplugin.tar.gz
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testplugin2.tar.gz
  tests/testplugin2.tar.gz.asc
  tests/testplugin2.tar.gz.sig
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13302 GH-10438 - Rewrite existing plugin API tests to exclusively test via actual plugin
  .circleci/config.yml
  app/plugin_api_test.go
  app/plugin_api_tests/basic_config.go
  app/plugin_api_tests/manual.test_load_configuration_defaults_plugin/main.go
  app/plugin_api_tests/manual.test_load_configuration_plugin/main.go
  app/plugin_api_tests/test_bots_plugin/main.go
  app/plugin_api_tests/test_call_log_api_plugin/main.go
  app/plugin_api_tests/test_get_bundle_path_plugin/main.go
  app/plugin_api_tests/test_get_channels_for_team_for_user_plugin/main.go
  app/plugin_api_tests/test_get_direct_channel_plugin/main.go
  app/plugin_api_tests/test_get_profile_image_plugin/main.go
  app/plugin_api_tests/test_member_channels_plugin/main.go
  app/plugin_api_tests/test_members_plugin/main.go
  app/plugin_api_tests/test_search_channels_plugin/main.go
  app/plugin_api_tests/test_search_posts_in_team_plugin/main.go
  app/plugin_api_tests/test_search_teams_plugin/main.go
  app/plugin_api_tests/test_send_mail_plugin/main.go
  app/plugin_api_tests/test_set_profile_image_plugin/main.go
  app/plugin_api_tests/test_update_user_active_plugin/main.go
  app/plugin_api_tests/test_update_user_status_plugin/main.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13628 Bump GolangCI-Lint to v1.23.0
  .circleci/config.yml
  .golangci.yml
  build/Jenkinsfile.pr
Labels: 3: Reviews Complete

#13661 Disable unused linter
  .golangci.yml
Labels: 3: Reviews Complete, Tests/Not Needed

#13450 Remove more instances of GOPATH from Makefile and CI
  .circleci/config.yml
  .gitignore
  Makefile
  build/Jenkinsfile.pr
  build/release.mk
  scripts/test.sh
Labels: 3: Reviews Complete, AutoMerge

#13637 [MM-21373] Don't send verification
  app/email.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13564 MM-21071
  api4/system.go
  model/client4.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13658 translations PR 20200120
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Area/Localization, AutoMerge

#13651 Bump app version to 5.22
  model/version.go
Labels: 2: Dev Review, QA Review Done

#13643 Ignore guest accounts flag
  api4/role.go
  api4/team.go
  api4/user.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#13669 Automated cherry pick of #13643
  api4/role.go
  api4/team.go
  api4/user.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13674 Cherry pick of #13637
  app/email.go
Labels: Changelog/Not Needed, Docs/Not Needed

#13668 MM-21071
  api4/system.go
  model/client4.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13671 Allow GOBIN to be overriden with environment variables
  Makefile
Labels: 3: Reviews Complete, Tests/Not Needed

#13684 Set the GOBIN to install go-junit-report in the correct location
  .circleci/config.yml
Labels: 3: Reviews Complete, Tests/Not Needed

#13631 Use always strings for cache keys
  api4/openGraph.go
  app/post_metadata.go
  app/status.go
  services/cache/cache.go
  services/cache/lru/lru.go
  services/cache/lru/lru_test.go
  store/localcachelayer/user_layer.go
Labels: 3: Reviews Complete

#13629 MM-21769 - Validate plugin bundle and signature files when packaging MM
  Makefile
  build/plugin-production-public-key.gpg
  build/release.mk
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13662 Remove imports from golint blacklist
  .golangci.yml
Labels: 3: Reviews Complete, Tests/Not Needed

#13685 Manual cherry pick of #13629
  Makefile
  build/plugin-production-public-key.gpg
  build/release.mk
Labels: AutoMerge

#13738 Add mm server bin directory
  .gitignore
  bin/.gitignore
Labels: 3: Reviews Complete

#13350 [MM-18121] Fix config set panic
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13663 Modifies the interface to add search index metrics and initialises metrics first so it can be used from elasticsearch
  app/enterprise.go
  einterfaces/metrics.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13614 [MM-20804] Add "Unarchive Channel" option to the channel info screen - Additional fixes
  app/channel.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#13683 User Management > User role change not reflected in the UI without a refresh
  api4/user_test.go
  app/user.go
Labels: 3: Reviews Complete, CherryPick/Approved

#13745 Automated cherry pick of #13683
  api4/user_test.go
  app/user.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13610 MM-21019 - Fix race in (*Environment).SetPluginState()
  plugin/environment.go
  plugin/health_check.go
  plugin/supervisor.go
Labels: 3: Reviews Complete

#13746 Compare config without environment variables to send config updates to the cluster
  app/config.go
Labels: 3: Reviews Complete

#13598 MM-19250 - new endpoint to retrieve command by id
  api4/command.go
  api4/command_test.go
  model/client4.go
  web/context.go
Labels: 3: Reviews Complete, QA Review Done

#13604 MM-20865 - Demo Plugin: Enabling and disabling demo plugin generates "connection is shutdown" error
  app/plugin_hooks_test.go
  plugin/environment.go
  plugin/supervisor.go
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#13752 export GOBIN
  Makefile
Labels: 3: Reviews Complete, Tests/Not Needed

#13744 Automated cherry pick of #13350
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13636 [MM-21572] Disable InstallFromUrl if EnableUploads is false
  api4/plugin.go
  api4/plugin_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13764 Automated cherry pick of #13636
  api4/plugin.go
  api4/plugin_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13754 Fix GetMembers store methods order, which wasn't working properly in postgres
  store/sqlstore/team_store.go
  store/storetest/team_store.go
Labels: 3: Reviews Complete, QA Review Done

#13675 MM-21915: improve tar gz path traversal
  app/extract_plugin_tar.go
  app/extract_plugin_tar_test.go
  app/plugin_install.go
  utils/extract.go
  utils/path.go
  utils/path_test.go
Labels: AutoMerge, CherryPick/Approved, QA Review Done

#13747 [MM-21946] [MM-21945] Ensure deleted groups are not returned from the groups API
  store/sqlstore/group_store.go
  store/storetest/group_store.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13765 .gitignore prepackaged_plugins and report.xml
  .gitignore
Labels: 2: Dev Review, Tests/Not Needed

#13768 Automated cherry pick of #13747
  store/sqlstore/group_store.go
  store/storetest/group_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13767 Automated cherry pick of #13675
  app/extract_plugin_tar.go
  app/extract_plugin_tar_test.go
  app/plugin_install.go
  utils/extract.go
  utils/path.go
  utils/path_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13679 MM-21922: Add metrics for http verb
  einterfaces/metrics.go
  web/handlers.go
Labels: 3: Reviews Complete, QA Review Done

#13759 Making private opengraph methods in the app layer
  app/opengraph.go
  app/post_metadata.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13758 Making private import methos in the app layer
  app/import.go
  app/import_functions.go
  app/import_functions_test.go
  app/import_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13760 Making private app/cluster_handlers.go methods
  app/cluster_handlers.go
  app/server.go
Labels: 3: Reviews Complete, Tests/Not Needed

#13677 Allow plugins to specify a ReleaseNotesURL via manifest
  api4/plugin_test.go
  app/plugin.go
  model/manifest.go
  model/manifest_test.go
  tests/README.md
  tests/testplugin.tar.gz
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
  tests/testplugin2.tar.gz
  tests/testplugin2.tar.gz.asc
  tests/testplugin2.tar.gz.sig
Labels: 3: Reviews Complete, QA Review Done

#13785 Add 5.20 method to release branches for adding GOBIN.
  build/Jenkinsfile.branch
Labels: 2: Dev Review, AutoMerge

#13751 Avoid panic when push messages are empty or nil
  api4/system.go
  api4/system_test.go
  app/notification_push.go
  app/notification_push_test.go
  i18n/en.json
  model/push_notification.go
  model/push_notification_test.go
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#13789 Automated cherry pick of #13751
  api4/system.go
  api4/system_test.go
  app/notification_push.go
  app/notification_push_test.go
  i18n/en.json
  model/push_notification.go
  model/push_notification_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13779 MM-20977 - Inviting multiple users with valid/allowed and invalid emails causes the invites for the valid users not to be sent (new pr)
  api4/team.go
  api4/team_test.go
  app/team.go
  model/client4.go
  model/team_member.go
Labels: 3: Reviews Complete, QA Review Done

#13682 [MM-21573] Certificate Uploads only via CLI
  api4/config.go
  api4/config_test.go
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#13624 MM-21727 add an endpoint to move a command to another team
  api4/command.go
  api4/command_test.go
  model/client4.go
  model/command_request.go
Labels: 3: Reviews Complete, QA Review Done

#13748 plugin/helpers: fix an unchecked issue when comparing two configs
  plugin/helpers_config.go
  plugin/helpers_config_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#13793 Automated cherry pick of #13748
  plugin/helpers_config.go
  plugin/helpers_config_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13791 Automated cherry pick of #13682
  api4/config.go
  api4/config_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13776 MM-22067: Check guest email allowance separately
  app/team.go
  app/team_test.go
  app/user_test.go
Labels: CherryPick/Approved, QA Review Done

#13796 Automated cherry pick of #13776
  app/team.go
  app/team_test.go
  app/user_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#13792 Removing unused param and unneeded query
  store/sqlstore/channel_store.go
Labels: 3: Reviews Complete, QA Review Done

#13773 Ignore empty fields, change method name
  model/manifest.go
  model/manifest_test.go
Labels: 3: Reviews Complete

#13769 delete kv on setting nil
  app/plugin_test.go
  store/sqlstore/plugin_store.go
Labels: QA Review Done

#13800 Add documentation for number field for plugins
  model/manifest.go
  model/manifest_test.go
Labels: 3: Reviews Complete, Demo Plugin Changes/Needed
