Repository mattermost/mattermost, pull requests merged in 2021-08, with the labels that each got.

#18039 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17943 MM-36127 Check for emojis in message attachment titles
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note

#18041 Print a helpful message for JSON column update failures.
  store/sqlstore/store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18011 [MM-37202] Use native upsert query in StatusStore.SaveOrUpdate()
  store/sqlstore/status_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18037 MM-36990: Use upsert for system key update
  app/permissions_migrations.go
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: 4: Reviews Complete, release-note-none

#17463 [MM-33255] Add migrations for OAuthAuthData schema
  db/migrations/bindata.go
  db/migrations/mysql/000033_create_oauthauthdata.down.sql
  db/migrations/mysql/000033_create_oauthauthdata.up.sql
  db/migrations/postgres/000033_create_oauthauthdata.down.sql
  db/migrations/postgres/000033_create_oauthauthdata.up.sql
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, AutoMerge, release-note

#17459 [MM-33270] Add migrations for SharedChannels and SharedChannelAttachment schemas
  db/migrations/bindata.go
  db/migrations/mysql/000032_create_sharedchannels.down.sql
  db/migrations/mysql/000032_create_sharedchannels.up.sql
  db/migrations/mysql/000033_create_sidebar_channels.down.sql
  db/migrations/mysql/000033_create_sidebar_channels.up.sql
  db/migrations/mysql/000034_create_oauthauthdata.down.sql
  db/migrations/mysql/000034_create_oauthauthdata.up.sql
  db/migrations/mysql/000035_create_sharedchannelattachments.down.sql
  db/migrations/mysql/000035_create_sharedchannelattachments.up.sql
  db/migrations/postgres/000032_create_sharedchannels.down.sql
  db/migrations/postgres/000032_create_sharedchannels.up.sql
  db/migrations/postgres/000033_create_sidebar_channels.down.sql
  db/migrations/postgres/000033_create_sidebar_channels.up.sql
  db/migrations/postgres/000034_create_oauthauthdata.down.sql
  db/migrations/postgres/000034_create_oauthauthdata.up.sql
  db/migrations/postgres/000035_create_sharedchannelattachments.down.sql
  db/migrations/postgres/000035_create_sharedchannelattachments.up.sql
Labels: 4: Reviews Complete, AutoMerge, release-note

#17458 [MM-33271] Add migrations for SharedChannelUsers schema
  db/migrations/bindata.go
  db/migrations/mysql/000036_create_sharedchannelusers.down.sql
  db/migrations/mysql/000036_create_sharedchannelusers.up.sql
  db/migrations/postgres/000036_create_sharedchannelusers.down.sql
  db/migrations/postgres/000036_create_sharedchannelusers.up.sql
  store/sqlstore/shared_channel_store.go
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17457 [MM-33269] Add migrations for SharedChannelRemotes
  db/migrations/bindata.go
  db/migrations/mysql/000037_create_sharedchannelremotes.down.sql
  db/migrations/mysql/000037_create_sharedchannelremotes.up.sql
  db/migrations/postgres/000037_create_sharedchannelremotes.down.sql
  db/migrations/postgres/000037_create_sharedchannelremotes.up.sql
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#18042 Remove deprecated *model.Client methods
  api4/system_test.go
  api4/user_test.go
  model/client4.go
Labels: 4: Reviews Complete, release-note

#17039 [MM-33072] Add migrations for jobs schema
  db/migrations/bindata.go
  db/migrations/mysql/000038_create_jobs.down.sql
  db/migrations/mysql/000038_create_jobs.up.sql
  db/migrations/postgres/000038_create_jobs.down.sql
  db/migrations/postgres/000038_create_jobs.up.sql
  store/sqlstore/job_store.go
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17884 [M-36899] Remove deprecated SourcePluginId
  app/plugin_requests.go
  plugin/context.go
Labels: 4: Reviews Complete, release-note

#17005 [MM-33059] Add migrations for ChannelMemberHistory
  db/migrations/bindata.go
  db/migrations/mysql/000039_create_channel_member_history.down.sql
  db/migrations/mysql/000039_create_channel_member_history.up.sql
  db/migrations/postgres/000039_create_channel_member_history.down.sql
  db/migrations/postgres/000039_create_channel_member_history.up.sql
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17302 [MM-33272] db/migrations: add migration scripts for sidebar categories
  db/migrations/bindata.go
  db/migrations/mysql/0000340create_sidebar_categories.up.sql
  db/migrations/mysql/000040_create_sidebar_categories.down.sql
  db/migrations/postgres/000040_create_sidebar_categories.down.sql
  db/migrations/postgres/000040_create_sidebar_categories.up.sql
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, release-note-none

#17165 Move upload sessions over to new schema migrations
  db/migrations/bindata.go
  db/migrations/mysql/000040create_sidebar_categories.up.sql
  db/migrations/mysql/000041_create_upload_sessions.down.sql
  db/migrations/mysql/000041_create_upload_sessions.up.sql
  db/migrations/postgres/000041_create_upload_sessions.down.sql
  db/migrations/postgres/000041_create_upload_sessions.up.sql
  go.mod
  go.sum
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upload_session_store.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_go115.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_pre_go115.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/golang.org/x/sys/unix/README.md
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note

#18045 [MM-28985] Remove pointers to slice (part 2)
  api4/channel_test.go
  api4/post_test.go
  api4/preference_test.go
  app/status.go
  model/client4.go
  model/custom_status.go
Labels: 4: Reviews Complete, release-note-none

#18053 MM-35754: Fail fast if templates directory is not found
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#18052 MM-37573: Ignore nil fields in attachments
  app/post_metadata.go
  app/slack.go
  model/post.go
  model/post_test.go
  model/slack_attachment.go
Labels: 4: Reviews Complete, release-note-none

#18056 Bump to 5.31.10
  model/version.go
Labels: release-note-none

#18058 Update latest version to 5.37.1
  build/Dockerfile
Labels: release-note-none

#18059 Update version to 5.35.6
  model/version.go
Labels: AutoMerge, release-note-none

#18060 Update version to 5.36.3
  model/version.go
Labels: AutoMerge, release-note-none

#17137 Move threads over to new schema migrations
  db/migrations/bindata.go
  db/migrations/mysql/000042_create_threads.down.sql
  db/migrations/mysql/000042_create_threads.up.sql
  db/migrations/mysql/000043_thread_memberships.down.sql
  db/migrations/mysql/000043_thread_memberships.up.sql
  db/migrations/postgres/000042_create_threads.down.sql
  db/migrations/postgres/000042_create_threads.up.sql
  db/migrations/postgres/000043_thread_memberships.down.sql
  db/migrations/postgres/000043_thread_memberships.up.sql
  store/sqlstore/store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
Labels: AutoMerge, release-note

#17883 [MM-27593] s/AllExecutables/Executables/
  model/manifest.go
  model/manifest_test.go
Labels: 4: Reviews Complete, release-note

#18057 MM-37575: Handle nil value in override_username
  app/notification.go
  app/notification_test.go
Labels: 4: Reviews Complete, release-note-none

#18066 MM-37576: Fix reference to incorrect error variable
  app/user.go
  app/user_test.go
Labels: 4: Reviews Complete, release-note-none

#18051 MM-37579: Fix typo in map property
  app/email/email.go
  app/email/email_test.go
Labels: 4: Reviews Complete, release-note-none

#17971 Add Focalboard to known plugin telemetry
  services/telemetry/telemetry.go
Labels: release-note-none

#18073 Automated cherry pick of #17971
  services/telemetry/telemetry.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18075 Log error from a compliance job failure
  app/compliance.go
Labels: 4: Reviews Complete, release-note-none

#18069 Remove deprecated model.ComparePassword method
  model/user.go
  model/user_test.go
Labels: 4: Reviews Complete, release-note

#17870 [MM-2307] Move plugin helpers from mattermost-server repository into mattermost-plugin-api
  Makefile
  model/manifest.go
  plugin/checker/check_helpers.go
  plugin/checker/check_helpers_test.go
  plugin/checker/main.go
  plugin/client.go
  plugin/client_rpc.go
  plugin/driver.go
  plugin/helpers.go
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
  plugin/helpers_config.go
  plugin/helpers_config_test.go
  plugin/helpers_kv.go
  plugin/helpers_kv_test.go
  plugin/helpers_plugin.go
  plugin/helpers_plugin_test.go
  plugin/plugintest/example_hello_user_test.go
  plugin/plugintest/helpers.go
Labels: 4: Reviews Complete, release-note

#18068 [MM-37578] - Add setting for onboarding
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
  tests/test-config.json
Labels: 2: Dev Review, release-note

#18077 MM-37491: Fix flaky test on file content extraction
  app/file.go
  app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note-none

#18054 [MM-37496] Temporarily disable admin advisor notifications
  app/app.go
  app/app_iface.go
  app/bot.go
  app/server.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#18090 Automated cherry pick of #18011
  store/sqlstore/status_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18071 Prepackage board version to 0.8.2
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18092 Automated cherry pick of #18071
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#17796 MM-22845: Added support for permalink previews.
  api4/channel.go
  api4/post.go
  app/admin.go
  app/app_iface.go
  app/authorization.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/post_test.go
  app/ratelimit.go
  app/role_test.go
  app/shared_channel.go
  app/syncables_test.go
  app/user_test.go
  app/web_conn.go
  config/client.go
  model/config.go
  model/feature_flags.go
  model/message_export.go
  model/permalink.go
  model/post.go
  model/post_embed.go
  model/post_list.go
  services/telemetry/telemetry.go
  templates/globalrelay_compliance_export_message.html
  tests/test-config.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#18082 Pre-package Incident Collaboration v1.16.0
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#18095 Automated cherry pick of #18082
  Makefile
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18096 Automated cherry pick of #18082
  Makefile
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note

#17070 Move user terms of service tables over to new schema migrations
  db/migrations/bindata.go
  db/migrations/mysql/000044_create_user_terms_of_service.down.sql
  db/migrations/mysql/000044_create_user_terms_of_service.up.sql
  db/migrations/postgres/000044_create_user_terms_of_service.down.sql
  db/migrations/postgres/000044_create_user_terms_of_service.up.sql
  go.mod
  go.sum
  store/sqlstore/upgrade.go
  vendor/modules.txt
Labels: Lifecycle/1:stale, release-note

#17190 Fix for when the 'migrate' command drops the custom default language.…
  cmd/mattermost/commands/config.go
Labels: 4: Reviews Complete, release-note-none

#17041 [MM-33257] Add migrations for PluginKeyValueStore schema
  db/migrations/bindata.go
  db/migrations/mysql/000045_create_plugin_key_value_store.down.sql
  db/migrations/mysql/000045_create_plugin_key_value_store.up.sql
  db/migrations/postgres/000045_create_plugin_key_value_store.down.sql
  db/migrations/postgres/000045_create_plugin_key_value_store.up.sql
  store/sqlstore/plugin_store.go
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#18044 MM-37165: Fix improper plugin shutdown
  plugin/client_rpc.go
  plugin/supervisor.go
Labels: 4: Reviews Complete, release-note-none

#18033 [GH-18004] Fix staticcheck errors from _test.go files
  .golangci.yml
  api4/bot_test.go
  api4/channel_test.go
  api4/config_test.go
  api4/emoji_test.go
  api4/file_test.go
  api4/group_test.go
  api4/post_test.go
  api4/team_test.go
  api4/user_test.go
  api4/webhook_test.go
  app/slashcommands/command_test.go
  jobs/schedulers_test.go
  model/bot_test.go
  model/config_test.go
  services/searchengine/bleveengine/bleve_test.go
  services/slackimport/main_test.go
  store/sqlstore/upgrade_test.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/group_store.go
  store/storetest/plugin_store.go
  store/storetest/post_store.go
  store/storetest/remote_cluster_store.go
  store/storetest/session_store.go
  store/storetest/shared_channel_store.go
  store/storetest/user_access_token_store.go
  store/storetest/webhook_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18079 Fix possible endless loop
  app/app.go
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#18091 Automated cherry pick of #18011
  store/sqlstore/status_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18098 Translations update from Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#18104 Automated cherry pick of #18071
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#18100 Skip racy TestPreparePostForClient
  app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note-none

#18107 update mm server builder to use go 1.16.7
  .circleci/config.yml
  .gitlab-ci.yml
  build/README.md
  build/local-test-env.sh
Labels: 2: Dev Review, release-note-none

#18110 Automated cherry pick of #17933
  api4/license.go
  api4/license_test.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18111 Automated cherry pick of #18053
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18008 [MM-36318] Set bot profile image and icon only if they have changed
  api4/user_test.go
  app/bot.go
  app/plugin_api.go
  app/user.go
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18067 Remove remnants of config watcher
  config/logging.go
  config/watcher.go
  config/watcher_test.go
Labels: 3: QA Review, release-note

#18087 [MM-37716] Drop support for LHS specific bot icons
  api4/bot.go
  api4/bot_test.go
  app/app_iface.go
  app/bot.go
  app/bot_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  i18n/en.json
  model/client4.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 4: Reviews Complete, release-note

#18076 [MM-37616] Self-managed: Update email template to new branding - Welcome and Verification email
  templates/partials/logo.mjml
  templates/partials/style.mjml
  templates/partials/verify.mjml
  templates/verify_body.html
  templates/welcome_body.html
Labels: 2: Dev Review, release-note-none

#18072 [MM-37306] Replace db count query in user signup process
  app/import_functions.go
  app/user.go
  i18n/en.json
  services/users/errors.go
  services/users/users.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#18103 [MM-37755] Idiomatic naming (SMTP, TLS, TCP, XML, CSS, HTML, HTTP)
  api4/apitestlib.go
  api4/file_test.go
  api4/image_test.go
  api4/upload_test.go
  api4/user.go
  api4/user_test.go
  app/app.go
  app/download.go
  app/opengraph.go
  app/opengraph_test.go
  app/permissions_migrations.go
  app/plugin.go
  app/plugin_requests.go
  app/post_metadata_test.go
  app/post_test.go
  app/server.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/utils_test.go
  config/utils.go
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  model/access.go
  model/authorize.go
  model/client4.go
  model/command.go
  model/config.go
  model/config_test.go
  model/manifest.go
  model/oauth.go
  model/outgoing_webhook.go
  model/permission.go
  model/role.go
  model/utils.go
  model/utils_test.go
  services/telemetry/mocks/ServerIface.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  shared/mlog/levels.go
  shared/mlog/logr.go
  shared/mlog/tcp.go
  shared/mlog/tcp_test.go
  tests/test-config.json
  utils/subpath_test.go
  web/handlers.go
  web/handlers_test.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note-none

#18093 Using native JSON operations to add thread participants
  store/sqlstore/adapters.go
  store/sqlstore/adapters_test.go
  store/sqlstore/store.go
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17941 [MM-10166] Add MaxImageResolution config setting
  api4/file_test.go
  app/brand.go
  app/file.go
  app/image.go
  app/team.go
  app/upload.go
  app/user.go
  model/config.go
  model/utils.go
  services/telemetry/telemetry.go
  tests/test-config.json
Labels: 4: Reviews Complete, Docs/Needed, release-note

#18101 [MM-37557] Move error out of client4 response
  api4/apitestlib.go
  api4/bleve_test.go
  api4/bot_test.go
  api4/brand_test.go
  api4/channel_category_test.go
  api4/channel_test.go
  api4/cluster_test.go
  api4/command_help_test.go
  api4/command_test.go
  api4/commands_test.go
  api4/config_test.go
  api4/data_retention_test.go
  api4/elasticsearch_test.go
  api4/emoji_test.go
  api4/export_test.go
  api4/file_test.go
  api4/group_test.go
  api4/import_test.go
  api4/integration_action_test.go
  api4/job_test.go
  api4/ldap_test.go
  api4/license_test.go
  api4/oauth_test.go
  api4/openGraph_test.go
  api4/permissions_test.go
  api4/plugin_test.go
  api4/post_test.go
  api4/preference_test.go
  api4/reaction_test.go
  api4/role_test.go
  api4/saml_test.go
  api4/scheme_test.go
  api4/shared_channel_test.go
  api4/status_test.go
  api4/system_test.go
  api4/team_test.go
  api4/terms_of_service_test.go
  api4/upload_test.go
  api4/user_test.go
  api4/user_viewmembers_test.go
  api4/webhook_test.go
  api4/websocket_norace_test.go
  api4/websocket_test.go
  app/plugin_api_test.go
  app/slashcommands/auto_environment.go
  app/slashcommands/auto_teams.go
  app/slashcommands/auto_users.go
  app/slashcommands/command_loadtest.go
  cmd/mattermost/commands/channel_test.go
  cmd/mattermost/commands/command_test.go
  cmd/mattermost/commands/team_test.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/webhook_test.go
  manualtesting/manual_testing.go
  manualtesting/test_autolink.go
  model/client4.go
  model/client4_test.go
  model/websocket_client.go
  model/websocket_client_test.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note

#18102 [MM-37760] Reduce export surface of client4
  api4/bot_test.go
  api4/config_test.go
  api4/file_test.go
  api4/system_test.go
  api4/team_test.go
  model/client4.go
  model/client4_test.go
Labels: 4: Reviews Complete, release-note

#18113 MM-36084 - Certificate Auth: Remove SAML dependency in license check
  api4/user.go
  api4/user_test.go
  config/client.go
Labels: 3: QA Review, release-note-none

#18119 MM-37378: Unskip TestPanicLog
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#18120 Update Session Props to use one query
  store/sqlstore/session_store.go
  store/storetest/session_store.go
Labels: 4: Reviews Complete, release-note-none

#18123 Improve session cleanup
  app/server.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/SessionStore.go
  store/storetest/session_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#18125 Skip flaky TestTrialLicense
  api4/license_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18064 [MM-37664] Remove deprecated Backend field from plugin manifest
  app/integration_action_test.go
  app/plugin_api_test.go
  app/plugin_hooks_test.go
  app/post_test.go
  model/manifest.go
  model/manifest_test.go
  plugin/health_check_test.go
  plugin/supervisor_test.go
Labels: 4: Reviews Complete, release-note

#18139 [MM-37898] Exclude bots from initial user store emptiness check
  services/users/users.go
  services/users/users_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#18143 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#18116 [MM-22051] Remove To/From JSON (Channels)
  api4/channel.go
  api4/channel_category.go
  api4/data_retention.go
  app/channel.go
  app/user.go
  model/channel.go
  model/channel_list.go
  model/channel_member.go
  model/channel_search.go
  model/channel_sidebar.go
  model/channel_stats.go
  model/channel_view.go
  model/client4.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#18121 [MM-22051] Remove To/From JSON (Users)
  api4/bot.go
  api4/user.go
  api4/user_local.go
  model/client4.go
  model/client4_test.go
  model/user.go
  model/user_access_token.go
  model/user_access_token_search.go
  model/user_access_token_search_test.go
  model/user_access_token_test.go
  model/user_autocomplete.go
  model/user_search.go
  model/user_search_test.go
  model/user_terms_of_service.go
  model/user_terms_of_service_test.go
  model/user_test.go
  model/users_stats.go
  model/websocket_message.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note-none

#18127 [MM-22051] Remove To/From JSON (Team)
  api4/data_retention.go
  api4/scheme.go
  api4/team.go
  api4/team_local.go
  api4/team_test.go
  app/team.go
  model/client4.go
  model/team.go
  model/team_member.go
  model/team_member_test.go
  model/team_search.go
  model/team_search_test.go
  model/team_stats.go
  model/team_test.go
  store/storetest/team_store.go
Labels: 4: Reviews Complete, release-note-none

#18137 Switch to mysql/mysql-server docker image for ARM64 support.
  build/docker-compose.common.yml
Labels: release-note-none

#18144 Update version to 5.38.1
  model/version.go
Labels: release-note-none

#18122 Use DB native JSON operations for Delete post
  store/sqlstore/adapters.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#18136 [MM-37726] - Self-managed: Update email template to new branding - Invitation email
  templates/invite_body.html
  templates/invite_body.mjml
  templates/partials/style.mjml
Labels: 2: Dev Review, release-note-none

#18015 [MM-18391] Removing convert channel endpoint
  api4/channel.go
  api4/channel_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, release-note

#18130 [MM-22051] Remove To/From JSON (Status, Bot, Reaction, Thread, FileInfo)
  api4/file_test.go
  api4/post.go
  api4/reaction.go
  api4/status.go
  api4/upload_test.go
  api4/user.go
  api4/user_test.go
  app/channel.go
  app/cluster_handlers.go
  app/notification.go
  app/reaction.go
  app/status.go
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  model/bot.go
  model/client4.go
  model/file.go
  model/file_info.go
  model/reaction.go
  model/status.go
  model/status_test.go
  model/thread.go
Labels: 4: Reviews Complete, release-note-none

#17923 [MM-29217] Remove Posts.ParentId
  api4/command.go
  api4/post_test.go
  app/auto_responder_test.go
  app/command.go
  app/command_autocomplete.go
  app/import_functions.go
  app/notification.go
  app/post.go
  app/post_test.go
  app/slashcommands/auto_posts.go
  app/slashcommands/command_echo.go
  app/slashcommands/command_loadtest.go
  app/slashcommands/command_test.go
  app/webhook.go
  i18n/en.json
  model/command_webhook.go
  model/command_webhook_test.go
  model/compliance_post.go
  model/post.go
  model/post_test.go
  services/cache/lru_test.go
  services/slackimport/slackimport.go
  store/searchtest/helper.go
  store/sqlstore/command_webhook_store.go
  store/sqlstore/compliance_store.go
  store/sqlstore/integrity.go
  store/sqlstore/integrity_test.go
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
  store/storetest/channel_store.go
  store/storetest/file_info_store.go
  store/storetest/post_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, release-note

#18097 Modified updateUserNotifyProps to directly update the field
  app/app_iface.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  app/user.go
  services/users/users.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#18131 [MM-37846] Fix payload for post deleted event
  api4/post_test.go
  app/post.go
Labels: 4: Reviews Complete, release-note-none

#18196 Replaced all instances of "zz" + model.NewId() with NewTestId()(#18194)
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18197 [GH-18192] Replace all instances of "zz" + model.NewId() in storetest/group_store.go with NewTestId
  store/storetest/group_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18201 Fix bad merge causing CI to fail
  api4/post_test.go
Labels: AutoMerge, release-note-none

#18198 Automated cherry pick of #18131
  api4/post_test.go
  app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18189 MM-38004 fix racy unit test
  shared/mlog/mlog.go
Labels: 4: Reviews Complete, release-note-none

#18155 Prepackage Playbooks v1.16.1
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18134 [MM-37727] - Self-managed: Update email template to new branding - Mention
  app/notification_email.go
  templates/messages_notification.html
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#18145 Change inbucket default port from 10080 to 9001
  build/docker-compose-generator/main.go
  build/docker-compose.common.yml
  build/docker-compose.yml
  build/dotenv/test.env
  build/gitlab-dc.common.yml
  build/gitlab-dc.mysql.yml
  build/gitlab-dc.postgres.yml
  docker-compose.makefile.yml
  docker-compose.yaml
  shared/mail/inbucket.go
Labels: 4: Reviews Complete, release-note-none

#17948 [MM-27312] Allow uploading 10 files per post
  i18n/en.json
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#18203 Automated cherry pick of #18155
  Makefile
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#18202 Automated cherry pick of #18155
  Makefile
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#18204 Automated cherry pick of #18189
  shared/mlog/mlog.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick

#18206 MM-27312 cherrypick to Cloud
  i18n/en.json
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#18117 [MM-36445] Changing elastic search docker version
  build/docker-compose.common.yml
  build/gitlab-dc.common.yml
Labels: 4: Reviews Complete, release-note

#18200 [MM-37726] - Self-managed: Update email template to new branding - Invitation email
  templates/invite_body.html
  templates/invite_body.mjml
  templates/messages_notification.html
  templates/partials/style.mjml
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: 2: Dev Review, release-note-none

#18207 MM-38016 Fix racy unit test (TestService_AddTopicListener)
  services/remotecluster/mocks_test.go
  services/remotecluster/ping_test.go
  services/remotecluster/send_test.go
  services/remotecluster/sendprofileImage_test.go
  services/remotecluster/service_test.go
  shared/mlog/tlog.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note-none

#18211 Automated cherry pick of #18207
  services/remotecluster/mocks_test.go
  services/remotecluster/ping_test.go
  services/remotecluster/send_test.go
  services/remotecluster/sendprofileImage_test.go
  services/remotecluster/service_test.go
  shared/mlog/tlog.go
  web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#17995 MM-36448: Removes legacy CLI commands.
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/channel_test.go
  cmd/mattermost/commands/channelargs.go
  cmd/mattermost/commands/command.go
  cmd/mattermost/commands/command_test.go
  cmd/mattermost/commands/commandargs.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_flag_test.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/extract_content.go
  cmd/mattermost/commands/group.go
  cmd/mattermost/commands/group_test.go
  cmd/mattermost/commands/import.go
  cmd/mattermost/commands/integrity.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/ldap.go
  cmd/mattermost/commands/license.go
  cmd/mattermost/commands/main_test.go
  cmd/mattermost/commands/permissions.go
  cmd/mattermost/commands/permissions_test.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/reset.go
  cmd/mattermost/commands/roles.go
  cmd/mattermost/commands/roles_test.go
  cmd/mattermost/commands/sampledata.go
  cmd/mattermost/commands/sampledata_test.go
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
  cmd/mattermost/commands/teamargs.go
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/userargs.go
  cmd/mattermost/commands/utils.go
  cmd/mattermost/commands/utils_test.go
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
  i18n/en.json
  scripts/diff-config.sh
  scripts/jq-dep-check.sh
  scripts/ldap-check.sh
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
Labels: 4: Reviews Complete, release-note

#18209 Automated cherry pick of #18134
  app/notification_email.go
  templates/messages_notification.html
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#18152 [MM-23279] Idiomatic naming (IP)
  app/command_autocomplete.go
  app/context.go
  app/plugin_hooks_test.go
  app/plugin_requests.go
  app/ratelimit.go
  app/request/context.go
  config/environment_test.go
  einterfaces/mocks/AppContextInterface.go
  model/client4.go
  model/cluster_discovery.go
  model/cluster_discovery_test.go
  model/cluster_info.go
  model/cluster_info_test.go
  model/config.go
  model/utils.go
  model/utils_test.go
  plugin/context.go
  services/telemetry/telemetry.go
  tests/test-config.json
  web/context.go
  web/handlers.go
Labels: 4: Reviews Complete, release-note

#18220 [MM-38028] Bring back jobserver command
  cmd/mattermost/commands/jobserver.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18208 Update version to 5.38.2
  model/version.go
Labels: release-note-none

#18213 Automated cherry pick of #18076
  templates/partials/style.mjml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18218 Automated cherry pick of #18152
  app/command_autocomplete.go
  app/context.go
  app/plugin_hooks_test.go
  app/plugin_requests.go
  app/ratelimit.go
  app/request/context.go
  config/environment_test.go
  einterfaces/mocks/AppContextInterface.go
  model/client4.go
  model/cluster_discovery.go
  model/cluster_discovery_test.go
  model/cluster_info.go
  model/cluster_info_test.go
  model/config.go
  model/utils.go
  model/utils_test.go
  plugin/context.go
  services/telemetry/telemetry.go
  tests/test-config.json
  web/context.go
  web/handlers.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18215 Automated cherry pick of #18200
  templates/invite_body.html
  templates/invite_body.mjml
  templates/messages_notification.html
  templates/partials/style.mjml
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18146 [MM-37682] Expose SiteURL to non-authenticated sessions
  config/client.go
Labels: release-note-none

#18205 [GH-18195] Remove all instances of zz + model.NewId() in storetest/us…
  store/storetest/user_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18225 Automated cherry pick of #18088
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  i18n/en.json
  model/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18216 Automated cherry pick of #17995
  cmd/mattermost/commands/channel.go
  cmd/mattermost/commands/channel_test.go
  cmd/mattermost/commands/channelargs.go
  cmd/mattermost/commands/command.go
  cmd/mattermost/commands/command_test.go
  cmd/mattermost/commands/commandargs.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_flag_test.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/extract_content.go
  cmd/mattermost/commands/group.go
  cmd/mattermost/commands/group_test.go
  cmd/mattermost/commands/import.go
  cmd/mattermost/commands/integrity.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/ldap.go
  cmd/mattermost/commands/license.go
  cmd/mattermost/commands/main_test.go
  cmd/mattermost/commands/permissions.go
  cmd/mattermost/commands/permissions_test.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/reset.go
  cmd/mattermost/commands/roles.go
  cmd/mattermost/commands/roles_test.go
  cmd/mattermost/commands/sampledata.go
  cmd/mattermost/commands/sampledata_test.go
  cmd/mattermost/commands/team.go
  cmd/mattermost/commands/team_test.go
  cmd/mattermost/commands/teamargs.go
  cmd/mattermost/commands/user.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/userargs.go
  cmd/mattermost/commands/utils.go
  cmd/mattermost/commands/utils_test.go
  cmd/mattermost/commands/webhook.go
  cmd/mattermost/commands/webhook_test.go
  i18n/en.json
  scripts/diff-config.sh
  scripts/jq-dep-check.sh
  scripts/ldap-check.sh
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18222 [MM-37731] - Self-managed: Update email template to new branding - Invitation Guests
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_ended_email.html
  templates/cloud_upgrade_request_email.html
  templates/cloud_welcome_email.html
  templates/invite_body.html
  templates/license_up_for_renewal.html
  templates/messages_notification.html
  templates/over_user_limit_30_days_body.html
  templates/over_user_limit_7_days_body.html
  templates/over_user_limit_90_days_body.html
  templates/over_user_limit_workspace_suspended_body.html
  templates/partials/style.mjml
  templates/payment_failed_body.html
  templates/payment_failed_no_card_body.html
  templates/reached_user_limit_body.html
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: 2: Dev Review, 1: PM Review, release-note-none, Setup Cloud + CWS Test Server

#18228 Automated cherry pick of #18220
  cmd/mattermost/commands/jobserver.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18226 Fixes race condition in notification.go
  app/notification.go
Labels: kind/bug, release-note-none

#18230 Automated cherry pick of #18222
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_ended_email.html
  templates/cloud_upgrade_request_email.html
  templates/cloud_welcome_email.html
  templates/invite_body.html
  templates/license_up_for_renewal.html
  templates/messages_notification.html
  templates/over_user_limit_30_days_body.html
  templates/over_user_limit_7_days_body.html
  templates/over_user_limit_90_days_body.html
  templates/over_user_limit_workspace_suspended_body.html
  templates/partials/style.mjml
  templates/payment_failed_body.html
  templates/payment_failed_no_card_body.html
  templates/reached_user_limit_body.html
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18231 Automated cherry pick of #18226
  app/notification.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18210 Combine alterations on Posts table for 6.0 schema migration
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#18233 Fix racy test TestViewChannelCollapsedThreadsTurnedOff
  app/notification.go
Labels: 4: Reviews Complete, release-note-none

#18133 Prepare support for sqlx
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#18234 Combine alterations on Posts table (#18210) - cloud cherrypick
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#18135 [MM-37725] - Self-managed: Update email template to new branding - Password Reset
  templates/reset_body.html
Labels: 1: PM Review, CherryPick/Approved, QA Deferred, release-note-none, Setup Cloud + CWS Test Server

#18236 Automated cherry pick of #18135
  templates/reset_body.html
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18078 [MM-36387] Address db performance audit items
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/status_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18114 Update channel member notify props to use native JSON
  app/channel.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#18239 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#18243 Update latest version to 5.38.1
  build/Dockerfile
Labels: AutoMerge, release-note-none

#18229 Fix for test-data make target
  Makefile
  scripts/wait-for-system-start.sh
Labels: CherryPick/Approved, release-note-none

#18250 Automated cherry pick of #18229
  Makefile
  scripts/wait-for-system-start.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18248 MM-36387 cherry-pick to cloud
  store/sqlstore/channel_store.go
  store/sqlstore/post_store.go
  store/sqlstore/status_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#18255 update mattermost go builder to 20210810_golang-1.16.7 and fix gitlab image definition
  .circleci/config.yml
  .gitlab-ci.yml
  build/README.md
  build/local-test-env.sh
Labels: 4: Reviews Complete, release-note

#18251 Automated cherry pick of #18117
  build/docker-compose.common.yml
  build/gitlab-dc.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18217 Issue #18191 and #18193 fixed
  store/storetest/compliance_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18257 move users service to app directory
  app/authentication.go
  app/channel_test.go
  app/email/helper_test.go
  app/email/service.go
  app/import_functions.go
  app/oauth.go
  app/server.go
  app/server_test.go
  app/session.go
  app/team.go
  app/user.go
  app/user_test.go
  app/users/bot_default_image.go
  app/users/constants.go
  app/users/errors.go
  app/users/helper_test.go
  app/users/main_test.go
  app/users/password.go
  app/users/password_test.go
  app/users/profile_picture.go
  app/users/profile_picture_test.go
  app/users/service.go
  app/users/service_test.go
  app/users/session.go
  app/users/session_test.go
  app/users/users.go
  app/users/users_test.go
  app/users/utils.go
  app/web_hub_test.go
Labels: 4: Reviews Complete, release-note-none

#18151 Add plugin websocket hooks
  app/web_conn.go
  model/websocket_request.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18199 [GH-18190] Remove all instances of "zz" + model.NewId() in storetest/channel_sto…
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#18258 Automated cherry pick of #18151
  app/web_conn.go
  model/websocket_request.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#18247 Update MM version/sqlstore to version 6.0.0
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#18261 Update mmctl to v5.38.1
  scripts/download_mmctl_release.sh
Labels: release-note-none

#18031 [MM-37494] Check for license SKU when preparing marketplace requests
  app/plugin.go
  model/license.go
Labels: 1: PM Review, CherryPick/Approved, release-note

#18262 [MM-37494] Cherrypick #18031: Check for license SKU when preparing marketplace requests
  app/plugin.go
  model/license.go
Labels: release-note

#18256 update mattermost go builder to use go 1.16.7
  .circleci/config.yml
  .gitlab-ci.yml
  .gitlab-ci/test.yml
  build/local-test-env.sh
Labels: 4: Reviews Complete, release-note

#18259 [MM-36695] Fix flaky TestRequestTrialLicense test
  api4/license_test.go
  app/license.go
Labels: 4: Reviews Complete, release-note-none

#18253 MM-37787: ThreadAutoFollow must be true to enable CollapsedThreads
  i18n/en.json
  model/config.go
  model/config_test.go
Labels: 4: Reviews Complete, release-note

#18238 Added a sqlXPassThrough layer
  app/plugin_api_tests/test_db_driver/main.go
  store/sqlstore/sqlx_wrapper.go
  store/sqlstore/sqlx_wrapper_test.go
  store/sqlstore/store.go
Labels: 2: Dev Review, release-note-none

#18303 Translations update from Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#18296 Automated cherry pick of #18052
  app/post_metadata.go
  app/slack.go
  model/post.go
  model/post_test.go
  model/slack_attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18287 Automated cherry pick of #18146
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
