Repository mattermost/mattermost, pull requests merged in 2021-12, with the labels that each got.

#19112 Automated cherry pick of #19102 on release-6.2
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
Labels: 2: Dev Review, release-note-none

#19114 [MM-40395] - Text Changes in Congratulations email after trial signup
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, release-note-none

#19100 MM-40222 - show gov references in license page when gov license
  model/license.go
  utils/license.go
Labels: 2: Dev Review, release-note-none

#19109 Update version to 5.37.6
  model/version.go
Labels: release-note-none

#18885 MM-38674 - AB test for first guided channel creation
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#19119 [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-12-02
  api4/post.go
  api4/post_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/post.go
  app/post_metadata.go
  i18n/en.json
  i18n/pl.json
  jobs/resend_invitation_email/worker.go
  model/client4.go
  model/license.go
  model/version.go
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
  utils/license.go
  web/handlers.go
  web/handlers_test.go
Labels: 4: Reviews Complete, release-note-none

#19120 Automated cherry pick of #18885
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19104 Clarify comment on golang-migrate connection
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#19090 build: add mmctl to arm64 packages
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: 2: Dev Review, release-note

#19040 Remove reliable websockets configuration
  api4/websocket.go
  api4/websocket_test.go
  app/web_conn.go
  app/web_conn_test.go
  app/web_hub.go
  config/client.go
  model/config.go
Labels: 4: Reviews Complete, release-note

#19043 Updated Terms of Service to Terms of Use
  model/config.go
Labels: 4: Reviews Complete, release-note

#18917 Updated Account Settings to Settings
  i18n/en.json
Labels: release-note

#18795 MM-36862: removes participant from thread
  model/utils.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#19131 Automated cherry pick of #19129 on release-6.2
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
Labels: 2: Dev Review, release-note-none

#19132 Automated cherry pick of #19129 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
Labels: 2: Dev Review, release-note-none

#19128 [MM-40485] Enable receiving binary websocket messages
  api4/websocket_test.go
  app/web_conn.go
  model/websocket_client.go
  model/websocket_client_test.go
  model/websocket_request.go
Labels: 4: Reviews Complete, release-note

#19113 Remove the remaining fields from *app.Server
  app/brand.go
  app/channels.go
  app/file.go
  app/server.go
  app/slack.go
  app/team.go
  app/upload.go
  app/user.go
Labels: 4: Reviews Complete, Do Not Merge, release-note-none

#19096 MM-38150 Adding playbooks permissions
  api4/role.go
  app/app_test.go
  app/migrations.go
  app/permissions_migrations.go
  app/plugin_api.go
  app/scheme.go
  model/migration.go
  model/permission.go
  model/role.go
  model/scheme.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/sqlstore/integrity_test.go
  store/sqlstore/scheme_store.go
  store/sqlstore/upgrade.go
  store/storetest/scheme_store.go
  testlib/store.go
Labels: 2: Dev Review, release-note-none

#19130 Pre-package Playbooks v1.22.1
  Makefile
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#19137 Automated cherry pick of #19130
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19138 Automated cherry pick of #19130
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19122 Remove dead struct ManifestExecutables
  model/manifest.go
Labels: 4: Reviews Complete, release-note

#19136 MM-40469: Handle invalid response codes from plugins
  app/plugin_commands.go
  app/plugin_commands_test.go
Labels: 2: Dev Review, release-note-none

#19012 [MM-39636] Migrate from gorp to sqlx in store/sqlstore/product_notices_store.go
  store/sqlstore/product_notices_store.go
Labels: 4: Reviews Complete, Lifecycle/1:stale, AutoMerge, release-note-none, Contributor

#18994 [MM-39636] Migrate from gorp to sqlx in store/sqlstore/retention_policy_store.go
  store/sqlstore/retention_policy_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#19146 [MM-39231] Migrate license store from gorp to sqlx in store/sqlstore/license_store.go
  store/sqlstore/license_store.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#19111 prepackage boards to v0.11.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#19151 Automated cherry pick of #19111
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19153 Automated cherry pick of #19152 on release-6.2
  i18n/nl.json
  i18n/ru.json
  i18n/tr.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#19154 Automated cherry pick of #19152 on cloud
  i18n/nl.json
  i18n/ru.json
  i18n/tr.json
Labels: release-note-none

#19174 update boards version to 0.7.5
  Makefile
Labels: release-note

#19167 update boards version to 0.9.5
  Makefile
Labels: release-note

#19166 update boards version to 0.10.1
  Makefile
Labels: release-note

#19022 [MM-39640] Migrate from gorp to sqlx in store/sqlstore/role_store.go
  store/sqlstore/role_store.go
Labels: 4: Reviews Complete, 3: QA Review, AutoMerge, release-note-none, Contributor

#19164 Improve gif processing
  app/file.go
Labels: 4: Reviews Complete, 2: Dev Review, release-note-none

#19185 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19186 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19187 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19177 Remove unnecessary test TestValidateToken
  shared/mfa/mfa_test.go
Labels: release-note-none

#19183 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19184 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19182 Update version to 6.2.1
  model/version.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#19143 fix mmctl download script when using as stand alone script
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: release-note-none

#19192 [MM-40682] - SIGSEGV after upgrade from 6.1.0 to 6.2.0
  app/plugin.go
  app/plugin_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#19179 Allow go benchmarks to use api helpers functions
  api4/apitestlib.go
  api4/file_test.go
  api4/team_test.go
Labels: 4: Reviews Complete, release-note-none

#19195 Automated cherry pick of #19192
  app/plugin.go
  app/plugin_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19158 Re-initialize plugins only when needed
  app/channels.go
Labels: 4: Reviews Complete, Do Not Merge, release-note

#19107 [GH-19105] - Add helper function to handle columns on reserved names
  store/sqlstore/command_store.go
  store/sqlstore/compliance_store.go
  store/sqlstore/store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#19201 Update version to 6.0.5
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19203 Update version to 6.2.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19191 Force right index for post deletion
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note-none

#19194 MM-40537: Bump bleve dependency to fix Sentry crash
  go.mod
  go.sum
  vendor/github.com/blevesearch/bleve/v2/.gitignore
  vendor/github.com/blevesearch/bleve/v2/analysis/type.go
  vendor/github.com/blevesearch/bleve/v2/config_app.go
  vendor/github.com/blevesearch/bleve/v2/config_disk.go
  vendor/github.com/blevesearch/bleve/v2/document/field_ip.go
  vendor/github.com/blevesearch/bleve/v2/go.mod
  vendor/github.com/blevesearch/bleve/v2/go.sum
  vendor/github.com/blevesearch/bleve/v2/index/scorch/snapshot_index.go
  vendor/github.com/blevesearch/bleve/v2/index/upsidedown/upsidedown.go
  vendor/github.com/blevesearch/bleve/v2/mapping.go
  vendor/github.com/blevesearch/bleve/v2/mapping/document.go
  vendor/github.com/blevesearch/bleve/v2/mapping/field.go
  vendor/github.com/blevesearch/bleve/v2/query.go
  vendor/github.com/blevesearch/bleve/v2/search.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_datetime.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_numeric.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_terms.go
  vendor/github.com/blevesearch/bleve/v2/search/facets_builder.go
  vendor/github.com/blevesearch/bleve/v2/search/highlight/fragmenter/simple/simple.go
  vendor/github.com/blevesearch/bleve/v2/search/query/ip_range.go
  vendor/github.com/blevesearch/bleve/v2/search/query/query_string_lex.go
  vendor/github.com/blevesearch/bleve/v2/search/searcher/search_ip_range.go
  vendor/github.com/blevesearch/zapx/v11/posting.go
  vendor/github.com/blevesearch/zapx/v12/posting.go
  vendor/github.com/blevesearch/zapx/v13/posting.go
  vendor/github.com/blevesearch/zapx/v14/posting.go
  vendor/github.com/blevesearch/zapx/v15/posting.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#19002 [MM-39999] Increase key length in plugin KV store to 150
  app/plugin_api_tests/test_kv/main.go
  model/plugin_key_value.go
  model/plugin_key_value_test.go
  store/sqlstore/plugin_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#19202 Update version to 6.1.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19199 Update version to 5.37.7
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19188 [MM-40407] - Do not show the Renew Now if the license id does not exist in the portal
  api4/license.go
  app/license.go
  app/server.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#19210 [MM-29137] - adding a feature flag for inline post editing
  model/feature_flags.go
Labels: 2: Dev Review, release-note

#19216 Lock CI from /release-6.3
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: 2: Dev Review, release-note-none

#19235 Automated cherry pick of #19194
  go.mod
  go.sum
  vendor/github.com/blevesearch/bleve/v2/.gitignore
  vendor/github.com/blevesearch/bleve/v2/analysis/type.go
  vendor/github.com/blevesearch/bleve/v2/config_app.go
  vendor/github.com/blevesearch/bleve/v2/config_disk.go
  vendor/github.com/blevesearch/bleve/v2/document/field_ip.go
  vendor/github.com/blevesearch/bleve/v2/go.mod
  vendor/github.com/blevesearch/bleve/v2/go.sum
  vendor/github.com/blevesearch/bleve/v2/index/scorch/snapshot_index.go
  vendor/github.com/blevesearch/bleve/v2/index/upsidedown/upsidedown.go
  vendor/github.com/blevesearch/bleve/v2/mapping.go
  vendor/github.com/blevesearch/bleve/v2/mapping/document.go
  vendor/github.com/blevesearch/bleve/v2/mapping/field.go
  vendor/github.com/blevesearch/bleve/v2/query.go
  vendor/github.com/blevesearch/bleve/v2/search.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_datetime.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_numeric.go
  vendor/github.com/blevesearch/bleve/v2/search/facet/facet_builder_terms.go
  vendor/github.com/blevesearch/bleve/v2/search/facets_builder.go
  vendor/github.com/blevesearch/bleve/v2/search/highlight/fragmenter/simple/simple.go
  vendor/github.com/blevesearch/bleve/v2/search/query/ip_range.go
  vendor/github.com/blevesearch/bleve/v2/search/query/query_string_lex.go
  vendor/github.com/blevesearch/bleve/v2/search/searcher/search_ip_range.go
  vendor/github.com/blevesearch/zapx/v11/posting.go
  vendor/github.com/blevesearch/zapx/v12/posting.go
  vendor/github.com/blevesearch/zapx/v13/posting.go
  vendor/github.com/blevesearch/zapx/v14/posting.go
  vendor/github.com/blevesearch/zapx/v15/posting.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19232 Automated cherry pick of #19104
  store/sqlstore/store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19230 Automated cherry pick of #19090
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19218 Automated cherry pick of #19040
  api4/websocket.go
  api4/websocket_test.go
  app/web_conn.go
  app/web_conn_test.go
  app/web_hub.go
  config/client.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19225 Automated cherry pick of #19111
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19237 Automated cherry pick of #19143
  build/release.mk
  scripts/download_mmctl_release.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19220 Automated cherry pick of #19096
  api4/role.go
  app/app_test.go
  app/migrations.go
  app/permissions_migrations.go
  app/plugin_api.go
  app/scheme.go
  model/migration.go
  model/permission.go
  model/role.go
  model/scheme.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/sqlstore/integrity_test.go
  store/sqlstore/scheme_store.go
  store/sqlstore/upgrade.go
  store/storetest/scheme_store.go
  testlib/store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19227 Automated cherry pick of #19164
  app/file.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19229 Automated cherry pick of #19012
  store/sqlstore/product_notices_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19221 Automated cherry pick of #18795
  model/utils.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19222 Automated cherry pick of #19136
  app/plugin_commands.go
  app/plugin_commands_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19223 Automated cherry pick of #19122
  model/manifest.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19236 Automated cherry pick of #19188
  api4/license.go
  app/license.go
  app/server.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19234 Automated cherry pick of #19179
  api4/apitestlib.go
  api4/file_test.go
  api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19224 Automated cherry pick of #19146
  store/sqlstore/license_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19226 Automated cherry pick of #19022
  store/sqlstore/role_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19228 Automated cherry pick of #19177
  shared/mfa/mfa_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19231 Automated cherry pick of #19113
  app/brand.go
  app/channels.go
  app/file.go
  app/server.go
  app/slack.go
  app/team.go
  app/upload.go
  app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19233 Automated cherry pick of #19192
  app/plugin.go
  app/plugin_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19008 [GH-18965] - Pass expire time from outside Cleanup method
  app/server.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/tokens_store.go
  store/sqlstore/tokens_store_test.go
  store/store.go
  store/storetest/mocks/TokenStore.go
  store/storetest/tokens_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Lifecycle/1:stale, release-note-none, Contributor

#19217 upgrade db to 6.3.0
  store/sqlstore/upgrade.go
Labels: CherryPick/Approved, release-note, 3: Perf Review

#19242 Automated cherry pick of #19217
  store/sqlstore/upgrade.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19196 [MM-39542] Allow upsert for duplicate key in LinkMetadataStore
  store/sqlstore/link_metadata_store.go
  store/storetest/link_metadata_store.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#19243 Cherry-pick of #18669 Drop existing default on Users.Timezone prior to column type change
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#19244 Cherry-pick of #18669 Drop existing default on Users.Timezone prior to column type change
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#19245 Cherry-pick of #18669 Drop existing default on Users.Timezone prior to column type change
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#19246 cherry-pick #19196 [MM-39542] Allow upsert for duplicate key in LinkM…
  store/sqlstore/link_metadata_store.go
  store/storetest/link_metadata_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19260 Cherry-pick of #19097
  web/handlers.go
  web/handlers_test.go
Labels: 4: Reviews Complete, release-note-none
