Repository mattermost/mattermost, pull requests merged in 2021-07, with the labels that each got.

#17856 Run test-schema on additional refs.
  .gitlab-ci.yml
Labels: AutoMerge, release-note-none

#17857 Fast forward recent pipeline changes to cloud.
  .circleci/config.yml
  .gitlab-ci.yml
  build/.gitignore
  build/Dockerfile
  build/dotenv/test-schema-validation.env
  build/gitlab-dc.common.yml
  build/gitlab-dc.mysql.yml
  build/gitlab-dc.postgres.yml
  build/gitlab-dc.schemamysql.yml
  build/gitlab-dc.schemapostgres.yml
Labels: release-note-none

#17863 Translations update from Weblate
  i18n/de.json
  i18n/ja.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17816 [MM-36457] - Send email when license is up for renewal
  app/email.go
  app/server.go
  i18n/en.json
  model/license.go
  templates/license_up_for_renewal.html
  templates/license_up_for_renewal.mjml
Labels: QA Review Done, Setup Cloud Test Server, release-note-none

#17871 Lock CI for release-5.37
  .circleci/config.yml
  .gitlab-ci.yml
  model/version.go
  scripts/download_mmctl_release.sh
Labels: release-note-none

#17855 Use original opengraph dependency
  go.mod
  go.sum
  vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#17867 Prepackage focalboard v0.7.3
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#17876 Automated cherry pick of #17867
  Makefile
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#17877 Automated cherry pick of #17867
  Makefile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17874 MM-36731 - ux changes cloud starter flat fee
  model/cloud.go
Labels: release-note-none

#17887 Default CollapsedThreads feature flag to on
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note

#17890 Reliable Websockets: default to true
  model/config.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17886 Pre-package Incident Collaboration v1.14.2
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17893 Set current schema version to 5.37
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17892 Bump schema version to 5.37
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17069 [MM-33395] Invalidate email tokens
  app/email.go
  app/user.go
  app/user_test.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/tokens_store.go
  store/store.go
  store/storetest/mocks/TokenStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#17880 ChannelStore: Use native upsert for Postgres
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#17882 PluginStore: Use native upsert for Postgres
  store/sqlstore/plugin_store.go
Labels: 4: Reviews Complete, release-note-none

#17898 Automated cherry pick of #17886
  Makefile
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17894 PreferenceStore: Use native upsert for Postgres
  store/sqlstore/preference_store.go
Labels: 4: Reviews Complete, release-note-none

#17899 MM-36947: Fix failure in master
  app/slashcommands/helper_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17903 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17881 MM-36894: Racy test: TestExecuteCommandInDirectMessageChannel
  app/notification_push.go
Labels: 4: Reviews Complete, release-note-none

#17905 fix an issue that possibly emerged from upstream merge
  app/auto_responder.go
Labels: 2: Dev Review, release-note-none

#17888 MM-36779 - Add ChimeraOAuthProxyURL config option
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, kind/feature, release-note

#17909 Move some variables out of model
  app/command.go
  app/command_test.go
  app/post.go
  model/at_mentions.go
  model/emoji.go
  model/post.go
Labels: 4: Reviews Complete, release-note

#17912 MM-21333: Unexport fields in WebSocketEvent
  api4/channel_test.go
  api4/post_test.go
  app/web_conn_test.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17916 Pre-package Incident Collaboration v1.14.3
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#17917 Automated cherry pick of #17916
  Makefile
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17897 go: upgrade builder image to use go1.16
  .circleci/config.yml
  build/README.md
  build/local-test-env.sh
Labels: release-note

#17803 [MM-35345][MM-35494] fixes for incorrect mentions and unreads for threads and channels
  model/version.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, release-note

#17798 [MM-36563] Only read body from inter-plugin request if there is one
  app/plugin_api_test.go
  plugin/client_rpc.go
Labels: 4: Reviews Complete, release-note

#17901 MM-36947: Fix TestHeaderProviderDoCommand
  app/slashcommands/helper_test.go
Labels: 4: Reviews Complete, release-note-none

#17914 MM-21473: Remove unused cluster events
  model/cluster_message.go
Labels: 4: Reviews Complete, release-note

#17920 MM-21357: Use typed constants ClusterEvent
  api4/plugin_test.go
  app/busy_test.go
  app/plugin_event.go
  einterfaces/cluster.go
  einterfaces/metrics.go
  einterfaces/mocks/ClusterInterface.go
  einterfaces/mocks/MetricsInterface.go
  model/cluster_message.go
  services/cache/cache.go
  services/cache/lru.go
  services/cache/lru_striped.go
  services/cache/provider.go
  services/cache/provider_test.go
  testlib/cluster.go
Labels: 4: Reviews Complete, release-note

#17925 MM-36909: Skip flaky CreateDefaultMemberships for now
  app/syncables_test.go
Labels: 4: Reviews Complete, release-note-none

#17902 GroupStore: Use native upsert
  store/sqlstore/group_store.go
Labels: 4: Reviews Complete, release-note-none

#17927 MM-36411- Skip flaky TestUpdateConfigDiffInAuditRecord
  api4/config_test.go
Labels: 4: Reviews Complete, release-note-none

#17932 Bump version
  build/Dockerfile
Labels: release-note-none

#17910 MM-21333: Remove deprecated session method
  model/session.go
  model/session_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17300 [MM-33264] db/migrations: add migration scripts for Remote Clusters
  db/migrations/bindata.go
  db/migrations/mysql/000031_create_remote_clusters.down.sql
  db/migrations/mysql/000031_create_remote_clusters.up.sql
  db/migrations/postgres/000031_create_remote_clusters.down.sql
  db/migrations/postgres/000031_create_remote_clusters.up.sql
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17934 Update version to 5.37.1
  app/slashcommands/helper_test.go
  model/version.go
Labels: release-note-none

#17938 [MM-35345]: fix unreads in threads and migration
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: 4: Reviews Complete, release-note-none

#17926 [MM-35925] Follow thread when posting in one, even if previously unfollowed
  app/post.go
  app/post_test.go
Labels: 4: Reviews Complete, release-note-none

#17845 [MM-36711] nested sql query for reply_count in getSingle post method of post_sto…
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#17942 Add a return in 2 places
  api4/cloud.go
Labels: release-note-none

#17939 [MM-32604] Remove hard-coded override of MaxNotificationsPerChannel
  app/server.go
Labels: 4: Reviews Complete, release-note

#17919 MM-37034: Bump the MySQL min version to 5.7
  build/docker-compose.common.yml
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, release-note

#17947 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
Labels: release-note-none

#17692 Introduce per platform make package targets
  Makefile
  build/release.mk
Labels: 2: Dev Review, 3: QA Review, release-note

#17827 Decouple emailservice from app package
  api4/cloud.go
  api4/team_local.go
  api4/user.go
  api4/user_test.go
  app/app.go
  app/channel_test.go
  app/cloud.go
  app/email/email.go
  app/email/email_batching.go
  app/email/email_batching_test.go
  app/email/email_test.go
  app/email/errors.go
  app/email/helper_test.go
  app/email/main_test.go
  app/email/notification_email.go
  app/email/service.go
  app/email/utils.go
  app/email_test.go
  app/notification_email.go
  app/notification_email_test.go
  app/plugin_api.go
  app/server.go
  app/session.go
  app/team.go
  app/user.go
  app/user_test.go
  app/web_hub_test.go
  go.tools.mod
  go.tools.sum
  i18n/en.json
  services/users/profile_picture.go
  services/users/service.go
  services/users/service_test.go
  services/users/users.go
  web/saml.go
Labels: 4: Reviews Complete, release-note-none

#17928 MM-21357: Use typed constant for channel types
  api4/apitestlib.go
  api4/channel.go
  api4/channel_local.go
  api4/channel_test.go
  app/channel.go
  app/helper_test.go
  app/import_functions_test.go
  app/import_test.go
  app/import_types.go
  app/import_validators_test.go
  app/notification_push.go
  app/notification_push_test.go
  app/slashcommands/auto_channels.go
  app/slashcommands/helper_test.go
  cmd/mattermost/commands/sampledata.go
  migrations/helper_test.go
  model/auditconv.go
  model/channel.go
  model/client4.go
  model/message_export.go
  model/role.go
  model/role_test.go
  model/shared_channel.go
  services/sharedchannel/channelinvite.go
  services/slackimport/parsers.go
  services/slackimport/slackimport.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchtest/helper.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/integrity.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#17879 Consider empty body before unmarshal on do post action
  app/integration_action.go
  app/integration_action_test.go
Labels: 4: Reviews Complete, release-note

#17946 [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-07-19
  .circleci/config.yml
  Makefile
  api4/cloud.go
  api4/config_test.go
  app/email.go
  app/notification_push.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/post.go
  app/post_test.go
  app/server.go
  app/slashcommands/helper_test.go
  app/syncables_test.go
  app/user.go
  app/user_test.go
  build/Dockerfile
  build/README.md
  build/local-test-env.sh
  go.mod
  go.sum
  i18n/en.json
  model/cloud.go
  model/config.go
  model/feature_flags.go
  model/license.go
  model/version.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/group_store.go
  store/sqlstore/plugin_store.go
  store/sqlstore/post_store.go
  store/sqlstore/preference_store.go
  store/sqlstore/store.go
  store/sqlstore/thread_store.go
  store/sqlstore/tokens_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
  store/store.go
  store/storetest/mocks/TokenStore.go
  store/storetest/post_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
  templates/license_up_for_renewal.html
  templates/license_up_for_renewal.mjml
  vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#17966 Automated cherry pick of #17879
  app/integration_action.go
  app/integration_action_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17727 MM-36085: Split out System/Team Schemes from license feature checks.
  Makefile
  api4/role.go
  api4/role_test.go
  build/release.mk
  i18n/bg.json
  i18n/de.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
Labels: release-note

#17945 Cleanup model/utils.go
  api4/post_test.go
  api4/role.go
  api4/role_test.go
  app/import_validators.go
  app/plugin_signature.go
  model/config.go
  model/role.go
  model/team.go
  model/user.go
  model/utils.go
  model/utils_test.go
Labels: 4: Reviews Complete, release-note

#17961 Remove FromJSON functions (Part 1)
  api4/bot.go
  api4/bot_test.go
  app/oauth.go
  model/access.go
  model/access_test.go
  model/analytics_row.go
  model/analytics_row_test.go
  model/audit.go
  model/audit_test.go
  model/audits.go
  model/audits_test.go
  model/authorize.go
  model/authorize_test.go
  model/bot.go
  model/bot_test.go
  model/client4.go
  web/oauth.go
Labels: 4: Reviews Complete, release-note

#17969 update mattermost server build to use go 1.16.6
  .circleci/config.yml
  .gitlab-ci.yml
  build/README.md
  build/local-test-env.sh
Labels: 4: Reviews Complete, release-note

#17967 MM-37033 - update product model to match with customer web server
  model/cloud.go
Labels: CherryPick/Approved, release-note-none

#17936 MM-37130 Add feature flag for global header.
  model/feature_flags.go
Labels: 4: Reviews Complete, release-note-none

#17976 Bump to 5.31.9
  model/version.go
Labels: AutoMerge, release-note-none

#17922 [MM-36327] - Make a translation string clearer
  i18n/en.json
  i18n/en_AU.json
Labels: 2: Dev Review, release-note-none

#17982 Increase mysql version of gitlab docker-compose.
  build/gitlab-dc.mysql.yml
  build/gitlab-dc.schemamysql.yml
Labels: AutoMerge, release-note-none

#17944 MM-35392 Load thread unreads for other teams on app load
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/team.go
  model/client4.go
  model/team_member.go
  model/thread.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, release-note

#17984 Automated cherry pick of #17944
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/team.go
  model/client4.go
  model/team_member.go
  model/thread.go
  store/sqlstore/thread_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17987 Fix bad merge causing undefined CRT constant
  app/team.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17981 MM-22051: Remove FromJson part 2
  api4/channel.go
  api4/channel_category.go
  api4/channel_local.go
  api4/data_retention.go
  model/channel.go
  model/channel_count.go
  model/channel_data.go
  model/channel_list.go
  model/channel_member.go
  model/channel_member_test.go
  model/channel_search.go
  model/channel_search_test.go
  model/channel_sidebar.go
  model/channel_test.go
  model/client4.go
  model/team_search_test.go
Labels: 4: Reviews Complete, release-note

#17993 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17977 [MM-37064] - Onboarding flow is showing for existing users
  api4/preference_test.go
  app/plugin_api_test.go
  app/user.go
  app/user_test.go
  model/preference.go
Labels: 2: Dev Review, CherryPick/Candidate, release-note-none

#17997 MM-37378: Skip TestPanicLog
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#18000 Translations update from Weblate
  i18n/hu.json
  i18n/nl.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17999 MM-22051: Remove ToJson methods from network writes
  api4/bot.go
  api4/channel.go
  api4/channel_local.go
  api4/command.go
  api4/command_local.go
  api4/command_test.go
  api4/compliance.go
  api4/config.go
  api4/config_local.go
  api4/emoji.go
  api4/file.go
  api4/job.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/preference.go
  api4/reaction.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/status.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/terms_of_service.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/webhook.go
  api4/webhook_local.go
Labels: 4: Reviews Complete, release-note-none

#17998 MM-25516: Changed to byte slice instead of string for cluster messages
  api4/plugin_test.go
  app/busy.go
  app/busy_test.go
  app/cluster_handlers.go
  app/plugin_api.go
  app/plugin_api_tests/manual.test_http_upgrade_websocket_plugin/main.go
  app/plugin_event.go
  app/slashcommands/command_share_test.go
  app/status.go
  app/web_hub.go
  model/cluster_message.go
  model/cluster_message_test.go
  model/websocket_message.go
  model/websocket_message_test.go
  services/users/session.go
  services/users/users.go
  store/localcachelayer/channel_layer.go
  store/localcachelayer/emoji_layer.go
  store/localcachelayer/file_info_layer.go
  store/localcachelayer/layer.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/reaction_layer.go
  store/localcachelayer/role_layer.go
  store/localcachelayer/scheme_layer.go
  store/localcachelayer/team_layer.go
  store/localcachelayer/terms_of_service_layer.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/webhook_layer.go
Labels: 4: Reviews Complete, release-note

#17985 MM-36446: Omit Filenames from Post JSON.
  model/post.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note

#17989 MM-36545 Fix replica lag issue causing missed websocket events to update following
  app/notification.go
Labels: release-note

#17913 [MM-35470] Disable config watching logic
  Makefile
  api4/config_test.go
  app/options.go
  app/server.go
  app/server_test.go
  cmd/mattermost/commands/cmdtestlib.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/root.go
  cmd/mattermost/commands/server.go
  config/database.go
  config/file.go
  config/file_test.go
  config/memory.go
  config/migrate.go
  config/migrate_test.go
  config/store.go
  config/store_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, Docs/Needed, release-note

#18002 Cherry-pick to cloud of MM-37064
  api4/preference_test.go
  app/plugin_api_test.go
  app/user.go
  app/user_test.go
  model/preference.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17933 [MM-37108] Fix possible nil dereference in team edition
  api4/license.go
  api4/license_test.go
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#18007 Automated cherry pick of #17933
  api4/license.go
  api4/license_test.go
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#18012 Improve error logged from App.addUserToChannel
  app/channel.go
Labels: 4: Reviews Complete, release-note-none

#17848 MM-36248 Fix GitLab Button Color and Text not reflecting in UI
  config/client.go
Labels: 4: Reviews Complete, release-note

#17930 [MM-36995] Start using db native JSON datatypes
  go.mod
  go.sum
  store/sqlstore/channel_store.go
  store/sqlstore/job_store.go
  store/sqlstore/link_metadata_store.go
  store/sqlstore/post_store.go
  store/sqlstore/session_store.go
  store/sqlstore/store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/storetest/channel_store.go
  vendor/github.com/mattermost/gorp/column.go
  vendor/github.com/mattermost/gorp/table.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note

#18005 MM-22051: Remove ToJson from model (part 1)
  api4/command.go
  api4/emoji.go
  app/cluster_discovery.go
  cmd/mattermost/commands/cmdtestlib.go
  model/access.go
  model/analytics_row.go
  model/audit.go
  model/audits.go
  model/authorize.go
  model/channel.go
  model/channel_count.go
  model/channel_data.go
  model/channel_member.go
  model/channel_stats.go
  model/channel_view.go
  model/channel_view_test.go
  model/client4.go
  model/cluster_discovery.go
  model/cluster_discovery_test.go
  model/cluster_info.go
  model/cluster_info_test.go
  model/cluster_stats.go
  model/cluster_stats_test.go
  model/command.go
  model/command_args.go
  model/command_request.go
  model/command_response.go
  model/command_test.go
  model/compliance.go
  model/compliance_test.go
  model/config.go
  model/emoji.go
  plugin/helpers_config.go
  testlib/resources.go
  web/oauth.go
Labels: 4: Reviews Complete, release-note

#18014 MM-37042 Add "playbooks" and "boards" to restricted team URLs list
  model/team_test.go
  model/utils.go
Labels: 4: Reviews Complete, release-note

#17992 [MM-37278] Removing data retention feature flag
  go.tools.mod
  go.tools.sum
  i18n/en.json
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18009 MM-37417: Push notification authz fix.
  api4/post.go
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
Labels: 2: Dev Review, 3: QA Review, release-note

#18016 MM-37299 - add feature flag for invite members ab testing
  model/feature_flags.go
Labels: release-note-none

#17965 [MM-37118] Don't mark channel as read for reply posts with CRT on
  app/post.go
  app/post_test.go
Labels: 4: Reviews Complete, QA Review Done, Setup HA Cloud Test Server, release-note-none

#17842 Making doc extraction more reliable
  go.mod
  go.sum
  services/docextractor/docextractor_test.go
  services/docextractor/documents.go
  tests/sample-doc.doc
  vendor/code.sajari.com/docconv/.travis.yml
  vendor/code.sajari.com/docconv/README.md
  vendor/code.sajari.com/docconv/go.mod
  vendor/code.sajari.com/docconv/go.sum
  vendor/code.sajari.com/docconv/local.go
  vendor/code.sajari.com/docconv/pages.go
  vendor/code.sajari.com/docconv/rtf.go
  vendor/code.sajari.com/docconv/tidy.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#18024 Lock CI for release-5.38
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#18027 DB upgrade 5.38
  store/sqlstore/upgrade.go
Labels: AutoMerge, release-note-none

#18023 [MM-37314] Fix categorization method version for plugin api
  plugin/api.go
Labels: 2: Dev Review, release-note-none

#18029 cherry pick of #17965 on release-5.38
  app/post.go
  app/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed

#18020 [MM-36544][MM-37439] Don't re-follow on reply to unfollowed thread
  app/notification.go
  app/post.go
  app/post_test.go
  app/user.go
  store/sqlstore/thread_store.go
  store/store.go
Labels: 4: Reviews Complete, release-note

#17364 [MM-33273] add migrations for sidebarchannels
  db/migrations/bindata.go
  db/migrations/mysql/000032_create_sidebar_channels.down.sql
  db/migrations/mysql/000032_create_sidebar_channels.up.sql
  db/migrations/postgres/000032_create_sidebar_channels.down.sql
  db/migrations/postgres/000032_create_sidebar_channels.up.sql
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, release-note-none
