Repository mattermost/mattermost, pull requests merged in 2021-04, with the labels that each got.

#17306 [MM-34179] app: move cluster registeration to server creation
  app/admin.go
  app/app.go
  app/app_iface.go
  app/cluster_handlers.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/session.go
  app/web_hub.go
  cmd/mattermost/commands/server.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17313 Bump to 5.33.4
  model/version.go
Labels: AutoMerge, release-note-none

#17307 MM-34487: Add dead queue
  app/web_conn.go
  app/web_conn_test.go
Labels: 4: Reviews Complete, release-note-none

#17320 MM-33746 hotfix
  .circleci/config.yml
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
  store/sqlstore/upgrade.go
Labels: release-note

#17099 MM-33708 - Add MentionCountRoot column to ChannelMembers
  .circleci/config.yml
  api4/channel_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  app/team.go
  app/user.go
  model/channel_member.go
  model/client4.go
  model/team_member.go
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/group_store.go
  store/sqlstore/post_store.go
  store/sqlstore/team_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#17321 [MM-34557] commands/server_test: add skip
  cmd/mattermost/commands/server_test.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17322 [MM-34179] cherry-pick of: app: move cluster registeration to server creation (#17306)
  app/admin.go
  app/app.go
  app/app_iface.go
  app/cluster_handlers.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/session.go
  app/web_hub.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/server_test.go
Labels: release-note-none

#17327 Automated cherry pick of #17321
  cmd/mattermost/commands/server_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17323 [MM-34520] app/server: make sure if metrics server goroutine executed
  app/server.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17173 MM-33913: Fix read-after-write issues with team member
  api4/apitestlib.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/helper_test.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_invite_test.go
  app/slashcommands/helper_test.go
  app/team.go
  app/team_test.go
  app/user.go
  cmd/mattermost/commands/team.go
  migrations/helper_test.go
  services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note-none

#17174 MM-34002: Improve AddUserToChannel
  api4/apitestlib.go
  api4/channel.go
  api4/channel_local.go
  api4/channel_test.go
  api4/post_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/helper_test.go
  app/notification_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/post_test.go
  app/slashcommands/command_invite.go
  app/slashcommands/command_invite_test.go
  app/slashcommands/command_leave_test.go
  app/slashcommands/command_remove_test.go
  app/slashcommands/helper_test.go
  app/syncables.go
  app/syncables_test.go
  app/team.go
  app/user.go
  app/user_test.go
  cmd/mattermost/commands/channel.go
  migrations/helper_test.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note-none

#17032 Fix initialism errors (PR-2)
  app/plugin_api_tests/basic_config.go
  app/plugin_api_tests/test_get_channels_for_team_for_user_plugin/main.go
  app/plugin_api_tests/test_get_direct_channel_plugin/main.go
  app/plugin_api_tests/test_get_profile_image_plugin/main.go
  app/plugin_api_tests/test_member_channels_plugin/main.go
  app/plugin_api_tests/test_members_plugin/main.go
  app/plugin_api_tests/test_search_channels_plugin/main.go
  app/plugin_api_tests/test_search_posts_in_team_plugin/main.go
  app/plugin_api_tests/test_set_profile_image_plugin/main.go
  app/plugin_api_tests/test_update_user_active_plugin/main.go
  app/plugin_api_tests/test_update_user_status_plugin/main.go
  einterfaces/ldap.go
  einterfaces/mfa.go
  einterfaces/mocks/LdapInterface.go
  einterfaces/mocks/MfaInterface.go
  einterfaces/mocks/NotificationInterface.go
  einterfaces/notification.go
  plugin/api.go
  services/httpservice/client_test.go
  services/imageproxy/imageproxy.go
  services/marketplace/client.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/store.go
  store/storetest/mocks/AuditStore.go
  store/storetest/mocks/BotStore.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/CommandStore.go
  store/storetest/mocks/FileInfoStore.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/OAuthStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/mocks/ProductNoticesStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/StatusStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/mocks/UploadSessionStore.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/UserTermsOfServiceStore.go
  store/storetest/mocks/WebhookStore.go
  store/timerlayer/timerlayer.go
  utils/merge_test.go
  utils/subpath_test.go
  utils/utils.go
  utils/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#17334 Translations update from Weblate
  i18n/fr.json
  i18n/nl.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17338 [MM-34240]-Cloud: Congratulations welcome email missing images
  app/email.go
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#17163 MM-33905 -always add FeatureFlags to config
  api4/config.go
  api4/config_test.go
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#16917 All Sections to SubSections
  api4/bleve.go
  api4/bleve_test.go
  api4/cluster.go
  api4/compliance.go
  api4/config.go
  api4/config_test.go
  api4/elasticsearch.go
  api4/job.go
  api4/job_test.go
  api4/ldap.go
  api4/license.go
  api4/role.go
  api4/saml.go
  api4/system.go
  api4/team.go
  api4/team_test.go
  app/app_iface.go
  app/config.go
  app/job.go
  app/job_test.go
  app/opentracing/opentracing_layer.go
  app/permissions_migrations.go
  config/environment.go
  config/store.go
  i18n/en.json
  model/config.go
  model/job.go
  model/migration.go
  model/permission.go
  model/permission_test.go
  model/role.go
  model/utils.go
  model/utils_test.go
  scripts/mattermost-postgresql-5.0.sql
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/job_store.go
  store/sqlstore/role_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
  store/timerlayer/timerlayer.go
  testlib/store.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#17344 Automated cherry pick of #17338
  app/email.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17348 [No-Ticket] Fix Broken Test
  api4/config_test.go
Labels: 4: Reviews Complete, release-note

#17325 Automated cherry pick of #17306
  .circleci/config.yml
  app/admin.go
  app/app.go
  app/app_iface.go
  app/cluster_handlers.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/session.go
  app/web_hub.go
  cmd/mattermost/commands/server.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17339 Add missing wrapped errors
  app/brand.go
  app/channel.go
  app/emoji.go
  app/oauth.go
  app/plugin.go
  app/team.go
  app/user.go
  cmd/mattermost/commands/webhook.go
Labels: 4: Reviews Complete, release-note-none

#17324 Automated cherry pick of #17306
  .circleci/config.yml
  app/admin.go
  app/app.go
  app/app_iface.go
  app/cluster_handlers.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/session.go
  app/web_hub.go
  cmd/mattermost/commands/server.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17326 Automated cherry pick of #17321
  .circleci/config.yml
  cmd/mattermost/commands/server_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17183 Improve document extraction and including a document extraction command
  app/app_iface.go
  app/file.go
  app/migrations.go
  app/opentracing/opentracing_layer.go
  app/upload.go
  cmd/mattermost/commands/extract_content.go
  model/config.go
  services/docextractor/archive.go
  services/docextractor/combine.go
  services/docextractor/docextractor.go
  services/docextractor/docextractor_test.go
  services/docextractor/documents.go
  services/docextractor/interface.go
  services/docextractor/mmpreview.go
  services/docextractor/pdf.go
  services/docextractor/plain.go
  store/sqlstore/file_info_store.go
Labels: 4: Reviews Complete, release-note

#17355 Bump to 5.31.4
  model/version.go
Labels: release-note-none

#17356 Update en.json
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17358 Bump no_output_timeout to 2 hours
  .circleci/config.yml
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17345 [MM-33941] log invalid username
  model/user.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17362 Update en.json
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#17086 Refactor SQL queries in store/sqlstore/preference_store.go to use the squirrel builder
  store/sqlstore/preference_store.go
  store/storetest/preference_store.go
Labels: 4: Reviews Complete, release-note-none

#17368 Bump version
  build/Dockerfile
Labels: release-note-none

#17369 Fix missing version
  model/version.go
Labels: release-note

#17316 [MM-34414] Add TrialEndAt to cloud model Subscription type
  model/cloud.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#17182 [MM-33826] add more detailed S3 error messages
  api4/system_test.go
  app/file.go
  app/server.go
  i18n/en.json
  shared/filestore/filesstore_test.go
  shared/filestore/s3store.go
Labels: 2: Dev Review, 3: QA Review, AutoMerge, Setup Cloud Test Server, release-note-none

#16769 MM-29584: Make apps plugin hook invocation/registration conditional
  plugin/helpers_bots.go
  plugin/helpers_bots_test.go
Labels: 2: Dev Review, QA Review Done, release-note-none

#17346 Enable the errorAssertions govet check for mattermost-server code
  Makefile
  api4/file_test.go
  api4/team_test.go
  api4/user_test.go
  app/channel_test.go
  app/file_test.go
  app/post_test.go
  app/remote_cluster_test.go
  app/server_test.go
  app/session_test.go
  app/user_test.go
  config/database_test.go
  config/file_test.go
  migrations/migrations_test.go
  model/remote_cluster_test.go
  plugin/helpers_bots_test.go
  services/remotecluster/ping_test.go
  store/localcachelayer/user_layer_test.go
  store/storetest/file_info_store.go
  store/storetest/reaction_store.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#17371 [MM-34504] Change cloud welcome email copy
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#17186 [MM-31899] Use a custom user-agent when previewing links
  app/post_metadata.go
  services/httpservice/client.go
Labels: 4: Reviews Complete, release-note

#17381 Translations update from Weblate
  i18n/bg.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, release-note-none

#17378 [MM-33058] Add migrations for bots schema
  db/migrations/bindata.go
  db/migrations/mysql/000029_create_bots.down.sql
  db/migrations/mysql/000029_create_bots.up.sql
  db/migrations/postgres/000029_create_bots.down.sql
  db/migrations/postgres/000029_create_bots.up.sql
  store/sqlstore/bot_store.go
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#17232 MM-33180: Extend Group APIs for plugins.
  app/plugin_api.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 4: Reviews Complete, release-note

#17161 [MM-32044] Reset SAML auth data
  api4/api.go
  api4/saml.go
  api4/saml_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/saml.go
  build/docker/keycloak/README.md
  i18n/en.json
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, 3: QA Review, AutoMerge, Setup Cloud Test Server, release-note

#17382 Translations update from Weblate (#17381)
  i18n/bg.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, release-note-none

#17347 MM-32133 shared channel username collisions
  api4/shared_channel_test.go
  app/remote_cluster_service_mock.go
  app/remote_cluster_test.go
  app/session_test.go
  app/slashcommands/command_remote.go
  i18n/en.json
  model/at_mentions.go
  model/auditconv.go
  model/config.go
  model/remote_cluster.go
  model/remote_cluster_test.go
  model/user.go
  model/user_test.go
  services/remotecluster/invitation.go
  services/remotecluster/send_test.go
  services/remotecluster/sendmsg.go
  services/remotecluster/service.go
  services/sharedchannel/channelinvite_test.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  services/sharedchannel/util.go
  services/sharedchannel/util_test.go
  store/sqlstore/remote_cluster_store.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
Labels: 3: QA Review, release-note-none

#17386 MM-34785: Skip TestPing
  services/remotecluster/ping_test.go
Labels: 4: Reviews Complete, release-note-none

#17387 MM-34786: Fix racy test TestStartServerTLSSuccess
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#17388 MM-34787: Add colored output for non JSON console logs
  model/config.go
  shared/mlog/log.go
  shared/mlog/testing.go
  utils/logger.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#17365 [MM-34507] - MM Server: Send email for trial ending
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_end_warning.mjml
Labels: 4: Reviews Complete, release-note-none

#17108 MM-32657: Update group sync to work with AD - SAML ids
  einterfaces/ldap.go
  einterfaces/mocks/LdapInterface.go
Labels: 4: Reviews Complete, release-note

#17398 Add IsFreeTrial to Subscription and SubscriptionStats types
  model/cloud.go
Labels: AutoMerge, release-note

#17399 Automated cherry pick of #17347
  api4/shared_channel_test.go
  app/remote_cluster_service_mock.go
  app/remote_cluster_test.go
  app/session_test.go
  app/slashcommands/command_remote.go
  i18n/en.json
  model/at_mentions.go
  model/auditconv.go
  model/config.go
  model/remote_cluster.go
  model/remote_cluster_test.go
  model/user.go
  model/user_test.go
  services/remotecluster/invitation.go
  services/remotecluster/send_test.go
  services/remotecluster/sendmsg.go
  services/remotecluster/service.go
  services/sharedchannel/channelinvite_test.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  services/sharedchannel/util.go
  services/sharedchannel/util_test.go
  store/sqlstore/remote_cluster_store.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17383 Translations update from Weblate (#17381)
  i18n/bg.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17394 Automated cherry pick of #17186
  app/post_metadata.go
  services/httpservice/client.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17397 Feature: Support Cloud 14-day Trial
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_end_warning.mjml
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#17402 Automated cherry pick of #17397
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_end_warning.mjml
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17361 MM-34549 shared channels; add users to channel that were already sync'd
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/shared_channel.go
  app/slashcommands/command_remote.go
  model/shared_channel.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, release-note-none

#17350 [MM-34240] - Cloud: "Congratulations" welcome email missing images
  api4/cloud.go
  app/email.go
  templates/cloud_welcome_email.html
Labels: CherryPick/Candidate, release-note-none

#17411 Automated cherry pick of #17350
  api4/cloud.go
  app/email.go
  templates/cloud_welcome_email.html
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17390 MM-34774 Root post with mention should be auto-followed but hidden from thread results
  app/notification.go
  app/post_test.go
Labels: 4: Reviews Complete, release-note

#17400 MM-34785 fix racy ping test
  services/remotecluster/mocks_test.go
  services/remotecluster/ping_test.go
  services/remotecluster/send_test.go
  services/remotecluster/service_test.go
Labels: 4: Reviews Complete, release-note-none

#17413 [MM-34888] Revert Posts.FileIds migration on MySQL
  scripts/mattermost-mysql-5.0.sql
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#17343 MM-34609 Mark-as-unread on a post in a thread should cause auto-follow
  api4/post_test.go
  app/channel.go
  app/notification.go
  app/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#17404 Fix problem with nulls in file infos content field
  store/sqlstore/file_info_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17423 Cherry pick #17404
  store/sqlstore/file_info_store.go
Labels: release-note-none

#17416 Fix 5.35 migration
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Tests Not Required, release-note-none

#16891 Mm 30807 granular data retention scaffold
  api4/channel.go
  api4/channel_test.go
  api4/data_retention.go
  api4/team.go
  api4/team_test.go
  app/analytics.go
  app/app_iface.go
  app/channel.go
  app/data_retention.go
  app/helper_test.go
  app/import_functions_test.go
  app/layer_generators/main.go
  app/opentracing/opentracing_layer.go
  app/security_update_check.go
  app/server.go
  app/team.go
  einterfaces/data_retention.go
  einterfaces/mocks/DataRetentionInterface.go
  i18n/en.json
  model/channel.go
  model/channel_search.go
  model/client4.go
  model/data_retention_policy.go
  model/team.go
  model/team_search.go
  model/utils.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/retention_policy_store_test.go
  store/sqlstore/store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/RetentionPolicyStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/retention_policy_store.go
  store/storetest/shared_channel_store.go
  store/storetest/store.go
  store/storetest/team_store.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/params.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#17392 [MM-34725] app/user: check if username or email is in use before patching a user
  app/bot.go
  app/bot_test.go
  app/user.go
  app/user_test.go
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  store/sqlstore/user_store.go
Labels: 4: Reviews Complete, release-note-none

#17429 Hotfix add multistatements param on mysql url
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: release-note

#17414 [MM-34888] Fix 5.32 migration (cloud branch)
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17437 Revert "Mm 30807 granular data retention scaffold"
  api4/channel.go
  api4/channel_test.go
  api4/data_retention.go
  api4/team.go
  api4/team_test.go
  app/analytics.go
  app/app_iface.go
  app/channel.go
  app/data_retention.go
  app/helper_test.go
  app/import_functions_test.go
  app/layer_generators/main.go
  app/opentracing/opentracing_layer.go
  app/security_update_check.go
  app/server.go
  app/team.go
  einterfaces/data_retention.go
  einterfaces/mocks/DataRetentionInterface.go
  i18n/en.json
  model/channel.go
  model/channel_search.go
  model/client4.go
  model/data_retention_policy.go
  model/team.go
  model/team_search.go
  model/utils.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/retention_policy_store_test.go
  store/sqlstore/store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/RetentionPolicyStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/retention_policy_store.go
  store/storetest/shared_channel_store.go
  store/storetest/store.go
  store/storetest/team_store.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/params.go
Labels: release-note-none

#17425 MM-34792 test shouldn't depend on upgrade sequence
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: 2: Dev Review, CherryPick/Approved, release-note

#17439 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17415 [MM-34888] Fix 5.32 migration (master branch)
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17418 [MM-34919] Use Mattermost-Plugin-ID header to pass ID in inter-plugin requests
  app/plugin_api_test.go
  app/plugin_requests.go
  plugin/context.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17443 Automated cherry pick of #17418
  app/plugin_api_test.go
  app/plugin_requests.go
  plugin/context.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17428 Hotfix add multistatements param on mysql url
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Done, release-note

#17431 MM-34983: Remove check for number of data sources
  i18n/en.json
  model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17446 Automated cherry pick of #17431
  i18n/en.json
  model/config.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17403 Add doc extraction dependencies
  build/Dockerfile
Labels: AutoMerge, CherryPick/Approved, release-note-none

#17401 [MM-34840] Remove the Remove System Permissions
  app/permissions_migrations.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17449 Automated cherry pick of #17403
  build/Dockerfile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17451 Automated cherry pick of #17401
  app/permissions_migrations.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17444 [MM-13799] Avoid queries timing out during upgrade
  go.mod
  go.sum
  store/sqlstore/store_test.go
  store/sqlstore/upgrade.go
  vendor/github.com/mattermost/gorp/column.go
  vendor/github.com/mattermost/gorp/gorp.go
  vendor/github.com/mattermost/gorp/table.go
  vendor/modules.txt
Labels: CherryPick/Approved, QA/Tests Not Required, release-note

#17422 #MM-34893 Completely disabled Admin Advisor
  app/app.go
  app/bot.go
  app/server.go
Labels: CherryPick/Approved, Docs/Needed, release-note-none

#17454 Automated cherry pick of #17422
  app/app.go
  app/bot.go
  app/server.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17441 MM-34125: Remove WebSocketDelay feature flag
  app/web_conn.go
  model/feature_flags.go
Labels: 4: Reviews Complete, release-note

#17453 [MM-13799] Avoid queries timing out during upgrade (cloud cherry-pick)
  go.mod
  go.sum
  store/sqlstore/store_test.go
  store/sqlstore/upgrade.go
  vendor/github.com/mattermost/gorp/column.go
  vendor/github.com/mattermost/gorp/gorp.go
  vendor/github.com/mattermost/gorp/table.go
  vendor/modules.txt
Labels: release-note

#17460 Fixing problem with read-replica on indexing files
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/file_info_layer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, CherryPick/Approved, release-note-none

#17461 Automated cherry pick of #17460
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/file_info_layer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17464 Mm 30807 granular data retention scaffold
  api4/channel.go
  api4/channel_test.go
  api4/data_retention.go
  api4/team.go
  api4/team_test.go
  app/analytics.go
  app/app_iface.go
  app/channel.go
  app/data_retention.go
  app/helper_test.go
  app/import_functions_test.go
  app/layer_generators/main.go
  app/opentracing/opentracing_layer.go
  app/security_update_check.go
  app/server.go
  app/team.go
  einterfaces/data_retention.go
  einterfaces/mocks/DataRetentionInterface.go
  i18n/en.json
  model/channel.go
  model/channel_search.go
  model/client4.go
  model/data_retention_policy.go
  model/team.go
  model/team_search.go
  model/utils.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/retention_policy_store_test.go
  store/sqlstore/store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/RetentionPolicyStore.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/retention_policy_store.go
  store/storetest/shared_channel_store.go
  store/storetest/store.go
  store/storetest/team_store.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/params.go
Labels: release-note-none

#17409 MM-31717: Remove HTTP clustering
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#17447 MM-34871 CRT: Participants of thread include non-replying followers (and past followers)
  app/channel.go
  app/notification.go
  app/post_test.go
  app/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#17448 MM-34872 CRT: thread last_viewed_at updated when channel is viewed
  app/channel.go
  app/channel_test.go
  app/post_test.go
Labels: 4: Reviews Complete, release-note

#17470 Fix performance problem on document extraction
  services/docextractor/plain.go
Labels: CherryPick/Approved, QA/Tests Not Required, release-note-none

#17122 Custom status fixes
  api4/status.go
  app/slashcommands/command_custom_status.go
Labels: 4: Reviews Complete, release-note

#17473 Automated cherry pick of #17470
  services/docextractor/plain.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17176 [MM-32281] SqlRoleStore/GetByName: add context to allow read from master
  api4/apitestlib.go
  api4/group_test.go
  api4/role.go
  api4/role_test.go
  app/app_iface.go
  app/app_test.go
  app/channel.go
  app/channel_test.go
  app/helper_test.go
  app/import_functions.go
  app/import_functions_test.go
  app/job_test.go
  app/migrations.go
  app/opentracing/opentracing_layer.go
  app/permissions.go
  app/permissions_test.go
  app/role.go
  app/role_test.go
  app/slashcommands/helper_test.go
  app/team.go
  app/user_test.go
  services/telemetry/mocks/ServerIface.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/role_layer.go
  store/localcachelayer/role_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/role_store.go
  store/sqlstore/scheme_store.go
  store/store.go
  store/storetest/mocks/RoleStore.go
  store/storetest/role_store.go
  store/storetest/scheme_store.go
  store/timerlayer/timerlayer.go
  web/oauth_test.go
Labels: 4: Reviews Complete, release-note-none

#17466 [MM-34838] Remove Ancillary Permissions That Are Purposefully Being Removed
  api4/api.go
  api4/permission.go
  api4/permissions_test.go
  api4/role.go
  model/client4.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17410 [MM-34798] Respect MM_SERVER_PATH when looking for templates
  app/server.go
  shared/templates/templates.go
  web/static.go
Labels: 4: Reviews Complete, release-note-none

#17181 MM-31339: Send only one direct message reply within one calendar day.
  app/auto_responder.go
  app/auto_responder_test.go
  app/helper_test.go
  i18n/en.json
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/utils.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17391 [MM-34216] app/import: do not break import process if a dm channel is invalid
  app/export.go
  app/export_test.go
  app/import.go
  app/import_test.go
Labels: 4: Reviews Complete, release-note-none

#17305 [MM-33662] - Mock out CWS in enterprise code
  Makefile
  config.mk
  model/cloud.go
Labels: 4: Reviews Complete, release-note

#17474 MM-34895 CRT: Replying to a root post with an at-mention triggers an unread mention
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#17482 Improving doc extraction command
  cmd/mattermost/commands/extract_content.go
  services/docextractor/docextractor_test.go
  services/docextractor/plain.go
Labels: AutoMerge, CherryPick/Approved, Tests/Not Needed, release-note-none

#17487 Lock CI for release-5.35
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#17489 Automated cherry pick of #17466
  api4/api.go
  api4/permission.go
  api4/permissions_test.go
  api4/role.go
  model/client4.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17375 MM-34712 shared channels: sync user profile image
  Makefile
  api4/remote_cluster.go
  model/user.go
  services/remotecluster/mocks_test.go
  services/remotecluster/send.go
  services/remotecluster/sendfile.go
  services/remotecluster/sendmsg.go
  services/remotecluster/sendprofileImage.go
  services/remotecluster/sendprofileImage_test.go
  services/remotecluster/service.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
Labels: 4: Reviews Complete, release-note-none

#17185 [MM-33853] remove CSV row limit in compliance monitoring
  model/compliance.go
  model/config.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/compliance_store.go
  store/store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/ComplianceStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, 3: QA Review, release-note

#17488 upgrade DB for 5.35
  model/version.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#17478 [MM-35039] - Send trial ended email
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_ended_email.html
  templates/cloud_trial_ended_email.mjml
Labels: 2: Dev Review, QA Deferred, Setup Cloud Test Server, release-note-none

#17498 Automated cherry pick of #17482
  cmd/mattermost/commands/extract_content.go
  services/docextractor/docextractor_test.go
  services/docextractor/plain.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17509 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17510 Automated cherry pick of #17478
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_ended_email.html
  templates/cloud_trial_ended_email.mjml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#17501 Bump to 5.31.5
  model/version.go
Labels: release-note-none

#17512 Automated cherry pick of #17375
  Makefile
  api4/remote_cluster.go
  model/user.go
  services/remotecluster/mocks_test.go
  services/remotecluster/send.go
  services/remotecluster/sendfile.go
  services/remotecluster/sendmsg.go
  services/remotecluster/sendprofileImage.go
  services/remotecluster/sendprofileImage_test.go
  services/remotecluster/service.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#17513 Automated cherry pick of #17482
  cmd/mattermost/commands/extract_content.go
  services/docextractor/docextractor_test.go
  services/docextractor/plain.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#17500 upgrade DB for 5.35 (#17488)
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17484 Updates on CI
  .circleci/config.yml
  Makefile
Labels: 4: Reviews Complete, release-note-none

#17406 MM-32950: Reliable WebSockets: Basic single server
  api4/websocket.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/web_conn.go
  app/web_conn_test.go
  app/web_hub.go
  app/web_hub_test.go
  config/client.go
Labels: 4: Reviews Complete, release-note-none

#17504 MM-35125 CRT: Mention badge on threads doesn't appear until refresh
  app/notification.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note

#17517 drop wrong migration item
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17480 update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#17507 MM-35127 CRT: Marking thread as unread doesn't set the timestamp correctly
  api4/user_test.go
  app/post.go
Labels: Setup Cloud Test Server, release-note

#17505 MM-35128 CRT: Global Threads item should not be affected by 'mark as unread' in channel
  app/channel.go
  store/sqlstore/channel_store.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note

#17525 Fix file info index batch
  store/sqlstore/file_info_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17524 MM-35239: Skip TestHubSessionRevokeRace
  app/web_hub_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17503 MM-35103 Replies in a thread with an initial mention triggers notification each time
  app/notification.go
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#17456 MM-34674 Adding config telemetry for feature flags.
  config/client.go
  config/feature_flags.go
  config/feature_flags_test.go
  model/config.go
  model/feature_flags.go
  model/feature_flags_test.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 4: Reviews Complete, release-note-none

#17385 MM-24455: Fix role responses.
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/permissions_migrations.go
  app/role.go
  app/role_test.go
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note

#17526 Automated cherry pick of #17525
  store/sqlstore/file_info_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17465 [MM-34918] Update prepackaged version of autolink and GitHub
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17296 MM-18818 Prompt admins to set the Support Email
  app/app.go
  app/server.go
  app/server_test.go
  i18n/en.json
  model/config.go
  model/system.go
  templates/email_info.html
  templates/invite_body.html
  templates/partials/questions_footer.mjml
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: 4: Reviews Complete, release-note

#17529 Automated cherry pick of #17503
  app/notification.go
  store/sqlstore/upgrade_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17534 MM-35239: Fix racy test HubSessionRevokeRace
  app/web_hub_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17530 Automated cherry pick of #17465
  Makefile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17527 Automated cherry pick of #17525
  store/sqlstore/file_info_store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17536 Automated cherry pick of #17465
  Makefile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17154 Bump golangci version to v1.38.0
  .circleci/config.yml
  .gitlab-ci.yml
  .golangci.yml
  api4/bot_test.go
  api4/config_test.go
  api4/post_test.go
  api4/terms_of_service_test.go
  app/file_test.go
  app/group_test.go
  app/import_functions_test.go
  app/post.go
  app/post_test.go
  app/slashcommands/command_test.go
  model/integration_action_test.go
  model/post_test.go
  store/storetest/channel_store.go
  store/storetest/compliance_store.go
  store/storetest/team_store.go
  vendor/modules.txt
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#17518 MM-35181 Move SharedChannelsUsers.ChannelId column add to 5.36 migration
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#17538 bump golangci-lint to 1.39.0
  .circleci/config.yml
Labels: release-note-none

#17495 [MM-35077] Add basic support for plugin intra-cluster communication
  app/busy_test.go
  app/cluster_handlers.go
  app/plugin_api.go
  einterfaces/cluster.go
  einterfaces/mocks/ClusterInterface.go
  model/cluster_message.go
  model/plugin_cluster_event.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
  testlib/cluster.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#17520 MM-22678 Use more user-friendly errors for channel commands
  app/slashcommands/command_channel_header.go
  app/slashcommands/command_channel_purpose.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#17523 [MM-35222] Fix DoGuestRolesCreationMigration
  app/migrations.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note-none

#17537 MM-35290 CRT: Reply on a unfollowed thread causes re-following
  app/notification.go
Labels: 4: Reviews Complete, release-note-none

#17540 Automated cherry pick of #17523
  app/migrations.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17506 MM-35123 - CRT: Replying to a post with mention causes two mention badges to appear
  app/notification.go
Labels: 4: Reviews Complete, release-note

#17541 MM-35300 CRT: No mention badge on Threads when user is mentioned in both the root post and a reply post
  app/notification.go
Labels: release-note-none

#17533 MM-35206 CRT: is_following on posts not reflecting state properly
  model/post.go
  store/sqlstore/post_store.go
Labels: 2: Dev Review, release-note-none

#17543 Automated cherry pick of #17523
  app/migrations.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17522 MM-34878: Add metrics for websocket reconnects
  app/web_conn.go
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
Labels: 4: Reviews Complete, release-note-none

#17531 CRT: Don't ignore own replies during reply count calculation
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, release-note-none
