Repository mattermost/mattermost, pull requests merged in 2021-05, with the labels that each got.

#17559 ci: update inbucket to use mattermost/inbucket:release-1.2.0
  build/docker-compose.common.yml
Labels: 2: Dev Review, release-note

#17561 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17562 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17566 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17564 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17563 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17565 ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)
  build/docker-compose.common.yml
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#17557 ci: drop sentry setup for PRs
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#17558 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note

#17445 [MM-29666] compliance export skipped posts
  model/message_export.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/compliance_store.go
  store/store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/ComplianceStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, 3: QA Review, release-note-none

#17372 [MM-33908] Resync LDAP Groups to Teams and Channels
  api4/group.go
  api4/ldap.go
  api4/ldap_test.go
  app/app_iface.go
  app/group.go
  app/ldap.go
  app/opentracing/opentracing_layer.go
  app/syncables.go
  app/syncables_test.go
  cmd/mattermost/commands/ldap.go
  einterfaces/ldap.go
  einterfaces/mocks/LdapInterface.go
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, 3: QA Review, release-note

#17567 [MM-35061] - Welcome Email: Missing spacing between icon and paragraphs
  templates/cloud_welcome_email.html
Labels: 2: Dev Review, release-note-none

#17582 MM-35430 sanitize user before creation during sync
  services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, release-note

#17588 Translations update from Weblate
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/ro.json
  i18n/zh-CN.json
Labels: release-note-none

#17585 Pre-package Incident Collaboration v1.9.3
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17592 Automated cherry pick of #17585
  Makefile
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17590 [MM-35404] - Cloud Trial - Body of 'Trial ends today Email (Admin-only)' conflicts with subject line
  i18n/en.json
Labels: QA Deferred, release-note-none

#17601 build/package: remove dist/mattermost directory
  build/release.mk
Labels: 4: Reviews Complete, release-note-none

#17595 MM-35582 updated i18n strings
  i18n/en.json
Labels: 2: Dev Review, Area/Localization, release-note-none

#17606 remove request.Context from shared channel service methods
  api4/remote_cluster.go
  app/remote_cluster_service_mock.go
  services/remotecluster/recv.go
  services/remotecluster/service.go
  services/remotecluster/service_test.go
  services/sharedchannel/attachment.go
  services/sharedchannel/channelinvite.go
  services/sharedchannel/channelinvite_test.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#17560 ci: upgrade inbucket
  build/docker-compose.common.yml
Labels: 4: Reviews Complete, release-note-none

#17591 Removes JS redirection
  i18n/en.json
  utils/api.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#17610 Cherry Pick of https://github.com/mattermost/mattermost-server/pull/17591 into release-5.35
  i18n/en.json
  utils/api.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17611 https://github.com/mattermost/mattermost-server/pull/17591 cherry pick into cloud
  i18n/en.json
  utils/api.go
Labels: AutoMerge, release-note-none

#17609 Bump to 5.31.6
  model/version.go
Labels: release-note-none

#17551 Add RequestTrialLicense function to the plugin API
  app/plugin_api.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 4: Reviews Complete, release-note

#17619 [MM-35404] cherry-pick - Cloud Trial - Body of 'Trial ends today Email (Admin-only)' conflicts with subject line
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#17629 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17624 [MM-35767] Ignore readTimeout param from MySQL datasource
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17632 [MM-35767] Cherrypick on 5.35
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: release-note-none

#17634 MM-35802 Rename json fields for GetAllSharedChannels to match other channel objects
  model/shared_channel.go
Labels: release-note

#17636 Remove redundant additions to cache hit/miss counters
  store/localcachelayer/user_layer.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17602 [MM-35424] Fix job schedulers server from missing leader change event
  app/server.go
  jobs/schedulers.go
  jobs/schedulers_test.go
  jobs/server.go
Labels: 4: Reviews Complete, release-note

#17644 Fix racy tests
  jobs/schedulers_test.go
Labels: AutoMerge, QA/Tests Not Required, release-note-none

#17578 [MM-32390] Config logic refactor
  Makefile
  api4/config_test.go
  api4/user_test.go
  app/audit.go
  app/feature_flags.go
  app/featureflag/feature_flags_sync.go
  app/featureflag/feature_flags_sync_test.go
  app/featureflag/split_logger.go
  app/options.go
  app/server.go
  build/release.mk
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/server.go
  config/client_test.go
  config/common_test.go
  config/config_generator/generator/generator.go
  config/database_test.go
  config/default.go
  config/emitter.go
  config/export_test.go
  config/file_test.go
  config/logging.go
  config/logging_test.go
  config/main_test.go
  config/memory_test.go
  config/migrate.go
  config/migrate_test.go
  config/store.go
  config/store_test.go
  config/unmarshal.go
  config/utils.go
  config/utils_test.go
  config/watcher.go
  scripts/config_generator/main.go
  scripts/config_generator/main_test.go
Labels: 4: Reviews Complete, release-note

#17222 [MM-7968] restrict creation of direct channels to team members
  api4/channel_test.go
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_msg.go
  app/team.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#17646 Fix races in config refactor
  config/store.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17643 [MM-35841] Fix invalid use of variables in invite_body template
  app/email.go
  templates/invite_body.html
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#17647 [MM-35861] Add missing migration transformation
  app/permissions_migrations.go
  model/migration.go
  testlib/store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#17649 [MM-35841] Fix invalid use of variables in invite_body template (#17643)
  app/email.go
  templates/invite_body.html
Labels: release-note-none

#17651 Update the about.mattermost.com links to the real ones
  model/config.go
Labels: 1: PM Review, release-note-none

#17655 Cherrypick pr 17647 to cloud
  app/permissions_migrations.go
  model/migration.go
  testlib/store.go
Labels: AutoMerge, release-note-none

#17654 Cherrypick PR 17647 to release-5.35
  app/permissions_migrations.go
  model/migration.go
  testlib/store.go
Labels: AutoMerge, release-note-none

#17579 MM-35133 trigger sync user immediately after change
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post_test.go
  app/reaction_test.go
  app/server.go
  app/shared_channel.go
  app/shared_channel_notifier_test.go
  app/shared_channel_service_iface.go
  app/user.go
  model/post.go
  model/shared_channel.go
  services/sharedchannel/attachment.go
  services/sharedchannel/getpostssince.go
  services/sharedchannel/msg.go
  services/sharedchannel/response.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  services/sharedchannel/sync_send_remote.go
  services/sharedchannel/util.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/post_store.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#17623 [MM-28692] Include config diffs in audit record for config changing API calls
  api4/apitestlib.go
  api4/config.go
  api4/config_local.go
  api4/config_test.go
  app/app_iface.go
  app/config.go
  app/migrations.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  config/common_test.go
  config/database_test.go
  config/diff.go
  config/diff_test.go
  config/file_test.go
  config/migrate.go
  config/migrate_test.go
  config/store.go
  config/store_test.go
  i18n/en.json
  web/context.go
Labels: 4: Reviews Complete, release-note

#17657 Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time (#16067)"
  api4/apitestlib.go
  api4/status.go
  api4/status_test.go
  app/app.go
  app/app_iface.go
  app/helper_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/server.go
  app/status.go
  model/scheduled_task.go
  model/scheduled_task_test.go
  model/status.go
  model/status_test.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/status_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/StatusStore.go
  store/storetest/status_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17656 Use Node 14 build image for web app
  .circleci/config.yml
Labels: release-note-none

#17666 Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time (#16067)"
  api4/apitestlib.go
  api4/status.go
  api4/status_test.go
  app/app.go
  app/app_iface.go
  app/helper_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/server.go
  app/status.go
  model/scheduled_task.go
  model/scheduled_task_test.go
  model/status.go
  model/status_test.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/status_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/StatusStore.go
  store/storetest/status_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17667 [MM-35931] Apply DB migrations regardless of version patch value
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Tests Not Required, release-note

#17661 Remove all remaining occurences of fakeApp
  app/app_iface.go
  app/integration_action.go
  app/notification_push.go
  app/opentracing/opentracing_layer.go
  app/plugin_requests.go
  app/plugin_requests_test.go
  app/plugin_test.go
  app/server.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17577 check authdata for different format
  app/user.go
  app/user_test.go
  einterfaces/mocks/OauthProvider.go
  einterfaces/oauthproviders.go
  model/gitlab/gitlab.go
  web/oauth_test.go
Labels: 3: QA Review, release-note

#17627 Fix typo in `extract-documents-content` command line tool description
  cmd/mattermost/commands/extract_content.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#17670 Translations update from Weblate
  i18n/de.json
  i18n/fr.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17612 Remove reintroduced CustomUserStatuses feature flag
  model/feature_flags.go
Labels: 4: Reviews Complete, release-note-none

#17645 MM-3543/MM-35436: fix thread being marked unread when updating reply posts
  api4/user_test.go
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, release-note-none

#17673 MM-34895: LastViewed should be updated correctly for new thread membership
  api4/user_test.go
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: release-note-none

#17678 MM-34895: fix test from earlier LastViewed CRT changes
  store/storetest/thread_store.go
Labels: 2: Dev Review, release-note-none

#17669 MM-35945: handle lots of files in ExtractTarGz
  app/extract_plugin_tar.go
  app/extract_plugin_tar_test.go
Labels: 4: Reviews Complete, release-note-none

#17576 [MM-34303] Add team ID to response when linking a channel to a group
  api4/group_test.go
  model/group_syncable.go
  store/sqlstore/group_store.go
Labels: 3: QA Review, release-note

#17677 Update webapp build image to Node 16
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#17424 MM-34758 Collapsed Reply Threads without mobile support
  api4/channel.go
  api4/channel_test.go
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  model/channel_view.go
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: Setup Cloud Test Server, release-note

#17475 Fixed MM-33249 issue
  app/slashcommands/command_custom_status.go
  app/slashcommands/command_custom_status_test.go
  model/custom_status.go
  model/emoji.go
Labels: 4: Reviews Complete, release-note

#17685 Pass-through DB Driver implementation
  shared/driver/conn.go
  shared/driver/driver.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, release-note-none

#17676 [MM-35625] Add controller for changing cloud subscription
  api4/cloud.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  model/cloud.go
Labels: 4: Reviews Complete, release-note-none

#17570 Custom status expiry
  api4/status.go
  app/slashcommands/command_custom_status.go
  app/slashcommands/command_custom_status_test.go
  model/custom_status.go
Labels: 4: Reviews Complete, release-note
