Repository mattermost/mattermost, pull requests merged in 2021-02, with the labels that each got.

#16803 Make channel readonly when shared as such
  services/sharedchannel/channelinvite.go
  services/sharedchannel/channelinvite_test.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/service.go
Labels: 2: Dev Review, release-note-none

#16827 MM-32299 Add sync'd users to team & ChannelMembers
  Makefile
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/mock_ServerIface_test.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, release-note-none

#16794 [MM-32253] Fix "Cannot mark unread a DM message in a thread"
  app/notification.go
  app/post.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, Tests/Done, release-note-none

#16797 [MM-31731] Fix cleanup threads to properly handle not found errors
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#16831 Automated cherry pick of #16794
  app/notification.go
  app/post.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16832 Automated cherry pick of #16794
  app/notification.go
  app/post.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16833 Automated cherry pick of #16797
  store/sqlstore/post_store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16837 Automated cherry pick of #16797
  store/sqlstore/post_store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16667 [MM-31790] Support Packet Generation BACKEND
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/file.go
  app/file_test.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/server_test.go
  config/client.go
  einterfaces/ldap.go
  einterfaces/mocks/LdapInterface.go
  i18n/en.json
  model/client4.go
  model/system.go
  services/searchengine/bleveengine/bleve.go
  services/searchengine/interface.go
  services/searchengine/mocks/SearchEngineInterface.go
  testlib/testdata/mysql_migration_warmup.sql
  testlib/testdata/postgres_migration_warmup.sql
Labels: 4: Reviews Complete, release-note

#16808 MM-5639: Write panic to log on the way out
  cmd/mattermost/commands/server.go
Labels: 4: Reviews Complete, release-note

#16828 [NO-TICKET] Cleanup - remove unused code
  app/file.go
  app/file_test.go
  app/helper_test.go
  services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note-none

#16841 Translations update from Weblate
  i18n/bg.json
  i18n/ja.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#16847 MM-32553 hard delete channel when channel invite fails
  services/sharedchannel/channelinvite.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/service.go
Labels: 4: Reviews Complete, release-note

#16840 MM-30314 Don't delete all SidebarChannels when removed from team (5.31)
  store/sqlstore/channel_store_categories.go
  store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, AutoMerge, Setup Cloud Test Server, release-note

#16823 Add 'files' as a reserved team
  model/utils.go
Labels: 4: Reviews Complete, release-note

#16786 [MM-31497] - Prevent end users from inviting people and exceeding the free tier limits
  api4/cloud.go
  api4/team.go
  model/client4.go
  model/cloud.go
Labels: 4: Reviews Complete, release-note

#16836 [MM-32389] Fix FeatureFlags section erroneously getting written to config
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16863 Automated cherry pick of #16836
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/store.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16861 Automated cherry pick of #16836
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#16862 Automated cherry pick of #16836
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#16604 Send user updated websocket event on plugin.UpdateUser
  app/app_iface.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  app/user.go
Labels: 4: Reviews Complete, release-note

#16866 MM-32569: prepackage Incident Collaboration v1.3.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16870 Automated cherry pick of #16866
  Makefile
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16818 Fix initialisms/app
  app/admin.go
  app/analytics.go
  app/app_iface.go
  app/audit.go
  app/authorization.go
  app/auto_responder.go
  app/bot.go
  app/channel.go
  app/channel_category.go
  app/command.go
  app/email.go
  app/email_batching.go
  app/export.go
  app/file.go
  app/file_bench_test.go
  app/file_test.go
  app/group.go
  app/import_functions.go
  app/import_functions_test.go
  app/import_test.go
  app/integration_action.go
  app/notification.go
  app/notification_push.go
  app/notification_push_test.go
  app/notification_test.go
  app/oauth.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_requests.go
  app/post.go
  app/post_test.go
  app/preference.go
  app/product_notices.go
  app/ratelimit.go
  app/session.go
  app/slack.go
  app/slack_test.go
  app/slashcommands/auto_channels.go
  app/slashcommands/helper_test.go
  app/status.go
  app/team.go
  app/team_test.go
  app/terms_of_service.go
  app/upload.go
  app/user.go
  app/user_terms_of_service.go
  app/user_test.go
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
  app/webhook.go
  app/webhook_test.go
  app/webhub_fuzz.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16874 [MM-31369] Fix racy TestFileStoreWatcherEmitter/enabled
  config/file_test.go
Labels: 4: Reviews Complete, release-note-none

#16844 [MM-32122] Add translation strings for shared channels slash commands
  app/slashcommands/command_remote.go
  app/slashcommands/command_share.go
  app/slashcommands/command_share_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#16856 Avoid possible false possitives when generating team names
  store/storetest/scheme_store.go
Labels: 4: Reviews Complete, release-note-none

#16878 [NO-TICKET] Remove unused function attributes
  app/file.go
  services/slackimport/slackimport.go
  utils/i18n.go
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#16875 pre-package incident management v1.3.2
  Makefile
  app/plugin_test.go
  model/feature_flags.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#16889 Translations update from Weblate
  i18n/bg.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#16890 Automated cherry pick of #16875
  Makefile
  app/plugin_test.go
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16853 MM-32525 Incorrect number of mentions for channels when threads are enabled
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#16614 [MM-31247] Add support for compressed export files with attachments
  api4/api.go
  api4/export.go
  api4/export_local.go
  api4/export_test.go
  app/app.go
  app/app_iface.go
  app/enterprise.go
  app/export.go
  app/export_test.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  cmd/mattermost/commands/export.go
  cmd/mattermost/commands/import.go
  i18n/en.json
  imports/placeholder.go
  jobs/export_process/worker.go
  jobs/import_process/worker.go
  jobs/interfaces/export_process_interface.go
  jobs/jobs_watcher.go
  jobs/server.go
  jobs/workers.go
  model/client4.go
  model/config.go
  model/config_test.go
  model/job.go
  utils/archive.go
  web/params.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16810 Migrating AppError to error for mailservice
  app/email.go
  app/email_batching.go
  app/notification_email.go
  app/plugin_api.go
  app/server.go
  i18n/en.json
  services/mailservice/mail.go
  services/mailservice/mail_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16796 MM-32047:Added AppCustomURLSchemes settings to telemetry
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 2: Dev Review, release-note-none

#16865 unparam lint
  .golangci.yml
  api4/cloud.go
  api4/file.go
  api4/job.go
  api4/system.go
  config/database_test.go
  go.tools.mod
  go.tools.sum
  i18n/en.json
  mlog/logr.go
  plugin/interface_generator/main.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16900 Changed require.Nil to require.NoError when error type is used
  services/awsmeter/awsmeter_test.go
  services/cache/lru_test.go
  services/cache/provider_test.go
  services/docextractor/docextractor_test.go
  services/filesstore/filesstore_test.go
  services/filesstore/s3store_test.go
  services/httpservice/client_test.go
  services/imageproxy/atmos_camo_test.go
  services/imageproxy/local_test.go
  services/mailservice/mail_test.go
  services/searchengine/bleveengine/bleve_test.go
  services/upgrader/upgrader_linux_test.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#16886 Replacing {require,assert}.{Nil,NotNil} with {require,assert}.{NoError,Error} in the store tests (when comparing errors)
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/file_info_layer_test.go
  store/localcachelayer/post_layer_test.go
  store/localcachelayer/reaction_layer_test.go
  store/localcachelayer/role_layer_test.go
  store/localcachelayer/scheme_layer_test.go
  store/localcachelayer/team_layer_test.go
  store/localcachelayer/terms_of_service_layer_test.go
  store/localcachelayer/user_layer_test.go
  store/localcachelayer/webhook_layer_test.go
  store/searchtest/channel_layer.go
  store/searchtest/file_info_layer.go
  store/searchtest/helper.go
  store/searchtest/post_layer.go
  store/searchtest/user_layer.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_test.go
  store/sqlstore/integrity_test.go
  store/sqlstore/preference_store_test.go
  store/sqlstore/scheme_store.go
  store/sqlstore/session_store.go
  store/sqlstore/store_test.go
  store/sqlstore/upgrade_test.go
  store/storetest/audit_store.go
  store/storetest/bot_store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/channel_store_categories.go
  store/storetest/cluster_discovery_store.go
  store/storetest/command_store.go
  store/storetest/command_webhook_store.go
  store/storetest/compliance_store.go
  store/storetest/emoji_store.go
  store/storetest/file_info_store.go
  store/storetest/group_store.go
  store/storetest/job_store.go
  store/storetest/license_store.go
  store/storetest/link_metadata_store.go
  store/storetest/oauth_store.go
  store/storetest/plugin_store.go
  store/storetest/post_store.go
  store/storetest/preference_store.go
  store/storetest/reaction_store.go
  store/storetest/role_store.go
  store/storetest/scheme_store.go
  store/storetest/session_store.go
  store/storetest/status_store.go
  store/storetest/system_store.go
  store/storetest/team_store.go
  store/storetest/terms_of_service_store.go
  store/storetest/thread_store.go
  store/storetest/user_access_token_store.go
  store/storetest/user_store.go
  store/storetest/user_terms_of_service.go
  store/storetest/webhook_store.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#16880 MM-32275 Shared channel file attachment support
  api4/handlers.go
  api4/remote_cluster.go
  api4/upload.go
  app/app_iface.go
  app/authentication.go
  app/channel_share.go
  app/helper_test.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/session.go
  app/session_test.go
  app/slashcommands/command_share.go
  app/slashcommands/helper_test.go
  app/upload.go
  i18n/en.json
  mlog/levels.go
  model/channel_shared.go
  model/channel_shared_test.go
  model/client4.go
  model/file_info.go
  model/remote_cluster.go
  model/session.go
  model/upload_session.go
  services/remotecluster/invitation.go
  services/remotecluster/ping.go
  services/remotecluster/recv.go
  services/remotecluster/response.go
  services/remotecluster/response_test.go
  services/remotecluster/send.go
  services/remotecluster/send_test.go
  services/remotecluster/sendfile.go
  services/remotecluster/sendmsg.go
  services/remotecluster/service.go
  services/remotecluster/service_test.go
  services/sharedchannel/attachment.go
  services/sharedchannel/channelinvite.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/response.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upload_session_store.go
  store/store.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#16819 Optimise creation of DM
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#16895 MM-32471: Use created user to update roles
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
  cmd/mattermost/commands/user.go
Labels: 4: Reviews Complete, release-note-none

#16907 Revert MM-27312
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  model/post.go
  scripts/mattermost-mysql-5.0.sql
  scripts/mattermost-postgresql-5.0.sql
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#16908 Revert "MM-27312 Allow uploading 10 files per post (#16235)"
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  model/post.go
  scripts/mattermost-mysql-5.0.sql
  scripts/mattermost-postgresql-5.0.sql
  store/sqlstore/post_store.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#16896 MM31503 - screen to restrict access because workspace capacity
  api4/cloud.go
Labels: 2: Dev Review, release-note

#16894 MM-31182: Reuse the created bot user when creating a DM channel
  app/bot.go
  app/bot_test.go
  app/channel.go
Labels: release-note

#16433 Allow 'mmctl channel move' to move private channels
  api4/channel.go
  api4/channel_local.go
  api4/channel_test.go
Labels: 4: Reviews Complete, release-note

#16829 Duplucate test scenario fix
  config/utils_test.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note

#16901 unparam lint
  app/channel.go
  config/utils.go
  store/searchtest/helper.go
  store/searchtest/user_layer.go
Labels: AutoMerge, release-note-none

#16912 Cleanup unnecessary concurrent db calls on user
  app/user.go
Labels: 2: Dev Review, release-note

#16911 MM-30882: Fix read-after-write issue for demoting user
  app/bot.go
  app/channel.go
  app/channel_test.go
  app/command.go
  app/email_batching.go
  app/export.go
  app/integration_action.go
  app/notification.go
  app/oauth.go
  app/post.go
  app/session.go
  app/slack.go
  app/team.go
  app/user.go
  app/webhook.go
  cmd/mattermost/commands/user_test.go
  cmd/mattermost/commands/userargs.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/localcachelayer/user_layer.go
  store/localcachelayer/user_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/searchlayer/layer.go
  store/searchlayer/user_layer.go
  store/sqlstore/context.go
  store/sqlstore/context_test.go
  store/sqlstore/post_store.go
  store/sqlstore/session_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
  web/context_test.go
Labels: 4: Reviews Complete, release-note

#16922 Set required go version to 1.15
  go.mod
Labels: release-note-none

#16816 Reducing the filestore dependencies from the rest of the source code
  api4/plugin_test.go
  app/file.go
  app/plugin_test.go
  app/server.go
  model/config.go
  model/file.go
  model/utils.go
  services/filesstore/filesstore.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/s3store.go
  services/filesstore/s3store_test.go
  services/mailservice/mail.go
  services/mailservice/mail_test.go
  testlib/resources.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16937 Bump to 5.32.1
  model/version.go
Labels: release-note-none

#16885 MM-32652 /threads?unread=true returns null threads and no counts if there are no unread threads
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: release-note

#16926 Migrate channel to waitgroup for access the store in parallel
  go.mod
  store/sqlstore/user_store.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#16758 [MM-32136] add "telemetry: disabled" comments to the Config struct
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note-none

#16942 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#16793 [MM-31247] Implement job to delete export files
  app/app.go
  app/enterprise.go
  i18n/en.json
  imports/placeholder.go
  jobs/export_delete/scheduler.go
  jobs/export_delete/worker.go
  jobs/interfaces/export_delete_interface.go
  jobs/jobs_watcher.go
  jobs/schedulers.go
  jobs/server.go
  jobs/workers.go
  model/job.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16943 MM-32893: Refactor the getting of DB handle
  store/sqlstore/context.go
  store/sqlstore/team_store.go
  store/sqlstore/user_store.go
Labels: 4: Reviews Complete, release-note-none

#16944 add config telemetry check to vet tool
  Makefile
Labels: 2: Dev Review, release-note-none

#16852 Mm 32279/handle shared channel creation for DMs
  api4/shared_channel_test.go
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/shared_channel_notifier.go
  app/shared_channel_notifier_test.go
  app/shared_channel_service_iface.go
  app/web_hub.go
  i18n/en.json
  model/channel.go
  model/channel_shared.go
  services/sharedchannel/channelinvite.go
  services/sharedchannel/channelinvite_test.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/slackimport/slackimport.go
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, release-note

#16905 Replacing require.nil in app layer
  app/app_test.go
  app/bot_test.go
  app/channel_category_test.go
  app/channel_test.go
  app/config_test.go
  app/email_batching_test.go
  app/export_test.go
  app/file_test.go
  app/helper_test.go
  app/import_functions_test.go
  app/import_test.go
  app/integration_action_test.go
  app/job_test.go
  app/login_test.go
  app/notification_push_test.go
  app/notification_test.go
  app/oauth_test.go
  app/opengraph_test.go
  app/plugin_api_test.go
  app/plugin_health_check_test.go
  app/plugin_hooks_test.go
  app/plugin_install_test.go
  app/plugin_signature_test.go
  app/plugin_test.go
  app/post_metadata_test.go
  app/post_test.go
  app/product_notices_test.go
  app/role_test.go
  app/server_test.go
  app/session_test.go
  app/syncables_test.go
  app/team_test.go
  app/upload_test.go
  app/user_test.go
  app/webhook_test.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#16898 Reduce the coupling of the mailservice with the rest of the application
  app/admin.go
  app/app.go
  app/config.go
  app/email.go
  app/security_update_check.go
  app/server.go
  services/mailservice/mail.go
  services/mailservice/mail_test.go
Labels: 4: Reviews Complete, release-note-none

#16882 [MM-32543] - Add ability to send email to admin that users are trying to invite others
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/email_test.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/client4.go
  templates/cloud_upgrade_request_email.html
Labels: 4: Reviews Complete, release-note

#16920 Update incident-collaboration to 1.4.0
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, release-note

#16950 Revert "MM-24530-Add support for search terms with underscore using postgresql engine"
  api4/post_test.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
Labels: 2: Dev Review, release-note-none

#16906 Replacing require.nil in api layer
  api4/bot_test.go
  api4/brand_test.go
  api4/command_test.go
  api4/emoji_test.go
  api4/export_test.go
  api4/file_test.go
  api4/import_test.go
  api4/integration_action_test.go
  api4/job_test.go
  api4/license_test.go
  api4/oauth_test.go
  api4/plugin_test.go
  api4/post_test.go
  api4/preference_test.go
  api4/reaction_test.go
  api4/role_test.go
  api4/scheme_test.go
  api4/system_test.go
  api4/team_test.go
  api4/upload_test.go
  api4/user_test.go
  api4/websocket_test.go
Labels: 4: Reviews Complete, Tests/Not Needed, release-note-none

#16871 [MM-31674] app/product_notices: implement notices for ext. dependencies
  app/product_notices.go
  app/product_notices_test.go
  model/product_notices.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16952 Bump version
  build/Dockerfile
Labels: release-note-none

#16854 Save access on plugin env during ServePluginPublicRequest
  app/plugin_requests.go
  app/plugin_requests_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16957 Automated cherry pick of #16950
  api4/post_test.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16956 Automated cherry pick of #16950
  api4/post_test.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16955 Automated cherry pick of #16920
  Makefile
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16893 Updates the release version of the osixia/openldap Docker image.
  build/docker-compose.common.yml
Labels: 3: QA Review, release-note-none

#16887 [MM-32352] Add Experimental Subsections BACKEND
  api4/bleve.go
  api4/bleve_test.go
  api4/job.go
  api4/job_test.go
  app/app_iface.go
  app/job.go
  app/job_test.go
  app/opentracing/opentracing_layer.go
  app/permissions_migrations.go
  i18n/en.json
  model/migration.go
  model/permission.go
  model/role.go
  testlib/store.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#16835 Custom status feature
  api4/status.go
  app/app_iface.go
  app/command.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_custom_status.go
  app/status.go
  config/client.go
  i18n/en.json
  model/config.go
  model/custom_status.go
  model/emoji.go
  model/feature_flags.go
  model/preference.go
  model/user.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16925 Isolate more the mfa service
  app/authentication.go
  app/user.go
  i18n/en.json
  model/utils.go
  model/utils_test.go
  services/mfa/mfa.go
  services/mfa/mfa_test.go
Labels: 4: Reviews Complete, release-note-none

#16976 Automated cherry pick of #16835
  api4/status.go
  app/app_iface.go
  app/command.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_custom_status.go
  app/status.go
  config/client.go
  i18n/en.json
  model/config.go
  model/custom_status.go
  model/emoji.go
  model/feature_flags.go
  model/preference.go
  model/user.go
  services/telemetry/telemetry.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16877 [Partial Fix - #16623]: Fix initialism errors in codebase.
  app/app.go
  app/bot.go
  app/channel.go
  app/email.go
  app/file.go
  app/login.go
  app/oauth.go
  app/plugin.go
  app/plugin_requests.go
  app/post.go
  app/product_notices.go
  app/ratelimit.go
  app/reaction.go
  app/team.go
  app/upload.go
  app/user.go
  config/store.go
  go.tools.mod
  go.tools.sum
  model/command_response.go
  plugin/client_rpc.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/interface_generator/main.go
  plugin/supervisor.go
  store/errors.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/store.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/CommandStore.go
  store/storetest/mocks/FileInfoStore.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/PluginStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/ReactionStore.go
  store/storetest/mocks/RoleStore.go
  store/storetest/mocks/SchemeStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/TeamStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/mocks/UserAccessTokenStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/WebhookStore.go
  store/timerlayer/timerlayer.go
  utils/api.go
  utils/html.go
  utils/html_test.go
  utils/jsonutils/json.go
  utils/jsonutils/json_test.go
  utils/markdown/autolink.go
  utils/subpath.go
  utils/subpath_test.go
  utils/urlencode.go
  utils/urlencode_test.go
  utils/utils.go
  utils/utils_test.go
  web/handlers.go
  web/web.go
Labels: release-note-none

#16967 Improve error during WebSocket upgrade
  api4/websocket.go
Labels: 4: Reviews Complete, release-note-none

#16980 Remote any references to sqlite
  model/config.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 2: Dev Review, release-note

#16985 Close search replicas on store close
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 2: Dev Review, release-note

#16982 Change CSP during development for faster source maps
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#16795 User friendly error messages during OAUTH and SAML flows
  utils/api.go
  web/oauth.go
  web/oauth_test.go
  web/saml.go
Labels: 4: Reviews Complete, release-note-none

#16987 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16704 Adding bulk-indexing and improving a bit the name indexing for bleve and elasticsearch
  i18n/en.json
  model/feature_flags.go
  services/searchengine/bleveengine/bleve.go
  services/searchengine/bleveengine/common.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16929 Migrate from usage of channels to waitgroups on app/analytics.go
  app/analytics.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16996 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#16930 NO-TCIKET fix bad smells - error strings should not be capitalized
  app/command_autocomplete.go
  app/file_test.go
  app/layer_generators/main.go
  plugin/client_rpc.go
  plugin/supervisor.go
  services/docextractor/documents.go
  services/mailservice/inbucket.go
  store/layer_generators/main.go
  utils/i18n.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16945 [MM-32521] remove local socket file if it already exists
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#16966 [MM-32665] app/product_notices: support notice for deprecating elasticsearch
  app/product_notices.go
  app/product_notices_test.go
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#16999 Fix mailservice tests race condition
  services/mailservice/mail_test.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#16962 MM-32669 GetPostsSinceForSync
  .gitignore
  Makefile
  app/app_iface.go
  app/channel_share.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_share.go
  build/docker/nginx/default.conf
  docker-compose.yaml
  model/channel_shared.go
  model/post.go
  services/remotecluster/ping.go
  services/sharedchannel/channelinvite.go
  services/sharedchannel/getpostssince.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/shared_channel_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#17007 app/product_notices: check if server search engine is nil
  app/product_notices.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#16953 Replacing require.nil in model package
  model/access_test.go
  model/bundle_info_test.go
  model/channel_member_test.go
  model/channel_test.go
  model/command_autocomplete_test.go
  model/command_webhook_test.go
  model/config_test.go
  model/file_info_test.go
  model/incoming_webhook_test.go
  model/integration_action_test.go
  model/link_metadata_test.go
  model/preference_test.go
  model/push_notification_test.go
  model/team_member_test.go
  model/terms_of_service_test.go
  model/user_terms_of_Service_test.go
  model/user_test.go
  model/websocket_client_test.go
Labels: 2: Dev Review, release-note-none

#16958 [MM-32691] - Send email when the users are not able to join a workspace
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email.go
  app/email_test.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/client4.go
  model/cloud.go
Labels: 4: Reviews Complete, release-note

#17008 MM-33221 Merge GetSingleInclDeleted into GetSingle for PostStore
  app/integration_action.go
  app/integration_action_test.go
  app/plugin_hooks_test.go
  app/post.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/file_info_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note-none

#17012 Add missed translation for file indexing
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16998 Fixes error message when creator_id is not set
  api4/webhook_local.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#16997 Log intentionally unsent notifications as DEBUG
  app/notification.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17003 [MM-32348] services/bleve: only log update conf when there is an actual change
  services/searchengine/bleveengine/bleve.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#16979 [Partial Fix #16623]: Fix initialism errors in codebase.
  app/app_iface.go
  app/authorization.go
  app/channel.go
  app/channel_category.go
  app/email.go
  app/expirynotify_test.go
  app/export.go
  app/file.go
  app/file_bench_test.go
  app/file_test.go
  app/group.go
  app/import_functions.go
  app/import_test.go
  app/integration_action.go
  app/login.go
  app/notification_push.go
  app/notification_push_test.go
  app/oauth.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_commands_test.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_key_value_store.go
  app/plugin_test.go
  app/post.go
  app/post_test.go
  app/reaction.go
  app/session.go
  app/slashcommands/auto_posts.go
  app/user.go
  app/web_hub.go
  app/webhook.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16824 [GH-15906][MM-22844] Redesign welcome and verify email.
  .circleci/config.yml
  Makefile
  app/email.go
  build/release.mk
  i18n/en.json
  scripts/diff-email-templates.sh
  services/mailservice/mail.go
  templates/Makefile
  templates/deactivate_body.html
  templates/email_change_body.html
  templates/email_change_verify_body.html
  templates/invite_body.html
  templates/mfa_change_body.html
  templates/over_user_limit_30_days_body.html
  templates/over_user_limit_7_days_body.html
  templates/over_user_limit_90_days_body.html
  templates/over_user_limit_support_body.html
  templates/over_user_limit_workspace_suspended_body.html
  templates/partials/email_footer.mjml
  templates/partials/header.mjml
  templates/partials/header_verify.mjml
  templates/partials/logo.mjml
  templates/partials/questions_footer.mjml
  templates/partials/style.mjml
  templates/partials/verify.mjml
  templates/password_change_body.html
  templates/payment_failed_body.html
  templates/payment_failed_no_card_body.html
  templates/reached_user_limit_body.html
  templates/remove_expired_license.html
  templates/reset_body.html
  templates/signin_change_body.html
  templates/verify_body.html
  templates/verify_body.mjml
  templates/welcome_body.html
  templates/welcome_body.mjml
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16954 Replacing require.nil in web package
  web/context_test.go
  web/oauth_test.go
  web/response_writer_wrapper_test.go
  web/web_test.go
  web/webhook_test.go
Labels: 4: Reviews Complete, release-note-none

#15605 Add the API for search files
  api4/file.go
  api4/file_test.go
  app/app_iface.go
  app/file.go
  app/file_test.go
  app/migrations.go
  app/opentracing/opentracing_layer.go
  app/upload.go
  i18n/en.json
  model/client4.go
  model/config.go
  services/telemetry/telemetry.go
  testlib/store.go
Labels: 4: Reviews Complete, release-note

#17021 Update webapp build image
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#17004 [MM-32621] Remove app.waitForSidebarCategories
  app/channel_category.go
  app/team.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store_categories.go
  store/store.go
  store/storetest/channel_store_categories.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#16951 MM-32693: Use master when emoji_layer is invalidated
  app/emoji.go
  app/import_functions.go
  app/import_functions_test.go
  store/localcachelayer/emoji_layer.go
  store/localcachelayer/emoji_layer_test.go
  store/localcachelayer/layer.go
  store/localcachelayer/main_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/emoji_store.go
  store/store.go
  store/storetest/emoji_store.go
  store/storetest/mocks/EmojiStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#17031 [MM-33333] Fix GetSidebarCategories() failing on db replicas
  store/sqlstore/channel_store_categories.go
Labels: 2: Dev Review, 3: QA Review, release-note-none
