Repository mattermost/mattermost, pull requests merged in 2021-10, with the labels that each got.

#18390 [MM-36472] Fix inconsistencies in Roles columns
  db/migrations/bindata.go
  db/migrations/mysql/000003_alter_team_members_roles.down.sql
  db/migrations/mysql/000003_alter_team_members_roles.up.sql
  db/migrations/postgres/000003_alter_team_members_roles.down.sql
  db/migrations/postgres/000003_alter_team_members_roles.up.sql
  i18n/en.json
  model/channel_member.go
  model/session.go
  model/session_test.go
  model/team_member.go
  model/user.go
  model/user_test.go
  scripts/mattermost-mysql-6.0.sql
  scripts/mattermost-postgresql-6.0.sql
  store/sqlstore/channel_store.go
  store/sqlstore/session_store.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
Labels: 4: Reviews Complete, release-note

#18490 build: set 600 permission to config.json when packagin the app
  build/release.mk
Labels: 2: Dev Review, release-note-none

#18488 docker/build: push image to the testing repository
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#18524 [MM-39014] Execute update posts query first in 6.0 db schema migration
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#18530 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#18540 Remove searchEngine from App
  app/app.go
  app/options.go
  app/searchengine.go
Labels: 4: Reviews Complete, release-note-none

#18411 [GH-15744] Remove direct token store access in api4/user module
  api4/user.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18534 Translations update from Weblate (#18530)
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none

#18533 Translations update from Weblate (#18530)
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none

#18545 Translations update from Weblate
  i18n/pl.json
  i18n/sv.json
Labels: release-note-none

#18544 Pre-package Channel Export plugin v1.0.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18517 Migrate from gorp to sqlx in store/sqlstore/command_webhook_store.go
  store/sqlstore/command_webhook_store.go
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#18551 Automated cherry pick of #18545
  i18n/pl.json
  i18n/sv.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18550 Automated cherry pick of #18545
  i18n/pl.json
  i18n/sv.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18552 Automated cherry pick of #18544
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18553 Automated cherry pick of #18539
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18554 Automated cherry pick of #18544
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18542 Pre-package Playbooks v1.20.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup HA Cloud Test Server, release-note

#18555 Automated cherry pick of #18542
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18541 [MM-39072] - Run make build-templates on latest master
  app/email/email.go
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_ended_email.html
  templates/invite_body.html
  templates/invite_body.mjml
  templates/license_up_for_renewal.html
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: 2: Dev Review, QA Review Done, release-note-none, Setup Cloud + CWS Test Server

#18571 MM-38497: Fix Sentry crash in PostAction.Equals
  model/integration_action.go
  model/integration_action_test.go
Labels: 4: Reviews Complete, release-note-none

#18496 MM-38624 Migrate ChannelMemberHistoryStore to sqlx
  store/sqlstore/channel_member_history_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#18132 Turn focalboard plugin on by default
  config/diff_test.go
  model/config.go
  model/config_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#18599 Automated cherry pick of #18132
  config/diff_test.go
  model/config.go
  model/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18598 Automated cherry pick of #18405
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
