Repository mattermost/mattermost, pull requests merged in 2021-01, with the labels that each got.

#16610 [MM-31555] Print golang version on server startup
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#16532 Removed AppError from searchlayer/user_layer.go
  store/searchlayer/user_layer.go
  store/searchtest/user_layer.go
Labels: 2: Dev Review, AutoMerge, release-note-none

#16594 Automated cherry pick of #16576
  Makefile
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16612 [MM-31360] downgrade error logs which doesn't break the flow
  api4/channel.go
  api4/system.go
  api4/user.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/utils.go
  model/config.go
  model/file_info.go
  plugin/health_check.go
  services/awsmeter/awsmeter.go
  services/imageproxy/local.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  services/slackimport/slackimport.go
  services/telemetry/telemetry.go
  services/upgrader/upgrader_linux.go
  utils/i18n.go
  web/context.go
  web/handlers.go
  web/handlers_test.go
  web/oauth.go
  web/saml.go
Labels: 4: Reviews Complete, release-note-none

#16600 cherry-pick #16567: revert "Temporary fix for oauth on cloud beta"
  app/oauth.go
  web/handlers.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16314 Bump golang image
  .circleci/config.yml
  .gitlab-ci.yml
  .gitlab-ci/test.yml
  build/Jenkinsfile.branch
  build/README.md
  build/local-test-env.sh
Labels: 4: Reviews Complete, release-note

#16624 MM-31618: Bump golangci to 1.33.2
  .circleci/config.yml
  .gitlab-ci.yml
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR, release-note-none

#16593 Automated cherry pick of #16189
  api4/image.go
  api4/image_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16561 MM-31369: Fix racy test TestFileStoreWatcher
  config/file_test.go
Labels: 2: Dev Review, release-note-none

#16595 MM-30836: Use feature flags for RemoteClusterService
  app/server.go
  config/client.go
  model/feature_flags.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note-none

#16456 MM-30810 Remove special props from /me post
  app/slashcommands/command_me.go
  app/slashcommands/command_me_test.go
Labels: 4: Reviews Complete, release-note-none

#16575 Add check for empty src translation strings
  .circleci/config.yml
  Makefile
  go.tools.mod
  go.tools.sum
  i18n/en.json
Labels: release-note-none

#16451 MM-28861 Marketplace feature flags
  api4/apitestlib.go
  app/helper_test.go
  app/plugin.go
  model/feature_flags.go
  model/marketplace_plugin.go
  web/web_test.go
Labels: 4: Reviews Complete, release-note

#16634 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#16632 [MM-31572] downgrade some error logs for store package
  store/searchlayer/channel_layer.go
  store/searchlayer/post_layer.go
  store/searchlayer/user_layer.go
  store/sqlstore/integrity.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note-none

#16631 MM-31061: Remove pointers to slice
  app/file.go
  services/filesstore/filesstore.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/mocks/FileBackend.go
  services/filesstore/s3store.go
Labels: 4: Reviews Complete, release-note-none

#16562 MM-31370: Fix racy TestClusterShutdownRace
  app/server.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16645 MM-31744: Removes privacy policy text from repo, points to website.
  build/PRIVACY_POLICY.md
Labels: release-note-none

#16644 MM-31715: Flip ExperimentalGossip to be true by default
  model/config.go
  tests/test-config.json
Labels: 4: Reviews Complete, release-note

#16648 [MM-31776] explicitly call level functions for mlog
  web/context.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, CherryPick/Approved, Docs/Not Needed, release-note-none

#16651 Automated cherry pick of #16648
  web/context.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16642 Translations update from Weblate
  i18n/bg.json
  i18n/sv.json
Labels: 4: Reviews Complete, release-note

#16190 Add search engine support for files
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  i18n/en.json
  model/file_info_list.go
  model/file_info_search_results.go
  model/post.go
  model/search_params.go
  model/search_params_test.go
  services/searchengine/bleveengine/bleve.go
  services/searchengine/bleveengine/bleve_test.go
  services/searchengine/bleveengine/common.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  services/searchengine/bleveengine/search.go
  services/searchengine/interface.go
  services/searchengine/mocks/SearchEngineInterface.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/searchlayer/file_info_layer.go
  store/searchlayer/layer.go
  store/searchlayer/post_layer.go
  store/searchtest/file_info_layer.go
  store/searchtest/helper.go
  store/sqlstore/file_info_store.go
  store/sqlstore/file_info_store_test.go
  store/store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16643 MM-30892: Avoid unnecessary table scan in AnalyticsPostCount.
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note

#16559 MM-31336-update missing translation string
  app/oauth.go
  i18n/en.json
Labels: release-note-none

#16606 [MM-31289] Add some metrics for remote cluster service
  api4/remote_cluster.go
  app/server.go
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  i18n/en.json
  services/remotecluster/invitation.go
  services/remotecluster/mocks_test.go
  services/remotecluster/ping.go
  services/remotecluster/recv.go
  services/remotecluster/send.go
  services/remotecluster/service.go
Labels: 4: Reviews Complete, release-note-none

#16672 Translations update from Weblate
  i18n/bg.json
  i18n/es.json
  i18n/ko.json
  i18n/nl.json
  i18n/ro.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#16656 MM-31876: Fix racy test GetReplica
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16677 Temporary fix for OAuth on cloud
  web/handlers.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16679 Disable known issue with Api spec on cloud
  .circleci/config.yml
Labels: release-note-none

#16639 MM-31699 Don't downgrade plugins with feature flag for on-prem
  app/plugin.go
Labels: 4: Reviews Complete, release-note-none

#16681 Fix s3
  .circleci/config.yml
Labels: release-note-none

#16569 [MM-28000] Fix system manager can download export files without right permissions
  api4/apitestlib.go
  api4/job.go
  api4/job_test.go
  api4/user_test.go
  app/permissions_migrations.go
  i18n/en.json
  model/migration.go
  model/permission.go
  model/role.go
  testlib/store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16669 Update en.json to fix a typo
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#16598 MM-30338 Add feature flag for collapsedthreads
  api4/user_test.go
  app/notification.go
  model/feature_flags.go
Labels: release-note

#16685 Fix go.mod to give priority to go mod tidy
  Makefile
  go.mod
Labels: 4: Reviews Complete, release-note-none

#14682 [GH-14493] Accept any GOOS and GOARCH combination in manifest
  model/manifest.go
  model/manifest_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#16687 hotfix-threads-migrate
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#16688 hotfix-cherrypick-release-5.31
  store/sqlstore/upgrade.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#16689 hotfix-cherrypick-cloud-upgrade
  store/sqlstore/upgrade.go
Labels: release-note-none

#16661 MM-31882 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete, release-note-none

#16616 MM-30362: Cypress/E2E: LDAP-SAML Sync
  build/docker/keycloak/keycloak.crt
  build/docker/keycloak/keycloak_cert.pem
  build/docker/keycloak/realm.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#16693 MM-31992: Remove some unnecessary words from the unused linter
  .golangci.yml
Labels: 4: Reviews Complete, release-note-none

#16503 MM-29988 - Update exising Post APIs with collapsed threads
  api4/commands_test.go
  api4/post.go
  api4/post_test.go
  api4/team_test.go
  app/app_iface.go
  app/file.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/post.go
  app/post_test.go
  config/client.go
  model/client4.go
  model/post.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#16694 migration hotfix
  store/sqlstore/upgrade.go
Labels: release-note-none

#16695 Hardcode mmctl version
  scripts/download_mmctl_release.sh
Labels: release-note-none

#16698 Release 5.29 hotfix upgrade
  store/sqlstore/upgrade.go
Labels: release-note-none

#16697 migration hotfix
  store/sqlstore/upgrade.go
Labels: release-note-none

#16638 MM-28519 Shared channel sync service
  api4/post_test.go
  api4/remote_cluster.go
  app/app_iface.go
  app/channel_share.go
  app/opentracing/opentracing_layer.go
  app/remote_cluster.go
  app/server.go
  app/slashcommands/command_remote.go
  app/slashcommands/command_share.go
  app/slashcommands/util.go
  i18n/en.json
  mlog/levels.go
  model/auditconv.go
  model/channel_shared.go
  model/channel_shared_test.go
  model/post_list.go
  model/remote_cluster.go
  model/remote_cluster_test.go
  model/utils.go
  model/utils_test.go
  services/remotecluster/error.go
  services/remotecluster/invitation.go
  services/remotecluster/mocks_test.go
  services/remotecluster/ping.go
  services/remotecluster/ping_test.go
  services/remotecluster/recv.go
  services/remotecluster/response.go
  services/remotecluster/send.go
  services/remotecluster/send_test.go
  services/remotecluster/service.go
  services/remotecluster/service_test.go
  services/sharedchannel/channelinvite.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_shared_channels.go
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/shared_channel_store_test.go
  store/sqlstore/store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/RemoteClusterStore.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/mocks/Store.go
  store/storetest/remote_cluster_store.go
  store/storetest/shared_channel_store.go
  store/storetest/store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16629 [MM-31573] update log levels for the app package
  app/app.go
  app/bot.go
  app/channel.go
  app/cluster_discovery.go
  app/command.go
  app/config.go
  app/emoji.go
  app/file.go
  app/import_functions.go
  app/integration_action.go
  app/ldap.go
  app/license.go
  app/notification.go
  app/notification_email.go
  app/notification_email_test.go
  app/notification_push.go
  app/oauth.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_key_value_store.go
  app/plugin_signature.go
  app/post.go
  app/product_notices.go
  app/ratelimit.go
  app/server.go
  app/server_test.go
  app/session.go
  app/status.go
  app/team.go
  app/upload.go
  app/user.go
  app/web_conn.go
  app/websocket_router.go
Labels: 2: Dev Review, release-note-none

#16581 MM-31492 - fix error message
  app/oauth.go
Labels: 4: Reviews Complete, release-note-none

#16696 Expands release note instructions.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#16744 Bump up Go docker image to 1.15.5
  build/Dockerfile.buildenv
Labels: 4: Reviews Complete, release-note

#16745 upgrade fix
  store/sqlstore/upgrade.go
Labels: release-note

#16529 [MM-30851] Replace ExperimentalChannelSidebarOrganization with EnableLegacySidebar
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#16702 Add make command for running the app in an HA topology
  Makefile
  build/docker/nginx/default.conf
  docker-compose.yaml
Labels: 4: Reviews Complete, release-note-none

#16692 MM-30314 Don't delete all SidebarChannels when removed from team
  store/sqlstore/channel_store_categories.go
  store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, release-note

#16663 MM-31710 Server/API: change total_unread_replies to total_unread_threads
  api4/user_test.go
  model/thread.go
  store/sqlstore/thread_store.go
Labels: 2: Dev Review, release-note

#16447 After OAUTH, SAML auth completion, Redirect to App custom url scheme with token data as query params.
  i18n/en.json
  model/config.go
  utils/api.go
  utils/utils.go
  utils/utils_test.go
  web/oauth.go
  web/saml.go
Labels: 4: Reviews Complete

#16675 MM-31433/shared channel sync notifier
  app/channel.go
  app/helper_test.go
  app/notification.go
  app/post_test.go
  app/reaction_test.go
  app/server.go
  app/shared_channel_notifier.go
  app/shared_channel_notifier_test.go
  app/shared_channel_service_iface.go
  app/web_hub.go
  services/sharedchannel/service.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#16618 MM-24530-Add support for search terms with underscore using postgresql engine
  api4/post_test.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16751 Translations update from Weblate
  i18n/bg.json
  i18n/ja.json
  i18n/nl.json
  i18n/ro.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#16649 docker: prometheus and grafana for development
  Makefile
  build/docker-compose-generator/main.go
  build/docker-compose.common.yml
  build/docker-compose.yml
  build/docker/grafana/dashboards/README.md
  build/docker/grafana/dashboards/home.json
  build/docker/grafana/dashboards/mattermost/mattermost-performance-kpi-metrics_rev2.json
  build/docker/grafana/dashboards/mattermost/mattermost-performance-monitoring-bonus-metrics_rev2.json
  build/docker/grafana/dashboards/mattermost/mattermost-performance-monitoring_rev2.json
  build/docker/grafana/grafana.ini
  build/docker/grafana/provisioning/dashboards/mattermost.yaml
  build/docker/grafana/provisioning/datasources/prometheus.yml
  build/docker/prometheus-linux.yml
  build/docker/prometheus.yml
  config.mk
  docker-compose.makefile.yml
  docker-compose.yaml
Labels: 4: Reviews Complete, release-note-none

#16668 [MM-31277]: Change default MaxFileSize from 50Mb to 100Mb
  model/config.go
  model/utils.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#16746 MM-31596: Support permalink in shared channels
  go.tools.mod
  go.tools.sum
  i18n/en.json
  mlog/levels.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/mock_ServerIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16673 [MM-30808] - Switch creation of users to use app method vs client method
  app/slashcommands/auto_constants.go
  app/slashcommands/auto_users.go
  app/slashcommands/command_loadtest.go
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#16611 [MM-31404] api4/config: return error when patching PluginSettings.EnableUploads
  api4/config.go
  api4/config_local.go
  api4/config_test.go
  i18n/en.json
Labels: 4: Reviews Complete, Setup Old Test Server, release-note-none

#16654 MM-31875 soft delete reactions
  i18n/en.json
  model/reaction.go
  model/reaction_test.go
  store/localcachelayer/channel_layer_test.go
  store/localcachelayer/reaction_layer_test.go
  store/sqlstore/reaction_store.go
  store/sqlstore/reaction_store_test.go
  store/sqlstore/upgrade.go
  store/storetest/reaction_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#16760 Remove local imports from golangci
  .golangci.yml
Labels: 4: Reviews Complete, release-note-none

#16753 MM-32033: Check if a remote is already added before inviting
  app/app_iface.go
  app/channel_share.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_share.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/shared_channel_store.go
  store/store.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16747 [MM-31112] - Update license renewal email
  api4/license.go
  app/email.go
  app/license.go
  app/server.go
  i18n/en.json
  i18n/es.json
  i18n/uk.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note-none

#16650 Job metrics & dynamic Grafana annotations
  app/server.go
  build/docker/grafana/dashboards/mattermost/mattermost-performance-monitoring_rev2.json
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  jobs/jobs.go
  jobs/jobs_test.go
  jobs/server.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16755 MM-32034: Auto share a channel if not shared
  app/app_iface.go
  app/channel_share.go
  app/opentracing/opentracing_layer.go
  app/slashcommands/command_share.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/shared_channel_store.go
  store/store.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16763 MM-31721: Fix Cache-Control directives
  api4/bot.go
  api4/compliance.go
  api4/emoji.go
  api4/file.go
  api4/post.go
  api4/team.go
  api4/user.go
  web/oauth.go
Labels: 4: Reviews Complete, release-note

#16766 cherry-pick#31112: Update license renewal email
  api4/license.go
  app/email.go
  app/license.go
  app/server.go
  i18n/en.json
  i18n/es.json
  i18n/uk.json
Labels: release-note-none

#16768 Add unique constraint on remote cluster site id, in order to prevent …
  app/remote_cluster.go
  app/remote_cluster_test.go
  i18n/en.json
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/store.go
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, release-note-none

#16770 MM-32013: Do not allow password change in /auth endpoint
  api4/user.go
  app/user.go
  i18n/en.json
  model/user.go
Labels: 4: Reviews Complete, release-note

#16767 Update README.md
  README.md
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16776 MM-31353: Fix incorrect time truncation logic
  app/product_notices.go
Labels: 4: Reviews Complete, release-note

#16757 MM-32027 - Marking a thread as unread not possible or marks all threads as unread.
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, release-note

#16780 MM-32248 streamline serialization auto-generation
  Makefile
  model/serialized_gen.go
  model/session.go
  model/session_serial_gen.go
  model/team_member.go
  model/team_member_serial_gen.go
  model/user.go
  model/user_serial_gen.go
  model/utils.go
Labels: 2: Dev Review, release-note-none

#16633 [MM-31249] Add /exports API endpoint
  api4/api.go
  api4/export.go
  api4/export_local.go
  api4/export_test.go
  app/app_iface.go
  app/export.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/client4.go
  web/params.go
Labels: release-note-none

#16626 [MM-31597] Implement export process job
  api4/api.go
  api4/export.go
  api4/export_local.go
  api4/export_test.go
  app/app.go
  app/app_iface.go
  app/enterprise.go
  app/export.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  imports/placeholder.go
  jobs/export_process/worker.go
  jobs/import_process/worker.go
  jobs/interfaces/export_process_interface.go
  jobs/jobs_watcher.go
  jobs/server.go
  jobs/workers.go
  model/client4.go
  model/config.go
  model/config_test.go
  model/job.go
  web/params.go
Labels: release-note-none

#16588 [MM-28423] Implement ImportDelete job
  app/app.go
  app/app_iface.go
  app/enterprise.go
  app/file.go
  app/import.go
  app/opentracing/opentracing_layer.go
  app/upload.go
  i18n/en.json
  imports/placeholder.go
  jobs/import_delete/scheduler.go
  jobs/import_delete/worker.go
  jobs/interfaces/import_delete_interface.go
  jobs/jobs_watcher.go
  jobs/schedulers.go
  jobs/server.go
  jobs/workers.go
  model/job.go
  services/filesstore/filesstore.go
  services/filesstore/filesstore_test.go
  services/filesstore/localstore.go
  services/filesstore/mocks/FileBackend.go
  services/filesstore/s3store.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16772 Send websocket notification when shared channel state changes
  app/helper_test.go
  app/post_test.go
  app/reaction_test.go
  app/server.go
  app/shared_channel_notifier_test.go
  app/shared_channel_service_iface.go
  app/slashcommands/command_share.go
  app/slashcommands/command_share_test.go
  app/slashcommands/helper_test.go
  testlib/cluster.go
Labels: 4: Reviews Complete, release-note-none

#16773 When inviting a remote send over the home channel type
  app/shared_channel_service_iface.go
  app/slashcommands/command_share.go
  services/sharedchannel/channelinvite.go
Labels: release-note-none

#16785 Enable govet check for empty strings
  Makefile
  web/saml.go
Labels: 4: Reviews Complete, release-note-none

#16788 Translations update from Weblate
  i18n/bg.json
  i18n/es.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#16782 MM-32252 Ignore serverversion condition on cloud for in-product notices
  app/product_notices.go
  app/product_notices_test.go
Labels: 2: Dev Review, CherryPick/Approved, release-note

#16790 Automated cherry pick of #16782
  app/product_notices.go
  app/product_notices_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16784 storetest/channel_store: update a stop word
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#16652 [MM-0] - fix return wrapped error when net.Listen returns error
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#15953 [MM15037] Stop sending notifications to user whose Oauth bot posted
  app/notification.go
  app/notification_test.go
  model/post.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note

#16302 Update Bundled plugin packages for v5.32
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#16779 Update version.go
  model/version.go
Labels: 4: Reviews Complete, release-note-none

#16700 MM-32018 update URL endpoint for DownloadComplianceReport function
  model/client4.go
Labels: 2: Dev Review, 3: QA Review, release-note

#16103 15249 sync.pool
  app/oauth.go
  app/plugin_requests.go
  app/session.go
  app/web_conn.go
  services/cache/lru.go
  services/cache/lru_test.go
  web/handlers.go
  wsapi/websocket_handler.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none

#16792 MM-31391: Add max connection idle timeout to config
  go.tools.mod
  go.tools.sum
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/storetest/settings.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#16701 MM-31993: Add flag to disable gossip compression
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#16809 Lock CI from cloud/release-5.32
  .circleci/config.yml
  .gitlab-ci.yml
  model/version.go
  scripts/download_mmctl_release.sh
Labels: release-note-none

#16813 Bump version
  build/Dockerfile
Labels: AutoMerge, release-note-none

#16814 Automated cherry pick of #16302
  Makefile
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#16659 MM-31713 Server/API: GetUserThread method
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  i18n/en.json
  model/client4.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, release-note

#16805 [MM-32234] Fix config.json getting reset
  api4/apitestlib.go
  api4/config_test.go
  app/config.go
  app/options.go
  app/server.go
  app/server_test.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/server.go
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/migrate.go
  config/migrate_test.go
  config/store.go
  config/store_test.go
  services/mailservice/mail_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note

#16825 Bump up minimum required Go version
  Makefile
Labels: 4: Reviews Complete, release-note-none

#16821 Cherrypick for MM-32234 on 5.31
  api4/apitestlib.go
  api4/config_test.go
  app/config.go
  app/options.go
  app/server.go
  app/server_test.go
  cmd/mattermost/commands/config.go
  cmd/mattermost/commands/config_test.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/plugin.go
  cmd/mattermost/commands/plugin_test.go
  cmd/mattermost/commands/server.go
  config/common_test.go
  config/database_test.go
  config/file_test.go
  config/migrate.go
  config/migrate_test.go
  config/store.go
  config/store_test.go
  services/mailservice/mail_test.go
Labels: release-note

#16783 MM-31709 Store posts/reactions for remote clusters
  app/post.go
  app/server.go
  go.tools.mod
  go.tools.sum
  model/channel_shared.go
  model/license.go
  model/post.go
  model/reaction.go
  model/user.go
  model/user_serial_gen.go
  services/remotecluster/response.go
  services/remotecluster/response_test.go
  services/remotecluster/send.go
  services/remotecluster/service.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/msg.go
  services/sharedchannel/service.go
  services/sharedchannel/sync_recv.go
  services/sharedchannel/sync_send.go
  store/errors.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/reaction_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/ReactionStore.go
  store/storetest/mocks/SharedChannelStore.go
  store/storetest/reaction_store.go
  store/storetest/shared_channel_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#16543 [MM-30292] Don't include prepackaged plugin into Marketplace response for cloud
  api4/plugin_test.go
  app/plugin.go
Labels: 4: Reviews Complete, release-note-none

#16660 MM-31712 Server/API: Unreads-only filter for GetUserThreads
  api4/user.go
  api4/user_test.go
  model/client4.go
  model/thread.go
  store/sqlstore/thread_store.go
Labels: 2: Dev Review, release-note

#16748 MM-31711 - Implement cursor paging for threads
  api4/user.go
  api4/user_test.go
  i18n/en.json
  model/client4.go
  model/thread.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, release-note
