Repository mattermost/mattermost, pull requests merged in 2021-11, with the labels that each got.

#18907 Lock CI for release-6.1
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#18912 Automated cherry pick of #18860
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18913 Automated cherry pick of #18855
  api4/config.go
  api4/config_local.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18915 Automated cherry pick of #18835
  api4/post.go
  api4/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18914 Automated cherry pick of #18840
  app/web_conn.go
  app/web_conn_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18922 Automated cherry pick of #18855
  api4/config.go
  api4/config_local.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18925 [MM-39597] Cherry-pick to 5.39
  api4/config.go
  api4/config_local.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#18862 [MM-39448] Remove command arguments from auditCommandArgs
  model/auditconv.go
  model/auditconv_test.go
Labels: 4: Reviews Complete, release-note-none

#18929 Automated cherry pick of #18862
  model/auditconv.go
  model/auditconv_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18920 Use the correct error variable from provider.GetSSOSettings
  app/oauth.go
  app/oauth_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#18930 Revert "DOPS-602: Change how mmctl gets packaged and locally fetched. "
  .circleci/config.yml
  build/release.mk
  scripts/mmctl-dev.sh
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#18928 Automated cherry pick of #18862
  model/auditconv.go
  model/auditconv_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18931 Automated cherry pick of #18920
  app/oauth.go
  app/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18932 Automated cherry pick of #18920
  app/oauth.go
  app/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18933 Automated cherry pick of #18920
  app/oauth.go
  app/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18924 db: upgrade db for 6.1 on the release 6.1 branch
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#18923 db: upgrade db to 6.0 and prepare for 6.1
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note

#18908 Remove job server dependency searchengine
  app/server.go
  services/searchengine/bleveengine/bleve.go
  services/searchengine/bleveengine/bleve_test.go
  services/searchengine/bleveengine/indexer/indexing_job_test.go
  services/searchengine/searchengine.go
  services/telemetry/telemetry_test.go
  store/searchlayer/layer_test.go
  testlib/helper.go
Labels: 4: Reviews Complete, release-note-none

#18927 Fix PluginHealthCheckJob
  app/plugin.go
  app/server.go
  plugin/environment.go
Labels: 4: Reviews Complete, release-note-none

#18939 Automated cherry pick of #18911 on release-6.1
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#18902 [MM-39503] - Remove DownloadApps Feature Flag
  model/feature_flags.go
Labels: 2: Dev Review, release-note

#18826 MM-39420: Checks for presence of slice before index access.
  app/notification.go
  app/post.go
Labels: Work In Progress, release-note

#18937 Ordering clarifications
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#18944 Automated cherry pick of #18826
  app/notification.go
  app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18921 MM-39804 - Remove license expiration checks for cloud
  app/server.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#18946 Automated cherry pick of #18921
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18943 Automated cherry pick of #18826
  app/notification.go
  app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18947 Automated cherry pick of #18826
  app/notification.go
  app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18948 Revert "Ordering clarifications"
  app/server.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18935 MM-39314: Pre-package Playbooks 1.21.0
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#18952 Automated cherry pick of #18935
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18953 Automated cherry pick of #18935
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18802 Remove DND run debug log
  app/status.go
Labels: 4: Reviews Complete, release-note-none

#18887 [MM-39630] - Migrate from gorp to sqlx in store/sqlstore/tokens_store.go
  store/sqlstore/tokens_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#18936 Add JobSettings.CleanupJobsThresholdDays to telemetry
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note-none

#18938 Move plugins under Channels
  app/app.go
  app/app_iface.go
  app/channels.go
  app/cluster_handlers.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_event.go
  app/plugin_install.go
  app/plugin_requests.go
  app/plugin_shutdown_test.go
  app/plugin_signature.go
  app/plugin_statuses.go
  app/plugin_test.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#16988 MM-32396 Create endpoint for listing all the roles
  api4/role.go
  api4/role_local.go
  api4/role_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/role.go
  app/role_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, release-note

#18962 Automated cherry pick of #18961 on release-6.1
  i18n/de.json
  i18n/hu.json
  i18n/ja.json
Labels: release-note-none

#18963 Automated cherry pick of #18961 on cloud
  i18n/de.json
  i18n/hu.json
  i18n/ja.json
Labels: release-note-none

#18964 Ordering clarifications
  app/server.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18978 update client function to match the new format and fix bad merge
  model/client4.go
Labels: release-note-none

#18967 [MM-39820] Add AppBarEnabled feature flag
  model/feature_flags.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#18971 MM-40003 Fix patch route for Town Square
  api4/channel.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#18980 Automated cherry pick of #18971
  api4/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18973 prepackage boards to 0.10.0
  Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note

#18981 Automated cherry pick of #18973
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18888 [MM-39639] - Migrate from gorp to sqlx in store/sqlstore/user_access_token_store.go
  store/sqlstore/user_access_token_store.go
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#18801 GH-18288: Allow configuring unsafe-eval and unsafe-inline
  model/config.go
  services/telemetry/telemetry.go
  web/handlers.go
  web/handlers_test.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#18974 Move pluginCommands into Channels
  api4/plugin.go
  api4/plugin_test.go
  app/app.go
  app/app_iface.go
  app/channels.go
  app/integration_action.go
  app/notification_push_test.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_commands_test.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_requests.go
  app/plugin_requests_test.go
  app/plugin_test.go
  app/server.go
  web/web_test.go
Labels: 4: Reviews Complete, release-note-none

#18976 [MM-40022] - Expose telemetry service in the server
  app/telemetry.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 2: Dev Review, release-note-none

#18987 Mm 38799 invite to team
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#18979 [MM-39374] Remove DesktopLatestVersion and DesktopMinVersion
  api4/system.go
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
  tests/test-config.json
Labels: 4: Reviews Complete, release-note

#18989 Use the correct error variable from provider.GetSSOSettings (#18920)
  app/oauth.go
  app/oauth_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#18347 MM-36687 CRT push notifications
  api4/system.go
  api4/system_test.go
  api4/user.go
  app/app_iface.go
  app/channel.go
  app/notification.go
  app/notification_email.go
  app/notification_push.go
  app/notification_push_test.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/push_notification.go
Labels: release-note-none

#18793 MM-38508 CRT: DM notification missing the sender name
  app/notification_push.go
  app/notification_push_test.go
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done

#18968 [MM-39504] - Remove Prewritten Messages Feature Flag
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#18891 [MM-39642] - Migrate from gorp to sqlx in store/sqlstore/session_store.go
  store/sqlstore/session_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#18892 [MM-39644] - Migrate from gorp to sqlx in store/sqlstore/upload_session_store.go
  store/sqlstore/upload_session_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#18894 [MM-39060] - A/B Test: Reminder to Join Workspace email
  api4/team.go
  api4/team_local.go
  app/app_iface.go
  app/email/email.go
  app/email/email_test.go
  app/email_test.go
  app/opentracing/opentracing_layer.go
  app/team.go
  i18n/en.json
  jobs/resend_invitation_email/worker.go
  model/feature_flags.go
  model/team_member.go
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#18897 [MM-39638] - Migrate from gorp to sqlx in store/sqlstore/status_store.go
  store/sqlstore/status_store.go
Labels: 4: Reviews Complete, Hacktoberfest, Lifecycle/1:stale, hacktoberfest-accepted, release-note-none, Contributor

#18896 [MM-39641] Migrate Webhook store to sqlx
  store/sqlstore/webhook_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#18898 [MM-39637] - Migrate from gorp to sqlx in store/sqlstore/shared_channel_store.go
  store/sqlstore/shared_channel_store.go
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#18958 [MM-39851] Add CRUD methods for user sessions to plugin API
  app/plugin_api.go
  app/session.go
  i18n/en.json
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 4: Reviews Complete, release-note

#18982 MM-39612: Make acquiring and removing connections atomic
  api4/apitestlib.go
  api4/websocket_test.go
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
  app/websocket_router.go
  model/websocket_client.go
Labels: 4: Reviews Complete, release-note-none

#19003 Automated cherry pick of #18894
  api4/team.go
  api4/team_local.go
  app/app_iface.go
  app/email/email.go
  app/email/email_test.go
  app/email_test.go
  app/opentracing/opentracing_layer.go
  app/team.go
  i18n/en.json
  jobs/resend_invitation_email/worker.go
  model/feature_flags.go
  model/team_member.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19005 Automated cherry pick of #18958
  app/plugin_api.go
  app/session.go
  i18n/en.json
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19004 Automated cherry pick of #18982
  api4/apitestlib.go
  api4/websocket_test.go
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
  app/websocket_router.go
  model/websocket_client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19009 Automated cherry pick of #19001 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#18966 MM-39341: Sentry crash: nil dereference in *User.ClearNonProfileFields
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, release-note-none

#18934 Add remaining CRT migrations
  db/migrations/bindata.go
  db/migrations/mysql/000054_create_crt_channelmembership_count.down.sql
  db/migrations/mysql/000054_create_crt_channelmembership_count.up.sql
  db/migrations/mysql/000055_create_crt_thread_count_and_unreads.down.sql
  db/migrations/mysql/000055_create_crt_thread_count_and_unreads.up.sql
  db/migrations/postgres/000054_create_crt_channelmembership_count.down.sql
  db/migrations/postgres/000054_create_crt_channelmembership_count.up.sql
  db/migrations/postgres/000055_create_crt_thread_count_and_unreads.down.sql
  db/migrations/postgres/000055_create_crt_thread_count_and_unreads.up.sql
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note-none

#19015 Automated cherry pick of #18966
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18977 [MM-40016] Implement deep copy method for model.WebSocketEvent
  app/post.go
  app/post_test.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 4: Reviews Complete, release-note

#19026 Automated cherry pick of #18977
  app/post.go
  app/post_test.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#18951 MM-39634: Migrated gorp to sqlx
  store/sqlstore/terms_of_service_store.go
Labels: 4: Reviews Complete, release-note, Contributor

#18949 MM-39632: Migrate from using gorp to sqlx
  store/sqlstore/user_terms_of_service.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#18996 Update version to 5.39.3
  model/version.go
Labels: release-note-none

#19034 Automated cherry pick of #19032 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, release-note-none

#18945 MM-39635: Migrate gorp to sqlx #18873
  store/sqlstore/remote_cluster_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note, Contributor

#18998 Update version to 5.37.5
  model/version.go
Labels: release-note-none

#18999 Update version to 6.1.1
  model/version.go
Labels: release-note-none

#18997 Update version to 5.38.5
  model/version.go
Labels: release-note-none

#18995 Update version to 6.0.4
  model/version.go
Labels: release-note-none

#19013 [MM-37013] Better post filtering for job
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note-none

#19038 Automated cherry pick of #19020
  web/oauth.go
  web/oauth_test.go
  web/saml.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19018 Change default log rotation size to 100MB
  config/logger.go
Labels: 4: Reviews Complete, release-note

#19010 Move enterprise features under Channels
  app/app.go
  app/channels.go
  app/config.go
  app/enterprise.go
  app/enterprise_test.go
  app/server.go
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#19046 [MM-40342] Fix panic in Mattermost Server for cloud installations
  jobs/resend_invitation_email/worker.go
Labels: 2: Dev Review, CherryPick/Candidate, Setup Cloud Test Server, kind/bug, release-note-none

#19048 Automated cherry pick of #19046
  jobs/resend_invitation_email/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19014 Take view archived config into account on users and posts api endpoints
  api4/post.go
  api4/post_test.go
  api4/user.go
  api4/user_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#19052 Lock CI from /release-6.2
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#19055 Automated cherry pick of #19020
  web/oauth.go
  web/oauth_test.go
  web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19057 Automated cherry pick of #19046
  jobs/resend_invitation_email/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19056 Automated cherry pick of #19018
  config/logger.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19085 upgrade db to 6.2.0
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#19087 Automated cherry pick of #19085
  store/sqlstore/upgrade.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19086 Prepare db for 6.3
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#18942 [MM-38239 & MM-39788] Recent files causing crash
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  i18n/en.json
  model/client4.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#19098 Automated cherry pick of #18942
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  i18n/en.json
  model/client4.go
  store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#18505 [GH-18306] Make getPrepackaged resilient to missing plugin icons
  app/plugin.go
Labels: 4: Reviews Complete, Hacktoberfest, Lifecycle/frozen, hacktoberfest-accepted, release-note-none, Contributor

#19103 MM-39433: Fixes (*App).getEmbedsAndImages parameter.
  app/post_metadata.go
Labels: 2: Dev Review, CherryPick/Candidate, release-note

#19106 Automated cherry pick of #19102 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
Labels: release-note-none

#19097 Do not parse developer flags if empty
  web/handlers.go
  web/handlers_test.go
Labels: 4: Reviews Complete, release-note-none

#19049 [MM-40345] - Fix telemetry in resend invite email job
  jobs/resend_invitation_email/worker.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none
