Repository mattermost/mattermost, pull requests merged in 2021-06, with the labels that each got.

#17691 Translations update from Weblate
  i18n/bg.json
  i18n/fr.json
  i18n/hu.json
Labels: release-note-none

#17675 Making default pdf extracting more robust
  services/docextractor/pdf.go
  services/docextractor/pdf_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17668 conceptual user service: initial commit
  app/app_iface.go
  app/authentication.go
  app/channel_test.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/user.go
  app/user_test.go
  i18n/en.json
  model/user.go
  services/users/constants.go
  services/users/errors.go
  services/users/helper_test.go
  services/users/main_test.go
  services/users/password.go
  services/users/password_test.go
  services/users/users.go
  services/users/users_test.go
  services/users/utils.go
  utils/password.go
  web/webhook_test.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17695 Fix some semgrep issues
  app/email_batching_test.go
  app/plugin_requests.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17682 Adding the focalboard plugin feature flag
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#17686 Adds focalboard v0.6.7 as a prepackaged plugin
  Makefile
Labels: CherryPick/Approved, release-note

#17703 hotfix: user import issue where the user roles were overwritten for the import path
  services/users/users.go
Labels: 4: Reviews Complete, release-note-none

#17687 db: upgrade db to 5.36
  model/version.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, release-note

#17697 [MM-30980] Avoid modifying original post when sending a notification
  app/notification_push.go
  app/notification_push_test.go
Labels: QA Deferred, release-note

#17660 Change about and help links back to default redirects
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#17711 Lock CI for release-5.36
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#17712 [MM-31624] cmd: remove platform binary
  Makefile
  build/release.mk
  cmd/mattermost/commands/root.go
  cmd/mattermost/commands/server.go
  cmd/mattermost/commands/server_test.go
  cmd/platform/main.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note

#17709 DB driver: Add wrapper structs for low-level objects
  shared/driver/conn.go
  shared/driver/objects.go
Labels: 4: Reviews Complete, release-note-none

#17716 Bump version
  build/Dockerfile
Labels: AutoMerge, release-note-none

#17720 Upgrade version to 5.36.0
  model/version.go
Labels: 4: Reviews Complete, release-note-none

#17713 Bump to 5.35.3
  model/version.go
Labels: release-note-none

#17723 [MM-36236] Fix nil map assignment crash
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Tests Not Required, release-note

#17724 Automated cherry pick of #17723
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17725 Automated cherry pick of #17723
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17726 Automated cherry pick of #17723
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17714 Bump to 5.34.4
  model/version.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17715 Bump to 5.33.5
  model/version.go
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17702 [MM-29241] Image logic refactor
  app/bot.go
  app/brand.go
  app/file.go
  app/image.go
  app/imaging/decode.go
  app/imaging/decode_bench_test.go
  app/imaging/decode_test.go
  app/imaging/encode.go
  app/imaging/encode_test.go
  app/imaging/orientation.go
  app/imaging/preview.go
  app/imaging/svg.go
  app/imaging/svg_test.go
  app/imaging/utils.go
  app/imaging/utils_bench_test.go
  app/imaging/utils_test.go
  app/server.go
  app/slack.go
  app/team.go
  app/upload.go
  app/user.go
  i18n/en.json
  model/file_info.go
  services/slackimport/slackimport.go
  tests/fill_test_16bit_rgb.png
  tests/fill_test_16bit_rgb_out.png
  tests/fill_test_16bit_rgba.png
  tests/fill_test_16bit_rgba_out.png
  tests/fill_test_8bit_palette.png
  tests/fill_test_8bit_palette_out.png
  tests/fill_test_8bit_rgb.png
  tests/fill_test_8bit_rgb_out.png
  tests/fill_test_8bit_rgba.png
  tests/fill_test_8bit_rgba_out.png
  tests/fill_test_opaque.png
Labels: 4: Reviews Complete, release-note

#17330 Remove direct store calls from api4/system_local.go
  api4/system_local.go
  app/app.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17706 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#17719 [MM-36198] - Activating a user in System Console does not respect cloud user limits
  api4/cloud.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/cloud.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#17742 Automated cherry pick of #17719
  api4/cloud.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/cloud.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17717 MM-35805: following a thread should also mark it as read
  api4/user_test.go
  app/user.go
Labels: 4: Reviews Complete, release-note-none

#17722 [MM-36217] Improve column default utilities
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17710 [MM-29901] Remove redundant indexes
  db/migrations/bindata.go
  db/migrations/mysql/000001_create_teams.up.sql
  db/migrations/mysql/000002_create_team_members.up.sql
  db/migrations/postgres/000001_create_teams.down.sql
  db/migrations/postgres/000001_create_teams.up.sql
  db/migrations/postgres/000002_create_team_members.down.sql
  db/migrations/postgres/000002_create_team_members.up.sql
  store/sqlstore/channel_store.go
  store/sqlstore/emoji_store.go
  store/sqlstore/oauth_store.go
  store/sqlstore/post_store.go
  store/sqlstore/preference_store.go
  store/sqlstore/product_notices_store.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/status_store.go
  store/sqlstore/store_test.go
  store/sqlstore/upgrade.go
  store/sqlstore/user_access_token_store.go
  store/sqlstore/user_store.go
  store/sqlstore/user_terms_of_service.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#17751 Automated cherry pick of #17697
  app/notification_push.go
  app/notification_push_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17745 Pre-package Incident Collaboration v1.12.0
  Makefile
  model/feature_flags.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#17753 Automated cherry pick of #17745
  Makefile
  model/feature_flags.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17598 [MM-27622] Publish messages as SystemBot when a user is required
  api4/channel_local.go
  api4/channel_test.go
  app/app.go
  app/app_iface.go
  app/bot.go
  app/bot_test.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/bot.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#17659 MM-31612 Optimize bulk import process by avoiding writing zip to disk
  app/app_iface.go
  app/export_test.go
  app/import.go
  app/import_functions.go
  app/import_functions_test.go
  app/import_test.go
  app/import_types.go
  app/opentracing/opentracing_layer.go
  cmd/mattermost/commands/import.go
  cmd/mattermost/commands/sampledata.go
  i18n/en.json
  jobs/import_process/worker.go
Labels: 3: QA Review, release-note

#17683 MM-36054: send reply_count with following ws event
  api4/user_test.go
  app/user.go
Labels: 4: Reviews Complete, release-note-none

#17743 Mattermost Server OAuth Flow Cross-Site Scripting
  web/oauth.go
  web/saml.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#17757 Automated cherry pick of #17743
  web/oauth.go
  web/saml.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17758 Automated cherry pick of #17743
  web/oauth.go
  web/saml.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17760 Automated cherry pick of #17743
  web/oauth.go
  web/saml.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17761 Automated cherry pick of #17743
  web/oauth.go
  web/saml.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17759 Automated cherry pick of #17743
  web/oauth.go
  web/saml.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17746 MM-35538 - display purchase modal when coming from email
  app/email.go
Labels: QA Deferred, release-note-none

#17769 Bump to 5.33.6
  model/version.go
Labels: release-note-none

#17768 Bump to 5.34.5
  model/version.go
Labels: release-note-none

#17770 Bump to 5.31.7
  model/version.go
Labels: release-note-none

#17359 MM-34434: Trial license flag
  api4/license_test.go
  model/client4.go
  model/license.go
  model/license_test.go
Labels: 3: QA Review, release-note-none

#17756 Lock CI for release-6.0
  .circleci/config.yml
  .gitlab-ci.yml
  scripts/download_mmctl_release.sh
Labels: release-note-none

#17776 Translations update from Weblate
  i18n/bg.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17764 MM-35030: Hoist GetDBVersion before creating store
  app/server.go
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#17771 Skip database-reliant tests during short mode unit testing
  cmd/mattermost/commands/version_test.go
  config/migrate_test.go
Labels: 4: Reviews Complete, AutoMerge, Tests/Not Needed, release-note-none

#17774 MM-36257 Change Post.IsFollowing to a pointer and set to nil for responses to updates to Posts
  app/post.go
  app/post_test.go
  model/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#17762 Give local dev HA cluster a name
  docker-compose.yaml
Labels: 4: Reviews Complete, release-note-none

#17777 [MM-36411] Fix flaky TestUpdateConfigDiffInAuditRecord
  api4/config_test.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#17744 users service: add sessions
  app/admin.go
  app/app_iface.go
  app/channel_test.go
  app/cluster_handlers.go
  app/config.go
  app/oauth.go
  app/opentracing/opentracing_layer.go
  app/plugin_requests.go
  app/server.go
  app/session.go
  app/session_test.go
  app/team.go
  app/user.go
  app/user_test.go
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
  cmd/mattermost/commands/user.go
  services/users/helper_test.go
  services/users/session.go
  services/users/session_test.go
  services/users/users.go
  services/users/utils.go
  testlib/store.go
  web/handlers.go
  wsapi/websocket_handler.go
Labels: 2: Dev Review, release-note-none

#17754 MM-35396 Refactor GetThreadForUser store func to take membership as argument to prevent replica lag issues and reduce joins in query
  api4/post_test.go
  api4/user.go
  app/app_iface.go
  app/channel.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post_test.go
  app/user.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#17778 Bump to 5.36.1
  model/version.go
Labels: release-note-none

#17752 [MM-36268] Fix replication lag error on post reply
  app/channel.go
  app/notification.go
  app/user.go
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#17680 [MM-8497] Ability to set Do Not Disturb for a specified period of time
  api4/apitestlib.go
  api4/status.go
  api4/status_test.go
  app/app.go
  app/app_iface.go
  app/helper_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/server.go
  app/status.go
  model/feature_flags.go
  model/scheduled_task.go
  model/scheduled_task_test.go
  model/status.go
  model/status_test.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/status_store.go
  store/sqlstore/upgrade.go
  store/store.go
  store/storetest/mocks/StatusStore.go
  store/storetest/status_store.go
  store/timerlayer/timerlayer.go
Labels: release-note-none

#17773 MM-35415: ignore 'any' notification setting for CRT reply posts
  app/notification.go
  app/notification_test.go
Labels: 4: Reviews Complete, release-note-none

#17779 DB driver implementation via RPC
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_api_tests/test_db_driver/main.go
  app/plugin_db_driver.go
  app/plugin_hooks_test.go
  plugin/client.go
  plugin/client_rpc.go
  plugin/db_rpc.go
  plugin/environment.go
  plugin/health_check_test.go
  plugin/helpers.go
  plugin/supervisor.go
  plugin/supervisor_test.go
  services/telemetry/telemetry_test.go
  shared/driver/conn.go
  shared/driver/driver.go
  shared/driver/objects.go
  store/sqlstore/store_test.go
  utils/test_files_compiler.go
  web/web_test.go
Labels: 4: Reviews Complete, release-note-none

#17755 MM-35699: CRT off should behave same as CRT unsupported
  app/channel.go
  app/channel_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#17766 [MM-36318] Avoid redundant bot user update
  app/bot.go
  model/bot.go
  model/bot_test.go
Labels: 4: Reviews Complete, release-note

#17472 MM-34437 Preventing infinite trial requests
  Makefile
  api4/license.go
  api4/license_test.go
  app/enterprise.go
  app/license.go
  app/server.go
  einterfaces/license.go
  einterfaces/mocks/LicenseInterface.go
  i18n/en.json
  model/license.go
  model/license_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/license_store.go
  store/store.go
  store/storetest/mocks/LicenseStore.go
  store/timerlayer/timerlayer.go
  utils/license.go
  utils/license_test.go
  utils/mocks/LicenseValidatorIface.go
  utils/testutils/testutils.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#17789 Prevent JS Execution on Pre-login OAUTH screen
  utils/api.go
  web/oauth_test.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#17741 [34475] Support emoji 13.0
  app/import_validators_test.go
  app/slashcommands/command_custom_status.go
  app/slashcommands/command_custom_status_test.go
  model/emoji_data.go
Labels: release-note

#17718 Fixup: app_test: remove unused search engine initialization
  app/app_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17792 DB RPC driver: add master/replica support
  app/plugin_api_tests/test_db_driver/main.go
  app/plugin_db_driver.go
  plugin/client.go
  plugin/db_rpc.go
  plugin/helpers.go
  shared/driver/driver.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17795 Automated cherry pick of #17789
  utils/api.go
  web/oauth_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17794 Automated cherry pick of #17789
  utils/api.go
  web/oauth_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17793 Automated cherry pick of #17789
  utils/api.go
  web/oauth_test.go
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17784 user service: add oauth and profile images
  app/app_iface.go
  app/channel_test.go
  app/login.go
  app/oauth.go
  app/oauth_test.go
  app/opentracing/opentracing_layer.go
  app/server.go
  app/session.go
  app/session_test.go
  app/user.go
  app/user_test.go
  app/web_hub_test.go
  services/users/bot_default_image.go
  services/users/errors.go
  services/users/helper_test.go
  services/users/profile_picture.go
  services/users/profile_picture_test.go
  services/users/service.go
  services/users/service_test.go
  services/users/session.go
  services/users/session_test.go
  services/users/users.go
  testlib/store.go
Labels: 4: Reviews Complete, release-note-none

#17799 MM-35297 Add the ability to control if thread is followed when marking post as unread and don't autofollow from API
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  app/post_test.go
Labels: 4: Reviews Complete, release-note-none

#17807 Adding plugin.Driver mocks
  Makefile
  plugin/plugintest/driver.go
Labels: 4: Reviews Complete, release-note-none

#17808 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#17800 MM-36430 Follow threads without memberships if marked as unread
  app/user.go
  app/user_test.go
Labels: 4: Reviews Complete, AutoMerge, QA Deferred, release-note-none

#17811 Bump to 5.34.6
  model/version.go
Labels: release-note-none

#17812 Bump to 5.35.5
  model/version.go
Labels: release-note-none

#17806 MM-36590 Re-add old emoji aliases
  app/slashcommands/command_custom_status_test.go
  model/emoji_data.go
Labels: CherryPick/Approved, QA Deferred, Setup Cloud Test Server, release-note-none

#17817 Automated cherry pick of #17806
  app/slashcommands/command_custom_status_test.go
  model/emoji_data.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17818 Automated cherry pick of #17800
  app/user.go
  app/user_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17815 Bump to 5.31.8
  model/version.go
Labels: release-note-none

#17814 Bump to 5.36.2
  api4/config_test.go
  model/version.go
Labels: release-note-none

#17819 Bump version
  build/Dockerfile
Labels: release-note-none

#17417 [MM-30831] granular data retention wireup
  app/syncables_test.go
  i18n/en.json
  jobs/workers.go
  model/config.go
  model/data_retention_policy.go
  model/post.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_member_history_store.go
  store/sqlstore/post_store.go
  store/sqlstore/preference_store.go
  store/sqlstore/reaction_store.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/channel_member_history_store.go
  store/storetest/group_store.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/mocks/ReactionStore.go
  store/storetest/mocks/RetentionPolicyStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/post_store.go
  store/storetest/preference_store.go
  store/storetest/reaction_store.go
  store/storetest/retention_policy_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, release-note

#17765 Enable e2e testing with docker-compose on GitLab
  .circleci/config.yml
  .gitlab-ci.yml
  .gitlab-ci/scripts/test-schema/mysql.sh
  .gitlab-ci/scripts/test-schema/postgres.sh
  .gitlab-ci/scripts/test/mysql.sh
  .gitlab-ci/scripts/test/postgres.sh
  .gitlab-ci/test-schema.yml
  .gitlab-ci/test.yml
  build/.gitignore
  build/dotenv/test-schema-validation.env
  build/gitlab-dc.common.yml
  build/gitlab-dc.mysql.yml
  build/gitlab-dc.postgres.yml
  build/gitlab-dc.schemamysql.yml
  build/gitlab-dc.schemapostgres.yml
Labels: release-note-none

#17823 Hotfix to build master branch
  .gitlab-ci.yml
Labels: release-note-none

#17822 Bump focalboard prepackaged plugin version to v0.7.0
  Makefile
Labels: 2: Dev Review, release-note

#17824 Fix thread mention counts
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#17825 Bump focalboard prepackaged plugin version to v0.7.0 (#17822)
  Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#17828 Image as env var.
  .gitlab-ci.yml
  .gitlab-ci/scripts/test-schema/mysql.sh
  .gitlab-ci/scripts/test-schema/postgres.sh
  .gitlab-ci/scripts/test/mysql.sh
  .gitlab-ci/scripts/test/postgres.sh
Labels: release-note-none

#17826 MM-36429 Do not increment mention counts when marking root posts with no replies as unread
  app/channel.go
  app/channel_test.go
  app/user.go
  store/sqlstore/thread_store.go
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#17829 MM-36654 Re-add Mattermost emoji
  model/emoji_data.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#17831 Automated cherry pick of #17829
  model/emoji_data.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17821 MM-32421: Extend channel sidebar category APIs for Plugins
  app/plugin_api.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/plugintest/api.go
Labels: 4: Reviews Complete, release-note

#17839 Translations update from Weblate
  i18n/bg.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ko.json
  i18n/nl.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#17841 Update minor version to 5.37.0
  model/version.go
Labels: release-note-none

#17775 [MM-11143] Strip markdown formatting characters from push notifications
  app/notification_push.go
  go.mod
  go.sum
  utils/markdown.go
  utils/markdown_test.go
  vendor/github.com/yuin/goldmark/.gitignore
  vendor/github.com/yuin/goldmark/LICENSE
  vendor/github.com/yuin/goldmark/Makefile
  vendor/github.com/yuin/goldmark/README.md
  vendor/github.com/yuin/goldmark/ast/ast.go
  vendor/github.com/yuin/goldmark/ast/block.go
  vendor/github.com/yuin/goldmark/ast/inline.go
  vendor/github.com/yuin/goldmark/extension/ast/definition_list.go
  vendor/github.com/yuin/goldmark/extension/ast/footnote.go
  vendor/github.com/yuin/goldmark/extension/ast/strikethrough.go
  vendor/github.com/yuin/goldmark/extension/ast/table.go
  vendor/github.com/yuin/goldmark/extension/ast/tasklist.go
  vendor/github.com/yuin/goldmark/extension/definition_list.go
  vendor/github.com/yuin/goldmark/extension/footnote.go
  vendor/github.com/yuin/goldmark/extension/gfm.go
  vendor/github.com/yuin/goldmark/extension/linkify.go
  vendor/github.com/yuin/goldmark/extension/strikethrough.go
  vendor/github.com/yuin/goldmark/extension/table.go
  vendor/github.com/yuin/goldmark/extension/tasklist.go
  vendor/github.com/yuin/goldmark/extension/typographer.go
  vendor/github.com/yuin/goldmark/go.mod
  vendor/github.com/yuin/goldmark/go.sum
  vendor/github.com/yuin/goldmark/markdown.go
  vendor/github.com/yuin/goldmark/parser/attribute.go
  vendor/github.com/yuin/goldmark/parser/atx_heading.go
  vendor/github.com/yuin/goldmark/parser/auto_link.go
  vendor/github.com/yuin/goldmark/parser/blockquote.go
  vendor/github.com/yuin/goldmark/parser/code_block.go
  vendor/github.com/yuin/goldmark/parser/code_span.go
  vendor/github.com/yuin/goldmark/parser/delimiter.go
  vendor/github.com/yuin/goldmark/parser/emphasis.go
  vendor/github.com/yuin/goldmark/parser/fcode_block.go
  vendor/github.com/yuin/goldmark/parser/html_block.go
  vendor/github.com/yuin/goldmark/parser/link.go
  vendor/github.com/yuin/goldmark/parser/link_ref.go
  vendor/github.com/yuin/goldmark/parser/list.go
  vendor/github.com/yuin/goldmark/parser/list_item.go
  vendor/github.com/yuin/goldmark/parser/paragraph.go
  vendor/github.com/yuin/goldmark/parser/parser.go
  vendor/github.com/yuin/goldmark/parser/raw_html.go
  vendor/github.com/yuin/goldmark/parser/setext_headings.go
  vendor/github.com/yuin/goldmark/parser/thematic_break.go
  vendor/github.com/yuin/goldmark/renderer/html/html.go
  vendor/github.com/yuin/goldmark/renderer/renderer.go
  vendor/github.com/yuin/goldmark/text/reader.go
  vendor/github.com/yuin/goldmark/text/segment.go
  vendor/github.com/yuin/goldmark/util/html5entities.go
  vendor/github.com/yuin/goldmark/util/unicode_case_folding.go
  vendor/github.com/yuin/goldmark/util/util.go
  vendor/github.com/yuin/goldmark/util/util_safe.go
  vendor/github.com/yuin/goldmark/util/util_unsafe.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note

#17847 Fix flaky test: TestSendAutoResponseIfNecessary
  app/auto_responder.go
Labels: 4: Reviews Complete, release-note-none

#17846 [MM-36481] Fix emoji regex to support thumbsup
  app/slashcommands/command_custom_status.go
  model/emoji.go
  model/emoji_test.go
  model/utils.go
  model/utils_test.go
Labels: 3: QA Review, release-note-none

#17851 Automated cherry pick of #17847
  app/auto_responder.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17850 Automated cherry pick of #17846
  app/slashcommands/command_custom_status.go
  model/emoji.go
  model/emoji_test.go
  model/utils.go
  model/utils_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#17852 Use forked version of gziphandler
  api4/handlers.go
  go.mod
  go.sum
  vendor/github.com/NYTimes/gziphandler/.travis.yml
  vendor/github.com/NYTimes/gziphandler/go.mod
  vendor/github.com/mattermost/gziphandler/.gitignore
  vendor/github.com/mattermost/gziphandler/.golangci.yml
  vendor/github.com/mattermost/gziphandler/CODE_OF_CONDUCT.md
  vendor/github.com/mattermost/gziphandler/CONTRIBUTING.md
  vendor/github.com/mattermost/gziphandler/LICENSE
  vendor/github.com/mattermost/gziphandler/Makefile
  vendor/github.com/mattermost/gziphandler/README.md
  vendor/github.com/mattermost/gziphandler/go.mod
  vendor/github.com/mattermost/gziphandler/go.sum
  vendor/github.com/mattermost/gziphandler/gzip.go
  vendor/github.com/mattermost/gziphandler/gzip_go18.go
  vendor/modules.txt
  web/handlers.go
  web/static.go
Labels: 2: Dev Review, release-note-none

#17853 move migration to future release as 536 is already done
  store/sqlstore/upgrade.go
Labels: 4: Reviews Complete, AutoMerge, kind/bug, release-note-none

#17168 [MM-33538] Trims space from user email when sanitizing user input
  api4/user_test.go
  model/user.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none
