Repository mattermost/mattermost, pull requests merged in 2022-04, with the labels that each got.

#19893 Pre-package Playbooks v1.26.1
  Makefile
Labels: release-note

#19856 api4/license: Return 400 instead of 501 if format is not passed
  api4/license.go
  api4/license_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#19877 app/post_metadata: add a type cast check for OpenGraph images
  app/post_metadata.go
  app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note-none

#19891 update morph dependency
  config/database.go
  go.mod
  go.sum
  store/sqlstore/store.go
  vendor/github.com/mattermost/morph/README.md
  vendor/github.com/mattermost/morph/drivers/lock.go
  vendor/github.com/mattermost/morph/drivers/logger.go
  vendor/github.com/mattermost/morph/drivers/mysql/lock.go
  vendor/github.com/mattermost/morph/drivers/postgres/lock.go
  vendor/github.com/mattermost/morph/morph.go
  vendor/github.com/mattermost/morph/sources/embedded/README.md
  vendor/github.com/mattermost/morph/sources/embedded/embedded.go
  vendor/github.com/mattermost/morph/sources/file/file.go
  vendor/github.com/mattermost/morph/sources/go_bindata/README.md
  vendor/github.com/mattermost/morph/sources/source.go
  vendor/modules.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#19892 api4/post_test: skip TestDeletePostEvent
  api4/post_test.go
Labels: 4: Reviews Complete, release-note-none

#19876 api4/system: add check if model.FileSettings is empty
  api4/system.go
  api4/system_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#19880 store/channel_store_categories: check if the category has a valid type
  store/sqlstore/channel_store_categories.go
Labels: 4: Reviews Complete, release-note-none

#19833 MM-40148: threadsOnly query param for user threads
  api4/user.go
  api4/user_test.go
  app/user.go
  i18n/en.json
  model/client4.go
  model/thread.go
Labels: QA Review Done, release-note

#19896 adopt forked squirrel supporting from UPDATE FROM
  go.mod
  go.sum
  store/sqlstore/thread_store.go
  vendor/github.com/Masterminds/squirrel/squirrel_ctx.go
  vendor/github.com/Masterminds/squirrel/statement.go
  vendor/github.com/Masterminds/squirrel/update.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#19890 bugfix: post edit time limit is not a licensed feature anymore
  app/post.go
Labels: 4: Reviews Complete, CherryPick/Approved, kind/bug, release-note

#19904 Automated cherry pick of #19890
  app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19905 cherry-pick a4aa586 to release-6.4
  go.mod
  go.sum
  store/sqlstore/store.go
  vendor/github.com/go-morph/morph/sources/go_bindata/README.md
  vendor/github.com/go-morph/morph/sources/source.go
  vendor/github.com/mattermost/morph/.gitignore
  vendor/github.com/mattermost/morph/AUTHORS
  vendor/github.com/mattermost/morph/LICENSE
  vendor/github.com/mattermost/morph/Makefile
  vendor/github.com/mattermost/morph/README.md
  vendor/github.com/mattermost/morph/color_logger.go
  vendor/github.com/mattermost/morph/docker-compose.yml
  vendor/github.com/mattermost/morph/drivers/driver.go
  vendor/github.com/mattermost/morph/drivers/error.go
  vendor/github.com/mattermost/morph/drivers/lock.go
  vendor/github.com/mattermost/morph/drivers/logger.go
  vendor/github.com/mattermost/morph/drivers/mysql/lock.go
  vendor/github.com/mattermost/morph/drivers/mysql/mysql.go
  vendor/github.com/mattermost/morph/drivers/mysql/utils.go
  vendor/github.com/mattermost/morph/drivers/postgres/lock.go
  vendor/github.com/mattermost/morph/drivers/postgres/postgres.go
  vendor/github.com/mattermost/morph/drivers/postgres/utils.go
  vendor/github.com/mattermost/morph/drivers/utils.go
  vendor/github.com/mattermost/morph/go.mod
  vendor/github.com/mattermost/morph/go.sum
  vendor/github.com/mattermost/morph/models/migration.go
  vendor/github.com/mattermost/morph/models/parse.go
  vendor/github.com/mattermost/morph/morph.go
  vendor/github.com/mattermost/morph/sources/embedded/README.md
  vendor/github.com/mattermost/morph/sources/embedded/embedded.go
  vendor/github.com/mattermost/morph/sources/file/file.go
  vendor/github.com/mattermost/morph/sources/source.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note

#19921 Pre-package Playbooks v1.26.2
  Makefile
Labels: release-note

#19922 Automated cherry pick of #19921
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19920 MM-42813: Fallback to default config if nil is passed
  api4/system.go
Labels: 4: Reviews Complete, release-note-none

#19898 Optimize marshalling for jsonb types
  model/utils.go
  store/sqlstore/job_store.go
  store/sqlstore/link_metadata_store.go
  store/sqlstore/session_store.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/user_store.go
  store/sqlstore/utils.go
Labels: 4: Reviews Complete, release-note-none

#19889 MM-41323: Secure plugin marketplace modification
  api4/config.go
  api4/config_test.go
Labels: 4: Reviews Complete, release-note-none

#19925 Automated cherry pick of #19920
  api4/system.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19928 Automated cherry pick of #19921
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19927 [MM-43073] broadcast post unread websocket when CRT off
  api4/post_test.go
  app/channel.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#19932 Automated cherry pick of #19927
  api4/post_test.go
  app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19931 Automated cherry pick of #19927
  api4/post_test.go
  app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19870 Prepackage Apps plugin and enable Apps feature flag by default
  Makefile
  config/diff_test.go
  model/config.go
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#19929 Pre-package Playbooks v1.23.1
  Makefile
Labels: 4: Reviews Complete, release-note

#19933 Automated cherry pick of #19870
  Makefile
  config/diff_test.go
  model/config.go
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19938 Automated cherry pick of #19870
  Makefile
  config/diff_test.go
  model/config.go
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19930 [MM-42355] Prepackage Calls v0.4.8
  Makefile
  build/release.mk
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#19899 [MM-42522] - The reply-to email address in our Cloud trial emails is no-reply@mattermost.com instead of feedback-cloud@mattermost.com
  app/email/email.go
  app/email/email_test.go
  app/email/utils.go
Labels: 2: Dev Review, release-note-none

#19935 MM-43137: Fix racy test TestUpdateActiveBotsSideEffect
  store/sqlstore/user_store.go
Labels: 2: Dev Review, release-note-none

#19937 [MM-42889] fixed search term for archived channels
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#19941 Automated cherry pick of #19937
  store/sqlstore/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19910 MM-42880: Fix TestRunServerSuccess
  cmd/mattermost/commands/server_test.go
Labels: 4: Reviews Complete, release-note-none

#19940 Automated cherry pick of #19937
  store/sqlstore/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19939 MM-42725: exclude channels from teams user has left
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, QA Deferred, release-note

#19943 Automated cherry pick of #19939
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19875 Disambiguates some units.
  api4/channel_test.go
  api4/team.go
  api4/team_test.go
  api4/user.go
  app/session.go
  model/config.go
  model/data_retention_policy.go
  model/license.go
  store/sqlstore/retention_policy_store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/post_store.go
  store/storetest/retention_policy_store.go
  store/storetest/team_store.go
  store/storetest/thread_store.go
Labels: QA Deferred, release-note-none

#19942 Automated cherry pick of #19939
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19765 [MM-38615] Permalink Previews for DMs/GMs
  app/post.go
  app/post_metadata.go
  app/post_metadata_test.go
  app/post_test.go
  model/permalink.go
Labels: 4: Reviews Complete, release-note-none

#19861 app: add channels wrapper
  app/channel.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#19936 MM-43143: Dataloaders for roles
  api4/graphql.go
  api4/resolver.go
  api4/resolver_channel_member.go
  api4/resolver_team_member.go
  api4/resolver_test.go
  api4/resolver_user.go
  go.mod
  go.sum
  vendor/github.com/graph-gophers/dataloader/v6/.gitignore
  vendor/github.com/graph-gophers/dataloader/v6/.travis.yml
  vendor/github.com/graph-gophers/dataloader/v6/LICENSE
  vendor/github.com/graph-gophers/dataloader/v6/MIGRATE.md
  vendor/github.com/graph-gophers/dataloader/v6/README.md
  vendor/github.com/graph-gophers/dataloader/v6/TRACE.md
  vendor/github.com/graph-gophers/dataloader/v6/cache.go
  vendor/github.com/graph-gophers/dataloader/v6/codecov.yml
  vendor/github.com/graph-gophers/dataloader/v6/dataloader.go
  vendor/github.com/graph-gophers/dataloader/v6/go.mod
  vendor/github.com/graph-gophers/dataloader/v6/go.sum
  vendor/github.com/graph-gophers/dataloader/v6/in_memory_cache.go
  vendor/github.com/graph-gophers/dataloader/v6/key.go
  vendor/github.com/graph-gophers/dataloader/v6/trace.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#19918 MM-43082: Added new telemetry values for groups.
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, QA Deferred, release-note

#19849 MM-39058 - invite people to join team and channels
  api4/team.go
  api4/team_local.go
  api4/team_test.go
  app/app_iface.go
  app/email/email.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/email_test.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/team_test.go
  app/user.go
  i18n/en.json
  jobs/resend_invitation_email/worker.go
  model/client4.go
  model/member_invite.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#19956 agniva spelling
  api4/cloud.go
  api4/user.go
  api4/webhook.go
  app/admin.go
  app/compliance.go
  app/feature_flags.go
  app/import_functions.go
  app/integration_action.go
  app/notification.go
  app/options.go
  app/plugin_signature.go
  app/server.go
  app/server_inactivity.go
  app/team.go
  db/migrations/mysql/000046_create_users.up.sql
  einterfaces/account_migration.go
  einterfaces/mocks/AccountMigrationInterface.go
  plugin/hooks.go
  services/searchengine/bleveengine/common.go
  services/tracing/tracing.go
  shared/filestore/s3store.go
  store/errors.go
  store/localcachelayer/layer.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/session_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/team_store.go
  store/sqlstore/webhook_store.go
  templates/payment_failed_body.html
  templates/payment_failed_no_card_body.html
Labels: 4: Reviews Complete, release-note-none

#19960 MM-43144: Add teams loader
  api4/graphql.go
  api4/resolver.go
  api4/resolver_team.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/teams/teams.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, release-note-none

#19874 [MM-41993]: fixed counting thread mentions in unread root post
  api4/user_test.go
  app/post.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, kind/bug, release-note-none

#19961 v2 cherry-pick of a4aa586 to release-6.5
  go.mod
  go.sum
  store/sqlstore/store.go
  vendor/github.com/go-morph/morph/sources/go_bindata/README.md
  vendor/github.com/go-morph/morph/sources/source.go
  vendor/github.com/mattermost/morph/.gitignore
  vendor/github.com/mattermost/morph/AUTHORS
  vendor/github.com/mattermost/morph/LICENSE
  vendor/github.com/mattermost/morph/Makefile
  vendor/github.com/mattermost/morph/README.md
  vendor/github.com/mattermost/morph/color_logger.go
  vendor/github.com/mattermost/morph/docker-compose.yml
  vendor/github.com/mattermost/morph/drivers/driver.go
  vendor/github.com/mattermost/morph/drivers/error.go
  vendor/github.com/mattermost/morph/drivers/lock.go
  vendor/github.com/mattermost/morph/drivers/logger.go
  vendor/github.com/mattermost/morph/drivers/mysql/lock.go
  vendor/github.com/mattermost/morph/drivers/mysql/mysql.go
  vendor/github.com/mattermost/morph/drivers/mysql/utils.go
  vendor/github.com/mattermost/morph/drivers/postgres/lock.go
  vendor/github.com/mattermost/morph/drivers/postgres/postgres.go
  vendor/github.com/mattermost/morph/drivers/postgres/utils.go
  vendor/github.com/mattermost/morph/drivers/utils.go
  vendor/github.com/mattermost/morph/go.mod
  vendor/github.com/mattermost/morph/go.sum
  vendor/github.com/mattermost/morph/models/migration.go
  vendor/github.com/mattermost/morph/models/parse.go
  vendor/github.com/mattermost/morph/morph.go
  vendor/github.com/mattermost/morph/sources/embedded/README.md
  vendor/github.com/mattermost/morph/sources/embedded/embedded.go
  vendor/github.com/mattermost/morph/sources/file/file.go
  vendor/github.com/mattermost/morph/sources/source.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note

#19924 Update link to Docker instructions
  README.md
Labels: 4: Reviews Complete, release-note-none

#19959 MM-43252: Skip TestPreparePostForClient
  app/post_metadata_test.go
Labels: 2: Dev Review, release-note-none

#19845 MM-41909: Allow 1 char channel name
  app/slashcommands/command_channel_rename_test.go
  i18n/en.json
  model/channel.go
  model/shared_channel.go
  model/utils.go
  model/utils_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#19966 MM-39565 - remove top option ab testing
  model/feature_flags.go
Labels: release-note-none

#19963 typo in makefile
  Makefile
  services/searchengine/mocks/SearchEngineInterface.go
  services/sharedchannel/mock_AppIface_test.go
  services/sharedchannel/mock_ServerIface_test.go
  services/telemetry/mocks/ServerIface.go
  shared/filestore/mocks/FileBackend.go
  shared/filestore/mocks/ReadCloseSeeker.go
  utils/mocks/LicenseValidatorIface.go
Labels: release-note-none

#19968 MM-43340: Fix racy test TestGraphQLChannelMembers
  api4/resolver_team.go
  model/team.go
Labels: 4: Reviews Complete, release-note-none

#19970 MM-43341: Skip TestImportImportUser
  app/import_functions_test.go
  app/import_test.go
Labels: 4: Reviews Complete, release-note-none

#19971 Update version to 6.3.8
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19973 Update minor version to 6.7.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19972 Propagate the parse error for URLs
  config/database_test.go
  config/file_test.go
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#19969 MM-43232: Racy test TestWebsocketRace
  model/websocket_client_test.go
Labels: 4: Reviews Complete, release-note-none

#19984 Add .gitpod.yml to use mattermost-gitpod-config repo for Gitpod configuration
  .gitpod.yml
Labels: 2: Dev Review, release-note-none

#19850 [MM-42742] Insights - Top Reactions API Endpoint
  api4/reaction.go
  api4/reaction_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/reaction.go
  app/reaction_test.go
  i18n/en.json
  model/client4.go
  model/insights.go
  model/insights_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/reaction_store.go
  store/store.go
  store/storetest/mocks/ReactionStore.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/params.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#19975 config/database: update queries to improve reads/writes
  config/database.go
  config/migrations/mysql/000003_update_configurations_sha.down.sql
  config/migrations/mysql/000003_update_configurations_sha.up.sql
  config/migrations/postgres/000003_update_configurations_sha.down.sql
  config/migrations/postgres/000003_update_configurations_sha.up.sql
Labels: 4: Reviews Complete, release-note

#20000 Cleaning up old migration commands
  Makefile
Labels: 4: Reviews Complete, release-note-none

#19987 jobs: add config cleanup job
  app/server.go
  config/database.go
  config/database_test.go
  config/store.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#19951 [MM-41185]: new API to mark thread as unread
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, release-note

#20002 MM-42877: Fix TestGetFileHeaders
  api4/file_test.go
Labels: 4: Reviews Complete, release-note-none

#19962 MM-41565,MM-42473: fixes incorrect unread thread count
  api4/user_test.go
  app/notification.go
Labels: 4: Reviews Complete, release-note

#20006 Update minio-go dependency to 7.0.24
  go.mod
  go.sum
  vendor/github.com/minio/minio-go/v7/Makefile
  vendor/github.com/minio/minio-go/v7/api-bucket-notification.go
  vendor/github.com/minio/minio-go/v7/api-compose-object.go
  vendor/github.com/minio/minio-go/v7/api-get-object-file.go
  vendor/github.com/minio/minio-go/v7/api-list.go
  vendor/github.com/minio/minio-go/v7/api-put-object-multipart.go
  vendor/github.com/minio/minio-go/v7/api-put-object-streaming.go
  vendor/github.com/minio/minio-go/v7/api-put-object.go
  vendor/github.com/minio/minio-go/v7/api-putobject-snowball.go
  vendor/github.com/minio/minio-go/v7/api-select.go
  vendor/github.com/minio/minio-go/v7/api.go
  vendor/github.com/minio/minio-go/v7/bucket-cache.go
  vendor/github.com/minio/minio-go/v7/core.go
  vendor/github.com/minio/minio-go/v7/functional_tests.go
  vendor/github.com/minio/minio-go/v7/go.mod
  vendor/github.com/minio/minio-go/v7/go.sum
  vendor/github.com/minio/minio-go/v7/pkg/credentials/file_minio_client.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/iam_aws.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/sts_client_grants.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/sts_ldap_identity.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/sts_tls_identity.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/sts_web_identity.go
  vendor/github.com/minio/minio-go/v7/pkg/encrypt/server-side.go
  vendor/github.com/minio/minio-go/v7/pkg/notification/notification.go
  vendor/github.com/minio/minio-go/v7/pkg/replication/replication.go
  vendor/github.com/minio/minio-go/v7/pkg/signer/request-signature-streaming.go
  vendor/github.com/minio/minio-go/v7/retry.go
  vendor/github.com/minio/minio-go/v7/utils.go
  vendor/modules.txt
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#20005 MM-43448: Bump the CI to use Go 1.18.1
  .circleci/config.yml
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#20010 Bump golangci to use 1.18
  .circleci/config.yml
  .golangci.yml
  Makefile
  app/webhub_fuzz.go
  cmd/mattermost/main_test.go
  utils/markdown.go
Labels: 4: Reviews Complete, release-note-none

#20011 Add feature flag for command palette
  model/feature_flags.go
Labels: 4: Reviews Complete, release-note-none

#20014 [DOPS-920] Fix mmctl download bash script
  scripts/download_mmctl_release.sh
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, kind/bug, release-note-none, Contributor

#19949 [MM-43151] add test for archived channels search
  store/storetest/channel_store.go
Labels: release-note-none

#19934 MM-43045: minimize JOIN Posts
  app/post_test.go
  app/user.go
  db/migrations/mysql/000081_threads_deleteat.down.sql
  db/migrations/mysql/000081_threads_deleteat.up.sql
  db/migrations/postgres/000081_threads_deleteat.down.sql
  db/migrations/postgres/000081_threads_deleteat.up.sql
  model/thread.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
  store/storetest/post_store.go
  store/storetest/thread_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note

#20030 Weblate cloud pr 20017
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20039 Automated cherry pick of #20028
  db/migrations/mysql/000082_upgrade_oauth_mattermost_app_id.down.sql
  db/migrations/mysql/000082_upgrade_oauth_mattermost_app_id.up.sql
  db/migrations/postgres/000082_upgrade_oauth_mattermost_app_id.down.sql
  db/migrations/postgres/000082_upgrade_oauth_mattermost_app_id.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20015 MM-43464 Enable timestamp for default audit config
  config/logger.go
  config/logger_test.go
Labels: 2: Dev Review, release-note

#19993 [MM-43253] Allow per connection WebSocket broadcasts
  app/web_conn.go
  app/web_conn_test.go
  app/web_hub.go
  app/web_hub_test.go
  model/websocket_message.go
Labels: 4: Reviews Complete, release-note

#20051 MM-43653: Fix incorrect system store update
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#20052 Automated cherry pick of #20051
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20053 Automated cherry pick of #20051
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20055 Automated cherry pick of #20051
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20054 Automated cherry pick of #20051
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20047 Query optimization for top reactions.
  store/sqlstore/reaction_store.go
Labels: QA Deferred, release-note-none

#20041 Mm 43084 add cloud workspace limits endpoint
  api4/cloud.go
  api4/cloud_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  model/client4.go
  model/cloud.go
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#19989 [MM-43339] Add Cloud Subscription Upgrade Confirmation Email
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email/email.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_upgrade_confirmation.html
  templates/cloud_upgrade_confirmation.mjml
Labels: release-note-none

#20044 Pre-package Playbooks v1.27.0
  Makefile
Labels: Setup Cloud Test Server, release-note

#20064 Automated cherry pick of #20044
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20004 MM-42927: Use new gosaml2 library
  go.mod
  go.sum
  vendor/github.com/mattermost/gosaml2/.travis.yml
  vendor/github.com/mattermost/gosaml2/README.md
  vendor/github.com/mattermost/gosaml2/attribute.go
  vendor/github.com/mattermost/gosaml2/authn_request.go
  vendor/github.com/mattermost/gosaml2/build_logout_response.go
  vendor/github.com/mattermost/gosaml2/build_request.go
  vendor/github.com/mattermost/gosaml2/decode_logout_request.go
  vendor/github.com/mattermost/gosaml2/decode_response.go
  vendor/github.com/mattermost/gosaml2/go.mod
  vendor/github.com/mattermost/gosaml2/go.sum
  vendor/github.com/mattermost/gosaml2/logout_request.go
  vendor/github.com/mattermost/gosaml2/retrieve_assertion.go
  vendor/github.com/mattermost/gosaml2/saml.go
  vendor/github.com/mattermost/gosaml2/test_constants.go
  vendor/github.com/mattermost/gosaml2/types/encrypted_assertion.go
  vendor/github.com/mattermost/gosaml2/types/encrypted_key.go
  vendor/github.com/mattermost/gosaml2/types/metadata.go
  vendor/github.com/mattermost/gosaml2/types/response.go
  vendor/github.com/mattermost/gosaml2/uuid/uuid.go
  vendor/github.com/mattermost/gosaml2/validate.go
  vendor/github.com/mattermost/gosaml2/xml_constants.go
  vendor/github.com/mattermost/xml-roundtrip-validator/LICENSE.txt
  vendor/github.com/mattermost/xml-roundtrip-validator/README.md
  vendor/github.com/mattermost/xml-roundtrip-validator/SECURITY.md
  vendor/github.com/mattermost/xml-roundtrip-validator/go.mod
  vendor/github.com/mattermost/xml-roundtrip-validator/go.sum
  vendor/github.com/mattermost/xml-roundtrip-validator/validator.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#19953 [MM-42739] Insights - Top Channels API Endpoint
  api4/api.go
  api4/insights.go
  api4/insights_test.go
  api4/reaction.go
  api4/reaction_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/client4.go
  model/insights.go
  model/insights_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/reaction_store.go
  store/store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
  web/context.go
  web/params.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#20056 Automated cherry pick of #20051
  store/sqlstore/system_store.go
  store/storetest/system_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19988 [MM-43393]: replace .Decoder() method with .Token()
  app/imaging/svg.go
  app/imaging/svg_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, kind/bug, release-note-none

#20079 Automated cherry pick of #19988
  app/imaging/svg.go
  app/imaging/svg_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20016 Updated NPS pluing to 1.2.0
  Makefile
Labels: 4: Reviews Complete, QA Review Done, release-note, Setup Cloud + CWS Test Server

#20050 Cherry pick of #19610
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/notification_push.go
  app/notification_push_test.go
  app/opentracing/opentracing_layer.go
  model/push_notification.go
  store/storetest/group_store.go
  store/storetest/post_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20082 Automated cherry pick of #19988
  app/imaging/svg.go
  app/imaging/svg_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20081 Automated cherry pick of #19988
  app/imaging/svg.go
  app/imaging/svg_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20092 Bump GoSAML dependency
  go.mod
  go.sum
  vendor/github.com/mattermost/gosaml2/types/encrypted_key.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#20097 Update version to 6.5.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20095 Update version to 6.3.9
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#20096 Update version to 6.4.4
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#20087 MM-43829: Default for user display_name preference
  api4/resolver_channel.go
  api4/resolver_channel_test.go
Labels: 4: Reviews Complete, release-note-none

#20094 MM-43848: Skip flaky TestUserStore/LocalCache+MySQL/UpdateUpdateAt
  app/post_test.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note-none

#20007 [MM-43443] Don't log error when SendEmailNotifications is set to false
  app/server.go
  shared/mail/mail.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#20091 Remove code duplication and move utility methods to the store utils
  config/database.go
  config/utils.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#20103 Lock CI from /release-6.7
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#20093 Update Chrome supported version to 100+
  i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, AutoMerge, release-note-none

#20106 Automated cherry pick of #20075
  services/upgrader/upgrader_linux.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20105 Automated cherry pick of #19988
  app/imaging/svg.go
  app/imaging/svg_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20107 Automated cherry pick of #20093
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20074 MM-43770: Rename to Threads.ThreadDeleteAt
  db/migrations/mysql/000081_threads_deleteat.down.sql
  db/migrations/mysql/000081_threads_deleteat.up.sql
  db/migrations/mysql/000083_threads_threaddeleteat.down.sql
  db/migrations/mysql/000083_threads_threaddeleteat.up.sql
  db/migrations/postgres/000081_threads_deleteat.down.sql
  db/migrations/postgres/000081_threads_deleteat.up.sql
  db/migrations/postgres/000083_threads_threaddeleteat.down.sql
  db/migrations/postgres/000083_threads_threaddeleteat.up.sql
  model/thread.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#20078 [MM-43199] api4/elasticsearch: test elasticsearch after checking the config values
  api4/elasticsearch.go
  api4/elasticsearch_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none
