Repository mattermost/mattermost, pull requests merged in 2022-12, with the labels that each got.

#21602 [MM-46331] Change insights response writers as per convention
  api4/insights.go
Labels: release-note-none

#21736 [MM-48521] Fix for batch notification email not rendering properly
  app/email/email_batching.go
  app/email/notification_email.go
  app/email/notification_email_test.go
  app/notification_email.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21792 Automated cherry pick of #21736
  app/email/email_batching.go
  app/email/notification_email.go
  app/email/notification_email_test.go
  app/notification_email.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21795 Automated cherry pick of #21736
  app/email/email_batching.go
  app/email/notification_email.go
  app/email/notification_email_test.go
  app/notification_email.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21518 [MM-44765] Add API method for getting post's information from permalink
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  model/client4.go
  model/post_info.go
Labels: Hacktoberfest, hacktoberfest-accepted, release-note

#21782 exlude boards build from release 7.3
  .circleci/config.yml
Labels: release-note-none

#21766 [MM-48472]: Update the Upgrade Confirmation Email for yearly subscriptions
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email/email.go
  app/email/email_test.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, release-note, Setup Cloud + CWS Test Server

#21799 Revert "[feat] CI essential multi-product architecture changes #20783)"
  .circleci/config.yml
  build/docker/mysql.conf.d/custom.cnf
  build/docker/postgres.conf
  templates/cloud_30_day_arrears.html
Labels: 2: Dev Review, release-note-none

#21772 MPA: move product hooks out of plugins environment
  api4/websocket.go
  app/channel.go
  app/channels.go
  app/cluster_handlers.go
  app/file.go
  app/login.go
  app/onboarding.go
  app/platform/service.go
  app/platform/web_conn.go
  app/platform/web_conn_test.go
  app/platform/web_hub_test.go
  app/plugin.go
  app/plugin_hooks_test.go
  app/post.go
  app/reaction.go
  app/server.go
  app/team.go
  app/upload.go
  app/user.go
  app/web_conn.go
  plugin/environment.go
  plugin/interface_generator/main.go
  plugin/product.go
  plugin/product_hooks_generated.go
  product/hooks.go
Labels: 4: Reviews Complete, release-note-none

#21529 Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.4
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 4: Reviews Complete, AutoMerge, release-note

#21530 Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.3
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 4: Reviews Complete, AutoMerge, release-note

#21805 Revert MPA circle CI build PRs for the release-7.5 branch
  .circleci/config.yml
  app/platform/service.go
  app/platform/service_test.go
  build/docker/mysql.conf.d/custom.cnf
  build/docker/postgres.conf
  build/release.mk
Labels: 2: Dev Review, release-note-none

#21171 MM-48120/MM-48623 Patch plugin bundle react-dom on webapp extract
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_hooks_test.go
  model/config.go
  plugin/environment.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  web/web_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#21810 Automated cherry pick of #21171
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_hooks_test.go
  model/config.go
  plugin/environment.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  web/web_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21809 Automated cherry pick of #21171
  app/plugin.go
  app/plugin_api_test.go
  app/plugin_hooks_test.go
  model/config.go
  plugin/environment.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  web/web_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21781 [MM-48727] Restore license checks for SSO in self-hosted deployments
  cmd/mattermost/main.go
  config/client.go
  model/license.go
  model/oauthproviders/google/google.go
  model/oauthproviders/google/google_test.go
  model/oauthproviders/office365/office365.go
  model/oauthproviders/office365/office365_test.go
  model/oauthproviders/openid/openid.go
  model/oauthproviders/openid/openid_test.go
Labels: Do Not Merge, 3: QA Review, CherryPick/Approved, release-note-none

#21814 Automated cherry pick of #21781
  cmd/mattermost/main.go
  config/client.go
  model/license.go
  model/oauthproviders/google/google.go
  model/oauthproviders/google/google_test.go
  model/oauthproviders/office365/office365.go
  model/oauthproviders/office365/office365_test.go
  model/oauthproviders/openid/openid.go
  model/oauthproviders/openid/openid_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21812 Automated cherry pick of #21781
  cmd/mattermost/main.go
  config/client.go
  model/license.go
  model/oauthproviders/google/google.go
  model/oauthproviders/google/google_test.go
  model/oauthproviders/office365/office365.go
  model/oauthproviders/office365/office365_test.go
  model/oauthproviders/openid/openid.go
  model/oauthproviders/openid/openid_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21803 app: avoid plugin env check for RunMultiHook and use pluginslock while accessing plugin env
  app/channel.go
  app/channels.go
  app/file.go
  app/login.go
  app/plugin.go
  app/post.go
  app/reaction.go
  app/team.go
  app/upload.go
  app/user.go
Labels: 4: Reviews Complete, release-note-none

#21732 Pre-package Playbooks v1.29.3 to v7.1
  Makefile
Labels: 4: Reviews Complete, Setup Cloud Test Server, AutoMerge, release-note

#21733 Pre-package Playbooks v1.32.7 to v7.4
  Makefile
Labels: 4: Reviews Complete, Setup Cloud Test Server, AutoMerge, release-note

#21734 Pre-package Playbooks v1.32.7 to v7.5
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Setup Cloud Test Server, AutoMerge, release-note

#21648 [MM-42421] Prevent guests from seeing users through groups API (#21151)
  api4/group.go
  api4/group_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/group.go
  app/group_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21649 [MM-42421] Prevent guests from seeing users through groups API (#21151)
  api4/group.go
  api4/group_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/group.go
  app/group_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21720 Enables PostPriority FeatureFlag by default
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#21717 [MM-47566] Add upcominginvoice field to Subscription type
  api4/cloud.go
  model/cloud.go
  web/context.go
Labels: 4: Reviews Complete, release-note-none

#21815 Automated cherry pick of #21720
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21801 MM-48125 - Downgrades send upgrade email
  api4/cloud.go
  model/cloud.go
Labels: 2: Dev Review, QA Deferred, release-note

#21548 Minimize app dependency on platform service
  api4/channel.go
  api4/post.go
  api4/resolver_user.go
  api4/user.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/platform/helper_test.go
  app/platform/mocks/SuiteIFace.go
  app/platform/service.go
  app/platform/status.go
  app/platform/web_conn.go
  app/platform/web_hub.go
  app/platform/web_hub_test.go
  app/platform/websocket_router.go
  app/server.go
  app/session.go
  app/status.go
Labels: 4: Reviews Complete, release-note-none

#21819 Sha2
  api4/hosted_customer.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  model/hosted_customer.go
Labels: release-note-none

#21826 Automated cherry pick of #21818
  api4/drafts.go
  app/draft.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21821 MM-48651: Log error while queuing telemetry
  app/server.go
  model/config.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 4: Reviews Complete, release-note-none

#21830 Automated cherry pick of #21821
  app/server.go
  model/config.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21824 Pre-package Playbooks v1.34.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#21833 Automated cherry pick of #21824
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21832 Automated cherry pick of #21824
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21703 [MM-45052] Mark method as deprecated
  model/insights.go
Labels: 4: Reviews Complete, release-note-none

#21835 Automated cherry pick of #21703
  model/insights.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21834 MM-48476 - Upgrade calls to v0.11.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21836 [MM-48649]: Call the SendSubscriptionHistoryEvent function in a GO routine
  app/user.go
Labels: release-note-none

#21838 Automated cherry pick of #21834
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21839 Automated cherry pick of #21836
  app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21837 Automated cherry pick of #21834
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21831 [MM-48947] app/platform: do not restart metrics on every config save
  app/platform/config.go
  app/platform/config_test.go
  app/platform/service.go
  app/platform/service_test.go
Labels: 4: Reviews Complete, release-note

#21569 [MM-47378] Respond with bad requests for wrong query parameters 'roles' in getUsers
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  i18n/en.json
  model/client4.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#21841 Skip "block user by domain but allow bot" test
  app/team_test.go
Labels: 4: Reviews Complete, release-note-none

#21843 Automated cherry pick of #21831
  app/platform/config.go
  app/platform/config_test.go
  app/platform/service.go
  app/platform/service_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21847 MM-48984: Add missing timeout while creating a connection
  app/plugin_db_driver.go
  app/plugin_db_driver_test.go
Labels: 2: Dev Review, release-note-none

#21817 MM-48924 Don't cache remote_entry.js files
  web/static.go
  web/web_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21858 Automated cherry pick of #21817
  web/static.go
  web/web_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21859 Automated cherry pick of #21817
  web/static.go
  web/web_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21849 [MM-48098]: "Downgrade to Starter" CTA's go to purchase modal instead of pricing modal
  templates/cloud_45_day_arrears.html
  templates/cloud_90_day_arrears.html
  templates/partials/cloud_title_3subtitles_button.mjml
Labels: release-note-none

#21850 [MM-48091]: Remove is_paid_tier
  api4/cloud.go
  api4/cloud_test.go
  app/user_test.go
  model/cloud.go
Labels: 2: Dev Review, 3: QA Review, release-note-none

#21811 [MM-48622] Set Global Drafts Feature Flag to True
  model/feature_flags.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note-none

#21868 [MM-48946] Fix read after write issue when uploading data
  api4/remote_cluster.go
  api4/upload.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/upload.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/upload_session_store.go
  store/store.go
  store/storetest/mocks/UploadSessionStore.go
  store/storetest/upload_session_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#21804 Self-hosted in-product purchase
  api4/hosted_customer.go
  api4/hosted_customer_test.go
  app/app_iface.go
  app/hosted_customer.go
  app/opentracing/opentracing_layer.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
  model/cloud.go
  model/config.go
  model/hosted_customer.go
  model/websocket_message.go
  services/telemetry/telemetry.go
  web/handlers.go
  web/handlers_test.go
Labels: 2: Dev Review, release-note

#21774 Allow S3 uploads without a timeout for exports
  app/app_iface.go
  app/file.go
  app/opentracing/opentracing_layer.go
  jobs/export_process/worker.go
  shared/filestore/filesstore_test.go
  shared/filestore/s3store.go
Labels: 2: Dev Review, release-note

#21861 product/hooks: hooks service no longer requires channels service start
  app/channels.go
  product/api.go
Labels: 4: Reviews Complete, release-note-none

#21870 [MM-48864] telemetry: add product hooks to daily telemetry
  app/app_iface.go
  app/channels.go
  app/opentracing/opentracing_layer.go
  services/telemetry/mocks/ServerIface.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 4: Reviews Complete, release-note-none

#21885 [MM-49087] Bump NPS to 1.3.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#21879 update pre-package boards to v7.5.4
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#21890 Update minor version to 7.7.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21893 Automated cherry pick of #21879
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21892 Manual cherry pick #21885
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21775 [MM-44347] Add parameter to return group members in order of display name
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/group.go
  app/opentracing/opentracing_layer.go
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#21875 app/product: block products to be initialized with the feature flag
  app/product.go
  app/product_test.go
Labels: 4: Reviews Complete, release-note-none

#21854 [MM-49003] Close the pipe reader when done reading
  jobs/export_process/worker.go
Labels: 2: Dev Review, release-note

#21900 [MM-49172] Close pipes on file writer error
  app/file.go
  app/upload.go
Labels: 2: Dev Review, release-note-none

#21898 [MM-49170] Implement Auditable Interface for Patch Post Struct
  api4/post.go
  model/post.go
Labels: 4: Reviews Complete, release-note-none

#21881 [MM 48128]: Fix Spacing problem on "Payment Failed" email
  templates/payment_failed_no_card_body.html
Labels: release-note-none

#21806 [MM-44842] Add restore_group permission
  api4/group.go
  api4/group_test.go
  app/app_test.go
  app/permissions_migrations.go
  model/migration.go
  model/permission.go
  model/role.go
  testlib/store.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#21896 Use path rather than filepath for embedded files
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#21921 Automated cherry pick of #21774
  app/app_iface.go
  app/file.go
  app/opentracing/opentracing_layer.go
  jobs/export_process/worker.go
  shared/filestore/filesstore_test.go
  shared/filestore/s3store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21919 Automated cherry pick of #21898
  api4/post.go
  model/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21923 Automated cherry pick of #21854
  jobs/export_process/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21730 [MM-48626] Move plugins environment out of Channels
  api4/plugin.go
  api4/plugin_test.go
  api4/websocket.go
  app/app_iface.go
  app/channel.go
  app/channels.go
  app/cluster_handlers.go
  app/collection.go
  app/download.go
  app/file.go
  app/integration_action.go
  app/login.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_commands_test.go
  app/plugin_db_driver.go
  app/plugin_db_driver_test.go
  app/plugin_event.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_requests.go
  app/plugin_requests_test.go
  app/plugin_shutdown_test.go
  app/plugin_signature.go
  app/plugin_statuses.go
  app/plugin_test.go
  app/post.go
  app/reaction.go
  app/server.go
  app/team.go
  app/upload.go
  app/user.go
  app/web_conn.go
  cmd/mattermost/commands/init.go
  web/web_test.go
Labels: 4: Reviews Complete, release-note-none

#21928 Update version to 7.5.3
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21929 Update version to 7.4.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21930 Update version to 7.1.6
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21934 Revert "[MM-48626] Move plugins environment out of Channels (#21730)"
  api4/plugin.go
  api4/plugin_test.go
  api4/websocket.go
  app/app_iface.go
  app/channel.go
  app/channels.go
  app/cluster_handlers.go
  app/collection.go
  app/download.go
  app/file.go
  app/integration_action.go
  app/login.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_commands_test.go
  app/plugin_db_driver.go
  app/plugin_db_driver_test.go
  app/plugin_event.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_requests.go
  app/plugin_requests_test.go
  app/plugin_shutdown_test.go
  app/plugin_signature.go
  app/plugin_statuses.go
  app/plugin_test.go
  app/post.go
  app/reaction.go
  app/server.go
  app/team.go
  app/upload.go
  app/user.go
  app/web_conn.go
  cmd/mattermost/commands/init.go
  web/web_test.go
Labels: 4: Reviews Complete, release-note-none

#21938 Automated cherry pick of #21934
  api4/plugin.go
  api4/plugin_test.go
  api4/websocket.go
  app/app_iface.go
  app/channel.go
  app/channels.go
  app/cluster_handlers.go
  app/collection.go
  app/download.go
  app/file.go
  app/integration_action.go
  app/login.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/plugin_commands.go
  app/plugin_commands_test.go
  app/plugin_db_driver.go
  app/plugin_db_driver_test.go
  app/plugin_event.go
  app/plugin_hooks_test.go
  app/plugin_install.go
  app/plugin_install_test.go
  app/plugin_requests.go
  app/plugin_requests_test.go
  app/plugin_shutdown_test.go
  app/plugin_signature.go
  app/plugin_statuses.go
  app/plugin_test.go
  app/post.go
  app/reaction.go
  app/server.go
  app/team.go
  app/upload.go
  app/user.go
  app/web_conn.go
  cmd/mattermost/commands/init.go
  web/web_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21924 Cherry-picking translations
  i18n/de.json
  i18n/ja.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#21911 MM-49077: fixes errors in migration job
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#21941 Automated cherry pick of #21911
  store/sqlstore/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21940 always set CWSURL in client config
  config/client.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#21945 Automated cherry pick of #21940
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21944 Automated cherry pick of #21940
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21946 Add comments for the subscriptionHistoryEvent call
  app/user.go
Labels: 2: Dev Review, release-note-none

#21857 [MM-48878] cmd/mattermost/export: start export command without metrics
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/export.go
  cmd/mattermost/commands/init.go
  cmd/mattermost/commands/jobserver.go
  cmd/mattermost/commands/test.go
Labels: 4: Reviews Complete, release-note

#21948 sqlstore/store: make SetupConnection public to be used by products
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#21943 MM-49354: Make compliance export query cancellable
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/compliance_store.go
  store/sqlstore/sqlx_wrapper.go
  store/store.go
  store/storetest/compliance_store.go
  store/storetest/mocks/ComplianceStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#21917 Expose boards APIs for MPA
  go.mod
  go.sum
  product/api.go
  product/service.go
Labels: 2: Dev Review, release-note-none

#21935 Improve bulk export logging
  app/export.go
  jobs/export_process/worker.go
Labels: 4: Reviews Complete, release-note

#21950 Add DuplicateBoard to service API
  product/api.go
Labels: 4: Reviews Complete, release-note-none

#21925 Message export: Fix job progress calculation
  i18n/en.json
  model/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#21770 Mm 47648 check license expandable
  api4/cloud.go
  api4/cloud_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  model/client4.go
  model/cloud.go
Labels: release-note

#21954 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#21959 Remove unnecessary debug log
  api4/drafts.go
Labels: 4: Reviews Complete, release-note-none

#21961 dry up some code. Move other code to app layer
  api4/license.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/true_up.go
Labels: release-note-none

#21788 [MM-47805] Remove CRT feature flag
  api4/channel_test.go
  api4/post_test.go
  api4/user_test.go
  app/channel_test.go
  app/notification.go
  app/notification_test.go
  app/post_test.go
  app/user_test.go
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note
