Repository mattermost/mattermost, pull requests merged in 2022-07, with the labels that each got.

#20590 [MM-45084] Pre-package Calls v0.7.0 for v7.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20591 Automated cherry pick of #20590
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20592 Automated cherry pick of #20590
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20410 Moved UserHasJoinedTeam after the processing
  app/team.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20362 [MM-44488] Cloud limits: enforcing messages
  api4/post.go
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_helpers.go
  app/post_helpers_test.go
  app/post_metadata.go
  app/post_test.go
  app/server.go
  i18n/en.json
  jobs/last_accessible_post/scheduler.go
  jobs/last_accessible_post/worker.go
  model/client4.go
  model/job.go
  model/post_list.go
  model/system.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchtest/helper.go
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/timerlayer/timerlayer.go
Labels: Setup Cloud Test Server, QA Review Done, release-note

#20594 Automated cherry pick of #20410
  app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20607 Automated cherry pick of #20598
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  jobs/base_workers.go
  jobs/last_accessible_post/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20609 MM-45536: Track GraphQL queries in Grafana
  api4/graphql.go
  web/context.go
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#20593 Update boards to v7.1.0
  Makefile
Labels: CherryPick/Approved, release-note

#20618 Automated cherry pick of #20593
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20620 Pre-package Playbooks v1.29.0
  Makefile
Labels: 4: Reviews Complete, release-note

#20621 Automated cherry pick of #20620
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20623 Automated cherry pick of #20620
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20595 [MM-45504] Improve GIF preprocessing logic
  app/post_metadata.go
  app/upload.go
  app/upload_test.go
  i18n/en.json
  model/file_info.go
  utils/imgutils/gif.go
  utils/imgutils/gif_test.go
Labels: release-note-none

#20613 MM-45168 Added GraphQL fields to channel and channel_member
  api4/resolver_channel_member_test.go
  api4/resolver_channel_test.go
  api4/schema.graphqls
  model/channel.go
  model/channel_member.go
Labels: 4: Reviews Complete, release-note-none

#20603 Usage: Round messages to 1K, files to 100MB
  api4/usage.go
  app/usage.go
  services/telemetry/telemetry.go
  utils/utils.go
  utils/utils_test.go
Labels: 2: Dev Review, release-note, Setup Cloud + CWS Test Server

#20599 MM-45395: Exclude bot and webhook posts from Top Team Channels. Exclude webhook posts from My Top Channels.
  app/channel_test.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 3: QA Review, Setup Cloud Test Server, QA Deferred, release-note-none

#20611 General GraphQL resolver optimizations
  api4/resolver_channel.go
  api4/resolver_channel_test.go
  api4/resolver_team.go
Labels: 4: Reviews Complete, release-note-none

#20610 MM-45168 GraphQL: add fields to Team
  api4/resolver_team_member_test.go
  api4/schema.graphqls
  model/team.go
Labels: release-note-none

#20572 [MM-45444] Denormalize Reactions to add ChannelId for top reactions insights query
  db/migrations/migrations.list
  db/migrations/mysql/000089_add-channelid-to-reaction.down.sql
  db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.down.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
  model/reaction.go
  store/sqlstore/integrity_test.go
  store/sqlstore/reaction_store.go
  store/storetest/reaction_store.go
Labels: 3: QA Review, CherryPick/Approved, QA Deferred, release-note

#20578 [MM-44691] Adding gender neutral doctor-emoji
  model/emoji_data.go
Labels: release-note-none, Contributor

#20627 Automated cherry pick of #20572
  db/migrations/migrations.list
  db/migrations/mysql/000089_add-channelid-to-reaction.down.sql
  db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.down.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
  model/reaction.go
  store/sqlstore/integrity_test.go
  store/sqlstore/reaction_store.go
  store/storetest/reaction_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20628 Automated cherry pick of #20599
  app/channel_test.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20629 Automated cherry pick of #20572
  db/migrations/migrations.list
  db/migrations/mysql/000089_add-channelid-to-reaction.down.sql
  db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.down.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
  model/reaction.go
  store/sqlstore/integrity_test.go
  store/sqlstore/reaction_store.go
  store/storetest/reaction_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20608 Additional APIs for Focalboard multi-product architecture
  app/channel.go
  app/permissions.go
  product/api.go
Labels: 2: Dev Review, release-note-none

#20624 Fix incorrect dead queue clear logic
  app/web_conn.go
  app/web_conn_test.go
Labels: 4: Reviews Complete, release-note-none

#20597 [MM-45490] Adding compliance export config to client
  config/client.go
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none

#20601 Add DB enums
  db/migrations/migrations.list
  db/migrations/mysql/000090_create_enums.down.sql
  db/migrations/mysql/000090_create_enums.up.sql
  db/migrations/postgres/000090_create_enums.down.sql
  db/migrations/postgres/000090_create_enums.up.sql
Labels: 4: Reviews Complete, release-note

#20630 Fix weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none, Do Not Merge/Mattermod

#20626 [MM-43787] Replace hardcoded PGP key with embedded one
  services/upgrader/pubkey.gpg
  services/upgrader/upgrader_linux.go
Labels: 4: Reviews Complete, release-note-none

#20634 MM-45535: Batch optimize auth checks in GraphQL
  api4/resolver_channel_member.go
  api4/resolver_team.go
  app/app_iface.go
  app/authorization.go
  app/opentracing/opentracing_layer.go
  model/session.go
Labels: 4: Reviews Complete, release-note-none

#20639 Automated cherry pick of #20638
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20525 Make three file settings editable in Cloud System Console UI
  model/config.go
Labels: 4: Reviews Complete, QA Review Done, AutoMerge, release-note-none, Setup Cloud + CWS Test Server

#20641 Clarify collation mismatch string
  store/sqlstore/store.go
Labels: 4: Reviews Complete, release-note-none

#20581 MM-45174 - split validate business email logic
  api4/cloud.go
  api4/cloud_test.go
  model/client4.go
Labels: 2: Dev Review, release-note-none

#20643 Coalesce migration of Reactions.ChannelId to '' if Post does not exist.
  db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, release-note-none

#20645 Automated cherry pick of #20643
  db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
  db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20642 Weblate 20220713
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none, Do Not Merge/Mattermod

#20647 MM-45725: Skip BusySet
  app/busy_test.go
Labels: 4: Reviews Complete, release-note-none

#20650 Update version to 7.1.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20649 Update minor version to 7.2.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20661 Update version to 7.1.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20652 Enable GraphQL in dev environments
  Makefile
Labels: 4: Reviews Complete, release-note-none

#20663 Fix broken master; ensure all product service APIs have correct implementations
  app/app.go
  app/bot.go
  app/channel.go
  app/channels.go
  app/cloud.go
  app/cluster.go
  app/config.go
  app/file.go
  app/license.go
  app/permissions.go
  app/plugin.go
  app/plugin_key_value_store.go
  app/post.go
  app/server.go
  app/team.go
  product/api.go
  store/store.go
Labels: 2: Dev Review, release-note-none

#20646 GraphQL: Add missing fields
  api4/resolver_user_test.go
  api4/schema.graphqls
  model/channel.go
  model/role.go
  model/session.go
  model/user.go
  model/utils.go
Labels: 4: Reviews Complete, release-note-none

#20659 [MM-45769] Properly initialize the request.Context for imports and tests
  app/product_notices_test.go
  app/teams/helper_test.go
  app/users/helper_test.go
  cmd/mattermost/commands/import.go
  cmd/mattermost/commands/init.go
  jobs/import_process/worker.go
  services/slackimport/slackimport_test.go
  web/context_test.go
  web/oauth_test.go
Labels: release-note-none

#20670 Update latest version to 7.1.0
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20653 [MM-45684] - Self Managed: Add pricing modal + Upgrade button
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, release-note

#20648 MM-44542: Add timeout to S3 operations
  i18n/en.json
  model/config.go
  shared/filestore/filesstore.go
  shared/filestore/filesstore_test.go
  shared/filestore/s3store.go
  shared/filestore/s3store_test.go
Labels: 4: Reviews Complete, release-note

#20571 Make 'DisableBotsWhenOwnerIsDeactivated' and 'HelpLink' editable in Cloud
  model/config.go
Labels: 4: Reviews Complete, QA Review Done, AutoMerge, release-note-none

#20669 [feat] Notice.txt generation configuration
  build/notice-file/Readme.md
  build/notice-file/config.yaml
Labels: Changelog/Not Needed, Docs/Not Needed, Tests/Not Needed, QA/Tests Not Required

#20673 Revert "[MM-45684] - Self Managed: Add pricing modal + Upgrade button"
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#20672 Translations update from Mattermost Weblate
  i18n/nl.json
Labels: release-note-none, Do Not Merge/Mattermod

#20678 Update latest version to 7.1.1
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20666 [MM-44365] Add values and operation to the condition checks
  store/storetest/group_store.go
Labels: 4: Reviews Complete, release-note-none

#20612 Removed opengraph type dependency for plugins by stripping post Metadata
  app/plugin_api.go
  app/post.go
  model/post.go
  model/post_list.go
  model/post_search_results.go
  plugin/client_rpc.go
Labels: 4: Reviews Complete, release-note-none

#20679 app/platform: add initial platform service skeleton
  app/platform/config.go
  app/platform/service.go
Labels: 4: Reviews Complete, release-note-none

#20689 Update version to 7.1.3
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20691 Update latest version to 7.1.2
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20686 MM-45208: strip post meta for plugins
  app/plugin_api.go
  app/post.go
  model/post.go
  model/post_list.go
  model/post_search_results.go
  plugin/client_rpc.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#20414 [MM-44948] Update sync
  services/sharedchannel/sync_send_remote.go
Labels: 3: QA Review, release-note-none

#20430 Store plugin OnActivate errors and include them in PluginStatus response
  app/plugin_test.go
  model/plugin_status.go
  plugin/environment.go
Labels: 4: Reviews Complete, release-note

#20279 [MM-42194] Get file information from a deleted post
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_metadata.go
  app/post_test.go
  model/client4.go
Labels: 4: Reviews Complete, release-note, Contributor

#20695 Automated cherry pick of #20686
  app/plugin_api.go
  app/post.go
  model/post.go
  model/post_list.go
  model/post_search_results.go
  plugin/client_rpc.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20696 Automated cherry pick of #20414
  services/sharedchannel/sync_send_remote.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20697 Automated cherry pick of #20430
  app/plugin_test.go
  model/plugin_status.go
  plugin/environment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20681 [MM-45862] Set size and extension to fileinfo
  api4/upload_test.go
  app/upload.go
  model/file_info.go
Labels: 4: Reviews Complete, release-note-none

#20699 Automated cherry pick of #20681
  api4/upload_test.go
  app/upload.go
  model/file_info.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20166 [MM-22846]: add a feature flag for post forwarding
  model/feature_flags.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#20700 Automated cherry pick of #20166
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20701 MM-45000: Upgrade to new opengraph module path
  app/post_metadata_test.go
  go.mod
  go.sum
  model/link_metadata.go
  model/link_metadata_test.go
  store/storetest/link_metadata_store.go
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR, release-note-none

#20694 MM-45875: Apply environment overrides in cluster scenario
  config/store.go
Labels: 4: Reviews Complete, CherryPick/Candidate, AutoMerge, release-note-none

#20683 move metrics server into platform service
  api4/apitestlib.go
  app/config.go
  app/platform/config.go
  app/platform/metrics.go
  app/platform/service.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#20706 Killing dyatlov/go-opengraph with fire
  go.mod
Labels: 2: Dev Review, release-note-none

#20676 [MM-45666] - A/B Test: Nav Bar Upgrade button
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#20657 Mm 43609
  api4/post.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_helpers.go
  app/post_helpers_test.go
  app/post_metadata.go
  model/client4.go
  model/post_list.go
Labels: release-note

#20709 Automated cherry pick of #20676
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20698 MM-45871: Do not try to extract content from images
  app/file.go
  app/file_test.go
Labels: 4: Reviews Complete, release-note-none

#20555 Hackathon: Post Reminders
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/channels.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/server.go
  db/migrations/migrations.list
  db/migrations/mysql/000091_create_post_reminder.down.sql
  db/migrations/mysql/000091_create_post_reminder.up.sql
  db/migrations/postgres/000091_create_post_reminder.down.sql
  db/migrations/postgres/000091_create_post_reminder.up.sql
  i18n/en.json
  model/client4.go
  model/post.go
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#20692 [MM-45817] Set cloud cookies whenever user gets logged in
  api4/user.go
  api4/user_test.go
  app/login.go
Labels: 2: Dev Review, release-note-none, Setup Cloud + CWS Test Server

#20677 Support hiding plugin settings based on hosting environment
  model/manifest.go
Labels: 4: Reviews Complete, QA Review Done, release-note

#20717 Added schema migration template to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#20707 Replace ioutil.Discard with io.Discard
  api4/apitestlib.go
  api4/brand.go
  api4/emoji.go
  api4/remote_cluster.go
  api4/system.go
  api4/team.go
  api4/user.go
  app/admin.go
  app/download.go
  app/notification_push.go
  app/post_metadata.go
  app/slashcommands/command_loadtest.go
  model/client4.go
  services/marketplace/client.go
  services/remotecluster/sendprofileImage_test.go
  shared/mail/inbucket.go
Labels: release-note-none

#20711 MM-43828: Pass object length for some image operations
  app/app_iface.go
  app/file.go
  app/file_bench_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_hooks_test.go
  i18n/en.json
  shared/filestore/s3store.go
Labels: 4: Reviews Complete, release-note-none

#20715 [MM-45715] Check for correct permission when requesting teams
  api4/resolver_team.go
  api4/resolver_team_member_test.go
Labels: 4: Reviews Complete, release-note-none

#20726 Revert "move metrics server into platform service"
  api4/apitestlib.go
  app/config.go
  app/platform/config.go
  app/platform/metrics.go
  app/platform/service.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#20674 MM-45194: Switch app/user and api4/user to logger context
  api4/apitestlib.go
  api4/bot.go
  api4/bot_test.go
  api4/post_test.go
  api4/remote_cluster.go
  api4/resolver_user_test.go
  api4/shared_channel_test.go
  api4/status.go
  api4/system_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/auto_responder.go
  app/auto_responder_test.go
  app/bot_test.go
  app/channel_test.go
  app/helper_test.go
  app/import_functions.go
  app/login.go
  app/notification_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/slashcommands/command_custom_status.go
  app/slashcommands/helper_test.go
  app/status.go
  app/status_test.go
  app/syncables_test.go
  app/team.go
  app/user.go
  app/user_test.go
  app/user_viewmembers_test.go
  einterfaces/ldap.go
  einterfaces/mocks/LdapInterface.go
  product/api.go
Labels: 4: Reviews Complete, release-note-none

#20728 Fix bad merge due to https://github.com/mattermost/mattermost-server/pull/20674
  api4/resolver_team_member_test.go
Labels: 4: Reviews Complete, release-note-none

#20682 MM-45713 - change 500 error to json object
  api4/cloud.go
  api4/cloud_test.go
  model/cloud.go
Labels: 2: Dev Review, release-note-none, Setup Cloud + CWS Test Server

#20565 MM-45272: Fix getPostThread permissions
  api4/post.go
  api4/post_test.go
  i18n/en.json
Labels: release-note

#20724 [MM-45990] log JSON parsing errors in API4
  api4/bot.go
  api4/channel.go
  api4/channel_category.go
  api4/channel_local.go
  api4/cloud.go
  api4/command.go
  api4/command_local.go
  api4/command_test.go
  api4/compliance.go
  api4/config.go
  api4/config_local.go
  api4/data_retention.go
  api4/emoji.go
  api4/file.go
  api4/file_test.go
  api4/graphql.go
  api4/graphql_client.go
  api4/group.go
  api4/integration_action.go
  api4/job.go
  api4/ldap.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/post_test.go
  api4/preference.go
  api4/reaction.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/status.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/terms_of_service.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/webhook.go
  api4/webhook_local.go
  app/plugin_api_test.go
  app/plugin_test.go
  model/utils.go
  model/utils_test.go
  shared/mail/inbucket.go
  store/storetest/team_store.go
  testlib/assertions.go
  web/context.go
Labels: 4: Reviews Complete, release-note-none

#20733 Update post reminder text
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#20731 MM-45715: Fix incorrect permissions (Round 2)
  api4/resolver_team_member_test.go
  app/authorization.go
Labels: 4: Reviews Complete, 3: QA Review, release-note-none

#20615 MM-43939: fixes LastReplyAt when deleting the last reply
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note

#20740 Revert "MM-43828: Pass object length for some image operations"
  app/app_iface.go
  app/file.go
  app/file_bench_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_hooks_test.go
  i18n/en.json
  shared/filestore/s3store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none
