Repository mattermost/mattermost, pull requests merged in 2022-10, with the labels that each got.

#21029 Fix delinquency emails
  templates/cloud_14_day_arrears.html
  templates/cloud_30_day_arrears.html
  templates/cloud_30_day_arrears.mjml
  templates/cloud_45_day_arrears.html
  templates/cloud_7_day_arrears.html
  templates/cloud_90_day_arrears.html
  templates/cloud_upgrade_confirmation.html
  templates/inactivity_body.html
  templates/invite_body.html
  templates/license_up_for_renewal.html
  templates/messages_notification.html
  templates/partials/style.css
  templates/payment_failed_body.html
  templates/reset_body.html
  templates/verify_body.html
  templates/welcome_body.html
Labels: release-note-none, Setup Cloud + CWS Test Server

#21176 Mm 46416 add default random message
  app/notification_email.go
  shared/mail/mail.go
  shared/mail/mail_test.go
Labels: Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note, Contributor

#21147 Eventbus tests
  shared/eventbus/eventbus.go
  shared/eventbus/eventbus_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#21221 [MM-44400]: removed feature flag for Advanced Text Editor
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none, kind/chore

#21242 fix a data race in the platform service
  app/platform/helper_test.go
  app/platform/service.go
  app/platform/web_hub.go
  app/platform/web_hub_test.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#21233 MM-47374: Revert full text search
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21262 Manual cherry pick of #21233
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#21267 Pre-package Playbooks v1.32.4
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#21271 Automated cherry pick of #21267
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21206 Update prepackaged boards to v7.4.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21268 MM-47037 - Prepackage Calls v0.9.0
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#21275 Automated cherry pick of #21267
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21274 Automated cherry pick of #21206
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21277 Automated cherry pick of #21268
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21273 Automated cherry pick of #21206
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21281 app/platform: move failover config initialization to platform
  app/platform/config.go
  app/platform/service.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#21280 MM-47403: Populate the productHooks field
  plugin/interface_generator/main.go
  plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, release-note-none

#20900 [MM-46644] Auto respond message
  model/utils.go
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#21284 Automated cherry pick of #20900
  model/utils.go
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21276 Automated cherry pick of #21268
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21285 Automated cherry pick of #21281
  app/platform/config.go
  app/platform/service.go
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21195 MM-47228 - restrict guest invitation flow if subscription plan does n…
  api4/team.go
  api4/team_test.go
  api4/user.go
  api4/user_test.go
  i18n/en.json
  model/license.go
Labels: 3: QA Review, release-note-none, Setup Cloud + CWS Test Server

#21286 Automated cherry pick of #21195
  api4/team.go
  api4/team_test.go
  api4/user.go
  api4/user_test.go
  i18n/en.json
  model/license.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21175 MM-29625: Remove CloudBilling Feature Flag
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#21288 Update prepackaged boards to v7.4.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21295 Automated cherry pick of #21288
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21294 Automated cherry pick of #21288
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21243 MM-47249: Blocklist focalboard plugin in product mode
  api4/config.go
  app/plugin.go
  i18n/en.json
  plugin/environment.go
Labels: 4: Reviews Complete, release-note-none

#21143 Update supported versions
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#21038 Do not send categories for teams deleted or not member of
  store/sqlstore/channel_store_categories.go
  store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, release-note

#21304 [MM-47367] Make sure mini preview is saved to database when updating database
  store/sqlstore/file_info_store.go
  store/storetest/file_info_store.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#21374 [MM-47468] Fix store metrics initialization
  app/platform/cluster.go
  app/platform/config.go
  app/platform/enterprise.go
  app/platform/helper_test.go
  app/platform/log.go
  app/platform/metrics.go
  app/platform/options.go
  app/platform/service.go
  app/platform/service_test.go
  app/platform/session.go
  app/platform/web_conn.go
  app/platform/web_hub.go
Labels: 4: Reviews Complete, release-note-none

#21376 Pre-package Playbooks v1.32.5
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#21109 Contribute Voice Message: Add initial config for voice messages
  api4/post.go
  app/post.go
  app/post_test.go
  config/client.go
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  i18n/en.json
  model/config.go
  model/feature_flags.go
  model/file_info.go
  model/file_info_test.go
  model/post.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, release-note-none

#21380 Automated cherry pick of #21376
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21383 Automated cherry pick of #21376
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21382 Update prepackage boards v7.4.2
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#21384 Automated cherry pick of #21382
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21385 Automated cherry pick of #21382
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21397 Update version to 7.2.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21393 Typo ExperimentalEnableVoiceMessage -> ExperimentalEnableVoiceMessages
  config/client.go
Labels: release-note-none

#20926 [MM-46694] A/B Test: welcome post
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
  model/feature_flags.go
  model/post.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: CherryPick/Candidate, QA Review Done, release-note-none, Setup Cloud + CWS Test Server

#21403 Automated cherry pick of #20926
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
  model/feature_flags.go
  model/post.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21405 Update minor version to 7.5.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21406 Update version to 7.4.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21377 GraphQL: Remove channel stats from the API
  api4/resolver_channel.go
  api4/resolver_channel_test.go
  api4/schema.graphqls
Labels: 4: Reviews Complete, release-note-none

#21045 new ui for email verification due to change in the email address
  app/email/email.go
  i18n/en.json
  templates/email_change_verify_body.html
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Setup Cloud Test Server, QA Review Done, release-note-none

#21408 Update version to 7.3.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21392 MM-47465: Skip flaky TestDeleteChannel
  api4/channel_test.go
Labels: 4: Reviews Complete, release-note-none

#21049 [MM-22831] nested config value setting using env vars
  config/environment.go
  config/environment_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note, Contributor

#21436 Updated CodeQL to use latest version
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: release-note-none

#21425 MM-47612: Skip flaky test TestPluginAPIDeleteUserPreferences
  app/plugin_api_test.go
Labels: 4: Reviews Complete, release-note-none

#21410 Mm 46549 gather intent cloud monthly subscription
  model/cloud.go
Labels: 2: Dev Review, release-note-none

#21251 [MM-47230] Apply role filters for /get/users in channel
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: Setup Cloud Test Server, release-note

#21391 MM-45723: Include DM/GM channels for user indexing
  store/searchlayer/user_layer.go
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note

#21333 MM-47250: Add new system console section
  app/permissions_migrations.go
  model/config.go
  model/migration.go
  model/permission.go
  model/role.go
  services/telemetry/telemetry.go
  testlib/store.go
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR, release-note

#21378 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Do Not Merge/Mattermod

#21441 [MM-47538] Pass handler functions directly while creating API endpoints
  api4/group.go
  api4/group_local.go
  api4/handlers.go
  api4/insights.go
Labels: release-note-none

#20946 Slack attachment in email notifications
  app/notification_email.go
  app/notification_email_test.go
  templates/invite_body.mjml
  templates/messages_notification.html
  templates/messages_notification.mjml
  templates/partials/card.mjml
  templates/partials/message_attachment.css
  templates/partials/message_attachment.html
  templates/partials/message_attachment_styles.mjml
  templates/partials/message_avatar_col.mjml
  templates/partials/message_button.mjml
  templates/partials/sender_info_col.mjml
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#21439 Replace 500 errors with more meaningful error codes
  api4/cloud.go
  api4/cloud_test.go
  model/client4.go
Labels: 2: Dev Review, release-note-none, Setup Cloud + CWS Test Server

#21456 Automated cherry pick of #21439
  api4/cloud.go
  api4/cloud_test.go
  model/client4.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21452 Fix translations
  i18n/de.json
  i18n/es.json
  i18n/nl.json
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#21048 [MM-45052] Add error checking in insights API
  api4/insights.go
  api4/insights_test.go
  app/channel_test.go
  app/reaction_test.go
  i18n/en.json
  model/insights.go
Labels: 4: Reviews Complete, release-note-none

#21365 move file backend to the platform service
  app/notification_push_test.go
  app/options.go
  app/platform/options.go
  app/platform/service.go
  app/server.go
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#21042 add PeopleProduct feature flag
  model/feature_flags.go
Labels: release-note-none

#21481 Update prepackage boards to v7.4.3
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21433 Display board statistics
  app/permissions.go
  product/api.go
Labels: 2: Dev Review, release-note

#21459 Cherry-picking translations into cloud
  i18n/de.json
  i18n/es.json
  i18n/nl.json
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#21482 Automated cherry pick of #21481
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21272 [MM-46440]: Update Logo and Remove grey email border
  templates/cloud_14_day_arrears.html
  templates/cloud_30_day_arrears.html
  templates/cloud_45_day_arrears.html
  templates/cloud_7_day_arrears.html
  templates/cloud_90_day_arrears.html
  templates/cloud_upgrade_confirmation.html
  templates/cloud_welcome_email.html
  templates/inactivity_body.html
  templates/invite_body.html
  templates/license_up_for_renewal.html
  templates/messages_notification.html
  templates/partials/style.css
  templates/password_change_body.html
  templates/payment_failed_body.html
  templates/reset_body.html
  templates/reset_body.mjml
  templates/verify_body.html
  templates/welcome_body.html
  templates/welcome_body.mjml
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#21483 Automated cherry pick of #21481
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21429 [MM-47560]: In-product: Add support for new fields (back-end and front-end)
  api4/cloud_test.go
  model/cloud.go
  templates/cloud_30_day_arrears.html
Labels: 2: Dev Review, release-note-none

#21227 MM-46528_Verify Invitation Flow Tracking Telemetry
  api4/team_local.go
  app/app_iface.go
  app/email/email.go
  app/email/email_test.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/email/utils.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/team_test.go
  app/user.go
Labels: 2: Dev Review, 3: QA Review, release-note-none

#21488 MM-46528_Verify Invitation Flow Tracking Telemetry - Fix build
  app/opentracing/opentracing_layer.go
  app/user.go
Labels: 2: Dev Review, release-note-none

#21491 MM-40690: Populate the error message with email address
  model/user.go
  model/user_test.go
Labels: 4: Reviews Complete, release-note-none

#21493 db/migrations: ensure to drop parentid from posts table
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#21151 [MM-42421] Prevent guests from seeing users through groups API
  api4/group.go
  api4/group_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/group.go
  app/group_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#21504 Automated cherry pick of #21151
  api4/group.go
  api4/group_test.go
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/group.go
  app/group_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21490 MM-47884: Migrate config state from focalboard plugin
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#21401 MM-46275/MM-46979 Production MPA for web app
  .circleci/config.yml
  app/platform/service_test.go
  build/release.mk
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#21435 MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA
  web/handlers.go
Labels: 4: Reviews Complete, release-note-none

#21497 platform/service: fix a flaky test for metrics
  app/platform/service.go
Labels: 2: Dev Review, release-note-none

#21492 MM-46874: Change to 400 for failed to upgrade ws
  api4/apitestlib.go
  api4/websocket.go
  api4/websocket_test.go
Labels: 4: Reviews Complete, release-note-none

#21519 Automated cherry pick of #21433
  app/permissions.go
  product/api.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21400 [MM-44336] Add timestamp parameter to test data slash commands
  app/slashcommands/auto_channels.go
  app/slashcommands/auto_posts.go
  app/slashcommands/auto_users.go
  app/slashcommands/command_loadtest.go
  model/user.go
  store/sqlstore/team_store.go
Labels: 4: Reviews Complete, release-note-none

#21505 [MM-45868] Replace TeamId column with ThreadTeamId
  db/migrations/migrations.list
  db/migrations/mysql/000094_threads_teamid.down.sql
  db/migrations/mysql/000094_threads_teamid.up.sql
  db/migrations/mysql/000096_threads_threadteamid.down.sql
  db/migrations/mysql/000096_threads_threadteamid.up.sql
  db/migrations/postgres/000094_threads_teamid.down.sql
  db/migrations/postgres/000094_threads_teamid.up.sql
  db/migrations/postgres/000096_threads_threadteamid.down.sql
  db/migrations/postgres/000096_threads_threadteamid.up.sql
  model/thread.go
  store/sqlstore/integrity.go
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
Labels: release-note

#21449 [Contribute/voice-message] Add voice message duration limit config
  app/av/mp3/parser.go
  app/helper_test.go
  app/post.go
  app/post_test.go
  config/client.go
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, AutoMerge, release-note-none

#21521 Change status code to 400 when attempting to enable Boards plugin with product enabled
  api4/config.go
  app/plugin.go
Labels: 4: Reviews Complete, release-note-none

#21516 MM-47736: Add jitter to job scheduler run time
  jobs/base_schedulers.go
  jobs/schedulers_test.go
Labels: 2: Dev Review, release-note-none

#21501 Fixed job.IsValid and added tests
  model/job.go
  model/job_test.go
Labels: 4: Reviews Complete, release-note-none

#21526 MM-46450: Enable skipped test
  api4/user_test.go
Labels: 4: Reviews Complete, release-note-none

#21500 MM-47861 Set paniced jobs to "failed"
  jobs/active_users/worker.go
  jobs/expirynotify/worker.go
  jobs/export_delete/worker.go
  jobs/export_process/worker.go
  jobs/extract_content/worker.go
  jobs/import_delete/worker.go
  jobs/import_process/worker.go
  jobs/jobs.go
  jobs/jobs_test.go
  jobs/last_accessible_file/worker.go
  jobs/last_accessible_post/worker.go
  jobs/migrations/worker.go
  jobs/notify_admin/worker.go
  jobs/product_notices/worker.go
  jobs/resend_invitation_email/worker.go
Labels: 4: Reviews Complete, release-note

#21486 Mm 46549 gather intent cloud monthly subscription
  model/cloud.go
Labels: 2: Dev Review, release-note-none

#21537 MM-46275/MM-46979 Production MPA for web app (#21401)
  .circleci/config.yml
  app/platform/service_test.go
  build/release.mk
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#21513 Actually build Boards product files in release builds
  .circleci/config.yml
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#21508 MM-47838 - Conclude A/B test for upgrade button
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note-none

#21544 Automated cherry pick of #21513
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21535 Automated cherry pick of #21048
  api4/insights.go
  api4/insights_test.go
  app/channel_test.go
  app/reaction_test.go
  i18n/en.json
  model/insights.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21545 Automated cherry pick of #21508
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21532 Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.1
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 2: Dev Review, release-note

#21531 Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.2
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 2: Dev Review, release-note

#21546 Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.5
  db/migrations/migrations.list
  db/migrations/mysql/000095_remove_posts_parentid.down.sql
  db/migrations/mysql/000095_remove_posts_parentid.up.sql
  db/migrations/postgres/000095_remove_posts_parentid.down.sql
  db/migrations/postgres/000095_remove_posts_parentid.up.sql
Labels: 4: Reviews Complete, release-note

#21542 Actually build Boards product files in release builds (#21513)
  .circleci/config.yml
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#21543 Upgrade NPS plugin to v1.3.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note

#21550 Automated cherry pick of #21543
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21549 app/platform: fix an issue about accessing to a closed db on shutdown
  app/platform/goroutines.go
  app/platform/service.go
  app/platform/service_test.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#21447 [MM-47716] Fix error in case of no cloud limits
  app/post.go
  app/post_test.go
Labels: 4: Reviews Complete, release-note-none
