Repository mattermost/mattermost, pull requests merged in 2022-05, with the labels that each got.

#20125 MM-41153: Add seats deployed to support packet
  app/server.go
  app/server_test.go
  app/support_packet.go
  app/support_packet_test.go
  model/system.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#20138 Update Dockerfile to 1.18.1
  build/Dockerfile.buildenv
Labels: 4: Reviews Complete, release-note-none

#20143 Automated cherry pick of #20138
  build/Dockerfile.buildenv
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20142 Automated cherry pick of #20138
  build/Dockerfile.buildenv
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20140 MM-43341: Fix flaky TestImportImportUser
  app/import_functions_test.go
Labels: 4: Reviews Complete, release-note-none

#20145 Automated cherry pick of #20137
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20133 MM-42997: Fix flaky TestDeletePostEvent
  api4/post_test.go
Labels: 4: Reviews Complete, release-note-none

#20134 [MM-43920] - Set Workspace Inactivity Email to only fire once and change subject
  app/email/email.go
  app/server_inactivity.go
  i18n/en.json
  templates/inactivity_body.html
  templates/inactivity_body.mjml
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#20150 Automated cherry pick of #20134
  app/email/email.go
  app/server_inactivity.go
  i18n/en.json
  templates/inactivity_body.html
  templates/inactivity_body.mjml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20148 [MM-43644] Prepackage Calls v0.4.9
  Makefile
  build/release.mk
Labels: 4: Reviews Complete, release-note

#20146 GraphQL: Unlock goroutine throttle to match batch capacity
  api4/graphql.go
  api4/resolver.go
  api4/resolver_user.go
  app/app_iface.go
  app/bot.go
  app/cloud.go
  app/export_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/slashcommands/auto_channels.go
  app/user.go
  app/user_viewmembers_test.go
  app/users/users.go
Labels: 4: Reviews Complete, release-note-none

#20155 MM-44044: Fix racy TestGraphQLChannelMembers
  api4/resolver_user.go
Labels: 4: Reviews Complete, release-note-none

#20153 Fixes: make run-server command
  Makefile
Labels: release-note-none

#20156 Update README.md
  README.md
Labels: 2: Dev Review, 1: PM Review, release-note-none

#19543 fix case studies link on README
  README.md
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#20159 [MM-43053] app/server: shutdown products before closing the store
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#20158 [MM-43354] update dependencies
  go.mod
  go.sum
Labels: 4: Reviews Complete, release-note-none

#20157 update make update dependencies rule
  Makefile
Labels: 4: Reviews Complete, release-note-none

#20063 Respect send push proxy notification configuration on test notifications
  app/channel.go
  app/expirynotify.go
  app/notification.go
  app/notification_push.go
Labels: 4: Reviews Complete, release-note

#20117 Bumps ES minor version.
  build/docker-compose.common.yml
  build/gitlab-dc.common.yml
Labels: QA Deferred, release-note

#20169 Automated cherry pick of #20063
  app/channel.go
  app/expirynotify.go
  app/notification.go
  app/notification_push.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20171 app/cluster.go: add PublishWebSocketEvent method
  app/cluster.go
Labels: 4: Reviews Complete, release-note-none

#20162 s/masterminds/mattermost for squirrel
  go.mod
  go.sum
  store/sqlstore/audit_store.go
  store/sqlstore/channel_member_history_store.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/cluster_discovery_store.go
  store/sqlstore/command_store.go
  store/sqlstore/command_webhook_store.go
  store/sqlstore/compliance_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/group_store.go
  store/sqlstore/integrity.go
  store/sqlstore/job_store.go
  store/sqlstore/license_store.go
  store/sqlstore/link_metadata_store.go
  store/sqlstore/plugin_store.go
  store/sqlstore/post_store.go
  store/sqlstore/preference_store.go
  store/sqlstore/product_notices_store.go
  store/sqlstore/reaction_store.go
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/role_store.go
  store/sqlstore/scheme_store.go
  store/sqlstore/session_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/status_store.go
  store/sqlstore/store.go
  store/sqlstore/system_store.go
  store/sqlstore/team_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/tokens_store.go
  store/sqlstore/upload_session_store.go
  store/sqlstore/user_store.go
  store/sqlstore/webhook_store.go
Labels: 4: Reviews Complete, release-note-none

#20161 [MM-44056] Make Calls plugin's state on Cloud controllable by feature flag
  Makefile
  app/plugin.go
  app/plugin_install.go
  app/plugin_test.go
  build/release.mk
  model/config.go
  model/config_test.go
  model/feature_flags.go
  model/utils.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#20173 Divide TrialEnd date by 1000 to account for it being in ms
  app/cloud.go
Labels: CherryPick/Approved, release-note-none

#20175 Automated cherry pick of #20173
  app/cloud.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20174 Automated cherry pick of #20161
  Makefile
  app/plugin.go
  app/plugin_install.go
  app/plugin_test.go
  build/release.mk
  model/config.go
  model/config_test.go
  model/feature_flags.go
  model/utils.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20177 Minor edits
  README.md
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#20176 MM-44088: Add teamID filter to channelMembers
  api4/graphql.go
  api4/resolver.go
  api4/resolver_channel_member.go
  api4/resolver_channel_member_test.go
  api4/resolver_team.go
  api4/schema.graphqls
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#20180 MM-43775: Use conn.NetConn() to get TCP conn from tls.Conn
  app/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#20186 Configure gitlab pipeline to use Go 1.18.1
  .gitlab-ci.yml
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/chore

#20188 Automated cherry pick of #20186
  .gitlab-ci.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20165 MM-44045: Fix double plugin creation due to recursive plugin activation
  plugin/environment.go
Labels: 2: Dev Review, release-note-none

#20088 [MM-32692] Add two more CRT options
  app/channel.go
  app/channel_test.go
  app/email/email_batching.go
  model/config.go
  model/config_test.go
Labels: 4: Reviews Complete, release-note

#20191 MM-41655: Prevent mmctl import into cloud instances
  api4/upload.go
  api4/upload_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#19649 [GH-19267] Spelling build
  .circleci/config.yml
  Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#20193 Makefile: Added setup-go-work to build step as well
  build/release.mk
Labels: 2: Dev Review, release-note-none

#20194 MM-44148: Skip racy TestIsCRTEnabledForUser
  app/channel_test.go
Labels: 4: Reviews Complete, release-note-none

#20184 [MM-44123] Advanced Text Editor Feature Flag
  model/feature_flags.go
Labels: release-note

#20144 MM-43716: enforce size limits in slack importer
  services/slackimport/slackimport.go
  utils/file.go
  utils/file_test.go
Labels: 4: Reviews Complete, CherryPick/Candidate, Setup Cloud Test Server, AutoMerge, release-note-none

#20178 MM-44101: GraphQL: Add sidebar categories at the top level
  api4/emoji.go
  api4/resolver.go
  api4/resolver_sidebar_categories_test.go
  api4/resolver_team_member.go
  api4/resolver_team_member_test.go
  api4/schema.graphqls
  api4/team.go
  app/app_iface.go
  app/import_functions.go
  app/import_functions_test.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/session_store.go
  store/sqlstore/team_store.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/storetest/team_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#20197 Fixes a null pointer if the plugin requests the limits on a non-cloud server
  app/plugin_api.go
Labels: 4: Reviews Complete, release-note-none

#20198 MM-41569: Prevent compliance directory to be changed on cloud instances
  api4/config.go
  api4/config_test.go
Labels: 4: Reviews Complete, release-note-none

#20201 Automated cherry pick of #20144
  services/slackimport/slackimport.go
  utils/file.go
  utils/file_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20202 Automated cherry pick of #20144
  services/slackimport/slackimport.go
  utils/file.go
  utils/file_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20204 Automated cherry pick of #20144
  services/slackimport/slackimport.go
  utils/file.go
  utils/file_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20027 POC: Cross-team recent search
  api4/file.go
  api4/post.go
  api4/post_test.go
  api4/user.go
  app/app_iface.go
  app/file.go
  app/file_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/post.go
  app/post_test.go
  db/migrations/mysql/000084_recent_searches.down.sql
  db/migrations/mysql/000084_recent_searches.up.sql
  db/migrations/postgres/000084_recent_searches.down.sql
  db/migrations/postgres/000084_recent_searches.up.sql
  i18n/en.json
  model/post.go
  model/search_params.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, release-note-none

#20203 Automated cherry pick of #20144
  services/slackimport/slackimport.go
  utils/file.go
  utils/file_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20206 config/diff: add utility function to get diffs scoped with struct tags
  api4/config.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: 4: Reviews Complete, release-note-none

#20029 Introduce (Get|Select|Exec)Builder
  store/sqlstore/sqlx_wrapper.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, release-note-none

#20152 [MM-43917] Cloud Freemium limits API: messages/posts
  api4/api.go
  api4/cloud_test.go
  api4/usage.go
  api4/usage_test.go
  api4/user_test.go
  app/analytics.go
  app/app_iface.go
  app/import_functions_test.go
  app/import_test.go
  app/migrations.go
  app/opentracing/opentracing_layer.go
  app/product_notices.go
  app/usage.go
  app/usage_test.go
  model/client4.go
  model/post.go
  model/usage.go
  services/searchengine/bleveengine/indexer/indexing_job.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/timerlayer/timerlayer.go
  utils/utils.go
  utils/utils_test.go
Labels: QA Deferred, release-note

#20235 Pre-package Playbooks v1.23.2
  Makefile
Labels: 4: Reviews Complete

#20163 MM-43529 - start freemium trial
  api4/cloud.go
  api4/cloud_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
Labels: 2: Dev Review, release-note-none

#20239 cherrypick-50eaec6
  app/channel.go
  app/expirynotify.go
  app/notification.go
  app/notification_push.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#20241 Cherrypick 32e3c2f and 50eaec6
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/channel.go
  app/expirynotify.go
  app/notification.go
  app/notification_push.go
  app/notification_push_test.go
  app/opentracing/opentracing_layer.go
  model/push_notification.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#20219 Update latest version to 6.7.0
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20244 Automated cherry pick of #20217
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20246 Automated cherry pick of #20217
  model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20243 Automated cherry pick of #20217
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20245 Automated cherry pick of #20217
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20114 [MM-43798] Change default CRT option from Disabled to AlwaysOn
  app/notification_push_test.go
  model/config.go
Labels: QA Deferred, release-note

#20141 MM-38982: fixes SVG uploading
  app/file.go
  app/import_functions.go
  app/upload.go
  model/file_info.go
  services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note

#20253 Automated cherry pick of #20163
  api4/cloud.go
  api4/cloud_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20256 Revert "config/diff: add utility function to get diffs scoped with struct tags (#20206)"
  api4/config.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20258 Automated cherry pick of #20256
  api4/config.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20164 Added Archived column to FileInfo
  db/migrations/mysql/000085_fileinfo_add_archived_column.down.sql
  db/migrations/mysql/000085_fileinfo_add_archived_column.up.sql
  db/migrations/postgres/000085_fileinfo_add_archived_column.down.sql
  db/migrations/postgres/000085_fileinfo_add_archived_column.up.sql
  model/file_info.go
  store/sqlstore/file_info_store.go
Labels: release-note

#20275 fix conflict in migration numbers
  db/migrations/mysql/000086_add_cloud_limits_archived.down.sql
  db/migrations/mysql/000086_add_cloud_limits_archived.up.sql
  db/migrations/postgres/000086_add_cloud_limits_archived.down.sql
  db/migrations/postgres/000086_add_cloud_limits_archived.up.sql
Labels: 4: Reviews Complete, release-note-none

#20286 prepackage calls 0.5.3
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20287 Automated cherry pick of #20286
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20185 Cloud Freemium - Integrations
  api4/config.go
  api4/config_test.go
  api4/usage.go
  api4/usage_test.go
  app/app_iface.go
  app/integration_action.go
  app/integrations.go
  app/integrations_test.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_test.go
  app/usage.go
  app/web_hub.go
  i18n/en.json
  model/client4.go
  model/config.go
  model/plugin_constants.go
  model/usage.go
  model/websocket_message.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, QA Review Done, release-note

#20282 [MM-44397] Restrict team creation based on subscription limits
  api4/team.go
  api4/team_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#20224 MM-44221: Add admin console setting to enable/disable App Bar
  config/client.go
  model/config.go
  model/feature_flags.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#20172 MM-43780: Adjust getPostThread API for easier pagination
  api4/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#20215 MM-31396: Attempt to fix deadlock while updating sidebar categories
  store/sqlstore/channel_store_categories.go
Labels: 4: Reviews Complete, 2: Dev Review, release-note-none

#20242 app: add permissions wrapper
  app/channels.go
  app/permissions.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#20291 MM-44568: sanitizes profiles in posts
  app/post_test.go
  store/sqlstore/post_store.go
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Deferred, release-note-none

#20303 Automated cherry pick of #20224
  config/client.go
  model/config.go
  model/feature_flags.go
  services/telemetry/telemetry.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20304 Automated cherry pick of #20291
  app/post_test.go
  store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20257 MM-44410 Add subresource integrity
  api4/graphql.go
Labels: release-note-none

#20306 Automated cherry pick of #20164
  db/migrations/mysql/000085_fileinfo_add_archived_column.down.sql
  db/migrations/mysql/000085_fileinfo_add_archived_column.up.sql
  db/migrations/postgres/000085_fileinfo_add_archived_column.down.sql
  db/migrations/postgres/000085_fileinfo_add_archived_column.up.sql
  model/file_info.go
  store/sqlstore/file_info_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20305 Automated cherry pick of #20114
  app/notification_push_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20045 Added index on SidebarCategories table
  db/migrations/mysql/000087_sidebar_categories_index.down.sql
  db/migrations/mysql/000087_sidebar_categories_index.up.sql
  db/migrations/postgres/000087_sidebar_categories_index.down.sql
  db/migrations/postgres/000087_sidebar_categories_index.up.sql
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#20308 Automated cherry pick of #20257
  api4/graphql.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20310 Fix release 7.0 pipeline
  .gitlab-ci.yml
Labels: release-note-none, kind/chore

#20292 MM-43878: don't err when reply createAt before parent createAt
  app/import_functions.go
  app/import_functions_test.go
  app/import_validators.go
  app/import_validators_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#20129 [MM-33123] Add a test for SetPostUnread-DM Channel
  api4/post_test.go
Labels: 2: Dev Review, release-note-none

#20299 MM-44568: sanitizes profiles in posts (#20291)
  app/post_test.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20311 Automated cherry pick of #20292
  app/import_functions.go
  app/import_functions_test.go
  app/import_validators.go
  app/import_validators_test.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20300 MM-44568: sanitizes profiles in posts (#20291)
  app/post_test.go
  store/sqlstore/post_store.go
Labels: release-note-none

#20250 [MM-44263] Only include user posts in post count
  api4/usage_test.go
  app/usage.go
  model/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#20254 [MM-44263] Cache Posts Usage
  app/usage.go
  model/cluster_message.go
  model/post.go
  store/localcachelayer/layer.go
  store/localcachelayer/post_layer.go
Labels: 4: Reviews Complete, release-note

#20312 Remove NextSyncAt from GetRemoteStatus query
  store/sqlstore/shared_channel_store.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#20288 MM-44130: Changed email button text.
  i18n/en.json
Labels: 4: Reviews Complete, QA Deferred, release-note

#20328 Automated cherry pick of #20288
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20330 Automated cherry pick of #20281
  api4/team.go
  api4/team_test.go
  api4/usage.go
  api4/usage_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/usage.go
  i18n/en.json
  model/client4.go
  model/usage.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none
