Repository mattermost/mattermost, pull requests merged in 2022-09, with the labels that each got.

#20929 Revert "Use error log level for websocket timeouts (#19609)"
  app/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#20932 [6.3 Backport] - Exclude deleted group members
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#20935 Weblate fix
  i18n/hu.json
  i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#20723 Adds OmitConnection parameter to broadcast
  api4/plugin.go
  api4/user.go
  api4/websocket_test.go
  app/admin_advisor.go
  app/channel.go
  app/channel_category.go
  app/cluster.go
  app/emoji.go
  app/group.go
  app/integration_action.go
  app/notification.go
  app/plugin.go
  app/plugin_api.go
  app/plugin_statuses.go
  app/post.go
  app/preference.go
  app/reaction.go
  app/role.go
  app/server.go
  app/shared_channel_notifier_test.go
  app/slashcommands/command_expand_collapse.go
  app/slashcommands/command_share.go
  app/status.go
  app/team.go
  app/teams/teams.go
  app/user.go
  app/web_conn.go
  app/web_conn_test.go
  app/web_hub_test.go
  app/webhub_fuzz.go
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 4: Reviews Complete, release-note

#20777 [MM-45564] - Notify Admin v2
  Makefile
  api4/cloud.go
  api4/cloud_test.go
  api4/notify_admin.go
  api4/notify_admin_test.go
  api4/user.go
  app/app_iface.go
  app/cloud.go
  app/notify_admin.go
  app/notify_admin_test.go
  app/opentracing/opentracing_layer.go
  app/server.go
  db/migrations/migrations.list
  db/migrations/mysql/000093_notify_admin.down.sql
  db/migrations/mysql/000093_notify_admin.up.sql
  db/migrations/postgres/000093_notify_admin.down.sql
  db/migrations/postgres/000093_notify_admin.up.sql
  i18n/en.json
  jobs/notify_admin/scheduler.go
  jobs/notify_admin/worker.go
  model/client4.go
  model/cloud.go
  model/config.go
  model/job.go
  model/notify_admin.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/notify_admin_store.go
  store/sqlstore/notify_admin_store_test.go
  store/sqlstore/store.go
  store/store.go
  store/storetest/mocks/NotifyAdminStore.go
  store/storetest/mocks/Store.go
  store/storetest/notify_admin_store.go
  store/storetest/store.go
  store/timerlayer/timerlayer.go
  tests/test-config.json
Labels: 2: Dev Review, release-note-none, Setup Cloud + CWS Test Server

#20940 Optimize CI test runtime
  api4/apitestlib.go
  api4/channel_test.go
  api4/job_test.go
  api4/system_test.go
  api4/team_test.go
  testlib/testdata/mysql_migration_warmup.sql
  testlib/testdata/postgres_migration_warmup.sql
Labels: 2: Dev Review, release-note-none

#20919 [MM-46663] Only enable marketplace command completion when config allows it
  app/slashcommands/command_marketplace.go
  app/slashcommands/command_marketplace_test.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#20949 Automated cherry pick of #20919
  app/slashcommands/command_marketplace.go
  app/slashcommands/command_marketplace_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20858 [MM-46516] P1 - Fix total message counting for top DM
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#20944 MM-46869: Fix channel props not appearing in GraphQL
  api4/resolver_channel.go
  api4/resolver_channel_test.go
  model/utils.go
Labels: 4: Reviews Complete, release-note-none

#20955 MM-46902: Skip TestFileinfosForPost
  api4/post_test.go
Labels: 4: Reviews Complete, release-note-none

#20933 Optimize CircleCI pipelines
  .circleci/config.yml
  build/docker/mysql.conf.d/custom.cnf
  build/docker/postgres.conf
Labels: 2: Dev Review, release-note-none, kind/chore

#20953 Automated cherry pick of #20858
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20896 [MM-46667] P1 Fix top DM insights pagination
  api4/insights_test.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#20962 MM-46911: Skip flaky TestGetTopDMsForUserSince
  api4/insights_test.go
Labels: 4: Reviews Complete, release-note-none

#20959 Automated cherry pick of #20896
  api4/insights_test.go
  store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20956 Add missing field "sortOrder" to graphQL schema
  api4/resolver_sidebar_categories_test.go
  api4/schema.graphqls
  model/channel_sidebar.go
Labels: 4: Reviews Complete, release-note

#20830 MM-29123: Removed the hard coded gitlab.com in Terms of Service error
  app/oauth.go
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#20762 [MM-45801] Added limit
  store/sqlstore/post_store.go
Labels: 2: Dev Review, release-note-none

#20910 Pre-package Playbooks `v1.32.1`
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#20968 Automated cherry pick of #20910
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20925 [MM-44729] Update payment failed email
  app/cloud.go
  app/email/email.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  i18n/en.json
  templates/cloud_45_day_arrears.html
  templates/cloud_90_day_arrears.html
  templates/partials/cloud_title_3subtitles_button.mjml
  templates/payment_failed_body.html
  templates/payment_failed_body.mjml
Labels: 4: Reviews Complete, release-note-none

#20969 Automated cherry pick of #20910
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20970 Automated cherry pick of #20762
  store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20960 Bump splitio dependency
  go.mod
  go.sum
Labels: 4: Reviews Complete, release-note-none

#20974 Automated cherry pick of #20960
  go.mod
  go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20973 Automated cherry pick of #20960
  go.mod
  go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20954 Allow inline JSON in config.json for advanced logging config
  app/audit.go
  app/platform/config.go
  config/logconfigsrc.go
  config/logconfigsrc_test.go
  config/migrate.go
  config/utils.go
  config/utils_test.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#20978 Initialize the logger for imports
  jobs/import_process/worker.go
Labels: 2: Dev Review, release-note-none

#20980 Automated cherry pick of #20978
  jobs/import_process/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20981 Automated cherry pick of #20978
  jobs/import_process/worker.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20965 MM-46911: P1 - Fix MySQL query to filter bots out of TopDM
  api4/insights_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#20963 MM-46871: Add remining search parameters to be escaped
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note-none

#20984 Automated cherry pick of #20963
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20982 Automated cherry pick of #20965
  api4/insights_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20983 Revert "Allow inline JSON in config.json for advanced logging config (#20954)
  app/audit.go
  app/platform/config.go
  config/logconfigsrc.go
  config/logconfigsrc_test.go
  config/migrate.go
  config/utils.go
  config/utils_test.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#20979 Prepackage Playbooks v1.32.2
  Makefile
Labels: CherryPick/Approved, release-note

#20985 Automated cherry pick of #20979
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20986 Automated cherry pick of #20979
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20988 Automated cherry pick of #20963
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20989 Automated cherry pick of #20965
  api4/insights_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20905 [MM-46603] P1 - Improvements in handling '0 posts' channels
  api4/insights_test.go
  app/channel_test.go
  app/helper_test.go
  model/channel.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#20991 Automated cherry pick of #20905
  api4/insights_test.go
  app/channel_test.go
  app/helper_test.go
  model/channel.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20990 Automated cherry pick of #20905
  api4/insights_test.go
  app/channel_test.go
  app/helper_test.go
  model/channel.go
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20875 MM-46408: adds PostPriority feature flag and admin setting
  config/client.go
  model/config.go
  model/feature_flags.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#20898 Badge count fix for push notifications when CRT is enabled
  app/notification_push.go
  app/notification_push_test.go
  app/web_hub_test.go
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#20872 [MM-31745] Add translations for enterprise PR#1266
  i18n/en.json
Labels: release-note-none

#21001 Automated cherry pick of #20998
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21004 MM-46947 - Fix: Manifest parsing won't allow placeholders for custom pluginSettingType
  model/manifest.go
  model/manifest_test.go
Labels: 4: Reviews Complete, release-note-none

#21006 MM-46421 - Prepackage Calls v0.8.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20888 MM-46004 Add Focalboard webpack dev server to dev CSP policy
  web/handlers.go
  web/handlers_test.go
Labels: 4: Reviews Complete, release-note-none

#21011 Automated cherry pick of #21006
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21010 Automated cherry pick of #21006
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21003 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#21016 Automated cherry pick of #20998
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21015 Automated cherry pick of #20998
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21017 Weblate 220913
  i18n/nl.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#21020 Automated cherry pick of #21019
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21021 Automated cherry pick of #21019
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21009 Pre-package Playbooks v1.29.2 (v7.2)
  Makefile
Labels: 4: Reviews Complete, release-note

#21008 Pre-package Playbooks v1.29.2 (v7.1)
  Makefile
Labels: 4: Reviews Complete, release-note

#21007 Pre-package Playbooks v1.23.3 (v6.3)
  Makefile
Labels: 4: Reviews Complete, release-note

#20996 MM-46604: Fix racy access to session props
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
Labels: 2: Dev Review, release-note-none

#21005 [MM-45580] Send deliquency since to end users and allow new notify ad…
  api4/cloud.go
  api4/cloud_test.go
  model/notify_admin.go
Labels: 2: Dev Review, release-note-none

#21023 Automated cherry pick of #20998
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20997 MM-38698: Add limit to the CLI compliance export command
  cmd/mattermost/commands/export.go
  einterfaces/message_export.go
  einterfaces/mocks/MessageExportInterface.go
  store/storetest/compliance_store.go
Labels: 4: Reviews Complete, release-note

#21027 [MM-41962] File extraction happens in an unbounded manner
  app/file.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#21032 Automated cherry pick of #20996
  app/web_conn.go
  app/web_hub.go
  app/web_hub_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21033 Update minor version to 7.4.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21034 Update version to 7.3.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21044 Translations update from Mattermost Weblate
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
Labels: release-note-none, Do Not Merge/Mattermod

#21025 MM-46990 Report correct import error
  i18n/en.json
  jobs/base_workers.go
  jobs/jobs.go
  jobs/jobs_test.go
Labels: 2: Dev Review, release-note-none

#21103 Contribute: Wrangler model
  model/post_list.go
  model/wrangler.go
Labels: release-note-none

#21104 Add wrangler config
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
Labels: release-note-none

#21107 Event bus interfaces
  app/eventbus.go
  shared/eventbus/eventbus.go
Labels: release-note-none

#21105 Adds api tests for the moveThread endpoint
  api4/post.go
  api4/post_test.go
  model/client4.go
  model/post.go
Labels: release-note-none

#21114 Wrangler config use pointers
  model/config.go
Labels: release-note-none

#21113 Check wrangler config
  api4/post.go
  api4/post_test.go
  model/config.go
  model/user.go
Labels: release-note-none

#21110 Add event bus pub sub
  app/eventbus.go
  go.mod
  go.sum
  shared/eventbus/eventbus.go
Labels: release-note-none

#21112 Contribute: Event Bus Product API
  api4/system.go
  i18n/en.json
  web/context.go
  web/params.go
Labels: release-note-none

#21118 Plugin API for Event Bus
  app/plugin_api.go
  plugin/api.go
  plugin/api_timer_layer_generated.go
  plugin/client_rpc_generated.go
  plugin/eventbus_helper/plugin_helper.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
  plugin/plugintest/api.go
  plugin/plugintest/hooks.go
  plugin/product_hooks_generated.go
Labels: 2: Dev Review, release-note-none

#21031 [MM-47002] Fix new private channels not showing up in least active channels insights
  store/sqlstore/channel_store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, AutoMerge, release-note

#21117 Contribute Voice Message: Implement basic MP3 parser
  app/av/mp3/parser.go
  app/av/mp3/parser_test.go
  app/av/mp3/samples/sample-32000-96.mp3
  app/av/mp3/samples/sample-44100-128.mp3
  app/av/mp3/samples/sample-48000-64.mp3
  app/av/mp3/samples/sample-invalid.mp3
Labels: 2: Dev Review, release-note-none

#21121 Wrangler logic
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  model/post.go
  model/user.go
Labels: do-not-merge/release-note-label-needed

#21123 Wrangler logic
  app/post.go
Labels: release-note-none

#21126 Translations update from Mattermost Weblate
  i18n/en_AU.json
  i18n/ja.json
  i18n/pl.json
  i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#19985 [MM-42191]: Include deleted posts
  api4/commands_test.go
  api4/post.go
  api4/post_test.go
  api4/team_test.go
  model/client4.go
  model/permission.go
  model/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note, Contributor

#20703 [MM-44489] Cloud limits: enforcing files
  api4/file.go
  app/app_iface.go
  app/file.go
  app/file_helper.go
  app/file_helper_test.go
  app/file_test.go
  app/import_functions.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_metadata.go
  app/post_test.go
  app/server.go
  i18n/en.json
  jobs/last_accessible_file/scheduler.go
  jobs/last_accessible_file/worker.go
  model/client4.go
  model/file_info.go
  model/file_info_list.go
  model/job.go
  model/system.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#20975 ci: add minimum GitHub token permissions for workflows
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete, release-note-none, Contributor

#20977 Fix username uniqueness unit test
  store/storetest/user_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#21040 [MM-42400] Prevent making groups with reserved names
  api4/group_test.go
  i18n/en.json
  model/group.go
Labels: 4: Reviews Complete, release-note-none

#21047 Update Header with application/json
  web/web.go
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#20943 Avoid counting top channel posts for posts made by plugins and OAuth apps
  api4/post_test.go
  app/channel_test.go
  app/plugin_api.go
  app/plugin_api_test.go
  app/post.go
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note

#21149 MM-46105: Simplify posts batch retrieval query
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note-none

#19126 [MM-24461] Show last active time of users when not online
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: release-note

#20893 Mm 46065
  api4/post.go
Labels: release-note
