Repository mattermost/mattermost, pull requests merged in 2022-02, with the labels that each got.

#19441 [MM-41351] Set ThreadAutoFollow to false by default
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: Docs/Done, release-note

#19455 [MM-41351] Set ThreadAutoFollow to false by default (#19441)
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: release-note

#19456 [MM-41351] Set ThreadAutoFollow to false by default (#19441)
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: release-note

#19411 MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true
  app/channel.go
Labels: release-note

#19458 [MM-41351] Set ThreadAutoFollow to false by default (#19441)
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: release-note

#19459 [MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true
  app/channel.go
Labels: release-note

#19460 [MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true
  app/channel.go
Labels: release-note

#19461 [MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true
  app/channel.go
Labels: release-note

#19462 [MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true
  app/channel.go
Labels: release-note

#19426 [MM-41189] Remove "Invite to team" feature flag
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#19457 [MM-41351] Set ThreadAutoFollow to false by default (#19441)
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note

#19464 Fix/weblate conflicts
  i18n/de.json
  i18n/en_AU.json
  i18n/nl.json
  i18n/pl.json
  i18n/tr.json
Labels: kind/bug, release-note-none

#19366 Growth spike: Get latest MM version
  api4/system.go
  app/admin.go
  app/admin_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/github_release.go
Labels: release-note

#19436 Temporary disabling .pages indexing to avoid crashes on malicious files
  services/docextractor/documents.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note

#19465 GraphQL (part 1): Store layer
  api4/channel.go
  api4/channel_category.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/team.go
  app/user.go
  manualtesting/manual_testing.go
  model/channel.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/file_info_layer.go
  store/searchlayer/post_layer.go
  store/sqlstore/channel_member_history_store.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_member_history_store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelMemberHistoryStore.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#19480 Automated cherry pick of #19436
  services/docextractor/documents.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19481 Automated cherry pick of #19436
  services/docextractor/documents.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19482 Automated cherry pick of #19436
  services/docextractor/documents.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19483 Automated cherry pick of #19436
  services/docextractor/documents.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19435 [MM-41290] Add Endpoint to complete onboarding
  api4/plugin_test.go
  api4/system.go
  api4/system_test.go
  app/app_iface.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  i18n/en.json
  model/client4.go
  model/onboarding.go
  services/marketplace/client.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#19469 Automated cherry pick of #19421
  go.mod
  go.sum
  vendor/github.com/go-morph/morph/drivers/lock.go
  vendor/github.com/go-morph/morph/drivers/mysql/mysql.go
  vendor/github.com/go-morph/morph/drivers/postgres/postgres.go
  vendor/github.com/go-morph/morph/morph.go
  vendor/modules.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19473 Automated cherry pick of #19411
  app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19468 Automated cherry pick of #19340
  model/cloud.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19470 Automated cherry pick of #19383
  db/migrations/bindata.go
  db/migrations/mysql/000075_alter_upload_sessions_index.down.sql
  db/migrations/mysql/000075_alter_upload_sessions_index.up.sql
  db/migrations/postgres/000075_alter_upload_sessions_index.down.sql
  db/migrations/postgres/000075_alter_upload_sessions_index.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19471 Automated cherry pick of #19417
  app/license.go
  app/license_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19472 Automated cherry pick of #19423
  i18n/en.json
  web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19474 Automated cherry pick of #19441
  api4/user_test.go
  app/post_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19479 Automated cherry pick of #19436
  services/docextractor/documents.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19444 [MM-40582] Send unsanitized user to source on user_updated
  api4/user_test.go
  app/user.go
Labels: 2: Dev Review, release-note, Contributor

#19418 MM-41184: Remove /config/migrate API endpoint
  api4/config.go
  api4/config_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, release-note

#19475 Automated cherry pick of #19409
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19489 MM-41184: Remove /config/migrate API endpoint (#19418)
  api4/config.go
  api4/config_test.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#19492 Update version to 6.3.4
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19488 Update version to 5.37.9
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19490 Update version to 6.1.4
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19491 Update version to 6.2.4
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#19454 Feature Flag for health of server dashboard
  model/feature_flags.go
Labels: QA Deferred, release-note

#19500 Update database to v6.4.0
  store/sqlstore/upgrade.go
Labels: 2: Dev Review, CherryPick/Approved, release-note, kind/chore

#19501 Automated cherry pick of #19500
  store/sqlstore/upgrade.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19484 [MM-41343] Password reset must be 24hour
  app/user.go
  app/user_test.go
Labels: QA Review Done, release-note

#19494 Skip exporting channels for deleted teams
  app/export.go
  app/export_test.go
Labels: 4: Reviews Complete, kind/bug, release-note

#19505 Pin GolangCI to a specific version
  .circleci/config.yml
  Makefile
Labels: 4: Reviews Complete, release-note-none

#19498 MM-41085: Use a counting semaphore in sendNotifications
  app/notification.go
Labels: 4: Reviews Complete, release-note-none

#19516 Skip and warn on emoji import when name conflicts with system emoji
  app/import_functions.go
  app/import_functions_test.go
  app/import_validators.go
  app/import_validators_test.go
  i18n/en.json
  model/emoji.go
Labels: 4: Reviews Complete, CherryPick/Approved, kind/bug, release-note

#19515 [MM-41534] - Portal not picking up MMCLOUDURL cookie
  app/login.go
Labels: 2: Dev Review, release-note-none

#19443 MM-41035: Pre-package Playbooks v1.24.1
  Makefile
Labels: CherryPick/Approved, release-note

#19439 Migrate ChannelStore.UpdateLastViewedAt to squirrel
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#19524 Automated cherry pick of #19443
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19506 Migrate Channelstore categories to sqlx
  model/channel.go
  store/sqlstore/channel_store.go
  store/sqlstore/channel_store_categories.go
  store/sqlstore/preference_store.go
  store/storetest/mocks/dbSelecter.go
Labels: 4: Reviews Complete, release-note-none

#19499 [MM-40935] Add OnInstall() plugin hook
  api4/system.go
  app/app_iface.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  model/plugin_on_install_event.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
  plugin/plugintest/hooks.go
Labels: 4: Reviews Complete, release-note

#18492 MM-36589: provide previous values for unreads
  api4/apitestlib.go
  api4/user_test.go
  app/channel.go
  app/notification.go
  app/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#19495 [MM-41408] Remove autotour feature flag
  model/feature_flags.go
Labels: 2: Dev Review, QA Deferred, release-note-none

#19094 [MM-39629] - Migrate from gorp to sqlx in store/sqlstore/thread_store.go
  store/sqlstore/sqlx_wrapper.go
  store/sqlstore/thread_store.go
  store/storetest/mocks/sqlxExecutor.go
Labels: AutoMerge, release-note-none, Contributor

#19387 [MM-41200] Add OnSendDailyTelemetry() plugin hook
  app/plugin_hooks_test.go
  plugin/client_rpc_generated.go
  plugin/hooks.go
  plugin/hooks_timer_layer_generated.go
  plugin/plugintest/hooks.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#19502 prepare for next 6.5.0
  model/version.go
Labels: 4: Reviews Complete, release-note-none, kind/chore

#19437 Growth spike guest accounts
  api4/user.go
  api4/user_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  i18n/en.json
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#19530 MM-41143: Pass a custom logger to morph
  store/sqlstore/store.go
  store/sqlstore/utils.go
Labels: 4: Reviews Complete, release-note-none

#19536 MM-38419: Split UPSERT statement into 2
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#19379 [GH-19267] Spelling strings
  i18n/en.json
  i18n/en_AU.json
Labels: AutoMerge, release-note-none, Contributor

#19518 prepackage focalboard v0.14.0
  Makefile
Labels: 2: Dev Review, 1: PM Review, CherryPick/Approved, release-note

#19538 Automated cherry pick of #19518
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19539 Automated cherry pick of #19518
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19546 MM-41797: Skip Flaky test in ThreadStore
  store/storetest/thread_store.go
Labels: 4: Reviews Complete, release-note-none

#19547 MM-41796: Sentry crash: use the correct error variable
  app/team.go
  app/team_test.go
Labels: 4: Reviews Complete, release-note-none

#19551 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ko.json
  i18n/pl.json
  i18n/tr.json
Labels: Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#19544 Remove ColMap
  store/sqlstore/audit_store.go
  store/sqlstore/bot_store.go
  store/sqlstore/channel_member_history_store.go
  store/sqlstore/channel_store.go
  store/sqlstore/cluster_discovery_store.go
  store/sqlstore/command_store.go
  store/sqlstore/command_webhook_store.go
  store/sqlstore/compliance_store.go
  store/sqlstore/emoji_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/group_store.go
  store/sqlstore/integrity_test.go
  store/sqlstore/job_store.go
  store/sqlstore/license_store.go
  store/sqlstore/link_metadata_store.go
  store/sqlstore/oauth_store.go
  store/sqlstore/plugin_store.go
  store/sqlstore/post_store.go
  store/sqlstore/preference_store.go
  store/sqlstore/product_notices_store.go
  store/sqlstore/reaction_store.go
  store/sqlstore/remote_cluster_store.go
  store/sqlstore/retention_policy_store.go
  store/sqlstore/role_store.go
  store/sqlstore/scheme_store.go
  store/sqlstore/session_store.go
  store/sqlstore/shared_channel_store.go
  store/sqlstore/status_store.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/system_store.go
  store/sqlstore/team_store.go
  store/sqlstore/terms_of_service_store.go
  store/sqlstore/thread_store.go
  store/sqlstore/tokens_store.go
  store/sqlstore/upload_session_store.go
  store/sqlstore/user_access_token_store.go
  store/sqlstore/user_store.go
  store/sqlstore/webhook_store.go
Labels: 4: Reviews Complete, release-note-none

#19553 fix typo in the app/export_test.go
  app/export_test.go
Labels: 4: Reviews Complete, release-note-none

#19554 fix a typo in the mysql/000010_create_group_channels.up.sql
  db/migrations/bindata.go
  db/migrations/mysql/000010_create_group_channels.up.sql
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#19541 Allow developpers to use a docker-compose.override.yaml file
  .gitignore
  Makefile
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#19557 Automated cherry pick of #19554
  db/migrations/bindata.go
  db/migrations/mysql/000010_create_group_channels.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19563 Revert "MM-41211: Adds ability to set SessionLengthSSOInDays to a dec…
  api4/user.go
  app/app_iface.go
  app/login.go
  app/oauth.go
  app/oauth_test.go
  app/opentracing/opentracing_layer.go
  app/session.go
  app/users/session.go
  app/users/session_test.go
  i18n/en.json
  model/builtin.go
  model/config.go
  model/session.go
  services/upgrader/upgrader.go
  web/handlers_test.go
Labels: 2: Dev Review, release-note-none

#19446 Use case onboarding
  api4/system.go
  app/app_iface.go
  app/migrations.go
  app/onboarding.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/feature_flags.go
  model/system.go
Labels: 2: Dev Review, release-note

#19364 [MM-37987] cmd/mattermost/version: remove store initialization from version cmd
  .circleci/config.yml
  .gitlab-ci/scripts/test-schema/mysql.sh
  .gitlab-ci/scripts/test-schema/postgres.sh
  cmd/mattermost/commands/db.go
  cmd/mattermost/commands/version.go
  scripts/mysql-migration-test.sh
  scripts/psql-migration-test.sh
Labels: 4: Reviews Complete, Docs/Done, release-note

#19424 Adding the Scorecard analysis
  .github/workflows/scorecards-analysis.yml
Labels: do-not-merge/release-note-label-needed

#19568 Update version to 6.4.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19573 Change log level for missing plugin
  app/plugin_requests.go
Labels: 4: Reviews Complete, release-note-none

#19545 Replace remaining GetMaster() queries
  Makefile
  app/channel_category_test.go
  app/config_test.go
  app/helper_test.go
  app/plugin_api_tests/test_db_driver/main.go
  app/post_test.go
  app/user_test.go
  store/localcachelayer/layer_test.go
  store/sqlstore/integrity.go
  store/sqlstore/sqlx_wrapper.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/sqlstore/upgrade.go
  store/storetest/bot_store.go
  store/storetest/channel_store.go
  store/storetest/channel_store_categories.go
  store/storetest/mocks/JSONSerializable.go
  store/storetest/mocks/ObjectCache.go
  store/storetest/mocks/SqlStore.go
  store/storetest/mocks/dbSelecter.go
  store/storetest/mocks/sqlxExecutor.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/retention_policy_store.go
  store/storetest/role_store.go
  store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note-none

#19569 Bump morph dependency
  go.mod
  go.sum
  vendor/github.com/go-morph/morph/color_logger.go
  vendor/github.com/go-morph/morph/morph.go
  vendor/modules.txt
Labels: 4: Reviews Complete, release-note-none

#19507 MM-41499: Optimize TeamsUnread
  app/team.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#19585 Changing log level for some license logs
  app/license.go
Labels: 4: Reviews Complete, release-note-none

#18839 Custom groups
  api4/apitestlib.go
  api4/channel_test.go
  api4/group.go
  api4/group_test.go
  api4/handlers.go
  api4/ldap.go
  api4/team_test.go
  api4/user.go
  api4/user_test.go
  api4/webhook_test.go
  api4/websocket_norace_test.go
  app/app_iface.go
  app/app_test.go
  app/authorization.go
  app/authorization_test.go
  app/group.go
  app/group_test.go
  app/helper_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/permissions_migrations.go
  app/plugin_api.go
  app/syncables_test.go
  app/user.go
  config/client.go
  go.tools.sum
  i18n/en.json
  model/client4.go
  model/config.go
  model/feature_flags.go
  model/group.go
  model/license.go
  model/migration.go
  model/permission.go
  model/role.go
  model/user_get.go
  model/user_search.go
  model/websocket_message.go
  plugin/environment_test.go
  services/telemetry/telemetry.go
  services/upgrader/upgrader.go
  store/errors.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/group_store.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/team_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
  testlib/store.go
  tests/group-role-has-permission.csv
  web/params.go
Labels: 2: Dev Review, Docs/Needed, 3: QA Review, Setup Cloud Test Server, 3: Security Review, release-note

#19565 Add new /test dms command
  app/slashcommands/auto_channels.go
  app/slashcommands/command_loadtest.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#19567 [MM-41668] Remove "add support email" admin advisor notifications
  app/admin_advisor.go
  app/server.go
  app/server_test.go
  i18n/en.json
  model/system.go
Labels: 4: Reviews Complete, QA Review Done, AutoMerge, release-note

#19571 MM-40813: Add config interface
  app/audit.go
  app/channels.go
  app/config.go
  app/notification_push_test.go
  app/options.go
  app/plugin.go
  app/plugin_install.go
  app/plugin_requests.go
  app/plugin_signature.go
  app/plugin_statuses.go
  app/product.go
  app/server.go
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#19606 Update version to 6.3.5
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19608 Update version to 6.2.5
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19574 MM-39351: fixes LastRootPostAt being null
  .editorconfig
  db/migrations/bindata.go
  db/migrations/mysql/000076_upgrade_lastrootpostat.down.sql
  db/migrations/mysql/000076_upgrade_lastrootpostat.up.sql
  db/migrations/postgres/000076_upgrade_lastrootpostat.down.sql
  db/migrations/postgres/000076_upgrade_lastrootpostat.up.sql
Labels: 4: Reviews Complete, release-note

#19594 [MM-41712] Allow sending intra-cluster WS events reliably
  app/web_hub.go
  app/web_hub_test.go
  model/websocket_message.go
Labels: release-note

#19564 Update Safari minimum recommended version
  i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, AutoMerge, release-note

#19374 [MM-40917] - Inactive Server Email Notification
  app/email/email.go
  app/server.go
  app/server_inactivity.go
  i18n/en.json
  model/feature_flags.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/post_store.go
  store/storetest/session_store.go
  store/timerlayer/timerlayer.go
  templates/inactivity_body.html
  templates/inactivity_body.mjml
Labels: 2: Dev Review, 3: QA Review, CherryPick/Candidate, Setup Cloud Test Server, release-note-none

#19615 Automated cherry pick of #19374
  app/email/email.go
  app/server.go
  app/server_inactivity.go
  i18n/en.json
  model/feature_flags.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/sqlstore/session_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/post_store.go
  store/storetest/session_store.go
  store/timerlayer/timerlayer.go
  templates/inactivity_body.html
  templates/inactivity_body.mjml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19604 MM-41972: Skip flaky test TestAllowGroupMentions
  app/notification_test.go
Labels: 4: Reviews Complete, release-note-none

#19609 Use error log level for websocket timeouts
  app/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#19620 [MM-42033] Fix racy TestReliableWebSocketSend
  app/helper_test.go
  app/options.go
  app/web_hub_test.go
Labels: 4: Reviews Complete, release-note-none

#19590 [MM-41671] Support Email Position+Validation
  api4/config.go
  model/config.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#19624 Automated cherry pick of #19604
  app/notification_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19625 revert to status found for login cws
  api4/user.go
Labels: 2: Dev Review, release-note-none

#19591 [MM-41756] Remove AcceptedServiceTermsId column
  db/migrations/bindata.go
  db/migrations/mysql/000077_upgrade_users_v6.5.down.sql
  db/migrations/mysql/000077_upgrade_users_v6.5.up.sql
  db/migrations/postgres/000077_upgrade_users_v6.5.down.sql
  db/migrations/postgres/000077_upgrade_users_v6.5.up.sql
Labels: 4: Reviews Complete, release-note-none

#19626 Automated cherry pick of #19625
  api4/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19548 Fix the broken MariaDB JSON path queries
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#19634 Cherry pick of [MM-41756] Remove AcceptedServiceTermsId column #19591
  db/migrations/bindata.go
  db/migrations/mysql/000077_upgrade_users_v6.5.down.sql
  db/migrations/mysql/000077_upgrade_users_v6.5.up.sql
  db/migrations/postgres/000077_upgrade_users_v6.5.down.sql
  db/migrations/postgres/000077_upgrade_users_v6.5.up.sql
Labels: AutoMerge, release-note-none

#19621 MM-36668: Trim large slash commands before logging
  app/command.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#19638 Skip TestDeleteChannel
  api4/channel_test.go
Labels: 4: Reviews Complete, release-note-none

#19639 Chore/cherry pick translation
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, kind/chore

#19640 Update version to 6.4.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19619 Fixed MM-42027
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/team_test.go
  i18n/en.json
  jobs/jobs.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/job_store.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, QA Review Done, release-note-none

#19642 fix string constants
  app/migrations.go
  app/onboarding.go
  model/system.go
Labels: 2: Dev Review, CherryPick/Approved, QA Deferred, release-note-none

#19643 Automated cherry pick of #19642
  app/migrations.go
  app/onboarding.go
  model/system.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#19542 [GH-19267] Spelling tests
  api4/apitestlib.go
  api4/bot_test.go
  api4/channel_test.go
  api4/emoji_test.go
  api4/integration_action_test.go
  api4/user_test.go
  api4/user_viewmembers_test.go
  api4/webhook_test.go
  app/channel_test.go
  app/file_test.go
  app/import_functions_test.go
  app/notification_test.go
  app/plugin_api_test.go
  app/post_metadata_test.go
  app/product_notices_test.go
  app/remote_cluster_test.go
  app/server_test.go
  app/team_test.go
  app/teams/teams_test.go
  app/user_test.go
  app/user_viewmembers_test.go
  app/webhook_test.go
  config/common_test.go
  config/database_test.go
  config/environment_test.go
  config/file_test.go
  model/link_metadata_test.go
  model/search_params_test.go
  model/utils_test.go
  plugin/environment_test.go
  scripts/get_latest_release.sh
  services/cache/lru_striped_test.go
  services/docextractor/docextractor_test.go
  shared/mail/mail_test.go
  store/searchtest/file_info_layer.go
  store/searchtest/post_layer.go
  store/searchtest/user_layer.go
  store/storetest/channel_store.go
  store/storetest/channel_store_categories.go
  store/storetest/shared_channel_store.go
  store/storetest/team_store.go
  utils/merge_test.go
Labels: release-note-none, Contributor

#19646 Automated cherry pick of #19619
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/team_test.go
  i18n/en.json
  jobs/jobs.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/job_store.go
  store/store.go
  store/storetest/job_store.go
  store/storetest/mocks/JobStore.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#19633 [MM-42068] Add check to stop custom groups linking to teams and channels
  api4/group.go
  api4/group_test.go
Labels: 3: QA Review, release-note

#19523 MM-41349: CRT, fix LastUpdated semantics
  api4/post.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/notification.go
  app/opentracing/opentracing_layer.go
  app/post_test.go
  model/thread.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/post_store.go
  store/storetest/thread_store.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: Setup Cloud Test Server, AutoMerge, release-note-none
