Repository mattermost/mattermost, pull requests merged in 2022-06, with the labels that each got.

#20295 store: guests will only receive results of which channels they are in
  api4/channel_test.go
  app/channel.go
  services/searchengine/bleveengine/search.go
  services/searchengine/interface.go
  services/searchengine/mocks/SearchEngineInterface.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/searchtest/channel_layer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#20315 MM 43666 - request bussiness email
  api4/cloud.go
  api4/cloud_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  model/client4.go
  model/cloud.go
Labels: 2: Dev Review, release-note-none

#20344 Fix failures for circleci ubuntu image
  .circleci/config.yml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, kind/bug, release-note-none

#20340 Add StatusOK return to the softDeleteTeamsExcept controller
  api4/team.go
Labels: 4: Reviews Complete, release-note-none

#20349 MM-44420 - replace 14-day references with new freemium 30-day
  app/email/email_test.go
  i18n/en.json
Labels: release-note-none

#20309 MM-44638: Remove upgrade.go
  app/migrations.go
  db/migrations/mysql/000088_remaining_migrations.down.sql
  db/migrations/mysql/000088_remaining_migrations.up.sql
  db/migrations/postgres/000088_remaining_migrations.down.sql
  db/migrations/postgres/000088_remaining_migrations.up.sql
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/store.go
  store/sqlstore/team_store.go
  store/sqlstore/upgrade.go
  store/sqlstore/upgrade_test.go
  store/store.go
  store/storetest/mocks/TeamStore.go
  store/timerlayer/timerlayer.go
  testlib/store.go
Labels: 2: Dev Review, release-note-none

#20334 Cherry pick of #20295 into release-6.5
  api4/channel_test.go
  app/channel.go
  services/searchengine/bleveengine/search.go
  services/searchengine/interface.go
  services/searchengine/mocks/SearchEngineInterface.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/searchtest/channel_layer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20335 Cherry pick of #20295 into release-6.6
  api4/channel_test.go
  app/channel.go
  services/searchengine/bleveengine/search.go
  services/searchengine/interface.go
  services/searchengine/mocks/SearchEngineInterface.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/channel_layer.go
  store/searchtest/channel_layer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20276 Bumped prepackaged mattermost-plugin-apps to v1.1.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20354 Automated cherry pick of #20276
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20325 MM-41728: Validate emoji size in app while importing
  app/import_functions.go
  app/import_functions_test.go
  tests/large_image_file.jpg
Labels: 4: Reviews Complete, release-note-none

#20225 MM-43918: freemium limit for storage
  api4/usage.go
  api4/usage_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/usage.go
  i18n/en.json
  model/client4.go
  model/usage.go
  store/localcachelayer/file_info_layer.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/file_info_store.go
  store/store.go
  store/storetest/file_info_store.go
  store/storetest/mocks/FileInfoStore.go
  store/timerlayer/timerlayer.go
Labels: QA Deferred, release-note-none

#20351 [MM-44329] Add a method to store.Store interface to get sql.DB object
  store/sqlstore/store.go
  store/store.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
Labels: 4: Reviews Complete, release-note-none

#20359 [MM-44786] Fix Trusted Header Parsing for Cloudflare
  utils/utils.go
  utils/utils_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#20294 [MM-44604] Ensure we return after setting error in api4/config.go
  api4/config.go
Labels: release-note-none

#20263 MM-44412: correct usage of updateAt to createAt
  app/channel.go
  app/channel_test.go
Labels: 4: Reviews Complete, release-note-none

#20365 Automated cherry pick of #20263
  app/channel.go
  app/channel_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20358 [MM-42192] Include deleted posts in GetPost
  api4/channel.go
  api4/channel_local.go
  api4/post.go
  api4/post_test.go
  api4/preference.go
  api4/system.go
  app/app_iface.go
  app/channel.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/post.go
  app/post_metadata.go
  app/post_test.go
  app/reaction.go
  app/user.go
  model/client4.go
Labels: 2: Dev Review, release-note

#20371 Prepackage focalboard v7.0.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20376 Automated cherry pick of #20371
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20377 Automated cherry pick of #20371
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20374 app/plugin: add product middleware and allow products register routers
  app/channels.go
  app/plugin.go
  app/plugin_requests.go
  app/server.go
Labels: 4: Reviews Complete, release-note-none

#20370 Bump pre-packaged version of Zoom to v1.6.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#20383 Automated cherry pick of #20370
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20382 Automated cherry pick of #20370
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20341 Pre-package Playbooks v1.28.1
  Makefile
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note

#20386 Automated cherry pick of #20341
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20388 [MM-44512] Pre-package Calls v0.6.0 and enable it by default
  Makefile
  app/plugin.go
  app/plugin_test.go
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20390 Automated cherry pick of #20388
  Makefile
  app/plugin.go
  app/plugin_test.go
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20392 [MM-44512] Cherry-pick #20388 on release-7.0
  Makefile
  app/plugin.go
  app/plugin_test.go
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
Labels: release-note-none

#20393 Automated cherry pick of #20372
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20384 Simplify ParamsFromRequest
  web/params.go
  web/params_test.go
Labels: 4: Reviews Complete, release-note-none

#20364 [MM-43831] removed the parallel marker from the subtests
  app/post_test.go
Labels: 4: Reviews Complete, release-note-none

#20357 Set Advanced Text Editor feature flag default value to True
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#20400 Automated cherry pick of #20357
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20398 [MM-44925] simplified the ID generator
  model/utils.go
Labels: 4: Reviews Complete, release-note-none

#20391 Revert "config/diff: add utility function to get diffs scoped with st…
  api4/config.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#20401 Cherry pick of #20357 on release-7.0.
  model/feature_flags.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20402 Automated cherry pick of #20391
  api4/config.go
  config/diff.go
  config/diff_test.go
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20394 update boards to v7.0.1
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#20404 Automated cherry pick of #20181
  api4/channel_test.go
  app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20407 Automated cherry pick of #20394
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20214 [MM-43785] Hide insights feature intro for new users
  api4/preference_test.go
  app/plugin_api_test.go
  app/user.go
  app/user_test.go
  model/preference.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#20406 Automated cherry pick of #20394
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20389 remove unused code around unimplemented ExperimentalSettings.EnableCl…
  config/client.go
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#20380 [MM-44573] Sanitize options
  app/channel_test.go
  app/file.go
  app/post.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none

#20409 Automated cherry pick of #20380
  app/channel_test.go
  app/file.go
  app/post.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20412 MM-42714: Trim token sizes to 26 characters
  app/authentication.go
  app/authentication_test.go
Labels: 4: Reviews Complete, release-note-none

#20379 [MM-44364] make config override actually override defaults
  Makefile
Labels: 4: Reviews Complete, release-note-none

#20387 Check for cloud license and CWS error when checking integration freemium limits
  api4/config_test.go
  app/integrations.go
  app/plugin_test.go
Labels: 2: Dev Review, QA Review Done, release-note-none

#20418 Cherry pick of #20380 (release-6.7)
  app/channel_test.go
  app/file.go
  app/post.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note-none

#20424 Automated cherry pick of #20387
  api4/config_test.go
  app/integrations.go
  app/plugin_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20425 [MM-44995] remove reference to 30 days trial in welcome email
  app/email/email.go
  app/email/email_test.go
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, QA Deferred, release-note-none

#20426 Automated cherry pick of #20425
  app/email/email.go
  app/email/email_test.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#20434 Cherry pick of #20380 (release-6.6)
  app/channel_test.go
  app/file.go
  app/post.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note-none

#20435 Cherry pick of #20380 (release-6.5) (#20434)
  app/channel_test.go
  app/file.go
  app/post.go
  services/sharedchannel/permalink.go
  services/sharedchannel/permalink_test.go
  store/localcachelayer/main_test.go
  store/localcachelayer/post_layer.go
  store/localcachelayer/post_layer_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/searchlayer/post_layer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/storetest/reaction_store.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: release-note-none

#20433 Fix client driver API for UpdateUserCustomStatus
  model/client4.go
Labels: 4: Reviews Complete, release-note-none

#20429 MM-44805: Avoid pointers in JSON parsing in createCategoryForTeamForUser
  api4/channel_category.go
  api4/channel_category_test.go
Labels: 4: Reviews Complete, release-note-none

#20431 MM-44806: Avoid pointers in JSON parsing in updateCategoryForTeamForUser
  api4/channel_category.go
  api4/channel_category_test.go
Labels: 4: Reviews Complete, release-note-none

#20413 MM-43733: Set concurrency limits via configuration
  app/channels.go
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#20403 Add Product Interfaces
  app/bot.go
  app/channel.go
  app/channels.go
  app/cluster.go
  app/product.go
  app/server.go
  app/team.go
  plugin/environment.go
  plugin/product.go
  product/README.md
  product/api.go
  product/doc.go
Labels: 4: Reviews Complete, release-note-none

#20445 [MM-41026] Fix flaky TestUploadDataConcurrent
  app/upload_test.go
Labels: 4: Reviews Complete, release-note-none

#20446 [MM-44951] Add go mod tidy CircleCI check
  .circleci/config.yml
  Makefile
  go.sum
Labels: release-note-none

#20449 Reflect alpine image change to fix build pipelines
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, release-note-none, kind/chore

#20450 Automated cherry pick of #20449
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20131 MM-43956: Adds post counts by duration.
  api4/handlers.go
  api4/insights.go
  api4/insights_test.go
  app/app_iface.go
  app/channel.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  app/reaction_test.go
  i18n/en.json
  model/insights.go
  model/insights_test.go
  model/user.go
  store/layer_generators/opentracing_layer.go.tmpl
  store/layer_generators/retry_layer.go.tmpl
  store/layer_generators/timer_layer.go.tmpl
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
  store/storetest/mocks/ChannelStore.go
  store/storetest/mocks/CommandStore.go
  store/storetest/mocks/EmojiStore.go
  store/storetest/mocks/PostStore.go
  store/storetest/mocks/SessionStore.go
  store/storetest/mocks/UserStore.go
  store/storetest/mocks/WebhookStore.go
  store/storetest/post_store.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#20456 Update version to 6.5.3
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20458 Update version to 6.6.3
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20326 websocket: drop less important events earlier
  app/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#20455 Update version to 6.3.10
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#20464 Update latest version to 6.7.1
  build/Dockerfile
Labels: release-note-none

#20443 MM-45000: Change dyatlov dependency
  app/post_metadata_test.go
  go.mod
  go.sum
  model/link_metadata.go
  model/link_metadata_test.go
  store/storetest/link_metadata_store.go
Labels: 4: Reviews Complete, release-note-none

#20469 Update latest version to 7.0.0
  build/Dockerfile
Labels: release-note-none

#20408 add file storage telemetry
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 2: Dev Review, release-note

#20454 File storage usage default 0
  store/sqlstore/file_info_store.go
  store/storetest/file_info_store.go
Labels: 4: Reviews Complete, 3: QA Review, release-note

#20474 Automated cherry pick of #20454
  store/sqlstore/file_info_store.go
  store/storetest/file_info_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20437 Improves group membership telemetry.
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/group_store.go
  store/store.go
  store/storetest/group_store.go
  store/storetest/mocks/GroupStore.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, 1: PM Review, release-note

#20439 Mm 44488 enforce posts support sorts
  app/channel.go
  app/post.go
  app/post_helpers.go
  app/post_helpers_test.go
Labels: release-note-none

#20444 MM-44236 Update server dependencies
  .circleci/config.yml
  Makefile
  app/channel_test.go
  go.mod
  go.sum
  model/post_list.go
  plugin/db_rpc.go
  services/remotecluster/ping_test.go
  services/remotecluster/send_test.go
  store/storetest/retention_policy_store.go
Labels: release-note-none

#20483 MM-43832: Fix flaky TestReadReplicaDisabledBasedOnLicense
  app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#20484 MM-43871: Fix flaky TestCreatePostAsUser
  app/post_test.go
Labels: 4: Reviews Complete, release-note-none

#20259 [MM-44434] Introduced search for channel id's through system console.
  api4/channel.go
  app/channel.go
  model/channel.go
  model/channel_search.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
Labels: 4: Reviews Complete, release-note, Contributor

#20488 Use a single critical section for users notified admin
  api4/channel.go
  api4/cloud_test.go
  app/channel.go
  app/cloud.go
  i18n/en.json
  model/channel.go
  model/channel_search.go
  store/sqlstore/channel_store.go
  store/store.go
  store/storetest/channel_store.go
Labels: release-note-none

#20423 [MM-44887] Consistency in "next billing date"
  app/cloud.go
  app/email/email.go
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note-none

#20492 Automated cherry pick of #20423
  app/cloud.go
  app/email/email.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20420 [MM-44363] Detect M1 and load compatible Elasticsearch version
  Makefile
  docker-compose.makefile.m1.yml
Labels: release-note-none

#20490 MM-44642 hide insights per license
  config/client.go
  config/client_test.go
Labels: QA Deferred, release-note

#20472 MM-25554: Remove hardcoded english as the search config
  build/docker/postgres.conf
  store/sqlstore/channel_store.go
  store/sqlstore/file_info_store.go
  store/sqlstore/post_store.go
  store/sqlstore/store.go
Labels: 2: Dev Review, release-note

#20491 remove freemium feature flag
  api4/cloud.go
  api4/cloud_test.go
  api4/config_test.go
  api4/team.go
  api4/team_test.go
  app/app_iface.go
  app/integrations.go
  app/plugin_test.go
  app/usage.go
  i18n/en.json
  model/feature_flags.go
Labels: 2: Dev Review, release-note

#20501 Check for nil,nil returned from GetUser
  app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#20503 Remove go.work files in make nuke
  Makefile
Labels: 4: Reviews Complete, release-note-none

#20485 jake/gh 20356
  app/file.go
  app/server.go
  app/users/profile_picture.go
  model/config.go
  shared/filestore/filesstore.go
  shared/filestore/s3_overrides.go
  shared/filestore/s3store.go
  shared/filestore/s3store_test.go
Labels: 4: Reviews Complete, release-note

#20195 [MM-44084] Feature: Top threads insights
  api4/insights.go
  api4/insights_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  i18n/en.json
  model/client4.go
  model/insights.go
  model/insights_test.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/thread_store.go
  store/store.go
  store/storetest/mocks/ThreadStore.go
  store/storetest/thread_store.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#20507 Automated cherry pick of #20506
  app/post_metadata_test.go
  go.mod
  go.sum
  model/link_metadata.go
  model/link_metadata_test.go
  store/storetest/link_metadata_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20489 MM-45159: Skip flaky TestCreateUserWithInitialPreferences
  app/user_test.go
Labels: 4: Reviews Complete, release-note-none

#20508 MM-45209 Revert PR checking for GetUser returning nil,nil
  app/user.go
Labels: 2: Dev Review, release-note-none

#20352 MM-44509 - subscription change not reflected after trial
  api4/cloud.go
  api4/cloud_test.go
  model/client4.go
  model/cloud.go
Labels: 2: Dev Review, release-note-none, Setup Cloud + CWS Test Server

#20283 Mm-20223 Add webp emoji support
  api4/emoji_test.go
  api4/file_test.go
  app/emoji.go
  tests/testwebp.webp
Labels: Setup Cloud Test Server, QA Review Done, release-note, Contributor

#20467 add check to generate migrations list
  .circleci/config.yml
  Makefile
  db/migrations/migrations.list
Labels: 4: Reviews Complete, release-note-none

#20516 MM-40450: Follow redirects in image proxy
  services/imageproxy/local.go
  services/imageproxy/local_test.go
Labels: 4: Reviews Complete, release-note-none

#20523 Pre-package Playbooks v1.28.2
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#20532 Automated cherry pick of #20518
  app/plugin_api_tests/test_set_profile_image_plugin/main.go
  app/plugin_install.go
  app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#20527 Additional Product APIs for Focalboard multi-product architecture
  .gitignore
  Makefile
  app/channels.go
  app/product.go
  app/server.go
  model/version.go
  product/api.go
  scripts/setup_go_work.sh
  shared/mlog/mlog.go
Labels: release-note-none

#20505 MM-45039 create mctx package
  app/request/context.go
Labels: release-note-none

#20538 Update version to 7.0.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20494 Adjustments to README
  README.md
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20542 Update latest version to 7.0.1
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#19382 [MM-41115] Add server-side username colorize preference
  app/export.go
  app/export_converters.go
  app/import_functions.go
  app/import_functions_test.go
  app/import_types.go
  model/preference.go
Labels: 4: Reviews Complete, release-note, Contributor

#20540 Sanitize cloud products for non admin users
  api4/cloud.go
  api4/cloud_test.go
  model/cloud.go
Labels: 2: Dev Review, release-note-none

#20534 MM-44863 - update trial details in product menu
  api4/cloud.go
  api4/cloud_test.go
Labels: 2: Dev Review, release-note-none

#20440 handle all JSON marshal errors in model/client4.go
  model/client4.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#20546 Add FileInfoStore and Cloud services for Focalboard multi product architecture
  app/cloud.go
  app/file.go
  app/server.go
  product/api.go
Labels: 2: Dev Review, release-note-none

#20560 cherry pick cloud weblate #20554
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#20353 GraphQL: Create dedicated top-level filter for sidebar categories
  api4/channel_category.go
  api4/resolver.go
  api4/resolver_sidebar_categories_test.go
  api4/resolver_team_member.go
  api4/resolver_team_member_test.go
  api4/schema.graphqls
  app/app_iface.go
  app/authorization_test.go
  app/channel_category.go
  app/channel_category_test.go
  app/channel_test.go
  app/opentracing/opentracing_layer.go
  app/plugin_api.go
  app/team.go
  app/team_test.go
  store/layer_generators/main.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/channel_store_categories.go
  store/store.go
  store/storetest/channel_store_categories.go
  store/storetest/mocks/ChannelStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#20563 Add KVStore service and Log service for Focalboard multi product architecture
  app/plugin_key_value_store.go
  app/server.go
  product/api.go
  shared/mlog/mlog.go
Labels: 2: Dev Review, release-note-none

#18232 [MM-36872] add threading headers to notification emails
  app/admin.go
  app/admin_advisor.go
  app/email/email.go
  app/email/email_batching.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/notification_email.go
  app/security_update_check.go
  shared/mail/mail.go
  shared/mail/mail_test.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#20550 [MM-45053] - Remove 'trial of Mattermost ending soon' product emails
  api4/cloud.go
  app/app_iface.go
  app/cloud.go
  app/email/email.go
  app/email/email_test.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/cloud.go
  templates/cloud_trial_end_warning.html
  templates/cloud_trial_end_warning.mjml
  templates/cloud_trial_ended_email.html
  templates/cloud_trial_ended_email.mjml
Labels: 2: Dev Review, release-note-none

#20557 [MM-45159] - Flaky test: TestCreateUserWithInitialPreferences
  app/user_test.go
Labels: 2: Dev Review, release-note-none

#20338 [MM-43649] - Ability for end users to notify admin to upgrade workspace
  api4/cloud.go
  api4/cloud_test.go
  app/app_iface.go
  app/cloud.go
  app/opentracing/opentracing_layer.go
  i18n/en.json
  model/client4.go
  model/cloud.go
  model/preference.go
Labels: 2: Dev Review, QA Deferred, release-note-none, Setup Cloud + CWS Test Server

#20568 Add Store service for Focalboard multi-product architecture
  app/server.go
  product/api.go
  store/store.go
Labels: 4: Reviews Complete, release-note-none

#20562 [MM-44159] Add user sort by admin status in channels
  api4/user.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/user.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/user_store.go
  store/store.go
  store/storetest/mocks/UserStore.go
  store/storetest/user_store.go
  store/timerlayer/timerlayer.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none
