Repository mattermost/mattermost, pull requests merged in 2023-11, with the labels that each got.

#25232 Admin console definition to typescript
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_definition.test.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar_category.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/enable_plugin_setting.ts
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/sass/routes/_admin-console.scss
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/selectors/admin_console.test.jsx
  webapp/channels/src/utils/admin_console_index.test.tsx
  webapp/channels/src/utils/admin_console_index.tsx
  webapp/channels/src/utils/admin_console_plugin_index.ts
  webapp/package-lock.json
Labels: 2: Dev Review, Docs/Not Needed, QA/Review Done, release-note-none

#25236 Fix flaky test introduced in #24602
  server/channels/app/post_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#25229 Added YouTube Link in README.md Get the latest news Section
  README.md
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25160 [MM-55170] Improve error message when trying to activate a plugin in an unsupported environment
  server/public/plugin/supervisor.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#25180 Reduce usage of mlog.Any
  server/channels/app/import_functions.go
  server/channels/app/platform/web_conn.go
  server/channels/app/post.go
  server/channels/app/syncables.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/group.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#24580 E2E test for multi-word keywords that highlight without notifications
  e2e-tests/playwright/support/ui/components/channels/delete_post_modal.ts
  e2e-tests/playwright/support/ui/components/channels/settings/notification_settings.ts
  e2e-tests/playwright/support/ui/components/channels/settings/settings_modal.ts
  e2e-tests/playwright/support/ui/components/global_header.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/pages/channels.ts
  e2e-tests/playwright/tests/functional/channels/settings/notifications/highlight_without_notification.spec.ts
Labels: 4: Reviews Complete, release-note-none

#25256 MM-54445 - MM-54444 - Calls: update plugin for security fix on v8.1
  server/Makefile
Labels: 4: Reviews Complete, release-note

#25258 MM-54445 - MM-54444 - Calls: update plugin for security fix on v7.8
  Makefile
Labels: 4: Reviews Complete, release-note

#25085 [MM-54758] Thread/posts jump when switching to and from preview mode
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25010 [MM-54357] Recent Mentions is showing posts for other similar named users.
  server/channels/store/searchtest/post_layer.go
  server/channels/store/sqlstore/post_store.go
  webapp/channels/src/actions/views/rhs.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#24873 [MM-54403] Introduce separate AdvanctedLogging levels for LDAP messages
  server/channels/api4/ldap.go
  server/public/shared/mlog/levels.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#25264 [MM-55112] Replace usage of LocalizedIcon in 'user_settings_notifications.tsx' with i/span tags
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25276 Update version.go to v9.3.0
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25277 Update version.go to v9.2.1
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25244 Manual cherrypick #24622
  webapp/channels/src/components/channel_layout/center_channel/center_channel.tsx
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/utils/path.ts
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, EETests, release-note-none

#25280 Manual cherrypick #24622
  webapp/channels/src/components/channel_layout/center_channel/center_channel.tsx
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/utils/path.ts
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25266 Update documentation on JS API client
  api/v4/source/introduction.yaml
  webapp/platform/client/README.md
Labels: 4: Reviews Complete, release-note-none

#25118 [MM-32406] Introduce trace logging level for LDAP messages
  server/channels/api4/hosted_customer.go
  server/channels/api4/ldap.go
  server/channels/app/app_iface.go
  server/channels/app/ldap.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/support_packet.go
  server/einterfaces/cloud.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/CloudInterface.go
  server/einterfaces/mocks/LdapInterface.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#25035 [MM-55051] Assign correct timestamp to support packet files
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/app/support_packet.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#24999 Replace `fmt.Sprint` usages with faster alternatives such as `strconv.FormatBool`
  server/channels/api4/hosted_customer.go
  server/channels/app/notification_email.go
  server/channels/app/platform/session.go
  server/channels/store/searchtest/helper.go
  server/channels/utils/hash.go
  server/cmd/mmctl/commands/utils_unix.go
  server/config/client.go
  server/platform/services/searchengine/bleveengine/testlib.go
Labels: 4: Reviews Complete, Hacktoberfest, QA/Deferred, release-note-none, Contributor

#24735 [MM-53204] Wont show "reset password" link if only LDAP/AD enabled
  webapp/channels/src/components/login/login.tsx
Labels: 4: Reviews Complete, Hacktoberfest, Lifecycle/1:stale, QA/Review Done, AutoMerge, hacktoberfest-accepted, release-note, Contributor

#25262 [MM-55212] Migrate server/channels/app/channel.go to make use of GenericStoreResult
  server/channels/app/channel.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, Contributor

#25271 feat: Introduce go-version file to support multiple go versions on CI
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci-master.yml
  .github/workflows/server-ci-pr.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  server/.go-version
Labels: 2: Dev Review, kind/feature, release-note-none

#25225 MM-55202-remove 'boards' from help command
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25279 Fix - Run artifacts workflow only for monorepo branches
  .github/workflows/server-ci-artifacts.yml
Labels: 2: Dev Review, release-note-none

#25273 feat: Introduce go-version file to support multiple go versions on CI
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci-master.yml
  .github/workflows/server-ci-pr.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  server/.go-version
Labels: 2: Dev Review, kind/feature, release-note-none

#25274 feat: Introduce go-version file to support multiple go versions on CI
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci-master.yml
  .github/workflows/server-ci-pr.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  server/.go-version
Labels: 2: Dev Review, kind/feature, release-note-none

#25275 feat: Introduce go-version file to support multiple go versions on CI
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci-master.yml
  .github/workflows/server-ci-pr.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  server/.go-version
Labels: 2: Dev Review, kind/feature, release-note-none

#25287 CLD-6507 - Fix the monorepo-checker CI job
  .github/workflows/server-ci-artifacts.yml
Labels: release-note-none

#25185 Update version to 7.8.14
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24958 MM-53764 - Remove OpenGraph section from API docs
  api/v4/source/introduction.yaml
Labels: 4: Reviews Complete, release-note-none

#25290 Fix typo in emoji code
  webapp/channels/src/actions/emoji_actions.js
Labels: 4: Reviews Complete, release-note-none

#25268 [MM-55106] Replace usage of LocalizedIcon in 'system_notice.tsx' with i/span tags
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
  webapp/channels/src/components/system_notice/system_notice.test.tsx
  webapp/channels/src/components/system_notice/system_notice.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#24971 Fix racy test issues
  server/channels/api4/apitestlib.go
  server/channels/api4/channel.go
  server/channels/api4/remote_cluster.go
  server/channels/api4/upload.go
  server/channels/api4/user.go
  server/channels/app/app_iface.go
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/app/compliance.go
  server/channels/app/context.go
  server/channels/app/file.go
  server/channels/app/helper_test.go
  server/channels/app/import.go
  server/channels/app/login.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/post.go
  server/channels/app/team_test.go
  server/channels/app/upload.go
  server/channels/jobs/batch_migration_worker.go
  server/channels/jobs/helper_test.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/sqlstore/context.go
  server/channels/store/sqlstore/context_test.go
  server/channels/web/context.go
  server/channels/web/context_test.go
  server/channels/web/handlers.go
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/channels/web/saml.go
  server/channels/web/web_test.go
  server/cmd/mattermost/commands/export.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/public/shared/request/context.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#24963 [MM-54816] Convert ./components/admin_console/color_setting.tsx from Class Component to Function Component
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/color_setting.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#25186 MM-54737 Fix error when updating a GM/DM
  webapp/channels/src/actions/websocket_actions.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24861 [GH-24745] Convert ./components/admin_console/setting.tsx from Class Component to Function Component
  webapp/channels/src/components/admin_console/__snapshots__/custom_url_schemes_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/radio_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/setting.tsx
Labels: 4: Reviews Complete, Hacktoberfest, Lifecycle/1:stale, QA/Review Done, release-note-none, Contributor

#24974 [MM-54820] Convert ./components/channel_header_mobile/unmute_channel_button/unmute_channel_button.tsx from Class Component to Function Component
  webapp/channels/src/components/channel_header_mobile/unmute_channel_button/unmute_channel_button.test.tsx
  webapp/channels/src/components/channel_header_mobile/unmute_channel_button/unmute_channel_button.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#25265 [MM-55213] GenericStoreResult in channels (#25234)
  server/channels/app/command.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, Contributor

#25285 release-7.8 cherry pick of #25010
  store/searchtest/post_layer.go
  store/sqlstore/post_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#25315 Remove dead method Handle404
  server/channels/app/app.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Not Required, release-note-none

#25316 Update version.go
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25284 release-8.1 cherry pick of #25010
  server/channels/store/searchtest/post_layer.go
  server/channels/store/sqlstore/post_store.go
  webapp/channels/src/actions/views/rhs.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, EETests, release-note-none

#25281 Update playbooks to v1.39.1
  server/Makefile
Labels: 2: Dev Review, Setup Cloud Test Server, release-note

#25247 [CLD-6528] Fix preparing workspace redirecting to invalid channel
  webapp/channels/src/components/preparing_workspace/preparing_workspace.tsx
Labels: 4: Reviews Complete, release-note-none

#25227 [MM-55164] Fix deadlock on shutdown due to stuck goroutine
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note

#25325 Update version to 7.8.15
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, EETests, release-note-none

#25327 Update version.go for v8.1
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25328 Update version.go for v9.0
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25329 Update version.go for v9.1
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24250 [MM-54029] IDP descriptor can any string
  server/i18n/en.json
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note-none

#25192 [MM-55294] Migrate jest v26 to v29 to speed up "web app CI PR / test"
  webapp/channels/jest.config.js
  webapp/channels/package.json
  webapp/channels/src/actions/views/create_comment.test.jsx
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/add_user_to_channel_modal/add_user_to_channel_modal.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.test.tsx
  webapp/channels/src/components/autocomplete_selector.tsx
  webapp/channels/src/components/browse_channels/browse_channels.test.tsx
  webapp/channels/src/components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx
  webapp/channels/src/components/emoji/emoji_list_item/emoji_list_item.tsx
  webapp/channels/src/components/more_direct_channels/more_direct_channels.test.tsx
  webapp/channels/src/components/post_view/commented_on/commented_on.tsx
  webapp/channels/src/components/post_view/post_message_preview/post_message_preview.tsx
  webapp/channels/src/components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
  webapp/channels/src/components/search_bar/search_bar.tsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
  webapp/channels/src/components/three_days_left_trial_modal/__snapshots__/three_days_left_trial_modal.test.tsx.snap
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/tests/setup_jest.ts
  webapp/package-lock.json
  webapp/platform/client/jest.config.js
  webapp/platform/client/setup_jest.ts
  webapp/platform/components/jest.config.js
  webapp/platform/components/package.json
  webapp/platform/components/setup_jest.ts
  webapp/platform/components/tsconfig.json
Labels: 4: Reviews Complete, release-note-none

#25037 [MM-55053] Use request-specific logger in channels/app/file.go
  server/channels/api4/drafts.go
  server/channels/api4/file.go
  server/channels/api4/post.go
  server/channels/app/app_iface.go
  server/channels/app/draft.go
  server/channels/app/draft_test.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/app/import_functions.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/post.go
  server/channels/app/post_metadata.go
  server/channels/app/post_test.go
  server/channels/app/slack.go
  server/channels/app/upload.go
  server/channels/app/user_test.go
  server/platform/services/slackimport/slackimport.go
  server/platform/services/slackimport/slackimport_test.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#25040 CLD-5699 Preliminary fixes
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/.e2erc_setup
  e2e-tests/.ci/.env.cypress
  e2e-tests/.ci/.env.dashboard
  e2e-tests/.ci/.env.server
  e2e-tests/.ci/.env.server.cloud
  e2e-tests/.ci/.gitignore
  e2e-tests/.ci/dashboard.override.yml
  e2e-tests/.ci/dashboard.start.sh
  e2e-tests/.ci/dashboard.stop.sh
  e2e-tests/.ci/docker-compose.cypress.yml
  e2e-tests/.ci/docker-compose.playwright.yml
  e2e-tests/.ci/docker_compose_generator.sh
  e2e-tests/.ci/server.cloud_customer_delete.sh
  e2e-tests/.ci/server.cloud_init.sh
  e2e-tests/.ci/server.cloud_teardown.sh
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.run_playwright.sh
  e2e-tests/.ci/server.run_test.sh
  e2e-tests/.ci/server.start.sh
  e2e-tests/.ci/server.stop.sh
  e2e-tests/.gitignore
  e2e-tests/Makefile
  e2e-tests/README.md
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
Labels: 2: Dev Review, release-note-none

#25115 loading_spinner.tsx converted to functional component.
  webapp/channels/src/components/__snapshots__/loading_image_preview.test.tsx.snap
  webapp/channels/src/components/__snapshots__/pdf_preview.test.jsx.snap
  webapp/channels/src/components/admin_console/data_grid/__snapshots__/data_grid.test.tsx.snap
  webapp/channels/src/components/apps_form/__snapshots__/apps_form_component.test.tsx.snap
  webapp/channels/src/components/widgets/loading/__snapshots__/loading_wrapper.test.tsx.snap
  webapp/channels/src/components/widgets/loading/loading_spinner.test.tsx
  webapp/channels/src/components/widgets/loading/loading_spinner.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, kind/feature, release-note-none, Contributor

#25080 [MM-54804] Convert ./components/post_emoji/post_emoji.tsx from Class Component to Function Component
  webapp/channels/src/components/post_emoji/post_emoji.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#25320 Mm 55298 generic integration action
  server/channels/app/integration_action.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, Contributor

#25345 Automated cherry pick of #25281
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25346 Automated cherry pick of #25281
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25348 Update playbooks to v1.39.1 (#25281)
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note-none

#25349 Update playbooks to v1.39.1 (#25281)
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note-none

#25295 [GH-21568] Add the request context and logger to all public methods in server/channels/app/auto_responder.go
  server/channels/api4/user.go
  server/channels/app/app_iface.go
  server/channels/app/auto_responder.go
  server/channels/app/auto_responder_test.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, Contributor

#25299 [MM-55107] Replace usage of LocalizedIcon in 'update_user_group_modal.tsx' with i/span tags
  webapp/channels/src/components/update_user_group_modal/__snapshots__/update_user_group_modal.test.tsx.snap
  webapp/channels/src/components/update_user_group_modal/update_user_group_modal.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25286 MM-54998: Optimize JSON marshalling in websocket broadcast
  server/channels/app/platform/web_conn.go
  server/public/model/websocket_message.go
  server/public/model/websocket_message_test.go
Labels: 4: Reviews Complete, release-note

#25347 MM-50246 - Updating custom styles for login page
  webapp/channels/src/components/login/login.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25213 [MM-55004] Add warning log message when app run as root
  server/cmd/mattermost/commands/root.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#25270 [GH-21566] Add request context and logger to all public methods in server/channels/app/authentication.go
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/import_functions.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/user.go
  server/channels/web/saml.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25156 MM-54774 - update session roles when promote/demote guests
  server/channels/app/platform/session.go
  server/channels/app/platform/session_test.go
  server/channels/app/user.go
Labels: 4: Reviews Complete, QA/Review Done, release-note

#25370 fix: Show proper version on about modal
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Labels: 2: Dev Review, kind/feature, release-note-none

#25163 MM-55050 - Updating Terms of Service page
  webapp/channels/src/components/terms_of_service/terms_of_service.tsx
  webapp/channels/src/sass/routes/_signup.scss
  webapp/channels/src/sass/utils/_flex.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25374 Automated cherry pick of #25370
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25375 Automated cherry pick of #25370
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25376 Automated cherry pick of #25370
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25377 Automated cherry pick of #25370
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24682 MM-53360 : Scroll to the bottom of channel banner
  webapp/channels/src/components/hint-toast/__snapshots__/hint_toast.test.tsx.snap
  webapp/channels/src/components/hint-toast/hint_toast.scss
  webapp/channels/src/components/hint-toast/hint_toast.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.tsx
  webapp/channels/src/components/scroll_to_bottom_toast/index.tsx
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.scss
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.test.tsx
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.tsx
  webapp/channels/src/components/toast_wrapper/toast__wrapper.scss
  webapp/channels/src/components/toast_wrapper/toast_wrapper.test.tsx
  webapp/channels/src/components/toast_wrapper/toast_wrapper.tsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, QA/Review Done, release-note, Contributor

#25371 Fix bad merge
  server/channels/app/import_functions.go
Labels: 4: Reviews Complete, release-note-none

#25383 Automated cherry pick of #25039
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24641 MM-54238 Add WebSocket broadcast hook and don't broadcast when other users were mentioned
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  server/channels/app/platform/helper_test.go
  server/channels/app/platform/service.go
  server/channels/app/platform/web_broadcast_hook.go
  server/channels/app/platform/web_broadcast_hook_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/server.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  server/public/model/websocket_message.go
Labels: 3: QA Review, Setup HA Cloud Test Server, release-note

#25154 Fixes #25120 - Horizontal scrollbar appearing on slash command autocomplete
  webapp/channels/src/sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, 2: Dev Review, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#25289 [MM-53432] Register WebVTT format to be previewable as text
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/syntax_highlighting.test.ts
  webapp/channels/src/utils/syntax_highlighting.tsx
Labels: 4: Reviews Complete, release-note

#25251 [MM-55009] Remove pre-fetch preference and set new pre fetch limits
  webapp/channels/src/components/data_prefetch/actions.test.tsx
  webapp/channels/src/components/data_prefetch/actions.ts
  webapp/channels/src/components/data_prefetch/data_prefetch.test.tsx
  webapp/channels/src/components/data_prefetch/data_prefetch.tsx
  webapp/channels/src/components/data_prefetch/index.ts
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/preferences.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#25350 [MM-55339] Improve types for Markdown component
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/markdown/__snapshots__/markdown.test.tsx.snap
  webapp/channels/src/components/markdown/index.ts
  webapp/channels/src/components/markdown/markdown.test.tsx
  webapp/channels/src/components/markdown/markdown.tsx
Labels: 4: Reviews Complete, release-note-none

#25317 [MM-55165] Remove target=_blank from file preview links
  webapp/channels/src/components/file_info_preview/__snapshots__/file_info_preview.test.tsx.snap
  webapp/channels/src/components/file_info_preview/file_info_preview.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#25366 Remove workflow failure check in favour of Argo-driven version
  .github/workflows/workflow-failure-check.yml
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#23176 [MM-52445] Fix double url encoding of oauth redirect URI params
  server/channels/app/oauth.go
  server/channels/web/oauth_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#25393 Wipe LDAP filter when running make config-ldap
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#24993 Convert status_icon_new.tsx to functional component
  webapp/channels/src/components/status_icon_new.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Deferred, kind/feature, release-note-none, Contributor

#25339 [MM-55300] Migrate "server/channels/app/post.go" to make use of GenericStoreResult
  server/channels/app/post.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25344 [MM-55305] Migrate "server/channels/store/sqlstore/post_store.go" to use GenericStoreResult
  server/channels/store/sqlstore/post_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25338 [MM-55299] Migrate server/channels/app/notification.go to make use of GenericStoreResult
  server/channels/app/notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25053 [GH-24843]: Fix customize_your_experience overlay position
  webapp/channels/src/components/global_header/right_controls/right_controls.tsx
  webapp/channels/src/components/tours/onboarding_tour/customize_your_experience_tour_tip.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25391 [MM-55409] Enable revive linter on enterprise code
  server/.golangci.yml
  server/channels/app/file.go
  server/channels/app/oauthproviders/gitlab/gitlab.go
  server/platform/shared/filestore/filesstore.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#25398 Upgrade "mattermost/compass-icons" to 0.1.39
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#25164 [MM-55102] Replace usage of LocalizedIcon in 'channel_intro_message.tsx' with i/span tags
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
Labels: 4: Reviews Complete, Hacktoberfest, kind/feature, release-note-none, Contributor

#25301 chore: migrate AWS SDK for JavaScript v2 APIs to v3 in e2e-tests
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
  e2e-tests/cypress/utils/artifacts.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#25404 Backport playbooks 1.36.3 to 7.8
  Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, EETests, release-note-none

#25388 [MM-55306] Migrate server/platform/services/telemetry/telemetry.go to make use of GenericStoreResult
  server/platform/services/telemetry/telemetry.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none, Contributor

#25402 [MM-55412] Use go-style error handling in team_controller
  webapp/channels/src/components/team_controller/team_controller.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#25389 fix: Fix about modal version for cloud installations
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Labels: 4: Reviews Complete, kind/bug, release-note-none

#25415 Automated cherry pick of #25389
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#25048 Switch to docker compose v2
  .github/workflows/esrupgrade-common.yml
  .github/workflows/migration.yml
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  server/Makefile
  server/build/local-test-env.sh
  server/scripts/replica-mysql-config.sh
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25418 Update version to 7.8.16
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24984 [MM-40384]: Channel notification settings modal UX revamp
  e2e-tests/cypress/tests/integration/channels/channel/channel_info_rhs_spec.js
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/channel_notifications_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/desktop_notifications_2_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/ignore_channel_mentions_spec.js
  webapp/channels/src/components/alert_banner.tsx
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.scss
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.test.tsx
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/collapse_view.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/describe.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/expand_view.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/extra_info.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/notification_section.test.jsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/__snapshots__/section_title.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/components/collapse_view.test.tsx
  webapp/channels/src/components/channel_notifications_modal/components/collapse_view.tsx
  webapp/channels/src/components/channel_notifications_modal/components/describe.test.tsx
  webapp/channels/src/components/channel_notifications_modal/components/describe.tsx
  webapp/channels/src/components/channel_notifications_modal/components/expand_view.test.tsx
  webapp/channels/src/components/channel_notifications_modal/components/expand_view.tsx
  webapp/channels/src/components/channel_notifications_modal/components/extra_info.test.tsx
  webapp/channels/src/components/channel_notifications_modal/components/extra_info.tsx
  webapp/channels/src/components/channel_notifications_modal/components/notification_section.jsx
  webapp/channels/src/components/channel_notifications_modal/components/notification_section.test.jsx
  webapp/channels/src/components/channel_notifications_modal/components/section_title.scss
  webapp/channels/src/components/channel_notifications_modal/components/section_title.test.tsx
  webapp/channels/src/components/channel_notifications_modal/components/section_title.tsx
  webapp/channels/src/components/channel_notifications_modal/index.ts
  webapp/channels/src/components/channel_notifications_modal/utils.tsx
  webapp/channels/src/components/widgets/modals/components/base_setting_item.scss
  webapp/channels/src/components/widgets/modals/components/base_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/checkbox_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/modal_header.scss
  webapp/channels/src/components/widgets/modals/components/modal_header.tsx
  webapp/channels/src/components/widgets/modals/components/modal_section.scss
  webapp/channels/src/components/widgets/modals/components/modal_section.tsx
  webapp/channels/src/components/widgets/modals/components/modal_sidebar.scss
  webapp/channels/src/components/widgets/modals/components/modal_sidebar.tsx
  webapp/channels/src/components/widgets/modals/components/radio_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/react_select_item.tsx
  webapp/channels/src/components/widgets/modals/components/save_changes_panel.scss
  webapp/channels/src/components/widgets/modals/components/save_changes_panel.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
  webapp/platform/types/src/channels.ts
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note, Contributor

#25332 MM-55267 Add ability for server-side Markdown code to understand emojis
  server/public/shared/markdown/emoji.go
  server/public/shared/markdown/emoji_test.go
  server/public/shared/markdown/html.go
  server/public/shared/markdown/inlines.go
  server/public/shared/markdown/markdown.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25411 [MM-55456] Add npm "test:updatesnapshot" command to workspace
  webapp/package.json
  webapp/platform/components/package.json
Labels: 4: Reviews Complete, release-note-none

#25399 [MM-55332] Convert `./components/permissions_gates/channel_permission_gate.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  webapp/channels/src/components/permissions_gates/channel_permission_gate/__snapshots__/channel_permission_gate.test.tsx.snap
  webapp/channels/src/components/permissions_gates/channel_permission_gate/channel_permission_gate.tsx
  webapp/channels/src/components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  webapp/channels/src/components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, EETests, release-note-none, Contributor

#25427 MM-54963 - Update prepackaged calls to v0.21.0
  server/Makefile
Labels: CherryPick/Approved, EETests, release-note

#25428 Automated cherry pick of #25427
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25401 [MM-55333] Convert `./components/post_view/floating_timestamp/floating_timestamp.tsx` from Class Component to Function Component
  webapp/channels/src/components/post_view/floating_timestamp/floating_timestamp.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none, Contributor

#25386 [MM-55334] Migrate `./components/admin_console/blockable_link/blockab_link.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/blockable_link/blockable_link.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/custom_policy_form/__snapshots__/custom_policy_form.test.tsx.snap
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/__snapshots__/global_policy_form.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_details.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
Labels: 4: Reviews Complete, QA/Review Done, release-note-none, Contributor

#25351 [MM-55304] Migrate "server/channels/store/searchlayer/user_layer.go" to use GenericStoreResult
  server/channels/store/searchlayer/user_layer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25368 [GH-21565]-Add the request context and logger to all public methods in server/channels/app/audit.go
  server/channels/api4/system.go
  server/channels/api4/user.go
  server/channels/app/app_iface.go
  server/channels/app/audit.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/web/context.go
  server/channels/wsapi/user.go
  server/cmd/mattermost/commands/export.go
  server/cmd/mattermost/commands/import.go
  server/cmd/mattermost/commands/jobserver.go
Labels: 4: Reviews Complete, Changelog/Not Needed, release-note-none, Contributor

#25341 fix: Add new and final dev registry for pr artifacts
  .github/workflows/server-ci-artifacts.yml
  e2e-tests/.ci/.e2erc
Labels: 2: Dev Review, kind/bug, release-note-none

#24168 [MM-52941] Adds from: suggestion when typing @ in search
  webapp/channels/src/components/search/search.tsx
Labels: 4: Reviews Complete, Lifecycle/1:stale, Setup Cloud Test Server, release-note-none, Contributor

#25070 [GH-25020] Add new resource links to [Help (?) drop-down menu] & icons
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  webapp/channels/src/components/widgets/menu/menu.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_item_action.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_item_external_link.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25437 Fix flaky test api4/Test_applyIPFilters
  server/channels/api4/ip_filtering.go
  server/channels/api4/ip_filtering_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#25430 MM-55450: Handle error in db migrate phase
  server/channels/store/sqlstore/migrate.go
Labels: 4: Reviews Complete, release-note-none

#25426 MM-55403: fix remote marketplace visibility
  webapp/channels/src/components/admin_console/plugin_management/index.ts
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.test.tsx
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25436 Update minimum supported Edge and Chrome versions
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, AutoMerge, release-note

#25405 MM-55060 - Calls: Add PushTypeCalls for calls-specific push notifications
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#25445 Automated cherry pick of #25405
  server/public/model/push_notification.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25446 Automated cherry pick of #25426
  webapp/channels/src/components/admin_console/plugin_management/index.ts
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.test.tsx
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25429 [MM-55336] Fixed team name alignment in channel switcher
  webapp/channels/src/sass/components/_suggestion-list.scss
Labels: CherryPick/Approved, release-note-none

#25422 Simplify request generation in store tests
  server/channels/app/plugin_api_tests/test_db_driver/main.go
  server/channels/jobs/batch_migration_worker_test.go
  server/channels/store/localcachelayer/emoji_layer_test.go
  server/channels/store/localcachelayer/layer_test.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/sqlstore/preference_store_test.go
  server/channels/store/sqlstore/store_test.go
  server/channels/store/storetest/audit_store.go
  server/channels/store/storetest/bot_store.go
  server/channels/store/storetest/channel_member_history_store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/channel_store_categories.go
  server/channels/store/storetest/cluster_discovery_store.go
  server/channels/store/storetest/command_store.go
  server/channels/store/storetest/command_webhook_store.go
  server/channels/store/storetest/compliance_store.go
  server/channels/store/storetest/desktop_tokens_store.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/emoji_store.go
  server/channels/store/storetest/file_info_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/license_store.go
  server/channels/store/storetest/link_metadata_store.go
  server/channels/store/storetest/notify_admin_store.go
  server/channels/store/storetest/oauth_store.go
  server/channels/store/storetest/plugin_store.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/storetest/post_persistent_notification_store.go
  server/channels/store/storetest/post_priority_store.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/storetest/product_notices_store.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/storetest/remote_cluster_store.go
  server/channels/store/storetest/retention_policy_store.go
  server/channels/store/storetest/role_store.go
  server/channels/store/storetest/scheme_store.go
  server/channels/store/storetest/session_store.go
  server/channels/store/storetest/shared_channel_store.go
  server/channels/store/storetest/status_store.go
  server/channels/store/storetest/system_store.go
  server/channels/store/storetest/team_store.go
  server/channels/store/storetest/terms_of_service_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/storetest/tokens_store.go
  server/channels/store/storetest/true_up_review_store.go
  server/channels/store/storetest/upload_session_store.go
  server/channels/store/storetest/user_access_token_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/storetest/user_terms_of_service.go
  server/channels/store/storetest/webhook_store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none

#25119 chore: remove deprecated "io/ioutil" imports
  server/cmd/mmctl/commands/auth_utils.go
  server/cmd/mmctl/commands/auth_utils_test.go
  server/cmd/mmctl/commands/config.go
  server/cmd/mmctl/commands/config_e2e_test.go
  server/cmd/mmctl/commands/config_test.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/license.go
  server/cmd/mmctl/commands/license_e2e_test.go
  server/cmd/mmctl/commands/license_test.go
  server/cmd/mmctl/commands/plugin_test.go
  server/cmd/mmctl/commands/sampledata.go
  server/cmd/mmctl/commands/sampledata_test.go
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/user_test.go
  server/cmd/mmctl/commands/utils.go
  server/cmd/mmctl/commands/utils_unix_test.go
  tools/mmgotool/commands/i18n.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Hacktoberfest, QA/Review Not Required, release-note-none, Contributor

#25447 Automated cherry pick of #25429
  webapp/channels/src/sass/components/_suggestion-list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24987 [MM-54933] Add the ability to @ mention custom groups in group constrained teams and channels
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#25457 Automated cherry pick of #24987
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25460 Automated cherry pick of #25458
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25304 [MM-55266] Fix AdvancedLoggingConfig validation
  server/public/model/config.go
  server/public/model/config_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#25463 Automated cherry pick of #25304
  server/public/model/config.go
  server/public/model/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25416 [MM-55335] Convert ./components/admin_console/filter/filter_checkbox.tsx from Class Component to Function Component
  webapp/channels/src/components/admin_console/filter/filter_checkbox.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none, Contributor

#25412 [MM-42586] Reaction toggle behavior
  webapp/channels/src/actions/post_actions.test.ts
  webapp/channels/src/actions/post_actions.ts
  webapp/channels/src/actions/views/create_comment.test.jsx
  webapp/channels/src/actions/views/create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.test.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_create_post/index.ts
  webapp/channels/src/components/post_view/post_reaction/index.ts
  webapp/channels/src/components/post_view/post_reaction/post_reaction.test.tsx
  webapp/channels/src/components/post_view/post_reaction/post_reaction.tsx
  webapp/channels/src/components/post_view/post_recent_reactions/index.ts
  webapp/channels/src/components/post_view/post_recent_reactions/post_recent_reactions.tsx
  webapp/channels/src/components/post_view/reaction_list/index.ts
  webapp/channels/src/components/post_view/reaction_list/reaction_list.tsx
  webapp/channels/src/components/post_view/reaction_list/reactions_list.test.tsx
  webapp/channels/src/utils/post_utils.test.tsx
  webapp/channels/src/utils/post_utils.ts
Labels: 4: Reviews Complete, release-note, Setup Cloud + CWS Test Server, Contributor

#25470 Automated cherry pick of #25435
  server/channels/app/product_notices.go
  server/channels/app/product_notices_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25475 Automated cherry pick of #25435
  server/channels/app/product_notices.go
  server/channels/app/product_notices_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25476 Automated cherry pick of #25435
  server/channels/app/product_notices.go
  server/channels/app/product_notices_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25477 Automated cherry pick of #25435
  server/channels/app/product_notices.go
  server/channels/app/product_notices_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25479 [MM-55401] Update pre-packaged Calls to v0.21.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#25480 [MM-55401] Update pre-packaged Calls to v0.21.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#25481 [MM-55401] Update pre-packaged Calls to v0.21.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24249 [MM-55268] Implement `ServeMetrics` plugins hook
  server/channels/app/platform/metrics.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go
  server/i18n/en.json
  server/public/plugin/client_rpc.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/interface_generator/main.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, release-note

#25443 Bump prepackage GitHub plugin version to 2.1.7
  server/Makefile
Labels: release-note

#25282 MM-40414: Add empty state icons
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_buttons_spec.js
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_post_spec.js
  e2e-tests/cypress/tests/integration/channels/bot_accounts/tags_spec.js
  e2e-tests/cypress/tests/integration/channels/channel/channel_info_rhs_spec.js
  e2e-tests/cypress/tests/integration/channels/channel/open_rhs_coming_from_system_console_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_3_spec.ts
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/dot_menu_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/esc_close_modal_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/pinned_posts_1_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/pinned_posts_2_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/post_options_menu_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/post_pre_header_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/private_channel_open_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/save_post_spec.js
  e2e-tests/cypress/tests/integration/channels/search/clear_input_spec.js
  e2e-tests/cypress/tests/integration/channels/search/cleared_search_term_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/helpers.js
  e2e-tests/cypress/tests/integration/channels/search_filter/negative_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs_spec.js
  e2e-tests/cypress/tests/support/ui/global_header.js
  e2e-tests/cypress/tests/support/ui/post.ts
  webapp/channels/src/components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  webapp/channels/src/components/channel_header/components/header_icon_wrapper.tsx
  webapp/channels/src/components/channel_info_rhs/menu.test.tsx
  webapp/channels/src/components/channel_info_rhs/menu.tsx
  webapp/channels/src/components/common/svg_images_components/channel_files_svg.tsx
  webapp/channels/src/components/common/svg_images_components/channel_search_svg.tsx
  webapp/channels/src/components/common/svg_images_components/index.ts
  webapp/channels/src/components/common/svg_images_components/mentons_svg.tsx
  webapp/channels/src/components/common/svg_images_components/pin_svg.tsx
  webapp/channels/src/components/common/svg_images_components/saved_messages_svg.tsx
  webapp/channels/src/components/common/svg_images_components/search_svg.tsx
  webapp/channels/src/components/common/svg_images_components/user_groups_members_svg.tsx
  webapp/channels/src/components/common/svg_images_components/user_groups_svg.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/__snapshots__/saved_posts_button.test.tsx.snap
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx
  webapp/channels/src/components/main_menu/__snapshots__/main_menu.test.tsx.snap
  webapp/channels/src/components/main_menu/main_menu.tsx
  webapp/channels/src/components/no_results_indicator/__snapshots__/no_results_indicator.test.tsx.snap
  webapp/channels/src/components/no_results_indicator/no_results_indicator.scss
  webapp/channels/src/components/no_results_indicator/no_results_indicator.test.tsx
  webapp/channels/src/components/no_results_indicator/no_results_indicator.tsx
  webapp/channels/src/components/no_results_indicator/types.ts
  webapp/channels/src/components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.tsx.snap
  webapp/channels/src/components/post_view/post_flag_icon/post_flag_icon.tsx
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
  webapp/channels/src/components/rhs_card_header/rhs_card_header.tsx
  webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx
  webapp/channels/src/components/search_results/search_results.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_list/user_groups_list.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, AutoMerge, release-note, Contributor

#25410 [MM-55455] Add "no-constant-binary-expression" eslint rule
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/menu/menu.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/eslint-plugin/configs/.eslintrc.json
Labels: 4: Reviews Complete, release-note-none

#25469 feat: Add docker image on artifacts generation summary
  .github/workflows/server-ci-artifacts.yml
Labels: kind/feature, release-note-none

#25221 [MM-55028] Added OAuthOutgoingConnection store
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000116_create_outgoing_oauth_connections.down.sql
  server/channels/db/migrations/mysql/000116_create_outgoing_oauth_connections.up.sql
  server/channels/db/migrations/postgres/000116_create_outgoing_oauth_connections.down.sql
  server/channels/db/migrations/postgres/000116_create_outgoing_oauth_connections.up.sql
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/retrylayer/retrylayer_test.go
  server/channels/store/sqlstore/outgoing_oauth_connection_store.go
  server/channels/store/sqlstore/outgoing_oauth_connection_store_test.go
  server/channels/store/sqlstore/store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/OutgoingOAuthConnectionStore.go
  server/channels/store/storetest/mocks/Store.go
  server/channels/store/storetest/outgoing_oauth_connection.go
  server/channels/store/storetest/store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/outgoing_oauth_connection.go
  server/public/model/outgoing_oauth_connection_test.go
Labels: kind/feature, release-note

#25500 reset to weblate upstream
  server/i18n/de.json
  server/i18n/hr.json
  server/i18n/hu.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/sv.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/el.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/id.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ka.json
  webapp/channels/src/i18n/kk.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lo.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/ml.json
  webapp/channels/src/i18n/ne.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sr.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: 2: Dev Review, QA/Review Not Required, release-note-none

#25183 MM-54814: Convert ./components/widgets/menu/menu_group.tsx from Class Component to Function Component
  webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
  webapp/channels/src/components/main_menu/__snapshots__/main_menu.test.tsx.snap
  webapp/channels/src/components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  webapp/channels/src/components/widgets/menu/menu_group.tsx
  webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#25505 MM-54774 - update session roles when promote/demote guests (#25156)
  server/channels/app/platform/session.go
  server/channels/app/platform/session_test.go
  server/channels/app/user.go
Labels: release-note

#24391 MM-52655 Allow plugin requests to include Authorization headers from external systems
  server/channels/app/plugin_requests.go
Labels: 3: QA Review, release-note, Contributor
