Repository mattermost/mattermost, pull requests merged in 2023-04, with the labels that each got.

#22530 MM-49564: Drafts upsert in the Store vs App layer
  model/draft.go
  model/draft_test.go
  server/channels/api4/drafts.go
  server/channels/app/app_iface.go
  server/channels/app/draft.go
  server/channels/app/draft_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/draft_store.go
  server/channels/store/store.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/mocks/DraftStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#22745 [MM-51098] Hide "copy invite link" when selecting guest - migrated from webapp
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_spec.ts
  webapp/channels/src/components/invitation_modal/invite_view.scss
  webapp/channels/src/components/invitation_modal/invite_view.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#22792 Boards: Avoid panic in Boards file request handler when file not found.
  server/boards/api/files.go
Labels: release-note, Area/Boards

#22770 open browse channels directly when user has no channel creation permissions
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
Labels: 2: Dev Review, QA Deferred, release-note-none

#22698 MM-50252_Refresh UI of the marketplace to improve first impressions
  webapp/channels/src/actions/command.ts
  webapp/channels/src/components/__snapshots__/generic_modal.test.tsx.snap
  webapp/channels/src/components/actions_menu/actions_menu.tsx
  webapp/channels/src/components/app_bar/app_bar_marketplace.tsx
  webapp/channels/src/components/custom_open_plugin_install_post_renderer/index.tsx
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/send_draft_modal.test.tsx.snap
  webapp/channels/src/components/generic_modal.scss
  webapp/channels/src/components/generic_modal.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  webapp/channels/src/components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/index.ts
  webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_app/__snapshots__/marketplace_item_app.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/__snapshots__/marketplace_item_plugin.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_list/marketplace_list.test.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_list/navigation_row/__snapshots__/navigation_row.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_list/navigation_row/index.ts
  webapp/channels/src/components/plugin_marketplace/marketplace_list/navigation_row/navigation_button.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.test.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.scss
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.test.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
  webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/__snapshots__/input.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/input.scss
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/utils/_mixins.scss
  webapp/platform/components/src/generic_modal/footer_content/__snapshots__/footer_pagination.test.tsx.snap
  webapp/platform/components/src/generic_modal/footer_content/footer_pagination.scss
  webapp/platform/components/src/generic_modal/footer_content/footer_pagination.test.tsx
  webapp/platform/components/src/generic_modal/footer_content/footer_pagination.tsx
  webapp/platform/components/src/generic_modal/footer_content/index.ts
  webapp/platform/components/src/generic_modal/generic_modal.tsx
  webapp/platform/components/src/index.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#22743 MM-51804 - add channels lhs not working
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: CherryPick/Approved, QA Review Done, release-note-none, Setup Cloud + CWS Test Server

#22731 MM-51768: Scrub username/password from SQL datasource
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/sqlstore/utils_test.go
  server/config/database.go
  server/config/database_test.go
  server/config/utils.go
  server/config/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#22796 Cherry pick MM-51885: Avoid panic in Boards file request handler
  server/boards/api/files.go
Labels: release-note

#22740 [MM-51724]
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: QA Deferred, release-note-none

#22752 MM-51845 : Remove any allusion of e2e from webapp
  webapp/channels/.eslintignore
  webapp/channels/.eslintrc.json
  webapp/channels/.gobom.json
  webapp/channels/Makefile
  webapp/channels/jest.config.js
  webapp/channels/package.json
  webapp/channels/tsconfig.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#22649 Fix add bot error handling
  webapp/channels/src/components/integrations/bots/add_bot/add_bot.tsx
Labels: 4: Reviews Complete, kind/bug, release-note-none, Contributor

#22780 MM-51870 Fix /test url and json
  server/channels/app/slashcommands/command_loadtest.go
Labels: CherryPick/Approved, QA Review Done, release-note-none

#22768 Fixed Add Channel_test_cases
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_sidebar_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/custom_categories_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/new_channel_dropdown_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_guest_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/system_scheme_permission_part2_spec.js
  e2e-tests/cypress/tests/integration/channels/mark_as_unread/helpers.js
  e2e-tests/cypress/tests/support/ui/sidebar_left.ts
Labels: 4: Reviews Complete, release-note-none

#22785 [MM-44860] Screen reader announcing link copied on copying the link in invite modal
  webapp/channels/src/components/invitation_modal/invite_view.tsx
Labels: QA Review Done, release-note

#22806 MM-51912 - fix not able to scroll in the LHS
  webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, QA Review Done, release-note-none

#22709 [MM-51236] - Add opt-in checkbox in self-hosted account creation page
  model/hosted_customer.go
  server/channels/api4/hosted_customer.go
  server/channels/einterfaces/cloud.go
  server/channels/einterfaces/mocks/CloudInterface.go
  server/i18n/en.json
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.scss
  webapp/channels/src/components/signup/signup.test.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/widgets/inputs/check/check.scss
  webapp/channels/src/components/widgets/inputs/check/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/cloud.ts
Labels: 2: Dev Review, 3: QA Review, release-note-none, 1. UX Review

#22811 MM-51804 - Manual cherry pick for (#22743) - add channels lhs not working
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22790 Update prepackage boards to v7.8.4
  Makefile
Labels: 4: Reviews Complete, release-note

#22791 update prepackage boards to v7.9.3
  Makefile
Labels: 4: Reviews Complete, release-note

#22664 fix announcement bar overlap after signup
  webapp/channels/src/sass/routes/_signup.scss
Labels: 4: Reviews Complete, QA Review Done, release-note, Contributor

#22803 Pre-package Playbooks v1.35.2 to v7.7
  Makefile
Labels: 2: Dev Review, release-note

#22802 Pre-package Playbooks v1.36.1 to v7.8
  Makefile
Labels: 2: Dev Review, release-note

#22801 Pre-package Playbooks v1.36.1 to v7.9
  Makefile
Labels: 2: Dev Review, release-note

#22807 fix: e2e tests
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/account_settings/account_settings_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/account_settings_position_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/email_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/fullname_edit_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/fullname_truncate_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/help_text_link_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/nickname_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/profile_picture_change_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/profile_picture_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/username_spec.ts
  e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/more_channels_spec.js
  e2e-tests/cypress/tests/integration/channels/channel/more_public_channels_spec.js
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_name_validations_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/custom_categories_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/new_channel_dropdown_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_group_sync_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/oauth/oauth_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/permissions/team_permissions_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/about/edition_and_license_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/builtin_commands/common_commands_1_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_shift_a_account_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
  e2e-tests/cypress/tests/integration/channels/menus/main_menu_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_recently_used_spec.js
  e2e-tests/cypress/tests/integration/channels/multi_team_and_dm/existing_channel_name_spec.js
  e2e-tests/cypress/tests/integration/channels/profile_settings/profile_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/settings/sidebar/fullname_spec.js
  e2e-tests/cypress/tests/support/ui/account_settings_modal.d.ts
  e2e-tests/cypress/tests/support/ui/account_settings_modal.js
  e2e-tests/cypress/tests/support/ui/channel.js
  e2e-tests/cypress/tests/support/ui/channel_sidebar.js
  e2e-tests/cypress/tests/support/ui/sidebar_left.ts
  e2e-tests/cypress/tests/support/ui_commands.ts
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#22810 MM-51915-fix no more channels to join text
  webapp/channels/src/i18n/en.json
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#22817 MM-51911 - The Delete Workspace Button Opens the Modal in a New Tab
  webapp/channels/src/components/admin_console/billing/delete_workspace/delete_workspace_cta.tsx
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#22823 fix various copy/paste/typos
  model/license.go
  server/channels/api4/license_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#22829 MM-51904 Fix choose different shipping spacing
  webapp/channels/src/components/choose_different_shipping/choose_different_shipping.scss
  webapp/channels/src/components/payment_form/mixins.scss
  webapp/channels/src/components/payment_form/payment_form.scss
Labels: 3: QA Review, CherryPick/Candidate, release-note-none, Setup Cloud + CWS Test Server

#22836 cherry-pick MM-51904 to cloud
  webapp/channels/src/components/choose_different_shipping/choose_different_shipping.scss
  webapp/channels/src/components/payment_form/mixins.scss
  webapp/channels/src/components/payment_form/payment_form.scss
Labels: release-note-none

#22800 [MM-51905] Fix: Successful trial request shows error modal
  model/config.go
  server/channels/utils/license-public-key-test.txt
  server/channels/utils/license-public-key.txt
  webapp/channels/src/components/start_trial_form_modal/index.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#22844 Manual cherry pick 22810
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22845 Merge pull request #22817 from mattermost/MM-51911-delete-workspace-b…
  webapp/channels/src/components/admin_console/billing/delete_workspace/delete_workspace_cta.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22846 [MM-51724] Cherry-pick for cloud
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22840 [MM-51724] Cherry-pick for release-7.9
  api4/user.go
  api4/user_test.go
Labels: release-note-none

#22848 Fix: License public keys incorrect
  model/config.go
  server/channels/utils/license-public-key-test.txt
  server/channels/utils/license-public-key.txt
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#22841 [MM-51724] Cherry-pick for release-7.8
  api4/user.go
  api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22843 [MM-51724] Cherry-pick for release-7.1
  api4/user.go
  api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22851 CP: MM-51768: Scrub username/password from SQL datasource
  config/database.go
  config/database_test.go
  config/utils.go
  config/utils_test.go
  store/sqlstore/store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, release-note-none

#22491 [MM-51302] Fix scroll to the bottom of editor after pasting long text
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/replies_spec.js
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/textbox/textbox.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#22853 CP: MM-51768: Scrub username/password from SQL datasource
  config/database.go
  config/database_test.go
  config/utils.go
  config/utils_test.go
  store/sqlstore/store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22854 CP: MM-51768: Scrub username/password from SQL datasource
  config/database.go
  config/database_test.go
  config/utils.go
  config/utils_test.go
  store/sqlstore/store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22855 CP: MM-51768: Scrub username/password from SQL datasource
  config/database.go
  config/database_test.go
  config/utils.go
  config/utils_test.go
  store/sqlstore/store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22837 [MM-51724] Cherry-pick for release-7.10
  api4/user.go
  api4/user_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22424 [MM-51034] Sanitize embedded posts transmitted over WS
  server/channels/app/post.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#22857 Automated cherry pick of #22424
  server/channels/app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22832 MM-51359 Replace makeGetUserTimezone selector with getCurrentTimezone and similar selectors
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/activity_and_insights/insights/top_channels/top_channels.tsx
  webapp/channels/src/components/custom_status/custom_status_emoji.test.tsx
  webapp/channels/src/components/custom_status/custom_status_emoji.tsx
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/dot_menu/index.ts
  webapp/channels/src/components/post_markdown/index.ts
  webapp/channels/src/components/post_reminder_custom_time_picker_modal/index.ts
  webapp/channels/src/components/post_view/post_edited_indicator/index.ts
  webapp/channels/src/components/profile_popover/index.ts
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/root/effects.ts
  webapp/channels/src/components/status_dropdown/index.ts
  webapp/channels/src/components/suggestion/search_date_suggestion/index.ts
  webapp/channels/src/components/timestamp/index.test.tsx
  webapp/channels/src/components/timestamp/index.ts
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/manage_timezones/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/timezone.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/timezone.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/timezone_utils.ts
  webapp/channels/src/selectors/general.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#22711 [MM-51489]: Fix issue with compact message mode
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/post/post_options.tsx
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note

#22784 Fixes MM-50733
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/oauth_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/OAuthStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#22856 CP: MM-51768: Scrub username/password from SQL datasource
  config/database.go
  config/database_test.go
  config/utils.go
  config/utils_test.go
  store/sqlstore/store.go
  store/sqlstore/utils.go
  store/sqlstore/utils_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22865 Automated cherry pick of #22784
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/oauth_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/OAuthStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22858 Automated cherry pick of #22711
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/post/post_options.tsx
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/responsive/_tablet.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22839 bind to localhost:0 for tests
  server/channels/api4/apitestlib.go
  server/channels/app/app_test.go
  server/channels/app/helper_test.go
  server/channels/app/platform/helper_test.go
  server/channels/app/platform/service_test.go
  server/channels/app/server_test.go
  server/channels/app/slashcommands/helper_test.go
  server/channels/web/web_test.go
  server/cmd/mattermost/commands/server_test.go
  server/playbooks/server/main_test.go
Labels: QA/Tests Not Required, release-note-none

#22727 [MM-50744] do not add event listeners to every visible post
  webapp/channels/src/components/post/post_component.tsx
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#22795 MM-51842: fix value-change detection in number properties
  webapp/boards/src/properties/number/__snapshots__/number.test.tsx.snap
  webapp/boards/src/properties/number/number.test.tsx
  webapp/boards/src/properties/number/number.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#22868 add screenshots section to github pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review, release-note-none

#22710 Adds support for public routes on shared boards
  server/boards/integrationtests/boardsapp_test.go
  server/boards/server/boards_service_util.go
  webapp/boards/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/boards/src/components/centerPanel.test.tsx
  webapp/boards/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/boards/src/components/kanban/kanbanColumnHeader.tsx
  webapp/boards/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/boards/src/components/shareBoard/shareBoard.tsx
  webapp/boards/src/components/shareBoard/shareBoardLoginButton.test.tsx
  webapp/boards/src/components/shareBoard/shareBoardLoginButton.tsx
  webapp/boards/src/components/viewHeader/viewHeader.tsx
  webapp/boards/src/components/viewTitle.tsx
  webapp/boards/src/components/workspace.test.tsx
  webapp/boards/src/hooks/permissions.tsx
  webapp/boards/src/index.tsx
  webapp/boards/src/public/app.tsx
  webapp/boards/src/types/mattermost-webapp/index.d.ts
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/plugins/pluggable/pluggable.tsx
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/types/store/plugins.ts
  webapp/channels/src/utils/test_helper.ts
  webapp/playbooks/src/index.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#22877 Adds support for public routes on shared boards (#22710)
  server/boards/integrationtests/boardsapp_test.go
  server/boards/server/boards_service_util.go
  webapp/boards/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/boards/src/components/centerPanel.test.tsx
  webapp/boards/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/boards/src/components/kanban/kanbanColumnHeader.tsx
  webapp/boards/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/boards/src/components/shareBoard/shareBoard.tsx
  webapp/boards/src/components/shareBoard/shareBoardLoginButton.test.tsx
  webapp/boards/src/components/shareBoard/shareBoardLoginButton.tsx
  webapp/boards/src/components/viewHeader/viewHeader.tsx
  webapp/boards/src/components/viewTitle.tsx
  webapp/boards/src/components/workspace.test.tsx
  webapp/boards/src/hooks/permissions.tsx
  webapp/boards/src/index.tsx
  webapp/boards/src/public/app.tsx
  webapp/boards/src/types/mattermost-webapp/index.d.ts
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/plugins/pluggable/pluggable.tsx
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/types/store/plugins.ts
  webapp/channels/src/utils/test_helper.ts
  webapp/playbooks/src/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, release-note

#22816 Fix playbooks e2e
  e2e-tests/cypress/tests/integration/playbooks/adminconsole/analytics_spec.js
  e2e-tests/cypress/tests/integration/playbooks/api/runs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/app_bar_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/broadcast_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/general_actions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/playbook_run_actions.js
  e2e-tests/cypress/tests/integration/playbooks/channels/post_type_components_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/retrospective_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/about_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/checklist_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/header_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/home_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/list_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/start_run_rhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/status_update_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/template_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/title_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/run_dialog_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/run_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/commands_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/info_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/owner_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/test_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/todo_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/update_request_post_spec.js
  e2e-tests/cypress/tests/integration/playbooks/digest_spec.js
  e2e-tests/cypress/tests/integration/playbooks/lhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/navigation_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/access_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/creation_button_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit/task_actions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit_metrics_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/feedback_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/list_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/overview_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/pagination_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/start_run_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/status_update_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/list_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/permissions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_general_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_checklist_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_finish_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_header_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_restore_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_retrospective_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_statusupdate_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_summary_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_taskactions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_rhs_participants_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_rhs_runinfo_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_rhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_rhs_statusupdates_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/taskinbox_spec.js
  e2e-tests/cypress/tests/integration/playbooks/tours_spec_ignore_.js
  e2e-tests/cypress/tests/support/ui/playbooks.js
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#22880 Added missing types
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#22884 Cherry pick: MM-51842: fix value-change detection in number properties
  webapp/boards/src/properties/number/__snapshots__/number.test.tsx.snap
  webapp/boards/src/properties/number/number.test.tsx
  webapp/boards/src/properties/number/number.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, release-note

#22886 Automated cherry pick of #22860
  webapp/channels/webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22878 MM-52001: i18n: Sync weblate changes for Boards and Playbooks
  webapp/boards/i18n/ar.json
  webapp/boards/i18n/de.json
  webapp/boards/i18n/en.json
  webapp/boards/i18n/en_AU.json
  webapp/boards/i18n/fr.json
  webapp/boards/i18n/he.json
  webapp/boards/i18n/hr.json
  webapp/boards/i18n/hu.json
  webapp/boards/i18n/it.json
  webapp/boards/i18n/ja.json
  webapp/boards/i18n/ka.json
  webapp/boards/i18n/ko.json
  webapp/boards/i18n/lt.json
  webapp/boards/i18n/nb_NO.json
  webapp/boards/i18n/nl.json
  webapp/boards/i18n/pl.json
  webapp/boards/i18n/pt.json
  webapp/boards/i18n/pt_BR.json
  webapp/boards/i18n/ru.json
  webapp/boards/i18n/sk.json
  webapp/boards/i18n/sv.json
  webapp/boards/i18n/tr.json
  webapp/boards/i18n/uk.json
  webapp/boards/i18n/zh_Hans.json
  webapp/boards/i18n/zh_Hant.json
  webapp/boards/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/boards/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/boards/src/components/calendar/fullCalendar.tsx
  webapp/boards/src/components/cardDetail/cardDetail.tsx
  webapp/boards/src/components/cardDetail/imagePaste.tsx
  webapp/boards/src/components/cardDialog.tsx
  webapp/boards/src/components/confirmAddUserForNotifications.tsx
  webapp/boards/src/components/content/attachmentElement.tsx
  webapp/boards/src/components/content/imageElement.tsx
  webapp/boards/src/components/gallery/galleryCard.tsx
  webapp/boards/src/components/kanban/kanbanCard.tsx
  webapp/boards/src/components/kanban/kanbanColumnHeader.tsx
  webapp/boards/src/components/onboardingTour/addProperties/add_properties.tsx
  webapp/boards/src/components/rhsChannelBoardItem.tsx
  webapp/boards/src/components/rhsChannelBoards.tsx
  webapp/boards/src/components/shareBoard/shareBoard.tsx
  webapp/boards/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/boards/src/components/table/tableGroupHeaderRow.tsx
  webapp/boards/src/components/table/tableRow.tsx
  webapp/boards/src/components/viewLImitDialog/viewLimitDialog.tsx
  webapp/boards/src/errors.ts
  webapp/boards/src/index.tsx
  webapp/playbooks/i18n/en_AU.json
  webapp/playbooks/i18n/fr.json
  webapp/playbooks/i18n/ko.json
  webapp/playbooks/i18n/pl.json
  webapp/playbooks/i18n/ru.json
  webapp/playbooks/i18n/tr.json
Labels: 4: Reviews Complete, release-note-none

#22754 MM-51831 : Add ESLint rule to "channels/components" to error out if "compass-components" package is used
  webapp/channels/.eslintrc.json
  webapp/channels/src/components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  webapp/channels/src/components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
  webapp/channels/src/components/app_bar/app_bar_marketplace.tsx
  webapp/channels/src/components/compass_theme_provider/compass_theme_provider.tsx
  webapp/channels/src/components/custom_status/date_time_input.tsx
  webapp/channels/src/components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  webapp/channels/src/components/global_header/center_controls/global_search_nav/global_search_nav.tsx
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  webapp/channels/src/components/global_header/left_controls/history_buttons/history_buttons.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding/product_branding.test.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding/product_branding.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_item/product_menu_item.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  webapp/channels/src/components/global_header/right_controls/at_mentions_button/at_mentions_button.test.tsx
  webapp/channels/src/components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/saved_posts_button.test.tsx
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx
  webapp/channels/src/components/global_header/right_controls/settings_button/settings_button.tsx
  webapp/channels/src/components/info_toast/info_toast.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_animations.tsx
  webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
  webapp/channels/src/components/post_view/post_edited_indicator/post_edited_indicator.tsx
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.test.tsx
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.tsx
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/components/suggestion/command_provider/command_provider.tsx
  webapp/channels/src/types/store/plugins.ts
Labels: 4: Reviews Complete, release-note-none

#22879 MM-52004 : Remove stub types packages for moment-timezone, highlightjs, classnames
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22875 MM-52005 : Add correct node version "engines" in root webapp
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22662 Resolving Error code "2" in Makefile for Stopping Processes
  webapp/Makefile
Labels: 4: Reviews Complete, release-note-none, Contributor

#22903 [fix] CI Correctly identify artifact downloads, calling workflow
  .github/workflows/artifacts.yml
Labels: release-note-none

#22825 [MM-51844 & MM-51843] Work template permissions check
  server/channels/app/worktemplates/templates.yaml
  server/channels/app/worktemplates/worktemplate_generated.go
  webapp/channels/src/components/work_templates/components/customize.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/worktemplates/playbooks/feature_lifecycle.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/playbooks.png
  webapp/channels/src/selectors/work_template.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#22905 Automated cherry pick of #22825
  server/channels/app/worktemplates/templates.yaml
  server/channels/app/worktemplates/worktemplate_generated.go
  webapp/channels/src/components/work_templates/components/customize.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/worktemplates/playbooks/feature_lifecycle.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/playbooks.png
  webapp/channels/src/selectors/work_template.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22881 MM-52003 : Remove unused and deprecated "mini-create-react-context" package
  webapp/boards/NOTICE.txt
  webapp/boards/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#22876 MM-52008 : Standardise package.json's version across all products in webapp
  webapp/boards/package.json
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/playbooks/package.json
Labels: 2: Dev Review, release-note-none

#22590 ESR Upgrade: One procedure per table in the v5.37 > v7.8 upgrade script
  scripts/esrupgrades/esr.5.37-7.8.mysql.up.sql
Labels: 2: Dev Review, release-note-none

#22911 E2E: expect boards product by default
  e2e-tests/cypress/tests/integration/channels/channel/new_channel_with_board_spec.js
  e2e-tests/playwright/global_setup.ts
  e2e-tests/playwright/support/constant.ts
  e2e-tests/playwright/support/flag.ts
  e2e-tests/playwright/support/server/client.ts
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/support/test_fixture.ts
  e2e-tests/playwright/test.config.ts
  e2e-tests/playwright/tests/functional/boards/board-creation-and-set-up/create_empty_board.spec.ts
  e2e-tests/playwright/tests/visual/boards/board_template.spec.ts
  e2e-tests/playwright/tests/visual/boards/view_untitled_board.spec.ts
Labels: 4: Reviews Complete, release-note-none

#22870 [MM-51990] Add 3 more options for company size dropdown
  webapp/channels/src/components/start_trial_form_modal/index.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#22913 MM-51461 - Prepackage calls v0.15.0
  server/Makefile
Labels: CherryPick/Approved, release-note, 3: Perf Review

#22914 Automated cherry pick of #22913
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22907 Deprecate Toolkit CODEOWNERS
  CODEOWNERS
Labels: QA/Tests Not Required, release-note-none

#22775 Rename event-id -> event_id for API naming consistency and safe parameter/variable name use
  server/playbooks/server/api/api.yaml
Labels: release-note, Contributor

#22815 [MM-26398] Remove deprecated model.CommandArgs.Session
  model/command_args.go
  server/channels/api4/command.go
Labels: 4: Reviews Complete, release-note

#22900 [MM-51878]: Migrate billing history unit test to testing library
  webapp/channels/src/components/admin_console/billing/__snapshots__/billing_history.test.tsx.snap
  webapp/channels/src/components/admin_console/billing/billing_history.test.tsx
  webapp/channels/src/components/admin_console/billing/billing_history.tsx
  webapp/channels/src/components/admin_console/billing/billing_history_table.tsx
Labels: 4: Reviews Complete, Tech/TypeScript, release-note, Migration: Enzyme to Testing library

#22920 Automated cherry pick of #22867
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22924 Do not shutdown DB handle from boards product
  server/boards/integrationtests/clienttestlib.go
  server/boards/server/server.go
Labels: 4: Reviews Complete, release-note-none

#22885 [MM-50827] Detect content-type if missing in response during link metadata generation
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note

#22929 Update version to 7.1.9
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22930 Update version to 7.7.5
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22931 Update version to 7.8.4
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22932 Update version to 7.9.3
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22622 [MM-51412] - In-product banner to communicate Cloud Free deprecation
  model/feature_flags.go
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/index.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.scss
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.test.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.tsx
  webapp/channels/src/components/alert_banner.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/channels/src/utils/constants.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Setup Cloud + CWS Test Server

#22527 [MM-51445] Replace compass-components icon component with compass icons
  webapp/channels/src/components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  webapp/channels/src/components/app_bar/app_bar_marketplace.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding/__snapshots__/product_branding.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding/product_branding.test.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding/product_branding.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_item/product_menu_item.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  webapp/channels/src/components/post_view/post_edited_indicator/post_edited_indicator.tsx
  webapp/channels/src/types/store/plugins.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#22936 Prepackage calls v0.15.1
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#22852 [MM-51479] Cloud Reverse Trial Banner Updates
  model/feature_flags.go
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_announcement-bar.scss
  webapp/channels/src/utils/constants.tsx
Labels: QA Deferred, release-note-none

#22940 Automated cherry pick of #22936
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22908 Work Template: use mattermost-server/playbooks package instead of old playbook repo
  go.mod
  go.sum
  server/channels/app/work_template_executor.go
  server/channels/app/work_templates_test.go
  server/channels/app/worktemplates/model.go
  server/channels/app/worktemplates/model_test.go
Labels: 2: Dev Review, release-note-none

#22921 Fix public boards setting not applying properly.
  server/boards/auth/auth.go
  server/boards/integrationtests/permissions_test.go
Labels: 2: Dev Review, release-note-none

#22669 [Webapp] added hour diff to profile
  webapp/channels/package.json
  webapp/channels/src/components/profile_popover/profile_localtime.tsx
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/i18n/en.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, AutoMerge, release-note

#22901 MM-52093 : Revert back the 'global-style' npmrc config
  webapp/.npmrc
Labels: 4: Reviews Complete, release-note-none

#22927 [MM-52121]: Migrate About build modal unit test to testing library
  webapp/channels/package.json
  webapp/channels/src/components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
  webapp/package-lock.json
Labels: 2: Dev Review, release-note, Migration: Enzyme to Testing library

#22898 GH21563: Add the request context and logger to all public methods in app/admin.go
  server/channels/api4/system.go
  server/channels/app/admin.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, release-note-none

#22830 Ensure feedback options are not submitting in their translated forms.
  webapp/channels/src/components/admin_console/billing/delete_workspace/delete_feedback.tsx
  webapp/channels/src/components/feedback_modal/downgrade_feedback.tsx
  webapp/channels/src/components/feedback_modal/feedback.tsx
Labels: 3: QA Review, release-note-none, Setup Cloud + CWS Test Server

#22849 [MM-51236] - Update newsletter opt-in copy
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.scss
  webapp/channels/src/components/signup/signup.test.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/widgets/inputs/check/check.scss
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, 1. UX Review

#22869 MM-51451 Replace all characters in generated values instead of just the first one
  webapp/channels/src/components/admin_console/schema_admin_settings.jsx
Labels: 4: Reviews Complete, release-note-none

#22833 MM-50577 Replaced makeCreateAriaLabelForPost with better memoized usePostAriaLabel
  webapp/channels/src/components/post_view/post_aria_label_div.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/latest_post_reader.test.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/latest_post_reader.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
  webapp/channels/src/utils/post_utils.ts
Labels: 2: Dev Review, QA Review Done, release-note

#22639 [MM-51413] - Update Cloud pricing modal to remove mentions of Cloud Free
  webapp/channels/src/components/pricing_modal/blank_card_image.svg.tsx
  webapp/channels/src/components/pricing_modal/card.tsx
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/components/pricing_modal/pricing_modal.scss
  webapp/channels/src/components/pricing_modal/self_hosted_content.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 3: QA Review, QA Deferred, release-note-none, Setup Cloud + CWS Test Server

#22933 server/channels: remove newWebConn method
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#22909 MM-49675: Update dependencies
  go.mod
  go.sum
Labels: 4: Reviews Complete, release-note-none

#22804 MM-51786: Sentry crash while installing a blocked plugin
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_install_test.go
  server/i18n/en.json
Labels: 2: Dev Review, release-note-none

#22676 MM-50746 - Edits to messages persist after cancelling
  e2e-tests/cypress/tests/integration/channels/messaging/edit_message_spec.js
  webapp/channels/src/components/edit_post/edit_post.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#22721 MM-49984: Displaying active search backend in system console
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/searchengine.go
  server/i18n/en.json
  server/platform/services/searchengine/searchengine.go
  server/platform/services/searchengine/searchengine_test.go
  webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/database_settings.jsx
  webapp/channels/src/components/admin_console/database_settings.test.jsx
  webapp/channels/src/i18n/en.json
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note

#22945 MM-52144 : Remove stub package "@types/react-day-picker"
  webapp/boards/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#22893 Translations update from Mattermost Weblate
  server/i18n/en_AU.json
  server/i18n/nl.json
  server/i18n/tr.json
  webapp/boards/i18n/fa.json
  webapp/boards/i18n/ka.json
  webapp/boards/i18n/lt.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/playbooks/i18n/ml.json
  webapp/playbooks/i18n/nl.json
Labels: release-note-none

#22956 MM-51662 Add more information to help text for SVGs and Latex
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note-none

#22883 Workspace dashboard improvements
  webapp/channels/src/components/admin_console/workspace-optimization/chips_list.test.tsx
  webapp/channels/src/components/admin_console/workspace-optimization/chips_list.tsx
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard.data.tsx
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard.tsx
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard.type.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/access.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/config.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/data_privacy.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/easy_management.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/performance.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/updates.ts
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#22962 MM-52165 : Remove 50% maxWorker on Channels test run
  webapp/boards/jest.config.js
  webapp/boards/package.json
  webapp/channels/build/contrib/gitlab/.gitlab-ci.yml
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22831 Add README to webapp folder
  webapp/README.md
  webapp/channels/README.md
  webapp/platform/README.md
Labels: 4: Reviews Complete, release-note-none

#22944 CWS URL public url fix
  model/config.go
Labels: QA Deferred, release-note-none

#22894 MM-51974 : Unify "react-intl" related dependencies versions across products
  webapp/boards/.eslintrc.json
  webapp/boards/package.json
  webapp/boards/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/boards/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/boards/src/components/sidebar/sidebarCategory.tsx
  webapp/channels/.eslintrc.json
  webapp/channels/package.json
  webapp/channels/src/components/__snapshots__/formatted_markdown_message.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.tsx.snap
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/cloud_subscribe_result_modal/__snapshots__/error.test.tsx.snap
  webapp/channels/src/components/cloud_subscribe_result_modal/__snapshots__/success.test.tsx.snap
  webapp/channels/src/components/code_block/__snapshots__/code_block.test.tsx.snap
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
  webapp/channels/src/components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  webapp/channels/src/components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
  webapp/channels/src/components/tours/crt_tour/crt_threads_pane_tutorial_tip.tsx
  webapp/channels/src/components/tours/crt_tour/crt_unread_tutorial_tip.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  webapp/channels/src/components/widgets/menu/menu_items/useWords.tsx
  webapp/channels/src/components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  webapp/channels/src/plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  webapp/channels/src/plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.tsx.snap
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/components/package.json
  webapp/platform/types/package.json
  webapp/playbooks/.eslintrc.json
  webapp/playbooks/i18n/en.json
  webapp/playbooks/package.json
  webapp/playbooks/src/components/backstage/metrics/metrics_card.tsx
  webapp/playbooks/src/components/backstage/playbook_list.tsx
  webapp/playbooks/src/components/backstage/playbook_list_row.tsx
  webapp/playbooks/src/components/backstage/playbook_runs/playbook_run/rhs_info_metrics.tsx
  webapp/playbooks/src/components/backstage/playbook_runs/playbook_run/status_update.tsx
  webapp/playbooks/src/components/backstage/runs_list/row.tsx
  webapp/playbooks/src/components/checklist_item/command.tsx
  webapp/playbooks/src/components/modals/run_playbook_modal.tsx
  webapp/playbooks/src/components/modals/update_run_status_modal.tsx
  webapp/playbooks/src/components/playbooks_selector.tsx
  webapp/playbooks/src/components/sidebar/sidebar.tsx
  webapp/playbooks/src/components/widgets/menu/menu_wrapper.tsx
Labels: 4: Reviews Complete, release-note-none

#22948 MM-51975 : Standardise Formatjs config for Playbooks & Boards
  webapp/boards/i18n/en.json
  webapp/boards/package.json
  webapp/playbooks/i18n/en.json
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22977 Skip flaky "sidebar template close other" Boards test temporarily
  webapp/boards/src/components/sidebar/sidebarCategory.test.tsx
Labels: 4: Reviews Complete, release-note-none

#22968 Remove redundant store APIs for Boards
  server/boards/api/blocks.go
  server/boards/app/blocks.go
  server/boards/app/blocks_test.go
  server/boards/app/export.go
  server/boards/integrationtests/boards_and_blocks_test.go
  server/boards/integrationtests/export_test.go
  server/boards/model/block.go
  server/boards/services/store/mockstore/mockstore.go
  server/boards/services/store/sqlstore/blocks.go
  server/boards/services/store/sqlstore/boards_and_blocks.go
  server/boards/services/store/sqlstore/public_methods.go
  server/boards/services/store/store.go
  server/boards/services/store/storetests/blocks.go
  server/boards/services/store/storetests/data_retention.go
Labels: 4: Reviews Complete, release-note-none

#22982 Automated cherry pick of #22310
  app/oauth.go
  app/oauth_test.go
  db/migrations/migrations.list
  db/migrations/mysql/000105_remove_tokens.down.sql
  db/migrations/mysql/000105_remove_tokens.up.sql
  db/migrations/postgres/000105_remove_tokens.down.sql
  db/migrations/postgres/000105_remove_tokens.up.sql
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/oauth_store.go
  store/store.go
  store/storetest/mocks/OAuthStore.go
  store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22986 POST playbook api specification includes public boolean definition
  server/playbooks/server/api/api.yaml
Labels: AutoMerge, release-note-none, Contributor

#22965 MM-51977 : Remove inconsistencies of the duplicate IDs with different defaultMessages
  webapp/channels/src/actions/command.ts
  webapp/channels/src/components/__snapshots__/setting_picture.test.tsx.snap
  webapp/channels/src/components/activity_and_insights/insights/top_channels/top_channels_line_chart/__snapshots__/top_channels_line_chart.test.tsx.snap
  webapp/channels/src/components/activity_and_insights/insights/top_channels/top_channels_line_chart/top_channels_line_chart.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/admin_console/request_button/__snapshots__/request_button.test.tsx.snap
  webapp/channels/src/components/admin_console/request_button/request_button.test.tsx
  webapp/channels/src/components/admin_console/server_logs/log_list.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  webapp/channels/src/components/apps_form/apps_form_component.tsx
  webapp/channels/src/components/apps_form/apps_form_container.tsx
  webapp/channels/src/components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
  webapp/channels/src/components/cloud_start_trial/cloud_start_trial_btn.tsx
  webapp/channels/src/components/dot_menu/dot_menu.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_preview.tsx
  webapp/channels/src/components/error_page/error_page.tsx
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/__snapshots__/file_preview_modal_main_nav.test.tsx.snap
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
  webapp/channels/src/components/header_footer_template/__snapshots__/header_footer_template.test.tsx.snap
  webapp/channels/src/components/header_footer_template/header_footer_template.tsx
  webapp/channels/src/components/integrations/__snapshots__/abstract_incoming_hook.test.tsx.snap
  webapp/channels/src/components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  webapp/channels/src/components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  webapp/channels/src/components/integrations/abstract_incoming_webhook.tsx
  webapp/channels/src/components/integrations/abstract_outgoing_webhook.jsx
  webapp/channels/src/components/integrations/bots/add_bot/__snapshots__/add_bot.test.tsx.snap
  webapp/channels/src/components/integrations/bots/add_bot/add_bot.test.tsx
  webapp/channels/src/components/integrations/bots/add_bot/add_bot.tsx
  webapp/channels/src/components/integrations/confirm_integration/__snapshots__/confirm_integration.test.tsx.snap
  webapp/channels/src/components/integrations/confirm_integration/confirm_integration.tsx
  webapp/channels/src/components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.tsx.snap
  webapp/channels/src/components/integrations/installed_oauth_apps/installed_oauth_apps.tsx
  webapp/channels/src/components/integrations/installed_outgoing_webhook.tsx
  webapp/channels/src/components/post_priority/post_priority_label.tsx
  webapp/channels/src/components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/self_hosted_purchase_modal/success_page.tsx
  webapp/channels/src/components/setting_picture.test.tsx
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  webapp/channels/src/components/team_groups_manage_modal/team_groups_manage_modal.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/plugins/call_button/call_button.tsx
Labels: 4: Reviews Complete, release-note-none

#22917 MM-51907 - Route True-Up Review Telemetry to CWS
  model/client4.go
  plugin/api_timer_layer_generated.go
  plugin/hooks_timer_layer_generated.go
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/channels/einterfaces/cloud.go
  server/channels/einterfaces/mocks/CloudInterface.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#22978 Playwright upgrade and small addition to ChannelsPage helper
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/playwright.config.ts
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  e2e-tests/playwright/support/ui/pages/channels.ts
Labels: 4: Reviews Complete, release-note-none

#22820 [MM-48670] Fix persistence of placeholder text
  webapp/channels/src/actions/views/create_comment.test.jsx
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.jsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_comment/index.ts
  webapp/channels/src/components/advanced_create_post/advanced_create_post.test.jsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_create_post/index.ts
  webapp/channels/src/components/drafts/__snapshots__/draft_row.test.tsx.snap
  webapp/channels/src/components/drafts/__snapshots__/drafts.test.tsx.snap
  webapp/channels/src/components/drafts/channel_draft/__snapshots__/channel_draft.test.tsx.snap
  webapp/channels/src/components/drafts/channel_draft/channel_draft.test.tsx
  webapp/channels/src/components/drafts/channel_draft/channel_draft.tsx
  webapp/channels/src/components/drafts/draft_row.test.tsx
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/components/drafts/drafts.test.tsx
  webapp/channels/src/components/drafts/drafts.tsx
  webapp/channels/src/components/drafts/index.ts
  webapp/channels/src/components/drafts/thread_draft/__snapshots__/thread_draft.test.tsx.snap
  webapp/channels/src/components/drafts/thread_draft/thread_draft.test.tsx
  webapp/channels/src/components/drafts/thread_draft/thread_draft.tsx
  webapp/channels/src/reducers/storage.ts
  webapp/channels/src/reducers/views/drafts.ts
  webapp/channels/src/reducers/views/index.ts
  webapp/channels/src/types/store/draft.ts
  webapp/channels/src/types/store/views.ts
  webapp/channels/src/utils/constants.tsx
Labels: Setup Cloud Test Server, release-note-none

#22979 Weblate 20220417
  server/i18n/bg.json
  server/i18n/de.json
  server/i18n/en_AU.json
  server/i18n/es.json
  server/i18n/fa.json
  server/i18n/fr.json
  server/i18n/hu.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/ko.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/ro.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/zh-CN.json
  server/i18n/zh-TW.json
  webapp/boards/i18n/fr.json
  webapp/boards/i18n/ja.json
  webapp/boards/i18n/nl.json
  webapp/boards/i18n/pt.json
  webapp/boards/i18n/ru.json
  webapp/boards/i18n/zh_Hans.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/tr.json
  webapp/playbooks/i18n/pl.json
Labels: release-note-none

#22757 Enable products for tests
  server/Makefile
  server/boards/model/services_api.go
  server/boards/server/notifications.go
  server/boards/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/boards/services/store/mattermostauthlayer/mattermostauthlayer_test.go
  server/boards/services/store/sqlstore/sqlstore.go
  server/channels/api4/apitestlib.go
  server/channels/api4/bot_test.go
  server/channels/api4/channel_test.go
  server/channels/api4/post_test.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/app_test.go
  server/channels/app/authorization_test.go
  server/channels/app/bot_test.go
  server/channels/app/channel_test.go
  server/channels/app/config.go
  server/channels/app/helper_test.go
  server/channels/app/notification_push_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/options.go
  server/channels/app/platform/config.go
  server/channels/app/platform/helper_test.go
  server/channels/app/platform/service_test.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_commands_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/post_test.go
  server/channels/app/product.go
  server/channels/app/product_test.go
  server/channels/app/server.go
  server/channels/app/server_test.go
  server/channels/app/slashcommands/helper_test.go
  server/channels/app/user_test.go
  server/channels/app/user_viewmembers_test.go
  server/channels/store/sqlstore/store.go
  server/channels/testlib/helper.go
  server/channels/testlib/store.go
  server/channels/testlib/testdata/boards_mysql_migration_warmup.sql
  server/channels/testlib/testdata/boards_postgres_migration_warmup.sql
  server/channels/web/web_test.go
  server/cmd/mattermost/commands/server_test.go
Labels: release-note-none

#22966 Bump autolink plugin version to 1.4.0
  server/Makefile
Labels: 4: Reviews Complete, release-note

#22958 Update version to 7.10.1
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#23006 Automated cherry pick of #22959
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22990 safer base64 generated values in settings
  webapp/channels/src/components/admin_console/generated_setting.tsx
Labels: 4: Reviews Complete, release-note

#23008 Revert "Automated cherry pick of #22310"
  app/oauth.go
  app/oauth_test.go
  db/migrations/migrations.list
  db/migrations/mysql/000105_remove_tokens.down.sql
  db/migrations/mysql/000105_remove_tokens.up.sql
  db/migrations/postgres/000105_remove_tokens.down.sql
  db/migrations/postgres/000105_remove_tokens.up.sql
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/oauth_store.go
  store/store.go
  store/storetest/mocks/OAuthStore.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22468 Update slash command permission
  server/channels/api4/command.go
  server/channels/api4/command_test.go
  server/model/permission.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#22887 MM-T4276 : E2E for set up Board emoji
  e2e-tests/cypress/tests/integration/boards/create_board_spec.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#23000 E2E/Playwright: Update dependencies, screenshots, config and type
  e2e-tests/playwright/README.md
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/sample.env
  e2e-tests/playwright/support/browser_context.ts
  e2e-tests/playwright/support/server/client.ts
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/support/server/init.ts
  e2e-tests/playwright/support/test_fixture.ts
  e2e-tests/playwright/support/ui/components/global_header.ts
  e2e-tests/playwright/test.config.ts
  e2e-tests/playwright/tests/visual/boards/board_template.spec.ts-snapshots/board-template-chrome-linux.png
  e2e-tests/playwright/tests/visual/boards/board_template.spec.ts-snapshots/board-template-firefox-linux.png
  e2e-tests/playwright/tests/visual/boards/board_template.spec.ts-snapshots/board-template-ipad-linux.png
  e2e-tests/playwright/tests/visual/boards/view_untitled_board.spec.ts-snapshots/view-untitled-board-chrome-linux.png
  e2e-tests/playwright/tests/visual/boards/view_untitled_board.spec.ts-snapshots/view-untitled-board-firefox-linux.png
  e2e-tests/playwright/tests/visual/boards/view_untitled_board.spec.ts-snapshots/view-untitled-board-ipad-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-iphone-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-iphone-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-iphone-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-iphone-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-iphone-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-iphone-linux.png
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#22973 MM-50122 : Remove and test refetching of channels on browser focus change
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/model/config.go
  server/platform/services/telemetry/telemetry.go
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#22631 MM-49214 : Filter out bot users shown in Apps modal form user pickers
  webapp/channels/src/components/apps_form/apps_form_field/apps_form_select_field.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#22981 MM-49603 : Remove fetching of deleted channels on page load
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, release-note

#22984 MM-50123 : Identify causes of removal of channel and channel members re fetching on team switch
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/components/team_controller/actions/index.ts
Labels: 4: Reviews Complete, release-note

#22888 MM-50427: Make MM survive DB replica outage
  server/boards/services/store/sqlstore/migrate.go
  server/channels/einterfaces/metrics.go
  server/channels/einterfaces/mocks/MetricsInterface.go
  server/channels/store/sqlstore/sqlx_wrapper.go
  server/channels/store/sqlstore/sqlx_wrapper_test.go
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/store_test.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/Store.go
  server/channels/store/storetest/settings.go
  server/channels/testlib/helper.go
  server/model/config.go
  server/platform/services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note

#22559 MM-45009: Delete ThreadMemberships from "left" channels
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.down.sql
  server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.up.sql
  server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.down.sql
  server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.up.sql
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ThreadStore.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#23031 Automated cherry pick of #22559
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.down.sql
  server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.up.sql
  server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.down.sql
  server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.up.sql
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ThreadStore.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22988 CI check for Boards and Playbooks i18n-extract
  .github/workflows/channels-ci.yml
Labels: 4: Reviews Complete, release-note-none

#22455 [MM-51089] Fix sorting value of category in CreateSidebarCategoryForTeamForUser
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#23029 Automated cherry pick of #22601
  app/post_metadata.go
  app/post_metadata_test.go
  app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#23030 Automated cherry pick of #22601
  app/post_metadata.go
  app/post_metadata_test.go
  app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#23003 Cherry-Pick PR 22917 into release-7.9
  api4/license.go
  api4/license_test.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#23005 Cherry-Pick PR 22917 into Cloud
  model/client4.go
  plugin/api_timer_layer_generated.go
  plugin/hooks_timer_layer_generated.go
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/channels/einterfaces/cloud.go
  server/channels/einterfaces/mocks/CloudInterface.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#22997 MM-51876 - use redirect if user already logged in
  webapp/channels/src/components/login/login.test.tsx
  webapp/channels/src/components/login/login.tsx
Labels: 4: Reviews Complete, release-note-none

#22955 [MM-52152] Expose license SkuShortName to all users
  server/channels/app/license_test.go
  server/channels/app/platform/license_test.go
  server/channels/utils/license.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Deferred, release-note-none
