Repository mattermost/mattermost, pull requests merged in 2023-02, with the labels that each got.

#22198 update libcurl3-gnutls (#22174)
  build/Dockerfile
Labels: 2: Dev Review, release-note-none

#22190 Automated cherry pick of #22119
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/email/email.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22192 Automated cherry pick of #22119
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/email/email.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22195 MM-49485: Properly disable plugin in product mode (round 2)
  app/channels.go
  app/plugin.go
  app/plugin_install.go
Labels: 4: Reviews Complete, QA Review Done, release-note

#22210 Bump Logr to version 2.0.16
  go.mod
  go.sum
Labels: 2: Dev Review, release-note

#22178 Automated cherry pick of #22156
  app/platform/web_hub_test.go
  model/websocket_message.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22211 error instead of panic if cloud endpoints are hit
  api4/cloud.go
  api4/hosted_customer.go
  api4/hosted_customer_test.go
  i18n/en.json
Labels: CherryPick/Approved, release-note

#22216 Automated cherry pick of #22211
  api4/cloud.go
  api4/hosted_customer.go
  api4/hosted_customer_test.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22223 Automated cherry pick of #22174
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22175 [MM-49991] Enable EnableOAuthServiceProvider by default
  model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note

#22186 Automated cherry pick of #22156
  app/platform/web_hub_test.go
  model/websocket_message.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21816 [MM-36289] App badge count fix for the direct messages
  store/sqlstore/user_store.go
Labels: 2: Dev Review

#22232 Automated cherry pick of #21816
  store/sqlstore/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22230 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22207 [MM-50082] Work templates: copy + other tweaks
  app/work_template_executor.go
  app/worktemplates/model.go
  app/worktemplates/model_test.go
  app/worktemplates/templates.yaml
  app/worktemplates/worktemplate_generated.go
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#22199 Manual cherry pick of (#22119) to Release 7.1
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/email/email.go
  app/opentracing/opentracing_layer.go
  app/status.go
  app/user.go
  app/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#22218 cherry-pick MM-50049
  api4/hosted_customer.go
  api4/hosted_customer_test.go
  i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22235 Automated cherry pick of #22118
  api4/hosted_customer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22188 Mm 49496 Add state and jobs for preventing screened purchase attempts from retrying
  api4/hosted_customer.go
  app/platform/license.go
  app/server.go
  jobs/hosted_purchase_screening/scheduler.go
  jobs/hosted_purchase_screening/worker.go
  model/job.go
  model/system.go
Labels: 2: Dev Review, QA Deferred, release-note

#22231 Automated cherry pick of #21816
  store/sqlstore/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22228 [MM-48010] Fetch Threads since parameter should return threads with new replies.
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: 4: Reviews Complete, CherryPick/Approved

#22241 Automated cherry pick of #22228
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22189 [MM-49921] Cloud export compliance
  api4/cloud.go
  model/cloud.go
Labels: release-note-none

#22239 update prepackage boards to v7.8.0
  Makefile
Labels: CherryPick/Approved, release-note

#22248 Automated cherry pick of #22239
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22247 Automated cherry pick of #22239
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22063 [MM-49034] Team data broadcasted are not sanitized and not targeted to the team
  app/team.go
  app/team_test.go
Labels: Setup Cloud Test Server, release-note-none

#22246 [OSF] Allows opening the work template modal from a slash command
  app/slashcommands/command_templates.go
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#22238 Work templates: move form SVG to PNG
  app/worktemplates/templates.yaml
  app/worktemplates/worktemplate_generated.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#22158 MM-49731 Regenerate emoji_data.go and gofmt it
  model/emoji_data.go
Labels: 4: Reviews Complete, release-note-none

#20945 MM-45494: Add endpoint for message history
  api4/post.go
  api4/post_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/post.go
  app/post_test.go
  db/migrations/migrations.list
  db/migrations/mysql/000102_posts_originalid_index.down.sql
  db/migrations/mysql/000102_posts_originalid_index.up.sql
  db/migrations/postgres/000102_posts_originalid_index.down.sql
  db/migrations/postgres/000102_posts_originalid_index.up.sql
  model/client4.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/post_store.go
  store/store.go
  store/storetest/mocks/PostStore.go
  store/storetest/post_store.go
  store/timerlayer/timerlayer.go
Labels: release-note, Contributor

#22171 MM-49868: Remove OpenId-custom free feature from cloud starter
  config/client.go
Labels: release-note-none, Setup Cloud + CWS Test Server

#22266 Automated cherry pick of #22171
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22263 [MM-50349] Add Feature Flag to Disable Tour Tips
  model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note-none

#22271 Automated cherry pick of #22263
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22267 MM-50355 - add senderId so the channel validations function can validate sender permissions when inviting guests
  api4/user_test.go
  app/email/email.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#22274 Automated cherry pick of #22267
  api4/user_test.go
  app/email/email.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22275 Automated cherry pick of #22267
  api4/user_test.go
  app/email/email.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22108 [MM-49744] Telemetry to track click on "Join Now" button in team invitation email
  app/email/email.go
Labels: release-note-none

#22278 MM-48504: Bump dependencies (#21994)
  app/server.go
  go.mod
  go.sum
  plugin/hclog_adapter.go
Labels: 2: Dev Review, release-note-none

#22276 Automated cherry pick of #22267
  api4/user_test.go
  app/email/email.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22279 Manual cherry pick of mattermost server 22119 upstream release 7.7
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/email/email.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22007 [MM-48029] notify admin for plugin install from work templates
  api4/notify_admin.go
  app/app_iface.go
  app/notify_admin.go
  app/notify_admin_test.go
  app/opentracing/opentracing_layer.go
  app/server.go
  db/migrations/migrations.list
  db/migrations/mysql/000103_add_sentat_to_notifyadmin.down.sql
  db/migrations/mysql/000103_add_sentat_to_notifyadmin.up.sql
  db/migrations/mysql/000104_upgrade_notifyadmin.down.sql
  db/migrations/mysql/000104_upgrade_notifyadmin.up.sql
  db/migrations/postgres/000103_add_sentat_to_notifyadmin.down.sql
  db/migrations/postgres/000103_add_sentat_to_notifyadmin.up.sql
  db/migrations/postgres/000104_upgrade_notifyadmin.down.sql
  db/migrations/postgres/000104_upgrade_notifyadmin.up.sql
  jobs/notify_admin/install_plugin_scheduler.go
  jobs/notify_admin/worker.go
  model/job.go
  model/notify_admin.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/notify_admin_store.go
  store/store.go
  store/storetest/mocks/NotifyAdminStore.go
  store/storetest/notify_admin_store.go
  store/timerlayer/timerlayer.go
Labels: Docs/Not Needed, release-note, Setup Cloud + CWS Test Server

#22226 Moving file response functionality to shared folder
  api4/cloud.go
  api4/file.go
  api4/hosted_customer.go
  api4/job.go
  api4/system.go
  shared/web/files.go
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note

#22283 Automated cherry pick of #22226
  api4/cloud.go
  api4/file.go
  api4/hosted_customer.go
  api4/job.go
  api4/system.go
  shared/web/files.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22280 MM-50355 - add senderId so the channel validations function can validate sender permissions when inviting guests (#22267)
  api4/user_test.go
  app/email/email.go
Labels: release-note-none

#22201 MM-48246 - AB test open RHS with linked board
  app/team.go
  i18n/en.json
  model/feature_flags.go
  model/preference.go
Labels: 2: Dev Review, release-note-none

#22289 Restore admin notify cooloff and remove debug logs
  api4/notify_admin.go
  app/notify_admin.go
Labels: 2: Dev Review, release-note-none

#22284 MM-50419: Fix panic at interface conversion
  shared/filestore/s3store.go
  shared/filestore/s3store_test.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22291 Moving file response functionality to shared folder (#22226)
  api4/cloud.go
  api4/file.go
  api4/hosted_customer.go
  api4/job.go
  api4/system.go
  shared/web/files.go
Labels: 4: Reviews Complete, release-note-none

#22282 [MM-50080] Limit max length for the name field
  app/work_templates.go
  app/work_templates_test.go
  i18n/en.json
Labels: 2: Dev Review, QA Deferred, release-note-none

#22294 MM-50419: Fix panic at interface conversion (#22284)
  shared/filestore/s3store.go
  shared/filestore/s3store_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22297 Update pre-package boards to v7.8.1
  Makefile
Labels: CherryPick/Approved, release-note

#22298 Automated cherry pick of #22297
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22245 MM-49851: forces PostPriority config to true
  app/migrations.go
  testlib/store.go
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved, release-note

#22299 MM-49679 - Prepackage calls 0.13.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#22300 Automated cherry pick of #22245
  app/migrations.go
  testlib/store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22302 Automated cherry pick of #22299
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22306 Add additional metadata to post reminder
  app/post.go
  model/post.go
Labels: 4: Reviews Complete, release-note-none

#22213 Revert "Revert "Set BoardsProduct FF to on by default" (#22177)"
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 4: Reviews Complete, release-note-none

#22315 Avoid divide by zero when hubs not created before first websocket msg
  app/platform/web_hub.go
Labels: 2: Dev Review, release-note-none

#22215 MM-49048: do not omit needed wsbroadcast vars (#22156)
  model/websocket_message.go
Labels: release-note-none

#22309 The GH token is not required for accesing PR metadata
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#22234 Automated cherry pick of #21816
  store/sqlstore/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22244 Automated cherry pick of #22228
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22243 Automated cherry pick of #22228
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22318 Automated cherry pick of #22304
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22314 MM-50443 - LdapSettings.SyncEnabled error message
  app/ldap.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#22323 Cherry pick of #22245
  app/migrations.go
  testlib/store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22319 The GH token is not required for accesing PR metadata (#22309)
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#22242 Automated cherry pick of #22228
  api4/user_test.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22330 Automated cherry pick of #21816
  store/sqlstore/user_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22329 Automated cherry pick of #22309
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22316 Update prepackaged boards to v7.8.2
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#22334 Cherry-pick: MM-50435: Improve data retention queries on MySQL (#22304)
  store/sqlstore/post_store.go
  store/sqlstore/thread_store.go
Labels: 2: Dev Review, release-note-none

#21153 Admin log table
  api4/system.go
  app/admin.go
  app/app_iface.go
  app/busy_test.go
  app/opentracing/opentracing_layer.go
  app/platform/busy_test.go
  app/platform/log.go
  einterfaces/cluster.go
  einterfaces/mocks/ClusterInterface.go
  i18n/en.json
  model/system.go
  testlib/cluster.go
Labels: Setup Cloud Test Server, release-note-none

#22331 Automated cherry pick of #22316
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22322 Improve error handling when plugin checksum fails
  plugin/supervisor.go
Labels: 4: Reviews Complete, release-note-none

#22296 [MM-48528] Add support for SendGrid X-SMTPAPI header in email sends
  app/admin.go
  app/admin_advisor.go
  app/email/email.go
  app/email/email_batching.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/notification_email.go
  app/security_update_check.go
  shared/mail/mail.go
  shared/mail/mail_test.go
Labels: 4: Reviews Complete, release-note-none

#22157 Update supported browser versions
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note

#22340 Update version to 7.8.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22355 Translations update from Mattermost Weblate
  i18n/vi.json
Labels: release-note-none

#22347 Update prepackage boards to v7.7.1
  Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#22363 Automated cherry pick of #22200
  api4/cloud.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/cloud.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22373 Cherry-picking translations
  i18n/de.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#22337 [MM-50516] Support multiple embed
  app/post_metadata.go
Labels: release-note-none

#22376 MM-47489 Assume Remote Cluster Service enabled if Shared Channels enabled.
  app/server.go
Labels: CherryPick/Approved, release-note

#22379 Cherry pick of #22337
  app/post_metadata.go
Labels: release-note-none

#22382 Cherry pick of #22337
  app/post_metadata.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22380 Cherry pick of #22337
  app/post_metadata.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22381 Cherry pick of #22337
  app/post_metadata.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22383 Cherry-pick MM-47489 (Shared Channels feature included in Professional license)
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22384 Cherry-pick MM-47489 (Shared Channels feature included in Professional license)
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22385 Cherry-pick MM-47489 (Shared Channels feature included in Professional license)
  app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#19662 fix plugin help example - method arguments order
  plugin/example_help_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#22390 update libcurl3-gnutls to 7.64.0-4+deb10u5
  build/Dockerfile
Labels: kind/bug, release-note-none

#22397 Mm 49495 Show past invoices for prior self-hosted purchases
  model/client4.go
  store/sqlstore/license_store.go
Labels: 2: Dev Review, release-note-none
