Repository mattermost/mattermost, pull requests merged in 2023-10, with the labels that each got.

#24629 MM-54361 - Update Calls plugin to v0.18.2
  server/Makefile
Labels: 4: Reviews Complete, release-note

#24662 MM-54361 - Update calls plugin to v0.13.1
  Makefile
Labels: 4: Reviews Complete, release-note

#24389 [MM-54493] Allow a user to disable the webapp prefetch
  webapp/channels/src/components/data_prefetch/data_prefetch.test.tsx
  webapp/channels/src/components/data_prefetch/data_prefetch.tsx
  webapp/channels/src/components/data_prefetch/index.ts
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/preferences.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#24619 update prepackage boards to v7.11.4
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#24614 MM-54555 - Include channel name in error
  server/channels/app/slashcommands/command_invite.go
  server/channels/app/slashcommands/command_invite_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#24677 Automated cherry pick of #24614
  server/channels/app/slashcommands/command_invite.go
  server/channels/app/slashcommands/command_invite_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24631 MM-54580: Fix panic in jobs/base_workers.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/jobs_test.go
Labels: 4: Reviews Complete, release-note

#23939 MM-52825 : Migrate "components/admin_console/database_settings.jsx" and tests to Typescript
  webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_settings.tsx
  webapp/channels/src/components/admin_console/database_settings.test.jsx
  webapp/channels/src/components/admin_console/database_settings.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#24636 Fix style for notices
  webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
  webapp/channels/src/components/system_notice/notices.tsx
  webapp/channels/src/components/system_notice/system_notice.tsx
  webapp/channels/src/sass/components/_system-notice.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#24681 Automated cherry pick of #24636
  webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
  webapp/channels/src/components/system_notice/notices.tsx
  webapp/channels/src/components/system_notice/system_notice.tsx
  webapp/channels/src/sass/components/_system-notice.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24621 Update minimum supported Edge version
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, AutoMerge, release-note

#24678 CP: MM-54580: Fix panic in jobs/base_workers.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24661 Update playbooks to v1.39.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup HA Cloud Test Server, release-note

#24594 Cypress/E2E: Upgrade cypress and test server config
  e2e-tests/cypress/.eslintrc.json
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
  e2e-tests/cypress/patches/@testing-library+cypress+9.0.0.patch
  e2e-tests/cypress/tests/integration/channels/channel/leave_and_archive_channel_destructive_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/cloud/billing/billing_history_free_trial_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/cloud/billing/payment_free_trial_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/extend_session/session_length_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/self-hosted/self_hosted_pricing_modal_spec.ts
  e2e-tests/cypress/tests/integration/playbooks/channels/app_bar_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
  e2e-tests/cypress/tests/support/api/bots.d.ts
  e2e-tests/cypress/tests/support/api/cloud_default_config.json
  e2e-tests/cypress/tests/support/api/group.ts
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
Labels: 4: Reviews Complete, release-note-none

#24195 MM-52792: Update createPost, updatePost, & patchPost
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/channels/app/post.go
  server/channels/web/context.go
  server/public/model/post.go
  server/public/model/post_test.go
  server/public/model/session.go
  server/public/model/session_test.go
Labels: 4: Reviews Complete, QA Review Done, release-note

#24692 Automated cherry pick of #24661
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24693 Automated cherry pick of #24636
  webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
  webapp/channels/src/components/system_notice/notices.tsx
  webapp/channels/src/components/system_notice/system_notice.tsx
  webapp/channels/src/sass/components/_system-notice.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24694 Automated cherry pick of #24614
  server/channels/app/slashcommands/command_invite.go
  server/channels/app/slashcommands/command_invite_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24695 Automated cherry pick of #24619
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24690 Automated cherry pick of #24661
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24697 Automated cherry pick of #24195
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/channels/app/post.go
  server/channels/web/context.go
  server/public/model/post.go
  server/public/model/post_test.go
  server/public/model/session.go
  server/public/model/session_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24332 MM-24276 Added "User joined and left" system messages
  webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx
  webapp/channels/src/components/post_view/combined_system_message/last_users.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#24698 MM-54361 - Update calls plugin to v0.17.1
  server/Makefile
Labels: 4: Reviews Complete, release-note

#24680 server/app: remove websocket_router.go
  server/channels/app/websocket_router.go
Labels: 4: Reviews Complete, release-note-none

#24633 MM-54581 Fixed a bug where converted GM showed up in incorrect team as well when someone else converted it
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channel_categories.ts
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#24181 Class to functional component example 1
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/autosize_textarea.test.tsx
  webapp/channels/src/components/autosize_textarea.tsx
  webapp/channels/src/components/common/hooks/useDidUpdate.ts
  webapp/platform/types/src/utilities.ts
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#24543 [MM-54497]Fix updatePost props
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24679 MM-54723 - Fixing btn icon sizes for RHS
  webapp/channels/src/sass/components/_buttons.scss
Labels: release-note-none

#24711 Automated cherry pick of #24633
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channel_categories.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24656 [MM-54024] Handle JSON nulls when unmarshalling in api4
  server/channels/api4/bot.go
  server/channels/api4/bot_test.go
  server/channels/api4/channel.go
  server/channels/api4/channel_local.go
  server/channels/api4/channel_test.go
  server/channels/api4/cloud.go
  server/channels/api4/data_retention.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/api4/hosted_customer.go
  server/channels/api4/notify_admin.go
  server/channels/api4/notify_admin_test.go
  server/channels/api4/saml.go
  server/channels/api4/system.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#24635 Minor refactor to simplify the getStateFromNotifyProps
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#24721 Automated cherry pick of #24635
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
Labels: release-note-none

#24634 Make GM Intro message to change based on the notification preferences.
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
  webapp/channels/src/components/post_view/channel_intro_message/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/channels.ts
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#24720 Automated cherry pick of #24635
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24725 Automated cherry pick of #24634
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
  webapp/channels/src/components/post_view/channel_intro_message/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24724 Automated cherry pick of #24634
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
  webapp/channels/src/components/post_view/channel_intro_message/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24670 Move the shared ESLint plugin/config into the monorepo
  webapp/channels/.eslintrc.json
  webapp/channels/package.json
  webapp/channels/src/components/external_link/index.tsx
  webapp/channels/src/components/size_aware_image.jsx
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/eslint-plugin/LICENSE.txt
  webapp/platform/eslint-plugin/README.md
  webapp/platform/eslint-plugin/configs/.eslintrc-react.json
  webapp/platform/eslint-plugin/configs/.eslintrc.json
  webapp/platform/eslint-plugin/index.js
  webapp/platform/eslint-plugin/package.json
  webapp/platform/eslint-plugin/rules/no-dispatch-getstate.js
  webapp/platform/eslint-plugin/rules/use-external-link.js
Labels: 4: Reviews Complete, release-note-none

#24705 Fixed a bug where channel URL preview used incorrect team
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#24708 Update e2e tests from upstream repository.
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/checklist_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/commands_spec.js
  e2e-tests/cypress/tests/support/ui/playbooks.js
Labels: 2: Dev Review, release-note-none

#24652 Remove usage of mattermost-redux from Cypress
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
  e2e-tests/cypress/tests/support/client-impl.js
Labels: 4: Reviews Complete, release-note-none

#24728 Automated cherry pick of #24705
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24732 Optimize mmctl CI run
  .github/workflows/mmctl-test-template.yml
  server/Makefile
Labels: 2: Dev Review, release-note-none

#24729 MM-54508 - MM-54769 - Update prepackaged Calls plugin to v0.20.0 for v9.1 and v9.2
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#24737 Update version to 7.8.13
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24736 Automated cherry pick of #24705
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24741 Update version to 8.0.5
  server/public/model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24746 Update version to 8.1.4
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24748 Update version to 9.0.2
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24493 [MM-54434] Use job.Logger to capture ldap logs
  server/channels/api4/command_test.go
  server/channels/api4/ldap.go
  server/channels/api4/saml.go
  server/channels/api4/system.go
  server/channels/api4/team_test.go
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/channels.go
  server/channels/app/enterprise_test.go
  server/channels/app/import_test.go
  server/channels/app/job_test.go
  server/channels/app/ldap.go
  server/channels/app/login.go
  server/channels/app/notify_admin_test.go
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/oauthproviders/gitlab/gitlab.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_commands_test.go
  server/channels/app/plugin_test.go
  server/channels/app/saml.go
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/channels/app/team_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/migrations/helper_test.go
  server/channels/jobs/migrations/migrations_test.go
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/channels/web/saml.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/extract_e2e_test.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/cmd/mmctl/commands/ldap_e2e_test.go
  server/einterfaces/account_migration.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/AccountMigrationInterface.go
  server/einterfaces/mocks/LdapInterface.go
  server/einterfaces/mocks/NotificationInterface.go
  server/einterfaces/mocks/OAuthProvider.go
  server/einterfaces/mocks/SamlInterface.go
  server/einterfaces/notification.go
  server/einterfaces/oauthproviders.go
  server/einterfaces/saml.go
  server/platform/services/slackimport/slackimport_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: 4: Reviews Complete, release-note-none

#24754 Convert ./components/admin_console/user_grid/user_grid_name.tsx to a function component #24740
  webapp/channels/src/components/admin_console/user_grid/user_grid_name.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#24818 [MM-54829] Convert LocalizedInput of 'emoji_list.tsx' to regular input component
  webapp/channels/src/components/emoji/emoji_list/emoji_list.tsx
Labels: 4: Reviews Complete, release-note-none

#24650 Pass a logger instead of embedding on job
  server/channels/app/job_test.go
  server/channels/jobs/active_users/worker.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/cleanup_desktop_tokens/worker.go
  server/channels/jobs/expirynotify/worker.go
  server/channels/jobs/export_delete/worker.go
  server/channels/jobs/export_process/worker.go
  server/channels/jobs/extract_content/worker.go
  server/channels/jobs/hosted_purchase_screening/worker.go
  server/channels/jobs/import_delete/worker.go
  server/channels/jobs/import_process/worker.go
  server/channels/jobs/jobs.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/last_accessible_file/worker.go
  server/channels/jobs/last_accessible_post/worker.go
  server/channels/jobs/migrations/scheduler.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/notify_admin/worker.go
  server/channels/jobs/plugins/worker.go
  server/channels/jobs/post_persistent_notifications/worker.go
  server/channels/jobs/product_notices/worker.go
  server/channels/jobs/resend_invitation_email/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/sqlstore/job_store.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/extract_e2e_test.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
  server/public/model/job.go
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#24838 Bump to latest mmjstool
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#24807 [MM-48233] Migrate /support/saml_commands.js file to TypeScript
  e2e-tests/cypress/tests/support/common_login_commands.d.ts
  e2e-tests/cypress/tests/support/saml_commands.js
  e2e-tests/cypress/tests/support/saml_commands.ts
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24860 Displayed error message for already used channel name
  server/channels/app/channel.go
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
  webapp/channels/src/components/new_channel_modal/new_channel_modal.scss
  webapp/channels/src/components/new_channel_modal/new_channel_modal.tsx
  webapp/channels/src/components/widgets/inputs/url_input/url_input.scss
Labels: release-note-none

#24852 [MM-54841] Convert LocalizedInput of 'oauth_to_email.tsx' to regular input component
  webapp/channels/src/components/claim/components/oauth_to_email.tsx
Labels: 4: Reviews Complete, Hacktoberfest, EETests, release-note-none, Contributor

#24663 Migrating some files from javascript to typescript
  webapp/channels/package.json
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/actions/integration_actions.test.ts
  webapp/channels/src/actions/integration_actions.tsx
  webapp/channels/src/actions/telemetry_actions.jsx
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/client/web_websocket_client.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/app.tsx
  webapp/channels/src/components/integrations/commands_container/commands_container.tsx
  webapp/channels/src/components/integrations/installed_incoming_webhooks/index.ts
  webapp/channels/src/components/invitation_modal/invitation_modal.test.tsx
  webapp/channels/src/components/invitation_modal/invite_view.test.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/components/overlay_trigger.tsx
  webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/suggestion/channel_mention_provider.tsx
  webapp/channels/src/components/suggestion/emoticon_provider.tsx
  webapp/channels/src/components/suggestion/search_channel_provider.tsx
  webapp/channels/src/components/suggestion/search_channel_with_permissions_provider.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/entry.tsx
  webapp/channels/src/i18n/i18n.jsx
  webapp/channels/src/plugins/index.js
  webapp/channels/src/plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  webapp/channels/src/plugins/pluggable/__snapshots__/pluggable.test.tsx.snap
  webapp/channels/src/plugins/pluggable/pluggable.test.tsx
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
  webapp/channels/src/plugins/test/__snapshots__/post_type.test.tsx.snap
  webapp/channels/src/plugins/test/main_menu_action.test.tsx
  webapp/channels/src/plugins/test/post_type.test.tsx
  webapp/channels/src/stores/local_storage_store.ts
  webapp/channels/src/stores/redux_store.tsx
  webapp/channels/src/tests/helpers/admin_console_plugin_index_sample_pluings.ts
  webapp/channels/src/tests/helpers/localstorage.tsx
  webapp/channels/src/tests/helpers/user_agent_mocks.ts
  webapp/channels/src/utils/__snapshots__/message_html_to_component.test.tsx.snap
  webapp/channels/src/utils/markdown/index.ts
  webapp/channels/src/utils/message_html_to_component.test.tsx
  webapp/channels/src/utils/message_html_to_component.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/utils.test.tsx
  webapp/channels/src/utils/utils.tsx
  webapp/channels/webpack.config.js
  webapp/package-lock.json
Labels: 4: Reviews Complete, 3: QA Review, Setup Cloud Test Server, release-note-none

#24788 [MM-54798] Convert `./components/widgets/separator/basic-separator.tsx` to function component
  webapp/channels/src/components/widgets/separator/basic-separator.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24815 MM-54139 - Updating disabled state menu color
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#24814 MM-54768 - Updating user popover UI
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/group_member_list.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
  webapp/channels/src/sass/components/_buttons.scss
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#24786 [MM-54795] Convert `./components/widgets/icons/fa_previous_icon.tsx` to function component
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_users.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  webapp/channels/src/components/widgets/icons/fa_previous_icon.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24658 Migrating the admin_definition.jsx file to typescript
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_definition.test.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar_category.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/enable_plugin_setting.ts
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/sass/routes/_admin-console.scss
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/selectors/admin_console.test.jsx
  webapp/channels/src/utils/admin_console_index.test.tsx
  webapp/channels/src/utils/admin_console_index.tsx
  webapp/channels/src/utils/admin_console_plugin_index.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#24865 Update subpackage versions for 9.2
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/platform/client/package.json
  webapp/platform/components/package.json
  webapp/platform/types/package.json
Labels: 4: Reviews Complete, release-note

#24869 Revert "MM-54855 Migrating the admin_definition.jsx file to typescript"
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/admin_definition.test.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar_category.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/enable_plugin_setting.ts
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/sass/routes/_admin-console.scss
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/selectors/admin_console.test.jsx
  webapp/channels/src/utils/admin_console_index.test.tsx
  webapp/channels/src/utils/admin_console_index.tsx
  webapp/channels/src/utils/admin_console_plugin_index.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note

#24628 MM-53513 Update styles of slack attachment buttons
  webapp/channels/src/components/post_view/message_attachments/action_button/action_button.test.tsx
  webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
  webapp/channels/src/sass/layout/_webhooks.scss
Labels: 4: Reviews Complete, release-note-none

#24842 Set env vars properly when running mmctl tests
  .github/workflows/mmctl-test-template.yml
Labels: 4: Reviews Complete, release-note-none

#24839 [MM-54833] Convert LocalizedInput of 'password_reset_form.tsx' to regular input component
  webapp/channels/src/components/password_reset_form/__snapshots__/password_reset_form.test.tsx.snap
  webapp/channels/src/components/password_reset_form/password_reset_form.tsx
Labels: 4: Reviews Complete, Hacktoberfest, EETests, release-note-none, Contributor

#24837 [MM-54839] Convert LocalizedInput of 'email_to_ldap.tsx' to regular input component
  webapp/channels/src/components/claim/components/email_to_ldap.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24827 Goodbye, GraphQL
  server/Makefile
  server/channels/api4/api.go
  server/channels/api4/apitestlib.go
  server/channels/api4/graphql.go
  server/channels/api4/graphql_client.go
  server/channels/api4/graphql_test.go
  server/channels/api4/resolver.go
  server/channels/api4/resolver_channel.go
  server/channels/api4/resolver_channel_member.go
  server/channels/api4/resolver_channel_member_test.go
  server/channels/api4/resolver_channel_test.go
  server/channels/api4/resolver_sidebar_categories_test.go
  server/channels/api4/resolver_team.go
  server/channels/api4/resolver_team_member.go
  server/channels/api4/resolver_team_member_test.go
  server/channels/api4/resolver_test.go
  server/channels/api4/resolver_user.go
  server/channels/api4/resolver_user_test.go
  server/channels/api4/schema.graphqls
  server/channels/app/app_iface.go
  server/channels/app/channel.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/layer_generators/main.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/channel_store_categories.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/context.go
  server/channels/web/handlers.go
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
  server/public/model/channel.go
  server/public/model/channel_member.go
  server/public/model/channel_sidebar.go
  server/public/model/custom_status.go
  server/public/model/feature_flags.go
  server/public/model/status.go
  server/public/model/team.go
  server/public/model/team_member.go
  server/public/model/user.go
  server/public/model/utils.go
  server/public/pluginapi/experimental/oauther/mock_oauther/mock_oauther.go
  server/public/shared/mlog/graphql.go
Labels: 4: Reviews Complete, release-note-none

#24859 [MM-54850] Use request-specific logger in channels/app/admin_advisor.go
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/integration_action.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, release-note-none

#24293 [MM-45309] Replace github.com/mattermost/gziphandler with github.com/klauspost/compress/gzhttp
  server/channels/api4/handlers.go
  server/channels/api4/post.go
  server/channels/web/handlers.go
  server/channels/web/static.go
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note

#24874 [MM-54831] Convert LocalizedInput of 'rename_channel_modal.tsx' to regular input component
  webapp/channels/src/components/rename_channel_modal/__snapshots__/rename_channel_modal.test.tsx.snap
  webapp/channels/src/components/rename_channel_modal/rename_channel_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24850 [MM-54879] Goodbye, GraphQL -- Regards Webapp
  e2e-tests/playwright/support/server/default_config.ts
  webapp/channels/src/actions/channel_actions.test.ts
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/actions/channel_queries.ts
  webapp/channels/src/actions/global_actions.test.ts
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/actions/telemetry_actions.jsx
  webapp/channels/src/actions/views/root.test.ts
  webapp/channels/src/actions/views/root.ts
  webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/preferences.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/teams.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users_queries.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/platform/client/src/client4.test.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#24046 [MM-53428] Delete empty drafts on upsert
  server/channels/app/draft.go
  server/channels/app/migrations.go
  server/channels/app/server.go
  server/channels/jobs/batch_migration_worker.go
  server/channels/jobs/batch_migration_worker_test.go
  server/channels/jobs/delete_empty_drafts_migration/delete_empty_drafts_migration.go
  server/channels/jobs/delete_empty_drafts_migration/delete_empty_drafts_migration_test.go
  server/channels/jobs/helper_test.go
  server/channels/jobs/main_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/draft_store.go
  server/channels/store/store.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/mocks/DraftStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/testlib/store.go
  server/go.mod
  server/go.sum
  server/public/model/draft.go
  server/public/model/job.go
  server/public/model/migration.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24901 Revert "Update prepackaged Jira plugin 4.0.0 (#24609)"
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24529 MM-47094 : Migrate "components/integrations/abstract_oauth_app.jsx" and tests to Typescript
  webapp/channels/src/components/integrations/__snapshots__/abstract_oauth_app.test.tsx.snap
  webapp/channels/src/components/integrations/abstract_oauth_app.test.tsx
  webapp/channels/src/components/integrations/abstract_oauth_app.tsx
  webapp/channels/src/components/integrations/add_oauth_app/__snapshots__/add_oauth_app.test.tsx.snap
  webapp/channels/src/components/integrations/add_oauth_app/add_oauth_app.tsx
  webapp/channels/src/components/integrations/edit_oauth_app/edit_oauth_app.tsx
Labels: 4: Reviews Complete, EETests, release-note-none, Contributor

#23631 MM-53023: Add origin device to ObserveAPIEndpointDuration
  server/channels/web/handlers.go
  server/channels/web/handlers_test.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
Labels: 4: Reviews Complete, release-note

#24893 update prepackage boards to v7.8.9
  Makefile
Labels: release-note

#24914 Update minor version to 9.2.0
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24915 Update version to 9.1.1
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24909 Automated cherry pick of #24619
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24908 Automated cherry pick of #24619
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24899 Move mmctl CI tests to free tier
  .github/workflows/mmctl-test-template.yml
Labels: 2: Dev Review, release-note-none

#24630 MM-53855 - Handle serverError undefined or null
  webapp/channels/src/components/admin_console/system_roles/system_role/add_users_to_role_modal/__snapshots__/add_users_to_role_modal.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.test.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/add_users_to_role_modal/index.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
Labels: 4: Reviews Complete, release-note-none

#24727 Remove professional plus from in-product pricing
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#24655 [MM-54639] Help menu should open correctly aligned
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note, Contributor

#24349 [MM-52710] Adding a separator to the channel search string
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
Labels: 4: Reviews Complete, release-note-none

#24327 Performance metrics: Differentiate requests that are from page load
  server/channels/web/handlers.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  webapp/channels/src/actions/telemetry_actions.jsx
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
Labels: release-note

#24929 Automated cherry pick of #24195
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/channels/app/post.go
  server/channels/web/context.go
  server/public/model/post.go
  server/public/model/post_test.go
  server/public/model/session.go
  server/public/model/session_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24647 MM-52642 CLD-6352 MM-54007 Prepare setup for Playwright pipeline
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/.e2erc_setup
  e2e-tests/.ci/.env.server.cloud
  e2e-tests/.ci/.gitignore
  e2e-tests/.ci/.shellcheckrc
  e2e-tests/.ci/dashboard.entrypoint.sh
  e2e-tests/.ci/dashboard.start.sh
  e2e-tests/.ci/dashboard.stop.sh
  e2e-tests/.ci/docker-compose.cypress.yml
  e2e-tests/.ci/docker-compose.playwright.yml
  e2e-tests/.ci/docker_compose_generator.sh
  e2e-tests/.ci/server.cloud_customer_create.sh
  e2e-tests/.ci/server.cloud_customer_delete.sh
  e2e-tests/.ci/server.override.yml
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.run_playwright.sh
  e2e-tests/.ci/server.start.sh
  e2e-tests/.ci/server.stop.sh
  e2e-tests/.gitignore
  e2e-tests/Makefile
  e2e-tests/README.md
  e2e-tests/playwright/README.md
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/playwright.config.ts
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/support/ui/components/channels/center_view.ts
  e2e-tests/playwright/support/ui/components/channels/header_mobile.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/visual/index.ts
  e2e-tests/playwright/support/visual/percy.ts
  e2e-tests/playwright/test.config.ts
  e2e-tests/playwright/tests/accessibility/common/login.spec.ts
  e2e-tests/playwright/tests/accessibility/common/reset_password.spec.ts
  e2e-tests/playwright/tests/accessibility/common/signup_user_complete.spec.ts
  e2e-tests/playwright/tests/functional/channels/search/find_channels.spec.ts
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  e2e-tests/playwright/tsconfig.json
  e2e-tests/playwright/types.ts
  webapp/channels/src/components/app_bar/app_bar_plugin_component.tsx
Labels: 4: Reviews Complete, release-note-none

#24919 Automated cherry pick of #24554
  server/channels/utils/api.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24872 Updated error message for invalid attachments
  webapp/channels/src/components/file_upload/file_upload.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/i18n/en_AU.json
Labels: 4: Reviews Complete, release-note-none

#24918 Automated cherry pick of #24554
  server/channels/utils/api.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24917 Automated cherry pick of #24554
  server/channels/utils/api.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24878 [MM-54766] Fix RHS Search/Info screens width for Mobile Web View
  webapp/channels/src/sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24862 Mm 24857 specific logger in post go
  server/channels/api4/post.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24889 MM-53481 Fix textbox broken Help link
  webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
  webapp/channels/src/components/textbox/index.ts
  webapp/channels/src/components/textbox/textbox_links.tsx
  webapp/channels/src/components/textbox/textbox_links/index.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#24714 Fixes [#24664] Improve System Message Formatting for Channel Header Edits
  webapp/channels/src/components/post_markdown/system_message_helpers.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#24739 [MM-54138] Remove code involving getRedirectLocation and state.entities.posts.expandedURLs
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/posts.ts
Labels: 4: Reviews Complete, release-note-none

#24090 Add "thanks" and "thank you" to "pray" emoji
  server/public/model/emoji_data.go
  webapp/channels/build/emoji/additional_shortnames.json
  webapp/channels/build/emoji/make_emojis.mjs
  webapp/channels/src/selectors/emojis.test.js
  webapp/channels/src/utils/emoji.json
  webapp/channels/src/utils/emoji.ts
Labels: 4: Reviews Complete, release-note

#24946 migrating database_settings.test.jsx to typescript
  webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/database_settings.test.tsx
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#24945 MM-54489 restrict mobile oauth/saml redirect to native app schemes (manual cherry-pick #24554)
  utils/api.go
  web/oauth_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24950 Add limiting ability to log fields (#24251)
  server/channels/app/platform/log.go
  server/go.mod
  server/go.sum
  server/platform/services/imageproxy/local.go
  server/public/model/config.go
Labels: release-note-none

#24951 Add limiting ability to log fields (#24251)
  server/channels/app/platform/log.go
  server/go.mod
  server/go.sum
  server/platform/services/imageproxy/local.go
  server/public/model/config.go
Labels: release-note-none

#24952 Add limiting ability to log fields (#24251)
  app/platform/log.go
  go.mod
  go.sum
  model/config.go
  services/imageproxy/local.go
Labels: release-note-none

#24925 Automated cherry pick of #24251
  server/channels/app/platform/log.go
  server/go.mod
  server/go.sum
  server/platform/services/imageproxy/local.go
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24890 [CLD-6373] Fix non-admin users requesting self hosted expansion status on load
  webapp/channels/src/components/common/hooks/useCanSelfHostedExpand.ts
Labels: 4: Reviews Complete, release-note-none

#24793 migrate channel header dropdown comp to functional comp
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/channel_header_dropdown/channel_header_dropdown.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24792 convert EmojiIcon component from class based to function based component
  webapp/channels/src/components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  webapp/channels/src/components/widgets/icons/emoji_icon.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24922 Automated cherry pick of #24495
  server/channels/app/authorization.go
  server/channels/app/post_metadata_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24923 Automated cherry pick of #24495
  server/channels/app/authorization.go
  server/channels/app/post_metadata_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24924 Automated cherry pick of #24495
  server/channels/app/authorization.go
  server/channels/app/post_metadata_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24868 [CLD-6077] Changes to Country Selectors throughout Webapp
  webapp/channels/src/components/admin_console/billing/company_info_edit.tsx
  webapp/channels/src/components/payment_form/address_form.tsx
  webapp/channels/src/components/payment_form/country_selector.tsx
  webapp/channels/src/components/payment_form/payment_form.scss
  webapp/channels/src/components/payment_form/payment_form.tsx
  webapp/channels/src/components/payment_form/state_selector.tsx
  webapp/channels/src/components/self_hosted_purchases/address.tsx
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/start_trial_form_modal/index.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#24809 GH-24784 Convert ./components/common/site_name_and_description.tsx to Function Component
  webapp/channels/src/components/common/site_name_and_description.tsx
  webapp/channels/src/components/create_team/__snapshots__/create_team.test.tsx.snap
  webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note, Contributor

#24954 Cherry pick 24495
  app/authorization.go
  app/post_metadata_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#24967 Automated cherry pick of #24897
  server/channels/app/import.go
  server/channels/store/sqlstore/context_test.go
  server/public/shared/request/context.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24828 MM-54731 Fixed a bug preventing users be added from system console
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#24938 [MM-23408] Migrate "components/setting_item_max.test.jsx" to Typescript
  webapp/channels/src/components/__snapshots__/setting_item_max.test.tsx.snap
  webapp/channels/src/components/setting_item_max.test.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24858 [MM-54838] Convert LocalizedInput of 'system_users.tsx' to regular input component
  webapp/channels/src/components/admin_console/system_users/system_users.test.tsx
  webapp/channels/src/components/admin_console/system_users/system_users.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24785 [MM-54794] Convert `./components/widgets/icons/fa_next_icon.tsx` to function component
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_users.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  webapp/channels/src/components/widgets/icons/fa_next_icon.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24931 [MM-54834] Convert LocalizedInput of `mfa/setup/setup.tsx` to regular input component
  webapp/channels/src/components/mfa/setup/setup.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24916 [MM-54858] Can't set 0 to a dialog element with subtype=number in interactive dialog
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.test.tsx
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
  webapp/channels/src/packages/mattermost-redux/src/utils/integration_utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/integration_utils.ts
Labels: 4: Reviews Complete, Hacktoberfest, QA Deferred, release-note, Contributor

#24962 Cherry pick #24494
  webapp/channels/src/components/suggestion/suggestion_list.jsx
Labels: release-note-none

#24803 #24773 Converted ./components/emoji_picker/components/emoji_picker_header.tsx to Function Component
  webapp/channels/src/components/emoji_picker/components/emoji_picker_header.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note, Contributor

#24886 [MM-54842] Convert LocalizedInput of 'abstract_command.tsx' to regular input component
  webapp/channels/src/components/integrations/__snapshots__/abstract_command.test.tsx.snap
  webapp/channels/src/components/integrations/abstract_command.test.tsx
  webapp/channels/src/components/integrations/abstract_command.tsx
  webapp/channels/src/components/integrations/add_command/__snapshots__/add_command.test.tsx.snap
  webapp/channels/src/components/integrations/edit_command/__snapshots__/edit_command.test.tsx.snap
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#24074 Adding Vietnamese as a new language (beta)
  server/i18n/vi.json
  server/public/shared/i18n/i18n.go
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/i18n/i18n.jsx
Labels: Setup Cloud Test Server, release-note-none, Contributor

#24965 Remove support for unused product interfaces
  server/channels/app/app_iface.go
  server/channels/app/channels.go
  server/channels/app/command.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_commands.go
  server/channels/app/plugin_commands_test.go
  server/channels/app/server.go
  server/channels/product/api.go
  server/channels/product/hooks.go
  server/channels/product/service.go
  server/platform/services/telemetry/mocks/ServerIface.go
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
Labels: Setup Cloud Test Server, QA/Tests Not Required, release-note-none

#24978 Automated cherry pick of #24828
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24969 Revert "Add "thanks" and "thank you" to "pray" emoji (#24090)"
  server/public/model/emoji_data.go
  webapp/channels/build/emoji/additional_shortnames.json
  webapp/channels/build/emoji/make_emojis.mjs
  webapp/channels/src/selectors/emojis.test.js
  webapp/channels/src/utils/emoji.json
  webapp/channels/src/utils/emoji.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#24651 MM-54640 Add API to get multiple emojis by name at once
  server/channels/api4/emoji.go
  server/channels/api4/emoji_test.go
  server/channels/testlib/helper.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/packages/mattermost-redux/src/actions/emojis.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/emojis.ts
  webapp/platform/client/src/client4.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#24980 Automated cherry pick of #24969
  server/public/model/emoji_data.go
  webapp/channels/build/emoji/additional_shortnames.json
  webapp/channels/build/emoji/make_emojis.mjs
  webapp/channels/src/selectors/emojis.test.js
  webapp/channels/src/utils/emoji.json
  webapp/channels/src/utils/emoji.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24983 Add documentation for get emojis by names API
  api/v4/source/emoji.yaml
Labels: 4: Reviews Complete, release-note-none

#24816 [MM-54474] Fixed behaviour of markdown code button
  webapp/channels/src/utils/markdown/apply_markdown.test.tsx
  webapp/channels/src/utils/markdown/apply_markdown.ts
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note, Contributor

#24801 Convert ./components/post_view/scroll_to_bottom_arrows.tsx to functional component
  webapp/channels/src/components/post_view/scroll_to_bottom_arrows.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note, Contributor

#24810 Convert ShieldOutlineIcon to function Component
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/widgets/icons/shield_outline_icon.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24977 MM-54777 - Updating invite modal guest button
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_channel-invite-modal.scss
  webapp/channels/src/sass/responsive/_tablet.scss
Labels: CherryPick/Approved, release-note-none

#24995 Automated cherry pick of #24977
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_channel-invite-modal.scss
  webapp/channels/src/sass/responsive/_tablet.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24973 [MM 24831] Convert LocalizedInput of 'email_to_oauth.tsx' to regular input component
  webapp/channels/src/components/claim/components/email_to_oauth.tsx
Labels: Hacktoberfest, 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#25001 Fix vi merge issues
  server/i18n/he.json
  server/i18n/hr.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/vi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/kk.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#24654 Fixes #24653 - Use getFileDownloadUrl for file_search_result_item
  webapp/channels/src/components/file_search_results/file_search_result_item.tsx
Labels: 4: Reviews Complete, Hacktoberfest, kind/bug, release-note, Contributor, QA-wanted

#24932 MM-54201 Move ExplicitMentions to its own file and rename it
  server/channels/app/mention_results.go
  server/channels/app/mention_results_test.go
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  server/channels/app/post.go
  server/channels/app/post_persistent_notification.go
Labels: 4: Reviews Complete, release-note-none

#25005 Translations update from Mattermost Weblate
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sr.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
Labels: Hacktoberfest, release-note-none, Do Not Merge/Mattermod

#24794 migrate notify counts component from class based to function based comp
  webapp/channels/src/components/notify_counts/notify_counts.test.tsx
  webapp/channels/src/components/notify_counts/notify_counts.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24747 refactor: convert DataGridHeader into function component
  webapp/channels/src/components/admin_console/data_grid/data_grid_header.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, kind/feature, release-note-none, Contributor

#24795 MM-24743 Migrate DataRowGrid to functional component
  webapp/channels/src/components/admin_console/data_grid/__snapshots__/data_grid.test.tsx.snap
  webapp/channels/src/components/admin_console/data_grid/data_grid_row.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24887 [MM-54793] Convert ./components/widgets/separator/notification-separator.tsx to Function Component
  webapp/channels/src/components/widgets/separator/notification-separator.tsx
Labels: 4: Reviews Complete, 2: Dev Review, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24797 Migrate RemoveFileSetting component from class based to function based component
  webapp/channels/src/components/admin_console/remove_file_setting.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24796 migrate DropdownSetting component from class based to function based component
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/push_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/dropdown_setting.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, release-note-none, Contributor

#24622 [MM-53904] Fix MM-53904
  webapp/channels/src/components/channel_layout/center_channel/center_channel.tsx
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/utils/path.ts
  webapp/channels/src/utils/utils.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#24988 [MM-54837] Convert LocalizedInput of 'permission_team_scheme_settings.tsx' to regular input component
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor
