Repository mattermost/mattermost, pull requests merged in 2023-03, with the labels that each got.

#22049 MM-49547: Handle Top DM case for deleted second user
  app/post_test.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 3: QA Review, Lifecycle/1:stale, release-note

#22403 update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390)
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22404 update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390)
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22406 update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390)
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22408 update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390)
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22411 Update version to 7.1.7
  model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22412 Update version to 7.7.3
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22413 Update version to 7.8.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22392 Migrate to CI pipeline to GitHub actions
  .circleci/config.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: 2: Dev Review, release-note-none

#22416 add sentry org to the env vars
  .github/workflows/ci.yml
Labels: 2: Dev Review, release-note-none

#22418 Use getsentry/action-release@v1 for sentry release
  .github/workflows/ci.yml
Labels: 2: Dev Review, release-note-none

#22421 MM-51019 - Add a Feature Flag for In-Product Expansion
  model/config.go
  services/telemetry/telemetry.go
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#22426 [MM-51054] Allow enabling/disabling plugins through env override
  config/common_test.go
  config/environment.go
Labels: 4: Reviews Complete, release-note

#22428 Cherry-pick of MM-51054 to `cloud`
  config/common_test.go
  config/environment.go
Labels: 4: Reviews Complete, release-note-none

#22427 [MM-50996] Set WorkTemplate FF to true by default
  model/feature_flags.go
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, CherryPick/Approved, release-note-none

#22431 Manual cherry pick of MM-MM-50996
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22425 Manual Cherry pick MM 50534 to release 7.9
  api4/cloud.go
  api4/cloud_test.go
  api4/license.go
  app/email/email.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/server.go
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
  model/cloud.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22430 Revert "Cherry-pick of MM-51054 to `cloud`"
  config/common_test.go
  config/environment.go
Labels: release-note-none

#22437 Revert "Revert "Revert "Set BoardsProduct FF to on by default" (#22177)""
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 4: Reviews Complete, 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22439 Revert "[MM-51054] Allow enabling/disabling plugins through env override"
  config/common_test.go
  config/environment.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22442 Revert "[MM-50996] Set WorkTemplate FF to true by default"
  model/feature_flags.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22443 Revert "Manual cherry pick of MM-MM-50996"
  model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22444 Revert "Revert "Revert "Set BoardsProduct FF to on by default" (#22177)" (#22213)" (#22437)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22423 Prepackage boards v7.9.0
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#22447 prepackage boards v7.9.0 (#22423)
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note

#22348 MM-48627: Fix flaky testGetUptoNSizeFileTime
  store/localcachelayer/file_info_layer_test.go
  store/sqlstore/file_info_store_test.go
  store/storetest/file_info_store.go
Labels: 2: Dev Review, release-note-none

#22358 MM-50393: Revamp email batching performance
  app/email/email_batching.go
  app/email/email_batching_test.go
  app/email/helper_test.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
  app/server.go
  app/team_test.go
Labels: 2: Dev Review, release-note-none

#22452 Cherry-picking translations
  i18n/de.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#22202 configure public key and related license variables at build time
  Makefile
  api4/license_test.go
  app/license.go
  app/platform/license.go
  build/release.mk
  model/config.go
  model/license_key.go
  model/license_key_test_env.go
  utils/license-public-key-test.txt
  utils/license-public-key.txt
  utils/license.go
  utils/license_public_key.go
  utils/license_public_key_test_env.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#22458 remove unsused/unnecessary gitlab ci steps
  .gitlab-ci.yml
  .gitlab-ci/scripts/test-schema/mysql.sh
  .gitlab-ci/scripts/test-schema/postgres.sh
  .gitlab-ci/scripts/test/mysql.sh
  .gitlab-ci/scripts/test/postgres.sh
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#22459 remove unsused/unnecessary gitlab ci steps (#22458)
  .gitlab-ci.yml
  .gitlab-ci/scripts/test-schema/mysql.sh
  .gitlab-ci/scripts/test-schema/postgres.sh
  .gitlab-ci/scripts/test/mysql.sh
  .gitlab-ci/scripts/test/postgres.sh
Labels: Changelog/Not Needed, Docs/Not Needed

#22469 MM-50566 - Calls 0.14.0 cherry pick
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22462 update prepackage boards to 7.9.1
  Makefile
Labels: CherryPick/Approved, release-note

#22471 update prepackage boards to 7.9.1 (#22462)
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22472 update prepackage boards to 7.9.1 (#22462)
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22478 Revert "Adding the debug bar logic in the server (#22410)"
  api4/api.go
  api4/debugbar.go
  app/app_iface.go
  app/debugbar.go
  app/email/email.go
  app/email/service.go
  app/opentracing/opentracing_layer.go
  app/platform/config.go
  app/platform/debugbar/debugbar.go
  app/platform/debugbar/logger.go
  app/platform/log.go
  app/platform/service.go
  app/platform/service_test.go
  app/plugin_api_tests/test_db_driver/main.go
  app/server.go
  cmd/mattermost/commands/db.go
  i18n/en.json
  model/debugbar.go
  services/searchengine/bleveengine/bleve_test.go
  shared/mlog/levels.go
  shared/mlog/mlog.go
  store/debugbarlayer/debugbarlayer.go
  store/layer_generators/debugbar_layer.go.tmpl
  store/layer_generators/main.go
  store/localcachelayer/layer_test.go
  store/searchlayer/layer_test.go
  store/sqlstore/sqlx_wrapper.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
  store/store.go
  store/storetest/mocks/Store.go
  store/storetest/store.go
  testlib/helper.go
  web/handlers.go
Labels: QA Deferred, release-note

#22453 MM-47489 Fix all occurrences of checking for RemoteClusterServiceLicense
  app/server.go
  model/license.go
  web/context.go
  web/handlers.go
Labels: release-note

#22465 Optimize precomputing of websocket event
  model/websocket_message.go
  model/websocket_message_test.go
Labels: 2: Dev Review, release-note

#22480 Updated Local Mode settings for cloud
  model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA Deferred, release-note-none, Setup Cloud + CWS Test Server

#22498 Automated cherry pick of #22480
  model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22500 check permissions to channel before patching via api(4620)
  server/boards/app/boards.go
  server/boards/app/boards_test.go
Labels: release-note-none

#22499 Added data migration to de-duplicate data from category_boards table(…
  server/boards/services/store/sqlstore/data_migrations.go
  server/boards/services/store/sqlstore/migrate.go
  server/boards/services/store/storetests/system.go
Labels: release-note-none

#22502 Prepackage boards v7.9.2
  Makefile
Labels: release-note

#22509 update prepackage boards to v7.9.2
  Makefile
Labels: release-note

#22510 Update most web app GitHub Actions for the monorepo
  .github/codeql/codeql-config.yml
  .github/workflows/channels-ci.yml
  .github/workflows/codeql-analysis.yml
  .nvmrc
  webapp/boards/.nvmrc
  webapp/channels/.github/codeql/codeql-config.yml
  webapp/channels/.github/workflows/ci.yml
  webapp/channels/.github/workflows/codeql-analysis.yml
  webapp/channels/.github/workflows/scorecards-analysis.yml
  webapp/channels/Makefile
  webapp/channels/jest.config.js
  webapp/channels/src/components/generic_modal.tsx
  webapp/channels/src/components/tours/channels_tour_tip.tsx
  webapp/channels/src/plugins/products.ts
  webapp/channels/src/types/products.d.ts
Labels: 4: Reviews Complete, release-note-none

#22438 [MM-49993] Return error if there is no telemetry ID
  app/server.go
  services/telemetry/telemetry.go
  services/telemetry/telemetry_test.go
Labels: 4: Reviews Complete, release-note-action-required

#22511 Re-add dist target for web app
  .github/workflows/channels-ci.yml
  server/build/release.mk
  webapp/Makefile
  webapp/channels/Makefile
Labels: 2: Dev Review, release-note-none

#22310 [MM-50219] OAuth 2.0
  app/oauth.go
  app/oauth_test.go
  db/migrations/migrations.list
  db/migrations/mysql/000105_remove_tokens.down.sql
  db/migrations/mysql/000105_remove_tokens.up.sql
  db/migrations/postgres/000105_remove_tokens.down.sql
  db/migrations/postgres/000105_remove_tokens.up.sql
  i18n/en.json
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/oauth_store.go
  store/store.go
  store/storetest/mocks/OAuthStore.go
  store/timerlayer/timerlayer.go
Labels: 3: QA Review, release-note-none

#22515 Automated cherry pick of #22453
  app/server.go
  model/license.go
  web/context.go
  web/handlers.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22518 Actually build the web app when the server builds
  .github/workflows/ci.yml
  server/build/release.mk
Labels: 4: Reviews Complete, release-note-none

#22522 Update version to 7.9.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22523 Update minor version to 7.10.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22481 MM-51321 Refactor audit log application.
  api4/bot.go
  api4/channel.go
  api4/channel_local.go
  api4/command.go
  api4/command_local.go
  api4/compliance.go
  api4/config.go
  api4/data_retention.go
  api4/emoji.go
  api4/export.go
  api4/file.go
  api4/group.go
  api4/job.go
  api4/ldap.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  api4/webhook.go
  api4/webhook_local.go
  app/session.go
  audit/record.go
  model/bot.go
  model/channel.go
  model/file_info.go
  model/group.go
  model/group_syncable.go
  model/guest_invite.go
  model/member_invite.go
  model/onboarding.go
  model/remote_cluster.go
  model/role.go
  model/scheme.go
  model/session.go
  model/switch_request.go
  model/team.go
  model/upload_session.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#22533 [MM-49486]: Option to exclude file count in channel stats
  api4/channel.go
  api4/channel_test.go
  model/client4.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#22537 Automated cherry pick of #22481
  api4/bot.go
  api4/channel.go
  api4/channel_local.go
  api4/command.go
  api4/command_local.go
  api4/compliance.go
  api4/config.go
  api4/data_retention.go
  api4/emoji.go
  api4/export.go
  api4/file.go
  api4/group.go
  api4/job.go
  api4/ldap.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  api4/webhook.go
  api4/webhook_local.go
  app/session.go
  audit/record.go
  model/bot.go
  model/channel.go
  model/file_info.go
  model/group.go
  model/group_syncable.go
  model/guest_invite.go
  model/member_invite.go
  model/onboarding.go
  model/remote_cluster.go
  model/role.go
  model/scheme.go
  model/session.go
  model/switch_request.go
  model/team.go
  model/upload_session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22538 Automated cherry pick of #22481
  api4/bot.go
  api4/channel.go
  api4/channel_local.go
  api4/command.go
  api4/command_local.go
  api4/compliance.go
  api4/config.go
  api4/data_retention.go
  api4/emoji.go
  api4/export.go
  api4/file.go
  api4/group.go
  api4/job.go
  api4/ldap.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  api4/webhook.go
  api4/webhook_local.go
  app/session.go
  audit/record.go
  model/bot.go
  model/channel.go
  model/file_info.go
  model/group.go
  model/group_syncable.go
  model/guest_invite.go
  model/member_invite.go
  model/onboarding.go
  model/remote_cluster.go
  model/role.go
  model/scheme.go
  model/session.go
  model/switch_request.go
  model/team.go
  model/upload_session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22541 Cherry pick of #22481
  api4/bot.go
  api4/channel.go
  api4/channel_local.go
  api4/command.go
  api4/command_local.go
  api4/compliance.go
  api4/config.go
  api4/data_retention.go
  api4/emoji.go
  api4/export.go
  api4/file.go
  api4/group.go
  api4/job.go
  api4/ldap.go
  api4/license.go
  api4/license_local.go
  api4/oauth.go
  api4/plugin.go
  api4/post.go
  api4/remote_cluster.go
  api4/role.go
  api4/saml.go
  api4/scheme.go
  api4/system.go
  api4/team.go
  api4/team_local.go
  api4/upload.go
  api4/user.go
  api4/user_local.go
  api4/user_test.go
  api4/webhook.go
  api4/webhook_local.go
  app/session.go
  audit/record.go
  model/bot.go
  model/channel.go
  model/file_info.go
  model/group.go
  model/group_syncable.go
  model/guest_invite.go
  model/member_invite.go
  model/onboarding.go
  model/post.go
  model/remote_cluster.go
  model/role.go
  model/scheme.go
  model/session.go
  model/switch_request.go
  model/team.go
  model/upload_session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22540 [MM-51466] Fixing monorepo websockets for boards
  server/boards/ws/plugin_adapter.go
Labels: release-note-none

#22554 Update version to 7.1.8
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22555 Update version to 7.7.4
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22581 E2E fix for mono-repo
  e2e/cypress/tests/integration/playbooks/channels/broadcast_spec.js
  e2e/cypress/tests/integration/playbooks/channels/rhs/checklist_spec.js
  e2e/cypress/tests/integration/playbooks/channels/rhs/status_update_spec.js
  e2e/cypress/tests/integration/playbooks/channels/slash_command/commands_spec.js
  e2e/cypress/tests/integration/playbooks/channels/slash_command/info_spec.js
  e2e/cypress/tests/integration/playbooks/channels/slash_command/owner_spec.js
  e2e/cypress/tests/integration/playbooks/channels/slash_command/test_spec.js
  e2e/cypress/tests/integration/playbooks/channels/slash_command/todo_spec.js
  e2e/cypress/tests/integration/playbooks/digest_spec.js
  e2e/cypress/tests/integration/playbooks/lhs_spec.js
  e2e/cypress/tests/integration/playbooks/playbooks/edit_spec.js
  e2e/cypress/tests/integration/playbooks/playbooks/overview_spec.js
  e2e/cypress/tests/integration/playbooks/runs/rdp_main_header_spec.js
  e2e/cypress/tests/integration/playbooks/runs/rdp_main_statusupdate_spec.js
  e2e/cypress/tests/integration/playbooks/runs/taskinbox_spec.js
  e2e/cypress/tests/support/api/playbooks.js
  e2e/cypress/tests/support/index.js
  e2e/cypress/tests/support/ui/playbooks.js
Labels: 2: Dev Review, release-note-none

#22580 Add blocklist for monorepo integrated plugins
  plugin/environment.go
  plugin/environment_test.go
  server/channels/app/channels.go
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_install_test.go
Labels: 2: Dev Review, release-note-none

#22601 MM-51486: Implementing UTS 46 to check for preview blocklist
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/app/team.go
Labels: 2: Dev Review, Do Not Merge, release-note-none

#22576 Run linters for all web app packages as part of Web App CI linting
  .github/workflows/channels-ci.yml
  webapp/boards/package.json
  webapp/channels/package.json
  webapp/platform/client/package.json
  webapp/platform/components/package.json
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22603 MM-45956: Optimize FileInfo stats query
  model/file_info.go
  server/channels/api4/file_test.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/app/import_functions.go
  server/channels/app/post.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000106_fileinfo_channelid.down.sql
  server/channels/db/migrations/mysql/000106_fileinfo_channelid.up.sql
  server/channels/db/migrations/postgres/000106_fileinfo_channelid.down.sql
  server/channels/db/migrations/postgres/000106_fileinfo_channelid.up.sql
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/file_info_layer.go
  server/channels/store/searchtest/file_info_layer.go
  server/channels/store/searchtest/helper.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/file_info_store.go
  server/channels/store/sqlstore/integrity.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/store.go
  server/channels/store/storetest/file_info_store.go
  server/channels/store/storetest/mocks/FileInfoStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note

#22579 Run tests for all web app packages in CI
  .github/workflows/channels-ci.yml
  webapp/boards/package.json
  webapp/channels/package.json
  webapp/platform/client/package.json
  webapp/playbooks/jest.config.js
  webapp/playbooks/package.json
Labels: 4: Reviews Complete, release-note-none

#22560 fix mem leak in hubConnectionIndex
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#22604 MM-51504: Control compliance export goroutine
  server/channels/app/server.go
Labels: 2: Dev Review, release-note-none

#22638 add concurrency limitation to gh actions
  .github/workflows/channels-ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e-ci.yml
Labels: 4: Reviews Complete, release-note-none

#22618 Add setup-go action
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: 2: Dev Review, release-note-none

#22626 Mm 50735
  model/hosted_customer.go
  webapp/channels/src/components/choose_different_shipping/choose_different_shipping.scss
  webapp/channels/src/components/choose_different_shipping/index.tsx
  webapp/channels/src/components/dropdown_input.scss
  webapp/channels/src/components/payment_form/address_form.tsx
  webapp/channels/src/components/payment_form/payment_form.scss
  webapp/channels/src/components/payment_form/payment_form.tsx
  webapp/channels/src/components/purchase_modal/purchase.scss
  webapp/channels/src/components/purchase_modal/purchase_modal.tsx
  webapp/channels/src/components/self_hosted_purchase_modal/address.tsx
  webapp/channels/src/components/self_hosted_purchase_modal/index.test.tsx
  webapp/channels/src/components/self_hosted_purchase_modal/index.tsx
  webapp/channels/src/components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/hosted_customer.ts
Labels: 2: Dev Review, QA Deferred, release-note

#22611 Fix EmailSettings.FeedbackEmail client validation
  webapp/channels/src/components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, release-note-none

#22635 MM-51699: Skip flaky test
  server/boards/app/boards_test.go
Labels: 4: Reviews Complete, release-note-none

#22616 Trigger master branch for builds
  .gitlab-ci.yml
Labels: 4: Reviews Complete, release-note-none

#22568 [MM-51467] - NotifyAdmin job reports an error for unlicensed servers
  server/channels/app/notify_admin.go
  server/channels/jobs/notify_admin/install_plugin_scheduler.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22606 Updated query to support old mysql version
  server/boards/services/store/sqlstore/boards_migrator.go
  server/boards/services/store/sqlstore/data_migrations.go
  server/boards/services/store/sqlstore/data_migrations_test.go
  server/boards/services/store/sqlstore/fixtures/testDeDuplicateCategoryBoardsMigration.sql
  server/boards/services/store/sqlstore/migrationstests/helpers.go
  server/boards/services/store/sqlstore/testlib.go
Labels: release-note-none

#22655 MM-51436: fixes broken link
  webapp/channels/src/components/post_priority/post_priority_picker.tsx
Labels: 2: Dev Review, QA Deferred, release-note-none

#22672 MM-51504: Control compliance export goroutine
  app/server.go
Labels: 2: Dev Review, release-note-none

#22628 Invoice not found is a 404 instead of a 500 error
  server/channels/api4/hosted_customer.go
Labels: 4: Reviews Complete, release-note

#22630 Revert testing workarounds
  server/channels/api4/apitestlib.go
  server/channels/app/app_test.go
  server/channels/app/helper_test.go
  server/channels/app/notification_push_test.go
  server/channels/app/product.go
  server/channels/app/slashcommands/helper_test.go
  server/channels/web/web_test.go
  server/playbooks/server/api_actions_test.go
  server/playbooks/server/api_bot_test.go
  server/playbooks/server/api_general_test.go
  server/playbooks/server/api_graphql_playbooks_test.go
  server/playbooks/server/api_graphql_runs_test.go
  server/playbooks/server/api_playbooks_test.go
  server/playbooks/server/api_runs_test.go
  server/playbooks/server/api_settings_test.go
  server/playbooks/server/api_stats_test.go
  server/playbooks/server/api_telemetry_test.go
  server/playbooks/server/main_test.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#22623 Boards: Use custom placeholder for telemetry.
  server/boards/services/telemetry/telemetry.go
  webapp/boards/src/index.tsx
Labels: QA Deferred, release-note-none

#22648 [MM-49751] - Turn off Inactive Server Email
  model/config.go
  model/feature_flags.go
  server/channels/app/email/email.go
  server/channels/app/email/email_test.go
  server/channels/app/email/mocks/ServiceInterface.go
  server/channels/app/email/service.go
  server/channels/app/server.go
  server/channels/app/server_inactivity.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/templates/inactivity_body.html
  server/templates/inactivity_body.mjml
  server/tests/test-config.json
Labels: 2: Dev Review, release-note-none

#22625 Remove configuration auto enable.
  model/config.go
  server/channels/api4/config.go
  server/config/diff_test.go
  server/i18n/en.json
Labels: 2: Dev Review, release-note-none

#22633 Remove unhelpful test publish.
  .github/workflows/channels-ci.yml
Labels: 2: Dev Review, release-note-none

#22705 MM-51739 Update Focalboard version to v7.9.2 for cloud
  Makefile
Labels: release-note-none

#22613 [MM-51680] : Revert New Browse Channels UI modal changes (https://github.com/mattermost/mattermost-webapp/pull/11262)
  e2e/cypress/tests/integration/channels/channel/archived_channels_1_spec.js
  e2e/cypress/tests/integration/channels/channel/more_channels_spec.js
  e2e/cypress/tests/integration/channels/channel/more_public_channels_spec.js
  e2e/cypress/tests/integration/channels/channel_sidebar/new_channel_dropdown_spec.ts
  e2e/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/tests/integration/channels/enterprise/ldap/ldap_group_sync_spec.js
  webapp/channels/src/actions/channel_actions.test.ts
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.jsx.snap
  webapp/channels/src/components/common/svg_images_components/magnifying_glass_svg.tsx
  webapp/channels/src/components/generic_modal.scss
  webapp/channels/src/components/more_channels/__snapshots__/more_channels.test.tsx.snap
  webapp/channels/src/components/more_channels/__snapshots__/searchable_channel_list.test.jsx.snap
  webapp/channels/src/components/more_channels/index.ts
  webapp/channels/src/components/more_channels/more_channels.scss
  webapp/channels/src/components/more_channels/more_channels.test.tsx
  webapp/channels/src/components/more_channels/more_channels.tsx
  webapp/channels/src/components/more_channels/searchable_channel_list.jsx
  webapp/channels/src/components/searchable_channel_list.jsx
  webapp/channels/src/components/searchable_channel_list.test.jsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_channel-invite-modal.scss
  webapp/channels/src/utils/constants.tsx
  webapp/platform/components/src/generic_modal/generic_modal.tsx
Labels: 2: Dev Review, release-note

#22637 MM-51700: Suppress websocket warnings with a threshold
  server/channels/app/platform/web_conn.go
Labels: 4: Reviews Complete, release-note-none

#22494 [MM-50002] Fix infinite reconnect loop when reconnect handler fails
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#22653 MM-50087_Add marketplace button to apps bar
  e2e/cypress/tests/integration/channels/plugins/marketplace/helpers.js
  webapp/channels/src/actions/command.test.js
  webapp/channels/src/actions/command.ts
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  webapp/channels/src/components/actions_menu/actions_menu.test.tsx
  webapp/channels/src/components/actions_menu/actions_menu.tsx
  webapp/channels/src/components/actions_menu/actions_menu_empty.test.tsx
  webapp/channels/src/components/actions_menu/actions_menu_mobile.test.tsx
  webapp/channels/src/components/actions_menu/index.ts
  webapp/channels/src/components/app_bar/__snapshots__/app_bar.test.tsx.snap
  webapp/channels/src/components/app_bar/app_bar.scss
  webapp/channels/src/components/app_bar/app_bar.test.tsx
  webapp/channels/src/components/app_bar/app_bar.tsx
  webapp/channels/src/components/app_bar/app_bar_marketplace.tsx
  webapp/channels/src/components/custom_open_plugin_install_post_renderer/index.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.test.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/utils/_mixins.scss
Labels: 2: Dev Review, QA Review Done, release-note-none, Setup Cloud + CWS Test Server, 1. UX Review

#22708 MM-51744: Ignore http.ErrServerClosed from Playbooks metricsServer
  server/playbooks/product/playbooks_product.go
Labels: release-note-none

#22701 MM-49869 - add channels Cta button to the LHS sidebar
  webapp/channels/src/actions/views/add_channel_dropdown.ts
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channel_dropdown.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/sidebar/invite_members_button.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/reducers/views/add_channel_cta_dropdown.ts
  webapp/channels/src/reducers/views/index.ts
  webapp/channels/src/sass/layout/_sidebar-left.scss
  webapp/channels/src/selectors/views/add_channel_dropdown.ts
  webapp/channels/src/types/store/views.ts
  webapp/channels/src/utils/constants.tsx
Labels: Setup Cloud Test Server, release-note-none

#22627 MM-51683 Re-add CODEOWNERS for Web Platform files
  CODEOWNERS
  webapp/channels/CODEOWNERS
Labels: 4: Reviews Complete, release-note-none

#22694 MM-51735 Remove references to mattermost-redux from Boards
  webapp/boards/package.json
  webapp/boards/src/components/cloudUpgradeNudge/cloudUpgradeNudge.tsx
  webapp/boards/src/index.tsx
  webapp/boards/src/rudder.ts
  webapp/boards/src/types/mattermost-webapp/index.d.ts
  webapp/boards/webpack.config.js
  webapp/package-lock.json
  webapp/playbooks/jest.config.js
Labels: 4: Reviews Complete, release-note-none

#22697 fix issue with card id being valid block but not card
  webapp/boards/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
  webapp/boards/src/components/boardsUnfurl/boardsUnfurl.test.tsx
  webapp/boards/src/components/boardsUnfurl/boardsUnfurl.tsx
Labels: Setup Cloud Test Server, QA Deferred, 3: Security Review, release-note

#22624 [MM-49090]: Exclude file count on channel stats api call on from channel header
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/components/channel_info_rhs/channel_info_rhs.test.tsx
  webapp/channels/src/components/channel_info_rhs/channel_info_rhs.tsx
  webapp/channels/src/components/channel_info_rhs/index.ts
  webapp/channels/src/components/channel_info_rhs/menu.test.tsx
  webapp/channels/src/components/channel_info_rhs/menu.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#22702 MM-49865 - add telemetry to account creation screen
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/utils/utils.tsx
Labels: release-note-none

#22703 MM-47849 - show worktemplate tourtip only once
  webapp/channels/src/components/tours/worktemplate_explore_tour/boards_tour_tip.tsx
  webapp/channels/src/components/tours/worktemplate_explore_tour/playbooks_tour_tip.tsx
  webapp/channels/src/components/tours/worktemplate_explore_tour/useShowTourTip.tsx
  webapp/channels/src/components/work_templates/index.tsx
  webapp/channels/src/components/work_templates/utils.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/work_templates.ts
  webapp/platform/types/src/work_templates.ts
Labels: release-note-none

#22505 Allowed searching users by substring in admin console
  server/channels/store/searchtest/user_layer.go
  server/channels/store/sqlstore/user_store.go
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
Labels: QA Review Done, release-note-none

#22713 [SEC-3469] Update codeql config for monorepo
  .github/workflows/codeql-analysis.yml
Labels: release-note-none

#22690 Mm 50952 RFQA can save notifications
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/schema_admin_settings.jsx
Labels: 2: Dev Review, release-note-none

#22729 Automated cherry pick of #22441
  app/support_packet.go
  model/system.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22730 Automated cherry pick of #22568
  app/notify_admin.go
  jobs/notify_admin/install_plugin_scheduler.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22569 [MM-51330] - Sentry Crash: nil pointer dereference in getSelfHostedProducts
  server/channels/api4/cloud.go
  server/channels/api4/cloud_test.go
  server/channels/api4/hosted_customer.go
Labels: 2: Dev Review, release-note-none

#22660 MM-51705 Fixes Shared Channels issue due to SELECT('*')
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/sqlstore/shared_channel_store.go
Labels: 2: Dev Review, release-note

#22714 set autolinked board feature flag false as default
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts
  model/feature_flags.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22617 update dialog color for sidebar category
  webapp/boards/src/components/sidebar/sidebarCategory.scss
Labels: QA Review Done, release-note

#22532 Fixed MM-51060
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note-none

#22678 Cherrypicking PR 22532 to v7.9
  app/post_metadata.go
  app/post_metadata_test.go
Labels: release-note-none

#22679 Cherrypicking PR 22532 to v7.8
  app/post_metadata.go
  app/post_metadata_test.go
Labels: release-note-none

#22680 Cherrypicking PR 22532 to v7.7
  app/post_metadata.go
  app/post_metadata_test.go
Labels: release-note-none

#22682 Cherrypicking PR 22532 to cloud
  app/post_metadata.go
  app/post_metadata_test.go
Labels: release-note-none

#22605 MM-T4275 added e2e tests for board description
  e2e-tests/cypress/tests/integration/boards/create_board_spec.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#22728 Include workflow name in the context ref
  .github/workflows/channels-ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e-tests-ci.yml
  .github/workflows/scorecards-analysis.yml
Labels: 2: Dev Review, release-note-none

#22706 Remove Webapp Build Hash
  model/version.go
  server/Makefile
  server/config/client.go
  server/playbooks/product/playbooks_product.go
  webapp/channels/src/components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/webpack.config.js
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#22733 MM-51795 remove cloud banner
  webapp/boards/i18n/en.json
  webapp/boards/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/boards/src/components/messages/cloudMessage.scss
  webapp/boards/src/components/messages/cloudMessage.test.tsx
  webapp/boards/src/components/messages/cloudMessage.tsx
  webapp/boards/src/components/messages/versionMessage.tsx
  webapp/boards/src/pages/boardPage/boardPage.scss
  webapp/boards/src/pages/boardPage/boardPage.tsx
  webapp/boards/src/store/users.ts
  webapp/boards/src/userSettings.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#22741 MM-51504: Control compliance export goroutine (#22672)
  app/server.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22717 MM-49786 - add no thanks button to onboarding completed screen
  webapp/channels/src/components/onboarding_tasklist/__snapshots__/onboarding_tasklist_completed.test.tsx.snap
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.test.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  webapp/channels/src/i18n/en.json
Labels: Setup Cloud Test Server, release-note-none, 1. UX Review

#22735 Optimize JSON marshalling in playbooks
  server/playbooks/server/api/api.go
Labels: 4: Reviews Complete, release-note-none

#22656 [MM-51347] Trial form error modal for embargoed and air gapped entities
  webapp/channels/src/components/common/hooks/useCWSAvailabilityCheck.ts
  webapp/channels/src/components/common/svg_images_components/airgapped_trial_activation_confirm_svg.tsx
  webapp/channels/src/components/start_trial_form_modal/air_gapped_modal.scss
  webapp/channels/src/components/start_trial_form_modal/air_gapped_modal.tsx
  webapp/channels/src/components/start_trial_form_modal/failure_modal.tsx
  webapp/channels/src/components/start_trial_form_modal/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/client/src/client4.ts
Labels: Setup Cloud Test Server, QA Deferred, release-note-none

#22620 [MM-51233] Updates for Trial Requests
  e2e-tests/cypress/tests/integration/channels/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/self-hosted/self_hosted_pricing_modal_spec.ts
  e2e-tests/cypress/tests/integration/channels/system_console/feature_discovery_cloud_spec.js
  model/client4.go
  model/license.go
  model/license_test.go
  server/channels/api4/cloud.go
  server/channels/api4/cloud_test.go
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/channels/app/channels.go
  server/channels/app/license.go
  server/i18n/en.json
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/billing/delete_workspace/result_modal.scss
  webapp/channels/src/components/admin_console/billing/delete_workspace/result_modal.tsx
  webapp/channels/src/components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  webapp/channels/src/components/common/hocs/cloud/with_open_start_trial_form_modal.tsx
  webapp/channels/src/components/common/hooks/useCWSAvailabilityCheck.ts
  webapp/channels/src/components/common/hooks/useOpenStartTrialFormModal.ts
  webapp/channels/src/components/common/svg_images_components/airgapped_trial_activation_confirm_svg.tsx
  webapp/channels/src/components/common/svg_images_components/laptop_with_warning_symbol_svg.tsx
  webapp/channels/src/components/feature_restricted_modal/feature_restricted_modal.tsx
  webapp/channels/src/components/learn_more_trial_modal/learn_more_trial_modal.tsx
  webapp/channels/src/components/learn_more_trial_modal/start_trial_btn.test.tsx
  webapp/channels/src/components/learn_more_trial_modal/start_trial_btn.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/start_trial_form_modal/air_gapped_modal.scss
  webapp/channels/src/components/start_trial_form_modal/air_gapped_modal.tsx
  webapp/channels/src/components/start_trial_form_modal/failure_modal.tsx
  webapp/channels/src/components/start_trial_form_modal/index.tsx
  webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.scss
  webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.test.tsx
  webapp/channels/src/components/start_trial_modal/index.tsx
  webapp/channels/src/components/start_trial_modal/start_trial_modal_svg.tsx
  webapp/channels/src/components/user_groups_modal/ad_ldap_upsell_banner.test.tsx
  webapp/channels/src/components/user_groups_modal/ad_ldap_upsell_banner.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/plugins/export.js
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/playbooks/src/client.ts
  webapp/playbooks/src/components/backstage/upgrade_modal.tsx
  webapp/playbooks/src/components/upgrade_banner.tsx
  webapp/playbooks/src/hooks/general.ts
Labels: 4: Reviews Complete, release-note

#22704 MM-49080 - Fix for: channel links causing the webapp to refresh
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: 4: Reviews Complete, release-note

#22610 [MM-51280] Fix JS error after ephemeral message
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#22674 [MM-51722] Migrate multiple enzyme tests to react testing library
  webapp/channels/src/components/__snapshots__/color_input.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/admin_console.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/color_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_console.test.tsx
  webapp/channels/src/components/admin_console/admin_navbar_dropdown/menu_item_blockable_link.test.tsx
  webapp/channels/src/components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_user_card/admin_user_card.test.tsx
  webapp/channels/src/components/admin_console/color_setting.test.tsx
  webapp/channels/src/components/admin_console/text_setting.test.tsx
  webapp/channels/src/components/color_input.tsx
Labels: 4: Reviews Complete, release-note

#22739 MM-51792 Replace Boards feature flag with env var
  model/feature_flags.go
  server/Makefile
  server/boards/product/boards_product.go
  server/boards/server/boards_service_util.go
  server/channels/app/product.go
  server/docker-compose.yaml
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22599 [MM-46941] Fix: PDF preview doesn't render some Japanese characters
  webapp/channels/src/components/pdf_preview.jsx
  webapp/channels/webpack.config.js
Labels: 4: Reviews Complete, release-note, Contributor

#22750 make autolinked board ff false as default
  model/feature_flags.go
Labels: release-note-none

#22609 MM-50384 : Mark all other menus deprecated
  webapp/channels/src/components/widgets/menu/menu.tsx
  webapp/channels/src/components/widgets/menu/menu_group.tsx
  webapp/channels/src/components/widgets/menu/menu_header.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.tsx
  webapp/channels/src/components/widgets/menu/menu_items/submenu_item.tsx
  webapp/channels/src/components/widgets/menu/menu_wrapper.tsx
  webapp/channels/src/components/widgets/menu/menu_wrapper_animation.tsx
Labels: 4: Reviews Complete, release-note

#22766 MM-51711_Feature flag: APPS sidebar category
  e2e-tests/playwright/support/server/default_config.ts
  model/feature_flags.go
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/platform/types/src/config.ts
Labels: 2: Dev Review, release-note-none

#22716 Update Work Templates content and images
  model/feature_flags.go
  server/channels/api4/work_templates.go
  server/channels/app/worktemplates/templates.yaml
  server/channels/app/worktemplates/worktemplate_generated.go
  server/i18n/de.json
  server/i18n/en.json
  server/i18n/en_AU.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/zh-CN.json
  webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channel_dropdown.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/work_templates/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/images/worktemplates/boards/meeting_agenda.png
  webapp/channels/src/images/worktemplates/boards/project_tasks.png
  webapp/channels/src/images/worktemplates/boards/roadmap.png
  webapp/channels/src/images/worktemplates/boards/sprint_planner.png
  webapp/channels/src/images/worktemplates/boards/team_retrospective.png
  webapp/channels/src/images/worktemplates/companywide/create_project/channel.png
  webapp/channels/src/images/worktemplates/companywide/create_project/create_project.png
  webapp/channels/src/images/worktemplates/companywide/create_project/create_project.svg
  webapp/channels/src/images/worktemplates/companywide/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/companywide/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/devops/incident_resolution/channel.png
  webapp/channels/src/images/worktemplates/devops/incident_resolution/incident_resolution.png
  webapp/channels/src/images/worktemplates/devops/product_release/channel.png
  webapp/channels/src/images/worktemplates/devops/product_release/product_release.png
  webapp/channels/src/images/worktemplates/leadership/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/leadership/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/playbooks/bug_bash.png
  webapp/channels/src/images/worktemplates/playbooks/feature_lifecycle.png
  webapp/channels/src/images/worktemplates/playbooks/incident_resolution.png
  webapp/channels/src/images/worktemplates/playbooks/product_release.png
  webapp/channels/src/images/worktemplates/product_teams/bug_bash/bug_bash.png
  webapp/channels/src/images/worktemplates/product_teams/bug_bash/channel.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/channel.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/feature_release.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/playbooks.png
  webapp/channels/src/images/worktemplates/product_teams/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/product_teams/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/product_teams/product_roadmap/channel.png
  webapp/channels/src/images/worktemplates/product_teams/product_roadmap/product_roadmap.png
  webapp/channels/src/images/worktemplates/product_teams/sprint_planning/channel.png
  webapp/channels/src/images/worktemplates/product_teams/sprint_planning/sprint_planning.png
  webapp/channels/src/selectors/work_template.ts
Labels: CherryPick/Candidate, Setup Cloud Test Server, QA Review Done, release-note

#22769 Cherry-pick: MM-51792 Replace Boards feature flag with env var (#22739)
  model/feature_flags.go
  server/Makefile
  server/boards/product/boards_product.go
  server/boards/server/boards_service_util.go
  server/channels/app/product.go
  server/docker-compose.yaml
Labels: release-note-none

#22772 Manual cherrypick of #22716
  model/feature_flags.go
  server/channels/api4/work_templates.go
  server/channels/app/worktemplates/templates.yaml
  server/channels/app/worktemplates/worktemplate_generated.go
  server/i18n/de.json
  server/i18n/en.json
  server/i18n/en_AU.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/zh-CN.json
  webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
  webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channel_dropdown.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/work_templates/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/images/worktemplates/boards/meeting_agenda.png
  webapp/channels/src/images/worktemplates/boards/project_tasks.png
  webapp/channels/src/images/worktemplates/boards/roadmap.png
  webapp/channels/src/images/worktemplates/boards/sprint_planner.png
  webapp/channels/src/images/worktemplates/boards/team_retrospective.png
  webapp/channels/src/images/worktemplates/companywide/create_project/channel.png
  webapp/channels/src/images/worktemplates/companywide/create_project/create_project.png
  webapp/channels/src/images/worktemplates/companywide/create_project/create_project.svg
  webapp/channels/src/images/worktemplates/companywide/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/companywide/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/devops/incident_resolution/channel.png
  webapp/channels/src/images/worktemplates/devops/incident_resolution/incident_resolution.png
  webapp/channels/src/images/worktemplates/devops/product_release/channel.png
  webapp/channels/src/images/worktemplates/devops/product_release/product_release.png
  webapp/channels/src/images/worktemplates/leadership/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/leadership/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/playbooks/bug_bash.png
  webapp/channels/src/images/worktemplates/playbooks/feature_lifecycle.png
  webapp/channels/src/images/worktemplates/playbooks/incident_resolution.png
  webapp/channels/src/images/worktemplates/playbooks/product_release.png
  webapp/channels/src/images/worktemplates/product_teams/bug_bash/bug_bash.png
  webapp/channels/src/images/worktemplates/product_teams/bug_bash/channel.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/channel.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/feature_release.png
  webapp/channels/src/images/worktemplates/product_teams/feature_release/playbooks.png
  webapp/channels/src/images/worktemplates/product_teams/goals_and_okrs/channel.png
  webapp/channels/src/images/worktemplates/product_teams/goals_and_okrs/goals_and_okrs.png
  webapp/channels/src/images/worktemplates/product_teams/product_roadmap/channel.png
  webapp/channels/src/images/worktemplates/product_teams/product_roadmap/product_roadmap.png
  webapp/channels/src/images/worktemplates/product_teams/sprint_planning/channel.png
  webapp/channels/src/images/worktemplates/product_teams/sprint_planning/sprint_planning.png
  webapp/channels/src/selectors/work_template.ts
Labels: AutoMerge, release-note-none
