Repository mattermost/mattermost, pull requests merged in 2023-12, with the labels that each got.

#25585 Fix 55496
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25578 Fix username collision for shared channels sync update
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: 4: Reviews Complete, release-note-none

#25575 Fix mung of usernames on collision in shared channels; tilde is not a valid character
  server/platform/services/sharedchannel/util.go
  server/platform/services/sharedchannel/util_test.go
Labels: 4: Reviews Complete, release-note-none

#25254 [MM-55180] Cut off text in the Position field in the profile modal
  webapp/channels/src/components/profile_popover/profile_popover.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25529 [MM-56017] Remove prereq-check.sh redantant script from Make
  server/Makefile
  server/scripts/prereq-check.sh
Labels: 4: Reviews Complete, release-note-none

#25548 [MM-54791]: Convert email icon component to function component
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/widgets/icons/email_icon.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25607 [GH-25595] Convert ./components/admin_console/group_settings/group_details/group_users_row.tsx from Class Component to Function Component
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_users.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/group_users_row.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25590 [MM-55999] Bring the revoke sessions button to the admin header and improve the styling of the header
  e2e-tests/cypress/tests/integration/channels/system_console/revoke_all_sessions_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_users/__snapshots__/system_users.test.tsx.snap
  webapp/channels/src/components/admin_console/system_users/index.ts
  webapp/channels/src/components/admin_console/system_users/list/__snapshots__/system_users_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_users/list/system_users_list.tsx
  webapp/channels/src/components/admin_console/system_users/revoke_sessions_button/index.tsx
  webapp/channels/src/components/admin_console/system_users/system_users.test.tsx
  webapp/channels/src/components/admin_console/system_users/system_users.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  webapp/channels/src/components/searchable_user_list/searchable_user_list.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note-none

#25565 Prep for MS Teams plugin API
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000117_msteams_shared_channels.down.sql
  server/channels/db/migrations/mysql/000117_msteams_shared_channels.up.sql
  server/channels/db/migrations/postgres/000117_msteams_shared_channels.down.sql
  server/channels/db/migrations/postgres/000117_msteams_shared_channels.up.sql
  server/channels/store/sqlstore/post_store.go
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/sqlstore/shared_channel_store.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/remote_cluster_store.go
  server/channels/store/storetest/shared_channel_store.go
  server/platform/services/remotecluster/ping.go
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/msg.go
  server/platform/services/sharedchannel/response.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/post.go
  server/public/model/remote_cluster.go
  server/public/model/shared_channel.go
Labels: 4: Reviews Complete, release-note-none

#25438 [MM-55153] Consolidate Desktop App API, use new contextBridge endpoints when available
  webapp/channels/package.json
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/components/channel_layout/channel_controller.test.tsx
  webapp/channels/src/components/channel_layout/channel_controller.tsx
  webapp/channels/src/components/desktop_auth_token.tsx
  webapp/channels/src/components/global_header/left_controls/history_buttons/history_buttons.tsx
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/unreads_status_handler/index.ts
  webapp/channels/src/components/unreads_status_handler/unreads_status_handler.test.tsx
  webapp/channels/src/components/unreads_status_handler/unreads_status_handler.tsx
  webapp/channels/src/plugins/export.js
  webapp/channels/src/utils/browser_history.tsx
  webapp/channels/src/utils/desktop_api.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25547 [MM-54802]: Convert app component to function component
  webapp/channels/src/components/app.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25620 [MM-56006] Convert ./components/discard_changes_modal.tsx from Class Component to Function Component
  webapp/channels/src/components/discard_changes_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25635 Pin morph and dbcmp versions used in test-migration
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#25577 Cherry-pick of #25331
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/reaction_test.go
  server/channels/app/export_test.go
  server/channels/app/reaction.go
  server/channels/app/reaction_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/config/client.go
  server/i18n/en.json
  server/public/model/config.go
  webapp/channels/src/actions/post_actions.test.ts
  webapp/channels/src/actions/post_actions.ts
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/reaction_limit_reached_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/post_utils.test.tsx
  webapp/channels/src/utils/post_utils.ts
  webapp/platform/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#25497 mmctl: add listing oauth apps
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/oauth.go
  server/cmd/mmctl/commands/oauth_test.go
  server/cmd/mmctl/docs/mmctl.rst
  server/cmd/mmctl/docs/mmctl_oauth.rst
  server/cmd/mmctl/docs/mmctl_oauth_list.rst
  server/cmd/mmctl/mocks/client_mock.go
Labels: 2: Dev Review, Area/mmctl, release-note

#25624 Add new bookmark endpoint
  api/Makefile
  api/v4/source/bookmarks.yaml
  api/v4/source/definitions.yaml
  api/v4/source/introduction.yaml
  server/channels/api4/api.go
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/channels/app/channel_bookmark_test.go
  server/i18n/en.json
  server/public/model/channel_bookmark.go
  server/public/model/client4.go
Labels: 2: Dev Review, release-note

#25523 [MM-55328] Convert `./components/toggle_modal_button/toggle_modal_button.test.tsx` from Class Component to Function Component
  webapp/channels/src/components/toggle_modal_button.test.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25634 [MM-56012] Convert ./components/admin_console/team_channel_settings/channel/channel_settings.tsx from Class Component to Function Component
  webapp/channels/src/components/admin_console/team_channel_settings/channel/channel_settings.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25610 [MM-53475] Migrate 'components/suggestion/emoticon_provider.test.jsx' to TypeScript
  webapp/channels/src/components/suggestion/emoticon_provider.test.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25487 [MM-55329] Convert ./plugins/test/post_type.test.jsx from Class Component to Function Component
  webapp/channels/src/plugins/test/post_type.test.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25486 [MM-55117] Replace usage of LocalizedIcon in 'view_user_group_modal_header.tsx' with i/span tags
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25643 [CLD-6778] Update IP filtering docs linkouts
  webapp/channels/src/components/admin_console/ip_filtering/add_edit_ip_filter_modal.tsx
  webapp/channels/src/components/admin_console/ip_filtering/enable_section.tsx
Labels: 4: Reviews Complete, release-note-none

#25562 [MM-55402]Duplicate operationId SaveAcknowledgementForPost in openapi description document
  api/v4/source/posts.yaml
Labels: 4: Reviews Complete, EETests, release-note-none, Contributor

#25340 [MM-54457] Suggestion list UI discrepancy from Add <user> to a Channel modal
  webapp/channels/src/components/suggestion/modal_suggestion_list.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#24672 [MM-54594] Adding new global relay type
  e2e-tests/playwright/support/server/default_config.ts
  server/i18n/en.json
  server/public/model/config.go
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/message_export_settings.test.jsx
  webapp/channels/src/components/admin_console/message_export_settings.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#25656 MM-54426 exclude Channel Bookmarks files from data retention
  api/v4/source/files.yaml
  server/channels/api4/file.go
  server/channels/api4/file_test.go
  server/channels/app/channel_bookmark_test.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/store/sqlstore/file_info_store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/store/storetest/file_info_store.go
  server/public/model/channel_bookmark.go
  server/public/model/file_info.go
  server/public/model/file_info_test.go
Labels: 2: Dev Review, release-note-none

#25567 Augment channel APIs to include bookmarks
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/app/app_iface.go
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/web/params.go
  server/channels/web/params_test.go
  server/i18n/en.json
  server/public/model/channel_bookmark.go
  server/public/model/client4.go
Labels: 2: Dev Review, release-note

#25501 MM-55468 Ensure custom status emojis exist
  server/channels/app/emoji.go
  server/channels/app/plugin_api_test.go
  server/channels/app/status.go
  server/channels/app/status_test.go
  server/i18n/en.json
  server/public/model/emoji.go
  webapp/channels/src/actions/emoji_actions.js
  webapp/channels/src/components/custom_status/__snapshots__/custom_status_modal.test.tsx.snap
  webapp/channels/src/components/custom_status/custom_status_modal.test.tsx
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/emoji/render_emoji.tsx
  webapp/channels/src/selectors/views/custom_status.ts
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/utils/test_helper.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#25662 Automated cherry pick of #25501
  server/channels/app/emoji.go
  server/channels/app/plugin_api_test.go
  server/channels/app/status.go
  server/channels/app/status_test.go
  server/i18n/en.json
  server/public/model/emoji.go
  webapp/channels/src/actions/emoji_actions.js
  webapp/channels/src/components/custom_status/__snapshots__/custom_status_modal.test.tsx.snap
  webapp/channels/src/components/custom_status/custom_status_modal.test.tsx
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/emoji/render_emoji.tsx
  webapp/channels/src/selectors/views/custom_status.ts
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/utils/test_helper.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25637 MM-55589: Throw warn logs for MySQL < 8
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/store_test.go
Labels: 4: Reviews Complete, release-note

#24943 [MM-54821] Convert "revoke_token_button.tsx" from Class Component to Function Component
  webapp/channels/src/components/admin_console/revoke_token_button/revoke_token_button.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#25638 MM-56039: Skip flaky test TestUserStore/LocalCache+PostgreSQL/SearchNotInTeam/
  server/channels/store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note-none

#25648 [MM-56061] Only render where field in model.AppError when it's present
  server/channels/api4/group.go
  server/channels/api4/notify_admin_test.go
  server/channels/api4/post_test.go
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authorization.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/web/context.go
  server/cmd/mmctl/commands/bot_e2e_test.go
  server/cmd/mmctl/commands/channel_e2e_test.go
  server/cmd/mmctl/commands/channel_users_e2e_test.go
  server/cmd/mmctl/commands/command_e2e_test.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/extract_e2e_test.go
  server/cmd/mmctl/commands/group_e2e_test.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/cmd/mmctl/commands/plugin_e2e_test.go
  server/cmd/mmctl/commands/plugin_marketplace_e2e_test.go
  server/cmd/mmctl/commands/team_e2e_test.go
  server/cmd/mmctl/commands/token_e2e_test.go
  server/cmd/mmctl/commands/user_e2e_test.go
  server/public/model/permission.go
  server/public/model/permission_test.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: 4: Reviews Complete, release-note

#25593 [MM-43331] No autofocus after RHS supression
  webapp/channels/src/components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  webapp/channels/src/components/rhs_thread/rhs_thread.test.tsx
  webapp/channels/src/components/rhs_thread/rhs_thread.tsx
  webapp/channels/src/components/sidebar_right/index.ts
  webapp/channels/src/components/sidebar_right/sidebar_right.test.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#25680 Automated cherry pick of #25637
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/store_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25616 MM-25111 Replace usage of LocalizedIcon in 'channel_members_rhs/header.tsx' with i/span tags
  webapp/channels/src/components/channel_members_rhs/header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25631 MM-55966 - SystemConsole fix enabling dependent settings.
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25687 Automated cherry pick of #25670
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25681 Automated cherry pick of #23176
  server/channels/app/oauth.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, EETests, release-note-none

#25671 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/en_AU.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none

#25691 MM-56164 - Update prepackaged calls to v0.22.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#25653 Adds update channel bookmark endpoint
  api/v4/source/bookmarks.yaml
  api/v4/source/definitions.yaml
  server/channels/api4/api.go
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/channels/app/app_iface.go
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/web/params.go
  server/i18n/en.json
  server/public/model/channel_bookmark.go
  server/public/model/channel_bookmark_test.go
  server/public/model/client4.go
Labels: release-note

#25692 Automated cherry pick of #25691
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25654 MM-56060: Create base scaffolding for websocket pub-sub
  server/channels/api4/websocket_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/websocket_router.go
  server/public/model/websocket_client.go
  server/public/model/websocket_message.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/team_sidebar/team_sidebar.tsx
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#25636 Migrate `./components/channel_header_mobile/show_search_button/show_search_button.tsx` from Class component to functional component
  webapp/channels/src/components/channel_header_mobile/__snapshots__/channel_header_mobile.test.tsx.snap
  webapp/channels/src/components/channel_header_mobile/show_search_button/show_search_button.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#25661 MM-56094 Add dedicated tests for RemoveMarkdown renderer
  webapp/channels/src/utils/markdown/link_only_renderer.test.tsx
  webapp/channels/src/utils/markdown/remove_markdown.test.tsx
  webapp/channels/src/utils/markdown/remove_markdown.ts
Labels: 4: Reviews Complete, release-note-none

#25710 MM-56178 - Update prepackaged calls to v0.22.1
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#25667 Delete not needed gitpod.yml file in the webapp
  api/.gitpod.yml
  webapp/channels/.gitpod.yml
Labels: 2: Dev Review, release-note-none, Contributor

#25709 Automated cherry pick of #25661
  webapp/channels/src/utils/markdown/link_only_renderer.test.tsx
  webapp/channels/src/utils/markdown/remove_markdown.test.tsx
  webapp/channels/src/utils/markdown/remove_markdown.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25711 Automated cherry pick of #25710
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25591 MM-55987: Bypass uploading to S3 for local mode mmctl import
  server/channels/api4/import_test.go
  server/channels/jobs/import_process/worker.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/docs/mmctl_import_process.rst
Labels: 4: Reviews Complete, release-note

#25511 MM-55655: Fix unbounded concurrency in outgoing webhooks
  server/channels/app/command.go
  server/channels/app/server.go
  server/channels/app/webhook.go
Labels: 4: Reviews Complete, release-note-none

#25694 MM-56071: Thread presence indicator
  server/channels/api4/websocket_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/websocket_router.go
  server/public/model/websocket_client.go
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#25701 bump the server/public module revision to an existing commit
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none

#25651 [MM-56010] Convert ./components/widgets/icons/accordion_toggle_icon.tsx from Class Component to Function Component
  webapp/channels/src/components/widgets/icons/accordion_toggle_icon.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#25672 [MM-56007] Convert `./components/get_public_link_modal/get_public_link_modal.tsx` from Class Component to Function Component
  webapp/channels/src/components/get_public_link_modal/get_public_link_modal.test.tsx
  webapp/channels/src/components/get_public_link_modal/get_public_link_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25644 Migrate `./components/widgets/icons/fa_warning_icon.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/request_button/__snapshots__/request_button.test.tsx.snap
  webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25617 [MM-55100] Replace usage of LocalizedIcon in 'create_user_groups_modal/create_user_groups_modal.tsx' with i/span tags
  webapp/channels/src/components/create_user_groups_modal/__snapshots__/create_user_groups_modal.test.tsx.snap
  webapp/channels/src/components/create_user_groups_modal/create_user_groups_modal.test.tsx
  webapp/channels/src/components/create_user_groups_modal/create_user_groups_modal.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25684 Fix MM53181
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: 4: Reviews Complete, release-note-none

#25717 [MM-56009] Convert `./components/post_view/embedded_bindings/embedded_bindings.tsx` from Class Component to Function Component
  webapp/channels/src/components/post_view/embedded_bindings/embedded_bindings.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25448 MM-55476: Optimize PostStore.Get
  server/channels/store/sqlstore/post_store.go
  server/channels/store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note

#25650 Allow developers to set a custom go version via env variables
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#25517 Add plugin user settings
  webapp/channels/src/components/settings_sidebar/settings_sidebar.test.tsx
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/components/user_settings/index.test.tsx
  webapp/channels/src/components/user_settings/index.ts
  webapp/channels/src/components/user_settings/index.tsx
  webapp/channels/src/components/user_settings/modal/index.ts
  webapp/channels/src/components/user_settings/modal/user_settings_modal.test.tsx
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/components/user_settings/plugin/__snapshots__/plugin.test.tsx.snap
  webapp/channels/src/components/user_settings/plugin/plugin.test.tsx
  webapp/channels/src/components/user_settings/plugin/plugin.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_setting.test.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_setting.tsx
  webapp/channels/src/components/user_settings/plugin/radio.test.tsx
  webapp/channels/src/components/user_settings/plugin/radio.tsx
  webapp/channels/src/components/user_settings/plugin/radio_option.test.tsx
  webapp/channels/src/components/user_settings/plugin/radio_option.tsx
  webapp/channels/src/components/user_settings/setting_desktop_header.test.tsx
  webapp/channels/src/components/user_settings/setting_desktop_header.tsx
  webapp/channels/src/components/user_settings/setting_mobile_header.test.tsx
  webapp/channels/src/components/user_settings/setting_mobile_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.test.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/sass/components/_settings-modal.scss
  webapp/channels/src/sass/routes/_settings.scss
  webapp/channels/src/selectors/plugins.test.js
  webapp/channels/src/selectors/plugins.ts
  webapp/channels/src/types/plugins/user_settings.ts
  webapp/channels/src/types/store/plugins.ts
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/plugins/plugin_setting_extraction.test.ts
  webapp/channels/src/utils/plugins/plugin_setting_extraction.tsx
  webapp/channels/src/utils/plugins/preferences.test.tsx
  webapp/channels/src/utils/plugins/preferences.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#25537 [MM-55110] Replace usage of LocalizedIcon in 'custom_theme_chooser.tsx' with i/span tags
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/__snapshots__/custom_theme_chooser.test.tsx.snap
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25713 New report router and user reporting refactoring
  api/Makefile
  api/v4/source/reports.yaml
  api/v4/source/users.yaml
  server/channels/api4/api.go
  server/channels/api4/report.go
  server/channels/api4/user.go
  server/channels/app/report.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/store/storetest/user_store.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/report.go
  server/public/model/user.go
  server/public/model/user_serial_gen.go
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note-none

#25686 Adds update channel bookmark sort order endpoint
  api/v4/source/bookmarks.yaml
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/channels/app/channel_bookmark.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/web/params.go
  server/i18n/en.json
  server/public/model/client4.go
Labels: 2: Dev Review, release-note

#25609 Export permalink preview component for plugins.
  webapp/channels/src/plugins/export.js
Labels: 4: Reviews Complete, release-note-none

#25728 Automated cherry pick of #25684
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25700 Adds list channel bookmarks endpoint
  api/v4/source/bookmarks.yaml
  server/channels/api4/apitestlib.go
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/public/model/client4.go
Labels: 2: Dev Review, release-note

#25698 feat: Migrate docker preview repo stuff in monorepo
  server/build/docker-preview/Dockerfile
  server/build/docker-preview/README.md
  server/build/docker-preview/config_docker.json
  server/build/docker-preview/docker-entry.sh
Labels: kind/feature, release-note-none

#25734 Automated cherry pick of #25698
  server/build/docker-preview/Dockerfile
  server/build/docker-preview/README.md
  server/build/docker-preview/config_docker.json
  server/build/docker-preview/docker-entry.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#25736 Automated cherry pick of #25698
  server/build/docker-preview/Dockerfile
  server/build/docker-preview/README.md
  server/build/docker-preview/config_docker.json
  server/build/docker-preview/docker-entry.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#25737 Automated cherry pick of #25698
  server/build/docker-preview/Dockerfile
  server/build/docker-preview/README.md
  server/build/docker-preview/config_docker.json
  server/build/docker-preview/docker-entry.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#25716 Add channel moderation to bookmarks
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/helpers.js
  server/channels/api4/apitestlib.go
  server/channels/api4/channel_bookmark_test.go
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/public/model/permission.go
  server/public/model/role.go
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/permissions.ts
Labels: release-note

#25685 MM-56087 Change Move Thread hotkey to force close menu
  webapp/channels/src/components/dot_menu/dot_menu.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25688 Fix translation ordering for release-8.1
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#25733 Automated cherry pick of #25698
  server/build/docker-preview/Dockerfile
  server/build/docker-preview/README.md
  server/build/docker-preview/config_docker.json
  server/build/docker-preview/docker-entry.sh
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, EETests, release-note-none

#25726 [MM-56206] Allow for proper paging and sorting
  api/v4/source/reports.yaml
  server/channels/api4/report.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/storetest/user_store.go
  server/public/model/client4.go
  server/public/model/report.go
  webapp/platform/types/src/client4.ts
Labels: 2: Dev Review, release-note-none

#25668 [MM-56011] Migrated radio_setting.tsx from Class to Functional Component #25603
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/radio_setting.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25722 [MM-55303] Make use of GenericStoreResult in webhook
  server/channels/app/webhook.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#25541 [MM-55330]: Convert `./components/widgets/popover/index.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  webapp/channels/src/components/suggestion/search_suggestion_list.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/__snapshots__/custom_theme_chooser.test.tsx.snap
  webapp/channels/src/components/widgets/popover/__snapshots__/popover.test.tsx.snap
  webapp/channels/src/components/widgets/popover/index.tsx
  webapp/channels/src/components/widgets/popover/popover.test.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25639 MM-33823 Fix suggestion box deleting the message
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#25488 MM-55505 - Updating thread avatars hover state
  webapp/channels/src/components/channel_invite_modal/team_warning_banner/__snapshots__/team_warning_banner.test.tsx.snap
  webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  webapp/channels/src/components/widgets/simple_tooltip/simple_tooltip.tsx
  webapp/channels/src/components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  webapp/channels/src/components/widgets/users/avatars/avatars.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25745 Run contributor PR tests on free tier
  .github/workflows/server-test-template.yml
Labels: 4: Reviews Complete, release-note-none

#23805 [MM-53269] Add configuration setting for integration requests timeout
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/integration_action_test.go
  server/channels/app/app_iface.go
  server/channels/app/command.go
  server/channels/app/integration_action.go
  server/channels/app/integration_action_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/slashcommands/command_test.go
  server/channels/app/webhook.go
  server/channels/app/webhook_test.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/public/model/config_test.go
  server/public/model/integration_action.go
  server/public/model/integration_action_test.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note

#23139 Removed blank space in sidebar display in compact view mode
  webapp/channels/src/components/post/post_component.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25611 [MM-55993] Create a composable independent table to be used in Admin reporting
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/list_table/elapsed_duration_cell.tsx
  webapp/channels/src/components/admin_console/list_table/index.ts
  webapp/channels/src/components/admin_console/list_table/list_table.scss
  webapp/channels/src/components/admin_console/list_table/list_table.tsx
  webapp/channels/src/components/admin_console/list_table/pagination.tsx
  webapp/channels/src/components/menu/menu.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_admin-console.scss
  webapp/channels/src/sass/utils/_mixins.scss
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#25741 MM-56273 - Update prepackaged calls to v0.22.2
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#25772 Automated cherry pick of #25741
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25536 [MM-29240] Improve buffer handling of UploadEmojiImage
  server/channels/app/app_iface.go
  server/channels/app/emoji.go
  server/channels/app/emoji_bench_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/utils/emoji.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Done, release-note

#25738 Updating sidebar position in settings modal
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/sass/routes/_settings.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#25777 chore: add test case ID to wrangler e2e tests
  e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_dm_spec.js
  e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_gm_spec.js
  e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_private_channel_spec.js
  e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_public_channel_spec.js
Labels: release-note-none

#25779 fix: Fix condition for choosing runner
  .github/workflows/server-test-template.yml
Labels: kind/bug, release-note-none

#25771 Add Options field to RemoteClusters
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000119_msteams_shared_channels_opts.down.sql
  server/channels/db/migrations/mysql/000119_msteams_shared_channels_opts.up.sql
  server/channels/db/migrations/postgres/000119_msteams_shared_channels_opts.down.sql
  server/channels/db/migrations/postgres/000119_msteams_shared_channels_opts.up.sql
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/storetest/remote_cluster_store.go
  server/public/model/remote_cluster.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#25765 [MM-56293] Convert `./components/admin_console/filter/filter_list.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/filter/filter_list.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25743 Mm 16623 fix all initialism errors in channels/app and channels/api4 dir
  server/channels/api4/apitestlib.go
  server/channels/api4/channel_test.go
  server/channels/api4/command_test.go
  server/channels/api4/post_test.go
  server/channels/api4/reaction_test.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
  server/channels/app/slashcommands/auto_posts.go
  server/channels/app/slashcommands/command_invite_people.go
  server/channels/app/slashcommands/command_loadtest.go
  server/channels/app/slashcommands/command_msg.go
  server/channels/app/slashcommands/command_remote.go
  server/channels/app/slashcommands/command_share.go
  server/cmd/mmctl/commands/command_e2e_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none, Contributor

#25544 Add pagination example to Client4
  server/public/model/client4_test.go
Labels: 4: Reviews Complete, release-note-none

#25472 Change dnd status and remind to next morning
  webapp/channels/src/components/dot_menu/post_reminder_submenu.tsx
  webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
Labels: 4: Reviews Complete, release-note

#25782 feat: Remove gitlab-ci yml file [skip ci]
  .gitlab-ci.yml
Labels: kind/feature, release-note-none

#25740 Add SectionNotice to plugin user settings
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/no_common_teams/no_common_teams.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/warning_text_section/warning_text_section.scss
  webapp/channels/src/components/convert_gm_to_channel_modal/warning_text_section/warning_text_section.tsx
  webapp/channels/src/components/section_notice.scss
  webapp/channels/src/components/section_notice.test.tsx
  webapp/channels/src/components/section_notice.tsx
  webapp/channels/src/components/user_settings/modal/user_settings_modal.test.tsx
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/components/user_settings/plugin/__snapshots__/plugin.test.tsx.snap
  webapp/channels/src/components/user_settings/plugin/plugin.test.tsx
  webapp/channels/src/components/user_settings/plugin/plugin.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_action.scss
  webapp/channels/src/components/user_settings/plugin/plugin_action.test.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_action.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_setting.test.tsx
  webapp/channels/src/components/user_settings/plugin/plugin_setting.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/types/plugins/user_settings.ts
  webapp/channels/src/utils/plugins/plugin_setting_extraction.test.ts
  webapp/channels/src/utils/plugins/plugin_setting_extraction.tsx
Labels: 4: Reviews Complete, release-note

#25744 MM-53676: Bump dependencies
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: 4: Reviews Complete, release-note-none

#25790 Remove user search skipped test
  server/channels/store/storetest/user_store.go
Labels: 4: Reviews Complete, release-note-none

#25775 MM-56071: Track multiple threads
  server/channels/api4/websocket_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/websocket_router.go
  server/public/model/websocket_client.go
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#25770 [MM-56297] Convert `./components/widgets/settings/radio_setting.tsx` from Class Component to Function Component
  webapp/channels/src/components/widgets/settings/radio_setting.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25767 [MM-56295] Convert `./components/post_view/message_attachments/message_attachment_list.tsx` from Class Component to Function Component
  webapp/channels/src/components/post_view/message_attachments/message_attachment_list.tsx
  webapp/channels/src/components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25764 [MM-56292] Convert `./components/widgets/icons/checkbox_partial_icon.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.tsx.snap
  webapp/channels/src/components/widgets/icons/checkbox_partial_icon.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25761 [MM-56298] Convert `./components/file_attachment/file_thumbnail/file_thumbnail.tsx` from Class Component to Function Component
  webapp/channels/src/components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
  webapp/channels/src/components/file_attachment/file_thumbnail/file_thumbnail.tsx
  webapp/channels/src/components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25796 Added API to return user count bands and user count
  api/Makefile
  api/v4/source/definitions.yaml
  api/v4/source/limits.yaml
  server/channels/api4/api.go
  server/channels/api4/limits.go
  server/channels/app/app_iface.go
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/limits.go
  webapp/platform/client/src/client4.ts
Labels: release-note-none

#23854 Refactor server runJobs function.
  server/channels/app/server.go
Labels: 4: Reviews Complete, Lifecycle/1:stale, release-note-none, Contributor

#25215 Improves validation in getRolesByName endpoint
  server/channels/api4/role.go
  server/channels/api4/role_test.go
  server/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#25791 Fix auto delete post when dismissed by a plugin
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, release-note

#25766 [MM-56294] Convert `./components/admin_console/group_settings/group_details/group_profile.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/group_profile.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25800 MM-56359: Skip TestUploadLicenseFile
  server/channels/api4/license_test.go
Labels: 4: Reviews Complete, release-note-none

#25801 shared/filestore/localstore.go: remove unnecessary warning
  server/platform/shared/filestore/filesstore_test.go
  server/platform/shared/filestore/localstore.go
Labels: 4: Reviews Complete, release-note-none

#25805 Shared channels plugin APIs for MS Teams plugin
  server/channels/api4/shared_channel_test.go
  server/channels/app/app_iface.go
  server/channels/app/channel.go
  server/channels/app/helper_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/remote_cluster.go
  server/channels/app/server.go
  server/channels/app/shared_channel.go
  server/channels/app/shared_channel_test.go
  server/channels/app/slashcommands/command_share.go
  server/channels/app/slashcommands/command_share_test.go
  server/channels/app/slashcommands/helper_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/RemoteClusterStore.go
  server/channels/store/storetest/remote_cluster_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/platform/services/remotecluster/mocks_test.go
  server/platform/services/remotecluster/ping.go
  server/platform/services/remotecluster/ping_test.go
  server/platform/services/remotecluster/send_test.go
  server/platform/services/remotecluster/sendprofileImage_test.go
  server/platform/services/remotecluster/service.go
  server/platform/services/remotecluster/service_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/shared_channel.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/api.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, release-note

#25808 Updated tier wording
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/components/pricing_modal/self_hosted_content.tsx
  webapp/channels/src/i18n/en.json
Labels: release-note-none

#25806 Removed user bands
  api/v4/source/definitions.yaml
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/public/model/limits.go
Labels: 4: Reviews Complete, release-note-none

#25699 [MM-56042] Show full timestamp with seconds in tooltip
  webapp/channels/src/components/post_view/post_time/post_time.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25807 Added air-gapped contact sales modal
  webapp/channels/src/components/air_gapped_contact_sales_modal/index.tsx
  webapp/channels/src/components/air_gapped_contact_sales_modal/style.scss
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: release-note-none

#25720 [MM-47306] Migrate /enterprise/integrations e2e tests to TypeScript
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_muting_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/integrations/incoming_webhook_spec.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#25697 [MM-56019] Move the deactivate account section to the last, and change the button to danger
  webapp/channels/src/components/setting_item_max.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
Labels: 2: Dev Review, release-note-none, Contributor

#25763 [MM-56291] Convert `./components/widgets/icons/checkbox_checked_icon.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/group_settings/__snapshots__/group_row.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap
  webapp/channels/src/components/widgets/icons/checkbox_checked_icon.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#25689 [MM-55974] Theme is not used in notification selector box in user notification settings
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#25379 [WIP] [MM-55031] OAuth Outgoing Connection App integration
  api/Makefile
  api/v4/source/definitions.yaml
  api/v4/source/outgoing_oauth_connections.yaml
  server/channels/api4/api.go
  server/channels/api4/outgoing_oauth_connection.go
  server/channels/api4/outgoing_oauth_connection_test.go
  server/channels/app/app.go
  server/channels/app/app_iface.go
  server/channels/app/channels.go
  server/channels/app/enterprise.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/server.go
  server/channels/utils/license.go
  server/channels/web/context.go
  server/channels/web/params.go
  server/einterfaces/mocks/OAuthOutgoingConnectionInterface.go
  server/einterfaces/mocks/OutgoingOAuthConnectionInterface.go
  server/einterfaces/outgoing_oauth_connection.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/feature_flags.go
  server/public/model/license.go
  server/public/model/outgoing_oauth_connection.go
  server/public/model/outgoing_oauth_connection_test.go
Labels: kind/feature, release-note

#25294 [MM-55307] Make AdminConsole/TeamFilterDropdown use AsyncSelect instead of LegacyInfiniteScroll
  webapp/channels/src/components/admin_console/data_retention_settings/channel_list/channel_list.scss
  webapp/channels/src/components/admin_console/filter/filter.scss
  webapp/channels/src/components/admin_console/filter/team_filter_dropdown/index.tsx
  webapp/channels/src/components/admin_console/filter/team_filter_dropdown/team_filter_checkbox.tsx
  webapp/channels/src/components/admin_console/filter/team_filter_dropdown/team_filter_dropdown.scss
  webapp/channels/src/components/admin_console/filter/team_filter_dropdown/team_filter_dropdown.tsx
  webapp/channels/src/components/gif_picker/components/InfiniteScroll/index.js
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#25731 [MM-47961] Migrate /support/assertions.js e2e tests file to TypeScript
  e2e-tests/cypress/tests/support/assertions.ts
Labels: 2: Dev Review, release-note-none, Contributor

#25230 [MM-47086] Migrate "components/size_aware_image.jsx" and tests to Typescript
  webapp/channels/src/components/__snapshots__/size_aware_image.test.tsx.snap
  webapp/channels/src/components/markdown_image/markdown_image.tsx
  webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.test.tsx
  webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx
  webapp/channels/src/components/post_view/post_image/post_image.tsx
  webapp/channels/src/components/single_image_view/single_image_view.test.tsx
  webapp/channels/src/components/single_image_view/single_image_view.tsx
  webapp/channels/src/components/size_aware_image.test.tsx
  webapp/channels/src/components/size_aware_image.tsx
Labels: Hacktoberfest, release-note-none, Contributor
