Repository mattermost/mattermost, pull requests merged in 2023-01, with the labels that each got.

#21907 MM-48988 Log plugins version on install and on startup
  app/plugin_install.go
  plugin/environment.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#21964 Mm 49258 - Inform admins trying to self-hosted purchase who the email listed on the JWT claim is
  model/hosted_customer.go
Labels: CherryPick/Approved, QA Deferred, release-note-none

#21952 MM-48345: Fix Critical level logging
  app/migrations.go
  app/platform/metrics.go
  app/server.go
  services/upgrader/upgrader_linux.go
  shared/mlog/global.go
  shared/mlog/global_test.go
Labels: 4: Reviews Complete, release-note

#21956 Clean untranslated logs
  model/utils.go
  model/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#21960 Return 404 when thread membership not found
  app/post_test.go
  app/user.go
  app/user_test.go
Labels: 4: Reviews Complete, release-note-none

#21899 [MM-48759] track event when redirect from cws signup with utm campaign
  api4/user.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#21882 [MM-47489] Move Shared Channels (Experimental) to Professional
  app/server.go
  config/client.go
  config/client_test.go
  model/license.go
  model/license_test.go
Labels: 4: Reviews Complete, release-note

#21726 [MM-23837] Support multiple users/channels in invite slash command
  app/slashcommands/command_invite.go
  app/slashcommands/command_invite_test.go
  i18n/en.json
Labels: Setup Cloud Test Server, release-note, Contributor

#21990 cicleci: add ability use target branch for pulling focalboard
  .circleci/config.yml
Labels: release-note-none

#21984 MM-45967: Print diff output in go mod tidy
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#21985 MM-49395: Increase compression for previews and emojis
  app/emoji.go
  app/imaging/encode.go
  app/user_test.go
  app/users/profile_picture.go
  i18n/en.json
  tests/10000x1_expected_preview.png
  tests/10000x1_expected_thumb.png
  tests/1x10000_expected_preview.png
  tests/1x10000_expected_thumb.png
  tests/fill_test_16bit_rgb_out.png
  tests/fill_test_16bit_rgba_out.png
  tests/fill_test_8bit_palette_out.png
  tests/fill_test_8bit_rgb_out.png
  tests/fill_test_8bit_rgba_out.png
Labels: 2: Dev Review, release-note

#21998 Automated cherry pick of #21969
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21991 Pre-pacakge Playbooks v1.35.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#22002 Automated cherry pick of #21991
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21887 Remove superfluous "channel" in comment
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, Lifecycle/1:stale, AutoMerge, release-note-none, Contributor

#22008 sqlstore/store: make SetupConnection public to be used by products (#…
  store/sqlstore/store.go
Labels: 2: Dev Review, release-note-none

#21995 cicleci: add ability use target branch for pulling focalboard (#21990)
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#22012 Manual cherry pick of #21969
  i18n/en.json
Labels: release-note-none

#21958 [MM-47187] Certificate auth for Elasticsearch
  i18n/en.json
  model/config.go
  services/telemetry/telemetry.go
Labels: 4: Reviews Complete, release-note-none

#22015 Manual cherry pick of #21882
  app/server.go
  config/client.go
  config/client_test.go
  model/license.go
  model/license_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22011 Manual cherry pick of #21896
  store/sqlstore/store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22001 Automated cherry pick of #21991
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22020 Contribute/wysiwyg
  model/feature_flags.go
Labels: 2: Dev Review, release-note-none

#22006 MM-49485: Set BoardsProduct FF to on by default
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, release-note

#22017 Cherry-pick: MM-48345: Fix Critical level logging (#21952)
  app/migrations.go
  app/platform/metrics.go
  app/server.go
  services/upgrader/upgrader_linux.go
  shared/mlog/global.go
  shared/mlog/global_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#22018 MM-49546: Sentry crash: fix nil pointer dereference
  app/post_test.go
  store/sqlstore/thread_store.go
Labels: 2: Dev Review, release-note-none

#22025 Cherry-pick: MM-49485: Set BoardsProduct FF to on by default (#22006)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, release-note

#21980 Update pre-package boards to v7.7.0
  Makefile
Labels: CherryPick/Approved, release-note

#22028 Automated cherry pick of #21980
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21986 [MM-42652] Re-enable test
  api4/channel_category_test.go
Labels: release-note-none

#22032 Automated cherry pick of #22018
  app/post_test.go
  store/sqlstore/thread_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22034 Automated cherry pick of #22013
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#21983 MM-49374: Update job metadata for bulk export
  app/app_iface.go
  app/export.go
  app/export_test.go
  app/opentracing/opentracing_layer.go
  cmd/mattermost/commands/export.go
  jobs/base_workers.go
  jobs/export_process/worker.go
Labels: 4: Reviews Complete, release-note

#22033 MM-49042 - Prepackage Calls version v0.12.0
  Makefile
Labels: CherryPick/Approved, release-note

#22037 Automated cherry pick of #22033
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22036 Automated cherry pick of #22033
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21886 Fix plugin /public handling for subpaths
  app/plugin_requests.go
  app/plugin_requests_test.go
  tests/README.md
  tests/testplugin.tar.gz
  tests/testplugin.tar.gz.asc
  tests/testplugin.tar.gz.sig
Labels: 4: Reviews Complete, release-note

#22046 Add Boards build information to client config
  config/client.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#21957 MM-39215: Add DBStatsCollector to metrics
  app/platform/service_test.go
  einterfaces/metrics.go
  einterfaces/mocks/MetricsInterface.go
  store/sqlstore/store.go
  store/sqlstore/store_test.go
Labels: release-note

#22035 MM-49083 Disable write timeouts for exports
  app/file.go
  shared/filestore/filesstore.go
Labels: release-note-none

#22052 Automated cherry pick of #22046
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22053 Automated cherry pick of #22046
  config/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21780 [MM-46579] Add a limit for preferences
  app/preference.go
  model/config.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#21994 MM-48504: Bump dependencies
  app/server.go
  go.mod
  go.sum
  plugin/hclog_adapter.go
Labels: 4: Reviews Complete, release-note-none

#22048 Skip TestReplicaLagQuery until MM-49604 is fixed
  store/sqlstore/store_test.go
Labels: 2: Dev Review, release-note-none

#22058 MM-49154: Do not translate server side logs
  web/handlers.go
Labels: 2: Dev Review, release-note-none

#21639 [MM-47896] Channel names can collide with GM names
  i18n/en.json
  model/channel.go
  model/channel_test.go
Labels: 4: Reviews Complete, release-note

#22009 Adds description of some channel searching options.
  model/channel.go
Labels: 2: Dev Review, QA Deferred, release-note-none

#22043 [MM-48973] Enable test that was fixed separately
  app/team_test.go
  app/user.go
Labels: 2: Dev Review, release-note-none

#21894 [MM 48440]: Remove the "Only visible to you" text
  app/post.go
  model/post.go
Labels: 4: Reviews Complete, release-note-none

#21913 [MM 48403]: Allow Wrangler to work for DMs/ Group messages
  app/post.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#22057 Bump GitLab plugin prepackaged version to 1.6.0
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#22066 Automated cherry pick of #22057
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22065 Automated cherry pick of #22057
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22067 MM-49638 - Prepackage calls v0.12.1
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#22069 Automated cherry pick of #22067
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22071 MM-49658: Correctly disable plugin in product mode
  app/plugin.go
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#22074 MM-49658: Correctly disable plugin in product mode (#22071)
  app/plugin.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22075 Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)"
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22077 Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)" (#22075)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22083 Revert "Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)" (#22075)"
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 4: Reviews Complete, release-note-none

#22090 Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)" (#22075)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, release-note-none

#22086 Revert "[MM-46579] Add a limit for preferences"
  app/preference.go
  model/config.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/sqlstore/preference_store.go
  store/store.go
  store/storetest/mocks/PreferenceStore.go
  store/storetest/preference_store.go
  store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#22081 Update version to 7.7.1
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22082 Update minor version to 7.8.0
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#21914 MM-47853 - True Up Review Backend
  api4/cloud.go
  api4/license.go
  api4/license_test.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/true_up.go
  db/migrations/migrations.list
  db/migrations/mysql/000101_create_true_up_review_history.down.sql
  db/migrations/mysql/000101_create_true_up_review_history.up.sql
  db/migrations/postgres/000101_create_true_up_review_history.down.sql
  db/migrations/postgres/000101_create_true_up_review_history.up.sql
  einterfaces/cloud.go
  einterfaces/mocks/CloudInterface.go
  i18n/en.json
  model/client4.go
  model/license.go
  model/true_up_review_profile.go
  services/telemetry/telemetry.go
  store/opentracinglayer/opentracinglayer.go
  store/retrylayer/retrylayer.go
  store/retrylayer/retrylayer_test.go
  store/sqlstore/store.go
  store/sqlstore/true_up_review_store.go
  store/sqlstore/true_up_review_store_test.go
  store/store.go
  store/storetest/mocks/Store.go
  store/storetest/mocks/TrueUpReviewStore.go
  store/storetest/store.go
  store/storetest/true_up_review_store.go
  store/timerlayer/timerlayer.go
  utils/true_up.go
  utils/true_up_test.go
Labels: 2: Dev Review, 3: QA Review, QA Deferred, release-note-none

#22078 MM-49474 - Add Telemetry Event for Submitting Downgrade Feedback
  api4/cloud.go
  model/cloud.go
Labels: 2: Dev Review, QA Deferred, release-note-none

#22102 MM-49720 Remove the check for active sessions in IsFirstUserAccount
  app/platform/config.go
  app/platform/config_test.go
Labels: 4: Reviews Complete, release-note

#21656 [SEC-2191] Add security headers with sensible default values.
  web/handlers.go
  web/handlers_test.go
  web/static.go
Labels: release-note

#22104 Cherry-pick 544304d into release 7.7
  app/platform/config.go
  app/platform/config_test.go
Labels: release-note

#22094 MM-49681 - Remove mentions of boards and integrations limits on delinquency emails, and replace remaining "Cloud Starter" text with "Cloud Free" text.
  app/email/email.go
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: QA Deferred, release-note-none

#22093 Handles an empty mysql.time_zone_name table.
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#22106 Automated cherry pick of #22093
  store/sqlstore/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22103 MM-49551: Check if RemoteId is nil for participant
  app/platform/shared_channel_notifier.go
  app/platform/shared_channel_notifier_test.go
Labels: 4: Reviews Complete, release-note-none

#22112 Add `GetDirectChannelOrCreate` to product API
  app/channel.go
  app/channels.go
  app/server.go
  product/api.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#22113 Automated cherry pick of #22112
  app/channel.go
  app/channels.go
  app/server.go
  product/api.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22101 MM-48089 Fix broken links in emails
  app/email/email_batching.go
  app/email/notification_email.go
  app/email/notification_email_test.go
  app/notification_email.go
  utils/markdown.go
  utils/markdown_test.go
Labels: 2: Dev Review, release-note

#22115 Automated cherry pick of #22103
  app/platform/shared_channel_notifier.go
  app/platform/shared_channel_notifier_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22116 Cloud: Fix relative email urls
  app/email/email_batching.go
  app/email/notification_email.go
  app/email/notification_email_test.go
  app/notification_email.go
  utils/markdown.go
  utils/markdown_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note

#22114 Update version to 7.7.2
  model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22054 Mm 49611
  app/plugin_test.go
  model/cloud.go
  model/notify_admin.go
Labels: 2: Dev Review, release-note

#22107 MM-49703: Bump Go version to 1.19
  .circleci/config.yml
  .golangci.yml
  Makefile
  build/Dockerfile.buildenv
  go.mod
  scripts/setup_go_work.sh
Labels: 4: Reviews Complete, release-note-none

#22118 if cloud interface reports upstream is off, notify the web client
  api4/hosted_customer.go
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#22022 [MM-49180] Error message not clear when creating group with mention name matching username
  app/group.go
  app/group_test.go
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#22126 Automated cherry pick of #22022
  app/group.go
  app/group_test.go
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#21883 Mpa playbooks
  Makefile
  app/app_iface.go
  app/channel.go
  app/channels.go
  app/collection.go
  app/opentracing/opentracing_layer.go
  app/permissions.go
  app/plugin_api.go
  app/post.go
  app/server.go
  app/team.go
  config/client.go
  model/version.go
  product/api.go
  product/service.go
  scripts/setup_go_work.sh
  shared/i18n/i18n.go
Labels: 2: Dev Review, release-note-none

#21106 Custom site name set on root HTML title
  web/static.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#22131 MM-49703: Bump Gitlab CI to 1.19
  .gitlab-ci.yml
Labels: 2: Dev Review, release-note-none

#22125 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 4: Reviews Complete, 1: PM Review, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22137 Cherry-picking translations from master
  i18n/de.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-TW.json
Labels: release-note-none, Contributor

#22128 MM-49604: Fix race condition in test
  store/sqlstore/store_test.go
Labels: 2: Dev Review, release-note-none

#22124 MM-49845: fixes acknowledgements in getpostsince
  app/post_acknowledgements.go
  app/post_acknowledgements_test.go
  store/sqlstore/post_acknowledgements_store.go
  store/storetest/post_acknowledgements_store.go
Labels: 2: Dev Review, QA Deferred, release-note-none

#22146 Automated cherry pick of #22143
  api4/cloud.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22147 Automated cherry pick of #22124
  app/post_acknowledgements.go
  app/post_acknowledgements_test.go
  store/sqlstore/post_acknowledgements_store.go
  store/storetest/post_acknowledgements_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22055 [MM-47846] Execute Work Template
  Makefile
  api4/work_templates.go
  api4/worktemplates.go
  api4/worktemplates_test.go
  app/app_iface.go
  app/mocks/WorkTemplateExecutor.go
  app/opentracing/opentracing_layer.go
  app/plugin.go
  app/product.go
  app/server.go
  app/work_template_executor.go
  app/work_templates.go
  app/work_templates_test.go
  app/worktemplates.go
  app/worktemplates/model.go
  app/worktemplates/model_test.go
  app/worktemplates/templates.yaml
  app/worktemplates/types.go
  app/worktemplates/worktemplate_generated.go
  app/worktemplates_test.go
  go.mod
  go.sum
  i18n/en.json
  model/worktemplate.go
Labels: 2: Dev Review, Setup Cloud Test Server, QA Deferred, release-note-none

#21869 [MM-48825] "plugin configured with a nil SecureConfig" warning logged when starting each plugin
  plugin/supervisor.go
Labels: 4: Reviews Complete, kind/bug, release-note

#21987 [MM-49265] Update translations when config is changed
  api4/config.go
  api4/team_test.go
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#22155 [MM-49959] Initialize the logger for CLI imports
  cmd/mattermost/commands/import.go
Labels: 2: Dev Review, release-note-none

#22165 Automated cherry pick of #22155
  cmd/mattermost/commands/import.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22159 [MM-50007] WorkTemplate: disallow creating private playbook without an enterprise license
  api4/work_templates.go
  app/worktemplates/model.go
  app/worktemplates/model_test.go
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#22168 [MM-49715] Work templates: add content
  app/worktemplates/categories.yaml
  app/worktemplates/generator/main.go
  app/worktemplates/templates.yaml
  app/worktemplates/worktemplate_generated.go
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Deferred, release-note-none

#22096 MM-49486: Option to exclude file count in channel stats
  api4/channel.go
  api4/channel_test.go
  model/client4.go
Labels: 4: Reviews Complete, release-note

#22174 Update libcurl3-gnutls
  build/Dockerfile
Labels: 4: Reviews Complete, release-note-none

#22119 MM-49813 - validate inviter permissions when sending invitations to private channels
  api4/team.go
  api4/team_test.go
  api4/user_test.go
  app/app_iface.go
  app/channel.go
  app/email/email.go
  app/opentracing/opentracing_layer.go
  app/user.go
  app/user_test.go
Labels: QA Review Done, 3: Security Review, release-note-none, Setup Cloud + CWS Test Server

#22072 Mm 49463 send invoices annual
  app/cloud.go
  app/email/email.go
  app/email/email_test.go
  app/email/mocks/ServiceInterface.go
  app/email/service.go
Labels: 3: QA Review, QA Review Done, release-note

#22156 MM-49048: do not omit needed wsbroadcast vars
  app/platform/web_hub_test.go
  model/websocket_message.go
Labels: 4: Reviews Complete, QA Deferred, release-note

#22177 Revert "Set BoardsProduct FF to on by default"
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: CherryPick/Approved, release-note-none

#22185 Automated cherry pick of #22174
  build/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#22183 Revert "Set BoardsProduct FF to on by default" (#22177)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, release-note-none

#22154 [MM-48385] Validate against a list of auth services
  app/imports/import_validators.go
  app/imports/import_validators_test.go
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#22187 Pre-package Playbooks v1.36.0
  Makefile
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note

#22194 update libcurl3-gnutls (#22174)
  build/Dockerfile
Labels: 2: Dev Review, release-note-none

#22181 Revert "Set BoardsProduct FF to on by default" (#22177)
  config/diff_test.go
  model/config.go
  model/config_test.go
  model/feature_flags.go
  scripts/test.sh
Labels: 2: Dev Review, release-note-none

#22145 MM-47537 Export and import read channels
  app/export.go
  app/export_converters.go
  app/export_test.go
  app/import_functions.go
  app/imports/import_types.go
  store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note

#22160 MM-50024: Handle empty team name for DM/GMs
  app/post.go
  store/sqlstore/post_store.go
  store/storetest/post_store.go
Labels: 4: Reviews Complete, release-note-none

#22162 [MM-49932] Remove experimental warning about plugins
  api4/plugin.go
Labels: 4: Reviews Complete, release-note-none

#22193 Automated cherry pick of #22187
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#22182 Manual cherry pick of #22155
  cmd/mattermost/commands/import.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22197 update libcurl3-gnutls (#22174)
  build/Dockerfile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#22196 Revert "[MM-42652] Re-enable test"
  api4/channel_category_test.go
Labels: 4: Reviews Complete, release-note-none

#22163 Automated cherry pick of #22141
  config/logger.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
