Repository mattermost/mattermost, pull requests merged in 2023-08, with the labels that each got.

#24111 Use | and \ vs. >
  .github/workflows/server-test-template.yml
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#24105 API Updates
  api/v4/source/commands.yaml
  api/v4/source/files.yaml
  api/v4/source/groups.yaml
  api/v4/source/ldap.yaml
  api/v4/source/users.yaml
  server/channels/api4/group.go
Labels: release-note-none

#24166 [CLD-6039] Add '(Only visible to admins)' to license overature banners
  webapp/channels/src/components/announcement_bar/overage_users_banner/index.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#24167 MM-53877: fix export config settings
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/filesstore_test.go
Labels: 4: Reviews Complete, release-note-none

#23997 Update vacuuming parameters for some tables
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000110_update_vacuuming.down.sql
  server/channels/db/migrations/mysql/000110_update_vacuuming.up.sql
  server/channels/db/migrations/postgres/000110_update_vacuuming.down.sql
  server/channels/db/migrations/postgres/000110_update_vacuuming.up.sql
Labels: release-note-none

#24142 remove legacy "Build API specification" workflow
  .github/workflows/server-ci-template.yml
Labels: 4: Reviews Complete, release-note-none

#24169 [MM-53881] Make sure export filestore won't use bifrost
  server/channels/app/platform/service.go
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/s3store.go
Labels: 4: Reviews Complete, CherryPick/Approved, kind/bug, release-note-none

#24176 Automated cherry pick of #24169
  server/channels/app/platform/service.go
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/s3store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24065 Remove unused functions getPing and resetPing
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
Labels: 2: Dev Review, release-note-none

#24179 Automated cherry pick of #24167
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/filesstore_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24180 Automated cherry pick of #24169
  server/channels/app/platform/service.go
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/s3store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24141 Updated API Code Samples
  api/Makefile
  api/server/go.mod
  api/server/go.sum
  api/server/main.go
  api/v4/source/bots.yaml
  api/v4/source/brand.yaml
  api/v4/source/channels.yaml
  api/v4/source/commands.yaml
  api/v4/source/exports.yaml
  api/v4/source/files.yaml
  api/v4/source/imports.yaml
  api/v4/source/introduction.yaml
  api/v4/source/oauth.yaml
  api/v4/source/plugins.yaml
  api/v4/source/posts.yaml
  api/v4/source/roles.yaml
  api/v4/source/schemes.yaml
  api/v4/source/sharedchannels.yaml
  api/v4/source/system.yaml
  api/v4/source/teams.yaml
  api/v4/source/uploads.yaml
  api/v4/source/users.yaml
  server/public/model/example_channel_test.go
Labels: 4: Reviews Complete, release-note

#24184 Revert s3 path prefix normalization for plugins
  server/channels/app/plugin.go
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#24186 MM-53679 - Update prepackaged calls to v0.18.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, Setup Cloud + CWS Test Server

#24192 Automated cherry pick of #24186
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24173 MM-53905: Skip racy test testGetUptoNSizeFileTime
  server/channels/store/storetest/file_info_store.go
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#24170 Fail vs. fatal on store startup
  server/channels/app/platform/service.go
  server/channels/app/plugin_api_tests/test_db_driver/main.go
  server/channels/store/localcachelayer/layer_test.go
  server/channels/store/searchlayer/layer_test.go
  server/channels/store/sqlstore/migrate_test.go
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/store_test.go
  server/channels/testlib/helper.go
  server/cmd/mattermost/commands/db.go
  server/cmd/mattermost/commands/init.go
  server/platform/services/searchengine/bleveengine/bleve_test.go
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#24190 feat: Introduce workflow to tag public server module
  .github/workflows/tag-public-module.yaml
Labels: 4: Reviews Complete, kind/feature, release-note-none

#24147 Fix: adapt e2e scripts to support MacOS as well
  e2e-tests/.ci/.e2erc
Labels: release-note-none

#24102 Adding PostAction plugin hook
  webapp/channels/src/components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.jsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_comment/index.ts
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_create_post/index.ts
  webapp/channels/src/components/dot_menu/index.ts
  webapp/channels/src/components/post/index.tsx
  webapp/channels/src/components/post/post_component.test.tsx
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/post/post_options.tsx
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/types/store/plugins.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#24205 Cherry pick of #23920 on release-7.8
  store/sqlstore/user_store.go
  store/storetest/user_store.go
Labels: release-note-none

#23747 Disable certain actions from running on forks
  .github/workflows/artifacts.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-push-mirrored.yml
  .github/workflows/esrupgrade.yml
  .github/workflows/scorecards-analysis.yml
Labels: 4: Reviews Complete, release-note-none

#24194 MM-53355: tidy up plugins
  server/channels/app/app_iface.go
  server/channels/app/cluster_handlers.go
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_install_test.go
  server/i18n/en.json
  server/public/model/feature_flags.go
  server/public/plugin/environment.go
Labels: Setup Cloud Test Server, QA/Tests Not Required, release-note

#24213 [MM-53943] Remove deprecated UserAuth.Password field
  server/channels/api4/user_test.go
  server/channels/app/user.go
  server/public/model/user.go
Labels: 4: Reviews Complete, release-note

#24212 [MM-40531] Remove deprecated ManifestExecutables struct
  server/public/model/manifest.go
Labels: 4: Reviews Complete, release-note

#24229 plugins: further logging tweaks, fixes
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
Labels: 4: Reviews Complete, QA/Tests Not Required, release-note-none

#24208 Update to github.com/golang-jwt/jwt/v5
  server/channels/app/license.go
  server/channels/app/platform/license.go
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none, Contributor

#24209 MM-53228: Adding schema version to cluster info
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/store_test.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/Store.go
  server/channels/store/storetest/store.go
  server/public/model/cluster_info.go
  webapp/channels/src/components/admin_console/cluster_table.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/admin.ts
Labels: 4: Reviews Complete, release-note-none

#24239 Automated cherry pick of #24214
  e2e-tests/cypress/tests/integration/channels/signin_authentication/signup_spec.js
  e2e-tests/playwright/support/test_fixture.ts
  e2e-tests/playwright/support/ui/components/footer.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/components/main_header.ts
  e2e-tests/playwright/support/ui/pages/index.ts
  e2e-tests/playwright/support/ui/pages/login.ts
  e2e-tests/playwright/support/ui/pages/reset_password.ts
  e2e-tests/playwright/support/ui/pages/signup.ts
  e2e-tests/playwright/tests/accessibility/channels/intro_channel.spec.ts
  e2e-tests/playwright/tests/accessibility/common/login.spec.ts
  e2e-tests/playwright/tests/accessibility/common/reset_password.spec.ts
  e2e-tests/playwright/tests/accessibility/common/signup_user_complete.spec.ts
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_icon.tsx
  webapp/channels/src/components/alert_banner.tsx
  webapp/channels/src/components/app_bar/__snapshots__/app_bar.test.tsx.snap
  webapp/channels/src/components/app_bar/app_bar_plugin_component.tsx
  webapp/channels/src/components/common/back_button.tsx
  webapp/channels/src/components/header_footer_template/__snapshots__/header_footer_template.test.tsx.snap
  webapp/channels/src/components/header_footer_template/header_footer_template.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/post_priority/post_priority_picker_overlay.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/widgets/inputs/check/index.tsx
  webapp/channels/src/components/widgets/inputs/password_input/password_input.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24242 Update README.md: Try cloud instead of use
  README.md
Labels: release-note-none

#24217 .npmrc: engine-strict
  webapp/.npmrc
Labels: 4: Reviews Complete, release-note-none

#23971 MM-50953 Post textbox cleanup
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/at_mention/__snapshots__/at_mention.test.tsx.snap
  webapp/channels/src/components/at_mention/at_mention.tsx
  webapp/channels/src/components/at_mention/at_mention_group.tsx
  webapp/channels/src/components/channel_info_rhs/about_area_dm.tsx
  webapp/channels/src/components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  webapp/channels/src/components/channel_members_rhs/member.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/markdown/markdown.tsx
  webapp/channels/src/components/post_markdown/post_markdown.test.tsx
  webapp/channels/src/components/post_markdown/post_markdown.tsx
  webapp/channels/src/components/post_profile_picture/post_profile_picture.tsx
  webapp/channels/src/components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  webapp/channels/src/components/post_view/post_message_view/post_message_view.tsx
  webapp/channels/src/components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  webapp/channels/src/components/profile_picture/profile_picture.test.tsx
  webapp/channels/src/components/profile_picture/profile_picture.tsx
  webapp/channels/src/components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
  webapp/channels/src/components/terms_of_service/terms_of_service.tsx
  webapp/channels/src/components/textbox.test.tsx
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/plugins/export.js
  webapp/channels/src/plugins/export.test.js
  webapp/channels/src/plugins/test/__snapshots__/post_type.test.jsx.snap
  webapp/channels/src/utils/__snapshots__/message_html_to_component.test.jsx.snap
  webapp/channels/src/utils/message_html_to_component.jsx
  webapp/channels/src/utils/message_html_to_component.test.jsx
Labels: 4: Reviews Complete, release-note-none

#24234 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none, Contributor

#24119 Update NOTICE.txt
  NOTICE.txt
  webapp/channels/NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24247 setup-node for master build from server
  .github/workflows/server-ci-template.yml
Labels: 2: Dev Review, QA/Tests Not Required, release-note-none

#24187 Migrate `components/post_view/post_flag_icon/post_flag_icon.tsx` from class to function component
  webapp/channels/src/components/post_view/post_flag_icon/post_flag_icon.tsx
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#24003 Mark category as read
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/post_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/websocket_message.go
  webapp/channels/src/actions/new_post.test.ts
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/logged_in/logged_in.test.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/components/post_view/post_list/index.tsx
  webapp/channels/src/components/post_view/post_list/post_list.test.tsx
  webapp/channels/src/components/post_view/post_list/post_list.tsx
  webapp/channels/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/channels/src/components/sidebar/channel_navigator/channel_navigator.test.tsx
  webapp/channels/src/components/sidebar/channel_navigator/channel_navigator.tsx
  webapp/channels/src/components/sidebar/channel_navigator/index.ts
  webapp/channels/src/components/sidebar/index.ts
  webapp/channels/src/components/sidebar/sidebar.tsx
  webapp/channels/src/components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/__snapshots__/sidebar_category_sorting_menu.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/create_new_category_menu_item.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/index.test.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/index.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/mark_as_read_confirm_modal.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/mark_as_read_menu_item.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_generic_menu.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu.test.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  webapp/channels/src/components/sidebar/sidebar_list/index.ts
  webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
  webapp/channels/src/components/sidebar/unread_channels.tsx
  webapp/channels/src/components/sidebar/unread_channels/index.ts
  webapp/channels/src/components/sidebar/unread_channels/unread_channels.tsx
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/selectors/views/channel_sidebar.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24244 MM-54004 migrate HeaderFooterNotLoggedIn as functional component
  server/public/model/config.go
  webapp/channels/src/components/header_footer_template/__snapshots__/header_footer_template.test.tsx.snap
  webapp/channels/src/components/header_footer_template/header_footer_template.test.tsx
  webapp/channels/src/components/header_footer_template/header_footer_template.tsx
  webapp/channels/src/components/header_footer_template/index.ts
  webapp/channels/src/components/header_footer_template_route.tsx
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#24210 Migrate access history modal to functional component
  webapp/channels/src/components/access_history_modal/access_history_modal.test.tsx
  webapp/channels/src/components/access_history_modal/access_history_modal.tsx
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#24183 Class to functional component example 2
  webapp/channels/src/components/copy_text.tsx
  webapp/channels/src/components/integrations/__snapshots__/installed_command.test.tsx.snap
  webapp/channels/src/components/integrations/__snapshots__/installed_incoming_webhook.test.tsx.snap
  webapp/channels/src/components/integrations/__snapshots__/installed_outgoing_webhook.test.tsx.snap
  webapp/channels/src/components/integrations/confirm_integration/__snapshots__/confirm_integration.test.tsx.snap
  webapp/channels/src/components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#22582 Remove remote users from the license counting and explicitly dissallow them to log in
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/user.go
  server/channels/app/users/users.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/UserStore.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/user_count.go
  webapp/channels/src/components/user_list_row_with_error/user_list_row_with_error.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, Docs/Done, QA Review Done, release-note

#24238 Fix MM:24226
  server/channels/app/platform/cluster_handlers.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#24252 MM-49063 Silence warning when lastViewedAt is undefined
  webapp/channels/src/components/post_view/post_list/index.tsx
  webapp/channels/src/components/post_view/post_view.tsx
Labels: 4: Reviews Complete, release-note-none

#24198 remove redundant getUser call
  server/channels/app/bot.go
Labels: 4: Reviews Complete, release-note-none, Contributor, kind/refactor

#24223 MM-52910 - remove boards product tour code
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu.tsx
  webapp/channels/src/components/onboarding_tasks/constants.ts
  webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
  webapp/channels/src/components/tours/constant.ts
  webapp/channels/src/components/tours/hooks.ts
  webapp/channels/src/components/tours/onboarding_explore_tools_tour/boards_tour_tip.tsx
  webapp/channels/src/components/tours/onboarding_explore_tools_tour/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#24231 MM-53688 Remove boards dataretention
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/data_retention_policy.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/data_retention_settings/__snapshots__/data_retention_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.test.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#24233 GH-24220: Fix member count shown as zero when searching in browse channel modal
  webapp/channels/src/components/browse_channels/browse_channels.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#24160 [MM-53699] : Remove channel header limit message when user adjusts to valid length
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, EETests, release-note-none, Contributor

#24189 Remove unused components
  webapp/channels/src/components/__snapshots__/picture_selector.test.tsx.snap
  webapp/channels/src/components/accordion.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree_runs.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/toggle_formatting_bar.tsx
  webapp/channels/src/components/advanced_text_editor/toggle_formatting_bar/index.ts
  webapp/channels/src/components/cloud_subscribe_with_loading_modal/index.tsx
  webapp/channels/src/components/cloud_usage_modal/mini_modal.scss
  webapp/channels/src/components/cloud_usage_modal/mini_modal.tsx
  webapp/channels/src/components/common/accordion/message_item.tsx
  webapp/channels/src/components/common/hooks/useGetSubscriptionProduct.ts
  webapp/channels/src/components/common/hooks/useOpenTrialBenefitsModal.ts
  webapp/channels/src/components/common/hooks/useValidateTeam.ts
  webapp/channels/src/components/common/hooks/useValidateUrl.ts
  webapp/channels/src/components/common/svg_images_components/boards_svg.tsx
  webapp/channels/src/components/common/svg_images_components/celebrate_svg.tsx
  webapp/channels/src/components/common/svg_images_components/getting_started_svg.tsx
  webapp/channels/src/components/common/svg_images_components/laptop-earth_svg.tsx
  webapp/channels/src/components/common/svg_images_components/laptop_svg.tsx
  webapp/channels/src/components/common/svg_images_components/mattermost_cloud_svg.tsx
  webapp/channels/src/components/common/svg_images_components/newspaper_svg.tsx
  webapp/channels/src/components/common/svg_images_components/person_mac_svg.tsx
  webapp/channels/src/components/common/svg_images_components/playbooks_svg.tsx
  webapp/channels/src/components/common/svg_images_components/push_notifications_svg.tsx
  webapp/channels/src/components/multi_input.scss
  webapp/channels/src/components/multi_input.tsx
  webapp/channels/src/components/picture_selector.scss
  webapp/channels/src/components/picture_selector.test.tsx
  webapp/channels/src/components/picture_selector.tsx
  webapp/channels/src/components/post_view/comment_icon/index.ts
  webapp/channels/src/components/progress_bar.scss
  webapp/channels/src/components/progress_bar.test.tsx
  webapp/channels/src/components/progress_bar.tsx
  webapp/channels/src/components/threading/global_threads_link/global_threads_link.tsx
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.scss
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.tsx
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal/index.ts
  webapp/channels/src/components/widgets/icons/dots_horizontal.tsx
  webapp/channels/src/components/widgets/icons/message_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none

#24154 [GH-16800]: Refactor raw SQL to query builder in group_store.go - part 1
  server/channels/store/sqlstore/group_store.go
Labels: 4: Reviews Complete, EETests, release-note-none, Contributor

#24259 Improve websocket logging
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: 4: Reviews Complete, release-note-none

#24211 [MM-53840] Add migration workflow
  .github/workflows/migration.yml
  .github/workflows/server-ci-template.yml
  .gitignore
  server/Makefile
  server/build/dotenv/migration.env
  server/build/dotenv/test.env
  server/scripts/wait-for-system-start.sh
  server/tests/template.load
Labels: 4: Reviews Complete, release-note-none

#24260 chore(e2e): Remove ReduceOnBoardingTaskList from e2e config
  e2e-tests/playwright/support/server/default_config.ts
Labels: release-note-none

#24237 Fix MM-53949
  server/channels/app/app_iface.go
  server/channels/app/draft.go
  server/channels/app/draft_test.go
  server/channels/app/file.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, release-note-none

#24218 Trims whitespace from command arguments in RootCmd
  server/cmd/mmctl/commands/root.go
  server/cmd/mmctl/commands/root_test.go
Labels: 3: QA Review, release-note, Contributor

#24295 Automated cherry pick of #22637
  app/platform/web_conn.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24277 config-reset: -tags production
  server/Makefile
Labels: CherryPick/Approved, release-note

#24286 MM-54158: S3PathMigration: Re-initialize stop chan
  server/channels/jobs/s3_path_migration/s3_path_migration.go
Labels: 4: Reviews Complete, release-note-none

#24298 Automated cherry pick of #24277
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24301 Automated cherry pick of #24225
  server/channels/api4/plugin_test.go
  server/channels/app/channels.go
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_install_test.go
  server/channels/app/plugin_test.go
  server/public/plugin/environment.go
  server/tests/README.md
  server/tests/testplugin-v0.0.2.tar.gz
  server/tests/testplugin-v0.0.2.tar.gz.asc
  server/tests/testplugin-v0.0.2.tar.gz.sig
  server/tests/testplugin.tar.gz.asc
  server/tests/testplugin.tar.gz.sig
  server/tests/testplugin2.tar.gz.asc
  server/tests/testplugin2.tar.gz.sig
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24177 MM-53764 - Fix: Improve limits on Opengraph Data Cache
  api/Makefile
  api/v4/source/opengraph.yaml
  server/channels/api4/api.go
  server/channels/api4/openGraph.go
  server/channels/api4/openGraph_test.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note

#24302 Automated cherry pick of #24177
  api/Makefile
  api/v4/source/opengraph.yaml
  server/channels/api4/api.go
  server/channels/api4/openGraph.go
  server/channels/api4/openGraph_test.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/platform/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#23530 [MM-32576] Text copied from Microsoft OneNote pastes as an image (v2)
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/paste_image_spec.js
  webapp/channels/src/components/file_upload/file_upload.test.tsx
  webapp/channels/src/components/file_upload/file_upload.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#24306 Automated cherry pick of #24286
  server/channels/jobs/s3_path_migration/s3_path_migration.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24263 MM-53924 - Implement NotificationWillBePushed plugin hook
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/test_templates/hook_notification_will_be_pushed.tmpl
  server/public/model/plugin_push_notification.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#24309 Automated cherry pick of #24263
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/test_templates/hook_notification_will_be_pushed.tmpl
  server/public/model/plugin_push_notification.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24310 Automated cherry pick of #24273
  server/channels/app/notification_push.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_test.go
  server/public/model/plugin_push_notification.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/plugintest/api.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24236 Replace Gfycat with GIPHY in emoji/gif picker
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/gif_picker/components/App/index.tsx
  webapp/channels/src/components/gif_picker/components/Categories/index.tsx
  webapp/channels/src/components/gif_picker/components/Header/index.tsx
  webapp/channels/src/components/gif_picker/components/Search/index.tsx
  webapp/channels/src/components/gif_picker/components/Trending/index.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_search.tsx
  webapp/channels/src/components/gif_picker/gif_picker.tsx
  webapp/channels/src/components/widgets/icons/giphy_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/gif_picker/powered-by-giphy-black.png
  webapp/channels/src/images/gif_picker/powered-by-giphy-white.png
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note

#24312 Automated cherry pick of #24236
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/gif_picker/components/App/index.tsx
  webapp/channels/src/components/gif_picker/components/Categories/index.tsx
  webapp/channels/src/components/gif_picker/components/Header/index.tsx
  webapp/channels/src/components/gif_picker/components/Search/index.tsx
  webapp/channels/src/components/gif_picker/components/Trending/index.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_search.tsx
  webapp/channels/src/components/gif_picker/gif_picker.tsx
  webapp/channels/src/components/widgets/icons/giphy_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/gif_picker/powered-by-giphy-black.png
  webapp/channels/src/images/gif_picker/powered-by-giphy-white.png
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/platform/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24264 Use generics in utils.Merge
  server/channels/utils/merge.go
  server/channels/utils/merge_test.go
  server/config/utils.go
Labels: 4: Reviews Complete, release-note-none

#24200 MM-53879: Fix recursive loading of license
  server/channels/api4/system.go
  server/channels/api4/user_test.go
  server/channels/app/admin.go
  server/channels/app/license.go
  server/channels/app/license_test.go
  server/channels/app/notification_test.go
  server/channels/app/oauth.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/platform/license.go
  server/channels/app/platform/license_test.go
  server/channels/app/platform/service.go
  server/channels/app/server.go
  server/cmd/mattermost/commands/init.go
  server/cmd/mattermost/commands/jobserver.go
  server/public/model/cluster_message.go
Labels: 4: Reviews Complete, release-note

#24292 Updates post text processing to fetch nonexisting custom groups
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/search.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#24288 Add missing return
  server/channels/api4/post.go
Labels: 4: Reviews Complete, release-note-none

#24321 Run make modules-tidy
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none

#24287 fixed initialism errors in accordance with golang conventions in 7 files.
  server/channels/app/import_functions_test.go
  server/channels/app/post_metadata_test.go
  server/channels/utils/file.go
  server/channels/utils/file_test.go
  server/platform/services/httpservice/client.go
  server/platform/services/httpservice/client_test.go
  server/platform/services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#24319 [MM-54183] Remove deprecated Manifest.RequiredConfig field
  server/public/model/manifest.go
Labels: 4: Reviews Complete, Docs/Done, release-note

#24296 [MM-54160] postgres migration: preserve index names and a couple of fixes
  server/tests/template.load
Labels: 4: Reviews Complete, release-note-none

#24320 [MM-54014] Run tests in public/...
  server/Makefile
  server/public/model/config_test.go
  server/public/model/service_environment_test.go
  server/public/plugin/environment_test.go
  server/public/pluginapi/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#24324 Automated cherry pick of #24292
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/search.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
  webapp/platform/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24314 Sync giphy package versions in package-lock.json file
  webapp/package-lock.json
Labels: 2: Dev Review, EETests, release-note-none, Contributor

#24282 MM-53999 Fix keyboard support for Menu components
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  e2e-tests/playwright/support/ui/components/channels/post_dot_menu.ts
  e2e-tests/playwright/support/ui/components/channels/post_menu.ts
  e2e-tests/playwright/support/ui/components/channels/post_reminder_menu.ts
  e2e-tests/playwright/support/ui/components/channels/sidebar_right.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/pages/channels.ts
  e2e-tests/playwright/tests/accessibility/channels/intro_channel.spec.ts
  e2e-tests/playwright/tests/functional/channels/drafts/drafts_on_deleted_message.spec.ts
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts
  webapp/channels/src/components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  webapp/channels/src/components/dot_menu/dot_menu.tsx
  webapp/channels/src/components/dot_menu/post_reminder_submenu.tsx
  webapp/channels/src/components/menu/menu.tsx
  webapp/channels/src/components/menu/menu_item.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/create_new_category_menu_item.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/mark_as_read_menu_item.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24339 Cherry pick MM-53842 to v8.0
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/gif_picker/components/App/index.tsx
  webapp/channels/src/components/gif_picker/components/Categories/index.tsx
  webapp/channels/src/components/gif_picker/components/Header/index.tsx
  webapp/channels/src/components/gif_picker/components/Search/index.tsx
  webapp/channels/src/components/gif_picker/components/Trending/index.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_search.tsx
  webapp/channels/src/components/gif_picker/gif_picker.tsx
  webapp/channels/src/components/widgets/icons/giphy_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/gif_picker/powered-by-giphy-black.png
  webapp/channels/src/images/gif_picker/powered-by-giphy-white.png
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24345 Automated cherry pick of #24200
  server/channels/api4/system.go
  server/channels/api4/user_test.go
  server/channels/app/admin.go
  server/channels/app/license.go
  server/channels/app/license_test.go
  server/channels/app/notification_test.go
  server/channels/app/oauth.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/platform/license.go
  server/channels/app/platform/license_test.go
  server/channels/app/platform/service.go
  server/channels/app/server.go
  server/cmd/mattermost/commands/init.go
  server/cmd/mattermost/commands/jobserver.go
  server/public/model/cluster_message.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24341 Bumping up migration number to 111
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000111_update_vacuuming.down.sql
  server/channels/db/migrations/mysql/000111_update_vacuuming.up.sql
  server/channels/db/migrations/postgres/000111_update_vacuuming.down.sql
  server/channels/db/migrations/postgres/000111_update_vacuuming.up.sql
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#24347 Automated cherry pick of #24341
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000111_update_vacuuming.down.sql
  server/channels/db/migrations/mysql/000111_update_vacuuming.up.sql
  server/channels/db/migrations/postgres/000111_update_vacuuming.down.sql
  server/channels/db/migrations/postgres/000111_update_vacuuming.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24330 update prepackaged boards to v7.11.3
  server/Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note

#24352 Automated cherry pick of #24330
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24265 Add support for actions in the unreads bar from plugins
  webapp/channels/src/components/post_view/new_message_separator/new_message_separator.test.tsx
  webapp/channels/src/components/post_view/new_message_separator/new_message_separator.tsx
  webapp/channels/src/components/post_view/post_list_row/__snapshots__/post_list_row.test.tsx.snap
  webapp/channels/src/components/post_view/post_list_row/index.ts
  webapp/channels/src/components/post_view/post_list_row/post_list_row.test.tsx
  webapp/channels/src/components/post_view/post_list_row/post_list_row.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/index.ts
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/components/widgets/separator/notification-separator.scss
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/types/store/plugins.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#24300 Pre-package Playbooks v1.38.1
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, QA/Tests Not Required, release-note

#24358 Automated cherry pick of #24300
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24359 Automated cherry pick of #24344
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24334 MM-54211 Fix Unreads category being visible with no unread channels
  webapp/channels/src/components/sidebar/sidebar.test.tsx
  webapp/channels/src/components/sidebar/unread_channels.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#24361 Automated cherry pick of #24334
  webapp/channels/src/components/sidebar/sidebar.test.tsx
  webapp/channels/src/components/sidebar/unread_channels.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24350 MM-53924 - Implement push notifications plugin hook and plugin api method
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/test_templates/hook_notification_will_be_pushed.tmpl
  server/public/model/plugin_push_notification.go
  server/public/model/push_notification.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/api.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#24366 Automated cherry pick of #24350
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/test_templates/hook_notification_will_be_pushed.tmpl
  server/public/model/plugin_push_notification.go
  server/public/model/push_notification.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/api.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24365 Update version to 8.1.1
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24346 Cherrypick of "MM-53879: Fix recursive loading of license (#24200)"
  server/channels/api4/system.go
  server/channels/api4/user_test.go
  server/channels/app/admin.go
  server/channels/app/license.go
  server/channels/app/license_test.go
  server/channels/app/notification_test.go
  server/channels/app/oauth.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/platform/license.go
  server/channels/app/platform/license_test.go
  server/channels/app/platform/service.go
  server/channels/app/server.go
  server/cmd/mattermost/commands/init.go
  server/cmd/mattermost/commands/jobserver.go
  server/public/model/cluster_message.go
Labels: 4: Reviews Complete, 2: Dev Review, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24364 Update minor version to 9.0.0
  server/public/model/version.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note-none

#24368 Automated cherry pick of #23751
  server/channels/api4/bot_test.go
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24369 Automated cherry pick of #24277
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24370 Automated cherry pick of #23530
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/paste_image_spec.js
  webapp/channels/src/components/file_upload/file_upload.test.tsx
  webapp/channels/src/components/file_upload/file_upload.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24371 Cherry pick (#24059) into release-8.0
  server/channels/api4/team.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/team.go
  server/channels/app/team_test.go
  webapp/channels/src/components/cloud_subscribe_with_loading_modal/index.tsx
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.scss
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/teams.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24372 [MM-53702] Remove Downgrade Team Selection modal and all accompanying…
  server/channels/api4/team.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/team.go
  server/channels/app/team_test.go
  webapp/channels/src/components/cloud_subscribe_with_loading_modal/index.tsx
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.scss
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
  webapp/channels/src/components/pricing_modal/downgrade_team_removal_modal/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/teams.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24373 backport
  api4/team.go
  app/app_iface.go
  app/opentracing/opentracing_layer.go
  app/team.go
  app/team_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24367 Automated cherry pick of #23751
  api4/bot_test.go
  api4/user.go
  api4/user_test.go
  app/authorization.go
  app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24374 Automated cherry pick of #24364
  server/public/model/version.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24340 Cherry pick MM-53842 to v8.1
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/gif_picker/components/App/index.tsx
  webapp/channels/src/components/gif_picker/components/Categories/index.tsx
  webapp/channels/src/components/gif_picker/components/Header/index.tsx
  webapp/channels/src/components/gif_picker/components/Search/index.tsx
  webapp/channels/src/components/gif_picker/components/Trending/index.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_search.tsx
  webapp/channels/src/components/gif_picker/gif_picker.tsx
  webapp/channels/src/components/widgets/icons/giphy_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/gif_picker/powered-by-giphy-black.png
  webapp/channels/src/images/gif_picker/powered-by-giphy-white.png
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#24377 Automated cherry pick of #24118
  e2e-tests/cypress/tests/support/api/role.js
  server/channels/api4/channel.go
  server/channels/api4/file.go
  server/channels/api4/integration_action.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/user.go
  server/channels/api4/webhook.go
  server/channels/app/app_test.go
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
  server/channels/app/permissions_migrations.go
  server/channels/app/post.go
  server/channels/app/webhook.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/storetest/scheme_store.go
  server/channels/testlib/store.go
  server/public/model/migration.go
  server/public/model/permission.go
  server/public/model/role.go
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/index.tsx
  webapp/channels/src/packages/mattermost-redux/src/constants/permissions.ts
  webapp/channels/src/utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24378 Automated cherry pick of #24118
  e2e-tests/cypress/tests/support/api/role.js
  server/channels/api4/channel.go
  server/channels/api4/file.go
  server/channels/api4/integration_action.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/user.go
  server/channels/api4/webhook.go
  server/channels/app/app_test.go
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
  server/channels/app/permissions_migrations.go
  server/channels/app/post.go
  server/channels/app/webhook.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/storetest/scheme_store.go
  server/channels/testlib/store.go
  server/public/model/migration.go
  server/public/model/permission.go
  server/public/model/role.go
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/index.tsx
  webapp/channels/src/packages/mattermost-redux/src/constants/permissions.ts
  webapp/channels/src/utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24380 Improve websocket logging (#24259)
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24376 Add read_channel_content permission
  api4/channel.go
  api4/file.go
  api4/integration_action.go
  api4/post.go
  api4/preference.go
  api4/reaction.go
  api4/user.go
  api4/webhook.go
  app/app_test.go
  app/authorization.go
  app/authorization_test.go
  app/permissions_migrations.go
  app/post.go
  app/webhook.go
  model/migration.go
  model/permission.go
  model/role.go
  store/sqlstore/integrity_test.go
  store/storetest/scheme_store.go
  testlib/store.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#24336 Upgrade & verify prepackaged plugins in prep for remote marketplace decommissioning.
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#24386 Automated cherry pick of #24336
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#24311 MM-52981, MM-53559: Streamlined in-product marketplace
  .github/workflows/mmctl-test-template.yml
  e2e-tests/cypress/tests/integration/channels/plugins/marketplace/ui_spec.js
  e2e-tests/playwright/support/server/default_config.ts
  server/Makefile
  server/channels/api4/plugin_test.go
  server/channels/api4/system_test.go
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/plugin_management/index.ts
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.test.tsx
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
  webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.scss
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.test.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
  webapp/channels/src/components/plugin_marketplace/web_marketplace_banner.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/images/icons/confluence.svg
  webapp/channels/src/images/icons/giphy.svg
  webapp/channels/src/images/icons/pager-duty.svg
  webapp/channels/src/images/marketplace-notice-background.jpg
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/platform/components/src/generic_modal/generic_modal.scss
  webapp/platform/components/src/generic_modal/generic_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#24362 Sanitize user in update user response
  server/channels/app/user.go
  server/channels/app/user_test.go
Labels: 2: Dev Review, release-note-none

#23724 [MM-22133] Allow exporting and importing archived channels
  server/channels/app/export.go
  server/channels/app/export_converters.go
  server/channels/app/export_test.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/imports/import_types.go
  server/channels/jobs/export_process/worker.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mattermost/commands/export.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/docs/mmctl_export_create.rst
  server/i18n/en.json
  server/public/model/bulk_export.go
Labels: 4: Reviews Complete, release-note-none

#24206 Add additional unit test for bot/user access
  server/channels/app/authorization_test.go
Labels: 4: Reviews Complete, release-note-none

#24390 MM-53165 Add X-Forwarded-For header to audit for rest api calls
  server/channels/app/audit.go
  server/channels/app/request/context.go
  server/channels/audit/audit_test.go
  server/channels/audit/record.go
  server/channels/web/context.go
  server/channels/web/handlers.go
Labels: release-note

#24385 CLD-6206 - Mirror node18 images
  server/scripts/mirror-docker-images.json
Labels: release-note-none

#24317 [MM-53333] Modified the delete category modal to contain a cancel button #24290
  webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
Labels: 2: Dev Review, 3: QA Review, release-note, Contributor

#24375 MM-52959 Update help text
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#24283 MM-53989 Upgrade to Node 18 and NPM 9
  .nvmrc
  e2e-tests/.ci/server.override.yml
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/scripts/skip_integrity_check.js
Labels: 4: Reviews Complete, release-note-none

#24383 Fixes config path for config-ldap make target
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#24413 Update supported Chromium version
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Done, Changelog/Done, AutoMerge, release-note

#24047 Add config setting to set default User Setting for filter join/leave message
  server/config/client.go
  server/config/client_test.go
  server/public/model/config.go
  server/public/model/config_test.go
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#24396 MM-54261: re-scope css to intended target
  webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
  webapp/channels/src/components/post_edit_history/post_edit_history.scss
  webapp/channels/src/components/post_edit_history/post_edit_history.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#24348 Add code block actions plugin extensibility
  webapp/channels/src/components/code_block/__snapshots__/code_block.test.tsx.snap
  webapp/channels/src/components/code_block/code_block.test.tsx
  webapp/channels/src/components/code_block/code_block.tsx
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/types/store/plugins.ts
Labels: release-note

#20894 Add UserHasBeenDeactivated plugin hook
  server/channels/app/plugin_hooks_test.go
  server/channels/app/user.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/plugintest/hooks.go
  server/public/plugin/product_hooks_generated.go
Labels: 4: Reviews Complete, QA Deferred, release-note, Contributor

#24405 [MM-52088] Fix flaky draft tests
  server/channels/api4/drafts_test.go
  server/channels/app/draft_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#24424 Automated cherry pick of #24396
  webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
  webapp/channels/src/components/post_edit_history/post_edit_history.scss
  webapp/channels/src/components/post_edit_history/post_edit_history.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#24140 [MM-37984] Allow Desktop App to authenticate via external providers outside of the app on supported servers
  server/channels/api4/handlers.go
  server/channels/api4/user.go
  server/channels/app/app_iface.go
  server/channels/app/desktop_login.go
  server/channels/app/desktop_login_test.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/server.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000112_rework_desktop_tokens.down.sql
  server/channels/db/migrations/mysql/000112_rework_desktop_tokens.up.sql
  server/channels/db/migrations/postgres/000112_rework_desktop_tokens.down.sql
  server/channels/db/migrations/postgres/000112_rework_desktop_tokens.up.sql
  server/channels/jobs/cleanup_desktop_tokens/scheduler.go
  server/channels/jobs/cleanup_desktop_tokens/worker.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/retrylayer/retrylayer_test.go
  server/channels/store/sqlstore/desktop_tokens_store.go
  server/channels/store/sqlstore/desktop_tokens_store_test.go
  server/channels/store/sqlstore/store.go
  server/channels/store/store.go
  server/channels/store/storetest/desktop_tokens_store.go
  server/channels/store/storetest/mocks/DesktopTokensStore.go
  server/channels/store/storetest/mocks/Store.go
  server/channels/store/storetest/store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/oauth.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/job.go
  server/public/model/user.go
  webapp/channels/src/actions/views/login.ts
  webapp/channels/src/components/desktop_auth_token.scss
  webapp/channels/src/components/desktop_auth_token.tsx
  webapp/channels/src/components/external_login_button/external_login_button.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#24400 MM-53410: Avoid antijoin for channelstore.channelSearchQuery
  server/channels/store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#24401 MM-49627: Suppress transformation of embedded images via image proxy
  server/channels/app/post_metadata.go
  server/platform/services/imageproxy/imageproxy.go
  server/platform/services/imageproxy/imageproxy_test.go
Labels: 4: Reviews Complete, release-note-none

#23117 MM-27936: Allow resizing the channel sidebar and right-hand sidebar
  webapp/channels/src/actions/views/lhs.ts
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/hooks.tsx
  webapp/channels/src/components/resizable_sidebar/constants.ts
  webapp/channels/src/components/resizable_sidebar/resizable_divider.tsx
  webapp/channels/src/components/resizable_sidebar/resizable_lhs/index.tsx
  webapp/channels/src/components/resizable_sidebar/resizable_rhs/index.tsx
  webapp/channels/src/components/resizable_sidebar/utils.ts
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar.tsx
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/components/window_size_observer/WindowSizeObserver.tsx
  webapp/channels/src/reducers/views/lhs.test.ts
  webapp/channels/src/reducers/views/lhs.ts
  webapp/channels/src/reducers/views/rhs.test.js
  webapp/channels/src/reducers/views/rhs.ts
  webapp/channels/src/sass/layout/_sidebar-left.scss
  webapp/channels/src/sass/layout/_sidebar-right.scss
  webapp/channels/src/sass/responsive/_desktop.scss
  webapp/channels/src/sass/utils/_mixins.scss
  webapp/channels/src/selectors/lhs.ts
  webapp/channels/src/selectors/rhs.ts
  webapp/channels/src/stores/hooks.ts
  webapp/channels/src/types/store/lhs.ts
  webapp/channels/src/types/store/rhs.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#24398 Move .editorconfig to repo root
  .editorconfig
  server/.editorconfig
Labels: 4: Reviews Complete, release-note-none

#24355 Adding SetFileSearchableContent plugin API endpoint
  server/channels/app/app_iface.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/post.go
  server/i18n/en.json
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/file.go
Labels: 2: Dev Review, release-note

#24099 MM-46494: Add filter options to browse channel modal
  e2e-tests/cypress/tests/integration/channels/channel/archived_channels_1_spec.js
  e2e-tests/cypress/tests/integration/channels/channel/browse_channels_spec.js
  e2e-tests/cypress/tests/integration/channels/channel/browse_public_channels_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_group_sync_spec.js
  webapp/channels/package.json
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap
  webapp/channels/src/components/browse_channels/__snapshots__/browse_channels.test.tsx.snap
  webapp/channels/src/components/browse_channels/browse_channels.scss
  webapp/channels/src/components/browse_channels/browse_channels.test.tsx
  webapp/channels/src/components/browse_channels/browse_channels.tsx
  webapp/channels/src/components/browse_channels/index.ts
  webapp/channels/src/components/searchable_channel_list.test.tsx
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
  webapp/channels/src/components/sidebar/sidebar.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  webapp/channels/src/i18n/en.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note, Contributor

#24395 Remove unnecessary mmctl enterprise deps
  server/cmd/mmctl/commands/enterprise.go
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none

#22597 Restore previously archived groups
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/group.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/storetest/group_store.go
  server/channels/web/params.go
  server/public/model/client4.go
  server/public/model/group.go
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/no_results_indicator/no_results_indicator.tsx
  webapp/channels/src/components/no_results_indicator/types.ts
  webapp/channels/src/components/post_markdown/index.ts
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
  webapp/channels/src/components/user_groups_modal/ad_ldap_upsell_banner.tsx
  webapp/channels/src/components/user_groups_modal/hooks.ts
  webapp/channels/src/components/user_groups_modal/index.ts
  webapp/channels/src/components/user_groups_modal/user_groups_filter/user_groups_filter.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_list/__snapshots__/user_groups_list.test.tsx.snap
  webapp/channels/src/components/user_groups_modal/user_groups_list/index.ts
  webapp/channels/src/components/user_groups_modal/user_groups_list/user_groups_list.test.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_list/user_groups_list.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal.scss
  webapp/channels/src/components/user_groups_modal/user_groups_modal.test.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal.tsx
  webapp/channels/src/components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/index.ts
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/search.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/group_utils.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/groups.ts
Labels: 4: Reviews Complete, release-note

#24335 MM-54191 Change how menu item click handlers are triggered after menus fully close
  webapp/channels/package.json
  webapp/channels/src/components/menu/menu.test.tsx
  webapp/channels/src/components/menu/menu.tsx
  webapp/channels/src/components/menu/menu_context.ts
  webapp/channels/src/components/menu/menu_item.tsx
  webapp/channels/src/components/menu/sub_menu.tsx
  webapp/channels/src/components/new_channel_modal/new_channel_modal.test.tsx
  webapp/package-lock.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#24394 Update Prepackaged GitLab plugin to 1.7.0
  server/Makefile
Labels: 4: Reviews Complete, release-note

#24430 updates on the migration template
  server/tests/template.load
Labels: 4: Reviews Complete, release-note-none

#24432 Cherry pick MM-54275 to v8.1
  server/Makefile
  server/config/client.go
  server/config/client_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24414 MM-53107 Add setting to limit the max number of markdown nodes
  server/config/client.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.jsx
  webapp/channels/src/components/admin_console/schema_admin_settings.jsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#24409 Cherry pick MM-54275 to v8.0
  server/Makefile
  server/config/client.go
  server/config/client_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24402 MM-54173 group mention punctuation
  webapp/channels/src/components/at_mention/__snapshots__/at_mention.test.tsx.snap
  webapp/channels/src/components/at_mention/at_mention.test.tsx
  webapp/channels/src/components/at_mention/at_mention.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note, Contributor

#24434 Cherry pick MM-54275 to v9.0
  server/Makefile
  server/config/client.go
  server/config/client_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#24435 Cherry pick MM-54275 to Cloud
  server/Makefile
  server/config/client.go
  server/config/client_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none
