Repository mattermost/mattermost, pull requests merged in 2024-07, with the labels that each got.

#27244 [MM-58405] Migrate tooltips of 'components/announcement_bar/default_announcement_bar/announcement_bar' to WithTooltip
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/with_tooltip/index.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#27242 [MM-58509] Migrate tooltips of "components/admin_console/user_grid/user_grid_role_dropdown.tsx" to WithTooltip
  webapp/channels/src/components/admin_console/user_grid/user_grid_role_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27462 chore: update package metadata for API reference
  api/package.json
Labels: 4: Reviews Complete, EETests, QA/Review Not Required, release-note-none

#27482 [MM-58840] Add routing restrictions
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: QA/Deferred, 3: Security Review, release-note-none

#27468 MM-58837 - Require permission to user to mark channels as read
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
Labels: 2: Dev Review, release-note-none

#27390 [MM-58796] Print panic message when mmctl panics
  server/cmd/mmctl/commands/root.go
  server/cmd/mmctl/commands/root_test.go
  server/cmd/mmctl/printer/printer.go
Labels: 4: Reviews Complete, release-note

#27494 [MM-59274] Potential for panic in app migrations
  server/channels/app/migrations.go
Labels: 4: Reviews Complete, release-note-none

#27512 Automated cherry pick of #27170
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/shared_channel.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27513 Automated cherry pick of #27170
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/shared_channel.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27516 Automated cherry pick of #27170
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/shared_channel.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27517 Automated cherry pick of #27482
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27520 Automated cherry pick of #27482
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27514 Automated cherry pick of #27170
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/shared_channel.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27518 Automated cherry pick of #27482
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27521 Automated cherry pick of #27427
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27522 Automated cherry pick of #27427
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27519 Automated cherry pick of #27482
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27523 Automated cherry pick of #27468
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27524 Automated cherry pick of #27468
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27506 [chore] migration of plugin-store
  server/Makefile
  server/build/release.mk
  server/cmd/mmctl/commands/plugin_e2e_test.go
Labels: release-note-none

#27528 Automated cherry pick of #27428
  webapp/channels/src/components/threading/global_threads/global_threads.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27495 MM-56774: Delete file along with bookmark
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/storetest/channel_bookmark.go
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#27353 [MM-58686] Adjust text alignment on custom status tooltip
  webapp/channels/src/components/custom_status/custom_status.scss
  webapp/channels/src/components/custom_status/custom_status_emoji.tsx
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none, Contributor

#27530 MM-58525 Fix upload file permissions (#27298)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27531 MM-58525 Fix upload file permissions (#27298)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27532 MM-58525 Fix upload file permissions (#27298)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27507 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/pl.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/sr.json
Labels: release-note-none, Do Not Merge/Mattermod

#27481 MM-58771 - Make manage_server permission, non updatable
  server/channels/api4/role.go
  server/channels/api4/role_test.go
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#27538 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, 2. Editor review

#27449 [MM-57942] Fix a panic on password is too long
  server/channels/app/user.go
  server/channels/app/users/password.go
  server/channels/app/users/password_test.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/storetest/user_store.go
  server/i18n/en.json
  server/public/model/user.go
  server/public/model/user_test.go
Labels: 4: Reviews Complete, release-note

#27432 Adds Remote Cluster related API endpoints
  api/Makefile
  api/v4/source/definitions.yaml
  api/v4/source/introduction.yaml
  api/v4/source/remoteclusters.yaml
  server/channels/api4/apitestlib.go
  server/channels/api4/remote_cluster.go
  server/channels/api4/remote_cluster_test.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/remote_cluster.go
  server/channels/app/slashcommands/command_remote.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/RemoteClusterStore.go
  server/channels/store/storetest/remote_cluster_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/remotecluster/invitation.go
  server/platform/services/remotecluster/mocks_test.go
  server/platform/services/remotecluster/ping.go
  server/platform/services/remotecluster/sendmsg.go
  server/platform/services/remotecluster/service.go
  server/platform/services/sharedchannel/sync_send.go
  server/public/model/client4.go
  server/public/model/remote_cluster.go
Labels: 2: Dev Review, release-note

#27543 Automated cherry pick of #27481
  server/channels/api4/role.go
  server/channels/api4/role_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27544 Automated cherry pick of #27481
  server/channels/api4/role.go
  server/channels/api4/role_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27545 Automated cherry pick of #27481
  server/channels/api4/role.go
  server/channels/api4/role_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27546 Automated cherry pick of #27481
  server/channels/api4/role.go
  server/channels/api4/role_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27547 Skips flaky test on the remote cluster API
  server/channels/api4/remote_cluster_test.go
Labels: 4: Reviews Complete, release-note-none

#27540 [MM-57738] Revert "Added GetPluginID method and tests (#27281)"
  server/public/model/manifest.go
  server/public/model/manifest_test.go
Labels: 4: Reviews Complete, release-note-none

#27185 [MM-58443] Migrate tooltips of 'components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx' to WithTooltip
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/__snapshots__/saved_posts_button.test.tsx.snap
  webapp/channels/src/components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#27490 Update Packet metadata generation based on feedback
  server/channels/app/plugin_api.go
  server/public/model/metadata.go
  server/public/model/metadata_test.go
  server/public/model/packet_metadata.go
  server/public/model/packet_metadata_test.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/system.go
  server/public/pluginapi/system_test.go
Labels: 4: Reviews Complete, release-note-none

#27460 Add platform information for push notification metrics
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/expirynotify.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/reaction.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/wsapi/system.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/notification.go
Labels: 4: Reviews Complete, release-note

#27548 Orders results of the GetAll remote clusters store method
  server/channels/api4/remote_cluster_test.go
  server/channels/store/sqlstore/remote_cluster_store.go
Labels: 4: Reviews Complete, release-note-none

#27533 MM-58525 Fix upload file permissions (#27298)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27361 MM-57824: Export/import custom status
  server/channels/app/export.go
  server/channels/app/export_test.go
  server/channels/app/import_functions.go
  server/channels/app/imports/import_types.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#26518 chore: fixes and updates keycloak development environment
  server/Makefile
  server/build/docker-compose.common.yml
  server/build/docker/keycloak/README.md
  server/build/docker/keycloak/ldap.mmsettings.json
  server/build/docker/keycloak/openid.mmsettings.json
  server/build/docker/keycloak/realm-export.json
  server/build/docker/keycloak/saml.mmsettings.json
Labels: 2: Dev Review, kind/bug, release-note

#26647 Correctly merge plugin configuration on mmctl config patch
  server/cmd/mmctl/commands/config.go
  server/cmd/mmctl/commands/config_test.go
  server/cmd/mmctl/commands/utils.go
  server/cmd/mmctl/commands/utils_test.go
Labels: 4: Reviews Complete, QA/Deferred, release-note

#27586 Translations update from Mattermost Weblate
  server/i18n/be.json
  server/i18n/bg.json
  server/i18n/cs.json
  server/i18n/de.json
  server/i18n/el.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/fa.json
  server/i18n/fr.json
  server/i18n/hi.json
  server/i18n/hu.json
  server/i18n/id.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/ko.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/ro.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/vi.json
  server/i18n/zh-CN.json
  server/i18n/zh-TW.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#27433 [MM-58856] Migrate tooltips of "components/copy_button.tsx" to WithTooltip
  webapp/channels/src/components/copy_button.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27388 [MM-58003] Allow setting AdvancedLoggingJSON via mmctl
  server/cmd/mmctl/commands/config.go
  server/cmd/mmctl/commands/config_test.go
Labels: 4: Reviews Complete, release-note

#26836 [MM-57963] Log Name and DisplayName of groups
  server/public/model/builtin.go
  server/public/model/builtin_test.go
  server/public/model/group.go
  server/public/model/group_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, Tests/Not Needed, release-note

#26860 [MM-58004] Update logged fields of users
  server/channels/audit/audit_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: 4: Reviews Complete, release-note

#27446 [MM-56339] Audit logs: on login add UserId and SessionId to audit's Actor field
  server/channels/api4/user_test.go
  server/channels/utils/merge_test.go
  server/channels/web/context.go
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: 4: Reviews Complete, release-note

#27572 Bump prepackage Github plugin version to 2.3.0
  server/Makefile
Labels: 4: Reviews Complete, release-note

#27591 Don't modify global variables in TestNoticeValidation
  server/channels/app/product_notices.go
  server/channels/app/product_notices_test.go
Labels: 4: Reviews Complete, release-note-none

#27499 chore(deps): remove dup stylelint depdendencies in webapp/channels
  NOTICE.txt
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#27577 MM-59345 add hover states expandable containers in workspace optimization page
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#27395 MM-58548 Remove manage_team permissions from System Console Ancillary permissions
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.up.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.up.sql
  server/public/model/role.go
Labels: QA/Deferred, release-note-none

#27600 Automated cherry pick of #27395
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.up.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.up.sql
  server/public/model/role.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27601 Automated cherry pick of #27395
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.up.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.up.sql
  server/public/model/role.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27599 Automated cherry pick of #27395
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/mysql/000124_remove_manage_team_permission.up.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.down.sql
  server/channels/db/migrations/postgres/000124_remove_manage_team_permission.up.sql
  server/public/model/role.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27606 Automated cherry pick of #27393
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.cloud_init.sh
  e2e-tests/.ci/server.cloud_teardown.sh
  e2e-tests/README.md
  e2e-tests/cypress/save_report.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27484 MM-58535 Add more information to LCP and INP metrics
  server/channels/app/metrics.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/metrics.go
  webapp/channels/jest.config.js
  webapp/channels/package.json
  webapp/channels/src/components/__snapshots__/file_upload_overlay.test.tsx.snap
  webapp/channels/src/components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.tsx.snap
  webapp/channels/src/components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.tsx.snap
  webapp/channels/src/components/admin_console/openid_convert/__snapshots__/openid_convert.test.tsx.snap
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.test.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  webapp/channels/src/components/file_info_preview/__snapshots__/file_info_preview.test.tsx.snap
  webapp/channels/src/components/integrations/bots/add_bot/__snapshots__/add_bot.test.tsx.snap
  webapp/channels/src/components/markdown_image/__snapshots__/markdown_image.test.tsx.snap
  webapp/channels/src/components/onboarding_tasklist/__snapshots__/onboarding_tasklist_completed.test.tsx.snap
  webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/__snapshots__/custom_theme_chooser.test.tsx.snap
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.ts
  webapp/channels/src/tests/image_url_mock.json
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/tests/setup_jest.ts
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/performance_telemetry/element_identification.test.tsx
  webapp/channels/src/utils/performance_telemetry/element_identification.ts
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#27060 [MM-56921] Rendered Latex in Codeblock when rendering disabled
  webapp/channels/src/components/code_block/code_block.tsx
  webapp/channels/src/components/latex_block/__snapshots__/latex_block.test.tsx.snap
  webapp/channels/src/components/latex_block/latex_block.test.tsx
  webapp/channels/src/components/latex_block/latex_block.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#27504 MM-58776 - Change Ancillary Permissions API to POST
  api/v4/source/permissions.yaml
  server/channels/api4/permission.go
  server/public/model/client4.go
  webapp/platform/client/src/client4.ts
Labels: QA/Review Done, release-note

#27587 Support release testing
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.start.sh
Labels: release-note-none

#24399 MM-53962: Adding ES8 dependency
  e2e-tests/.ci/server.generate.sh
  e2e-tests/playwright/support/server/default_config.ts
  server/build/Dockerfile.opensearch
  server/build/docker-compose-generator/main.go
  server/build/docker-compose.common.yml
  server/build/docker-compose.yml
  server/channels/jobs/jobs.go
  server/cmd/mmctl/commands/enterprise.go
  server/docker-compose.makefile.m1.yml
  server/docker-compose.makefile.yml
  server/docker-compose.yaml
  server/go.mod
  server/go.sum
  server/i18n/en.json
  server/public/model/builtin.go
  server/public/model/config.go
  server/tests/test-config.json
  webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, QA/Review Done, EETests, release-note

#27613 MM-58245 Don't allow patching real email or username for remote users
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, release-note-none

#27619 Automated cherry pick of #27613
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27621 Automated cherry pick of #27613
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27622 Automated cherry pick of #27613
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27160 MM-58351 Fix showing LHS scrollbar when moving mouse over on chrome and safari
  webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#27385 [MM-58778] Fixing white screen for GM conversion
  webapp/channels/src/components/post_view/gm_conversion_message/gm_conversion_message.tsx
  webapp/channels/src/i18n/en.json
Labels: 3: QA Review, release-note

#27624 [feat] adding container image scanning
  .github/workflows/server-ci-artifacts.yml
Labels: 2: Dev Review, Tech/DevOps, 3: Security Review, release-note-none

#27583 Sysadmin manage user settings
  server/channels/api4/report.go
  server/channels/app/user.go
  server/channels/app/users/utils.go
  server/channels/store/sqlstore/post_store.go
  server/public/model/report.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/admin_console/admin_user_card/admin_user_card.scss
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/index.ts
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.scss
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.test.tsx
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirmManageUserSettingsModal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/components/confirm_modal_redux/confirm_modal_redux.tsx
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.tsx
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/index.ts
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/manage_languages/index.ts
  webapp/channels/src/components/user_settings/display/manage_languages/manage_languages.test.tsx
  webapp/channels/src/components/user_settings/display/manage_languages/manage_languages.tsx
  webapp/channels/src/components/user_settings/display/manage_timezones/index.ts
  webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.test.tsx
  webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/components/user_settings/headers/setting_desktop_header.scss
  webapp/channels/src/components/user_settings/index.tsx
  webapp/channels/src/components/user_settings/modal/index.ts
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/components/user_settings/notifications/index.ts
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.test.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/index.ts
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/show_unreads_category.tsx
  webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx
  webapp/channels/src/components/widgets/smartLoader/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/preferences.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/preferences.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/preferences.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/timezone.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/sass/components/_modal.scss
  webapp/channels/src/sass/routes/_settings.scss
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/store.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#27631 [fix] ci container image scanning
  .github/workflows/server-ci-artifacts.yml
Labels: release-note-none

#27529 Updated required role for user report page GET API
  server/channels/api4/report.go
Labels: 2: Dev Review, release-note

#27375 [MM-56655] Remove deprecated Config.ProductSettings
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note

#27642 [MM-58750] Update prepackage calls to v0.29.0 for MM v9.11
  server/Makefile
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, CherryPick/Approved, release-note

#27643 Automated cherry pick of #27642
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27138 Adding Do not disturb and remote user hour warnings
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/do_not_disturb_warning.tsx
  webapp/channels/src/components/advanced_text_editor/remote_user_hour.tsx
  webapp/channels/src/components/common/svg_images_components/moon_svg.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Docs/Needed, release-note

#27418 MM-54856: Place emoji at cursor position while editing message
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
Labels: 4: Reviews Complete, QA/Review Done, release-note, Contributor

#27571 [MM-59350] Include LDAP vendor errors in Support Packet
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapInterface.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27376 [MM-55215] Remove deprecated LdapSettings.Trace
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note

#27573 [MM-59292] Add metadata to Support Packet
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/public/model/packet_metadata.go
  server/public/pluginapi/system.go
Labels: 4: Reviews Complete, QA/Deferred, release-note

#27647 Automated cherry pick of #27571
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapInterface.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27651 Automated cherry pick of #27573
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/public/model/packet_metadata.go
  server/public/pluginapi/system.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27645 Update Copilot plugin prepackaged version to 0.8.3
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27658 Automated cherry pick of #27645
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27657 Automated cherry pick of #27645
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27659 Automated cherry pick of #27655
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27629 MM-59416 Don't request notification permissions when we already have them
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27604 MM-59099 Show invalid emoji text with its original case (9.5)
  webapp/channels/src/components/post_emoji/post_emoji.test.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/utils/emoticons.tsx
  webapp/channels/src/utils/message_html_to_component.test.tsx
  webapp/channels/src/utils/message_html_to_component.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#27603 MM-59099 Show invalid emoji text with its original case
  webapp/channels/src/components/post_emoji/post_emoji.test.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/utils/emoticons.tsx
  webapp/channels/src/utils/message_html_to_component.test.tsx
  webapp/channels/src/utils/message_html_to_component.tsx
Labels: 4: Reviews Complete, CherryPick/Done, Setup Cloud Test Server, QA/Review Done, release-note

#27671 Automated cherry pick of #27629
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27672 Automated cherry pick of #27629
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27673 Automated cherry pick of #27603
  webapp/channels/src/components/post_emoji/post_emoji.test.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/utils/emoticons.tsx
  webapp/channels/src/utils/message_html_to_component.test.tsx
  webapp/channels/src/utils/message_html_to_component.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27668 [MM-59083] Handle permissions in user management options
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_manage_user_settings_modal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27636 Code enhancements to feature - Sysadmin manage user settings
  webapp/channels/src/components/confirm_modal_redux/confirm_modal_redux.tsx
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.tsx
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/index.ts
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/components/user_settings/index.tsx
  webapp/channels/src/components/user_settings/modal/index.ts
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/index.ts
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/show_unreads_category.tsx
  webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx
  webapp/channels/src/components/widgets/smart_loader/index.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/channels/src/selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27669 Fix E2E test triggering
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci.yml
Labels: release-note-none

#27679 Automated cherry pick of #27668
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_manage_user_settings_modal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27618 feat(e2e): Manage User Settings e2e tests
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/user_management/user_management_admin_control_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
Labels: 2: Dev Review, release-note-none

#27680 Automated cherry pick of #27636
  webapp/channels/src/components/confirm_modal_redux/confirm_modal_redux.tsx
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/index.ts
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx
  webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.tsx
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/index.ts
  webapp/channels/src/components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/components/user_settings/index.tsx
  webapp/channels/src/components/user_settings/modal/index.ts
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/index.ts
  webapp/channels/src/components/user_settings/sidebar/show_unreads_category/show_unreads_category.tsx
  webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx
  webapp/channels/src/components/widgets/smart_loader/index.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
  webapp/channels/src/selectors/views/channel_sidebar.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27471 MM-58847 Sanitize User
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: QA/Deferred, 3: Security Review, release-note-none

#27682 Automated cherry pick of #27471
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27683 Automated cherry pick of #27471
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27684 Automated cherry pick of #27471
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27685 Automated cherry pick of #27471
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27686 Automated cherry pick of #27471
  api/v4/source/users.yaml
  server/channels/api4/user_test.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27625 MM-59406- Fix wrong property set
  webapp/channels/src/components/admin_console/feature_discovery/features/saml.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note-none

#27670 MM-57354: Fix elastic search e2e tests
  e2e-tests/cypress/tests/integration/channels/autocomplete/helpers.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/crt_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/global_threads_spec.js
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/replies_spec.js
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/unread_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e-tests/cypress/tests/integration/channels/enterprise/elasticsearch_autocomplete/system_console_spec.js
  e2e-tests/cypress/tests/support/ui/post_dropdown_menu.js
  e2e-tests/cypress/tests/support/ui/sidebar_left.ts
Labels: 2: Dev Review, release-note-none

#27678 Added a bunch of debugging logs for Elasticsearch index check
  server/channels/app/elasticsearch.go
Labels: 4: Reviews Complete, release-note-none

#27687 Automated cherry pick of #27625
  webapp/channels/src/components/admin_console/feature_discovery/features/saml.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27368 MM-58756: paginate webhooks list
  server/cmd/mmctl/commands/webhook.go
  server/cmd/mmctl/commands/webhook_test.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#27690 Automated cherry pick of #27625
  webapp/channels/src/components/admin_console/feature_discovery/features/saml.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27479 MM-58527 - Fixing overflow issue for autocomplete
  webapp/channels/src/components/widgets/header/header.scss
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/layout/_content.scss
  webapp/channels/src/sass/layout/_headers.scss
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#27654 [MM-57418] Implement support for defining plugin settings sections
  server/public/model/manifest.go
  server/public/model/manifest_test.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/actions/admin_actions.test.js
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/custom_plugin_settings.test.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.test.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/types/store/plugins.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/types/src/plugins.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note

#27605 Remove deprecated function
  api/v4/source/permissions.yaml
  server/channels/api4/permission.go
Labels: 4: Reviews Complete, release-note-none

#27607 [MM-59296] Can't open web client on iOS Safari
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27691 Updated minimum supported Edge and Chrome versions
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Done, Changelog/Done, CherryPick/Approved, AutoMerge, release-note

#27697 Automated cherry pick of #27607
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27608 [MM-59060] Remove pre release features section from advanced section of user settings
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/markdown_preview_inline_image_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_spec.js
  e2e-tests/cypress/tests/support/api/cloud_default_config.json
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/cypress/tests/support/api/preference.js
  e2e-tests/playwright/support/server/default_config.ts
  server/config/client.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/tests/test-config.json
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/user_settings/advanced/index.ts
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/utils.tsx
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#27698 Automated cherry pick of #27691
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27677 Disable legacy-peer-deps and manually override mismatched dependencies
  webapp/.npmrc
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete, release-note-none

#27247 [MM-58515] Migrate tooltips of "components/shared_channel_indicator.tsx" to WithTooltip
  webapp/channels/src/components/shared_channel_indicator.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27703 Elasticsearch: Remove redundant message string
  webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
Labels: 4: Reviews Complete, release-note-none

#27721 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#27702 MM-58772 Fix counter metrics not using Date.now
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27731 Automated cherry pick of #27702
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27716 [MM-58045] Enable errcheck linter for enterprise/cloud package
  server/.golangci.yml
Labels: 4: Reviews Complete, release-note-none

#27714 [MM-17126] Enable errorAssertions linter for enterprise code
  server/Makefile
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#27715 [MM-59825] Fix linter error found by updated govet
  server/channels/app/channel_bookmark_test.go
  server/channels/app/integration_action_test.go
  server/channels/app/user_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Not Required, release-note-none

#27706 Update prepackage calls to v0.29.1 for MM v9.11
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27674 MM-58849 - Fixing upload button in bot screen
  webapp/channels/src/components/integrations/bots/add_bot/__snapshots__/add_bot.test.tsx.snap
  webapp/channels/src/components/integrations/bots/add_bot/add_bot.tsx
  webapp/channels/src/sass/components/_forms.scss
Labels: 4: Reviews Complete, release-note-none

#27746 Fix config targets in Makefile
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#27748 Automated cherry pick of #27715
  server/channels/app/channel_bookmark_test.go
  server/channels/app/integration_action_test.go
  server/channels/app/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27644 [MM-59368] import: enable importing thread followers for CRT
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ThreadStore.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/thread.go
  server/public/model/thread_test.go
Labels: 4: Reviews Complete, release-note

#27741 Automated cherry pick of #27706
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27745 MM-59835: Prevent unnecessary channel bookmarks request causing console 404
  webapp/channels/src/components/channel_bookmarks/channel_bookmarks.tsx
  webapp/channels/src/components/channel_bookmarks/utils.ts
  webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
  webapp/channels/src/components/channel_view/channel_view.test.tsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/channel_view/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note-none

#27749 Automated cherry pick of #27745
  webapp/channels/src/components/channel_bookmarks/channel_bookmarks.tsx
  webapp/channels/src/components/channel_bookmarks/utils.ts
  webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
  webapp/channels/src/components/channel_view/channel_view.test.tsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/channel_view/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27648 MM-59326: Remove deprecated overlay and use withTooltip in edit section of ip filtering in admin console
  webapp/channels/src/components/admin_console/ip_filtering/edit_section/edit_section_edit_table_row.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27747 Prominent payload limit error and configurable URL length limit
  server/channels/web/handlers.go
  server/channels/web/handlers_test.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
Labels: 2: Dev Review, 3: Security Review, release-note

#27729 Bump base image to Ubuntu 24
  .github/workflows/docker-push-mirrored.yml
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  server/build/Dockerfile
Labels: release-note-none

#27750 MM-59865: Set WebsocketEventScope FF to true
  server/public/model/feature_flags.go
Labels: 4: Reviews Complete, release-note-none

#27734 MM-57289: Bump dependencies
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: 4: Reviews Complete, EETests, release-note-none

#27751 MM-59026: Update reserved IP ranges
  server/public/shared/httpservice/client.go
Labels: 4: Reviews Complete, release-note-none

#27149 [MM-56904] Reduce the number of api requests made to fetch user information for GMs on page load
  server/channels/api4/preference_test.go
  server/channels/app/migrations.go
  server/channels/app/server.go
  server/channels/jobs/delete_dms_preferences_migration/delete_dms_preferences_migration.go
  server/channels/jobs/delete_dms_preferences_migration/delete_dms_preferences_migration_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/preference_store.go
  server/channels/store/sqlstore/preference_store_test.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PreferenceStore.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/testlib/store.go
  server/i18n/en.json
  server/public/model/job.go
  server/public/model/migration.go
  server/public/model/preference.go
  server/public/model/preference_test.go
  webapp/channels/src/actions/user_actions.test.ts
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/components/sidebar/sidebar_category/__snapshots__/sidebar_category_sorting_menu.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu.tsx
  webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, QA/Review Done, release-note

#27689 [MM-58440] Migrate tooltips of 'components/post_view/post_flag_icon' to WithTooltip
  webapp/channels/src/components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.tsx.snap
  webapp/channels/src/components/post_view/post_flag_icon/post_flag_icon.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27705 Fixed bug around channel file sidebar
  server/channels/store/searchtest/file_info_layer.go
  server/channels/store/sqlstore/file_info_store.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/public/model/post.go
Labels: release-note-none

#27335 [MM-58378] Prevent prepackaged playbook v2 from upgrading on servers without enterprise license
  server/channels/app/plugin.go
  server/public/model/license.go
Labels: 4: Reviews Complete, release-note-none

#27719 MM-59826: Add more invalidation event types
  server/enterprise/metrics/metrics.go
  server/public/model/cluster_message.go
Labels: 4: Reviews Complete, release-note-none

#27767 Automated cherry pick of #27751
  server/public/shared/httpservice/client.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none
