Repository mattermost/mattermost, pull requests merged in 2024-11, with the labels that each got.

#28372 [MM-60484 & MM-60485] Add disabled notification banners and section notices for web
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/announcement_bar/notification_permission_bar/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_never_granted_bar.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_unsupported_bar.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/section_notice/index.test.tsx
  webapp/channels/src/components/section_notice/index.tsx
  webapp/channels/src/components/section_notice/section_notice.scss
  webapp/channels/src/components/section_notice/section_notice_button.tsx
  webapp/channels/src/components/setting_item_max.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/index.test.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/index.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_section_notice/index.test.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_section_notice/index.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_section_notice/notification_permission_denied_section_notice.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_section_notice/notification_permission_never_granted_section_notice.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_section_notice/notification_permission_unsupported_section_notice.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_title_tag/index.test.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/notification_permission_title_tag/index.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.test.tsx
  webapp/channels/src/components/widgets/tag/tag.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_announcement-bar.scss
  webapp/channels/src/sass/routes/_settings.scss
  webapp/channels/src/utils/notifications.ts
Labels: 4: Reviews Complete, release-note-none

#28959 MM-61306: Cypress/E2E, fixed failed tests
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_buttons_spec.js
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_keyboard_usability_spec.js
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_nav_diff_regions_spec.js
  e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_reaction_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_search_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archived_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archived_leave_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/open_rhs_coming_from_system_console_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_4_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_add_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/integrations/incoming_webhook_spec.ts
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/basic_formatting_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_l_set_message_focus_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/channel_and_posts_links_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/permalink_message_edit_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/post_pre_header_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/message_bar_spec.js
  e2e-tests/cypress/tests/integration/channels/onboarding/login_page_link_account_creation_spec.js
  e2e-tests/cypress/tests/integration/channels/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e-tests/cypress/tests/integration/channels/search/clear_input_spec.js
  e2e-tests/cypress/tests/integration/channels/search/cleared_search_term_spec.js
  e2e-tests/cypress/tests/integration/channels/search/post_search_display_not_cloud_spec.js
  e2e-tests/cypress/tests/integration/channels/search/post_search_display_spec.js
  e2e-tests/cypress/tests/integration/channels/search/results_post_spec.js
  e2e-tests/cypress/tests/integration/channels/search/search_group_message_spec.js
  e2e-tests/cypress/tests/integration/channels/search/search_user_file_spec.js
  e2e-tests/cypress/tests/integration/channels/search/search_user_post_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/input_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/negative_spec.js
  e2e-tests/cypress/tests/integration/channels/toast/permalink_jump_to_spec.js
  e2e-tests/cypress/tests/support/ui/global_header.js
Labels: 4: Reviews Complete, release-note-none

#28770 Enable to AI plugin by default
  server/config/diff_test.go
  server/public/model/config.go
  server/public/model/config_test.go
  server/public/model/plugin_constants.go
  server/public/model/usage.go
Labels: 4: Reviews Complete, QA/Review Done, release-note

#28573 Fixed errcheck issues in server/channels/api4/webhook_test.go
  server/.golangci.yml
  server/channels/api4/webhook_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29035 [MM-59396] Update API docs to show common parameters, added per_page docs
  api/v4/source/introduction.yaml
Labels: 4: Reviews Complete, release-note-none

#29000 Add fetchMissingUsers option to AtMention and messageHtmlToComponent
  webapp/channels/src/components/at_mention/actions.ts
  webapp/channels/src/components/at_mention/at_mention.test.tsx
  webapp/channels/src/components/at_mention/at_mention.tsx
  webapp/channels/src/components/at_mention/index.tsx
  webapp/channels/src/components/channel_invite_modal/team_warning_banner/__snapshots__/team_warning_banner.test.tsx.snap
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/message_html_to_component.tsx
  webapp/channels/src/utils/post_utils.ts
Labels: 4: Reviews Complete, release-note

#28214 [MM-58745] export/import: enable exporting and importing bots canonically
  server/channels/app/export.go
  server/channels/app/export_converters.go
  server/channels/app/export_test.go
  server/channels/app/import.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/import_test.go
  server/channels/app/imports/import_types.go
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/bot_store.go
  server/channels/store/store.go
  server/channels/store/storetest/bot_store.go
  server/channels/store/storetest/mocks/BotStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mmctl/commands/importer/validate.go
  server/cmd/mmctl/commands/sampledata_util.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note

#29012 MM-61380 Fix link in Compliance Monitoring page banner
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#28694 MM-55192: Fix datepicker hang on DST dates
  webapp/channels/src/components/custom_status/date_time_input.test.tsx
  webapp/channels/src/components/custom_status/date_time_input.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#28964 Not scheduling post if inputs are open
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/custom_status/date_time_input.tsx
  webapp/channels/src/components/date_time_picker_modal/date_time_picker_modal.tsx
Labels: release-note-none

#28965 MM-61272 - Scrolled to scheduled post without error
  webapp/channels/src/components/drafts/scheduled_post_list/scheduled_post_list.tsx
Labels: 2: Dev Review, release-note-none

#28801 Custom status tooltip position fixed in channel switcher items
  webapp/channels/src/sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#28785 [MM-61097] Fix errcheck issues in server/channels/app/bot.go
  server/.golangci.yml
  server/channels/app/bot.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28795 Fix errcheck issue in oauth.go
  server/.golangci.yml
  server/channels/web/oauth.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28983 Update file_helper_test.go (fix errcheck issue)
  server/.golangci.yml
  server/channels/app/file_helper_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28958 Fix errcheck issues in server/channels/app/imaging/decode_test.go
  server/.golangci.yml
  server/channels/app/imaging/decode_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29043 Fixed errcheck issues in server/channels/app/oauth_test.go
  server/.golangci.yml
  server/channels/app/oauth_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29038 Fixed errcheck issues in server/channels/app/ldap.go
  server/.golangci.yml
  server/channels/app/ldap.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28910 Fixes errcheck in email_test.go
  server/.golangci.yml
  server/channels/app/email/email_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28970 Fix errcheck issues in server/channels/jobs/schedulers_test.go
  server/.golangci.yml
  server/channels/jobs/schedulers_test.go
Labels: 4: Reviews Complete, release-note-none

#28955 [MM-61259] Fix errcheck issues in server/channels/app/import_utils_test.go
  server/.golangci.yml
  server/channels/app/import_utils_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28931 Refactor admin settings to functional components
  webapp/channels/src/components/admin_console/admin_settings/__snapshots__/admin_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_settings/admin_setting.test.tsx
  webapp/channels/src/components/admin_console/admin_settings/admin_settings.tsx
  webapp/channels/src/components/admin_console/admin_settings/hooks.tsx
  webapp/channels/src/components/admin_console/admin_settings/types.ts
  webapp/channels/src/components/admin_console/admin_settings/utils.test.ts
  webapp/channels/src/components/admin_console/admin_settings/utils.ts
  webapp/channels/src/components/admin_console/bleve_settings.tsx
  webapp/channels/src/components/admin_console/cluster_settings.tsx
  webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
  webapp/channels/src/components/admin_console/database_settings.tsx
  webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
  webapp/channels/src/components/admin_console/message_export_settings.test.tsx
  webapp/channels/src/components/admin_console/message_export_settings.tsx
  webapp/channels/src/components/admin_console/old_admin_settings.tsx
  webapp/channels/src/components/admin_console/openid_convert/openid_convert.tsx
  webapp/channels/src/components/admin_console/password_settings.tsx
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
  webapp/channels/src/components/admin_console/push_settings.tsx
  webapp/channels/src/components/admin_console/session_length_settings.tsx
Labels: 4: Reviews Complete, release-note-none

#28559 Fixed errcheck issues in server/channels/api4/file_test.go
  server/.golangci.yml
  server/channels/api4/file_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28818 [MM-61106] fix server/channels/app/desktop_login.go errcheck issues
  server/.golangci.yml
  server/channels/app/desktop_login.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28872 MM-60147 - ws events on delete scheduled posts
  server/channels/app/scheduled_post.go
  server/public/model/websocket_message.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/utils/constants.tsx
Labels: release-note-none

#29065 Fixed errcheck issues in server/channels/app/opengraph_test.go
  server/.golangci.yml
  server/channels/app/opengraph_test.go
Labels: 2: Dev Review, release-note-none, Contributor

#29063 Fixed errcheck issues in server/channels/app/plugin_commands_test.go
  server/.golangci.yml
  server/channels/app/plugin_commands_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29104 [MM-61523] Skip flaky TestGetUserTeamScheduledPosts/should_get_created_scheduled_posts
  server/channels/app/scheduled_post_test.go
Labels: 4: Reviews Complete, release-note-none

#29103 Manual cherry pick of #28634
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/localcachelayer/user_layer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29044 Update Traditional Chinese to Beta
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/i18n/i18n.jsx
Labels: 4: Reviews Complete, AutoMerge, release-note

#29095 Translations update from Mattermost Weblate
  server/i18n/bg.json
  server/i18n/de.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/pl.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#29021 Fix minio Web UI access
  server/build/docker-compose.common.yml
  server/docker-compose.makefile.yml
Labels: 4: Reviews Complete, release-note-none

#29045 Fixed errcheck issues in server/channels/app/notification_push.go
  server/.golangci.yml
  server/channels/app/notification_push.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29117 Manual cherry pick of #28634
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/localcachelayer/user_layer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29118 Manual cherry pick of #28634
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/localcachelayer/user_layer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29084 MM-61520 - Fixed a bug where non-admin user wasn't able to edit their scheduled post
  webapp/channels/src/components/edit_post/index.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#29068 Fixed errcheck issues in server/channels/app/notification_test.go
  server/.golangci.yml
  server/channels/app/notification_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29115 Fix errcheck issues in server/channels/app/plugin_reattach
  server/.golangci.yml
  server/channels/app/plugin_reattach.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29124 [MM-61094] Fix errcheck issues in server/channels/app/app_test.go
  server/.golangci.yml
  server/channels/app/app_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28999 Fixathon ICU - remove npm vulnerabilities from production version
  webapp/channels/jest.config.js
  webapp/channels/package.json
  webapp/channels/src/components/pdf_preview.tsx
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/package.json
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#28844 MM-60124-emit and read create scheduled post WS event
  server/channels/api4/scheduled_post.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/scheduled_post.go
  server/channels/app/scheduled_post_test.go
  server/public/model/websocket_message.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/teams.ts
  webapp/channels/src/utils/constants.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#29134 [MM-60964] Update permissions banner button text and dismiss behaviour
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_never_granted_bar.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_unsupported_bar.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/stores/browser_store.tsx
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#29059 Fixed errcheck issues in server/channels/app/plugin_hooks_test.go
  server/.golangci.yml
  server/channels/app/plugin_hooks_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29024 [MM-59363] Shared channel event telemetry
  server/channels/app/channel.go
  server/channels/app/notification.go
  server/channels/app/post.go
  server/platform/services/telemetry/telemetry.go
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#29112 Fix mmctl build for FreeBSD
  server/cmd/mmctl/commands/utils_unix.go
Labels: 2: Dev Review, release-note-none, Contributor

#28786 [MM-61100] Fix errcheck issues in server/channels/app/busy_test.go
  server/.golangci.yml
  server/channels/app/busy_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29113 Fix errcheck issues in server/channels/app/plugin_deadlock_test.go
  server/.golangci.yml
  server/channels/app/plugin_deadlock_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29061 Fixed errcheck issues in server/channels/app/plugin_health_check_test.go
  server/.golangci.yml
  server/channels/app/plugin_health_check_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29022 update manage token model to work on load
  webapp/channels/src/components/admin_console/manage_tokens_modal/__snapshots__/manage_tokens_modal.test.tsx.snap
  webapp/channels/src/components/admin_console/manage_tokens_modal/manage_tokens_modal.test.tsx
  webapp/channels/src/components/admin_console/manage_tokens_modal/manage_tokens_modal.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#29015 Move Elasticsearch to source available :tada: :tada:
  server/enterprise/elasticsearch/common/common.go
  server/enterprise/elasticsearch/common/common_test.go
  server/enterprise/elasticsearch/common/indexing_job.go
  server/enterprise/elasticsearch/common/logger.go
  server/enterprise/elasticsearch/common/templates.go
  server/enterprise/elasticsearch/common/test_helpers.go
  server/enterprise/elasticsearch/common/test_suite.go
  server/enterprise/elasticsearch/common/version.go
  server/enterprise/elasticsearch/common/version_test.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_scheduler.go
  server/enterprise/elasticsearch/elasticsearch/bulk.go
  server/enterprise/elasticsearch/elasticsearch/bulk_test.go
  server/enterprise/elasticsearch/elasticsearch/common.go
  server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
  server/enterprise/elasticsearch/elasticsearch/elasticsearch_test.go
  server/enterprise/elasticsearch/elasticsearch/indexing_job.go
  server/enterprise/elasticsearch/elasticsearch/indexing_job_test.go
  server/enterprise/elasticsearch/elasticsearch/main_test.go
  server/enterprise/elasticsearch/elasticsearch/testlib.go
  server/enterprise/elasticsearch/init.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/aggregation_job_test.go
  server/enterprise/elasticsearch/opensearch/aggregation_scheduler.go
  server/enterprise/elasticsearch/opensearch/bulk.go
  server/enterprise/elasticsearch/opensearch/bulk_test.go
  server/enterprise/elasticsearch/opensearch/common.go
  server/enterprise/elasticsearch/opensearch/indexing_job.go
  server/enterprise/elasticsearch/opensearch/indexing_job_test.go
  server/enterprise/elasticsearch/opensearch/main_test.go
  server/enterprise/elasticsearch/opensearch/opensearch.go
  server/enterprise/elasticsearch/opensearch/opensearch_test.go
  server/enterprise/elasticsearch/opensearch/testlib.go
  server/enterprise/external_imports.go
  server/enterprise/local_imports.go
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none

#29132 MM-60331 - Scheduled post telemetry
  server/channels/app/scheduled_post_job.go
  server/platform/services/telemetry/telemetry.go
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/scheduled_posts.ts
  webapp/channels/src/packages/mattermost-redux/src/client/rudder.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/telemetry.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/posts.ts
Labels: 2: Dev Review, release-note-none

#29066 Fixed errcheck issues in server/channels/app/onboarding_test.go
  server/.golangci.yml
  server/channels/app/onboarding_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#27216 MM-56632 Display warning if requested mage size exceeds max (#26022)
  server/cmd/mmctl/commands/root.go
  server/cmd/mmctl/commands/utils.go
Labels: 4: Reviews Complete, release-note, Contributor

#28840 MM-60975 - Message export: Add startTime and endTime to export folder name
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
Labels: 4: Reviews Complete, release-note-none

#29036 Fixathon: Web app dependency updates part 1
  webapp/channels/jest.config.js
  webapp/channels/package.json
  webapp/channels/src/components/__snapshots__/setting_picture.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/channel_settings.tsx
  webapp/channels/src/components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
  webapp/channels/src/components/channel_layout/channel_identifier_router/channel_identifier_router.tsx
  webapp/channels/src/components/file_attachment/file_attachment.tsx
  webapp/channels/src/components/get_public_link_modal/get_public_link_modal.tsx
  webapp/channels/src/components/post/index.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/components/post_view/commented_on_files_message/commented_on_files_message.tsx
  webapp/channels/src/components/post_view/index.ts
  webapp/channels/src/components/post_view/post_view.tsx
  webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx
  webapp/channels/src/components/setting_picture.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_picture_section.tsx
  webapp/channels/src/components/widgets/menu/menu_wrapper.tsx
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/eslint-plugin/package.json
  webapp/platform/types/package.json
  webapp/scripts/build.mjs
  webapp/scripts/dev-server.mjs
  webapp/scripts/run.mjs
  webapp/scripts/runner.mjs
  webapp/scripts/utils.mjs
Labels: 4: Reviews Complete, release-note-none

#28873 MM-60978 - Message export: Improve xml fields; fix delete semantics
  server/channels/store/sqlstore/compliance_store.go
  server/enterprise/message_export/actiance_export/actiance_export.go
  server/enterprise/message_export/actiance_export/actiance_export_test.go
  server/enterprise/message_export/actiance_export/main_test.go
  server/enterprise/message_export/csv_export/csv_export.go
  server/enterprise/message_export/message_export.go
  server/enterprise/message_export/message_export_test.go
  server/enterprise/message_export/shared/shared.go
  server/enterprise/message_export/testdata/batch1ch2.tmpl
  server/enterprise/message_export/testdata/batch2xml.tmpl
  server/enterprise/message_export/testdata/batch3ch2.tmpl
  server/enterprise/message_export/testdata/e2eXml2.tmpl
  server/enterprise/message_export/worker.go
  server/public/model/message_export.go
Labels: 4: Reviews Complete, release-note-none

#26667 MM-57096 replaced hardcoded value with a color variable
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.scss
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.tsx
Labels: 2: Dev Review, release-note-none, Contributor

#29121 [MM-61458] Fix errcheck issues in server/channels/app/plugin_requests.go
  server/.golangci.yml
  server/channels/app/plugin_requests.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28689 [GH-28399] Errcheck jobtest
  server/.golangci.yml
  server/channels/api4/job_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29144 [MM-61506] Fix errcheck issues in server/channels/app/teams/helper_test.go
  server/.golangci.yml
  server/channels/app/teams/helper_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28676 MM-39918: mmctl: list archived private channels in channel list command with system admin user
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/app/app_iface.go
  server/channels/app/channel.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29120 MM-60123 - store most recently custom time
  webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.test.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.test.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 3: QA Review, release-note-none

#29013 Migrate mockery to packages feature
  server/Makefile
  server/channels/app/email/.mockery.yaml
  server/channels/app/platform/.mockery.yaml
  server/channels/store/.mockery.yaml
  server/channels/utils/.mockery.yaml
  server/einterfaces/.mockery.yaml
  server/platform/services/cache/.mockery.yaml
  server/platform/services/searchengine/.mockery.yaml
  server/platform/services/sharedchannel/.mockery.yaml
  server/platform/services/telemetry/.mockery.yaml
  server/platform/shared/filestore/.mockery.yaml
  server/public/plugin/.mockery.yaml
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29116 MM-60874 - show usertz in scheduled message options
  webapp/channels/src/components/advanced_text_editor/post_box_indicator/post_box_indicator.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.test.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/index.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.test.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/style.scss
  webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/timezone.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#28810 MM-61130: Use a channelMember map at web_hub level
  server/channels/api4/post_test.go
  server/channels/api4/websocket.go
  server/channels/app/app_iface.go
  server/channels/app/notification_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/app/web_conn_test.go
  server/channels/app/web_hub.go
Labels: 4: Reviews Complete, EETests, release-note-none

#29106 MM-61266 | MM-60948 - verified available actions on scheduled posts
  webapp/channels/src/actions/post_actions.ts
  webapp/channels/src/components/advanced_text_editor/use_submit.tsx
  webapp/channels/src/components/channel_view/index.ts
  webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/delete_scheduled_post_modal.tsx
  webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/components/drafts/utils.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#28987 Fixed errcheck isssues in Auto_responder_test.go
  server/.golangci.yml
  server/channels/app/auto_responder_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29153 MM-61068 - send WS event on scheduled message job send
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/scheduled_post.go
  server/channels/app/scheduled_post_job.go
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#28963 MM-44470 Fix SVG without width not displaying
  webapp/channels/src/components/file_preview_modal/image_preview.tsx
  webapp/channels/src/components/size_aware_image.tsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note-none, Contributor

#29142 [MM-61439] New Users: Change default setting for mobile push notifications to 'online, away, or offline'
  server/public/model/user.go
  server/public/model/user_test.go
Labels: 4: Reviews Complete, release-note-none

#28334 Add test notification tool
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/test_notification/trigger_browser_notification_spec.ts
  e2e-tests/cypress/tests/support/index.js
  e2e-tests/cypress/tests/support/notification_commands.ts
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_test.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/post.go
  server/public/model/post_test.go
  webapp/channels/src/actions/notification_actions.test.js
  webapp/channels/src/actions/notification_actions.tsx
  webapp/channels/src/components/common/hooks/use_external_link.test.ts
  webapp/channels/src/components/common/hooks/use_external_link.ts
  webapp/channels/src/components/external_link/__snapshots__/external_link.test.tsx.snap
  webapp/channels/src/components/external_link/external_link.test.tsx
  webapp/channels/src/components/external_link/index.tsx
  webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.test.tsx
  webapp/channels/src/components/section_notice/types.d.ts
  webapp/channels/src/components/user_settings/notifications/__snapshots__/send_test_notification_notice.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/send_test_notification_notice.test.tsx
  webapp/channels/src/components/user_settings/notifications/send_test_notification_notice.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note, Setup Cloud + CWS Test Server

#28937 Fixed errcheck issues in server/channels/app/imaging/decode.go
  server/.golangci.yml
  server/channels/app/imaging/decode.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28826 Add component library
  webapp/channels/src/components/component_library/component_library.scss
  webapp/channels/src/components/component_library/hooks.tsx
  webapp/channels/src/components/component_library/index.tsx
  webapp/channels/src/components/component_library/section_notice.cl.tsx
  webapp/channels/src/components/component_library/utils.tsx
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#29029 [MM-61441] Don't overwrite plugin secret settings with fake values
  server/config/utils.go
  server/config/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#29219 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/en-AU.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/uk.json
  server/i18n/zh-TW.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#29221 Automated cherry pick of #29029
  server/config/utils.go
  server/config/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29222 Automated cherry pick of #29029
  server/config/utils.go
  server/config/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29196 Fixed errcheck issues in server/channels/app/slashcommands/command_leave_test.go
  server/.golangci.yml
  server/channels/app/slashcommands/command_leave_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29006 ICU Fixathon - clean up React.Fragment old syntax
  webapp/channels/.eslintrc.json
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list.tsx
  webapp/channels/src/components/apps_form/apps_form_component.tsx
  webapp/channels/src/components/apps_form/apps_form_field/apps_form_field.tsx
  webapp/channels/src/components/browse_channels/browse_channels.tsx
  webapp/channels/src/components/channel_header/channel_header_title_direct.tsx
  webapp/channels/src/components/channel_header/channel_header_title_group.tsx
  webapp/channels/src/components/channel_header_dropdown/channel_header_dropdown_items.tsx
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
  webapp/channels/src/components/file_preview/file_progress_preview.tsx
  webapp/channels/src/components/integrations/bots/bots.tsx
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
  webapp/channels/src/components/invitation_modal/add_to_channels.tsx
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  webapp/channels/src/components/link_tooltip/link_tooltip.tsx
  webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx
  webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx
  webapp/channels/src/components/post_view/post_image/post_image.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.tsx
  webapp/channels/src/components/post_view/post_reaction/post_reaction.tsx
  webapp/channels/src/components/post_view/post_recent_reactions/post_recent_reactions.tsx
  webapp/channels/src/components/quick_input/max_length_input.tsx
  webapp/channels/src/components/search_hint/search_hint.tsx
  webapp/channels/src/components/sidebar/sidebar.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category.tsx
  webapp/channels/src/components/size_aware_image.tsx
  webapp/channels/src/components/toast_wrapper/toast_wrapper.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/color_chooser/color_chooser.tsx
  webapp/channels/src/components/widgets/inputs/channels_input.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.tsx
  webapp/channels/src/components/widgets/menu/menu_items/submenu_item.tsx
  webapp/channels/src/plugins/channel_header_plug/channel_header_plug.tsx
  webapp/channels/src/plugins/pluggable/pluggable.tsx
Labels: 4: Reviews Complete, release-note-none

#29214 MM-61700: Fix race conditions from web_hub initialization
  server/channels/app/bot.go
  server/channels/app/platform/helper_test.go
  server/channels/app/shared_channel.go
  server/channels/app/user.go
Labels: 4: Reviews Complete, release-note-none

#29123 MM-60141 - Scheduled post copy text option
  webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#29175 [MM-61547] Added debug settings for testing and e2e tests
  server/channels/app/server.go
  webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#29187 Scheudled post test enhancement
  server/channels/api4/scheduled_post_test.go
  server/channels/app/helper_test.go
  server/channels/app/scheduled_post_job_test.go
  server/channels/app/scheduled_post_test.go
Labels: 4: Reviews Complete, release-note-none

#29201 Fixed errcheck issues in server/channels/api4/post_test.go
  server/.golangci.yml
  server/channels/api4/post_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29208 MM - 60506 - notify user failed scheduled msgs
  server/channels/app/scheduled_post_job.go
  server/channels/app/scheduled_post_job_test.go
  server/channels/app/scheduled_post_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#29147 Demote unstable tests from daily run
  e2e-tests/cypress/.eslintrc.json
  e2e-tests/cypress/tests/integration/channels/account_settings/security/password_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/post_menu_spec.ts
  e2e-tests/cypress/tests/integration/channels/bot_accounts/bot_api_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/metrics/license_no_license_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/oauth/oauth_spec.ts
  e2e-tests/cypress/tests/integration/channels/integrations/message_to_channel_via_slash_command_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e-tests/cypress/tests/integration/channels/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e-tests/cypress/tests/integration/channels/mark_as_unread/toast_appears_unread_spec.js
  e2e-tests/cypress/tests/integration/channels/mark_as_unread/unread_toast_count_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/autocomplete_shown_each_channel_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_draft_then_switch_channel_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_reply_part2_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/permalink_loading_indicator_spec.js
  e2e-tests/cypress/tests/integration/channels/plugins/demo_plugin/webhook_spec.js
  e2e-tests/cypress/tests/integration/channels/plugins/plugin_startup_fail_spec.js
  e2e-tests/cypress/tests/integration/channels/search/clear_input_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/input_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_2_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/ui_and_api/customization_not_cloud_spec.js
  e2e-tests/cypress/tests/integration/channels/toast/unread_with_bottom_start_toast_spec.js
  e2e-tests/cypress/tests/integration/channels/websocket/handle_new_post_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/status_update_spec.js
  e2e-tests/cypress/tests/integration/playbooks/lhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit/actions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit/checklists_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit/header_spec.js
  e2e-tests/cypress/tests/integration/playbooks/playbooks/edit_metrics_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/permissions_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_header_spec.js
  e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_statusupdate_spec.js
  e2e-tests/playwright/tests/functional/system_console/system_users/export_data.spec.ts
Labels: release-note-none

#29230 Prepackage Calls v0.29.4 in `release-9.5`
  server/Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#29231 Prepackage Calls v0.29.4 in `release-9.11`
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#29232 [MM-61133] Prepackage Calls v1.3.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#29234 Automated cherry pick of #29232
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29206 [MM-61465] Fix errcheck issues in server/channels/app/post_metadata_test.go
  server/.golangci.yml
  server/channels/app/post_metadata_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29220 [MM-61516] Fix errcheck issues in server/channels/app/plugin_api_test.go
  server/.golangci.yml
  server/channels/app/plugin_api_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29228 Fix broken TestGetPost
  server/channels/api4/post_test.go
  server/channels/api4/user_test.go
Labels: 2: Dev Review, release-note-none

#28319 Added support for S3 storage classes
  api/v4/source/definitions.yaml
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/support/server/default_config.ts
  server/i18n/en.json
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/filesstore_test.go
  server/platform/shared/filestore/s3store.go
  server/public/model/config.go
  server/tests/test-config.json
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note, Contributor

#29152 MM-61484 - Deleting scheduled posts when permanently deleting a user
  server/channels/api4/outgoing_oauth_connection_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/scheduled_post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ScheduledPostStore.go
  server/channels/store/storetest/scheduled_post_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note-none

#29215 [MM-61697] Date time picker - use localized date format and don't reset time when changing dates
  webapp/channels/src/components/custom_status/date_time_input.tsx
  webapp/channels/src/utils/datetime.ts
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#29226 Scheudled post show more
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel_body.test.tsx
  webapp/channels/src/components/drafts/panel/panel_body.tsx
Labels: CherryPick/Approved, QA/Review Done, release-note-none, 1. UX Review

#29209 Update ES template strings
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/common.go
  server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/common.go
  server/enterprise/elasticsearch/opensearch/opensearch.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#29242 Automated cherry pick of #29226
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel_body.test.tsx
  webapp/channels/src/components/drafts/panel/panel_body.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29240 Automated cherry pick of #29215
  webapp/channels/src/components/custom_status/date_time_input.tsx
  webapp/channels/src/utils/datetime.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28833 [MM-61140] Allow plugins to add Support Packet data without UI elements
  server/channels/app/channel.go
  server/channels/app/channels.go
  server/channels/app/file.go
  server/channels/app/login.go
  server/channels/app/notification_push.go
  server/channels/app/platform/config.go
  server/channels/app/platform/service.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_conn_test.go
  server/channels/app/plugin.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/post.go
  server/channels/app/preference.go
  server/channels/app/reaction.go
  server/channels/app/support_packet.go
  server/channels/app/team.go
  server/channels/app/upload.go
  server/channels/app/user.go
  server/platform/services/telemetry/telemetry.go
  server/public/plugin/environment.go
  server/public/plugin/hooks.go
Labels: 4: Reviews Complete, release-note

#29211 Scheduled post left gm fix
  webapp/channels/src/components/drafts/draft_title/__snapshots__/draft_title.test.tsx.snap
  webapp/channels/src/components/drafts/draft_title/draft_title.test.tsx
  webapp/channels/src/components/drafts/draft_title/draft_title.tsx
  webapp/channels/src/components/drafts/draft_title/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/test_intl.tsx
Labels: 2: Dev Review, CherryPick/Approved, QA/Review Done, release-note-none

#29245 Automated cherry pick of #29211
  webapp/channels/src/components/drafts/draft_title/__snapshots__/draft_title.test.tsx.snap
  webapp/channels/src/components/drafts/draft_title/draft_title.test.tsx
  webapp/channels/src/components/drafts/draft_title/draft_title.tsx
  webapp/channels/src/components/drafts/draft_title/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/test_intl.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29178 Skipping flaky TestClientGetOutgoingOAuthConnection test
  server/channels/api4/outgoing_oauth_connection_test.go
Labels: 4: Reviews Complete, release-note-none

#29246 Automated cherry pick of #29228
  server/channels/api4/post_test.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29239 Automated cherry pick of #29152
  server/channels/api4/outgoing_oauth_connection_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/scheduled_post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ScheduledPostStore.go
  server/channels/store/storetest/scheduled_post_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29194 Fixed errcheck issues in server/channels/app/product_notices_test.go
  server/.golangci.yml
  server/channels/app/product_notices_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29119 Fix errcheck issues in server/channels/app/login_test
  server/.golangci.yml
  server/channels/app/login_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29177 update command_remove_test.go (fix errcheck issue)
  server/.golangci.yml
  server/channels/app/slashcommands/command_remove_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29198 Fixed errcheck issues in server/channels/app/session_test.go
  server/.golangci.yml
  server/channels/app/session_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29212 Fail fast while connecting to replicas
  .github/workflows/server-test-template.yml
  server/channels/store/sqlstore/store.go
  server/public/utils/sql/sql_utils.go
Labels: 4: Reviews Complete, release-note-none

#29141 MM-60481/MM-61301 fix bookmarks flaky tests
  server/channels/api4/channel_bookmark_test.go
Labels: 4: Reviews Complete, release-note-none

#29249 MM-61503 Updated golangci.yml configuration
  server/.golangci.yml
Labels: 4: Reviews Complete, release-note-none, Contributor

#29188 [MM-61513] Fix errcheck issues in channels/app/users/users_test.go fixes #29179
  server/.golangci.yml
  server/channels/app/users/users_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28966 Update file_info.go (fix errcheck issue)
  server/.golangci.yml
  server/channels/app/file_info.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#29169 Fixed errcheck issues in server/channels/app/slashcommands/command_loadtest.go
  server/.golangci.yml
  server/channels/app/slashcommands/command_loadtest.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29042 optionally exclude threads in direct messages
  server/channels/api4/channel_bookmark_test.go
  server/channels/api4/user.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/storetest/thread_store.go
  server/public/model/client4.go
  server/public/model/thread.go
Labels: 4: Reviews Complete, release-note

#29167 [MM-61512] Fix errcheck issues in server/channels/app/users/helper_test.go
  server/.golangci.yml
  server/channels/app/users/helper_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29267 [MM-61779] Skip flaky TestEditChannelBookmark/a_websockets_event_should_be_fired_as_part_of_editing_a_bookmark
  server/channels/api4/channel_bookmark_test.go
Labels: 4: Reviews Complete, release-note-none

#29260 GH-28752 fix errcheck lint issues in server/channels/testlib/helper.go
  server/.golangci.yml
  server/channels/testlib/helper.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29253 MM-61731 - enhance failed sent system bot message
  server/channels/app/scheduled_post_job.go
  server/channels/app/scheduled_post_job_test.go
  server/i18n/en.json
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#29257 MM-61733: Fix system console theme stability
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#29279 Automated cherry pick of #29257
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29268 [MM-61780] Skip flaky TestWebHubCloseConnOnDBFail
  server/channels/api4/post_test.go
Labels: 2: Dev Review, release-note-none

#29190 [MM-61517] Fix errcheck issues in channels/app/plugin_api_tests/manual.test_http_hijack_plugin
  server/.golangci.yml
  server/channels/app/plugin_api_tests/manual.test_http_hijack_plugin/main.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28433 E2E test for scheduled Draft feature
  e2e-tests/playwright/support/ui/components/channels/center_view.ts
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  e2e-tests/playwright/support/ui/components/channels/scheduled_draft_menu.ts
  e2e-tests/playwright/support/ui/components/channels/scheduled_draft_modal.ts
  e2e-tests/playwright/support/ui/components/channels/sidebar_left.ts
  e2e-tests/playwright/support/ui/components/channels/sidebar_right.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/pages/channels.ts
  e2e-tests/playwright/support/ui/pages/drafts.ts
  e2e-tests/playwright/support/ui/pages/index.ts
  e2e-tests/playwright/support/ui/pages/scheduled_draft.ts
  e2e-tests/playwright/tests/functional/channels/scheduled_drafts/create_scheduled_draft.spec.ts
  server/channels/app/scheduled_post_test.go
  webapp/channels/src/components/custom_status/date_time_input.tsx
  webapp/channels/src/components/edit_post/index.ts
Labels: release-note-none

#29250 Demote unstable tests
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/cypress/tests/integration/channels/bot_accounts/display_name_spec.ts
  e2e-tests/cypress/tests/integration/channels/bot_accounts/managing_bot_accounts_not_cloud_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_3_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_4_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_login_spec.ts
  e2e-tests/cypress/tests/integration/channels/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts
  e2e-tests/cypress/tests/integration/channels/messaging/pinned_posts_2_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/ignore_channel_mentions_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/unsaved_changes_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/rhs/start_run_rhs_spec.js
  e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/test_spec.js
Labels: release-note-none

#29247 MM-61303 - fix accesibility issues with feature scheduled messages
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
  webapp/channels/src/components/drafts/drafts.tsx
  webapp/channels/src/components/tabs/tab/index.tsx
  webapp/channels/src/components/tabs/tabs/index.tsx
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#29286 Automated cherry pick of #29247
  webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
  webapp/channels/src/components/drafts/drafts.tsx
  webapp/channels/src/components/tabs/tab/index.tsx
  webapp/channels/src/components/tabs/tabs/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28917 MM-61229: Place Redis behind enterprise
  server/channels/api4/apitestlib.go
  server/channels/app/options.go
  server/channels/app/platform/options.go
  server/channels/app/platform/service.go
Labels: 4: Reviews Complete, release-note-none

#29269 GH-29265: Fix errcheck errors in server/channels/app/platform/feature_flags.go
  server/.golangci.yml
  server/channels/app/platform/feature_flags.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29060 [MM-53339] import: dont miss out reactions from replies
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
Labels: 4: Reviews Complete, release-note

#29243 Added hover color on split send post button
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.scss
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#29288 Fix race condition in the web package
  server/channels/web/web_test.go
Labels: 2: Dev Review, release-note-none

#29154 [MM-61509] Fix errcheck issues in server/channels/app/user.go
  server/.golangci.yml
  server/channels/app/user.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29151 Fixes errcheck issues in server/channels/api4/team_test.go
  server/.golangci.yml
  server/channels/api4/team_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29274 MM-61536 - enable schmsgs feature on license upgrade
  webapp/channels/src/components/drafts/drafts.scss
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#29292 Fix flaky TestHandleFailedScheduledPosts test
  server/channels/app/scheduled_post_job_test.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#29254 MM-61721 - adjust scheduled messages channels legend
  webapp/channels/src/components/advanced_text_editor/scheduled_post_indicator/scheduled_post_indicator.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#29293 Automated cherry pick of #29274
  webapp/channels/src/components/drafts/drafts.scss
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29294 Automated cherry pick of #29254
  webapp/channels/src/components/advanced_text_editor/scheduled_post_indicator/scheduled_post_indicator.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29207 [MM-61466] Fix errcheck issues in server/channels/app/post_persistent_notification_test.go
  server/.golangci.yml
  server/channels/app/post_persistent_notification_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29297 Disable 8 core runners for mattermost build
  .github/workflows/esrupgrade-common.yml
  .github/workflows/server-ci-template.yml
Labels: kind/bug, release-note-none

#29291 Automated cherry pick of #29243
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.scss
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx
  webapp/channels/src/utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29218 [MM-61539] Removed duplicate draft icons when no scheduled posts exist and updated draft icon
  webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
  webapp/channels/src/i18n/en.json
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none, 1. UX Review

#29300 Automated cherry pick of #29218
  webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29138 MM-61318 Don't apply extra CSS to Markdown headings in thread list
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.scss
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, release-note

#29139 MM-61012 Add special handling to OS detection for mobile apps
  server/channels/app/login.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
Labels: 4: Reviews Complete, release-note

#29283 Add type annotation to generated language files map
  webapp/channels/src/i18n/imports.ts
  webapp/scripts/gen_lang_imports.mjs
Labels: 2: Dev Review, release-note-none

#29289 [MM-61518] Fixed errcheck issues in channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go
  server/.golangci.yml
  server/channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go
Labels: 4: Reviews Complete, release-note-none, Contributor
