Repository mattermost/mattermost, pull requests merged in 2024-05, with the labels that each got.

#26937 Automated cherry pick of #26516
  server/channels/app/integration_action.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26938 [MM-58070] Ensure the batched post handler also send websocket acknowledgements
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/websocket_actions.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26939 Automated cherry pick of #26938
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/websocket_actions.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26907 MM-57841 - Updating post delete modal
  webapp/channels/src/components/delete_post_modal/__snapshots__/delete_post_modal.test.tsx.snap
  webapp/channels/src/components/delete_post_modal/delete_post_modal.tsx
Labels: release-note-none

#26918 [MM-58043] Enable errcheck linter for enterprise/data_retention package
  server/.golangci.yml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Tests/Not Needed, release-note-none

#26924 [MM-57407] Add setting to disable the wake up on reconnect handler
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#26944 Fix E2E test cases and setup for GHA
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/dashboard.override.yml
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/.ci/server.start.sh
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/metrics/license_no_license_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/sidebar_link_navigation_e20_spec.js
  e2e-tests/cypress/tests/integration/channels/settings/display/theme/code_theme_colors_spec.js
  e2e-tests/cypress/tests/integration/channels/signin_authentication/login_close_server_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e-tests/cypress/tests/integration/channels/toast/unread_with_bottom_start_toast_spec.js
  e2e-tests/cypress/tests/utils/admin_console.js
Labels: release-note-none

#26929 [MM-58059] Remove PostPriority feature flag
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/post_test.go
  server/channels/api4/user_test.go
  server/channels/app/post_persistent_notification_test.go
  server/channels/app/post_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: 4: Reviews Complete, release-note

#26931 [MM-58064] Enable emptyStrCmp linter for enterprise code
  server/Makefile
Labels: 4: Reviews Complete, Docs/Not Needed, Tests/Not Needed, release-note-none

#26846 Properly unset active channel in the server
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26393 Fix types so the store can return undefined channels
  webapp/channels/src/actions/command.ts
  webapp/channels/src/actions/post_actions.ts
  webapp/channels/src/actions/views/channel.ts
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/index.ts
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_create_post/index.ts
  webapp/channels/src/components/at_sum_members_mention/notification_from_members_modal.tsx
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/channel_header/channel_header_title_favorite.tsx
  webapp/channels/src/components/channel_header/index.ts
  webapp/channels/src/components/channel_header_dropdown/channel_header_dropdown_items.tsx
  webapp/channels/src/components/channel_header_dropdown/index.ts
  webapp/channels/src/components/channel_header_dropdown/mobile_channel_header_dropdown.tsx
  webapp/channels/src/components/channel_info_rhs/index.ts
  webapp/channels/src/components/create_team/create_team.tsx
  webapp/channels/src/components/dot_menu/index.ts
  webapp/channels/src/components/drafts/channel_draft/channel_draft.tsx
  webapp/channels/src/components/drafts/channel_draft/index.ts
  webapp/channels/src/components/drafts/thread_draft/thread_draft.tsx
  webapp/channels/src/components/edit_post/index.ts
  webapp/channels/src/components/file_search_results/index.tsx
  webapp/channels/src/components/forward_post_modal/index.ts
  webapp/channels/src/components/forward_post_modal/index.tsx
  webapp/channels/src/components/invitation_modal/invitation_modal.tsx
  webapp/channels/src/components/invitation_modal/invite_view.tsx
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/member_list_channel/index.ts
  webapp/channels/src/components/move_thread_modal/move_thread_modal.tsx
  webapp/channels/src/components/post_edit_history/index.ts
  webapp/channels/src/components/post_markdown/post_markdown.tsx
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
  webapp/channels/src/components/post_view/channel_intro_message/index.ts
  webapp/channels/src/components/post_view/post_message_preview/index.ts
  webapp/channels/src/components/rhs_thread/rhs_thread.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  webapp/channels/src/components/threading/thread_viewer/index.ts
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/channels/src/components/toast_wrapper/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/channel_utils.ts
  webapp/channels/src/plugins/call_button/call_button.tsx
  webapp/channels/src/utils/channel_utils.tsx
  webapp/channels/src/utils/post_utils.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26902 [MM-57717] Convert SubMenuModal from Class Component to Function Component
  webapp/channels/src/components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  webapp/channels/src/components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.tsx
  webapp/channels/src/components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25395 [MM-55327]: Convert /components/permissions_gates/team_permission_gate/team_permission_gate.tsx from Class Component to Function Component
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  webapp/channels/src/components/browse_channels/__snapshots__/browse_channels.test.tsx.snap
  webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/integrations/__snapshots__/abstract_oauth_app.test.tsx.snap
  webapp/channels/src/components/main_menu/__snapshots__/main_menu.test.tsx.snap
  webapp/channels/src/components/permissions_gates/any_team_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/any_team_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/any_team_permission_gate/__snapshots__/any_team_permission_gate.test.tsx.snap
  webapp/channels/src/components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/any_team_permission_gate/index.ts
  webapp/channels/src/components/permissions_gates/channel_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/channel_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/channel_permission_gate/__snapshots__/channel_permission_gate.test.tsx.snap
  webapp/channels/src/components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/channel_permission_gate/channel_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/channel_permission_gate/index.ts
  webapp/channels/src/components/permissions_gates/channel_permission_gate/mattermost.code-workspace
  webapp/channels/src/components/permissions_gates/gate.test.tsx
  webapp/channels/src/components/permissions_gates/gate.tsx
  webapp/channels/src/components/permissions_gates/system_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/system_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/system_permission_gate/__snapshots__/system_permission_gate.test.tsx.snap
  webapp/channels/src/components/permissions_gates/system_permission_gate/index.ts
  webapp/channels/src/components/permissions_gates/system_permission_gate/system_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/system_permission_gate/system_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/team_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/team_permission_gate.tsx
  webapp/channels/src/components/permissions_gates/team_permission_gate/__snapshots__/team_permission_gate.test.tsx.snap
  webapp/channels/src/components/permissions_gates/team_permission_gate/index.ts
  webapp/channels/src/components/permissions_gates/team_permission_gate/team_permission_gate.test.tsx
  webapp/channels/src/components/permissions_gates/team_permission_gate/team_permission_gate.tsx
  webapp/channels/src/components/post_view/channel_intro_message/__snapshots__/add_members_button.test.tsx.snap
  webapp/channels/src/components/post_view/channel_intro_message/add_members_button.test.tsx
  webapp/channels/src/components/post_view/channel_intro_message/add_members_button.tsx
  webapp/channels/src/components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  webapp/channels/src/components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
  webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap
  webapp/channels/src/components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  webapp/channels/src/components/team_members_modal/__snapshots__/team_members_modal.test.tsx.snap
  webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26954 Chore(cypress): Review and Fix tests failing on master
  e2e-tests/cypress/tests/fixtures/markdown/markdown_code_block.html
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_buttons_spec.js
  e2e-tests/cypress/tests/integration/channels/archived_channel/post_menu_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_experience_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/integrations_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_k_open_gm_with_mouse_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/system_message_not_open_for_edit_spec.js
  e2e-tests/cypress/tests/integration/channels/markdown/markdown_text_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_followed_by_punctuation_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_insert_position_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_keyboard_entry_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_skin_tone_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_to_markdown_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/focus_move_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_parse_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_reaction_gm_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/permalink_loading_indicator_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/reactions_spec.js
  e2e-tests/cypress/tests/integration/channels/multi_team_and_dm/gm_header_spec.js
  e2e-tests/cypress/tests/integration/channels/settings/display/message_display_mode_colorize_username_spec.js
  e2e-tests/cypress/tests/integration/channels/settings/display/theme/code_theme_colors_spec.js
  e2e-tests/cypress/tests/integration/channels/settings/display/theme/settings_view_spec.js
  e2e-tests/cypress/tests/integration/channels/signin_authentication/login_open_server_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/environment_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/inactive_users_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/main_menu_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/reporting/team_statistics_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/announcement_banner_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/customization_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_cloud_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management/users_deactivation_not_cloud_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_not_cloud_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/closed_team_invite_by_email_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/teams_spec.js
  e2e-tests/cypress/tests/integration/channels/toast/new_messages_toast_spec.js
  e2e-tests/cypress/tests/utils/constants.js
Labels: release-note-none

#26942 MM-58092 Add feature flag and setting for client performance metrics
  server/config/client.go
  server/public/model/config.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#25859 [MM-56340] Add audit events for OAuth logins
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26698 Adding more visibility to the free edition in the interface
  webapp/channels/src/components/common/svg_images_components/logo_dark_blue_svg.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/__snapshots__/product_menu.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding_team_edition/index.ts
  webapp/channels/src/components/global_header/left_controls/product_menu/product_branding_team_edition/product_branding_team_edition.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu.test.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  webapp/channels/src/components/header_footer_route/header.scss
  webapp/channels/src/components/header_footer_route/header.tsx
  webapp/channels/src/components/login/login.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26932 [MM-57884] Layout issues with initial tool selection and invite screens in workspace
  webapp/channels/src/components/preparing_workspace/__snapshots__/invite_members.test.tsx.snap
  webapp/channels/src/components/preparing_workspace/invite_members.tsx
  webapp/channels/src/components/preparing_workspace/mixins.scss
  webapp/channels/src/components/preparing_workspace/preparing_workspace.scss
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26962 Update minimum supported Safari version
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, AutoMerge, release-note

#26870 [MM-58020] Improve error message of NotFound errors in store
  server/channels/store/errors.go
  server/channels/store/errors_test.go
  server/cmd/mmctl/commands/channel_e2e_test.go
  server/cmd/mmctl/commands/user_e2e_test.go
Labels: 4: Reviews Complete, release-note

#26963 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#26953 MM-52570 Prevent pasteHandler from having any effect when shift is held
  webapp/channels/src/utils/paste.test.tsx
  webapp/channels/src/utils/paste.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26969 avoid segfault in TestDeleteChannelBookmark
  server/channels/api4/channel_bookmark_test.go
Labels: 2: Dev Review, QA/Review Not Required, release-note-none

#26947 Fix system console defaults
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26976 Automated cherry pick of #26947
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26977 Automated cherry pick of #26947
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26407 MM-56975 UI Incremental Refinements
  webapp/channels/src/components/app_bar/app_bar.scss
  webapp/channels/src/components/backstage/backstage_controller.tsx
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.scss
  webapp/channels/src/components/drafts/drafts.scss
  webapp/channels/src/components/global_header/global_header.tsx
  webapp/channels/src/components/header_footer_route/header_footer_route.scss
  webapp/channels/src/components/menu/menu_styled.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_popover.tsx
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/threading/global_threads/global_threads.scss
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.scss
  webapp/channels/src/components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
  webapp/channels/src/components/threading/global_threads/thread_pane/thread_pane.scss
  webapp/channels/src/components/three_days_left_trial_modal/three_days_left_trial_modal.scss
  webapp/channels/src/components/widgets/menu/menu.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
  webapp/channels/src/components/widgets/modals/components/modal_header.scss
  webapp/channels/src/components/widgets/modals/components/modal_sidebar.scss
  webapp/channels/src/components/widgets/team_icon/team_icon.scss
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/base/_css_variables.scss
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_modal.scss
  webapp/channels/src/sass/components/_popover.scss
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/layout/_headers.scss
  webapp/channels/src/sass/layout/_sidebar-left.scss
  webapp/channels/src/sass/layout/_sidebar-right.scss
  webapp/channels/src/sass/layout/_team-sidebar.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/sass/routes/_backstage.scss
  webapp/platform/components/src/generic_modal/generic_modal.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#26943 [MM-58091] Fix tracking websocket connections
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#26978 Automated cherry pick of #26947
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26867 [MM-58002] Review start call button functionality in profile popover
  webapp/channels/package.json
  webapp/channels/src/components/profile_popover/index.test.tsx
  webapp/channels/src/components/profile_popover/index.tsx
  webapp/channels/src/components/profile_popover/profile_popover_actions/call_button.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_actions/call_button.tsx
  webapp/channels/src/components/profile_popover/profile_popover_actions/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
  webapp/channels/src/selectors/calls.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#26372 [MM-56902] Minor selector improvements
  webapp/channels/src/components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  webapp/channels/src/components/forward_post_modal/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/selectors/drafts.ts
  webapp/channels/src/selectors/onboarding.ts
Labels: 2: Dev Review, release-note-none

#26979 [MM-58159] Add admin setting for notification monitoring alongside feature flag
  server/channels/app/notification.go
  server/channels/app/web_broadcast_hooks.go
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#26800 MM-57878 Add PerformanceReporter for clientside performance metrics
  server/config/client.go
  server/platform/services/telemetry/telemetry.go
  webapp/channels/package.json
  webapp/channels/src/actions/telemetry_actions.jsx
  webapp/channels/src/components/post_view/post_list/post_list.tsx
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/performance_reporter_controller.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/tests/helpers/user_agent_mocks.ts
  webapp/channels/src/tests/performance_mock.test.ts
  webapp/channels/src/tests/performance_mock.ts
  webapp/channels/src/tests/setup_jest.ts
  webapp/channels/src/utils/performance_telemetry/index.ts
  webapp/channels/src/utils/performance_telemetry/long_task.ts
  webapp/channels/src/utils/performance_telemetry/platform_detection.test.ts
  webapp/channels/src/utils/performance_telemetry/platform_detection.ts
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
  webapp/channels/src/utils/user_agent.tsx
  webapp/package-lock.json
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#26970 MM-57881 Add metric for the amount of time it takes for the RHS to load a thread
  webapp/channels/jest.config.js
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/post_view/post_list/post_list.tsx
  webapp/channels/src/components/rhs_thread/index.ts
  webapp/channels/src/components/rhs_thread/rhs_thread.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/components/team_sidebar/components/team_button.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/index.ts
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/utils/performance_telemetry/index.ts
Labels: 4: Reviews Complete, release-note

#26919 Add new Metrics API
  server/channels/api4/api.go
  server/channels/api4/apitestlib.go
  server/channels/api4/metrics.go
  server/channels/api4/metrics_test.go
  server/channels/app/app_iface.go
  server/channels/app/metrics.go
  server/channels/app/opentracing/opentracing_layer.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/client4.go
  server/public/model/metrics.go
  server/public/model/metrics_test.go
  server/public/model/utils.go
  server/scripts/vet-api-check.sh
Labels: 4: Reviews Complete, release-note-none

#26921 MM-57548 - Fixing announcement banner icon
  webapp/channels/src/components/announcement_bar/__snapshots__/text_dismissable_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
  webapp/channels/src/sass/components/_announcement-bar.scss
Labels: 2: Dev Review, release-note-none

#26985 Change client metrics api path to client_perf
  server/channels/api4/metrics.go
  server/enterprise/metrics/metrics.go
  server/public/model/client4.go
  server/scripts/vet-api-check.sh
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note-none

#26948 Fix test for invite modal error
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_more_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_spec.ts
  webapp/channels/src/actions/invite_actions.test.ts
  webapp/channels/src/actions/invite_actions.ts
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26995 Translations update from Mattermost Weblate
  server/i18n/ja.json
  server/i18n/pl.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#26986 Use GetMasterX() to ensure writeability for the RefreshPostStats job
  server/channels/store/sqlstore/user_store.go
Labels: 4: Reviews Complete, release-note

#26987 Remove t and localizeMessage from components/activity_log_modal
  webapp/channels/src/components/activity_log_modal/components/__snapshots__/activity_log.test.tsx.snap
  webapp/channels/src/components/activity_log_modal/components/activity_log.test.tsx
  webapp/channels/src/components/activity_log_modal/components/activity_log.tsx
  webapp/channels/src/components/activity_log_modal/components/device_icon.tsx
Labels: 4: Reviews Complete, release-note-none

#26982 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note

#26998 Automated cherry pick of #26982
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26956 [MM-57877] Fix issue #26841
  server/channels/api4/team_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26999 Fix(cypress): Fix test cases for profile popover
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/account_settings_position_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/fullname_truncate_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/username_spec.ts
  e2e-tests/cypress/tests/integration/channels/bot_accounts/display_name_spec.js
  e2e-tests/cypress/tests/integration/channels/channel_settings/add_users_to_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_experience_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/profile_popover/profile_popover_spec_user_a_b_spec.ts
  e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/mobile_profile_popover_spec.js
  e2e-tests/cypress/tests/integration/channels/scroll/fixed_width_spec.js
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
Labels: release-note-none

#26996 MM-58026 Adming onboarding UI fix
  webapp/channels/src/sass/base/_structure.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, AutoMerge, release-note-none

#27000 Automated cherry pick of #26996
  webapp/channels/src/sass/base/_structure.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26868 add WARN to log constants
  webapp/channels/src/components/admin_console/admin_definition_constants.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, QA/Deferred, release-note-none

#27003 User group popover migrated to floating-ui
  webapp/channels/src/components/at_mention/__snapshots__/at_mention.test.tsx.snap
  webapp/channels/src/components/at_mention/at_mention.test.tsx
  webapp/channels/src/components/at_mention/at_mention.tsx
  webapp/channels/src/components/at_mention/index.tsx
  webapp/channels/src/components/profile_popover/profile_popover_title.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/constants.ts
  webapp/channels/src/components/user_group_popover/index.ts
  webapp/channels/src/components/user_group_popover/useShouldClose.ts
  webapp/channels/src/components/user_group_popover/user_group_popover.scss
  webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover_controller.tsx
  webapp/channels/src/i18n/en.json
Labels: do-not-merge/release-note-label-needed

#26936 PluginAPI: add ability to retrieve users by ids
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_test.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/user.go
  server/public/pluginapi/user_test.go
Labels: 2: Dev Review, release-note

#27004 Centralize the GetPackagePath
  server/channels/api4/plugin_test.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_api_tests/path.go
  server/channels/testlib/helper.go
  server/channels/testlib/resources.go
  server/channels/testlib/testdata/path.go
  server/channels/utils/fileutils/fileutils.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/extract_e2e_test.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/cmd/mmctl/commands/plugin_e2e_test.go
  server/path.go
Labels: 2: Dev Review, QA/Review Not Required, release-note-none

#27011 MM-58263 Remove CSRF check from /api/v4/client_perf
  server/channels/api4/metrics.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27014 Automated cherry pick of #27011
  server/channels/api4/metrics.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26869 fix css
  webapp/channels/src/sass/routes/_settings.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#27017 Automated cherry pick of #26869
  webapp/channels/src/sass/routes/_settings.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27001 [MM-54757] Stop broadcasting channel_deleted/channel_restored messages from private channels to non-members
  server/channels/app/channel.go
  server/channels/app/channel_test.go
Labels: 2: Dev Review, release-note

#27002 MM-58215 - Fixing error page
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
  webapp/channels/src/sass/routes/_error-page.scss
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#27021 Automated cherry pick of #27002
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
  webapp/channels/src/sass/routes/_error-page.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27008 MM-57860 - Check user belongs to remote when Shared Channels updates a user profile image
  server/channels/api4/remote_cluster.go
Labels: 4: Reviews Complete, release-note

#27007 MM-58257 - Use ConstantTimeCompare when comparing token.
  server/channels/app/session.go
Labels: 4: Reviews Complete, release-note

#26997 configure Loki for local development
  server/build/docker-compose-generator/main.go
  server/build/docker-compose.common.yml
  server/build/docker-compose.yml
  server/build/docker/grafana/dashboards/home.json
  server/build/docker/grafana/provisioning/datasources/loki.yml
  server/build/docker/prometheus.yml
  server/build/docker/promtail/promtail-local-config.yaml
  server/config.mk
  server/docker-compose.makefile.yml
  server/docker-compose.yaml
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#27024 Automated cherry pick of #27008
  server/channels/api4/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27025 Automated cherry pick of #27007
  server/channels/app/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27027 MM-58281 Allow client metrics to be floats and round timestamps
  server/channels/app/metrics.go
  server/public/model/metrics.go
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27028 Automated cherry pick of #27027
  server/channels/app/metrics.go
  server/public/model/metrics.go
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27041 [MM-53137] Remove flaky test
  server/channels/app/channel_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#27031 [MM-57857] Update prepackage calls to v0.27.0
  server/Makefile
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, AutoMerge, release-note

#27043 Automated cherry pick of #27031
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26984 Simplify how GlobalThreads fetches threads
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.test.tsx
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
  webapp/channels/src/components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.test.js
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/threads.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none

#27046 MM-58281 Change performance timestamps to be floats
  server/channels/api4/metrics_test.go
  server/public/model/metrics.go
  server/public/model/metrics_test.go
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27051 Automated cherry pick of #27046
  server/channels/api4/metrics_test.go
  server/public/model/metrics.go
  server/public/model/metrics_test.go
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27020 [MM-58271] User Profile pop up | Make Call button appear Disabled when user is on active call
  webapp/channels/src/components/profile_popover/profile_popover.scss
  webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/index.tsx
  webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/profile_popover_call_button_wrapper.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#27036 Removed message post limits warning
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/limits.go
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.test.ts
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/platform/types/src/limits.ts
Labels: Docs/Needed, CherryPick/Approved, release-note

#27019 Chore(cypress): Fix Known flaky test
  e2e-tests/cypress/tests/integration/channels/settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/announcement_banner_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_1_spec.js
Labels: release-note-none

#27042 CLD-7553 Implement per-MM_ENV runs, post the E2E test links back to user
  .github/workflows/e2e-fulltests-ci.yml
Labels: 4: Reviews Complete, release-note-none

#27062 Automated cherry pick of #27036
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/limits.go
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.test.ts
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/platform/types/src/limits.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27078 Manual cherrypick of #27036 for v9.8 - Removed message post limits warning
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/limits.go
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.test.ts
  webapp/channels/src/components/announcement_bar/post_limits_announcement_bar/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/platform/types/src/limits.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27083 Automated cherry pick of #27035
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/root/root.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27034 Lower user limit soft warning to 5K
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  webapp/channels/src/components/common/accordion/accordion_card.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, AutoMerge, release-note

#27086 Automated cherry pick of #27007
  server/channels/app/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27033 MM-58303 Report client metrics to Prometheus in seconds
  server/channels/app/metrics.go
  server/enterprise/metrics/metrics.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#27088 Automated cherry pick of #27034
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  webapp/channels/src/components/common/accordion/accordion_card.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27089 Automated cherry pick of #27033
  server/channels/app/metrics.go
  server/enterprise/metrics/metrics.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27075 MM-58328 - Fixing playbooks and boards layout
  webapp/channels/src/sass/base/_structure.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, EETests, release-note-none

#27018 MM-57863 - Check file attachment settings when sync'ing files for Shared Channels
  server/platform/services/sharedchannel/attachment.go
Labels: 4: Reviews Complete, release-note

#27048 MM-58262 Remove payload from RemoteClusterFrame audit
  server/public/model/remote_cluster.go
Labels: 4: Reviews Complete, release-note

#27090 Automated cherry pick of #27075
  webapp/channels/src/sass/base/_structure.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27091 Automated cherry pick of #27018
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27092 Automated cherry pick of #27048
  server/public/model/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26983 MM-57882 Add metric for the time it takes to open the Threads list
  server/channels/app/metrics.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/metrics.go
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
  webapp/channels/src/components/threading/global_threads_link/global_threads_link.tsx
  webapp/channels/src/utils/performance_telemetry/index.ts
Labels: 4: Reviews Complete, release-note

#27096 Automated cherry pick of #27018
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27047 Adds RemoteId to the fields to clean when coming from the API
  server/channels/api4/user_test.go
  server/public/model/user.go
Labels: 4: Reviews Complete, release-note-none

#27100 chore(e2e): Make EnableDiagnostics optional check
  e2e-tests/cypress/tests/support/index.js
Labels: release-note-none

#27052 [CLD-7742] Make location prop on ExternalLink component required
  webapp/channels/src/components/admin_console/group_settings/group_settings.tsx
  webapp/channels/src/components/admin_console/ip_filtering/save_confirmation_modal.tsx
  webapp/channels/src/components/admin_console/jobs/job_download_link.tsx
  webapp/channels/src/components/analytics/activated_users_card/title.tsx
  webapp/channels/src/components/external_link/__snapshots__/external_link.test.tsx.snap
  webapp/channels/src/components/external_link/external_link.test.tsx
  webapp/channels/src/components/external_link/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/main_menu/learn_about_teams_link.tsx
  webapp/channels/src/components/preparing_workspace/organization_status.tsx
  webapp/channels/src/components/reaction_limit_reached_modal.tsx
  webapp/channels/src/components/search_hint/search_hint.tsx
  webapp/channels/src/components/seats_calculator/consequences.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Labels: 4: Reviews Complete, release-note-none

#27006 [MM-58108] Posts missing channel_id in handleThreadReadChanged, handleAllThreadsInChannelMarkedRead, getThreadItemsInChannel
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/threads.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/threads.ts
  webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#27105 Cherry-pick of #27001 to release-9.9
  server/channels/app/channel.go
Labels: release-note-none

#27107 Automated cherry pick of #27007
  server/channels/app/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27108 Automated cherry pick of #27007
  server/channels/app/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27109 Automated cherry pick of #27007
  server/channels/app/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27113 Automated cherry pick of #27047
  server/channels/api4/user_test.go
  server/public/model/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27115 Automated cherry pick of #27047
  server/channels/api4/user_test.go
  server/public/model/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27116 Automated cherry pick of #27047
  server/channels/api4/user_test.go
  server/public/model/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27122 Cherry-pick of #27001 to release-9.5
  server/channels/app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27123 Cherry-pick of #27001 to release-9.8
  server/channels/app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27117 Automated cherry pick of #27047
  server/channels/api4/user_test.go
  server/public/model/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27118 Automated cherry pick of #27008
  server/channels/api4/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27119 Automated cherry pick of #27008
  server/channels/api4/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27120 Automated cherry pick of #27048
  server/public/model/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27121 Automated cherry pick of #27048
  server/public/model/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27110 Automated cherry pick of #27018
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27111 Automated cherry pick of #27018
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27112 Automated cherry pick of #27018
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27013 [MM-55485] Ensure user added to channel receives websocket event regardless of channel membership info retrieved in HA
  server/channels/app/channel.go
Labels: 4: Reviews Complete, Setup HA Cloud Test Server, release-note-none

#27038 Adding unsupported text into the team/e0 edition menu
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note

#27126 Automated cherry pick of #27038
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27094 [MM-58326] Remove aria-disabled for disabled tooltip in calls button following WithTooltip integration
  webapp/channels/src/components/profile_popover/profile_popover.scss
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/index.tsx
Labels: 4: Reviews Complete, release-note-none

#27049 Cleans RemoteId when sanitizing post input from the API
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/public/model/post.go
Labels: 4: Reviews Complete, release-note-none

#27128 Automated cherry pick of #27049
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/public/model/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27131 Automated cherry pick of #27049
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/public/model/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27130 Automated cherry pick of #27049
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/public/model/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27132 Automated cherry pick of #27049
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/public/model/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27044 Bump prepackage GitLab plugin version to 1.9.1
  server/Makefile
Labels: release-note

#27133 Automated cherry pick of #27125
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27134 Automated cherry pick of #27125
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27135 Automated cherry pick of #27125
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27136 Automated cherry pick of #27125
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27137 Automated cherry pick of #27125
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26957 MM-58025 Resolved automatic tz not reflecting without refresh by listening to app visibility event
  webapp/channels/src/components/logged_in/logged_in.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26808 ✨ feat(.github/holopin.yml): add holopin configuration file to manage…
  .github/holopin.yml
Labels: 4: Reviews Complete, release-note-none

#27084 [MM-58274] No side padding in plugins section of user profile popover
  webapp/channels/src/components/profile_popover/profile_popover.scss
  webapp/channels/src/components/profile_popover/profile_popover.tsx
Labels: 4: Reviews Complete, release-note-none

#27098 MM-58038: Use context to call master for DeletePost
  server/channels/api4/channel.go
  server/channels/api4/channel_local.go
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  server/channels/api4/preference.go
  server/channels/app/app_iface.go
  server/channels/app/channel.go
  server/channels/app/integration_action.go
  server/channels/app/integration_action_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/post_acknowledgements_test.go
  server/channels/app/post_metadata.go
  server/channels/app/post_test.go
  server/channels/app/reaction.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/file_info_layer.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
Labels: 4: Reviews Complete, EETests, release-note-none

#26992 [MM-57726] Convert AddIncomingWebhook from Class Component to Function Component
  webapp/channels/src/components/integrations/add_incoming_webhook/add_incoming_webhook.test.tsx
  webapp/channels/src/components/integrations/add_incoming_webhook/add_incoming_webhook.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#27056 Remove t from post and post textbox components
  webapp/channels/src/components/advanced_create_post/prewritten_chips.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_icon.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx
  webapp/channels/src/components/notify_confirm_modal.tsx
  webapp/channels/src/components/post_markdown/system_message_helpers.tsx
  webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx
  webapp/channels/src/components/post_view/combined_system_message/last_users.tsx
  webapp/channels/src/components/post_view/post_add_channel_member/post_add_channel_member.tsx
  webapp/channels/src/components/post_view/post_flag_icon/post_flag_icon.tsx
  webapp/channels/src/components/post_view/post_pre_header/post_pre_header.tsx
  webapp/channels/src/components/size_aware_image.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#27053 Remove t from invite-related code
  webapp/channels/src/actions/invite_actions.test.ts
  webapp/channels/src/actions/invite_actions.ts
  webapp/channels/src/components/channel_invite_modal/team_warning_banner/team_warning_banner.tsx
  webapp/channels/src/components/invitation_modal/invitation_modal.test.tsx
  webapp/channels/src/components/invitation_modal/invitation_modal.tsx
  webapp/channels/src/components/invitation_modal/invite_view.tsx
  webapp/channels/src/components/invitation_modal/result_table.test.tsx
  webapp/channels/src/components/invitation_modal/result_table.tsx
  webapp/channels/src/components/invitation_modal/result_view.tsx
  webapp/channels/src/components/preparing_workspace/invite_members.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.test.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.tsx
Labels: 4: Reviews Complete, release-note-none

#27055 Remove t from from cloud-related and license-related code
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.tsx
  webapp/channels/src/components/admin_console/billing/delete_workspace/progress_modal.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/index.tsx
  webapp/channels/src/components/announcement_bar/payment_announcement_bar/index.tsx
  webapp/channels/src/components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  webapp/channels/src/components/common/hooks/useExpandOverageUsersCheck.ts
  webapp/channels/src/components/common/hooks/useShowAdminLimitReached.ts
  webapp/channels/src/components/common/multi_select_cards/multi_select_card.tsx
  webapp/channels/src/components/downgrade_modal/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
  webapp/channels/src/components/preparing_workspace/plugins.tsx
  webapp/channels/src/components/pricing_modal/starter_disclaimer_cta.tsx
  webapp/channels/src/components/purchase_modal/icon_message.tsx
  webapp/channels/src/components/start_trial_form_modal/index.tsx
Labels: 4: Reviews Complete, release-note-none

#27058 Remove t from miscellaneous components
  webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
  webapp/channels/src/components/error_page/__snapshots__/error_message.test.tsx.snap
  webapp/channels/src/components/error_page/error_link.test.tsx
  webapp/channels/src/components/error_page/error_link.tsx
  webapp/channels/src/components/error_page/error_message.tsx
  webapp/channels/src/components/integrations/add_incoming_webhook/add_incoming_webhook.tsx
  webapp/channels/src/components/integrations/add_oauth_app/add_oauth_app.tsx
  webapp/channels/src/components/integrations/add_outgoing_webhook/add_outgoing_webhook.tsx
  webapp/channels/src/components/integrations/edit_command/edit_command.tsx
  webapp/channels/src/components/integrations/edit_incoming_webhook/edit_incoming_webhook.tsx
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  webapp/channels/src/components/no_results_indicator/__snapshots__/no_results_indicator.test.tsx.snap
  webapp/channels/src/components/no_results_indicator/no_results_indicator.tsx
  webapp/channels/src/components/search_results/search_results.tsx
  webapp/channels/src/components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category.tsx
  webapp/channels/src/components/threading/common/follow_button/follow_button.tsx
  webapp/channels/src/components/threading/global_threads/thread_menu/thread_menu.tsx
  webapp/channels/src/components/threading/global_threads/thread_pane/thread_pane.tsx
  webapp/channels/src/components/threading/global_threads_link/global_threads_link.tsx
  webapp/channels/src/components/tours/channels_tour_tip.tsx
Labels: 4: Reviews Complete, release-note-none

#26644 [MM-57384] Investigate app performance on repeated calls to `users/status/ids` and `users/ids` calls on posted event
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/actions/status_actions.test.ts
  webapp/channels/src/actions/status_actions.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/channel_layout/channel_controller.test.tsx
  webapp/channels/src/components/channel_layout/channel_controller.tsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/status_profile_polling.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#27159 MM-58359 Add page_load to Prometheus metrics
  server/channels/app/metrics.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/metrics.go
  webapp/channels/src/utils/performance_telemetry/index.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 4: Reviews Complete, release-note

#27054 Remove t from system console code
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.test.tsx
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/announcement_banner.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/compliance_export.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/custom_terms_of_service.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/data_retention.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/groups.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/guest_access.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/ldap.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/openid.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/openid_custom.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/saml.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/system_roles.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_button/edit_post_time_limit_button.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/team_list/abstract_list.test.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/abstract_list.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/abstract_list.test.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/abstract_list.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/convert_and_remove_confirm_modal.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/convert_confirm_modal.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.test.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/group/index.ts
  webapp/channels/src/components/admin_console/team_channel_settings/remove_confirm_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#27147 MM-58367 Increase maximum bucket size for LCP metrics
  server/enterprise/metrics/metrics.go
Labels: 2: Dev Review, release-note

#27106 MM-58348 Add missing query parameters to GetTeamMembers API doc
  api/v4/source/teams.yaml
Labels: 4: Reviews Complete, EETests, release-note-none

#27015 MM-58183 Post Error Style Fixes
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#27143 MM-57867 Don't delete existing channel on invitation error
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/public/model/shared_channel.go
Labels: 4: Reviews Complete, release-note

#27189 feat: Introduce build env image pipeline
  .github/workflows/build-server-image.yml
  server/build/Dockerfile.buildenv
Labels: 2: Dev Review, kind/bug, release-note-none

#27190 fix: Fix missing paths for build env docker image
  .github/workflows/build-server-image.yml
Labels: kind/bug, release-note-none

#27124 Add ServiceSettings.MaximumPayloadSize to SystemConsole
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#27191 fix: Fix buildEnv Dockerfile path
  .github/workflows/build-server-image.yml
Labels: 2: Dev Review, kind/bug, release-note-none

#27194 fix: Update download action with the official one
  .github/workflows/server-ci-artifacts.yml
  .github/workflows/server-ci-template.yml
Labels: 2: Dev Review, kind/bug, release-note-none

#27184 MM-58116 Increase width of profile picture setting
  webapp/channels/src/components/__snapshots__/setting_picture.test.tsx.snap
  webapp/channels/src/components/setting_picture.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#27171 [CLD-7724] Allow admin-set announcement banners to stack below system ones
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note
