Repository mattermost/mattermost, pull requests merged in 2024-10, with the labels that each got.

#28330 [MM-60328] cmd/mmctl/user: attempt to improve migrate-auth documentation
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/docs/mmctl_user_migrate-auth.rst
Labels: 4: Reviews Complete, release-note-none

#28358 [GH-28353] Fix errcheck issues in server/channels/api4/channel_bookmark_test.go
  server/.golangci.yml
  server/channels/api4/channel_bookmark_test.go
Labels: 4: Reviews Complete, release-note, Contributor

#28370 Excluded draft checks from scheduled posts
  webapp/channels/src/components/drafts/draft_row.tsx
Labels: release-note-none

#28359 Fixed a bug where files in scheduled post didn't show up until refresh
  webapp/channels/src/actions/views/create_comment.tsx
  webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
Labels: release-note-none

#28364 Errcheck issues fixed in server/channels/api4/brand_test.go
  server/.golangci.yml
  server/channels/api4/brand_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28288 Add Hacktoberfest 2024 Holopin badge to holopin.yml
  .github/holopin.yml
Labels: 4: Reviews Complete, release-note-none

#28312 MM-60351 Use oEmbed for YouTube links
  server/channels/app/oembed/endpoint.go
  server/channels/app/oembed/endpoint_test.go
  server/channels/app/oembed/generator/.gitignore
  server/channels/app/oembed/generator/providers.go.tmpl
  server/channels/app/oembed/generator/providers_generator.go
  server/channels/app/oembed/oembed.go
  server/channels/app/oembed/providers_gen.go
  server/channels/app/opengraph.go
  server/channels/app/post_metadata.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note

#28373 Automated cherry pick of #28312
  server/channels/app/oembed/endpoint.go
  server/channels/app/oembed/endpoint_test.go
  server/channels/app/oembed/generator/.gitignore
  server/channels/app/oembed/generator/providers.go.tmpl
  server/channels/app/oembed/generator/providers_generator.go
  server/channels/app/oembed/oembed.go
  server/channels/app/oembed/providers_gen.go
  server/channels/app/opengraph.go
  server/channels/app/post_metadata.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28374 Automated cherry pick of #28312
  server/channels/app/oembed/endpoint.go
  server/channels/app/oembed/endpoint_test.go
  server/channels/app/oembed/generator/.gitignore
  server/channels/app/oembed/generator/providers.go.tmpl
  server/channels/app/oembed/generator/providers_generator.go
  server/channels/app/oembed/oembed.go
  server/channels/app/oembed/providers_gen.go
  server/channels/app/opengraph.go
  server/channels/app/post_metadata.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28375 MM-60351 Use oEmbed for YouTube links (#28312) (9.5)
  server/channels/app/oembed/endpoint.go
  server/channels/app/oembed/endpoint_test.go
  server/channels/app/oembed/oembed.go
  server/channels/app/oembed/providers_gen.go
  server/channels/app/opengraph.go
  server/channels/app/post_metadata.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#28320 MM-60125 - Scheduled post channel indicator
  webapp/channels/src/actions/views/create_comment.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/post_box_indicator/post_box_indicator.tsx
  webapp/channels/src/components/advanced_text_editor/post_box_indicator/style.scss
  webapp/channels/src/components/advanced_text_editor/remote_user_hour.tsx
  webapp/channels/src/components/advanced_text_editor/scheduled_post_indicator/scheduled_post_indicator.scss
  webapp/channels/src/components/advanced_text_editor/scheduled_post_indicator/scheduled_post_indicator.tsx
  webapp/channels/src/components/advanced_text_editor/scheduled_post_indicator/short_scheduled_post_indicator.tsx
  webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
  webapp/channels/src/components/drafts/panel/panel_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/platform/types/src/schedule_post.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#28337 Error when generating invite codes for a confirmed remote cluster
  api/v4/source/remoteclusters.yaml
  server/channels/api4/remote_cluster.go
  server/channels/api4/remote_cluster_test.go
  server/i18n/en.json
Labels: release-note-none

#28357 [GH-28355] Fixed errcheck issues in server/channels/api4/channel_category.go
  server/.golangci.yml
  server/channels/api4/channel_category.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28403 Fixed errcheck issues in server/channels/api4/file.go
  server/.golangci.yml
  server/channels/api4/file.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28272 [MM57343] Add unit tests to Team Groups Management Modal
  webapp/channels/src/components/confirm_modal.tsx
  webapp/channels/src/components/team_groups_manage_modal/team_groups_manage_modal.test.tsx
  webapp/channels/src/components/team_groups_manage_modal/team_groups_manage_modal.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_item.tsx
Labels: 4: Reviews Complete, hacktoberfest-accepted, release-note-none, Contributor

#28405 Fixed errcheck issues in server/channels/api4/image_test.go
  server/.golangci.yml
  server/channels/api4/image_test.go
Labels: 4: Reviews Complete, Hacktoberfest, QA/Deferred, release-note-none, Contributor

#28413 server/Makefile: bump mattermost-plugin-metrics version
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#28415 Automated cherry pick of #28413
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28414 Revert MM-58726 & MM-60284 from v10.1
  webapp/channels/package.json
  webapp/channels/src/components/initial_loading_screen/index.ts
  webapp/channels/src/components/initial_loading_screen/initial_loading_screen.css
  webapp/channels/src/components/initial_loading_screen/initial_loading_screen_class.ts
  webapp/channels/src/components/initial_loading_screen/initial_loading_screen_template.html
  webapp/channels/src/components/no_script/no_script_template.html
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/root.html
  webapp/channels/webpack.config.js
  webapp/package-lock.json
Labels: 2: Dev Review, release-note-none

#28419 Automated cherry pick of #28366
  server/channels/api4/plugin_test.go
  server/channels/app/plugin.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28422 Automated cherry pick of #28366
  server/channels/api4/plugin_test.go
  server/channels/app/plugin.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28421 MM-50347 Make desktop app landing page optional
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#28426 Disable PerformanceReporter tests
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
Labels: 2: Dev Review, release-note-none

#28269 Avoid resetting device id when removed from push proxy
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/storetest/session_store.go
  server/public/model/session.go
Labels: release-note

#28439 Automated cherry pick of #28302
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28300 [MM-60253] Avoid unnecessary cache clearing during LDAP sync
  server/channels/app/channel.go
  server/channels/app/syncables.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/TeamStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note

#28480 Prepackage Calls v0.29.2 in v9.5
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#28477 Fixed errcheck issues in server/channels/api4/oauth.go
  server/.golangci.yml
  server/channels/api4/oauth.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28406 Errcheck issues fixed in server/channels/api4/group_test.go
  server/.golangci.yml
  server/channels/api4/group_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28332 MM 60445 - fix preparing workspace wrong redirect
  webapp/channels/src/components/root/root_redirect/index.ts
  webapp/channels/src/components/root/root_redirect/root_redirect.test.tsx
  webapp/channels/src/components/root/root_redirect/root_redirect.tsx
Labels: 4: Reviews Complete, 3: QA Review, Setup Cloud Test Server, release-note-none

#28216 [MM-56033]Added unit tests for UpdateUserCustomStatus and RemoveUserCustomStatu…
  server/channels/api4/status_test.go
Labels: 4: Reviews Complete, EETests, release-note-none, Contributor

#28476 Fixed errcheck issues in server/channels/api4/post.go
  server/.golangci.yml
  server/channels/api4/post.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28416 Fixed errcheck issues in server/channels/api4/integration_action.go
  server/.golangci.yml
  server/channels/api4/integration_action.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28427 Update index.ts (Filter archived channel from dropdown)
  webapp/channels/src/components/channel_select/index.ts
Labels: 2: Dev Review, Hacktoberfest, 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#28418 Fixed errcheck issues in server/channels/api4/ldap.go
  server/.golangci.yml
  server/channels/api4/ldap.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28475 Fixed errcheck issues in server/channels/api4/permission.go
  server/.golangci.yml
  server/channels/api4/permission.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#27919 [MM-59089] Add a compliance export constant
  server/i18n/en.json
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note-none

#26847 [MM-57991] Add log message about deleted rows from Data Retention job
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/sqlstore/retention_policy_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#28404 Fixed errcheck issues in server/channels/api4/group.go
  server/.golangci.yml
  server/channels/api4/group.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28516 fix: reaction test errcheck issues
  server/.golangci.yml
  server/channels/api4/reaction_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28557 Fixed errcheck issues in server/channels/api4/license_test.go
  server/.golangci.yml
  server/channels/api4/license_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28542 fix: shared channel errcheck issues
  server/.golangci.yml
  server/channels/api4/shared_channel.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28539 fix: system local errcheck issues
  server/.golangci.yml
  server/channels/api4/system_local.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28310 [MM-54021][MM-58736] Remove limit on loading channel members on initial load, reload members on reconnect, separate loading of members from channels on initial load
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/team_controller/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#28537 fix: system errcheck issues
  server/.golangci.yml
  server/channels/api4/system.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28581 Translations update from Mattermost Weblate
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
Labels: Hacktoberfest, release-note-none, Do Not Merge/Mattermod

#28345 Errcheck issues fixed
  server/channels/api4/bot_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28315 [CLD-8377] Add ability to open invitation modal from a query parameter
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/components/channel_layout/channel_controller.test.tsx
  webapp/channels/src/components/channel_layout/channel_controller.tsx
  webapp/channels/src/components/invitation_modal/no_permissions_view.scss
  webapp/channels/src/components/invitation_modal/no_permissions_view.tsx
  webapp/channels/src/components/query_param_actions/query_param_action_controller.test.tsx
  webapp/channels/src/components/query_param_actions/query_param_action_controller.tsx
  webapp/channels/src/components/root/actions/index.ts
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/root/root_redirect/root_redirect.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#28333 Emit license details to logs when added or removed
  server/channels/app/platform/license.go
Labels: 2: Dev Review, QA/Review Not Required, release-note

#28538 fix: team local errcheck issues
  server/.golangci.yml
  server/channels/api4/team_local.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28441 [GH-28396] Fixed errcheck issues in server/channels/api4/ip_filtering.go
  server/.golangci.yml
  server/channels/api4/ip_filtering.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28409 Fixed errcheck issues in server/channels/api4/handlers_test.go
  server/.golangci.yml
  server/channels/api4/handlers_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28556 Fixed errcheck issues in server/channels/api4/preference_test.go
  server/.golangci.yml
  server/channels/api4/preference_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28555 Fixed errcheck issues in server/channels/api4/outgoing_oauth_connection_test.go
  server/.golangci.yml
  server/channels/api4/outgoing_oauth_connection_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28479 Removed unused code from actions/views/create_comment.tsx
  webapp/channels/src/actions/views/create_comment.test.jsx
  webapp/channels/src/actions/views/create_comment.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, 2: Dev Review, release-note-none

#28485 Scheduled post config
  server/channels/api4/scheduled_post.go
  server/channels/app/scheduled_post_job.go
  server/channels/app/scheduled_post_job_test.go
  server/config/client.go
  server/i18n/en.json
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/advanced_text_editor/post_box_indicator/post_box_indicator.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx
  webapp/channels/src/components/advanced_text_editor/send_button/style.scss
  webapp/channels/src/components/drafts/drafts.tsx
  webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
  webapp/platform/types/src/config.ts
Labels: release-note-none

#28579 MM-60118 - Added index on ScheduledPosts table
  server/channels/db/migrations/mysql/000128_create_scheduled_posts.down.sql
  server/channels/db/migrations/mysql/000128_create_scheduled_posts.up.sql
  server/channels/db/migrations/postgres/000128_create_scheduled_posts.down.sql
  server/channels/db/migrations/postgres/000128_create_scheduled_posts.up.sql
Labels: release-note-none

#28513 fix: reaction errcheck issues
  server/.golangci.yml
  server/channels/api4/reaction.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28440 Update emoji_test.go (fix errcheck issue)
  server/.golangci.yml
  server/channels/api4/emoji_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28576 Automated cherry pick of #28300
  server/channels/app/channel.go
  server/channels/app/syncables.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/TeamStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28578 Automated cherry pick of #28300
  server/channels/app/channel.go
  server/channels/app/syncables.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/TeamStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR, release-note-none

#28544 fix: role errcheck issues
  server/.golangci.yml
  server/channels/api4/role.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28417 Fixed errcheck issues in server/channels/api4/group_local.go
  server/.golangci.yml
  server/channels/api4/group_local.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28407 Fix Errcheck issues in server/channels/api4/export.go
  server/.golangci.yml
  server/channels/api4/export.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28625 Scheduled posts misc fixes
  server/channels/app/scheduled_post_job.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/scheduled_post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ScheduledPostStore.go
  server/channels/store/storetest/scheduled_post_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/public/model/scheduled_post.go
  webapp/channels/src/components/drafts/utils.ts
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/schedule_post.ts
Labels: release-note-none

#28630 MM-60784 - Fix delete scheduled post on deleted thread
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
Labels: release-note-none

#28609 Fixed errcheck issues in server/channels/api4/webhook.go
  server/.golangci.yml
  server/channels/api4/webhook.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28482 refactor: convert channel_moderation files to ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/channel_mentions_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/constants.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/create_posts_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/helpers.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/higher_scoped_scheme_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/manage_members_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/post_reactions_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/system_config_spec.ts
  e2e-tests/cypress/tests/support/env.ts
  e2e-tests/cypress/tests/support/external_commands.ts
Labels: Hacktoberfest, release-note-none, Contributor, kind/refactor

#28551 fix: shared channel test errcheck issues
  server/.golangci.yml
  server/channels/api4/shared_channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28546 Fix errcheck issue for saml.go file
  server/.golangci.yml
  server/channels/api4/saml.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#27539 [MM-56073] MMCTL delete post command
  e2e-tests/cypress/tests/integration/channels/messaging/message_deletion_spec.js
  e2e-tests/cypress/tests/support/api_commands.ts
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/post.go
  server/channels/api4/post_local.go
  server/channels/api4/post_test.go
  server/channels/app/app_iface.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_test.go
  server/channels/app/user.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/file_info_layer.go
  server/channels/store/searchlayer/post_layer.go
  server/channels/store/searchtest/file_info_layer.go
  server/channels/store/searchtest/post_layer.go
  server/channels/store/sqlstore/file_info_store.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/file_info_store.go
  server/channels/store/storetest/mocks/FileInfoStore.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/post.go
  server/cmd/mmctl/commands/post_test.go
  server/cmd/mmctl/docs/mmctl_post.rst
  server/cmd/mmctl/docs/mmctl_post_delete.rst
  server/cmd/mmctl/mocks/client_mock.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/client4.go
  server/public/model/config.go
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#28335 Avoid using token from sanitized remote cluster
  server/channels/api4/remote_cluster.go
  server/channels/api4/remote_cluster_test.go
Labels: release-note-none

#28561 Integration action test
  server/.golangci.yml
  server/channels/api4/integration_action_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#27808 MM-47291 refactor: migrate collapsed_reply_threads to ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/channel_notifications_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/crt_settings_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/crt_tour_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/files_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/files_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/following_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/global_threads_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/last_viewed_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/open_thread_dm_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/replies_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/unread_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.ts
  e2e-tests/cypress/tests/support/task_commands.ts
  e2e-tests/cypress/tests/utils/plugins.js
Labels: Hacktoberfest, release-note-none, Contributor, kind/refactor

#28349 MM-47297 refactor: convert auth_sso files to ts
  e2e-tests/cypress/tests/integration/channels/enterprise/auth_sso/authentication_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/auth_sso/mfa_authentication_spec.ts
Labels: Hacktoberfest, release-note-none, Contributor, kind/refactor

#28574 Fix the response type of create bookmark in go client
  server/public/model/client4.go
Labels: 4: Reviews Complete, release-note-none

#28632 [MM-60851] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/system_notice/notices.tsx' with FormattedMessage
  webapp/channels/src/components/system_notice/notices.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28633 [MM-60849] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/outgoing_oauth_connections/installed_outgoing_oauth_connections.tsx' with FormattedMessagewith FormattedMessage
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/installed_outgoing_oauth_connections.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/installed_outgoing_oauth_connections.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28619 [MM-60833] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/group_settings/group_details/group_users.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_users.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/group_users.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28464 [MM-60789] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/channel_selector_modal/channel_selector_modal.tsx' with FormattedMessage
  webapp/channels/src/components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  webapp/channels/src/components/channel_selector_modal/channel_selector_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28641 [MM-60932] Fix errcheck issues in server/channels/api4/usage.go
  server/.golangci.yml
  server/channels/api4/usage.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28543 fix: scheme errcheck issues
  server/.golangci.yml
  server/channels/api4/scheme.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28531 fix: plugin test errcheck issues
  server/.golangci.yml
  server/channels/api4/plugin_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28275 [MM-59308] Cypress end to end test for channel header modal
  e2e-tests/cypress/tests/integration/channels/channel/channel_header_modal_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#28492 CLD-8395 Integrate playwright into E2E tests
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  .gitignore
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/dashboard.generate_test_cycle.sh
  e2e-tests/.ci/report.collect.sh
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.run_playwright.sh
  e2e-tests/README.md
  e2e-tests/playwright/.eslintrc.json
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/playwright.config.ts
  e2e-tests/playwright/report.webhookgen.js
Labels: 4: Reviews Complete, release-note-none

#28483 MM-47288 refactor: convert channels/channel/ files to ts
  e2e-tests/cypress/tests/integration/channels/channel/archived_channels_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/archived_channels_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/browse_channels_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/browse_public_channels_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_bookmarks_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_info_rhs_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_members_rhs_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_mention_autocomplete_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_name_tooltips_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_routing_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_settings_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_switcher_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/close_direct_group_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/convert_channel_to_private_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/convert_group_message_to_private_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/leave_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/user_to_admin_updates_manage_channel_members_rhs_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/user_to_channel_admin_member_updates_manage_channel_members_rhs_spec.ts
  e2e-tests/cypress/tests/support/api/role.d.ts
  e2e-tests/cypress/tests/support/api/user.d.ts
  e2e-tests/cypress/tests/support/ui/search.ts
  e2e-tests/cypress/tests/support/ui_commands.ts
Labels: Hacktoberfest, release-note-none, Contributor, kind/refactor

#28548 fix errcheck issue
  server/.golangci.yml
  server/channels/api4/import_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28644 Fixed errcheck issues in server/channels/api4/usage_test.go
  server/.golangci.yml
  server/channels/api4/usage_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28541 fix: status test errcheck issues
  server/.golangci.yml
  server/channels/api4/status_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28116 MM-58349: Shared Channels in System Console
  api/v4/source/sharedchannels.yaml
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/shared_channel.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/list_table/list_table.tsx
  webapp/channels/src/components/admin_console/secure_connections/building.svg.tsx
  webapp/channels/src/components/admin_console/secure_connections/chat.svg.tsx
  webapp/channels/src/components/admin_console/secure_connections/controls.tsx
  webapp/channels/src/components/admin_console/secure_connections/index.ts
  webapp/channels/src/components/admin_console/secure_connections/modals/modal_utils.tsx
  webapp/channels/src/components/admin_console/secure_connections/modals/secure_connection_accept_invite_modal.tsx
  webapp/channels/src/components/admin_console/secure_connections/modals/secure_connection_create_invite_modal.tsx
  webapp/channels/src/components/admin_console/secure_connections/modals/secure_connection_delete_modal.tsx
  webapp/channels/src/components/admin_console/secure_connections/modals/shared_channels_add_modal.tsx
  webapp/channels/src/components/admin_console/secure_connections/modals/shared_channels_remove_modal.tsx
  webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx
  webapp/channels/src/components/admin_console/secure_connections/secure_connection_row.tsx
  webapp/channels/src/components/admin_console/secure_connections/secure_connections.tsx
  webapp/channels/src/components/admin_console/secure_connections/team_selector.tsx
  webapp/channels/src/components/admin_console/secure_connections/utils.test.ts
  webapp/channels/src/components/admin_console/secure_connections/utils.ts
  webapp/channels/src/components/admin_console/team_channel_settings/save_changes_panel.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/common/hooks/useCopyText.ts
  webapp/channels/src/components/section_notice.scss
  webapp/channels/src/components/section_notice.test.tsx
  webapp/channels/src/components/section_notice.tsx
  webapp/channels/src/components/widgets/inputs/channels_input.scss
  webapp/channels/src/components/widgets/inputs/channels_input.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/components/src/generic_modal/generic_modal.tsx
  webapp/platform/types/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/remote_clusters.ts
  webapp/platform/types/src/shared_channels.ts
  webapp/platform/types/src/utilities.ts
Labels: QA/Review Done, release-note-none, 1. UX Review

#28517 fix: plugin errcheck issues
  server/.golangci.yml
  server/channels/api4/plugin.go
Labels: 4: Reviews Complete, Hacktoberfest, QA/Review Done, release-note-none, Contributor

#28663 Enhance reporting, add shellcheck (#28240)
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/.ci/report.collect.sh
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.start.sh
  e2e-tests/Makefile
  e2e-tests/README.md
Labels: release-note-none

#28665 Automated cherry pick of #28240
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/.ci/report.collect.sh
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.start.sh
  e2e-tests/Makefile
  e2e-tests/README.md
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28362 Errcheck issues fixed in server/channels/api4/brand.go
  server/.golangci.yml
  server/channels/api4/brand.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28199 MM 57516 - deactivate actions to ldap users
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/i18n/en.json
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.test.tsx
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.test.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#28654 [MM-60844] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/session_length_settings.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/session_length_settings.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28651 [MM-60838] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/billing/company_info_display.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/billing/company_info_display.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28682 Automated cherry pick of #28279
  e2e-tests/.ci/server.generate.sh
  e2e-tests/playwright/README.md
  e2e-tests/playwright/global_setup.ts
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/support/flag.ts
  e2e-tests/playwright/support/server/client.ts
  e2e-tests/playwright/support/server/init.ts
  e2e-tests/playwright/support/test_fixture.ts
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/landing_page.spec.ts-snapshots/landing-login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/login.spec.ts-snapshots/login-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e-tests/playwright/tests/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  webapp/platform/types/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28684 Automated cherry pick of #28492
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  .gitignore
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/dashboard.generate_test_cycle.sh
  e2e-tests/.ci/report.collect.sh
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.run_cypress.sh
  e2e-tests/.ci/server.run_playwright.sh
  e2e-tests/README.md
  e2e-tests/playwright/.eslintrc.json
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/playwright.config.ts
  e2e-tests/playwright/report.webhookgen.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#28679 Removed the max/min family of functions
  server/channels/app/notification.go
  server/channels/app/platform/service.go
  server/channels/app/platform/utils.go
  server/channels/store/localcachelayer/layer.go
  server/channels/store/sqlstore/shared_channel_store.go
  server/channels/store/sqlstore/utils.go
  server/public/pluginapi/cluster/mock_plugin_api_test.go
Labels: 4: Reviews Complete, release-note-none

#28678 Remove remaining references to model.NewXX
  server/channels/app/import_functions_test.go
  server/cmd/mmctl/commands/sampledata_util.go
  server/public/model/builtin.go
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note-none

#28639 MM-60786 - Fixed width of generic modal header to fix browser channel modal
  webapp/platform/components/src/generic_modal/generic_modal.scss
Labels: Setup Cloud Test Server, release-note-none

#28671 [MM-60842] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28681 store: use Builder
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/storetest/reaction_store.go
Labels: 4: Reviews Complete, release-note-none

#28139 MM-48231 refactor: convert file fetch_commands.js to ts
  e2e-tests/cypress/tests/support/fetch_commands.ts
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor, kind/refactor

#28608 [MM-60812] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_profile.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_profile.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note-none, Contributor

#28554 [MM-60809] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note-none, Contributor

#28577 [MM-60819] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/bots/bots.tsx' with FormattedMessage
  webapp/channels/src/components/backstage/components/backstage_list.tsx
  webapp/channels/src/components/integrations/bots/bots.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, release-note-none, Contributor

#28286 [MM-58834] Review user preferences export and import
  server/channels/app/export.go
  server/channels/app/export_converters.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/imports/import_types.go
  server/channels/app/user.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/storetest/post_store.go
  server/public/model/post.go
  server/public/model/preference.go
Labels: 4: Reviews Complete, release-note

#28652 [MM-60839] Remove unused 'webapp/channels/src/components/admin_console/billing/payment_details.tsx'
  webapp/channels/src/components/admin_console/billing/payment_details.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28668 [MM-60840] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28683 Only consider error-free scheduled posts for indicator in channel and RHS
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
Labels: Setup Cloud Test Server, release-note-none

#28680 Fixed draft and scheduled post UI in mobile view
  webapp/channels/src/components/drafts/drafts.scss
Labels: Setup Cloud Test Server, release-note-none

#28656 MM-60873 and MM-60872 - Fixed a bug with updating scheduled posts
  server/channels/app/scheduled_post.go
  server/channels/app/scheduled_post_job_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/scheduled_post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ScheduledPostStore.go
  server/channels/store/storetest/scheduled_post_store.go
  server/channels/store/timerlayer/timerlayer.go
  webapp/channels/src/components/drafts/scheduled_post_list/style.scss
Labels: 2: Dev Review, QA/Review Done, release-note-none

#28612 [MM-60821] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/installed_oauth_app/installed_oauth_app.tsx' with FormattedMessage
  webapp/channels/src/components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.tsx.snap
  webapp/channels/src/components/integrations/installed_oauth_app/installed_oauth_app.tsx
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/installed_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/installed_outgoing_oauth_connection.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28613 [MM-60827] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/suggestion/suggestion_list.tsx' with FormattedMessage
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28575 [MM-60828] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/team_selector_modal/team_selector_modal.tsx' with FormattedMessage
  webapp/channels/src/components/team_selector_modal/team_selector_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28519 [MM-60823] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/invitation_modal/add_to_channels.tsx' with FormattedMessage
  webapp/channels/src/components/invitation_modal/add_to_channels.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28622 [MM-60835] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/actions_menu/actions_menu.tsx' with FormattedMessage
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  webapp/channels/src/components/actions_menu/actions_menu.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28629 [MM-60830] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/user_list_row/user_list_row.tsx' with FormattedMessage
  webapp/channels/src/components/user_list_row/user_list_row.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28631 [MM-60852] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.tsx' with FormattedMessage
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28635 [MM-60836] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/message_export_settings.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/message_export_settings.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28552 [MM-60808] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28621 [MM-60834] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/select_team/select_team.tsx' with FormattedMessage
  webapp/channels/src/components/select_team/index.ts
  webapp/channels/src/components/select_team/select_team.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28623 [MM-60837] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/user_settings/security/user_access_token_section/user_access_token_section.tsx' with FormattedMessage
  webapp/channels/src/components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28607 [MM-60818] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx' with FormattedMessage
  webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28628 [MM-60825] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/mfa/setup/setup.tsx' with FormattedMessage
  webapp/channels/src/components/mfa/setup/setup.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28642 [MM-60817] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx' with FormattedMessage
  webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28547 [MM-60824] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/leave_team_modal/leave_team_modal.tsx' with FormattedMessage
  webapp/channels/src/components/leave_team_modal/__snapshots__/leave_team_modal.test.tsx.snap
  webapp/channels/src/components/leave_team_modal/leave_team_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28438 [MM-60788] Replace FormattedMarkdownMessage in custom_enable_disable_guest_accounts_setting, delete_channel_modal, signup.tsx & create_comment.tsx
  webapp/channels/src/components/admin_console/__snapshots__/custom_enable_disable_guest_accounts_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
  webapp/channels/src/components/delete_channel_modal/__snapshots__/delete_channel_modal.test.tsx.snap
  webapp/channels/src/components/delete_channel_modal/delete_channel_modal.tsx
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/create_comment.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#28693 Fixed errcheck issues in server/channels/api4/upload_test.go
  server/.golangci.yml
  server/channels/api4/upload_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28691 MM-60926: updated system_test.go to pass linter
  server/.golangci.yml
  server/channels/api4/system_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28620 MM-60541 Don't save an unmodified draft when changing channels
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#28614 [MM-60814] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/authorize/authorize.tsx' with FormattedMessage
  webapp/channels/src/components/authorize/authorize.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28657 [MM-60841] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/group_settings/group_details/group_profile_and_settings.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/group_settings/group_details/group_profile_and_settings.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28672 [MM-60850] FormattedMarkdownMessage in 'webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx' with FormattedMessage
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28643 Fixed errcheck issues in server/channels/api4/user_local.go
  server/.golangci.yml
  server/channels/api4/user_local.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28301 [MM-60422] Add GetChannelsWithActivityDuring
  server/channels/app/channel_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_member_history_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_member_history_store.go
  server/channels/store/storetest/mocks/ChannelMemberHistoryStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/config.go
  webapp/channels/src/components/admin_console/message_export_settings.test.tsx
  webapp/channels/src/components/admin_console/message_export_settings.tsx
Labels: 4: Reviews Complete, release-note

#28371 feat: E2E send test notifications
  e2e-tests/cypress/tests/integration/channels/test_notification/trigger_browser_notification_spec.ts
  e2e-tests/cypress/tests/support/index.js
  e2e-tests/cypress/tests/support/notification_commands.ts
Labels: release-note-none

#28688 Update root post update at on reply delete
  server/channels/store/sqlstore/post_store.go
  server/channels/store/storetest/post_store.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#28717 [MM-60553] Prepackage Calls v1.2.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#28721 Automated cherry pick of #28717
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28720 Automated cherry pick of #28688
  server/channels/store/sqlstore/post_store.go
  server/channels/store/storetest/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#28677 MM-47280 refactor: convert channels/ad_ldap files to ts
  e2e-tests/cypress/tests/integration/channels/ad_ldap/saml_ldap_sync_id_attrib_spec.ts
  e2e-tests/cypress/tests/integration/channels/ad_ldap/saml_ldap_sync_remove_spec.ts
  e2e-tests/cypress/tests/integration/channels/ad_ldap/saml_ldap_sync_spec.ts
  e2e-tests/cypress/tests/support/ldap_commands.d.ts
  e2e-tests/cypress/tests/support/ldap_server_commands.d.ts
  e2e-tests/cypress/tests/support/ldap_server_commands.ts
Labels: Hacktoberfest, release-note-none, Contributor, kind/refactor

#28675 [MM-60843] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx' with FormattedMessage
  webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28673 [MM-60847] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/installed_oauth_apps/installed_oauth_apps.tsx' with FormattedMessage
  webapp/channels/src/components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.tsx.snap
  webapp/channels/src/components/integrations/installed_oauth_apps/installed_oauth_apps.tsx
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28545 fix: role test errcheck issues
  server/.golangci.yml
  server/channels/api4/role_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28710 server: Fix typo in Makefile
  server/Makefile
  server/cmd/mmctl/commands/channel_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor

#28655 [MM-60846] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.tsx' with FormattedMessage
  webapp/channels/src/components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA/Deferred, release-note-none, Contributor

#28645 Fixed errcheck issues in server/channels/api4/oauth_test.go
  server/.golangci.yml
  server/channels/api4/oauth_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor
