Repository mattermost/mattermost, pull requests merged in 2024-03, with the labels that each got.

#26357 Manual Cherry-pick of 25510 (#26355)
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/emoji_test.go
  server/channels/api4/post.go
  server/channels/api4/reaction.go
  server/channels/api4/role.go
  server/channels/api4/role_test.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/client4.go
  server/public/model/config.go
  server/public/model/utils.go
  server/public/model/utils_test.go
  tools/mmgotool/commands/i18n.go
Labels: release-note-none

#26351 Automated cherry pick of #25943
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/i18n/en.json
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26352 Automated cherry pick of #25943
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/i18n/en.json
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26339 Automated cherry pick of #25579
  api/v4/source/preferences.yaml
  server/channels/api4/preference.go
  server/channels/api4/preference_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26340 Automated cherry pick of #25579
  api/v4/source/preferences.yaml
  server/channels/api4/preference.go
  server/channels/api4/preference_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26298 MM-56987: Improve cache API
  server/channels/app/platform/session.go
  server/channels/store/localcachelayer/terms_of_service_layer.go
  server/platform/services/cache/cache.go
  server/platform/services/cache/lru_test.go
  server/platform/services/cache/provider_test.go
Labels: 4: Reviews Complete, release-note-none

#26244 Implement plugin KV store in memory
  server/public/pluginapi/experimental/common/kvstore.go
  server/public/pluginapi/kv.go
  server/public/pluginapi/kv_memory.go
  server/public/pluginapi/kv_memory_test.go
  server/public/pluginapi/kv_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Tests/Not Needed, release-note-none

#26360 Manual cherry pick of #26045
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#25969 changed helper text to control-label class
  webapp/channels/src/sass/components/_inputs.scss
Labels: Lifecycle/1:stale, kind/bug, release-note-none, Contributor, 1. UX Review

#26374 Cherry pick Deprecate Admin Avisor #26045
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/notification_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26377 Manual cherrypick of #26045 for v9.3
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/notification_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26381 Manual cherrypick of #26045 for v8.1
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26380 Translations update from Mattermost Weblate
  server/i18n/be.json
  server/i18n/bg.json
  server/i18n/ca.json
  server/i18n/cs.json
  server/i18n/de.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/fa.json
  server/i18n/fi.json
  server/i18n/fr.json
  server/i18n/hi.json
  server/i18n/hu.json
  server/i18n/id.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/ko.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/ro.json
  server/i18n/ru.json
  server/i18n/sl.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/vi.json
  server/i18n/zh-CN.json
  server/i18n/zh-TW.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#26286 MM-56929- Dont allow guests to be set via team API
  server/channels/api4/team_test.go
  server/channels/app/import_functions_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26258 [MM-56848] Convert `./components/admin_console/settings_group.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/__snapshots__/bleve_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/push_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  webapp/channels/src/components/admin_console/settings_group.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#26354 MM-57037 Upgrade web app and pacakges to TypeScript 5.3.3
  webapp/channels/package.json
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/packages/mattermost-redux/src/utils/file_utils.ts
  webapp/channels/src/types/external/react-bootstrap.d.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/client/package.json
  webapp/platform/components/package.json
  webapp/platform/types/package.json
Labels: 4: Reviews Complete, release-note

#26287 MM-56881 Validate and ensure valid CustomStatus is stored
  server/i18n/en.json
  server/public/model/custom_status.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/selectors/views/custom_status.test.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26384 MM-57077 - Updating channel switcher header
  webapp/channels/src/sass/components/_channel-switcher.scss
Labels: release-note-none

#26305 [GH-21224] return error in plugin cmd
  server/cmd/mmctl/commands/plugin.go
  server/cmd/mmctl/commands/plugin_e2e_test.go
  server/cmd/mmctl/commands/plugin_marketplace_e2e_test.go
  server/cmd/mmctl/commands/plugin_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#26387 Fix Rollup warnings and remove some unused Rollup plugins
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/platform/components/package.json
  webapp/platform/components/rollup.config.js
Labels: 4: Reviews Complete, release-note-none

#26338 [MM-56651] fix: set cache duration
  server/platform/shared/web/files.go
Labels: 2: Dev Review, release-note, Contributor

#25663 [MM-56088] Adding extra logs for openId state failures
  server/channels/app/oauth.go
Labels: release-note-none

#26346 Update client and types npm packages to link to monorepo directly
  webapp/platform/client/package.json
  webapp/platform/types/package.json
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, kind/refactor

#26093 CLD-7074 Implement full E2E tests on Github Actions
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  .github/workflows/e2e-tests-ci.yml
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/dashboard.generate_test_cycle.sh
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.prepare.sh
  e2e-tests/Makefile
  e2e-tests/README.md
  e2e-tests/cypress/tests/integration/channels/plugins/plugin_startup_fail_spec.js
  e2e-tests/cypress/utils/report.js
Labels: release-note-none

#26255 MM-56879: Migrate caches from store layer to cache layer
  server/channels/api4/post_test.go
  server/channels/app/import_functions.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/platform/web_hub.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/webhook_test.go
  server/channels/store/localcachelayer/channel_layer.go
  server/channels/store/localcachelayer/emoji_layer.go
  server/channels/store/localcachelayer/file_info_layer.go
  server/channels/store/localcachelayer/layer.go
  server/channels/store/localcachelayer/post_layer.go
  server/channels/store/localcachelayer/reaction_layer.go
  server/channels/store/localcachelayer/role_layer.go
  server/channels/store/localcachelayer/scheme_layer.go
  server/channels/store/localcachelayer/team_layer.go
  server/channels/store/localcachelayer/terms_of_service_layer.go
  server/channels/store/localcachelayer/user_layer.go
  server/channels/store/localcachelayer/webhook_layer.go
  server/channels/store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#26388 MM-56980 add shared channel icon to searchable channel list
  webapp/channels/src/components/browse_channels/browse_channels.scss
  webapp/channels/src/components/searchable_channel_list.tsx
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26385 MM 56929 Dont allow guests to be set via channel API
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/app/import_functions_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26217 MM-56629 Render Markdown in batched email notifications
  server/channels/app/app_iface.go
  server/channels/app/email/email_batching.go
  server/channels/app/email/mocks/ServiceInterface.go
  server/channels/app/email/notification_email.go
  server/channels/app/email/service.go
  server/channels/app/notification_email.go
  server/channels/app/notification_email_test.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26410 MM-56402: Initialize replica conn pool on-demand
  server/public/pluginapi/store.go
  server/public/pluginapi/store_test.go
Labels: 4: Reviews Complete, release-note-none

#26363 MM-56784 - Update wrong documentation link
  webapp/channels/src/components/integrations/__snapshots__/abstract_outgoing_webhook.test.tsx.snap
  webapp/channels/src/components/integrations/abstract_outgoing_webhook.tsx
  webapp/channels/src/utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA/Review Done, release-note-none

#26332 MM-56625: Use patchConfig to update configs from system console
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_settings.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/custom_plugin_settings.test.tsx
  webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.test.tsx
  webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.test.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.test.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/index.ts
  webapp/channels/src/components/admin_console/data_retention_settings/index.ts
  webapp/channels/src/components/admin_console/index.ts
  webapp/channels/src/components/admin_console/openid_convert/index.ts
  webapp/channels/src/components/admin_console/openid_convert/openid_convert.test.tsx
  webapp/channels/src/components/admin_console/openid_convert/openid_convert.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.test.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
Labels: 4: Reviews Complete, release-note

#26412 Moved some common SQL function to public utils as they are used in plugins
  server/channels/store/sqlstore/migrate.go
  server/channels/store/sqlstore/store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/sqlstore/utils_test.go
  server/config/database.go
  server/public/utils/sql/sql_utils.go
  server/public/utils/sql/sql_utils_test.go
Labels: 2: Dev Review, release-note

#26391 MM-57084: Use cache for GetAllProfiles
  server/channels/app/user.go
  server/channels/store/localcachelayer/layer.go
  server/channels/store/localcachelayer/main_test.go
  server/channels/store/localcachelayer/user_layer.go
  server/channels/store/localcachelayer/user_layer_test.go
  server/public/model/cluster_message.go
  webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
Labels: 4: Reviews Complete, release-note-none

#26408 [GH-25494] add request context to public methods in bot go
  server/channels/api4/apitestlib.go
  server/channels/api4/bot.go
  server/channels/api4/bot_test.go
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
  server/channels/app/bot.go
  server/channels/app/bot_test.go
  server/channels/app/channel_test.go
  server/channels/app/helper_test.go
  server/channels/app/limits_test.go
  server/channels/app/notification_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/app/user_test.go
  server/cmd/mmctl/commands/bot_e2e_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none, Contributor

#26431 Automated cherry pick of #26427
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26432 Manual cherry pick of #25442
  server/channels/app/platform/service.go
  server/channels/app/server.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26434 MM-56892- Update prepackaged calls to v0.25.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#26435 Automated cherry pick of #26434
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26379 [MM-57065] Remove markdown from LDAP page size error
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note

#26142 MM-55251 - Updating reply count on thread post
  webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/selectors/rhs.ts
  webapp/channels/src/types/store/rhs.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26444 Automated cherry pick of #26287
  server/i18n/en.json
  server/public/model/custom_status.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/selectors/views/custom_status.test.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26445 Automated cherry pick of #26287
  server/i18n/en.json
  server/public/model/custom_status.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/selectors/views/custom_status.test.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26446 Automated cherry pick of #26287
  server/i18n/en.json
  server/public/model/custom_status.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/selectors/views/custom_status.test.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26447 Automated cherry pick of #25957
  server/channels/api4/team_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26294 MM-56983 Change how lastViewedAt is passed to NewMessageSeparator
  webapp/channels/src/components/post_view/new_message_separator/new_message_separator.test.tsx
  webapp/channels/src/components/post_view/new_message_separator/new_message_separator.tsx
  webapp/channels/src/components/post_view/post_list_row/__snapshots__/post_list_row.test.tsx.snap
  webapp/channels/src/components/post_view/post_list_row/post_list_row.test.tsx
  webapp/channels/src/components/post_view/post_list_row/post_list_row.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.test.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/index.ts
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/components/toast_wrapper/toast_wrapper.test.tsx
  webapp/channels/src/components/toast_wrapper/toast_wrapper.tsx
  webapp/channels/src/components/widgets/separator/notification-separator.tsx
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.ts
  webapp/channels/src/utils/post_utils.test.tsx
  webapp/channels/src/utils/post_utils.ts
Labels: 4: Reviews Complete, release-note-none

#26448 Automated cherry pick of #25957
  server/channels/api4/team_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26429 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#26449 Automated cherry pick of #26286
  server/channels/api4/team_test.go
  server/channels/app/import_functions_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26450 Automated cherry pick of #26286
  server/channels/api4/team_test.go
  server/channels/app/import_functions_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26453 Automated cherry pick of #26385
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/app/import_functions_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26080 Rebuild channel index
  server/channels/api4/config.go
  server/channels/api4/elasticsearch.go
  server/channels/app/app_iface.go
  server/channels/app/cloud.go
  server/channels/app/config.go
  server/channels/app/elasticsearch.go
  server/channels/app/enterprise.go
  server/channels/app/migrations.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/searchengine.go
  server/channels/app/server.go
  server/channels/app/user.go
  server/channels/utils/backoff.go
  server/einterfaces/jobs/elasticsearch.go
  server/i18n/en.json
  server/platform/services/searchengine/bleveengine/bleve.go
  server/platform/services/searchengine/interface.go
  server/platform/services/searchengine/mocks/SearchEngineInterface.go
  server/public/model/job.go
  server/public/model/migration.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/elasticsearch_settings.test.tsx
  webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
  webapp/channels/src/components/admin_console/jobs/table.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
Labels: 3: Security Review, release-note

#26462 MM-56625: Use patchConfig to update configs from system console (#26332)
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_settings.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/custom_plugin_settings.test.tsx
  webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.test.tsx
  webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.test.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.test.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/index.ts
  webapp/channels/src/components/admin_console/data_retention_settings/index.ts
  webapp/channels/src/components/admin_console/index.ts
  webapp/channels/src/components/admin_console/openid_convert/index.ts
  webapp/channels/src/components/admin_console/openid_convert/openid_convert.test.tsx
  webapp/channels/src/components/admin_console/openid_convert/openid_convert.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.test.jsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#26454 Adding AI plugin to pre-packaged plugins
  server/Makefile
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, CherryPick/Approved, AutoMerge, release-note

#26468 Automated cherry pick of #26454
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26467 MM-56929- Dont allow guests to be set via team API (#26286)
  server/channels/api4/team_test.go
  server/channels/app/import_functions_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26470 Automated cherry pick of #26385
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/app/import_functions_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26443 fix: error in truncate command with e2e script
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.generate.sh
Labels: 4: Reviews Complete, release-note-none

#26409 MM-49452 - Updating height of reply input
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#26191 MM-53703 Add display-name for experimental default channel
  server/channels/app/teams/teams.go
  server/channels/app/teams/teams_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26345 Add usage docs for WebSocket client to @mattermost/client
  webapp/platform/client/README.md
Labels: 4: Reviews Complete, release-note-none

#26274 Bump prepackage Gitlab plugin version to 1.8.1
  server/Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#25508 Added a action to return only the active channel and used it in the dropdown component
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.test.tsx
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
  webapp/channels/src/components/interactive_dialog/dialog_element/index.ts
Labels: 4: Reviews Complete, release-note

#26368 Convert ./components/file_info_preview/file_info_preview.tsx from Class Component to Function Component
  webapp/channels/src/components/__snapshots__/pdf_preview.test.tsx.snap
  webapp/channels/src/components/audio_video_preview/__snapshots__/audio_video_preview.test.tsx.snap
  webapp/channels/src/components/file_info_preview/file_info_preview.tsx
  webapp/channels/src/components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26475 [CLD-7343] Adding Node 20 support for images exposed under mattermostdevelopment/mirrored-node
  server/scripts/mirror-docker-images.json
Labels: release-note-none

#26474 [MM-57033] Update PL for user limit warning link
  webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
Labels: CherryPick/Approved, release-note-none

#26477 [CLD-7344] CD. Revisiting image registry for mattermostdevelopment/mirrored-keycloak
  server/scripts/mirror-docker-images.json
Labels: release-note-none

#26390 MM 57068 - remove export button from log item viewer.
  webapp/channels/src/components/admin_console/full_log_event_modal/full_log_event_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26479 Automated cherry pick of #26474
  webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26046 [MM-55629] SystemConsole: Unable to make HTTP request to get SAML metadata
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
Labels: 4: Reviews Complete, release-note

#26480 CLD-7343 Add node image version 20.11
  server/scripts/mirror-docker-images.json
Labels: release-note-none

#25886 [MM-56491] Allow sysadmins to LDAP sync SAML users when SamlSettings.EnableSyncWithLdap is true
  server/channels/api4/ldap.go
  server/channels/api4/ldap_test.go
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
Labels: 4: Reviews Complete, release-note

#26492 Fix incorrect translation string
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
Labels: 4: Reviews Complete, release-note-none

#26494 Automated cherry pick of #26287
  server/i18n/en.json
  server/public/model/custom_status.go
  server/public/model/user.go
  server/public/model/user_test.go
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/selectors/views/custom_status.test.ts
  webapp/channels/src/selectors/views/custom_status.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26481 [MM-57076] Stop removing local drafts when calling `removeDraft` for servers with synced drafts
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, Setup Cloud + CWS Test Server

#26496 Automated cherry pick of #26481
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26491 Add css variables for border radius
  webapp/channels/src/components/widgets/admin_console/admin_panel.scss
  webapp/channels/src/sass/base/_css_variables.scss
  webapp/channels/src/sass/components/_alerts.scss
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_dnd-pickers-dropdown-menu.scss
  webapp/channels/src/sass/components/_edit-post-time-limit-button.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/src/sass/components/_inputs.scss
  webapp/channels/src/sass/components/_popover.scss
  webapp/channels/src/sass/components/_scrollbar.scss
  webapp/channels/src/sass/routes/_about-modal.scss
  webapp/channels/src/sass/routes/_admin-console.scss
  webapp/channels/src/sass/utils/_variables.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26498 Automated cherry pick of #26473
  webapp/channels/src/sass/components/_multi-select.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26501 Automated cherry pick of #26481
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26502 Automated cherry pick of #26473
  webapp/channels/src/sass/components/_multi-select.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26469 Create proper SharedChannel record for InviteRemoteToChannel
  server/channels/app/platform/shared_channel_notifier.go
  server/platform/services/sharedchannel/service_api.go
Labels: CherryPick/Approved, release-note-none

#26505 Automated cherry pick of #26469
  server/channels/app/platform/shared_channel_notifier.go
  server/platform/services/sharedchannel/service_api.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26493 Patch eslint-plugin-react-hooks to properly handle class properties
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/package-lock.json
  webapp/package.json
  webapp/patches/eslint-plugin-react-hooks+4.6.0.patch
Labels: 4: Reviews Complete, release-note-none

#26458 MM-57119 Migrate various components to use WithTooltip
  webapp/channels/src/actions/emoji_actions.js
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  webapp/channels/src/components/admin_console/billing/billing_summary/billing_summary.tsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.tsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/common/multi_select_cards/multi_select_card.tsx
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/__snapshots__/keyboard_shortcuts_sequence.test.tsx.snap
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.test.tsx
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  webapp/channels/src/components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  webapp/channels/src/components/post_view/post_reaction/post_reaction.test.tsx
  webapp/channels/src/components/post_view/post_reaction/post_reaction.tsx
  webapp/channels/src/components/post_view/post_recent_reactions/post_recent_reactions.tsx
  webapp/channels/src/components/post_view/post_recent_reactions/recent_reactions_emoji_item.tsx
  webapp/channels/src/components/post_view/reaction/__snapshots__/reaction.test.tsx.snap
  webapp/channels/src/components/post_view/reaction/reaction.scss
  webapp/channels/src/components/post_view/reaction/reaction.tsx
  webapp/channels/src/components/post_view/reaction/reaction_tooltip/reaction_tooltip.tsx
  webapp/channels/src/components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
  webapp/channels/src/components/post_view/reaction_list/reaction_list.tsx
  webapp/channels/src/components/purchase_modal/purchase.scss
  webapp/channels/src/components/purchase_modal/renewal_card.tsx
  webapp/channels/src/components/seats_calculator/index.tsx
  webapp/channels/src/components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  webapp/channels/src/components/sidebar/channel_filter/channel_filter.tsx
  webapp/channels/src/components/team_sidebar/components/team_button.tsx
  webapp/channels/src/components/with_tooltip/create_tooltip.tsx
  webapp/channels/src/components/with_tooltip/index.tsx
  webapp/channels/src/components/with_tooltip/shortcut.tsx
  webapp/channels/src/components/with_tooltip/utils.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/utils/emoji_utils.ts
  webapp/channels/src/sass/components/_tooltip.scss
  webapp/channels/src/utils/i18n.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#26441 MM-57193: Standardize the cache names
  server/channels/app/platform/service.go
  server/channels/app/platform/status.go
  server/channels/store/localcachelayer/channel_layer.go
  server/channels/store/localcachelayer/file_info_layer.go
  server/channels/store/localcachelayer/post_layer.go
  server/channels/store/localcachelayer/team_layer.go
  server/channels/store/localcachelayer/terms_of_service_layer.go
  server/channels/store/localcachelayer/user_layer.go
  server/channels/store/localcachelayer/webhook_layer.go
Labels: 4: Reviews Complete, release-note-none

#25588 [MM-55994] Fix nbsp in group list modal
  webapp/channels/src/components/team_groups_manage_modal/team_groups_manage_modal.tsx
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26348 MM-56966 - cancel status request only on explicitly false config value
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
Labels: release-note-none

#26499 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none

#26508 Use specified `GO` var to generate `go.work` file
  server/Makefile
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#26414 [MM-57070] Remove detailed_error from errors when not in dev mode
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: 2: Dev Review, release-note

#26500 Fix Cypress tests on master
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_nav_diff_regions_spec.js
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/last_viewed_spec.js
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_3_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_4_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_3_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_feature_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/helpers.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/system_console_manage_guest_not_cloud_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/archived_channels_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/compliance_export_ui_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/reporting/site_statistics_spec.js
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/upload_files_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/builtin_commands/common_commands_2_spec.js
  e2e-tests/cypress/tests/integration/channels/integrations/integrations_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_up_down_in_rhs_spec.js
  e2e-tests/cypress/tests/integration/channels/mark_as_unread/mark_gm_as_unread_spec.js
  e2e-tests/cypress/tests/integration/channels/menus/status_dropdown_spec.js
  e2e-tests/cypress/tests/integration/channels/message_forwarding/forward_message_from_dm_spec.js
  e2e-tests/cypress/tests/integration/channels/message_forwarding/forward_message_from_private_channel_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/date_separator_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_keyboard_entry_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_picker_keyboard_usability_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_bullets_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_deleted_on_reply_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/post_textbox_height_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e-tests/cypress/tests/integration/channels/modals/quick_switcher_spec.js
  e2e-tests/cypress/tests/integration/channels/plugins/demo_plugin/webhook_spec.js
  e2e-tests/cypress/tests/integration/channels/plugins/link_tooltip_spec.js
  e2e-tests/cypress/tests/utils/plugins.js
  server/channels/api4/emoji.go
Labels: release-note-none

#26527 Automated cherry pick of #26414
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26528 Cherry pick of #26414
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: release-note-none

#26529 Cherry pick of #26414
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: release-note-none

#26530 Cherry pick of #26414
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: release-note-none

#26531 Cherry pick of #26414
  server/channels/api4/post_test.go
  server/channels/app/platform/websocket_router.go
  server/channels/web/handlers.go
  server/channels/wsapi/websocket_handler.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: release-note-none

#26334 MM-38745 feat: Add dont clear option for DND
  e2e-tests/cypress/tests/integration/channels/status/status_dnd_1_spec.js
  webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  webapp/channels/src/components/status_dropdown/index.ts
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
  webapp/channels/src/components/widgets/menu/menu_items/__snapshots__/submenu_item.test.tsx.snap
  webapp/channels/src/components/widgets/menu/menu_items/submenu_item.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/submenu_item.tsx
  webapp/channels/src/components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/tests/constants/users.ts
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, EETests, release-note, Setup Cloud + CWS Test Server, Contributor

#26512 MM-57245: Bump up Go version to 1.21
  .github/workflows/codeql-analysis.yml
  .github/workflows/migration.yml
  .github/workflows/mmctl-test-template.yml
  server/.go-version
  server/build/Dockerfile.buildenv
  server/cmd/mmctl/commands/bot_test.go
  server/cmd/mmctl/commands/channel_test.go
  server/cmd/mmctl/commands/channel_users_test.go
  server/cmd/mmctl/commands/channelargs_test.go
  server/cmd/mmctl/commands/command_test.go
  server/cmd/mmctl/commands/config_test.go
  server/cmd/mmctl/commands/export_test.go
  server/cmd/mmctl/commands/group_test.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/commands/integrity_test.go
  server/cmd/mmctl/commands/ldap_test.go
  server/cmd/mmctl/commands/license_test.go
  server/cmd/mmctl/commands/logs_test.go
  server/cmd/mmctl/commands/permission_role_test.go
  server/cmd/mmctl/commands/permissions_e2e_test.go
  server/cmd/mmctl/commands/permissions_test.go
  server/cmd/mmctl/commands/plugin_marketplace_test.go
  server/cmd/mmctl/commands/plugin_test.go
  server/cmd/mmctl/commands/post_test.go
  server/cmd/mmctl/commands/roles_test.go
  server/cmd/mmctl/commands/saml_test.go
  server/cmd/mmctl/commands/system_test.go
  server/cmd/mmctl/commands/team_test.go
  server/cmd/mmctl/commands/team_users_test.go
  server/cmd/mmctl/commands/teamargs_test.go
  server/cmd/mmctl/commands/token_test.go
  server/cmd/mmctl/commands/user_e2e_test.go
  server/cmd/mmctl/commands/user_test.go
  server/cmd/mmctl/commands/userargs_test.go
  server/cmd/mmctl/commands/webhook_test.go
  server/go.mod
  server/public/go.mod
  server/public/go.sum
Labels: 4: Reviews Complete, release-note

#26378 [MM-57071] Use bool for license_is_trial in Support Packet
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/public/model/system.go
Labels: 4: Reviews Complete, release-note

#26476 Fix search date suggestion crash
  webapp/channels/src/components/suggestion/search_date_suggestion/index.ts
  webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
  webapp/channels/src/components/suggestion/search_suggestion_list.tsx
  webapp/channels/src/components/suggestion/suggestion_date.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
  webapp/channels/src/components/widgets/popover/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#26534 MM-57377: Skip racy test
  server/channels/app/server_test.go
Labels: 4: Reviews Complete, release-note-none

#26413 MM-28014 Improve Channel Intros
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/group_message_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/send_message_via_profile_popover_spec.js
  e2e-tests/cypress/tests/integration/channels/multi_team_and_dm/gm_add_user_spec.js
  webapp/channels/src/components/common/svg_images_components/channel_intro_private_svg.tsx
  webapp/channels/src/components/common/svg_images_components/channel_intro_public_svg.tsx
  webapp/channels/src/components/common/svg_images_components/channel_intro_town_square_svg.tsx
  webapp/channels/src/components/post_view/channel_intro_message/add_members_button.scss
  webapp/channels/src/components/post_view/channel_intro_message/add_members_button.tsx
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.test.tsx
  webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx
  webapp/channels/src/components/post_view/channel_intro_message/index.ts
  webapp/channels/src/components/post_view/channel_intro_message/pluggable_intro_buttons/pluggable_intro_buttons.tsx
  webapp/channels/src/components/widgets/users/avatar/avatar.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_action-button.scss
  webapp/channels/src/sass/components/_module.scss
  webapp/channels/src/sass/layout/_headers.scss
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26478 [MM-57081] Spacing, font and cutoff issues on Channel notifications preferences modal
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/channel_notifications_spec.js
  webapp/channels/src/components/alert_banner.tsx
  webapp/channels/src/components/alert_banner/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/alert_banner/alert_banner.scss
  webapp/channels/src/components/alert_banner/index.test.tsx
  webapp/channels/src/components/alert_banner/index.tsx
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.scss
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
  webapp/channels/src/components/channel_notifications_modal/utils.tsx
  webapp/channels/src/components/file_limit_sticky_banner/index.tsx
  webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx
  webapp/channels/src/components/team_settings/team_access_tab/invite_section_input.tsx
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_description_section.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_name_section.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_picture_section.tsx
  webapp/channels/src/components/widgets/modals/components/base_setting_item.scss
  webapp/channels/src/components/widgets/modals/components/base_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/checkbox_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/modal_header.scss
  webapp/channels/src/components/widgets/modals/components/modal_header.tsx
  webapp/channels/src/components/widgets/modals/components/modal_section.scss
  webapp/channels/src/components/widgets/modals/components/modal_section.tsx
  webapp/channels/src/components/widgets/modals/components/radio_setting_item.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26517 MM-57344: Use a row constructor comparison to avoid a filter
  server/channels/store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note

#26539 Automated cherry pick of #26476
  webapp/channels/src/components/suggestion/search_date_suggestion/index.ts
  webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
  webapp/channels/src/components/suggestion/search_suggestion_list.tsx
  webapp/channels/src/components/suggestion/suggestion_date.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
  webapp/channels/src/components/widgets/popover/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25900 MM-55320 - Limit length of browser user agent version; ratelimit the /sessions endpoint
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26544 Automated cherry pick of #26517
  server/channels/store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note

#26543 Automated cherry pick of #26517
  server/channels/store/sqlstore/post_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note

#26214 [MM-56853] Add mmctl shell completion for commands
  server/cmd/mmctl/commands/completion.go
  server/cmd/mmctl/commands/completion_test.go
  server/cmd/mmctl/commands/init.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none

#26546 Automated cherry pick of #25900
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26547 Automated cherry pick of #25900
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26548 Automated cherry pick of #25900
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26549 Automated cherry pick of #25900
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26511 User limit enforcement
  server/channels/api4/user.go
  server/channels/app/limits.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/limits.go
  webapp/channels/src/components/admin_console/system_users/system_users.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note

#26550 Automated cherry pick of #26148
  server/channels/api4/brand.go
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/file.go
  server/channels/api4/handlers.go
  server/channels/api4/outgoing_oauth_connection.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/role.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/channels/api4/upload.go
  server/channels/api4/upload_local.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/channels/web/handlers.go
  server/i18n/en.json
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26553 Revert front-end changes for #25715
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
  webapp/channels/src/actions/websocket_actions.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26555 Automated cherry pick of #26553
  webapp/channels/src/actions/views/drafts.test.ts
  webapp/channels/src/actions/views/drafts.ts
  webapp/channels/src/actions/websocket_actions.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26535 MM-57378: Bump up golangci version
  server/.golangci.yml
  server/Makefile
  server/channels/app/post_metadata.go
  server/channels/store/sqlstore/channel_member_history_store.go
  server/channels/store/sqlstore/plugin_store.go
  server/channels/store/sqlstore/store.go
  server/channels/utils/humanize.go
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/public/model/config.go
  server/public/model/user.go
  server/public/plugin/client.go
  server/public/plugin/client_rpc.go
  server/public/utils/json.go
Labels: 4: Reviews Complete, release-note-none

#26490 [MM-57106] Remove unused cluster settings
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/store/searchlayer/layer_test.go
  server/public/model/cluster_discovery.go
  server/public/model/config.go
  server/tests/test-config.json
  webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/cluster_settings.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: Docs/Needed, Changelog/Done, 3: QA Review, release-note

#26561 Automated cherry pick of #26558
  server/go.mod
  server/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26560 Manual cherrypick for API handler options for v9.6
  server/channels/api4/emoji.go
  server/channels/api4/ldap.go
  server/channels/api4/license.go
  server/channels/api4/license_local.go
  server/channels/api4/plugin.go
  server/channels/api4/plugin_local.go
  server/channels/api4/remote_cluster.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26563 Cherrypicking API Handler params for 9.5
  server/channels/api4/brand.go
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/file.go
  server/channels/api4/handlers.go
  server/channels/api4/ldap.go
  server/channels/api4/license.go
  server/channels/api4/license_local.go
  server/channels/api4/plugin.go
  server/channels/api4/plugin_local.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/remote_cluster.go
  server/channels/api4/role.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/channels/api4/upload.go
  server/channels/api4/upload_local.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/channels/web/handlers.go
  server/i18n/en.json
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26564 Cherrypicking API Handler params for 8.1
  server/channels/api4/brand.go
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/file.go
  server/channels/api4/handlers.go
  server/channels/api4/ldap.go
  server/channels/api4/license.go
  server/channels/api4/license_local.go
  server/channels/api4/plugin.go
  server/channels/api4/plugin_local.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/remote_cluster.go
  server/channels/api4/role.go
  server/channels/api4/role_test.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/channels/api4/upload.go
  server/channels/api4/upload_local.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/channels/web/handlers.go
  server/i18n/en.json
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26554 Manual cherrypick of #26511 for v9.7
  server/channels/api4/user.go
  server/channels/app/limits.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/limits.go
  webapp/channels/src/components/admin_console/system_users/system_users.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#26557 Update prepackaged Calls to v0.25.1
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#26567 Cherrypick of #26513 for v9.7
  server/channels/api4/emoji.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26568 Automated cherry pick of #26557
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26569 [MM-55320] Cherry pick of #25900
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/session.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/user_agent_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SessionStore.go
  server/channels/store/storetest/session_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26565 [MM-57392] Skip flaky TestEditChannelBookmark test
  server/channels/api4/channel_bookmark_test.go
Labels: 4: Reviews Complete, release-note-none

#26423 [GH-26382] format command mmctl auth list
  server/cmd/mmctl/commands/auth.go
  server/cmd/mmctl/commands/auth_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#26395 [MM-56847] Convert ./components/post_view/post_image/post_image.tsx from Class Component to Function Component
  webapp/channels/src/components/post_view/post_image/post_image.tsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#26428 [GH-21216] Function removeUserFromChannel return error
  server/cmd/mmctl/commands/channel_users.go
  server/cmd/mmctl/commands/channel_users_e2e_test.go
  server/cmd/mmctl/commands/channel_users_test.go
  server/public/model/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Not Required, release-note-none, Contributor

#26581 [CLD-7373] Always overwrite CloudSettings based on service environment when in production
  server/public/model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26582 Automated cherry pick of #26581
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26583 Automated cherry pick of #26581
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26584 Automated cherry pick of #26581
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26585 Added error code in safety limit error
  server/i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#26586 Automated cherry pick of #26585
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26523 [MM-57295] Bulk export: add roles and permission schemes
  server/channels/app/export.go
  server/channels/app/export_converters.go
  server/channels/app/export_test.go
  server/channels/app/import.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/imports/import_types.go
  server/channels/jobs/export_process/worker.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/commands/export_e2e_test.go
  server/cmd/mmctl/commands/export_test.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/importer/validate.go
  server/cmd/mmctl/docs/mmctl_export_create.rst
  server/i18n/en.json
  server/public/model/bulk_export.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#26570 MM-57175 Tour Point Theme Color Update
  webapp/channels/src/components/onboarding_tasks/onboarding_video_modal/onboarding_video_modal.scss
  webapp/channels/src/components/shortcut_key/shortcut_key.scss
  webapp/channels/src/images/channels_and_direct_tour_tip.svg
  webapp/platform/components/src/tour_tip/tour_tip.scss
  webapp/platform/components/src/tour_tip/tour_tip.tsx
Labels: 4: Reviews Complete, release-note

#26577 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/sv.json
  server/i18n/th.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/el.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ka.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lo.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/ml.json
  webapp/channels/src/i18n/ne.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sq.json
  webapp/channels/src/i18n/sr.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/th.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#26608 Fix user group not being properly potitioned
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note-none, Setup Cloud + CWS Test Server

#26613 Automated cherry pick of #26608
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26603 MM-47680 Fix Thread Footer Buttons
  webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.scss
  webapp/channels/src/components/threading/common/button/button.scss
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server

#26510 CLD-7353 E2E: Disable sending diagnostics and security alert on test servers
  e2e-tests/.ci/server.generate.sh
  e2e-tests/cypress/tests/support/api/cloud_default_config.json
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/cypress/tests/support/index.js
  e2e-tests/playwright/global_setup.ts
  e2e-tests/playwright/support/server/default_config.ts
Labels: 2: Dev Review, release-note-none

#26610 Profile image from bytes
  server/public/pluginapi/bot.go
  server/public/pluginapi/bot_test.go
Labels: 2: Dev Review, QA/Review Not Required, release-note

#26612 [MM-57369] Remote users no longer labeled as 'remote' after updates to the System Console Users UI
  webapp/channels/src/components/admin_console/system_users/system_users.scss
  webapp/channels/src/components/admin_console/system_users/system_users.tsx
  webapp/channels/src/components/profile_popover/profile_popover_name/full_name.tsx
  webapp/channels/src/components/shared_user_indicator.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  webapp/channels/src/components/suggestion/search_user_provider.tsx
  webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/utils/_mixins.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26621 Automated cherry pick of #26612
  webapp/channels/src/components/admin_console/system_users/system_users.scss
  webapp/channels/src/components/admin_console/system_users/system_users.tsx
  webapp/channels/src/components/profile_popover/profile_popover_name/full_name.tsx
  webapp/channels/src/components/shared_user_indicator.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  webapp/channels/src/components/suggestion/search_user_provider.tsx
  webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/utils/_mixins.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26615 add UpdateUserRoles to plugin api
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_tests/test_update_user_roles_plugin/main.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/user.go
Labels: QA/Review Not Required, release-note
