Repository mattermost/mattermost, pull requests merged in 2024-06, with the labels that each got.

#27163 MM-58413: Migrate various components to use WithTooltip
  webapp/channels/src/components/advanced_create_post/priority_labels.tsx
  webapp/channels/src/components/common/comment_icon.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/sidebar/add_channel_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27168 [MM-58406] Migrate tooltips of 'components/custom_status/custom_status_text' to WithTooltip
  webapp/channels/src/components/custom_status/custom_status_text.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27251 Translations update from Mattermost Weblate
  server/i18n/ru.json
  server/i18n/sv.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
Labels: release-note-none, Do Not Merge/Mattermod

#27212 [MM-58500] Turn off PostedAck when the connection is no longer registered
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
Labels: 2: Dev Review, release-note-none

#27215 MM-58349 Don't allow remote user to create sessions or reset password
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: 4: Reviews Complete, AutoMerge, release-note

#27206 Automated cherry pick of #27143
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27257 Automated cherry pick of #27143
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27259 Automated cherry pick of #27143
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27264 Automated cherry pick of #27215
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26784 Update ChannelHeaderPlug tests to not use snapshots and ensure its more accessible
  e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/channel_header/channel_info_button.tsx
  webapp/channels/src/components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  webapp/channels/src/components/channel_header/components/header_icon_wrapper.test.tsx
  webapp/channels/src/components/channel_header/components/header_icon_wrapper.tsx
  webapp/channels/src/components/search/search.tsx
  webapp/channels/src/plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  webapp/channels/src/plugins/channel_header_plug/channel_header_plug.test.tsx
  webapp/channels/src/plugins/channel_header_plug/channel_header_plug.tsx
  webapp/channels/src/sass/components/_tooltip.scss
  webapp/channels/src/tests/setup_jest.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#27186 MM-58354 Fix numbered Markdown lists not wrapping long words
  webapp/channels/src/sass/layout/_markdown.scss
Labels: 4: Reviews Complete, release-note

#27256 Cherry pick (#27171) into release-9.8
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#27260 Automated cherry pick of #27215
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27261 Automated cherry pick of #27215
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27262 Automated cherry pick of #27215
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27265 Automated cherry pick of #27212
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27267 Cherry pick (#27171) into release-9.7
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
Labels: AutoMerge, release-note-none

#27268 Cherry pick (#27171) into release-9.6
  webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_announcement-bar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27270 Cherry-pick MM-57867 into release-9.5
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27146 [MM-58402] Migrate tooltips of 'components/emoji_picker_skin.tsx' & 'components/emoji_picker_category' to WithTooltip
  webapp/channels/src/components/emoji_picker/components/__snapshots__/emoji_picker_category.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.test.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_skin.tsx
  webapp/channels/src/sass/components/_tooltip.scss
Labels: 4: Reviews Complete, release-note-none

#27263 Automated cherry pick of #27215
  server/channels/api4/user_test.go
  server/channels/app/oauth_test.go
  server/channels/app/session.go
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27277 Automated cherry pick of #27203
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27279 Automated cherry pick of #27203
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27280 Automated cherry pick of #27203
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27196 MM-54195- add translation for errors checking group name
  server/channels/app/user.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#27278 Automated cherry pick of #27203
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27214 MM-58275 Ensure image proxy site URL is updated when that changes
  server/channels/utils/testutils/static_config_service.go
  server/platform/services/imageproxy/atmos_camo.go
  server/platform/services/imageproxy/atmos_camo_test.go
  server/platform/services/imageproxy/imageproxy.go
  server/platform/services/imageproxy/imageproxy_test.go
  server/platform/services/imageproxy/local.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#27222 MM-58499 Fix bolded icon issue in LHS
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#27272 [MM-58463] Remove defer for main/entry JS scripts
  webapp/channels/webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#27289 MM-58252 cherry-pick into release 9.5
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27082 [MM-58086] platform/busy_test.go: increase test busy duration time
  server/channels/app/platform/busy_test.go
Labels: 4: Reviews Complete, release-note-none

#27080 [MM-58341] db/migrations: mysql-8.4 fix for 000027_create_status
  server/channels/db/migrations/mysql/000027_create_status.up.sql
  server/channels/store/sqlstore/status_store.go
  server/channels/store/sqlstore/utils.go
Labels: 2: Dev Review, release-note-none

#26974 Prevent null unicode character errors during the migration
  server/tests/template.load
Labels: 2: Dev Review, release-note-none

#27284 Move HTTP service to public for plugin use
  server/channels/app/app.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post_metadata_test.go
  server/channels/app/server.go
  server/channels/jobs/export_delete/worker.go
  server/channels/jobs/export_process/worker.go
  server/channels/jobs/import_delete/worker.go
  server/channels/jobs/import_process/worker.go
  server/channels/jobs/resend_invitation_email/worker.go
  server/channels/jobs/server.go
  server/channels/jobs/workers.go
  server/platform/services/imageproxy/atmos_camo_test.go
  server/platform/services/imageproxy/imageproxy.go
  server/platform/services/imageproxy/local_test.go
  server/platform/services/marketplace/client.go
  server/platform/services/telemetry/mocks/ServerIface.go
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/shared/configservice/configservice.go
  server/public/shared/httpservice/client.go
  server/public/shared/httpservice/client_test.go
  server/public/shared/httpservice/httpservice.go
  server/public/shared/httpservice/transport.go
Labels: 4: Reviews Complete, release-note-none

#27290 MM-58253 Ensure remotes can only update users belonging to them
  server/go.mod
  server/go.sum
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#27294 Automated cherry pick of #27290
  server/go.mod
  server/go.sum
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27273 Remove t from utils/emojis and related code
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_popovers_spec.js
  webapp/channels/build/emoji/make_emojis.mjs
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/__snapshots__/emoji_picker_category.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_categories.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.test.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_skin.tsx
  webapp/channels/src/components/emoji_picker/constants/index.ts
  webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
  webapp/channels/src/components/emoji_picker/types/index.ts
  webapp/channels/src/utils/emoji.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#27213 [MM-58008] Calls Mobile: Settings for DM/GM ringing
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, release-note-none

#27204 [MM-58355] Send invalidate cache message across the cluster so that websocket connections on other instances are invalidated correctly
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
  server/channels/app/channel.go
  server/channels/app/platform/session.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/user.go
  server/channels/store/localcachelayer/channel_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/layer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/UserStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#27179 [MM-58445] Try deferring plugins scripts loading
  webapp/channels/src/plugins/index.js
Labels: 4: Reviews Complete, release-note

#27309 Automated cherry pick of #27296
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27281 [MM-57738] Added GetPluginID method to Manifest model
  server/public/model/manifest.go
  server/public/model/manifest_test.go
Labels: 4: Reviews Complete, release-note, Contributor

#27308 Add check to not send license expiration email when in Cloud
  server/channels/app/server.go
Labels: 4: Reviews Complete, release-note-none

#27311 Automated cherry pick of #27308
  server/channels/app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27312 Automated cherry pick of #27308
  server/channels/app/server.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27314 Automated cherry pick of #26070
  server/channels/api4/cloud.go
  server/i18n/en.json
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27315 Automated cherry pick of #26070
  server/channels/api4/cloud.go
  server/i18n/en.json
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27306 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/fa.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/sv.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#27317 MM-58577 Check remote ownership for posts and reactions
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/reaction.go
Labels: 4: Reviews Complete, release-note

#27140 Remove gobom files
  server/.gobom.json
  webapp/channels/.gobom.json
Labels: release-note-none

#27323 Automated cherry pick of #27317
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/reaction.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27275 Improve isolation of PerformanceReporter tests to increase their stability
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 4: Reviews Complete, release-note-none

#27319 [9.5 CP]MM-57152: Get webconn count from the whole cluster (#26813)
  server/channels/app/busy_test.go
  server/channels/app/platform/busy_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/channels/testlib/cluster.go
  server/einterfaces/cluster.go
  server/einterfaces/mocks/ClusterInterface.go
  server/public/model/cluster_message.go
Labels: 4: Reviews Complete, release-note

#23958 [MM-53356] server/app/migrations: refactor app migrations
  server/channels/app/app_iface.go
  server/channels/app/migrations.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, release-note-none

#27045 Add mobile metrics
  server/channels/app/helper_test.go
  server/channels/app/metrics.go
  server/channels/app/metrics_test.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/enterprise/metrics/metrics_test.go
  server/public/model/metrics.go
Labels: 4: Reviews Complete, release-note

#27329 MM-58577 cherry-pick to release 9.9
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/reaction.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27188 [MM-58017] Allow plugins to use more visualization types for admin statistics
  webapp/channels/src/components/analytics/system_analytics/system_analytics.test.tsx
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/platform/types/src/admin.ts
Labels: 4: Reviews Complete, release-note

#27333 Automated cherry pick of #27045
  server/channels/app/helper_test.go
  server/channels/app/metrics.go
  server/channels/app/metrics_test.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/enterprise/metrics/metrics_test.go
  server/public/model/metrics.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27334 Updates remote user creation process to preserve username and email
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, release-note-none

#27331 MM-57873 Check user visibility when accepting channel invites for DMs
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, release-note

#27076 MM-57839: Rewrite static assets only if needed
  server/channels/utils/subpath.go
  server/channels/utils/subpath_test.go
Labels: 4: Reviews Complete, release-note-none

#27339 Automated cherry pick of #26151
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27340 Automated cherry pick of #26158
  webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
  webapp/channels/src/components/edit_channel_header_modal/index.ts
  webapp/channels/src/components/textbox/textbox_links.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27344 Automated cherry pick of #27334
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27342 Automated cherry pick of #27334
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27343 Automated cherry pick of #27334
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27345 Automated cherry pick of #27334
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27346 Automated cherry pick of #27331
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27347 Automated cherry pick of #27331
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, EETests, release-note-none

#27328 MM-58577 cherry-pick to release 9.8
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/reaction.go
Labels: release-note

#27326 MM-58577 cherry-pick to release 9.5
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/reaction_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ReactionStore.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/reaction.go
Labels: release-note

#27348 Automated cherry pick of #27188
  webapp/channels/src/components/analytics/system_analytics/system_analytics.test.tsx
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/platform/types/src/admin.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27313 MM-58685 Fix Channel Header Icon Button Spacing
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_modal.scss
  webapp/channels/src/sass/layout/_headers.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, AutoMerge, release-note-none

#27349 Automated cherry pick of #27313
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_modal.scss
  webapp/channels/src/sass/layout/_headers.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27192 [MM-58456] Make react library be loaded at DOMContentLoaded instead of onload
  webapp/channels/src/entry.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#27356 fix 9.5 CI
  server/channels/store/storetest/mocks/ReactionStore.go
Labels: 4: Reviews Complete, release-note-none

#27355 Fix CI
  server/channels/store/storetest/mocks/ReactionStore.go
Labels: 4: Reviews Complete, release-note-none

#27350 Automated cherry pick of #26820
  server/channels/api4/channel.go
  server/channels/app/app_iface.go
  server/channels/app/authorization.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27330 MM-58528 Fixed wrapping button label for followed threads
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, AutoMerge, release-note-none

#27363 Automated cherry pick of #27330
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27172 [MM-53491] Fix rendering of active call icon in sidebar's channel link
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, AutoMerge, release-note-none

#27365 Automated cherry pick of #27172
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27351 MM-57873 cherry-pick to release 9.5
  server/go.mod
  server/go.sum
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note

#27352 [MM-58296] Update prepackage calls to v0.28.1 for MM v9.10
  server/Makefile
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, release-note

#27370 Automated cherry pick of #27352
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26909 [MM-58039] Enable errcheck linter for enterprise/saml package
  server/.golangci.yml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Tests/Not Needed, release-note-none

#27378 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/ja.json
  server/i18n/pl.json
  server/i18n/sv.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nb-NO.json
Labels: release-note-none, Do Not Merge/Mattermod

#27307 [MM-58315]: prepackage boards to v9.5+
  server/Makefile
Labels: 2: Dev Review, Docs/Needed, 3: QA Review, CherryPick/Approved, release-note-none

#26855 [MM-56074] mmctl job commands
  api/v4/source/jobs.yaml
  e2e-tests/cypress/tests/support/api/role.js
  server/channels/api4/job.go
  server/channels/api4/job_local.go
  server/channels/api4/job_test.go
  server/channels/app/app_iface.go
  server/channels/app/job.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/permissions_migrations.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/testlib/store.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/commands/extract.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/commands/job.go
  server/cmd/mmctl/commands/job_test.go
  server/cmd/mmctl/commands/ldap.go
  server/cmd/mmctl/commands/ldap_test.go
  server/cmd/mmctl/docs/mmctl.rst
  server/cmd/mmctl/docs/mmctl_job.rst
  server/cmd/mmctl/docs/mmctl_job_list.rst
  server/cmd/mmctl/docs/mmctl_job_update.rst
  server/cmd/mmctl/mocks/client_mock.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/job.go
  server/public/model/job_test.go
  server/public/model/migration.go
  server/public/model/permission.go
  server/public/model/role.go
Labels: QA/Review Done, release-note

#27274 Remove t from utils and most components
  webapp/channels/src/components/common/hooks/useGetHighestThresholdCloudLimit.test.ts
  webapp/channels/src/components/common/hooks/useGetMultiplesExceededCloudLimit.test.ts
  webapp/channels/src/components/copy_button.tsx
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_provider.tsx
  webapp/channels/src/components/suggestion/channel_mention_provider.tsx
  webapp/channels/src/components/suggestion/command_provider/command_provider.tsx
  webapp/channels/src/components/suggestion/emoticon_provider.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/widgets/icons/close_icon.tsx
  webapp/channels/src/components/widgets/inputs/channels_input.tsx
  webapp/channels/src/components/widgets/menu/menu_items/useWords.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/url.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none

#27379 Automated cherry pick of #27307
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27381 Cherry pick of #27307
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27382 Cherry pick #27307
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27383 Cherry pick #27307
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27380 Cherry pick of #27307
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, EETests, release-note-none

#27061 [MM-57988] Fix move thread logic to not block channel admins
  server/channels/api4/post.go
  server/channels/api4/post_test.go
  webapp/channels/src/selectors/posts.ts
Labels: 3: QA Review, Setup Cloud Test Server, 3: Security Review, release-note-none, Contributor

#27286 [MM-58560] Configurable session revocation during password resets
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/session_length_settings.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#27374 fix(webapp/Makefile): Drop quotes around appended cppflags
  webapp/Makefile
Labels: 4: Reviews Complete, release-note-none, Contributor

#27240 [MM-58513] Migrate tooltips of "components/channel_info_rhs/header.tsx" to WithTooltip
  webapp/channels/src/components/channel_info_rhs/header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27241 [MM-58514] Migrate tooltips of "components/channel_members_rhs/header.tsx" to WithTooltip
  webapp/channels/src/components/channel_members_rhs/header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27357 MM-57867 Don't delete existing DM on invitation error
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
Labels: 4: Reviews Complete, release-note-none

#27297 MM-57913 Increase maximum length of Preferences.Value column
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000122_preferences_value_length.down.sql
  server/channels/db/migrations/mysql/000122_preferences_value_length.up.sql
  server/channels/db/migrations/postgres/000122_preferences_value_length.down.sql
  server/channels/db/migrations/postgres/000122_preferences_value_length.up.sql
  server/public/model/preference.go
  server/public/model/preference_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note

#27397 MM-58823 Remove feature flag from client metrics
  server/config/client.go
  server/public/model/feature_flags.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27366 Move password utilities to their own file
  webapp/channels/src/components/admin_console/password_settings.tsx
  webapp/channels/src/components/admin_console/reset_password_modal/index.ts
  webapp/channels/src/components/admin_console/reset_password_modal/reset_password_modal.tsx
  webapp/channels/src/components/claim/components/ldap_to_email.tsx
  webapp/channels/src/components/claim/components/oauth_to_email.tsx
  webapp/channels/src/components/claim/index.ts
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/utils/password.test.tsx
  webapp/channels/src/utils/password.tsx
  webapp/channels/src/utils/utils.test.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none

#27406 Automated cherry pick of #27397
  server/config/client.go
  server/public/model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27407 Automated cherry pick of #27397
  server/config/client.go
  server/public/model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27405 Automated cherry pick of #27357
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27391 Add saml private key to gitignore, remove unused constants
  server/.gitignore
  server/channels/app/license.go
  server/channels/app/platform/license.go
Labels: 4: Reviews Complete, release-note-none

#27403 Automated cherry pick of #27357
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27404 Automated cherry pick of #27357
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27410 Cherry-pick MM-57867 into release 9.7
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27411 Cherry-pick MM-57867 release-9.8
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#27291 [MM-58519] Migrate tooltips of "components/integrations/bots/add_bot/add_bot.tsx" to WithTooltip
  webapp/channels/src/components/integrations/bots/add_bot/add_bot.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27416 Automated cherry pick of #27396
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27425 [MM-59037] Prepackage calls v0.28.2 for v9.10
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#27426 Automated cherry pick of #27425
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27201 MM-50594 - fix for group member count using wrong property
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.test.js
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note

#27197 [MM-58442] Migrate tooltips of 'components/drafts/panel/panel_header' to WithTooltip
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_header.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel_header.test.tsx
  webapp/channels/src/components/drafts/panel/panel_header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27371 [MM-32770] Inform user that mentions added in edited posts won't trigger notifications for the receiving user
  e2e-tests/cypress/tests/integration/channels/messaging/edit_message_spec.js
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, release-note, Contributor

#27417 MM-59033 Increase maximum bucket size for Load Event End metric
  server/enterprise/metrics/metrics.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#27429 Automated cherry pick of #27417
  server/enterprise/metrics/metrics.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#27364 Marks the RemoteTeamId field of RemoteClusters as deprecated
  server/channels/api4/shared_channel_test.go
  server/channels/app/remote_cluster_test.go
  server/channels/app/session_test.go
  server/channels/app/slashcommands/command_remote.go
  server/channels/store/storetest/shared_channel_store.go
  server/platform/services/remotecluster/invitation.go
  server/platform/services/remotecluster/recv.go
  server/platform/services/sharedchannel/channelinvite.go
  server/public/model/auditconv.go
  server/public/model/remote_cluster.go
  server/public/model/remote_cluster_test.go
Labels: 4: Reviews Complete, release-note

#27430 Fix not enough return values in handleChannelCreation
  server/platform/services/sharedchannel/channelinvite.go
Labels: 2: Dev Review, release-note-none

#27199 [MM-58410] Migrate tooltips of 'components/post/post_component' to WithTooltip
  webapp/channels/src/components/post/post_component.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27217 MM-57319 Direct Message modal message improvement
  webapp/channels/src/components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  webapp/channels/src/components/more_direct_channels/list/list.tsx
  webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#27412 MM-55973: Make keyboard shortcuts modal content div accessible via keyboard
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
Labels: 4: Reviews Complete, QA/Review Done, AutoMerge, release-note, Contributor

#27419 MM-59024 - Update code to handle column headers without text
  webapp/channels/src/components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/team_list/abstract_list.test.tsx
  webapp/channels/src/components/admin_console/system_user_detail/team_list/abstract_list.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note-none

#27298 MM-58525 Fix upload file permissions
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
  server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#26389 MM-57013 Added download button for downloading logs from server logs page in system console
  api/Makefile
  api/v4/source/logs.yaml
  server/channels/api4/system.go
  server/channels/api4/system_test.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/support_packet.go
  server/channels/app/support_packet_test.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/components/admin_console/server_logs/logs.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/admin.ts
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note, Contributor

#27248 [MM-58516] Migrate tooltips of "components/search/user_guide_dropdown/user_guide_dropdown.tsx" to WithTooltip
  webapp/channels/src/components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/search/user_guide_dropdown/user_guide_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27246 [MM-58512] Migrate tooltips of "components/status_dropdown/status_dropdown.tsx" to WithTooltip
  webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  webapp/channels/src/components/status_dropdown/status_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27440 [MM-59059] Re enable markdown preview for channel header in user advanced settings
  webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
  webapp/channels/src/components/edit_channel_header_modal/index.ts
  webapp/channels/src/components/textbox/textbox_links.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/utils/constants.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note-none

#27421 MM-58255 Ensure remote users do not get valid email addresses
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/notification.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: 4: Reviews Complete, release-note

#27450 Cherry pick MM-59059 to v9.5
  webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
  webapp/channels/src/components/edit_channel_header_modal/index.ts
  webapp/channels/src/components/textbox/textbox_links.tsx
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#27394 MM-58802 Fix overlapping back button
  webapp/channels/src/components/header_footer_route/header.scss
  webapp/channels/src/components/header_footer_route/header.tsx
  webapp/channels/src/components/signup/signup.scss
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#27393 CLD-5704 Migrate daily master/cloud tests
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  e2e-tests/.ci/.e2erc
  e2e-tests/.ci/report.publish.sh
  e2e-tests/.ci/server.cloud_init.sh
  e2e-tests/.ci/server.cloud_teardown.sh
  e2e-tests/README.md
  e2e-tests/cypress/save_report.js
Labels: release-note-none

#27448 MM-57913 Increase maximum length of Preferences.Value column (#27297)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000122_preferences_value_length.down.sql
  server/channels/db/migrations/mysql/000122_preferences_value_length.up.sql
  server/channels/db/migrations/postgres/000122_preferences_value_length.down.sql
  server/channels/db/migrations/postgres/000122_preferences_value_length.up.sql
  server/public/model/preference.go
  server/public/model/preference_test.go
Labels: 4: Reviews Complete, CherryPick/Done, release-note

#27451 Automated cherry pick of #27394
  webapp/channels/src/components/header_footer_route/header.scss
  webapp/channels/src/components/header_footer_route/header.tsx
  webapp/channels/src/components/signup/signup.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27455 Automated cherry pick of #27421
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/notification.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#27454 Automated cherry pick of #27421
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/notification.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/util.go
  server/public/model/user.go
  server/public/model/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25128 update for adding multiple members
  api/v4/source/channels.yaml
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/public/model/client4.go
  webapp/channels/src/actions/channel_actions.test.ts
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.test.js
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note

#27458 MM-58777 Confirm that sendBeacon exists before trying to use it
  webapp/channels/src/utils/performance_telemetry/reporter.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#27243 [MM-58510] Migrate tooltips of "components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx" to WithTooltip
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  webapp/channels/src/components/with_tooltip/create_tooltip.tsx
  webapp/channels/src/components/with_tooltip/index.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#27439 [MM-58407] Migrate tooltips of 'components/file_attachment/filename_overlay' to WithTooltip
  webapp/channels/src/components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap
  webapp/channels/src/components/file_attachment/filename_overlay.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27238 MM-58411 Migrate tooltips of 'components/actions_menu/actions_menu' to WithTooltip
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  webapp/channels/src/components/actions_menu/actions_menu.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#27422 [MM-58408] Migrate tooltips of 'components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav' to WithTooltip
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/__snapshots__/file_preview_modal_main_nav.test.tsx.snap
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27459 Change PerformanceReporter tests to not check exact values for timestamps
  webapp/channels/src/utils/performance_telemetry/reporter.test.ts
Labels: 2: Dev Review, release-note-none

#27447 [MM-58409] Migrate tooltips of 'components/file_preview_modal/popover_bar/popover_bar' to WithTooltip
  webapp/channels/src/components/file_preview_modal/popover_bar/__snapshots__/popover_bar.test.tsx.snap
  webapp/channels/src/components/file_preview_modal/popover_bar/popover_bar.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#27442 MM-58755 - Fixing inproduct notices spacing
  webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  webapp/channels/src/components/product_notices_modal/product_notices_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#27362 Bubble up parsing error from en.json
  tools/mmgotool/commands/i18n.go
Labels: 4: Reviews Complete, release-note-none
