Repository mattermost/mattermost, pull requests merged in 2024-02, with the labels that each got.

#26047 Allow HEAD requests on public files
  server/channels/api4/file.go
  server/channels/api4/file_test.go
Labels: 4: Reviews Complete, release-note-none

#26087 Fix shortcuts alignment on tooltips
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA/Review Done, release-note

#26092 Automated cherry pick of #26087
  webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25579 MM 55199 Limit User Preferences
  api/v4/source/preferences.yaml
  server/channels/api4/preference.go
  server/channels/api4/preference_test.go
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26039 [MM-55734] Add Request Context to ChannelStore.SaveMember
  server/channels/app/channel.go
  server/channels/app/email/helper_test.go
  server/channels/store/localcachelayer/channel_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/channel_layer.go
  server/channels/store/searchtest/helper.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_member_history_store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/channel_store_categories.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/remote_cluster_store.go
  server/channels/store/storetest/retention_policy_store.go
  server/channels/store/storetest/shared_channel_store.go
  server/channels/store/storetest/team_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Docs/Not Needed, EETests, QA/Review Not Required, release-note-none, Contributor

#26071 [MM-56680] Use Golang UnixMilli instead of UnixNano in Milli helpers
  server/public/model/utils.go
Labels: 2: Dev Review, release-note-none

#26090 MM-56705 Don't send post when clicking on the more formatting options button
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.test.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/hooks.tsx
Labels: 4: Reviews Complete, release-note

#26086 MM-56596 Fix username style in profile popover
  webapp/channels/src/components/profile_popover/profile_popover_name/user_name.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25957 MM-56536 Do not update team members scheme roles if user is guest
  server/channels/api4/team_test.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26108 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/hu.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/sv.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#26007 Improve Redux action types part 8/Rename NewActionFunc* back to ActionFunc*
  webapp/channels/src/actions/apps.ts
  webapp/channels/src/actions/channel_actions.ts
  webapp/channels/src/actions/cloud.tsx
  webapp/channels/src/actions/command.ts
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/actions/hooks.js
  webapp/channels/src/actions/hosted_customer.tsx
  webapp/channels/src/actions/integration_actions.tsx
  webapp/channels/src/actions/invite_actions.ts
  webapp/channels/src/actions/marketplace.ts
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/post_actions.ts
  webapp/channels/src/actions/status_actions.ts
  webapp/channels/src/actions/team_actions.ts
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/actions/views/channel.ts
  webapp/channels/src/actions/views/channel_sidebar.ts
  webapp/channels/src/actions/views/create_comment.tsx
  webapp/channels/src/actions/views/drafts.ts
  webapp/channels/src/actions/views/lhs.ts
  webapp/channels/src/actions/views/login.ts
  webapp/channels/src/actions/views/onboarding_tasks.ts
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/actions/views/root.ts
  webapp/channels/src/components/advanced_create_post/index.ts
  webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts
  webapp/channels/src/components/msg_typing/actions.ts
  webapp/channels/src/components/permalink_view/actions.ts
  webapp/channels/src/components/post/actions.ts
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/apps.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/boards.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channel_categories.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/emojis.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/errors.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/files.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/helpers.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/integrations.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/preferences.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/schemes.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/search.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/teams.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/timezone.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/types/actions.ts
  webapp/channels/src/plugins/products.ts
  webapp/channels/src/utils/channel_utils.tsx
Labels: 4: Reviews Complete, release-note-none

#26085 [MM-54750] Theme color sidebarHeaderTextColor is used with different backgrounds
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25954 MM-56513 Prevent deactivated users to be added as channel members
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note-none

#26099 [MM-56758] Enhance search implementation for Admin console
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.test.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.tsx
  webapp/channels/src/components/admin_console/highlight.tsx
  webapp/channels/src/components/admin_console/search_keyword_marking.tsx
  webapp/channels/src/components/admin_console/system_users/__snapshots__/system_users.test.tsx.snap
  webapp/channels/src/components/admin_console/system_users/system_users.tsx
Labels: 4: Reviews Complete, release-note-none

#26134 Automated cherry pick of #25946
  webapp/channels/src/utils/markdown/renderer.test.tsx
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26136 Automated cherry pick of #25955
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26137 Automated cherry pick of #25955
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26138 Automated cherry pick of #25955
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26140 Cherry pick of #25955
  server/Makefile
Labels: release-note-none

#26118 MM-53919 Add imagemin-gifsicle and imagemin-mozjpeg as required dependencies
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#26061 MM-55736 Add Request Context to TeamStore.SaveMember
  server/channels/app/channel_category_test.go
  server/channels/app/email/helper_test.go
  server/channels/app/slashcommands/auto_users.go
  server/channels/app/slashcommands/command_loadtest.go
  server/channels/app/teams/teams.go
  server/channels/manualtesting/manual_testing.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/team_layer.go
  server/channels/store/searchtest/helper.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/compliance_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/TeamStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/retention_policy_store.go
  server/channels/store/storetest/team_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none, Contributor

#26147 fixing typo
  server/i18n/en.json
Labels: release-note-none, Contributor

#25455 Mm 52993 - expose enable user statuses to client
  server/config/client.go
  server/config/client_test.go
  webapp/channels/src/actions/status_actions.test.ts
  webapp/channels/src/actions/status_actions.ts
  webapp/channels/src/actions/user_actions.test.ts
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/components/channel_layout/channel_controller.test.tsx
  webapp/channels/src/components/channel_layout/channel_controller.tsx
  webapp/channels/src/components/msg_typing/actions.test.ts
  webapp/channels/src/components/msg_typing/actions.ts
  webapp/channels/src/components/reset_status_modal/reset_status_modal.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/teams.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#26145 Server side FeatureFlag check
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/public/model/feature_flags.go
Labels: release-note-none

#26123 MM-56759 Fix crash caused by joinPrivateChannelPrompt
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26018 [MM-56602] Clicking outside the file preview area doesn't close the modal
  webapp/channels/src/sass/components/_modal.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#25721 mmctl: user preferences
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/user_e2e_test.go
  server/cmd/mmctl/docs/mmctl_user.rst
  server/cmd/mmctl/docs/mmctl_user_preference.rst
  server/cmd/mmctl/docs/mmctl_user_preference_delete.rst
  server/cmd/mmctl/docs/mmctl_user_preference_get.rst
  server/cmd/mmctl/docs/mmctl_user_preference_list.rst
  server/cmd/mmctl/docs/mmctl_user_preference_set.rst
  server/cmd/mmctl/mocks/client_mock.go
Labels: 4: Reviews Complete, release-note

#26062 MM-56180 changed CRTNotifier condition
  server/channels/app/notification.go
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note, Contributor

#26131 Add test case for non channel admin accessing post links
  e2e-tests/cypress/tests/integration/channels/messaging/channel_and_posts_links_spec.js
Labels: release-note-none

#26154 Add type inference for isFormatTokenLimitError function
  webapp/channels/src/utils/text_formatting.tsx
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, release-note-none

#26157 Automated cherry pick of #26154
  webapp/channels/src/utils/text_formatting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26156 Automated cherry pick of #26154
  webapp/channels/src/utils/text_formatting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26135 Automated cherry pick of #25946
  webapp/channels/src/utils/markdown/renderer.test.tsx
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26150 [MM-56782][MM-56783] Fix two small visuals with the user reporting interface
  webapp/channels/src/components/admin_console/system_users/system_users_date_range_menu/system_users_date_range_menu.scss
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA/Review Done, release-note-none

#26162 cherry pick of #25946
  webapp/channels/src/utils/markdown/renderer.test.tsx
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26161 cherry pick of #25946
  webapp/channels/src/utils/markdown/renderer.test.tsx
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26172 fix build: do not delete an empty set of preferences
  server/cmd/mmctl/commands/user_e2e_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Not Required, release-note-none

#26155 Cherry pick of 7d43712 (#25975) into release 8.1
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/documents.go
Labels: release-note-none

#26159 Cherry pick of 7d43712 (#25975) into release 9.2
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/documents.go
Labels: release-note-none

#26163 Cherry pick of 7d43712 (#25975) into release 9.3
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/documents.go
Labels: release-note-none

#26164 Cherry pick of 7d43712 (#25975) into release 9.4
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/documents.go
Labels: release-note-none

#25842 [MM-56455] Handle HTTP error for too large request body in Client4
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#26176 Automated cherry pick of #26100
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/saml.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/token.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26177 Automated cherry pick of #26100
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/saml.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/token.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26178 Automated cherry pick of #26100
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/saml.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/token.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26179 MM-56752 9.2 cherry pick
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/saml.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/token.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26181 MM-56752 8.1 cherry pick
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/oauth.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/saml.go
  server/channels/web/saml.go
  server/i18n/en.json
  server/public/model/token.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26165 [MM-56683] Auto select first emoji in emoji picker
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26182 Update minimum supported Edge and Chrome versions
  server/i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note

#26183 Fix racy unit tests by protecting Shared Channels service ref with a mutex
  server/channels/app/platform/service.go
  server/channels/app/platform/shared_channel_notifier.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26187 Automated cherry pick of #26182
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26188 Automated cherry pick of #26183
  server/channels/app/platform/service.go
  server/channels/app/platform/shared_channel_notifier.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26077 End to End test for Admin Reporting for Users, new User Management screen
  e2e-tests/playwright/support/ui/components/channels/generic_confirm_modal.ts
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/components/system_console/navbar.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/column_toggle_menu.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/filter_menu.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/filter_popover.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/system_users.ts
  e2e-tests/playwright/support/ui/components/system_console/sidebar.ts
  e2e-tests/playwright/support/ui/pages/index.ts
  e2e-tests/playwright/support/ui/pages/system_console.ts
  e2e-tests/playwright/support/util.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/actions.spec.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/column_sort.spec.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/column_toggler.spec.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/export_data.spec.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/filter_popover.spec.ts
  e2e-tests/playwright/tests/functional/system_console/system_users/search.spec.ts
  webapp/channels/src/components/admin_console/system_users/system_users_export/export_user_data_modal.tsx
  webapp/channels/src/components/confirm_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#26057 Add some more tests to the plugin API
  server/channels/app/plugin_api_test.go
  server/public/plugin/api.go
Labels: 4: Reviews Complete, AutoMerge, QA/Review Not Required, release-note-none

#26111 Migrate "cluster_settings.test.jsx, message_export_settings.test.jsx, schema_admin_settings.test.jsx, interactive_dialog/index.js" to Typescript
  webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/cluster_settings.test.tsx
  webapp/channels/src/components/admin_console/message_export_settings.test.tsx
  webapp/channels/src/components/admin_console/message_export_settings.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.test.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/interactive_dialog/dialog_introduction_text.tsx
  webapp/channels/src/components/interactive_dialog/index.ts
  webapp/channels/src/components/interactive_dialog/interactive_dialog.test.tsx
  webapp/channels/src/components/interactive_dialog/interactive_dialog.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/index.ts
  webapp/platform/types/src/integrations.ts
Labels: 4: Reviews Complete, release-note-none

#26143 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/en_AU.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none

#26158 [MM-56572] Preview doesn't work when editing a channel header
  webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
  webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
  webapp/channels/src/components/edit_channel_header_modal/index.ts
  webapp/channels/src/components/textbox/textbox_links.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_modal.scss
Labels: 4: Reviews Complete, release-note-none

#26126 [MM-56654] Turn off landing page for Desktop App token flow, cleanup check for landing page
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
Labels: 4: Reviews Complete, release-note

#26151 [MM-56478] Only clear the suggestion pretext when the suggestion is completed and not when the list is cleared
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#25433 [MM-55469] Don't show ldap job details until job runs
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#25343 [MM-53935] Log message if user tries to login using wrong password
  server/channels/app/authentication.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26196 Fix system console plugin headers
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA/Review Done, release-note

#26201 Cherry-picking Translations Weblate (#26143)
  server/i18n/de.json
  server/i18n/en_AU.json
  server/i18n/ja.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en_AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Contributor

#26203 Automated cherry pick of #26196
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26009 MM-56358: Unskip racy test TestUploadLicenseFile
  server/channels/api4/license_test.go
  server/channels/jobs/batch_worker.go
  server/channels/jobs/batch_worker_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
Labels: 4: Reviews Complete, release-note-none

#26122 Improve types of testing utilities and fix some types in unit test code
  webapp/channels/.eslintrc.json
  webapp/channels/src/actions/channel_actions.test.ts
  webapp/channels/src/actions/global_actions.test.ts
  webapp/channels/src/actions/invite_actions.test.ts
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/user_actions.test.ts
  webapp/channels/src/components/admin_console/license_settings/modals/confirm_license_removal_modal.test.tsx
  webapp/channels/src/components/admin_console/license_settings/modals/upload_license_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/team_warning_banner/team_warning_banner.test.tsx
  webapp/channels/src/components/channel_layout/channel_identifier_router/actions.test.ts
  webapp/channels/src/components/cloud_start_trial/cloud_start_trial_btn.test.tsx
  webapp/channels/src/components/cloud_start_trial/request_business_email_modal.test.tsx
  webapp/channels/src/components/cloud_subscribe_result_modal/error.test.tsx
  webapp/channels/src/components/cloud_subscribe_result_modal/success.test.tsx
  webapp/channels/src/components/dot_menu/dot_menu.test.tsx
  webapp/channels/src/components/external_link/external_link.test.tsx
  webapp/channels/src/components/learn_more_trial_modal/learn_more_trial_modal.test.tsx
  webapp/channels/src/components/learn_more_trial_modal/learn_more_trial_modal_step.test.tsx
  webapp/channels/src/components/learn_more_trial_modal/start_trial_btn.test.tsx
  webapp/channels/src/components/main_menu/main_menu.test.tsx
  webapp/channels/src/components/permalink_view/permalink_view.test.tsx
  webapp/channels/src/components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx
  webapp/channels/src/components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  webapp/channels/src/components/rhs_header_post/rhs_header_post.spec.tsx
  webapp/channels/src/components/search_results/search_limits_banner.test.tsx
  webapp/channels/src/components/sidebar/invite_members_button.test.tsx
  webapp/channels/src/components/sidebar/sidebar.test.tsx
  webapp/channels/src/components/suggestion/search_channel_with_permissions_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/team_controller/actions/index.test.ts
  webapp/channels/src/components/three_days_left_trial_modal/three_days_left_trial_modal.test.tsx
  webapp/channels/src/components/trial_benefits_modal/trial_benefits_modal.test.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
  webapp/channels/src/components/user_groups_modal/ad_ldap_upsell_banner.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_start_trial.test.tsx
  webapp/channels/src/components/widgets/users/avatars/avatars.test.tsx
  webapp/channels/src/components/youtube_video/youtube_video.test.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/test/merge_objects.ts
  webapp/channels/src/tests/test_store.tsx
  webapp/platform/types/src/utilities.ts
Labels: 4: Reviews Complete, release-note-none

#26129 Add handling of posts with unsafe links.
  webapp/channels/src/components/markdown_image/index.ts
  webapp/channels/src/components/markdown_image/markdown_image.test.tsx
  webapp/channels/src/components/markdown_image/markdown_image.tsx
  webapp/channels/src/utils/markdown/index.test.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/url.tsx
Labels: release-note-none

#26144 Add some tests for plugin hooks used by MS Teams plugin automute
  server/channels/app/plugin_hooks_test.go
Labels: 4: Reviews Complete, release-note-none

#26189 MM-56571 - Update prepackaged calls to v0.24.0
  server/Makefile
Labels: 2: Dev Review, Docs/Needed, CherryPick/Approved, Setup Cloud Test Server, release-note

#26220 Automated cherry pick of #26189
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#25985 MM-56579: Include deactivated users from DM posts
  server/channels/app/export.go
  server/channels/app/export_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note

#26152 Allow plugins to specify all props for create comment.
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_comment/index.ts
  webapp/channels/src/plugins/exported_create_post.tsx
Labels: 4: Reviews Complete, release-note-none

#26168 [MM-56798] Smoothen animation and lazy load User Settings
  webapp/channels/src/components/user_settings/modal/index.ts
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#26193 [MM-56824] Componentize the Mobile and Desktop section headers in the user settings modal.
  webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
  webapp/channels/src/components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/import_theme_modal/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/user_settings/display/user_settings_theme/import_theme_modal/index.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/import_theme_modal/index.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/components/user_settings/headers/setting_desktop_header.scss
  webapp/channels/src/components/user_settings/headers/setting_desktop_header.test.tsx
  webapp/channels/src/components/user_settings/headers/setting_desktop_header.tsx
  webapp/channels/src/components/user_settings/headers/setting_mobile_header.test.tsx
  webapp/channels/src/components/user_settings/headers/setting_mobile_header.tsx
  webapp/channels/src/components/user_settings/index.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.scss
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/channels/src/components/user_settings/plugin/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/user_settings/plugin/index.test.tsx
  webapp/channels/src/components/user_settings/plugin/index.tsx
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
  webapp/channels/src/components/user_settings/setting_desktop_header.tsx
  webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx
Labels: 4: Reviews Complete, release-note-none

#23612 [MM-52171] webapp: Make rhs_card reloading when card body is changed
  webapp/channels/src/components/rhs_card/__snapshots__/rhs_card.test.tsx.snap
  webapp/channels/src/components/rhs_card/rhs_card.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note, Contributor

#25669 [MM-53156] Remove Multi-Product architecture
  server/channels/api4/apitestlib.go
  server/channels/app/app.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/channel.go
  server/channels/app/channels.go
  server/channels/app/cloud.go
  server/channels/app/cluster_handlers.go
  server/channels/app/file.go
  server/channels/app/helper_test.go
  server/channels/app/license.go
  server/channels/app/notification_push_test.go
  server/channels/app/onboarding.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/options.go
  server/channels/app/permissions.go
  server/channels/app/platform/cluster.go
  server/channels/app/platform/config.go
  server/channels/app/plugin.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/plugin_requests.go
  server/channels/app/plugin_signature.go
  server/channels/app/post.go
  server/channels/app/preference.go
  server/channels/app/product.go
  server/channels/app/product_test.go
  server/channels/app/server.go
  server/channels/app/server_test.go
  server/channels/app/team.go
  server/channels/product/README.md
  server/channels/product/api.go
  server/channels/product/doc.go
  server/channels/product/product.go
  server/channels/product/service.go
  server/channels/store/store.go
  server/channels/web/web_test.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/public/plugin/interface_generator/main.go
  server/public/plugin/product.go
  server/public/plugin/product_hooks_generated.go
  server/public/pluginapi/bot.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#26230 MM-56878: Remove unused store method
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none

#26216 Promote/downgrade some languages
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/i18n/i18n.jsx
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, AutoMerge, release-note

#26125 Fix types of various fields in GlobalState
  webapp/channels/src/actions/channel_actions.test.ts
  webapp/channels/src/actions/global_actions.test.ts
  webapp/channels/src/actions/status_actions.test.ts
  webapp/channels/src/actions/user_actions.test.ts
  webapp/channels/src/actions/views/channel_sidebar.test.ts
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_members/index.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/easy_management.ts
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/channels/src/components/analytics/team_analytics/team_analytics.tsx
  webapp/channels/src/components/channel_info_rhs/about_area_channel.test.tsx
  webapp/channels/src/components/channel_info_rhs/about_area_dm.test.tsx
  webapp/channels/src/components/channel_info_rhs/about_area_gm.test.tsx
  webapp/channels/src/components/channel_layout/channel_identifier_router/actions.test.ts
  webapp/channels/src/components/more_direct_channels/index.ts
  webapp/channels/src/components/more_direct_channels/list/index.test.ts
  webapp/channels/src/components/sidebar/invite_members_button.test.tsx
  webapp/channels/src/components/sidebar/sidebar.test.tsx
  webapp/channels/src/components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
  webapp/channels/src/components/suggestion/search_channel_with_permissions_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/system_notice/notices.tsx
  webapp/channels/src/components/system_notice/system_notice.tsx
  webapp/channels/src/components/system_notice/types.ts
  webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.test.js
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/threads.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/selectors/drafts.test.ts
  webapp/channels/src/selectors/views/channel_sidebar.test.js
  webapp/channels/src/tests/constants/users.ts
  webapp/platform/types/src/admin.ts
  webapp/platform/types/src/channels.ts
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26237 [MM-56846] Convert `./components/analytics/table_chart.tsx` from Class Component to Function Component
  webapp/channels/src/components/analytics/table_chart.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#26226 MM-56776 Call ChannelHasBeenCreated plugin hook for GMs
  server/channels/app/channel.go
  server/channels/app/plugin_hooks_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#26231 fixing filenames
  server/i18n/en-AU.json
  server/i18n/kk-Latn.json
  server/i18n/nb-NO.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/i18n.jsx
  webapp/channels/src/i18n/kk-Latn.json
  webapp/channels/src/i18n/nb-NO.json
Labels: 2: Dev Review, QA/Review Done, release-note, Contributor

#26247 MM-56776 Call ChannelHasBeenCreated plugin hook for GMs (9.6)
  server/channels/app/channel.go
  server/channels/app/plugin_hooks_test.go
Labels: 4: Reviews Complete, CherryPick/Done, release-note

#26109 [MM-55737] Add Request Context to UserStore.Save
  server/channels/api4/ldap_test.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/bot_test.go
  server/channels/app/channel.go
  server/channels/app/email/helper_test.go
  server/channels/app/import_functions.go
  server/channels/app/notify_admin.go
  server/channels/app/notify_admin_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/helper_test.go
  server/channels/app/post.go
  server/channels/app/report.go
  server/channels/app/server.go
  server/channels/app/teams/helper_test.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/app/users/helper_test.go
  server/channels/app/users/users.go
  server/channels/app/users/users_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/user_layer.go
  server/channels/store/searchtest/helper.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/store.go
  server/channels/store/storetest/bot_store.go
  server/channels/store/storetest/channel_member_history_store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/compliance_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/UserStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/retention_policy_store.go
  server/channels/store/storetest/shared_channel_store.go
  server/channels/store/storetest/team_store.go
  server/channels/store/storetest/terms_of_service_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/storetest/user_access_token_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/slackimport/slackimport.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none, Contributor

#26238 [MM-56843] Convert `./actions/views/modals.test.jsx` from Class Component to Function Component
  webapp/channels/src/actions/views/modals.test.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#25812 Migration typescript/channel sidebar.js
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category.d.ts
  e2e-tests/cypress/tests/support/ui/channel_sidebar.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#25811 Migration typescript/team.js
  e2e-tests/cypress/tests/support/ui/team.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#25730 Migration: typescript/okta commands.js
  e2e-tests/cypress/tests/support/okta_commands.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#25324 [GH-25298] Place the text centered in default profile picture
  server/channels/app/users/errors.go
  server/channels/app/users/profile_picture.go
Labels: 4: Reviews Complete, kind/bug, release-note, Contributor

#24182 fixed typos
  api/v4/source/bots.yaml
Labels: 4: Reviews Complete, EETests, release-note-none

#25788 MM 19654 s3 debugging logs overlap, Wrapped mlog in an io.Writer func
  server/platform/shared/filestore/s3store.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#25840 Migration typescript/enterprise/ldap
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_group_sync_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_guest_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_login_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_setting_spec.ts
  e2e-tests/cypress/tests/support/api/preference.d.ts
  e2e-tests/cypress/tests/support/common_login_commands.d.ts
  e2e-tests/cypress/tests/support/ldap_commands.d.ts
Labels: 2: Dev Review, release-note-none, Contributor

#26079 [MM-56348] system/ping: add new method with options
  api/v4/source/system.yaml
  server/channels/api4/system.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/system.go
  server/cmd/mmctl/commands/system_test.go
  server/cmd/mmctl/mocks/client_mock.go
  server/public/model/client4.go
  server/public/model/system.go
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note

#26072 [CLD-6630] Cleanup: Refactor IP Filters email notification logic into app layer
  server/channels/api4/ip_filtering.go
  server/channels/app/app_iface.go
  server/channels/app/ip_filtering.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, release-note-none

#26048 [MM-55735] Add Request Context to PostStore.Save
  server/channels/api4/apitestlib.go
  server/channels/app/channel_test.go
  server/channels/app/post.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/post_layer.go
  server/channels/store/searchtest/helper.go
  server/channels/store/sqlstore/integrity_test.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/compliance_store.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/file_info_store.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/slackimport/slackimport.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note-none, Contributor

#26262 Log warning when plugin using Shared Channels APIs is uninstalled
  server/channels/app/shared_channel.go
Labels: 2: Dev Review, release-note-none

#26132 [MM-56660] When deleting a draft , the modal delete button does not have focus
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  webapp/channels/src/components/drafts/draft_actions/delete_draft_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#25729 MM-41586: Team setting modal UI update
  e2e-tests/cypress/tests/integration/channels/team_settings/closed_team_invite_by_email_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/invite_user_to_closed_team_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/remove_team_icon_spec.js
  e2e-tests/cypress/tests/integration/channels/team_settings/teams_spec.js
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/common/select_text_input/select_text_input.scss
  webapp/channels/src/components/common/select_text_input/select_text_input.tsx
  webapp/channels/src/components/main_menu/index.tsx
  webapp/channels/src/components/main_menu/main_menu.test.tsx
  webapp/channels/src/components/main_menu/main_menu.tsx
  webapp/channels/src/components/payment_form/address_form.tsx
  webapp/channels/src/components/payment_form/payment_form.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/team_general_tab/__snapshots__/open_invite.test.tsx.snap
  webapp/channels/src/components/team_general_tab/__snapshots__/team_general_tab.test.tsx.snap
  webapp/channels/src/components/team_general_tab/open_invite.test.tsx
  webapp/channels/src/components/team_general_tab/open_invite.tsx
  webapp/channels/src/components/team_general_tab/team_general_tab.scss
  webapp/channels/src/components/team_general_tab/team_general_tab.test.tsx
  webapp/channels/src/components/team_general_tab/team_general_tab.tsx
  webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx
  webapp/channels/src/components/team_settings/team_access_tab/index.ts
  webapp/channels/src/components/team_settings/team_access_tab/invite_section_input.tsx
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.test.tsx
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx
  webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.scss
  webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.test.tsx
  webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.tsx
  webapp/channels/src/components/team_settings/team_info_tab/index.ts
  webapp/channels/src/components/team_settings/team_info_tab/team_description_section.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_info_tab.scss
  webapp/channels/src/components/team_settings/team_info_tab/team_info_tab.test.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_info_tab.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_name_section.tsx
  webapp/channels/src/components/team_settings/team_info_tab/team_picture_section.scss
  webapp/channels/src/components/team_settings/team_info_tab/team_picture_section.tsx
  webapp/channels/src/components/team_settings/team_settings.tsx
  webapp/channels/src/components/team_settings_modal/__snapshots__/team_settings_modal.test.tsx.snap
  webapp/channels/src/components/team_settings_modal/index.ts
  webapp/channels/src/components/team_settings_modal/team_settings_modal.test.tsx
  webapp/channels/src/components/team_settings_modal/team_settings_modal.tsx
  webapp/channels/src/components/widgets/inputs/input/input.scss
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/components/widgets/inputs/url_input/url_input.tsx
  webapp/channels/src/components/widgets/modals/components/base_setting_item.scss
  webapp/channels/src/components/widgets/modals/components/base_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/checkbox_setting_item.tsx
  webapp/channels/src/components/widgets/modals/components/modal_section.scss
  webapp/channels/src/components/widgets/modals/components/modal_section.tsx
  webapp/channels/src/components/widgets/modals/components/save_changes_panel.scss
  webapp/channels/src/components/widgets/modals/components/save_changes_panel.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_settings-modal.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/sass/routes/_settings.scss
  webapp/channels/src/utils/utils.tsx
  webapp/platform/types/src/teams.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26234 [MM-56849] Convert `./components/post_view/failed_post_options/failed_post_options.tsx` from Class Component to Function Component
  webapp/channels/src/components/post_view/failed_post_options/failed_post_options.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#26233 [MM-56844] Convert `./components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26263 Removed limited reader from util deserializers
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/outgoing_oauth_connection.go
  server/channels/api4/post.go
  server/channels/api4/preference.go
  server/channels/api4/reaction.go
  server/channels/api4/role.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/team_local.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: release-note-none

#26073 [CLD-6430] Remove telemetry check from true_up_review
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  webapp/channels/src/components/analytics/true_up_review.test.tsx
  webapp/channels/src/components/analytics/true_up_review.tsx
Labels: 1: PM Review, release-note-none

#26227 MM-56822 Update logic around permissions and sanitization
  server/channels/api4/team_test.go
  server/channels/app/team.go
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26199 Metrics for shared channels
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/platform/services/remotecluster/sendfile.go
  server/platform/services/remotecluster/sendprofileImage.go
  server/platform/services/sharedchannel/mock_ServerIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
Labels: 2: Dev Review, release-note-none

#25794 MM-56201, MM-56280: Suppress typing and emoji events
  server/channels/app/platform/web_conn.go
  server/channels/app/web_conn_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
  webapp/channels/src/components/channel_view/channel_view.test.tsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/channel_view/index.ts
  webapp/channels/src/components/team_sidebar/index.ts
  webapp/channels/src/components/team_sidebar/team_sidebar.tsx
  webapp/channels/src/components/threading/thread_viewer/index.ts
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
  webapp/channels/src/utils/test_helper.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/posts.ts
Labels: 4: Reviews Complete, release-note-none

#26256 Remove unnecessary cache invalidation for channel
  server/platform/services/sharedchannel/service.go
Labels: 4: Reviews Complete, release-note-none

#26242 [MM-56889] Add PositionAttribute to LDAP test data
  server/Makefile
  server/tests/test-data.ldif
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#26281 Revert "MM-56201, MM-56280: Suppress typing and emoji events"
  server/channels/app/platform/web_conn.go
  server/channels/app/web_conn_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
  webapp/channels/src/components/channel_view/channel_view.test.tsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/channel_view/index.ts
  webapp/channels/src/components/team_sidebar/index.ts
  webapp/channels/src/components/team_sidebar/team_sidebar.tsx
  webapp/channels/src/components/threading/thread_viewer/index.ts
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
  webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
  webapp/channels/src/utils/test_helper.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/posts.ts
Labels: 4: Reviews Complete, release-note-none

#26283 Fix flaky IP Filtering test
  server/channels/api4/ip_filtering_test.go
Labels: 4: Reviews Complete, release-note-none

#26246 [MM-56901] Exclude selectors that have less than 5 calls from telemetry
  webapp/channels/src/actions/telemetry_actions.jsx
Labels: 2: Dev Review, release-note-none

#26264 MM-56925: Fix unnecessary cache invalidation of pinned post count
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/reaction.go
Labels: 4: Reviews Complete, release-note-none

#26045 Deprecate admin advisor
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: 2: Dev Review, release-note

#25836 [MM-56400] Allow mmctl to download a Support Packet using --local mode
  server/channels/api4/system_local.go
  server/channels/api4/system_test.go
Labels: 4: Reviews Complete, release-note

#26268 Don't email licensed/internal customers about Cloud Renewals
  server/channels/app/cloud.go
  server/public/model/cloud.go
Labels: 4: Reviews Complete, release-note-none

#26302 Update prepackaged calls to v0.23.1 - v8.1 branch
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#26288 Fix thread icon size and color
  webapp/channels/src/components/threading/global_threads_link/global_threads_link.scss
  webapp/channels/src/components/threading/global_threads_link/threads_icon.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note-none

#26303 [MM-54359] Manual cherry pick (release-8.1)
  server/channels/api4/plugin_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/plugin_api_tests/manual.test_websocket_session/main.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26259 [MM-56850] Convert `./components/modal_controller/modal_controller.tsx` from Class Component to Function Component
  webapp/channels/src/components/modal_controller/modal_controller.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#26295 MM-56985 Remove babel-plugin-lodash
  webapp/channels/.eslintrc.json
  webapp/channels/babel.config.js
  webapp/channels/package.json
  webapp/channels/src/actions/status_actions.test.ts
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/components/admin_console/data_retention_settings/channel_list/channel_list.tsx
  webapp/channels/src/components/admin_console/data_retention_settings/team_list/team_list.tsx
  webapp/channels/src/components/admin_console/group_settings/group_details/group_teams_and_channels_row.tsx
  webapp/channels/src/components/admin_console/group_settings/group_details/group_users.test.tsx
  webapp/channels/src/components/admin_console/member_list_group/member_list_group.test.tsx
  webapp/channels/src/components/admin_console/server_logs/logs.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_profile.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/hooks.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/payment_announcement_bar/index.tsx
  webapp/channels/src/components/app_bar/app_bar.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.tsx
  webapp/channels/src/components/cloud_start_trial/request_business_email_modal.tsx
  webapp/channels/src/components/common/hocs/cloud/with_get_cloud_subscription.tsx
  webapp/channels/src/components/custom_open_plugin_install_post_renderer/index.tsx
  webapp/channels/src/components/integrations/outgoing_oauth_connections/oauth_connection_audience_input.tsx
  webapp/channels/src/components/menu/menu_item.tsx
  webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
  webapp/channels/src/components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  webapp/channels/src/components/purchase_modal/purchase_modal.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
  webapp/channels/src/components/threading/global_threads/thread_menu/thread_menu.test.tsx
  webapp/channels/src/components/timestamp/timestamp.tsx
  webapp/channels/src/components/user_group_popover/user_group_popover.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/reducers/views/threads.ts
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/utils/func.ts
  webapp/channels/src/utils/paste.tsx
  webapp/channels/src/utils/utils.tsx
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#26170 [MM-56661] Fix: When deleting a draft you have to move your cursor away from the card and back to activate the buttons
  webapp/channels/src/components/drafts/panel/__snapshots__/panel.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26285 Fix multiple timer issue in CopyButton by using useRef
  webapp/channels/src/components/copy_button.tsx
Labels: 4: Reviews Complete, kind/bug, release-note-none, Contributor

#26307 Fix typo
  server/channels/app/import_functions_test.go
  server/cmd/mmctl/commands/config_e2e_test.go
  server/cmd/mmctl/commands/config_test.go
  server/cmd/mmctl/commands/utils_unix.go
  server/cmd/mmctl/commands/utils_windows.go
Labels: 2: Dev Review, release-note-none

#26236 [MM-56845] Convert `./components/suggestion/suggestion_date.tsx` from Class Component to Function Component
  webapp/channels/src/components/suggestion/suggestion_date.tsx
Labels: release-note-none, Setup Cloud + CWS Test Server, Contributor

#26257 [MM-56842] Convert `./components/status_icon.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  webapp/channels/src/components/status_icon.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, Setup Cloud + CWS Test Server, Contributor

#26284 MM-56965 - Updating header icon value
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_icon.tsx
  webapp/channels/src/components/channel_info_rhs/menu.tsx
  webapp/channels/src/components/channel_info_rhs/top_buttons.tsx
  webapp/channels/src/sass/admin_console_base/_sys_css_variables.scss
  webapp/channels/src/sass/base/_css_variables.scss
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/layout/_headers.scss
Labels: 4: Reviews Complete, release-note-none

#26301 MM-56780: Ensure p.Integration is not nil
  server/public/model/integration_action.go
  server/public/model/integration_action_test.go
Labels: 2: Dev Review, release-note-none

#26243 [MM-56890] Expose allocs and mutex pprof profiling data
  server/channels/app/platform/metrics.go
  server/channels/app/platform/metrics_test.go
Labels: 4: Reviews Complete, Docs/Needed, QA/Review Not Required, release-note-none

#26308 Manual cherrypick of #26045 for v9.6
  api/v4/source/system.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/support_packet_generation_spec.js
  server/channels/api4/system.go
  server/channels/app/admin_advisor.go
  server/channels/app/app_iface.go
  server/channels/app/bot.go
  server/channels/app/integration_action.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/system_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/SystemStore.go
  server/channels/store/storetest/system_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/model/post.go
  server/public/model/system.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/index.ts
  webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  webapp/channels/src/components/warn_metric_ack_modal/index.ts
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  webapp/channels/src/components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/websocket.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26128 MM-56090 Group Search fix
  webapp/channels/src/packages/mattermost-redux/src/utils/group_utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/group_utils.ts
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26279 marked some missed file APIs
  server/channels/api4/ldap.go
  server/channels/api4/license.go
  server/channels/api4/license_local.go
  server/channels/api4/plugin.go
  server/channels/api4/plugin_local.go
  server/channels/api4/remote_cluster.go
Labels: 4: Reviews Complete, release-note-none

#26318 feat: Upgrade github actions for node20
  .github/workflows/api.yml
  .github/workflows/docker-push-mirrored.yml
  .github/workflows/e2e-tests-ci.yml
  .github/workflows/esrupgrade-common.yml
  .github/workflows/i18n-ci-template.yml
  .github/workflows/migration.yml
  .github/workflows/mmctl-test-template.yml
  .github/workflows/sentry.yaml
  .github/workflows/server-ci-artifacts.yml
  .github/workflows/server-ci-master.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  .github/workflows/tag-public-module.yaml
  .github/workflows/webapp-ci-master.yml
  .github/workflows/webapp-ci-template.yml
Labels: kind/feature, release-note-none

#26133 [MM-19869] Remove unused SAML code
  server/i18n/en.json
Labels: 3: QA Review, release-note-none

#26304 MM-56781: Use correct error in doInviteRemote
  server/channels/app/slashcommands/command_share.go
  server/channels/app/slashcommands/command_share_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#26034 [CLD-7029] Add a new system console page for configuring custom export FileSettings
  server/channels/api4/system.go
  server/channels/api4/system_test.go
  server/channels/app/file.go
  server/public/model/config.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#26325 Cherry pick of #26098 and #26129
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  webapp/channels/src/components/markdown_image/index.ts
  webapp/channels/src/components/markdown_image/markdown_image.test.tsx
  webapp/channels/src/components/markdown_image/markdown_image.tsx
  webapp/channels/src/utils/markdown/index.test.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/url.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26070 [CLD-7046] Ability to disable self hosted server-side requests to CWS
  server/channels/api4/cloud.go
  server/i18n/en.json
  server/public/model/config.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26327 Cherry pick of #26098 and #26129
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  webapp/channels/src/components/markdown_image/index.ts
  webapp/channels/src/components/markdown_image/markdown_image.test.tsx
  webapp/channels/src/components/markdown_image/markdown_image.tsx
  webapp/channels/src/utils/markdown/index.test.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/url.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26328 Cherry pick of #26098 and #26129
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  webapp/channels/src/components/markdown_image/index.ts
  webapp/channels/src/components/markdown_image/markdown_image.test.tsx
  webapp/channels/src/components/markdown_image/markdown_image.tsx
  webapp/channels/src/utils/markdown/index.test.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/url.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26329 Cherry pick of #26098 and #26129
  .github/workflows/server-ci-template.yml
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  webapp/channels/src/components/markdown_image/index.js
  webapp/channels/src/components/markdown_image/markdown_image.jsx
  webapp/channels/src/components/markdown_image/markdown_image.test.jsx
  webapp/channels/src/utils/markdown/index.test.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/url.tsx
Labels: AutoMerge, release-note-none

#26239 MM-56877: Reduce usages of SessionHasPermissionToChannelByPost
  server/channels/api4/file.go
  server/channels/api4/file_test.go
  server/channels/api4/post.go
  server/channels/api4/reaction.go
  server/channels/app/authorization.go
  server/channels/app/reaction.go
Labels: 4: Reviews Complete, release-note-none

#26324 Update dependencies
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: 2: Dev Review, release-note-none

#26336 Automated cherry pick of #25579
  api/v4/source/preferences.yaml
  server/channels/api4/preference.go
  server/channels/api4/preference_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26337 Automated cherry pick of #26227
  server/channels/api4/team_test.go
  server/channels/app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26341 Automated cherry pick of #25579
  api/v4/source/preferences.yaml
  server/channels/api4/preference.go
  server/channels/api4/preference_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26343 Automated cherry pick of #26227
  server/channels/api4/team_test.go
  server/channels/app/team.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26273 [MM-56757] Expand NotificationsLog to include websocket and email, adding much more varied logging across the entire process
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/expirynotify.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/post_persistent_notification.go
  server/channels/app/reaction.go
  server/public/model/notification.go
Labels: 4: Reviews Complete, release-note

#26355 Manual Cherry-pick of 25510
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/emoji_test.go
  server/channels/api4/post.go
  server/channels/api4/reaction.go
  server/channels/api4/role.go
  server/channels/api4/role_test.go
  server/channels/api4/status.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/client4.go
  server/public/model/config.go
  server/public/model/utils.go
  server/public/model/utils_test.go
  tools/mmgotool/commands/i18n.go
Labels: release-note-none

#26356 Automated cherry pick of #26247
  server/channels/app/channel.go
  server/channels/app/plugin_hooks_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26218 Bump prepackage Github plugin version to 2.2.0
  server/Makefile
Labels: 4: Reviews Complete, release-note
