Repository mattermost/mattermost, pull requests merged in 2024-04, with the labels that each got.

#26623 Update playbooks to v1.39.2
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#26580 Update AI Plugin prepackaged version
  server/Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#26636 Update playbooks to v1.39.2
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note-none

#26637 Automated cherry pick of #26580
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26634 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/ja.json
  server/i18n/sv.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none

#26456 Removed unused compliance job from packet
  server/public/model/system.go
Labels: 4: Reviews Complete, release-note-none

#26507 MM-57154 - add license check to sysconsole items
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26572 [MM-55272] Accessibility: Team Icon requires tabbing twice
  webapp/channels/src/components/team_sidebar/components/team_button.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#26536 [MM-40568] Do not strip notification text for all platforms
  webapp/channels/src/actions/notification_actions.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#26578 [MM-57415] Removed unused IsOAuth field from AppError
  server/channels/web/handlers.go
  server/public/model/utils.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, QA/Review Not Required, release-note

#26605 MM-55252 Update RHS Thread View to Use Relative Timestamps
  webapp/channels/src/components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  webapp/channels/src/components/rhs_thread/rhs_thread.tsx
  webapp/channels/src/sass/components/_post-right.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26633 Add context to post reminder error logs
  server/channels/app/post.go
Labels: 4: Reviews Complete, release-note-none

#26619 MM-57512: Disable content extraction during import
  server/channels/app/app_iface.go
  server/channels/app/export_test.go
  server/channels/app/file.go
  server/channels/app/file_bench_test.go
  server/channels/app/file_test.go
  server/channels/app/import.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/import_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api_test.go
  server/channels/app/post_metadata_test.go
  server/channels/app/post_test.go
  server/channels/app/slack.go
  server/channels/app/user_test.go
  server/channels/jobs/import_process/worker.go
  server/cmd/mattermost/commands/import.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/docs/mmctl_import_process.rst
Labels: 4: Reviews Complete, release-note-none

#26645 Update default nginx client_max_body_size configuration
  server/build/docker/nginx/default.conf
Labels: 4: Reviews Complete, release-note-none

#26616 CLD-798 Add support for MM_ENV, various fixes
  .github/workflows/e2e-fulltests-ci.yml
  .github/workflows/e2e-tests-ci-template.yml
  .github/workflows/e2e-tests-ci.yml
  e2e-tests/Makefile
  e2e-tests/README.md
Labels: release-note-none

#26649 Improvements to logging start-up.
  server/channels/app/platform/config.go
  server/channels/app/platform/log.go
Labels: 2: Dev Review, release-note-none

#26313 [MM-56732] Update keycloak docker configs and add make command
  server/Makefile
  server/build/docker-compose.common.yml
  server/build/docker/keycloak/README.md
  server/build/docker/keycloak/keycloak.crt
  server/build/docker/keycloak/realm-export.json
  server/build/docker/keycloak/realm.json
  server/scripts/mirror-docker-images.json
Labels: 4: Reviews Complete, release-note

#26660 Remove very noisy log entry
  server/channels/app/post.go
Labels: 2: Dev Review, release-note-none

#26278 [MM-49243] - Use paged requests to request the list of teams
  server/cmd/mmctl/commands/channel.go
  server/cmd/mmctl/commands/channel_test.go
  server/cmd/mmctl/commands/command.go
  server/cmd/mmctl/commands/command_test.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/utils.go
  server/cmd/mmctl/commands/webhook.go
  server/cmd/mmctl/commands/webhook_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#26516 [MM-57298] Fix context cancellation for integration requests
  server/channels/app/integration_action.go
Labels: 4: Reviews Complete, release-note

#26471 [MM-54994] Use local requests instead of HTTP requests in the flow library
  server/public/pluginapi/experimental/flow/flow.go
  server/public/pluginapi/experimental/flow/handler.go
  server/public/pluginapi/experimental/flow/step.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26620 [MM-57356] Make use of go1.21 features
  server/channels/api4/user.go
  server/channels/api4/user_local.go
  server/channels/app/channel.go
  server/channels/app/notification_test.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/platform/web_conn.go
  server/channels/app/plugin_signature.go
  server/channels/app/role.go
  server/channels/app/role_test.go
  server/channels/app/session_test.go
  server/channels/app/user_agent.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/store/searchtest/testlib.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/storetest/group_store.go
  server/channels/utils/api.go
  server/channels/utils/utils.go
  server/cmd/mmctl/commands/sampledata.go
  server/public/model/command_autocomplete.go
  server/public/model/report.go
  server/public/model/websocket_message.go
  server/public/pluginapi/kv_memory.go
  server/public/utils/utils.go
  server/public/utils/utils_test.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#26665 Automated cherry pick of #26516
  server/channels/app/integration_action.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26540 [MM-57380] Fix running Support Packet tests locally
  server/channels/app/support_packet_test.go
Labels: 4: Reviews Complete, QA/Review Not Required, release-note-none

#26396 [MM-57078] Adding progress logs for attachments to bulk export job
  server/channels/app/export.go
Labels: 3: QA Review, release-note

#26651 Increased default payload limit from 100 kB to 300 kB
  server/public/model/config.go
Labels: release-note

#26533 [MM-57156] Make S3 upload part size configurable
  server/platform/shared/filestore/filesstore.go
  server/platform/shared/filestore/filesstore_test.go
  server/platform/shared/filestore/s3store.go
  server/platform/shared/filestore/s3store_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#26642 MM-57532: Improve timeouts for some tests
  server/channels/api4/channel_category_test.go
  server/channels/api4/channel_test.go
  server/channels/api4/commands_test.go
  server/channels/api4/integration_action_test.go
  server/channels/api4/post_test.go
  server/channels/api4/user_test.go
  server/channels/app/platform/web_hub_test.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_hooks_test.go
  server/channels/app/server_test.go
  server/channels/jobs/schedulers_test.go
  server/platform/services/telemetry/telemetry_test.go
  server/public/pluginapi/cluster/mutex_test.go
  server/public/pluginapi/kv_memory_test.go
Labels: 4: Reviews Complete, release-note-none

#26392 [MM-57085] Remove UseNewSAMLLibrary experimental setting
  e2e-tests/cypress/tests/integration/channels/enterprise/saml/okta_login_spec.js
  e2e-tests/cypress/tests/integration/channels/enterprise/saml/saml_automated_spec.js
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/app/channels.go
  server/channels/app/enterprise.go
  server/channels/app/enterprise_test.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, Docs/Not Needed, release-note

#26153 Send ephemeral message when a mentioned user is not a member of the team
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA/Review Done, release-note, Contributor

#26050 [MM-56653] Improve license loading errors
  server/channels/api4/license_test.go
  server/channels/app/license.go
  server/channels/app/platform/license.go
  server/channels/utils/license.go
  server/channels/utils/license_test.go
  server/channels/utils/mocks/LicenseValidatorIface.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA/Review Done, release-note

#26697 Automated cherry pick of #26650
  webapp/channels/package.json
  webapp/package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26696 Automated cherry pick of #26650
  webapp/channels/package.json
  webapp/package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26347 Added log to show which URL is blocked by CORS.
  server/channels/api4/websocket.go
  server/channels/api4/websocket_test.go
  server/i18n/en.json
Labels: 3: QA Review, Lifecycle/1:stale, release-note-none, Contributor

#26653 Fix default text setting on admin console not getting cleared
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26426 [MM-57147] Obfuscate ReplicaLagSettings in Support Packet
  server/public/model/config.go
  server/public/model/config_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#22394 [MM-47953] Outgoing webhook does not trigger when using multiple callback URLs
  server/channels/app/webhook.go
  server/channels/app/webhook_test.go
Labels: 4: Reviews Complete, release-note, Contributor

#25614 [MM-56008] Convert `./components/widgets/settings/bool_setting.tsx` to functional component
  webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
  webapp/channels/src/components/widgets/settings/bool_setting.test.tsx
  webapp/channels/src/components/widgets/settings/bool_setting.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26666 [MM-57519] Fill the {time} parameter with a blank string in places where it isn't used
  webapp/channels/src/components/custom_status/expiry_time.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26713 Automated cherry pick of #26660
  server/channels/app/post.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26198 [MM-56695] Consolidate desktop and mobile Notifications to one and a new desktop notification sound settings
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/message_auto_response_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/at_icon_still_shows_mentions_list_with_deactivated_triggers_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/at_mentions_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/channel_links_show_as_links_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/deselect_username_mention_trigger_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/desktop_notifications_1_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/desktop_notifications_2_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/desktop_notifications_3_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/helper.js
  e2e-tests/cypress/tests/integration/channels/notifications/notification_preferences_do_not_save_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/reply_notifications_spec.js
  e2e-tests/cypress/tests/integration/channels/notifications/reset_notification_when_settings_canceled_spec.js
  e2e-tests/cypress/tests/integration/channels/signin_authentication/desktop_session_expire_spec.js
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/components/__snapshots__/setting_item_max.test.tsx.snap
  webapp/channels/src/components/setting_item_max.tsx
  webapp/channels/src/components/user_settings/display/manage_languages/manage_languages.tsx
  webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/index.test.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/index.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/__snapshots__/desktop_notification_settings.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.test.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.tsx
  webapp/channels/src/components/user_settings/notifications/desktop_notification_sounds_setting/index.tsx
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  webapp/channels/src/components/user_settings/notifications/manage_auto_responder/__snapshots__/manage_auto_responder.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/manage_auto_responder/manage_auto_responder.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.test.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/channels/src/components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.tsx.snap
  webapp/channels/src/components/user_settings/security/mfa_section/mfa_section.tsx
  webapp/channels/src/components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_forms.scss
  webapp/channels/src/sass/routes/_settings.scss
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#26701 Add login/logout signal to Desktop App API
  webapp/channels/package.json
  webapp/channels/src/actions/global_actions.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/utils/desktop_api.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#26736 Automated cherry pick of #26651
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26737 Automated cherry pick of #26651
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26738 Automated cherry pick of #26651
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26740 Automated cherry pick of #26651
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26744 Automated cherry pick of #26653
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26606 updated modifyTeamsCmdF to return error instead of nil when encounting error
  server/cmd/mmctl/commands/team.go
  server/cmd/mmctl/commands/team_e2e_test.go
  server/cmd/mmctl/commands/team_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#26457 Gh 24291 api meesage unclear when parameters are incorrect
  server/channels/api4/channel.go
  server/channels/api4/channel_category_test.go
  server/channels/api4/channel_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#26664 Simplify page size in mmctl
  server/cmd/mmctl/commands/bot.go
  server/cmd/mmctl/commands/channel.go
  server/cmd/mmctl/commands/completion.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/commands/extract.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/init.go
  server/cmd/mmctl/commands/logs.go
  server/cmd/mmctl/commands/oauth.go
  server/cmd/mmctl/commands/plugin_marketplace.go
  server/cmd/mmctl/commands/team.go
  server/cmd/mmctl/commands/team_test.go
  server/cmd/mmctl/commands/token.go
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/utils.go
Labels: 4: Reviews Complete, release-note-none

#26595 Fix MM-55314
  server/channels/api4/group.go
  server/channels/api4/group_test.go
Labels: 4: Reviews Complete, release-note-none

#26661 [MM-57517] Add exact user ID lookup to the search query for Users
  server/channels/store/sqlstore/user_store.go
  server/channels/store/storetest/user_store.go
Labels: 2: Dev Review, release-note

#26741 CLD-7473 Limit parallelism for full E2E tests
  .github/workflows/e2e-fulltests-ci.yml
Labels: 4: Reviews Complete, release-note-none

#26732 Updated e2e-tests README.md
  e2e-tests/README.md
Labels: 4: Reviews Complete, release-note, Contributor

#26747 Automated cherry pick of #26595
  server/channels/api4/group.go
  server/channels/api4/group_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26746 Automated cherry pick of #26595
  server/channels/api4/group.go
  server/channels/api4/group_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26758 Manual cherry pick of #26595
  server/channels/api4/group.go
  server/channels/api4/group_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26421 MM-57018: support reattaching plugins
  server/channels/api4/plugin_local.go
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_reattach.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/plugin_reattach.go
  server/public/plugin/client.go
  server/public/plugin/environment.go
  server/public/plugin/health_check_test.go
  server/public/plugin/plugintest/example_reattach_test.go
  server/public/plugin/supervisor.go
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26762 Update playbooks to v1.39.3
  server/Makefile
Labels: 4: Reviews Complete, release-note

#26764 Update playbooks to v1.39.3
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#26754 [MM-57286] Prepackage calls v0.26.2
  server/Makefile
Labels: 4: Reviews Complete, release-note

#26604 [MM-57067][MM-57006][MM-57328] Acknowledge websocket POSTED events that may result in a notification on the web client
  server/channels/app/notification.go
  server/channels/app/notification_test.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  server/channels/wsapi/system.go
  server/public/model/websocket_message.go
  webapp/channels/src/actions/new_post.test.ts
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/utils/desktop_api.ts
  webapp/channels/src/utils/notifications.ts
  webapp/platform/client/src/websocket.ts
Labels: 2: Dev Review, release-note-none

#26718 [MM-57709] Convert `./components/channel_select/channel_select.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_select/channel_select.tsx
  webapp/channels/src/components/integrations/__snapshots__/abstract_incoming_hook.test.tsx.snap
  webapp/channels/src/components/integrations/__snapshots__/abstract_outgoing_webhook.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, Contributor

#26708 [MM-57727] Convert SearchDateSuggestion to functional component
  webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26709 [MM-55497] Add tooltips with enlarged emojis when hovering over emojis within message content
  webapp/channels/src/components/post_emoji/post_emoji.test.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26641 MM-55280: When closing/dismissing the find channels modal via keyboard, set focus on originating button
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.test.tsx
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
  webapp/channels/src/components/sidebar/channel_navigator/channel_navigator.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26589 Fix MM-57090
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: 4: Reviews Complete, release-note-none

#26635 Fixing modal styles for some modals
  webapp/channels/src/components/add_users_to_group_modal/__snapshots__/add_users_to_group_modal.test.tsx.snap
  webapp/channels/src/components/add_users_to_group_modal/add_users_to_group_modal.tsx
  webapp/channels/src/components/admin_console/billing/delete_workspace/result_modal.scss
  webapp/channels/src/components/browse_channels/browse_channels.scss
  webapp/channels/src/components/product_notices_modal/product_notices_modal.scss
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
  webapp/channels/src/sass/components/_modal.scss
Labels: 4: Reviews Complete, CherryPick/Approved, AutomatedCherryPick, release-note-none

#26551 [MM-55323] Allow end users to fetch the group members list of groups which allow @-mentions
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/api4/user.go
  server/public/model/client4.go
  server/public/model/group_member.go
Labels: 4: Reviews Complete, Docs/Not Needed, CherryPick/Approved, QA/Review Done, release-note

#26781 Automated cherry pick of #26635
  webapp/channels/src/components/add_users_to_group_modal/__snapshots__/add_users_to_group_modal.test.tsx.snap
  webapp/channels/src/components/add_users_to_group_modal/add_users_to_group_modal.tsx
  webapp/channels/src/components/admin_console/billing/delete_workspace/result_modal.scss
  webapp/channels/src/components/browse_channels/browse_channels.scss
  webapp/channels/src/components/product_notices_modal/product_notices_modal.scss
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
  webapp/channels/src/sass/components/_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26782 Automated cherry pick of #26551
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/api4/user.go
  server/public/model/client4.go
  server/public/model/group_member.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26783 Automated cherry pick of #26551
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/api4/user.go
  server/public/model/client4.go
  server/public/model/group_member.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26776 Automated cherry pick of #26589
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26777 Automated cherry pick of #26589
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26652 [MM-55283] Add channel name to aria label for sidebar options
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26722 [MM-57721] Convert `./components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  webapp/channels/src/components/channel_header_dropdown/menu_items/leave_channel/leave_channel.test.tsx
  webapp/channels/src/components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26719 [MM-57724] Convert `./components/channel_header_dropdown/mobile_channel_header_dropdown.tsx` from Class Component to Function Component
  webapp/channels/src/components/channel_header_dropdown/mobile_channel_header_dropdown.tsx
  webapp/channels/src/components/channel_header_mobile/__snapshots__/channel_header_mobile.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26785 Support for additional audit config via env var
  server/channels/app/audit.go
  server/public/shared/mlog/mlog.go
Labels: release-note-none

#26614 MM-57292 - Adding root post divider component
  webapp/channels/src/components/root_post_divider/root_post_divider.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#26794 Automated cherry pick of #26614
  webapp/channels/src/components/root_post_divider/root_post_divider.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26797 Automated cherry pick of #26310
  server/Makefile
  server/build/release.mk
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26796 Automated cherry pick of #26310
  server/Makefile
  server/build/release.mk
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26765 Update playbooks to v1.39.3
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#26766 Update playbooks to v1.39.3
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#26768 Update playbooks to v1.39.3
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#26798 [CLD-7375] Fix z index in stat trial form modal
  webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.scss
Labels: 4: Reviews Complete, release-note-none

#26753 MM-57786 Fix Shared Channels plugin api
  server/channels/app/remote_cluster.go
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/storetest/remote_cluster_store.go
  server/platform/services/remotecluster/mocks_test.go
  server/platform/services/remotecluster/ping.go
  server/platform/services/remotecluster/service.go
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/service_api.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/remote_cluster.go
  server/public/model/remote_cluster_test.go
  server/public/model/shared_channel.go
Labels: release-note-none

#26424 MM-56402: Introduce a pluginID to track RPC DB connections
  server/channels/api4/channel_bookmark_test.go
  server/channels/app/plugin_db_driver.go
  server/channels/app/plugin_db_driver_test.go
  server/public/plugin/driver.go
  server/public/plugin/environment.go
  server/public/plugin/supervisor.go
Labels: 4: Reviews Complete, release-note

#26763 [MM-57010] Include client type in websocket connections metric
  server/channels/api4/websocket.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/web/handlers.go
  server/channels/web/handlers_test.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
Labels: 4: Reviews Complete, Docs/Needed, release-note

#26671 Add post priority to incoming and outgoing webhook
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/webhook.go
  server/channels/app/webhook_test.go
  server/public/model/incoming_webhook.go
  server/public/model/outgoing_webhook.go
Labels: 4: Reviews Complete, QA/Review Done, release-note

#26699 MM-54569 : Update maximum password length on UI to 72 characters
  e2e-tests/cypress/tests/integration/channels/account_settings/security/password_spec.ts
  e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/signin_authentication/signup_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management/users_spec.js
  e2e-tests/playwright/support/ui/pages/signup.ts
  server/channels/app/users/password.go
  server/channels/app/users/password_test.go
  server/i18n/en.json
  server/public/model/config.go
  tools/mmgotool/commands/i18n.go
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/utils.test.tsx
Labels: 4: Reviews Complete, release-note

#26812 fix: Remove version dependency from Dockerfile
  server/build/Dockerfile
Labels: kind/bug, release-note-none

#26749 MM-57186 Update System Console Header Font
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note-none

#26778 Automated cherry pick of #26589
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26779 Automated cherry pick of #26589
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#26799 [MM-57066][MM-57329] Added metrics for all notification stopping points, consolidated categories between metrics and logging
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/expirynotify.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/reaction.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  server/channels/wsapi/system.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/feature_flags.go
  server/public/model/notification.go
  webapp/channels/package.json
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/utils/desktop_api.ts
  webapp/channels/src/utils/notifications.ts
  webapp/package-lock.json
  webapp/platform/client/src/websocket.ts
  webapp/platform/types/src/posts.ts
Labels: 4: Reviews Complete, release-note-none

#26631 Fix calling wrong method in README for ws
  webapp/platform/client/README.md
Labels: 4: Reviews Complete, release-note, Contributor

#26819 Import_process: Pass the right variable for error
  server/channels/jobs/import_process/worker.go
Labels: 4: Reviews Complete, release-note-none

#25823 [MM-54730] Don't use old hardcoded rule for validating imported posts
  api/v4/source/posts.yaml
  server/channels/api4/config_local.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/commands/importer/validate.go
  server/cmd/mmctl/mocks/client_mock.go
  server/tests/import_test.zip
Labels: 4: Reviews Complete, QA/Review Done, AutoMerge, release-note

#26629 [MM-57500] Streaming support for importing file attachments
  server/channels/app/file.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/import_test.go
  server/channels/app/post.go
  server/cmd/mmctl/commands/import_e2e_test.go
  server/i18n/en.json
  server/tests/import_test.zip
  server/tests/test_img_diff_A.png
  server/tests/test_img_diff_B.png
Labels: 4: Reviews Complete, release-note

#26792 fix: Migrate notifications to reusable actions
  .github/workflows/server-test-template.yml
Labels: kind/bug, release-note-none

#26801 Cypress/E2E: Upgrade cypress to 13.7.3 and its dependencies
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
Labels: 4: Reviews Complete, release-note-none

#26630 [MM-57391]: improved error message moving channels
  server/channels/api4/channel_test.go
  server/channels/app/channel.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/storetest/channel_store.go
Labels: 2: Dev Review, Lifecycle/1:stale, kind/feature, release-note-none, Contributor

#26771 [MM-57826] Make sure the original errors are wrapped when AppErrors are returned
  server/channels/api4/channel.go
  server/channels/api4/channel_category.go
  server/channels/api4/channel_local.go
  server/channels/api4/cloud.go
  server/channels/api4/config.go
  server/channels/api4/config_local.go
  server/channels/api4/data_retention.go
  server/channels/api4/emoji.go
  server/channels/api4/hosted_customer.go
  server/channels/api4/image.go
  server/channels/api4/ip_filtering.go
  server/channels/api4/ldap.go
  server/channels/api4/license.go
  server/channels/api4/license_local.go
  server/channels/api4/outgoing_oauth_connection.go
  server/channels/api4/plugin.go
  server/channels/api4/plugin_local.go
  server/channels/api4/remote_cluster.go
  server/channels/api4/saml.go
  server/channels/api4/system.go
  server/channels/api4/team.go
  server/channels/api4/user.go
  server/channels/api4/websocket.go
  server/channels/app/cloud.go
  server/channels/app/desktop_login.go
  server/channels/app/draft.go
  server/channels/app/file.go
  server/channels/app/file_helper.go
  server/channels/app/group.go
  server/channels/app/login.go
  server/channels/app/notify_admin.go
  server/channels/app/post.go
  server/channels/app/status.go
Labels: 4: Reviews Complete, release-note-none

#26716 [MM-57708] Convert `./components/copy_url_context_menu/copy_url_context_menu.tsx` from Class Component to Function Component
  webapp/channels/src/components/copy_url_context_menu/copy_url_context_menu.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26816 Make sure the RHS does not get focused when coming back from suppressed
  webapp/channels/src/actions/views/rhs.ts
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.tsx
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_comment/index.ts
  webapp/channels/src/components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  webapp/channels/src/components/rhs_thread/rhs_thread.tsx
  webapp/channels/src/components/sidebar_right/index.ts
  webapp/channels/src/components/sidebar_right/sidebar_right.test.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/create_comment.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/index.ts
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/reducers/views/rhs.test.js
  webapp/channels/src/reducers/views/rhs.ts
  webapp/channels/src/selectors/rhs.ts
  webapp/channels/src/selectors/views/rhs.ts
  webapp/channels/src/types/store/rhs.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26789 [MM-52675] Use message_source in copy text action (#26674)
  webapp/channels/src/components/dot_menu/dot_menu.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#26720 [MM-57723] Convert `./components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26834 Translations update from Mattermost Weblate
  server/i18n/be.json
  server/i18n/bg.json
  server/i18n/cs.json
  server/i18n/de.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/fa.json
  server/i18n/fi.json
  server/i18n/fr.json
  server/i18n/hi.json
  server/i18n/hr.json
  server/i18n/hu.json
  server/i18n/id.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/ko.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/ro.json
  server/i18n/ru.json
  server/i18n/sl.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/vi.json
  server/i18n/zh-CN.json
  server/i18n/zh-TW.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/zh-CN.json
Labels: release-note-none

#26821 Fix flaky ping test for remote clusters service
  server/platform/services/remotecluster/ping_test.go
Labels: 4: Reviews Complete, release-note-none

#26750 Remove access to global state from i18n/i18n
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/manage_languages/index.ts
  webapp/channels/src/components/user_settings/display/manage_languages/manage_languages.test.tsx
  webapp/channels/src/components/user_settings/display/manage_languages/manage_languages.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/i18n/i18n.jsx
  webapp/channels/src/selectors/i18n.ts
Labels: 4: Reviews Complete, QA/Deferred, release-note-none

#26289 MM-37809 Theming tweaks
  webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/__snapshots__/custom_theme_chooser.test.tsx.snap
  webapp/channels/src/packages/mattermost-redux/src/constants/preferences.ts
  webapp/channels/src/plugins/pluggable/__snapshots__/pluggable.test.tsx.snap
  webapp/channels/src/plugins/test/__snapshots__/post_type.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#26752 Remove access to global state from some files
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/app_bar/__snapshots__/app_bar.test.tsx.snap
  webapp/channels/src/components/app_bar/app_bar.test.tsx
  webapp/channels/src/components/copy_button.tsx
  webapp/channels/src/components/create_team/components/team_url/team_url.test.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
  webapp/channels/src/components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap
  webapp/channels/src/components/file_attachment/file_attachment.test.tsx
  webapp/channels/src/components/file_attachment/filename_overlay.tsx
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  webapp/channels/src/components/invitation_modal/index.tsx
  webapp/channels/src/components/invitation_modal/invitation_modal.test.tsx
  webapp/channels/src/components/invitation_modal/invitation_modal.tsx
  webapp/channels/src/components/invitation_modal/invite_view.test.tsx
  webapp/channels/src/components/invitation_modal/invite_view.tsx
  webapp/channels/src/components/new_channel_modal/new_channel_modal.test.tsx
  webapp/channels/src/components/overlay_trigger.test.tsx
  webapp/channels/src/components/overlay_trigger.tsx
  webapp/channels/src/components/post_emoji/post_emoji.test.tsx
  webapp/channels/src/components/post_profile_picture/post_profile_picture.test.tsx
  webapp/channels/src/components/quick_input/__snapshots__/quick_input.test.tsx.snap
  webapp/channels/src/components/quick_input/quick_input.test.tsx
  webapp/channels/src/components/quick_input/quick_input.tsx
  webapp/channels/src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
  webapp/channels/src/components/team_sidebar/components/team_button.test.tsx
  webapp/channels/src/components/team_sidebar/components/team_button.tsx
  webapp/channels/src/components/toast/toast.test.tsx
  webapp/channels/src/plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  webapp/channels/src/plugins/channel_header_plug/channel_header_plug.test.tsx
  webapp/channels/src/utils/utils.tsx
  webapp/package-lock.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26833 Playwright/E2E: Upgrade to playwright@1.43 and its dependencies
  e2e-tests/.ci/server.generate.sh
  e2e-tests/.ci/server.run_playwright.sh
  e2e-tests/playwright/README.md
  e2e-tests/playwright/global_setup.ts
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/support/ui/components/channels/post_dot_menu.ts
  e2e-tests/playwright/support/ui/components/channels/settings/notification_settings.ts
  e2e-tests/playwright/support/visual/percy.ts
  e2e-tests/playwright/test.config.ts
  e2e-tests/playwright/tests/accessibility/channels/intro_channel.spec.ts
  e2e-tests/playwright/tests/functional/channels/settings/notifications/highlight_without_notification.spec.ts
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e-tests/playwright/types.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none

#26811 MM-57885: Do not mark channel as read on tab unload
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/logged_in/logged_in.test.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
Labels: 4: Reviews Complete, release-note

#26802 Fixed racy TestPanicLog test
  server/channels/app/server_test.go
Labels: release-note-none

#26725 [MM-57713] Convert `./components/sidebar_right_menu/sidebar_right_menu.tsx` from Class Component to Function Component
  webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
  webapp/channels/src/components/sidebar_right_menu/constant.ts
  webapp/channels/src/components/sidebar_right_menu/index.ts
  webapp/channels/src/components/sidebar_right_menu/sidebar_right_menu.tsx
Labels: 2: Dev Review, release-note-none, Contributor

#26729 [MM-57725] Convert `./components/common/chip/chip.tsx` from Class Component to Function Component
  webapp/channels/src/components/common/chip/chip.tsx
Labels: 2: Dev Review, release-note-none, Contributor

#26820 [MM-56266] Use ListTeamChannels for member count permission for public channels
  server/channels/api4/channel.go
  server/channels/app/app_iface.go
  server/channels/app/authorization.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26770 Improve the true/false selector style in the admin console
  webapp/channels/src/components/admin_console/__snapshots__/bleve_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/custom_enable_disable_guest_accounts_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/boolean_setting.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note

#26854 Notification metrics fixes
  server/channels/api4/system.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/notification.go
Labels: 4: Reviews Complete, release-note-none

#26712 Bump prepackage Jira plugin version to 4.1.1
  server/Makefile
Labels: 2: Dev Review, release-note

#26721 [MM-57722] Convert `./components/admin_console/team_channel_settings/group/group_list.tsx` from Class Component to Function Component
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.test.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#26358 [MM-56854] Add shell completion to mmctl user active|deactivate
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/user_test.go
  server/cmd/mmctl/mocks/client_mock.go
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#26835 Cleanup usage of global logger
  server/channels/api4/license.go
  server/channels/api4/oauth.go
  server/channels/api4/plugin.go
  server/channels/api4/post.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user.go
  server/channels/app/app_iface.go
  server/channels/app/command_autocomplete.go
  server/channels/app/email_test.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/notify_admin.go
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/onboarding.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/platform/session.go
  server/channels/app/plugin.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_key_value_store.go
  server/channels/app/plugin_test.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/app/reaction.go
  server/channels/app/remote_cluster.go
  server/channels/app/report.go
  server/channels/app/session.go
  server/channels/app/slashcommands/command_exportlink.go
  server/channels/app/slashcommands/command_invite_people.go
  server/channels/app/team.go
  server/channels/app/team_test.go
  server/channels/app/true_up.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/jobs/resend_invitation_email/worker.go
  server/channels/manualtesting/manual_testing.go
  server/channels/web/oauth.go
  server/channels/web/saml.go
  server/cmd/mattermost/commands/jobserver.go
  server/cmd/mmctl/commands/plugin_marketplace_e2e_test.go
Labels: 4: Reviews Complete, Docs/Not Needed, Tests/Not Needed, release-note-none

#26643 Fix MM 56723
  server/channels/app/notification_push.go
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#26817 Fix MM-57090 (#26589)
  server/channels/api4/user_test.go
  server/channels/app/ldap.go
  server/channels/app/oauth.go
  server/i18n/en.json
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26866 Fix MM 56723 (#26643)
  server/channels/app/notification_push.go
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26728 [MM-57718] Convert `./components/post_view/message_attachments/action_button/action_button.tsx` from Class Component to Function Component
  webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
  webapp/channels/src/components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, Contributor

#26832 [GH-26831] fix modal suggestion list position
  webapp/channels/src/components/suggestion/modal_suggestion_list.tsx
Labels: 4: Reviews Complete, QA/Review Done, release-note-none, Contributor

#26703 Clicking on "remember my preference" in landing page does not tick the associated checkbox
  webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx
  webapp/channels/src/sass/routes/_get-app.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#26856 [MM-57962] Remove outdated Copy Link menu in favour of native Electron dropdown
  webapp/channels/src/components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.tsx.snap
  webapp/channels/src/components/copy_url_context_menu/copy_url_context_menu.test.tsx
  webapp/channels/src/components/copy_url_context_menu/copy_url_context_menu.tsx
  webapp/channels/src/components/copy_url_context_menu/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/components/team_sidebar/components/team_button.tsx
  webapp/channels/src/components/widgets/team_icon/team_icon.scss
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#26639 [MM-57564] Removing notification blocking getUserProfiles call from notification function
  webapp/channels/src/actions/notification_actions.jsx
Labels: 4: Reviews Complete, release-note

#25496 [MM-51554] Make LDAP sync job more resilient against errors
  server/channels/app/app_iface.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/syncables.go
  server/channels/app/syncables_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note

#26760 [MM-57789] Update mockery version for LDAP mocks
  server/Makefile
Labels: 4: Reviews Complete, release-note-none

#26662 [MM-57745] Fetch threads of the current channel only when root post is missing from the store in new posted event
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/status_actions.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/channel_layout/channel_controller.tsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26883 Fix MM 56723 (#26643)
  server/channels/app/notification_push.go
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26881 Fix MM 56723 (#26643)
  server/channels/app/notification_push.go
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26882 Fix MM 56723 (#26643)
  server/channels/app/notification_push.go
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26885 Fix MM 56723 (#26643)
  server/channels/app/notification_push.go
  server/go.mod
  server/go.sum
  server/public/model/push_notification.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#26826 [MM-57121] Remove remote_id if necessary when merging user profile
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Labels: 2: Dev Review, QA/Deferred, release-note-none

#26859 [MM-57966]Document the 200 maximum page size cap for the per_page parameter in a central location in the documentation
  api/v4/source/bots.yaml
  api/v4/source/channels.yaml
  api/v4/source/dataretention.yaml
  api/v4/source/introduction.yaml
  api/v4/source/ldap.yaml
  api/v4/source/users.yaml
Labels: kind/documentation, release-note-none, Contributor

#26890 Cherry-pick of #26799 and #26854 to `release-9.8`
  server/channels/api4/system.go
  server/channels/app/app_iface.go
  server/channels/app/expirynotify.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/reaction.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  server/channels/wsapi/system.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/public/model/feature_flags.go
  server/public/model/notification.go
  webapp/channels/package.json
  webapp/channels/src/actions/new_post.ts
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/utils/desktop_api.ts
  webapp/channels/src/utils/notifications.ts
  webapp/package-lock.json
  webapp/platform/client/src/websocket.ts
  webapp/platform/types/src/posts.ts
Labels: release-note-none

#26891 Automated cherry pick of #26826
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#26889 More notification metrics fixes
  server/channels/api4/websocket.go
  server/channels/app/notification.go
  server/channels/app/platform/web_conn.go
  server/channels/app/web_broadcast_hooks.go
  server/channels/app/web_broadcast_hooks_test.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  webapp/channels/src/plugins/pluggable/__snapshots__/pluggable.test.tsx.snap
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#26848 Migrate tests for Login to Testing Library and convert showNotification to a thunk
  webapp/channels/src/actions/notification_actions.jsx
  webapp/channels/src/components/login/__snapshots__/login.test.tsx.snap
  webapp/channels/src/components/login/login.test.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/utils/notifications.test.ts
  webapp/channels/src/utils/notifications.ts
Labels: 4: Reviews Complete, release-note-none

#26670 [MM-57744] Improve status received reducers
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/users.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#26383 MM-56324 Channel Header UI Update
  webapp/channels/src/components/app_bar/app_bar.scss
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/channel_header/channel_header_title.tsx
  webapp/channels/src/components/channel_header/channel_header_title_favorite.tsx
  webapp/channels/src/components/drafts/drafts.scss
  webapp/channels/src/components/search_results/search_results.tsx
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.tsx
  webapp/channels/src/components/threading/global_threads/global_threads.scss
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
  webapp/channels/src/components/widgets/header/header.scss
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_buttons.scss
  webapp/channels/src/sass/components/_channel-header__icon.scss
  webapp/channels/src/sass/components/_popover.scss
  webapp/channels/src/sass/layout/_headers.scss
  webapp/channels/src/sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA/Review Done, release-note

#26805 [MM-57851] Add WebP to MediaFormats #26628
  server/channels/app/imaging/decode.go
  server/platform/shared/web/files.go
Labels: 4: Reviews Complete, release-note, Contributor

#26895 Avoids returning an error if sharing a direct channel fails after its creation
  server/channels/app/channel.go
  server/i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, release-note-none
