Repository mattermost/mattermost, pull requests merged in 2025-07, with the labels that each got.

#32164 [MM-64630] Fix an issue where multiple channels can't be removed from policies
  server/channels/app/access_control.go
  server/channels/app/access_control_test.go
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none

#32802 Automated cherry pick of #32164
  server/channels/app/access_control.go
  server/channels/app/access_control_test.go
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32933 Automated cherry pick of #32118
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32936 Automated cherry pick of #32118
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33010 Automated cherry pick of #31226
  server/channels/app/notification.go
  webapp/channels/src/components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.tsx.snap
  webapp/channels/src/components/post_view/post_add_channel_member/index.ts
  webapp/channels/src/components/post_view/post_add_channel_member/post_add_channel_member.test.tsx
  webapp/channels/src/components/post_view/post_add_channel_member/post_add_channel_member.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32167 Channel Store: No SELECT *
  server/channels/app/user_test.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/storetest/channel_store.go
Labels: 4: Reviews Complete, release-note-none

#33038 remove spurious user limits log
  server/channels/app/user.go
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#31656 MM-61595 Use dedicated popover component for post actions menu when empty
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  webapp/channels/src/components/actions_menu/__snapshots__/actions_menu_empty.test.tsx.snap
  webapp/channels/src/components/actions_menu/actions_menu.scss
  webapp/channels/src/components/actions_menu/actions_menu.tsx
  webapp/channels/src/components/actions_menu/actions_menu_button.tsx
  webapp/channels/src/components/actions_menu/actions_menu_empty.test.tsx
  webapp/channels/src/components/actions_menu/actions_menu_empty_popover.tsx
  webapp/channels/src/components/actions_menu/actions_menu_icon.tsx
  webapp/channels/src/components/actions_menu/actions_menu_mobile.test.tsx
  webapp/channels/src/components/actions_menu/index.test.tsx
  webapp/channels/src/components/actions_menu/popover.tsx
  webapp/channels/src/tests/setup_jest.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#32494 Fix(cypress): Fix e2e failing on master
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/search/cleared_search_term_spec.js
Labels: release-note-none, E2E/Overridden

#33071 Automated cherry pick of #33011
  webapp/channels/src/components/admin_console/admin_definition.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32934 Automated cherry pick of #32118
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#32080 MM-62744 Change how custom URLs are autolinked to fix remote user at-mentions
  webapp/channels/package.json
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/markdown/index.ts
  webapp/channels/src/components/markdown/markdown.tsx
  webapp/channels/src/components/post_view/embedded_bindings/button_binding/button_binding.tsx
  webapp/channels/src/components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap
  webapp/channels/src/components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
  webapp/channels/src/components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/utils/__snapshots__/message_html_to_component.test.tsx.snap
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/markdown/index.ts
  webapp/channels/src/utils/markdown/renderer.tsx
  webapp/channels/src/utils/message_html_to_component.test.tsx
  webapp/channels/src/utils/post_utils.test.tsx
  webapp/channels/src/utils/text_formatting.tsx
  webapp/channels/src/utils/text_formatting_at_mentions.test.ts
  webapp/channels/src/utils/text_formatting_links.test.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, QA - Deferred, release-note

#33273 Update Agents plugin to v1.2.4
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, E2E/Overridden

#33297 Automated cherry pick of #33273
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33289 [MM-64748] Prepackage Calls v1.9.2 to 10.5
  server/Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#33068 Skip code coverage generation on cherry-pick PRs
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  .github/workflows/webapp-ci-template.yml
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#32575 [MM-64663] Fix potential panic in `mmctl ldap job show` command
  server/cmd/mmctl/commands/ldap.go
  server/cmd/mmctl/commands/ldap_e2e_test.go
  server/cmd/mmctl/docs/mmctl_ldap_idmigrate.rst
  server/cmd/mmctl/docs/mmctl_ldap_job_list.rst
  server/cmd/mmctl/docs/mmctl_ldap_job_show.rst
  server/cmd/mmctl/docs/mmctl_ldap_sync.rst
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#33044 [MM-64609] Fix bad link to ABAC Policy Edit page from Channel Management page
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_access_control_policy.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none

#32100 Added patch channel API doc for channel banner
  api/v4/source/channels.yaml
  api/v4/source/definitions.yaml
Labels: release-note, E2E/Overridden

#33354 Automated cherry pick of #33351
  server/i18n/en.json
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33355 Automated cherry pick of #33351
  server/i18n/en.json
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33358 Automated cherry pick of #33351
  server/i18n/en.json
  server/platform/services/sharedchannel/attachment.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32573 MM-64417 Change permissions table to use a grid for animation
  webapp/channels/src/components/widgets/admin_console/admin_panel.scss
  webapp/channels/src/components/widgets/admin_console/admin_panel_togglable.test.tsx
  webapp/channels/src/components/widgets/admin_console/admin_panel_togglable.tsx
  webapp/channels/src/sass/components/_permissions.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#33367 Automated cherry pick of #33287
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33366 Automated cherry pick of #33287
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33365 Automated cherry pick of #33287
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33372 Automated cherry pick of #33370
  server/channels/api4/upload.go
  server/channels/api4/upload_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33371 Automated cherry pick of #33370
  server/channels/api4/upload.go
  server/channels/api4/upload_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#32120 MM-64681 Fix in: filter in mobile search box
  e2e-tests/cypress/tests/integration/channels/search/mobile_search_spec.js
  webapp/channels/src/components/search/index.tsx
  webapp/channels/src/components/suggestion/search_suggestion_list.tsx
Labels: 4: Reviews Complete, release-note

#31288 MM-64483 YouTube Preview UI Update
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/youtube_video_spec.js
  webapp/channels/src/components/youtube_video/__snapshots__/youtube_video.test.tsx.snap
  webapp/channels/src/components/youtube_video/youtube_video.test.tsx
  webapp/channels/src/components/youtube_video/youtube_video.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_videos.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note

#31411 Content flagging systems console settings
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/i18n/en.json
  server/public/model/config.go
  server/public/model/content_flagging_settings.go
  server/public/model/content_flagging_settings_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/boolean_setting.tsx
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/additional_settings.scss
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/additional_settings.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/additional_settings.tsx
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/reason_option.scss
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/reason_option.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/additional_settings/reason_option.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_flagging_section_base.scss
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/content_reviewers.scss
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/content_reviewers.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/content_reviewers.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_option.scss
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_option.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_option.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_reviewers_section/team_reviewers_section.scss
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_reviewers_section/team_reviewers_section.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/content_reviewers/team_reviewers_section/team_reviewers_section.tsx
  webapp/channels/src/components/admin_console/content_flagging/notificatin_settings/notification_settings.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/notificatin_settings/notification_settings.tsx
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/__snapshots__/user_profile_pill.test.tsx.snap
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_multiselect.scss
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_multiselector.tsx
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_profile_option.scss
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_profile_option.tsx
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_profile_pill.scss
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_profile_pill.test.tsx
  webapp/channels/src/components/admin_console/content_flagging/user_multiselector/user_profile_pill.tsx
  webapp/channels/src/components/admin_console/data_grid/data_grid.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/server_logs/__snapshots__/logs.test.tsx.snap
  webapp/channels/src/components/admin_console/system_users/system_users_filters_popover/system_users_filter_team/index.tsx
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
  webapp/channels/src/components/widgets/team_icon/team_icon.scss
  webapp/channels/src/components/widgets/team_icon/team_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/content_flagging.ts
Labels: 2: Dev Review, release-note-none

#32803 MM-64713 - channel invite modal in abac channel should keep filtered list of users
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/components/channel_invite_modal/index.ts
Labels: Setup Cloud Test Server, release-note-none

#33392 Automated cherry pick of #33370
  server/channels/api4/upload.go
  server/channels/api4/upload_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33393 Automated cherry pick of #32803
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/components/channel_invite_modal/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33349 MM-63652: Transition gossip encryption functionality to GA
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/cluster_spec.js
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/public/model/config_test.go
  server/public/model/utils_test.go
  webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/cluster_settings.test.tsx
  webapp/channels/src/components/admin_console/cluster_settings.tsx
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/en.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ka.json
  webapp/channels/src/i18n/kk.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, EETests, release-note

#33414 Automated cherry pick of #32101
  server/channels/app/platform/shared_channel_service_iface.go
  server/channels/app/shared_channel_service_iface.go
  server/channels/app/shared_channel_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33379 [CLD-9351] Remove preview modal button when in calls view
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#31400 Remove PDF library version constraint and update to latest
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/pdf_test.go
Labels: release-note-none

#33417 Manual CP 9.11 Fix MM64178 (#30957)
  server/channels/api4/channel_test.go
  server/channels/api4/team_test.go
  server/channels/app/channel.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#33416 Manual CP 10.5 Fix MM64178 (#30957)
  server/channels/api4/channel_test.go
  server/channels/api4/team_test.go
  server/channels/app/channel.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#33432 Automated cherry pick of #30794
  webapp/channels/src/actions/telemetry_actions.jsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/create_selector/index.js
  webapp/channels/src/packages/mattermost-redux/src/utils/post_list.test.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33434 Automated cherry pick of #30985
  api/v4/source/sharedchannels.yaml
  server/channels/api4/shared_channel.go
  server/channels/app/shared_channel_service_iface.go
  server/channels/app/user_test.go
  server/channels/web/context.go
  server/channels/web/params.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/public/model/shared_channel.go
  server/public/model/user.go
  webapp/channels/src/actions/user_actions.ts
  webapp/channels/src/components/more_direct_channels/index.ts
  webapp/channels/src/components/more_direct_channels/more_direct_channels.test.tsx
  webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/platform/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33380 Add support for dynamic fetching of preview modal content from S3 bucket
  api/v4/source/cloud.yaml
  api/v4/source/definitions.yaml
  server/channels/api4/cloud.go
  server/channels/app/cloud.go
  server/i18n/en.json
  server/public/model/cloud.go
  server/public/model/config.go
  webapp/channels/src/actions/cloud.tsx
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal_controller.test.tsx
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal_controller.tsx
  webapp/channels/src/components/cloud_preview_modal/preview_modal_content_data.ts
  webapp/channels/src/hooks/useGetCloudPreviewModalContent.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/cloud.ts
Labels: 4: Reviews Complete, release-note-none

#30019 MM-62746: drop manual plugin deployment support
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA - Review Not Required, release-note, E2E/Overridden

#33451 [CLD-9535] [CLD-9352] Adjust useOpenSalesLink bases its query parameters on useExternalLink
  webapp/channels/src/components/common/hooks/useOpenSalesLink.ts
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#33452 Automated cherry pick of #33376
  server/channels/api4/config_local.go
  server/channels/api4/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33447 Upgrading board prepackage version to v9.1.5
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, AutoMerge, release-note-none

#33460 Automated cherry pick of #33447
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33461 Automated cherry pick of #33447
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33468 Automated cherry pick of #33376
  server/channels/api4/config_local.go
  server/channels/api4/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33462 Automated cherry pick of #31814
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/store/storetest/link_metadata_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33469 Automated cherry pick of #33376
  server/channels/api4/config_local.go
  server/channels/api4/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33467 Automated cherry pick of #33376
  server/channels/api4/config_local.go
  server/channels/api4/config_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33435 [MM-64844] Remove deprecated mmctl commands and flags
  server/cmd/mattermost/commands/version.go
  server/cmd/mmctl/commands/auth_utils.go
  server/cmd/mmctl/commands/channel.go
  server/cmd/mmctl/commands/channel_test.go
  server/cmd/mmctl/commands/command.go
  server/cmd/mmctl/commands/compliance_export_e2e_test.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/commands/permissions.go
  server/cmd/mmctl/commands/root.go
  server/cmd/mmctl/commands/team.go
  server/cmd/mmctl/commands/team_e2e_test.go
  server/cmd/mmctl/commands/team_test.go
  server/cmd/mmctl/commands/user.go
Labels: 4: Reviews Complete, release-note

#33399 [MM-64719] fix select type being ignored when it's null
  server/channels/store/sqlstore/attributes_store.go
  server/channels/store/storetest/attributes_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#33464 Automated cherry pick of #31814
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/store/storetest/link_metadata_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33465 Automated cherry pick of #31814
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/store/storetest/link_metadata_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33466 Automated cherry pick of #31814
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/store/storetest/link_metadata_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33491 Automated cherry pick of #33477
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33496 Upgrading board prepackged version to v9.1.5
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#33497 Upgrading board prepackged version to v9.1.5
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#33476 Updated minimum supported Edge and Chrome versions
  server/i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, AutoMerge, release-note, E2E/Overridden

#33495 Upgrading board prepackged version to v9.1.5
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#32142 MM-64526: Fix custom profile attributes API call for unauthenticated users
  webapp/channels/src/components/logged_in/index.test.ts
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/logged_in/logged_in.test.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/user_settings/general/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note

#33459 Edit post paste url fix
  webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
  webapp/channels/src/utils/paste.test.tsx
  webapp/channels/src/utils/paste.tsx
Labels: Setup Cloud Test Server, release-note

#33507 Increase pbkdf2 rounds to OWASP recommendation
  server/public/model/remote_cluster.go
Labels: release-note-none

#33378 Reporting config apis
  api/Makefile
  api/v4/source/content_flagging.yaml
  server/channels/api4/api.go
  server/channels/api4/content_flagging.go
  server/channels/api4/content_flagging_test.go
  server/channels/app/content_flagging.go
  server/channels/app/content_flagging_test.go
  server/config/client.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/content_flagging_settings.go
  server/public/model/content_flagging_settings_test.go
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/teams.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/content_flagging.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/teams.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/content_flagging.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/tests/constants/teams.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/teams.ts
Labels: release-note-none

#33443 [MM-64858] Generate Support Packet in memory instead of writing it to the file store first
  server/channels/api4/system.go
  server/channels/app/file.go
  server/channels/app/file_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#33450 Improve HTTP service IP and host validation error messages
  server/channels/app/post_metadata_test.go
  server/public/shared/httpservice/client.go
  server/public/shared/httpservice/client_test.go
  server/public/shared/httpservice/httpservice.go
Labels: 4: Reviews Complete, release-note-none

#33508 MM-64880 Revert change to border colour in list modals and remove a few things from applyTheme
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#33526 Automated cherry pick of #32522
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/public/model/config.go
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/attribute_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/index.ts
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.test.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/access_control.ts
  webapp/platform/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33523 Fix PostgreSQL SSL connection issue with sslmode=require in distroless images
  server/build/Dockerfile
  server/build/passwd
Labels: release-note-none, E2E/Overridden

#33537 Automated cherry pick of #33523
  server/build/Dockerfile
  server/build/passwd
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33446 [MM-26609] Show user auth_data in System Console user details page
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, release-note

#33542 [MM-56322] Document GetUsers plugin API limitation
  server/public/plugin/api.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#33274 MM-64628: [CPA+LDAP/SAML] CPA Fails LDAP Sync When Attribute Exceeds Character Limit
  server/i18n/en.json
Labels: 2: Dev Review, release-note-none

#31195 Adding the CPA LDAP/SAML Modal
  webapp/channels/src/components/admin_console/system_properties/attribute_modal.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.tsx
  webapp/channels/src/components/quick_input/quick_input.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/platform/components/src/generic_modal/generic_modal.scss
Labels: 3: QA Review, release-note-none

#31181 [MM-63593] Add mmctl user edit command
  server/channels/api4/user_local.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/user_e2e_test.go
  server/cmd/mmctl/commands/user_test.go
  server/cmd/mmctl/docs/mmctl_user.rst
  server/cmd/mmctl/docs/mmctl_user_edit.rst
  server/cmd/mmctl/docs/mmctl_user_edit_authdata.rst
  server/cmd/mmctl/docs/mmctl_user_edit_email.rst
  server/cmd/mmctl/docs/mmctl_user_edit_username.rst
  server/cmd/mmctl/mocks/client_mock.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#33562 [MM-64894] Check for non-primitive fields using DeepEqual
  server/public/model/slack_attachment.go
  server/public/model/slack_attachment_test.go
Labels: 4: Reviews Complete, release-note

#33388 MM-64755: Fix redirect in oauth login
  server/channels/utils/utils.go
  server/channels/utils/utils_test.go
Labels: 4: Reviews Complete, release-note-none

#33564 MM-64781 Make all internal dependencies use exact versions and ensure they match (10.11)
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/platform/client/package.json
  webapp/platform/mattermost-redux/package.json
Labels: 2: Dev Review, release-note-none

#33511 Remove `data` wrapper when Marshalling a PluginPropertyOption
  server/public/model/property_field.go
  server/public/model/property_field_test.go
Labels: release-note-none, E2E/Overridden

#33566 MM-64781 Make all internal dependencies use exact versions and ensure they match (10.9)
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/platform/client/package.json
  webapp/platform/mattermost-redux/package.json
Labels: 4: Reviews Complete, release-note-none

#33574 [MM-64946] Prepackage playbooks v2.3.0
  server/Makefile
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#33578 Automated cherry pick of #33560
  server/platform/services/sharedchannel/membership.go
  server/platform/services/sharedchannel/util.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33579 Automated cherry pick of #33574
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33539 Fix npm vulnerabilities
  webapp/channels/webpack.config.js
  webapp/package-lock.json
Labels: release-note-none

#33552 MM-64250 - solve js eror while downloading images
  webapp/channels/src/components/post_view/post_attachment_container/post_attachment_container.test.tsx
  webapp/channels/src/components/post_view/post_attachment_container/post_attachment_container.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#33590 Automated cherry pick of #33563
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/components/new_search/search_box_input.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33596 Automated cherry pick of #33559
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33598 Automated cherry pick of #33559
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33599 Automated cherry pick of #33559
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
