Repository mattermost/mattermost, pull requests merged in 2025-02, with the labels that each got.

#30079 Fix Playwright tests
  e2e-tests/playwright/support/flag.ts
  e2e-tests/playwright/support/test_fixture.ts
  e2e-tests/playwright/support/ui/components/channels/scheduled_draft_modal.ts
  e2e-tests/playwright/support/ui/components/channels/search_popover.ts
  e2e-tests/playwright/support/ui/components/channels/sidebar_right.ts
  e2e-tests/playwright/tests/functional/channels/search/search_box_suggestions.spec.ts
  e2e-tests/playwright/tests/functional/channels/search/team_selector.spec.ts
Labels: 2: Dev Review, AutoMerge, QA - Review Not Required, release-note-none

#29692 [MM-61598]: Fix ARIA roles, states, and properties are valid in user profile image and @user buttons
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_keyboard_usability_spec.js
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_post_spec.js
  webapp/channels/src/components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.tsx.snap
  webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  webapp/channels/src/components/at_mention/__snapshots__/at_mention.test.tsx.snap
  webapp/channels/src/components/at_mention/at_mention.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  webapp/channels/src/components/profile_picture/index.tsx
  webapp/channels/src/sass/components/_mentions.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, Contributor

#29657 [MM-62191] Remove `disintegration/imaging` dependency
  server/channels/app/emoji.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, AutoMerge, release-note-none, E2E/Overridden

#29629 [MM-61577]: Ensure all interactive functionality is operable with the keyboard in emoji picker
  e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/emoji/sorted_emojis_spec.ts
  e2e-tests/cypress/tests/integration/channels/messaging/emoji_keyboard_entry_spec.js
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category_or_emoji_row.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category_row.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_current_results.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_item.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/post_emoji/post_emoji.tsx
  webapp/channels/src/sass/components/_emoticons.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#30088 Automated cherry pick of #30033
  .github/workflows/server-ci-report.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30062 [MM-61848] Add Telemetry to capture Cross-Team Search usage.
  webapp/channels/src/components/new_search/new_search.tsx
  webapp/channels/src/packages/mattermost-redux/src/constants/telemetry.ts
Labels: 2: Dev Review, QA - Review Not Required, release-note-none

#30087 Upgrade language from alpha
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/i18n/i18n.jsx
Labels: 4: Reviews Complete, Docs/Needed, Changelog/Done, AutoMerge, release-note

#30091 Translations update from Mattermost Weblate
  server/i18n/ar.json
  server/i18n/ar_SA.json
  server/i18n/de.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  webapp/channels/src/i18n/ar_SA.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/bn.json
  webapp/channels/src/i18n/ca.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/el.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/gl.json
  webapp/channels/src/i18n/he.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/id.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ka.json
  webapp/channels/src/i18n/kk.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/lv.json
  webapp/channels/src/i18n/mk.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/pt.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sl.json
  webapp/channels/src/i18n/sr.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/th.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, Do Not Merge/Mattermod

#29899 [AI assisted]: Improve system console statistics performance
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/reporting/site_statistics_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/reporting/team_statistics_spec.js
  e2e-tests/cypress/tests/plugins/db_request.js
  e2e-tests/cypress/tests/plugins/index.js
  e2e-tests/cypress/tests/support/db_commands.ts
  server/channels/api4/user_test.go
  server/channels/app/analytics.go
  server/channels/app/import_functions_test.go
  server/channels/app/import_test.go
  server/channels/app/server.go
  server/channels/app/support_packet_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000130_system_console_stats.down.sql
  server/channels/db/migrations/mysql/000130_system_console_stats.up.sql
  server/channels/db/migrations/postgres/000130_system_console_stats.down.sql
  server/channels/db/migrations/postgres/000130_system_console_stats.up.sql
  server/channels/jobs/refresh_materialized_views/scheduler.go
  server/channels/jobs/refresh_materialized_views/worker.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/file_info_store.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/file_info_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/FileInfoStore.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/job.go
  webapp/channels/src/components/analytics/format.tsx
  webapp/channels/src/components/analytics/statistic_count.test.tsx
  webapp/channels/src/components/analytics/statistic_count.tsx
  webapp/channels/src/components/analytics/system_analytics/analytics.scss
  webapp/channels/src/components/analytics/system_analytics/system_analytics.test.tsx
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/stats.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/admin.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/file_utils.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/types/src/admin.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note, E2E/Overridden

#29490 MM-62050: restrict channel bookmarks in archived channels
  e2e-tests/cypress/tests/integration/channels/channel/channel_bookmarks_spec.ts
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_bookmarks/utils.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none

#30020 Add platform/mattermost-redux package for publishing
  webapp/channels/package.json
  webapp/channels/src/components/gif_picker/components/gif_picker_items.tsx
  webapp/channels/src/components/gif_picker/selectors.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/scheudled_posts.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/create_selector/index.d.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
  webapp/channels/src/types/external/key-mirror.d.ts
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/rudder.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/client/package.json
  webapp/platform/client/src/client4.ts
  webapp/platform/mattermost-redux/README.md
  webapp/platform/mattermost-redux/package.json
  webapp/platform/mattermost-redux/tsconfig.json
  webapp/platform/types/package.json
  webapp/platform/types/src/posts.ts
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30015 Add `typescript-eslint-language-service`
  webapp/channels/tsconfig.json
  webapp/channels/webpack.config.js
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete, release-note-none

#30044 [MM-62775] Fix: Bulk export not completing
  server/channels/app/export.go
  server/channels/app/export_test.go
  server/cmd/mmctl/commands/importer/validate.go
  server/tests/import_test.zip
Labels: 4: Reviews Complete, release-note

#30092 [MM-62845] Fix: Compliance export download link fails from S3 when using a dedicated file store
  server/channels/api4/job.go
  server/channels/app/file.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, release-note-none

#30111 Automated cherry pick of #30092
  server/channels/api4/job.go
  server/channels/app/app_iface.go
  server/channels/app/file.go
  server/channels/app/opentracing/opentracing_layer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none, E2E/Overridden

#30113 Automated cherry pick of #29361
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/strings.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.scss
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30112 Automated cherry pick of #29361
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/strings.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.scss
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#29989 [MM-62552] Custom Profile Attributes: use json.RawMessage for the value.
  api/v4/source/custom_profile_attributes.yaml
  server/channels/api4/custom_profile_attributes.go
  server/channels/api4/custom_profile_attributes_test.go
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/storetest/property_value_store.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/property_field.go
  server/public/model/property_value.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30118 t.Skip flaky TestUpdateOAuthApp
  server/channels/api4/oauth_test.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#29988 [MM-60989] Add SelectBuilderCtx to simplify db code
  server/channels/store/sqlstore/compliance_store.go
  server/channels/store/sqlstore/outgoing_oauth_connection_store.go
  server/channels/store/sqlstore/sqlx_wrapper.go
  server/channels/store/sqlstore/sqlx_wrapper_test.go
  server/channels/store/sqlstore/user_store.go
Labels: 4: Reviews Complete, release-note-none

#30120 [MM-62897] Compliance export backwards compatibility
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#30121 Automated cherry pick of #30120
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none, E2E/Overridden

#30102 Removed Elasticsearch and Opensearch channel index schema check
  server/channels/app/elasticsearch.go
  server/channels/app/server.go
  server/channels/app/user.go
  server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
  server/enterprise/elasticsearch/opensearch/opensearch.go
  server/i18n/en.json
  server/platform/services/searchengine/bleveengine/bleve.go
  server/platform/services/searchengine/interface.go
  server/platform/services/searchengine/mocks/SearchEngineInterface.go
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30105 [MM-62876] Bulk export warnings
  server/channels/app/export.go
  server/channels/app/export_test.go
Labels: 4: Reviews Complete, release-note-none

#30125 MM-62901: Apply constLabels on all metrics
  server/enterprise/metrics/metrics.go
Labels: 2: Dev Review, release-note-none

#30005 MM-60211: Bump dependencies
  server/channels/app/platform/web_broadcast_hook_test.go
  server/go.mod
  server/go.sum
  server/platform/shared/filestore/s3_overrides.go
  server/public/go.mod
  server/public/go.sum
  server/public/model/websocket_message_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30060 MM-62142: remove SELECT * from status store (round 2)
  server/channels/store/sqlstore/sqlx_wrapper.go
  server/channels/store/sqlstore/status_store.go
  server/channels/store/sqlstore/status_store_test.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/status_store.go
  server/channels/store/storetest/utils.go
Labels: QA - Review Not Required, release-note-none

#29963 [MM-62669] Updates to cloud specific imagery in system console
  webapp/channels/src/components/admin_console/billing/billing_history.scss
  webapp/channels/src/components/admin_console/billing/billing_history.tsx
  webapp/channels/src/components/admin_console/billing/billing_summary/billing_summary.tsx
  webapp/channels/src/components/admin_console/billing/company_info_display.scss
  webapp/channels/src/components/admin_console/billing/company_info_display.tsx
  webapp/channels/src/components/common/svg_images_components/chat_illustration.tsx
  webapp/channels/src/components/common/svg_images_components/company_svg.tsx
  webapp/channels/src/components/common/svg_images_components/empty_billing_history_svg.tsx
  webapp/channels/src/components/pricing_modal/blank_card_image.svg.tsx
  webapp/channels/src/components/pricing_modal/card.tsx
  webapp/channels/src/components/threading/global_threads/global_threads.tsx
Labels: 4: Reviews Complete, release-note-none

#30142 Correctly detect branch to decide if notifying
  .github/workflows/server-ci-report.yml
Labels: release-note-none, E2E/Overridden

#29624 [MM-62004] update threads after a channel gets moved
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ThreadStore.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: release-note-none, E2E/Overridden

#30143 Automated cherry pick of #30142
  .github/workflows/server-ci-report.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none, E2E/Overridden

#30081 [MM-62153] Avoid SELECT * in preference_store.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/preference_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PreferenceStore.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 2: Dev Review, EETests, QA - Review Not Required, release-note-none, Contributor, E2E/Overridden

#29761 MM-61215: Clarify to use --bypass-upload flag
  server/cmd/mmctl/commands/import.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30080 [MM-62152] Avoid SELECT * in oauth_store.go
  server/channels/store/sqlstore/oauth_store.go
Labels: 2: Dev Review, EETests, release-note-none, Contributor, E2E/Overridden

#30141 fix: MM-62714
  .github/workflows/server-ci-report.yml
Labels: kind/bug, release-note-none, E2E/Overridden

#30137 MM-62926: Fix standard logger redirection issue
  server/channels/app/platform/log.go
Labels: 2: Dev Review, release-note-none

#30001 fix(MM-60645): missing emoji on mobile
  server/public/model/channel_bookmark.go
  server/public/model/channel_bookmark_test.go
Labels: kind/bug, release-note-none

#30150 Automated cherry pick of #29490
  e2e-tests/cypress/tests/integration/channels/channel/channel_bookmarks_spec.ts
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_bookmarks/utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30156 Upgrading board version to 9.1.1
  server/Makefile
Labels: 4: Reviews Complete, 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29435 Migrating other 2 files from javascript to typescript
  webapp/channels/package.json
  webapp/channels/src/actions/global_actions.test.ts
  webapp/channels/src/actions/user_actions.test.ts
  webapp/channels/src/components/suggestion/search_channel_with_permissions_provider.test.tsx
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/plugins/index.ts
  webapp/channels/src/plugins/interactive_dialog.ts
  webapp/channels/src/selectors/local_storage.ts
  webapp/channels/src/store/index.test.ts
  webapp/channels/src/store/index.ts
  webapp/channels/src/stores/local_storage_store.ts
  webapp/channels/src/tests/react_testing_utils.tsx
  webapp/channels/src/utils/utils.test.tsx
  webapp/channels/src/utils/utils.tsx
  webapp/package-lock.json
  webapp/platform/types/src/integrations.ts
Labels: 4: Reviews Complete, release-note-none

#30158 Automated cherry pick of #30152
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30082 [MM-62149] Avoid SELECT * in emoji_store.go
  server/channels/store/sqlstore/emoji_store.go
  server/channels/store/sqlstore/utils.go
Labels: 4: Reviews Complete, EETests, QA - Review Not Required, release-note-none, Contributor, E2E/Overridden

#30134 Update User Limits for unlicensed servers
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_test.go
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Labels: 1: PM Review, CherryPick/Approved, release-note-none

#30095 Bump katex to 0.16.21
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#29547 [MM-55278]: Fixed autofocus on submenu's first element
  e2e-tests/playwright/tests/accessibility/channels/intro_channel.spec.ts
  webapp/channels/src/components/dot_menu/post_reminder_submenu.tsx
  webapp/channels/src/components/menu/menu.scss
  webapp/channels/src/components/menu/menu.test.tsx
  webapp/channels/src/components/menu/menu_item.tsx
  webapp/channels/src/components/menu/sub_menu.tsx
  webapp/channels/src/components/user_account_menu/__snapshots__/user_account_name_menuitem.test.tsx.snap
  webapp/channels/src/components/user_account_menu/user_account_dnd_menuitem.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#30162 Automated cherry pick of #30134
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_test.go
  webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none, E2E/Overridden

#30172 MM-62862: CP: Bump dependencies (x/net/html)
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#30027 [MM-62762] Make config location in Support Packet human-readable
  server/public/utils/sql/sql_utils.go
  server/public/utils/sql/sql_utils_test.go
Labels: 4: Reviews Complete, release-note

#30155 Upgrading board version v9.1.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30153 Upgraded board version to v9.1.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30154 Upgrading board version to v9.1.1
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30013 [MM-61683]: Ensure radio button groups are properly formed
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
  webapp/channels/src/components/channel_notifications_modal/utils.tsx
  webapp/channels/src/components/widgets/modals/components/radio_setting_item.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#30116 MM-62891 Fixed incorrectly applied label in Team Settings modal
  webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx
  webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.test.tsx
Labels: 4: Reviews Complete, release-note-none

#30176 MM-62862: CP: Bump dependencies (x/net/html)
  server/go.mod
  server/go.sum
Labels: 2: Dev Review, release-note-none

#30175 MM-62862: CP: Bump dependencies (x/net/html)
  server/go.mod
  server/go.sum
Labels: 2: Dev Review, release-note-none

#30173 MM-62862: CP: Bump dependencies (x/net/html)
  server/go.mod
  server/go.sum
Labels: 2: Dev Review, release-note-none

#30197 Automated cherry pick of #30116
  webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx
  webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.test.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30174 MM-62862: CP: Bump dependencies (x/net/html)
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none

#30187 [MM-62951] - CP MM-62876 Bulk export warnings (#30105)
  server/channels/app/export.go
  server/channels/app/export_test.go
Labels: 4: Reviews Complete, release-note-none

#30188 Bump katex for release 10.4
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30192 Bump katex for release 9.11
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30189 Bump katex for release 10.3
  webapp/channels/package.json
  webapp/package-lock.json
Labels: release-note-none

#30191 Bump katex for release 10.2
  webapp/channels/package.json
  webapp/package-lock.json
Labels: release-note-none

#30186 [MM-62864] Bump katex to 0.16.21 (#30095)
  webapp/channels/package.json
  webapp/package-lock.json
Labels: release-note-none

#30202 Automated cherry pick of #30095
  webapp/channels/package.json
  webapp/package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30179 added window title for scheduled post tab and fixed draft alignment
  webapp/channels/src/components/drafts/drafts.scss
  webapp/channels/src/components/unreads_status_handler/index.ts
  webapp/channels/src/components/unreads_status_handler/unreads_status_handler.test.tsx
  webapp/channels/src/components/unreads_status_handler/unreads_status_handler.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30198 Updates the property field and value update methods to use a single query for multiple entities
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/storetest/property_value_store.go
Labels: release-note-none, E2E/Overridden

#30163 Adds websocket messages to Custom Profile Attributes
  server/channels/api4/custom_profile_attributes_test.go
  server/channels/app/custom_profile_attributes.go
  server/channels/app/properties/property_value.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/mocks/PropertyValueStore.go
  server/channels/store/storetest/property_value_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/websocket_message.go
Labels: 3: QA Review, release-note, E2E/Overridden

#30182 MM-62944 Fix fileupload settings not being clickable
  webapp/channels/src/components/admin_console/file_upload_setting.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#30119 [MM-62553]+[MM-62554] Property Architecture: cursor based pagination
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/channels/app/properties/property_field.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000131_create_index_pagination_on_property_values.down.sql
  server/channels/db/migrations/mysql/000131_create_index_pagination_on_property_values.up.sql
  server/channels/db/migrations/mysql/000132_create_index_pagination_on_property_fields.down.sql
  server/channels/db/migrations/mysql/000132_create_index_pagination_on_property_fields.up.sql
  server/channels/db/migrations/postgres/000131_create_index_pagination_on_property_values.down.sql
  server/channels/db/migrations/postgres/000131_create_index_pagination_on_property_values.up.sql
  server/channels/db/migrations/postgres/000132_create_index_pagination_on_property_fields.down.sql
  server/channels/db/migrations/postgres/000132_create_index_pagination_on_property_fields.up.sql
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/storetest/property_value_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/property_field.go
  server/public/model/property_field_test.go
  server/public/model/property_value.go
  server/public/model/property_value_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30127 [aider assisted] MM-61888: Add ClientSideUserIds field to MetricsSettings
  server/channels/api4/metrics_test.go
  server/channels/app/metrics.go
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
  server/i18n/en.json
  server/public/model/config.go
  server/public/model/incoming_webhook.go
  webapp/channels/src/components/admin_console/__snapshots__/client_side_userids_setting.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/client_side_userids_setting.test.tsx
  webapp/channels/src/components/admin_console/client_side_userids_setting.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#30205 Automated cherry pick of #30182
  webapp/channels/src/components/admin_console/file_upload_setting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30206 Automated cherry pick of #30182
  webapp/channels/src/components/admin_console/file_upload_setting.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30207 Fix build: Remove call for removed attribute Page
  server/channels/store/storetest/property_value_store.go
Labels: release-note-none, E2E/Overridden

#30190 MM-62933 Revert position of post menu to match earlier versions
  webapp/channels/src/sass/components/_post-menu.scss
  webapp/channels/src/sass/components/_search.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30210 Automated cherry pick of #30190
  webapp/channels/src/sass/components/_post-menu.scss
  webapp/channels/src/sass/components/_search.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30097 MM-62548: CPA Reordering - drag and drop
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/public/model/custom_profile_attributes.go
  server/public/model/property_field.go
  webapp/channels/src/components/admin_console/list_table/list_table.scss
  webapp/channels/src/components/admin_console/list_table/list_table.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.test.ts
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.ts
  webapp/platform/types/src/properties.ts
  webapp/platform/types/src/utilities.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30034 MM-61375: Update file handling for bookmarks
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/store/storetest/mocks/ChannelBookmarkStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30211 Fix master build
  server/public/model/property_field_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30178 MM-62960: Improve webConn remove performance from hubConnectionIndex
  server/channels/api4/post_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/public/model/config.go
Labels: 3: QA Review, CherryPick/Approved, release-note-none, E2E/Overridden

#30216 Automated cherry pick of #30178
  server/channels/api4/post_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30218 Automated cherry pick of #30034
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/store/storetest/mocks/ChannelBookmarkStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30215 Automated cherry pick of #30178
  server/channels/api4/post_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30220 [Cherry-pick] MM-62960: Improve webConn remove performance from hubConnectionIndex (#30178)
  server/channels/api4/post_test.go
  server/channels/app/platform/web_conn.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
  server/public/model/config.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#29835 MM-62383 Replace React Bootstrap with Floating UI in Emoji Picker
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/edit_message_spec.js
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/use_editor_emoji_picker.tsx
  webapp/channels/src/components/channel_bookmarks/create_modal_name_input.tsx
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/dot_menu/dot_menu.tsx
  webapp/channels/src/components/dot_menu/index.ts
  webapp/channels/src/components/edit_scheduled_post/edit_post.tsx
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_overlay/emoji_picker_overlay.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_overlay/index.ts
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/emoji_picker/use_emoji_picker.tsx
  webapp/channels/src/components/post/post_options.tsx
  webapp/channels/src/components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  webapp/channels/src/components/post_view/post_reaction/post_reaction.test.tsx
  webapp/channels/src/components/post_view/post_reaction/post_reaction.tsx
  webapp/channels/src/components/post_view/reaction/reaction.scss
  webapp/channels/src/components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
  webapp/channels/src/components/post_view/reaction_list/add_reaction_button.test.tsx
  webapp/channels/src/components/post_view/reaction_list/add_reaction_button.tsx
  webapp/channels/src/components/post_view/reaction_list/reaction_list.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/floating.ts
  webapp/channels/src/utils/position_utils.test.tsx
  webapp/channels/src/utils/position_utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30209 MM-63138 Fix some console warnings
  webapp/channels/src/components/new_search/search_box_input.tsx
  webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  webapp/channels/src/components/threading/common/button/button.tsx
  webapp/channels/src/components/threading/common/follow_button/__snapshots__/follow_button.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30219 [MM-62961]: Fixed pointer event of submenu
  webapp/channels/src/components/menu/menu.scss
  webapp/channels/src/components/menu/sub_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, Contributor

#30226 MM-62050: restrict channel bookmarks in archived channels (#29490)
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_bookmarks/utils.ts
Labels: AutoMerge, release-note-none

#30234 Automated cherry pick of #30160
  server/channels/app/authentication.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_requests.go
  server/channels/web/context.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30195 [MM-54861] Command + K shortcut to hyperlink text doesn't work when editing a post
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/utils.test.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none

#30228 MM-62050: restrict channel bookmarks in archived channels (#29490)
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_bookmarks/utils.ts
Labels: AutoMerge, release-note-none

#30100 Adding a label wip languages
  webapp/channels/src/i18n/i18n.jsx
  webapp/channels/src/i18n/i18n.test.jsx
Labels: 4: Reviews Complete, Lifecycle/1:stale, release-note-none, Contributor, E2E/Overridden, E2E/Run

#30224 MM-62960: Support both webhub iteration scopes properly
  server/channels/api4/post_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, release-note-none, E2E/Overridden

#30238 [Cherry-pick] [AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_requests.go
  server/channels/web/context.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#30130 [Cherry-pick] [MM-62191] Remove `disintegration/imaging` dependency (#29657)
  server/channels/app/emoji.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#30245 server/Makefile: pin dbcmp
  server/Makefile
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30248 Automated cherry pick of #30245
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30229 MM-62050: restrict channel bookmarks in archived channels (#29490)
  server/channels/api4/channel_bookmark.go
  server/channels/api4/channel_bookmark_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_bookmarks/utils.ts
Labels: release-note-none

#30246 [Cherry-pick][AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_requests.go
  server/channels/web/context.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30247 [Cherry-pick][AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_requests.go
  server/channels/web/context.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30252 Automated cherry pick of #30224
  server/channels/api4/post_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30251 Automated cherry pick of #30224
  server/channels/api4/post_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30250 Automated cherry pick of #30224
  server/channels/api4/post_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30131 [Cherry-pick] [MM-62191] Remove `disintegration/imaging` dependency (#29657)
  server/channels/app/emoji.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#30133 [Cherry-pick] [MM-62191] Remove `disintegration/imaging` dependency (#29657)
  server/channels/app/emoji.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 2: Dev Review, release-note-none

#30030 Updated minimum supported Edge and Chrome versions
  server/i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note, E2E/Overridden

#30249 Automated cherry pick of #30224
  server/channels/api4/post_test.go
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30132 [Cherry-pick] [MM-62191] Remove `disintegration/imaging` dependency (#29657)
  server/channels/app/emoji.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30244 [Cherry-pick][AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api_test.go
  server/channels/app/plugin_requests.go
  server/channels/web/context.go
  server/i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#29996 Update Playbooks plugin to v2.1.1
  server/Makefile
Labels: 2: Dev Review, release-note

#30259 Automated cherry pick of #29996
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30256 Automated cherry pick of #29996
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30257 Automated cherry pick of #29996
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30098 Update Copilot plugin to v1.1.1
  server/Makefile
Labels: 2: Dev Review, release-note

#30181 [MM-55090] Threads created by users should not be auto-followed on reply by the creator when they've left the channel
  server/channels/app/notification.go
  server/channels/app/notification_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#30166 [MM-60555] Use channel memberships to calculate total unread status instead of team memberships
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#30167 [MM-62945] Load new channels for users added even if they're on a different team
  webapp/channels/src/actions/websocket_actions.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#30168 MM-61634 - adjust rhs a11y structure
  webapp/channels/src/components/channel_info_rhs/header.tsx
  webapp/channels/src/components/channel_members_rhs/header.tsx
  webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
  webapp/channels/src/components/resizable_sidebar/resizable_rhs/index.tsx
  webapp/channels/src/components/rhs_card_header/rhs_card_header.tsx
  webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx
  webapp/channels/src/components/search_results_header/search_results_header.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#30264 v9.11 cherry-pick of MM-62191
  server/channels/app/emoji.go
  server/channels/app/file_test.go
  server/channels/app/imaging/orientation.go
  server/channels/app/imaging/preview.go
  server/channels/app/imaging/preview_test.go
  server/channels/app/imaging/utils.go
  server/channels/app/imaging/utils_test.go
  server/go.mod
  server/go.sum
  server/tests/crop_test_input.png
  server/tests/crop_test_output_100x100.png
  server/tests/crop_test_output_100x45.png
  server/tests/crop_test_output_45x100.png
  server/tests/crop_test_output_45x45.png
  server/tests/fill_test_input.png
  server/tests/fill_test_output_100x100.png
  server/tests/fill_test_output_100x45.png
  server/tests/fill_test_output_45x100.png
  server/tests/fill_test_output_45x45.png
  server/tests/fit_test_input.png
  server/tests/fit_test_output_100x100.png
  server/tests/fit_test_output_100x45.png
  server/tests/fit_test_output_45x100.png
  server/tests/fit_test_output_45x45.png
  server/tests/orientation_test_1_expected_thumb.jpeg
  server/tests/orientation_test_2_expected_preview.jpeg
  server/tests/orientation_test_2_expected_thumb.jpeg
  server/tests/orientation_test_3_expected_preview.jpeg
  server/tests/orientation_test_3_expected_thumb.jpeg
  server/tests/orientation_test_4_expected_thumb.jpeg
  server/tests/orientation_test_5_expected_thumb.jpeg
  server/tests/orientation_test_6_expected_preview.jpeg
  server/tests/orientation_test_6_expected_thumb.jpeg
  server/tests/orientation_test_7_expected_preview.jpeg
  server/tests/orientation_test_7_expected_thumb.jpeg
  server/tests/orientation_test_8_expected_preview.jpeg
  server/tests/orientation_test_8_expected_thumb.jpeg
  server/tests/test_expected_tiff_thumb.jpeg
  server/tests/testgif_expected_thumbnail.jpg
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, E2E/Overridden

#30260 [MM-62660] Makefile: add ability to run local file store tests as standalone
  server/Makefile
  server/platform/shared/filestore/filesstore_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#29900 [MM-61610]: Added aria-activedescendant to the textbox
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_provider.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.test.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/textbox/textbox.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, Area/Accessibility, release-note-none, Contributor

#29890 [MM-62438] Fix flaky TestGetMattermostLog
  server/channels/app/platform/log_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#29565 [MM-22872] fix(messaging): DM list not scrolling when you press the up/down arrow keys
  e2e-tests/cypress/tests/integration/channels/messaging/dm_list_of_users_spec.js
  webapp/channels/src/components/more_direct_channels/list_item/index.ts
Labels: 4: Reviews Complete, kind/bug, release-note-none, Contributor, E2E/Overridden

#29902 [MM-61616]: Add tab roles inside Emoji Picker
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/__snapshots__/emoji_picker_category.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.test.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, Area/Accessibility, release-note-none, Contributor

#30279 Automated cherry pick of #30098
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30280 Automated cherry pick of #30098
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30281 Automated cherry pick of #30098
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30217 Automated cherry pick of #30034
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/store/storetest/mocks/ChannelBookmarkStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29957 Mm 62677 - modal focus management - find channels modal
  e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_header_spec.ts
  e2e-tests/cypress/tests/integration/channels/bot_accounts/in_teams_and_channels_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/leave_and_archive_channel_destructive_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/permissions/team_permissions_spec.ts
  e2e-tests/cypress/tests/integration/channels/messaging/focus_move_spec.js
  e2e-tests/cypress/tests/support/ui/channel.d.ts
  e2e-tests/cypress/tests/support/ui/channel.js
  webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  webapp/channels/src/components/channel_header_dropdown/channel_header_dropdown_items.tsx
  webapp/channels/src/components/channel_info_rhs/channel_info_rhs.tsx
  webapp/channels/src/components/channel_info_rhs/top_buttons.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.tsx
  webapp/channels/src/components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  webapp/channels/src/components/more_direct_channels/more_direct_channels.scss
  webapp/channels/src/components/more_direct_channels/more_direct_channels.test.tsx
  webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
  webapp/channels/src/components/new_search/new_search.tsx
  webapp/channels/src/components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.test.tsx
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
  webapp/channels/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/channels/src/components/sidebar/channel_navigator/channel_navigator.test.tsx
  webapp/channels/src/components/sidebar/channel_navigator/channel_navigator.tsx
  webapp/channels/src/components/sidebar/sidebar.tsx
  webapp/channels/src/components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category.tsx
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/components/three_days_left_trial_modal/three_days_left_trial_modal.scss
  webapp/channels/src/components/three_days_left_trial_modal/three_days_left_trial_modal.tsx
  webapp/channels/src/sass/components/_channel-switcher.scss
  webapp/channels/src/utils/a11y_controller.ts
  webapp/channels/src/utils/a11y_utils.ts
  webapp/platform/components/src/generic_modal/generic_modal.scss
  webapp/platform/components/src/generic_modal/generic_modal.tsx
Labels: Setup Cloud Test Server, release-note-none, 1. UX Review

#30135 [MM-62924] WebSocketClient reconnection unit tests
  webapp/channels/src/components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  webapp/platform/client/src/websocket.test.ts
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note

#30283 MM-61375: Update file handling for bookmarks (#30034)
  server/channels/app/channel_bookmark.go
  server/channels/app/channel_bookmark_test.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_bookmark_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_bookmark.go
  server/channels/store/storetest/mocks/ChannelBookmarkStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30286 Automated cherry pick of #30268
  server/channels/api4/user_test.go
  server/channels/app/bot.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30287 Automated cherry pick of #30268
  server/channels/api4/user_test.go
  server/channels/app/bot.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30288 Automated cherry pick of #30268
  server/channels/api4/user_test.go
  server/channels/app/bot.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30128 Clarify patch role permissions
  api/v4/source/roles.yaml
Labels: 4: Reviews Complete, release-note-none

#30265 MM-62866 Update axios dependency
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#30290 MM-63195: Allow only self for updateUserMFA
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: 4: Reviews Complete, release-note-none

#30297 [Cherry-pick][AI assisted] MM-62837: (#30268)
  server/channels/api4/user_test.go
  server/channels/app/bot.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30296 [Cherry-pick][AI assisted] MM-62837: (#30268)
  server/channels/api4/user_test.go
  server/channels/app/bot.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30300 Automated cherry pick of #30290
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30302 Automated cherry pick of #30290
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30301 Automated cherry pick of #30290
  server/channels/api4/user.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30307 Automated cherry pick of #29811
  webapp/channels/src/components/drafts/drafts.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30306 Automated cherry pick of #29811
  webapp/channels/src/components/drafts/drafts.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30303 Automated cherry pick of #30265
  webapp/channels/package.json
  webapp/package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30304 Automated cherry pick of #30265
  webapp/channels/package.json
  webapp/package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30193 Remove channel export plugin from transitional plugins list.
  server/channels/app/plugin.go
Labels: 2: Dev Review, release-note, E2E/Overridden

#30170 MM-62760 - Allow Team Admins to view team email
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#30169 MM-62564 - implement websockets for CPA
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/user_settings/general/index.ts
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/action_types/users.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, QA - Deferred, release-note-none, E2E/Overridden

#30261 MM-62079: Using a cache prefix to isolate cache keys for each test
  server/channels/api4/apitestlib.go
  server/channels/api4/post_test.go
  server/channels/app/platform/service.go
  server/platform/services/cache/provider.go
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden
