Repository mattermost/mattermost, pull requests merged in 2025-05, with the labels that each got.

#30716 MM-63648 - markdown images sometimes do not show the more button
  webapp/channels/src/components/post_view/show_more/__snapshots__/show_more.test.tsx.snap
  webapp/channels/src/components/post_view/show_more/show_more.test.tsx
  webapp/channels/src/components/post_view/show_more/show_more.tsx
Labels: 4: Reviews Complete, 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30685 MM-63649 - fix preview embeded images
  e2e-tests/cypress/tests/integration/channels/messaging/pasted_image_url_preview_spec.js
  webapp/channels/src/components/file_preview_modal/file_preview_modal.test.tsx
  webapp/channels/src/components/file_preview_modal/file_preview_modal.tsx
  webapp/channels/src/components/file_preview_modal/types.ts
  webapp/channels/src/utils/utils.test.tsx
  webapp/channels/src/utils/utils.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA-wanted

#30276 MM-62158: group store no SELECT * (Part 1)
  server/channels/store/sqlstore/group_store.go
  server/channels/store/storetest/group_store.go
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#30882 Renamed premium SKU to Enterprise Advanced
  e2e-tests/playwright/specs/functional/channels/channel_banner/channel_banner.spec.ts
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/license.go
  server/public/model/license_test.go
  server/public/pluginapi/license.go
  server/public/pluginapi/license_test.go
  webapp/channels/src/components/channel_banner/channel_banner.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.test.tsx
  webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.ts
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/license_utils.ts
  webapp/channels/src/utils/subscription.ts
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30894 Automated cherry pick of #30452
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30913 fix default field type if missing value_type in attrs
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Deferred, release-note-none

#30920 Automated cherry pick of #30913
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30921 Automated cherry pick of #30887
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx
  webapp/channels/src/components/profile_popover/profile_popover_url.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_url.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30820 MM-62930: Add validation of LDAP attribute values. (#30419)
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/.ci/server.prepare.sh
  server/Makefile
  server/i18n/en.json
  server/tests/custom-schema-objectID.ldif
  server/tests/test-data.ldif
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#30823 MM-62930: Add validation of LDAP attribute values. (#30419)
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/.ci/server.prepare.sh
  server/Makefile
  server/i18n/en.json
  server/tests/custom-schema-objectID.ldif
  server/tests/test-data.ldif
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#30916 System console tiered license check
  server/config/client.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.test.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
Labels: 2: Dev Review, 3: QA Review, release-note-none, E2E/Overridden

#30908 Automated cherry pick of #30471
  e2e-tests/cypress/tests/support/api/system.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30595 fix errcheck in server/channels/app/platform/session.go
  server/.golangci.yml
  server/channels/app/oauth.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/platform/session.go
  server/channels/app/platform/session_test.go
  server/channels/app/session.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#29146 [MM-61505] Fix errcheck issues in server/channels/app/team_test.go
  server/.golangci.yml
  server/channels/app/team_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#30822 MM-62930: Add validation of LDAP attribute values. (#30419)
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/.ci/server.prepare.sh
  server/Makefile
  server/i18n/en.json
  server/tests/custom-schema-objectID.ldif
  server/tests/test-data.ldif
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30938 Fix errcheck issue on master
  server/channels/app/platform/web_hub_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30907 Channel banner misc fixes
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#30945 fix: Ignore mm deps from Notice file
  server/build/notice-file/config.yaml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, kind/bug, release-note-none, E2E/Overridden

#30941 [MM-64179] Make MFA setup text generic for any authenticator app
  webapp/channels/src/components/mfa/__snapshots__/confirm.test.tsx.snap
  webapp/channels/src/components/mfa/confirm.tsx
  webapp/channels/src/components/mfa/setup/setup.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#30931 [CP] MM-63756: Added index to sidebarchannels table (#30724)
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.down.sql
  server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.up.sql
  server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.down.sql
  server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.up.sql
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30876 [MM-61774] Fix errcheck issues in server/channels/app/platform/status.go
  server/.golangci.yml
  server/channels/app/platform/status.go
Labels: 4: Reviews Complete, release-note-none

#30878 [MM-28923] Fix errcheck issues in server/channels/app/file.go
  server/.golangci.yml
  server/channels/app/file.go
  server/channels/app/file_test.go
Labels: 4: Reviews Complete, release-note-none

#30843 [MM-63837] Bump x/net version to 0.39
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: release-note

#30362 [GH-25995]_Validate SITE URL in mmctl auth login
  server/cmd/mmctl/commands/auth.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#30707 [MM-61074] Fix errcheck issues in oauth_test.go and web_test.go
  server/.golangci.yml
  server/channels/api4/file_test.go
  server/channels/api4/team_test.go
  server/channels/app/oauth_test.go
  server/channels/jobs/batch_migration_worker_test.go
  server/channels/jobs/batch_report_worker_test.go
  server/channels/jobs/batch_worker_test.go
  server/channels/jobs/export_delete_test.go
  server/channels/jobs/helper_test.go
  server/channels/utils/emoji.go
  server/channels/web/context_test.go
  server/channels/web/handlers_test.go
  server/channels/web/oauth_test.go
  server/channels/web/web_test.go
  server/channels/web/webhook_test.go
  server/cmd/mattermost/commands/cmdtestlib.go
  server/cmd/mattermost/commands/server_test.go
  server/public/shared/request/context.go
Labels: 4: Reviews Complete, release-note-none

#30678 [MM-29111] Fix errcheck issues in server/channels/app/upload.go
  server/.golangci.yml
  server/channels/app/upload.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30847 [MM-62986][MM-63011][MM-63013][MM-63014][MM-63018] Various accessibility fixes around login, account creation and MFA setup
  e2e-tests/cypress/tests/integration/channels/account_settings/security/password_spec.ts
  e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_2_spec.ts
  e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_4_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/bot_accounts/managing_bot_accounts_spec.ts
  e2e-tests/cypress/tests/integration/channels/signin_authentication/login_logout_smoke_spec.js
  e2e-tests/cypress/tests/integration/channels/signin_authentication/login_open_server_spec.js
  e2e-tests/cypress/tests/integration/channels/signin_authentication/signup_spec.js
  e2e-tests/cypress/tests/integration/channels/system_console/user_management/users_spec.js
  e2e-tests/cypress/tests/support/common_login_commands.js
  e2e-tests/playwright/lib/src/ui/pages/login.ts
  e2e-tests/playwright/lib/src/ui/pages/signup.ts
  e2e-tests/playwright/specs/accessibility/common/login.spec.ts
  e2e-tests/playwright/specs/accessibility/common/signup_user_complete.spec.ts
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  webapp/channels/src/components/alert_banner/index.tsx
  webapp/channels/src/components/channel_invite_modal/team_warning_banner/__snapshots__/team_warning_banner.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/header_footer_route/header.scss
  webapp/channels/src/components/login/login.test.tsx
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/mfa/setup/setup.test.tsx
  webapp/channels/src/components/mfa/setup/setup.tsx
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.test.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/widgets/inputs/password_input/password_input.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/password.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30905 [MM-62974][MM-62984][MM-63016][MM-63025] Various fixes for the Create Team screen
  webapp/channels/src/components/create_team/components/__snapshots__/display_name.test.tsx.snap
  webapp/channels/src/components/create_team/components/display_name.test.tsx
  webapp/channels/src/components/create_team/components/display_name.tsx
  webapp/channels/src/components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap
  webapp/channels/src/components/create_team/components/team_url/team_url.test.tsx
  webapp/channels/src/components/create_team/components/team_url/team_url.tsx
  webapp/channels/src/components/create_team/create_team.test.tsx
  webapp/channels/src/components/create_team/create_team.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30910 [MM-62971][MM-63017] Search box accessibility fixes
  webapp/channels/src/components/new_search/extension_suggestions.tsx
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30857 [MM-63015] Add more descriptive page titles to login/create account/password reset pages
  e2e-tests/cypress/tests/integration/channels/system_console/ui_and_api/custom_site_name_description_spec.ts
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/components/password_reset_form/password_reset_form.tsx
  webapp/channels/src/components/password_reset_send_link/__snapshots__/password_reset_send_link.test.tsx.snap
  webapp/channels/src/components/password_reset_send_link/index.ts
  webapp/channels/src/components/password_reset_send_link/password_reset_send_link.test.tsx
  webapp/channels/src/components/password_reset_send_link/password_reset_send_link.tsx
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30837 [MM-62987] Include description on aria-label for last reply time, make link focused when using up/down arrows.
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.test.tsx
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
  webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30963 MM-64209: Optimize completePopulatingCategoryChannelsT for MySQL
  server/channels/store/sqlstore/channel_store_categories.go
Labels: 4: Reviews Complete, release-note-none

#30966 Automated cherry pick of #30963
  server/channels/store/sqlstore/channel_store_categories.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30959 Manual cherry-pick of #30827
  .github/workflows/api.yml
  .github/workflows/e2e-tests-ci.yml
  .github/workflows/esrupgrade-common.yml
  .github/workflows/migration.yml
  .github/workflows/mmctl-test-template.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/server-ci-artifacts.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/cypress/tests/support/api/system.js
  server/Makefile
  server/go.mod
  server/go.sum
  server/public/go.mod
  server/public/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note, E2E/Overridden

#30967 Automated cherry pick of #30963
  server/channels/store/sqlstore/channel_store_categories.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30964 Revert #30939
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
Labels: 4: Reviews Complete, release-note

#30879 [MM-61498] Fix errcheck issues in server/channels/app/slashcommands/command_test.go
  server/.golangci.yml
  server/channels/app/slashcommands/command_test.go
Labels: 4: Reviews Complete, release-note-none

#30937 System Console enterprise advanced upsells
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/about/edition_and_license_spec.js
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.test.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Deferred, release-note-none

#30792 MM-63130: Move to webHub iteration to be alloc-free
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/web_hub_test.go
Labels: 4: Reviews Complete, LoadTest, release-note-none, E2E/Overridden

#30680 [MM-63661] add access control metrics
  server/einterfaces/metrics.go
  server/einterfaces/mocks/MetricsInterface.go
  server/enterprise/metrics/metrics.go
Labels: release-note-none, E2E/Overridden

#30988 Automated cherry pick of #30628
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30989 Automated cherry pick of #30628
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30990 Automated cherry pick of #30628
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30880 [MM-61499] Fix errcheck issues in server/channels/app/slashcommands/helper_test.go
  server/.golangci.yml
  server/channels/app/slashcommands/command_channel_header_test.go
  server/channels/app/slashcommands/command_channel_purpose_test.go
  server/channels/app/slashcommands/command_channel_rename_test.go
  server/channels/app/slashcommands/command_groupmsg_test.go
  server/channels/app/slashcommands/command_invite_people_test.go
  server/channels/app/slashcommands/command_invite_test.go
  server/channels/app/slashcommands/command_join_test.go
  server/channels/app/slashcommands/command_leave_test.go
  server/channels/app/slashcommands/command_marketplace_test.go
  server/channels/app/slashcommands/command_me_test.go
  server/channels/app/slashcommands/command_msg_test.go
  server/channels/app/slashcommands/command_mute_test.go
  server/channels/app/slashcommands/command_remove_test.go
  server/channels/app/slashcommands/command_share_test.go
  server/channels/app/slashcommands/command_test.go
  server/channels/app/slashcommands/helper_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30954 [MM-61765] Fix errcheck issues in server/channels/app/platform/license.go
  server/.golangci.yml
  server/channels/app/platform/license.go
Labels: 4: Reviews Complete, release-note-none

#30397 MM-57014 Extended console log search to all log attributes
  webapp/channels/src/components/admin_console/server_logs/__snapshots__/logs.test.tsx.snap
  webapp/channels/src/components/admin_console/server_logs/logs.test.tsx
  webapp/channels/src/components/admin_console/server_logs/logs.tsx
Labels: 4: Reviews Complete, release-note, Contributor, E2E/Overridden

#30960 [MM-62975][MM-62981] Invite Modal accessibility fixes
  webapp/channels/src/components/invitation_modal/result_table.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note, E2E/Overridden

#30922 [MM-62973][MM-63028][MM-63034][MM-63027] Various accessibility fixes around Browse Channels modal
  e2e-tests/cypress/tests/integration/channels/channel/browse_public_channels_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.ts
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/components/src/generic_modal/__snapshots__/generic_modal.test.tsx.snap
  webapp/platform/components/src/generic_modal/generic_modal.tsx
Labels: Setup Cloud Test Server, release-note, 1. UX Review, E2E/Overridden

#30771 MM-56906: Remove redundant calls on team switch
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/channel.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/channels/web/params.go
  server/channels/web/params_test.go
  server/public/model/channel_member.go
  server/public/model/client4.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/components/team_controller/actions/index.ts
  webapp/channels/src/components/team_controller/team_controller.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/platform/client/src/client4.test.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30924 [MM-63000][MM-63055][MM-63046] Various accessibility fixes around Drafts
  webapp/channels/src/components/common/hooks/use_scroll_on_render.ts
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/action.test.tsx.snap
  webapp/channels/src/components/drafts/draft_actions/action.tsx
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/components/drafts/panel/__snapshots__/panel.test.tsx.snap
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_header.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel.scss
  webapp/channels/src/components/drafts/panel/panel.tsx
  webapp/channels/src/components/drafts/panel/panel_header.scss
  webapp/channels/src/components/drafts/panel/panel_header.test.tsx
  webapp/channels/src/components/drafts/panel/panel_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30919 Handle error returned by GetClusterInfos()
  server/channels/api4/cluster.go
  server/channels/app/admin.go
  server/channels/app/busy_test.go
  server/channels/app/platform/busy_test.go
  server/channels/app/platform/support_packet.go
  server/channels/jobs/batch_migration_worker.go
  server/channels/jobs/batch_migration_worker_test.go
  server/channels/testlib/cluster.go
  server/einterfaces/cluster.go
  server/einterfaces/mocks/ClusterInterface.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30844 Better handle missing cluster node info fields
  webapp/channels/src/components/admin_console/cluster_table.tsx
  webapp/channels/src/components/admin_console/cluster_table_container.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note, E2E/Overridden

#31000 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/nb-NO.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/sv.json
  server/i18n/tr.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hi.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, E2E/Overridden

#30926 MM-62158: group store, migrate groupsBySyncableBaseQuery, part 2
  server/channels/store/sqlstore/group_store.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none

#30986 UX fixes in the policies list and edit policy pages
  webapp/channels/src/components/admin_console/access_control/editors/cel_editor/editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/cel_editor/editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/shared.scss
  webapp/channels/src/components/admin_console/access_control/editors/shared.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/values_editor.scss
  webapp/channels/src/components/admin_console/access_control/jobs/access_control_sync_job_table.scss
  webapp/channels/src/components/admin_console/access_control/jobs/access_control_sync_job_table.tsx
  webapp/channels/src/components/admin_console/access_control/modals/policy_test/test_modal.scss
  webapp/channels/src/components/admin_console/access_control/modals/policy_test/test_modal.tsx
  webapp/channels/src/components/admin_console/access_control/modals/user_sync/synced_user_list.tsx
  webapp/channels/src/components/admin_console/access_control/modals/user_sync/user_sync_modal.scss
  webapp/channels/src/components/admin_console/access_control/policies.scss
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.scss
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/channels/src/components/admin_console/jobs/table.tsx
  webapp/channels/src/i18n/en.json
Labels: release-note-none

#30745 [MM-63775] Use error from OnSamlLogin
  server/channels/web/saml.go
  server/i18n/en.json
Labels: release-note-none

#30379 [MM-63319] Add deactivation status to mmctl user search output
  server/cmd/mmctl/commands/user.go
  server/cmd/mmctl/commands/user_e2e_test.go
  server/cmd/mmctl/commands/user_test.go
Labels: 4: Reviews Complete, release-note

#30953 Permission schema error fix
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30987 Automated cherry pick of #30628
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31012 Automated cherry pick of #30953
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30981 MM-63912 - enhance validation for channel banner colors
  server/channels/api4/channel_test.go
  server/i18n/en.json
  server/public/model/channel.go
  server/public/model/channel_test.go
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, E2E/Overridden

#31014 Automated cherry pick of #30953
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31015 Automated cherry pick of #30953
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31016 Automated cherry pick of #30953
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31017 Automated cherry pick of #30953
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31019 Automated cherry pick of #30981
  server/channels/api4/channel_test.go
  server/i18n/en.json
  server/public/model/channel.go
  server/public/model/channel_test.go
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30859 Adds the capability to retrieve a property field by name
  server/channels/app/properties/property_field.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31023 Automated cherry pick of #30859
  server/channels/app/properties/property_field.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31031 [MM-64222] Update gosaml to match enterprise version
  server/go.mod
  server/go.sum
Labels: release-note-none, E2E/Overridden

#31033 Automated cherry pick of #31031
  server/go.mod
  server/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31006 MM-64155: Fix searchbox clear button to reset search type
  e2e-tests/playwright/specs/functional/channels/search/search_box_clear_button.spec.ts
  webapp/channels/src/components/new_search/new_search.tsx
  webapp/channels/src/components/new_search/search_box_input.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#31034 Automated cherry pick of #31031
  server/go.mod
  server/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30961 [MM-63619] Improve Groups API error semantics
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/group.go
  server/i18n/en.json
Labels: 4: Reviews Complete, QA - Review Not Required, release-note, E2E/Overridden

#30983 MM-63965 - add scroll to advanced text editor
  webapp/channels/src/components/__snapshots__/autosize_textarea.test.tsx.snap
  webapp/channels/src/components/autosize_textarea.tsx
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#31041 Pre-package MS Teams v2.2.1
  server/Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note, E2E/Overridden

#30979 MM-63968 - remove channel name input plus one
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#30746 [MM-63774] Allow users to leave private channels when there is only 1 member
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/i18n/en.json
Labels: 3: QA Review, CherryPick/Approved, release-note-none, E2E/Overridden

#31046 Fix flaky test for TestLeaveChannel
  server/channels/app/channel_test.go
Labels: release-note-none, E2E/Overridden

#31045 Automated cherry pick of #30746
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31009 Add beta badge to the admin definition
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.scss
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/widgets/tag/beta_tag.tsx
  webapp/channels/src/components/widgets/tag/tag.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#30984 MM-64232 - adjust disabled styles channel settings modal
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.tsx
  webapp/channels/src/components/widgets/inputs/input/input.scss
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none, 1. UX Review, E2E/Overridden

#31042 Automated cherry pick of #30983
  webapp/channels/src/components/__snapshots__/autosize_textarea.test.tsx.snap
  webapp/channels/src/components/autosize_textarea.tsx
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31044 Automated cherry pick of #30979
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31049 Automated cherry pick of #30984
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.tsx
  webapp/channels/src/components/widgets/inputs/input/input.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30971 Mm 63844 add end user indicators
  webapp/channels/src/components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.scss
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.scss
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.test.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.tsx
  webapp/channels/src/components/channel_members_rhs/index.ts
  webapp/channels/src/components/channel_members_rhs/member.tsx
  webapp/channels/src/components/channel_members_rhs/member_list.tsx
  webapp/channels/src/components/common/hooks/useAccessControlAttributes.test.tsx
  webapp/channels/src/components/common/hooks/useAccessControlAttributes.ts
  webapp/channels/src/components/widgets/tag/__snapshots__/alert_tag.test.tsx.snap
  webapp/channels/src/components/widgets/tag/alert_tag.scss
  webapp/channels/src/components/widgets/tag/alert_tag.test.tsx
  webapp/channels/src/components/widgets/tag/alert_tag.tsx
  webapp/channels/src/components/widgets/tag/tag_group.scss
  webapp/channels/src/components/widgets/tag/tag_group.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/access_control.ts
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none, E2E/Overridden

#30856 MM-63406: Update timezone automatically
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/utils/timezone.ts
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#31058 Automated cherry pick of #30971
  webapp/channels/src/components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.scss
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.scss
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.test.tsx
  webapp/channels/src/components/channel_members_rhs/channel_members_rhs.tsx
  webapp/channels/src/components/channel_members_rhs/index.ts
  webapp/channels/src/components/channel_members_rhs/member.tsx
  webapp/channels/src/components/channel_members_rhs/member_list.tsx
  webapp/channels/src/components/common/hooks/useAccessControlAttributes.test.tsx
  webapp/channels/src/components/common/hooks/useAccessControlAttributes.ts
  webapp/channels/src/components/widgets/tag/__snapshots__/alert_tag.test.tsx.snap
  webapp/channels/src/components/widgets/tag/alert_tag.scss
  webapp/channels/src/components/widgets/tag/alert_tag.test.tsx
  webapp/channels/src/components/widgets/tag/alert_tag.tsx
  webapp/channels/src/components/widgets/tag/tag_group.scss
  webapp/channels/src/components/widgets/tag/tag_group.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/access_control.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30797 Bump prepackage GitLab plugin version to 1.10.0
  server/Makefile
Labels: 2: Dev Review, release-note

#30668 Bump prepackage Github plugin version to 2.4.0
  server/Makefile
Labels: 2: Dev Review, AutoMerge, release-note

#30867 [MM-63838] Fix potential TypeError when Calls is disabled
  webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/index.test.tsx
  webapp/channels/src/selectors/calls.ts
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30347 MM-51488 Fixed checkboxes position in markdown lists for posts
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/layout/_markdown.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note, Contributor, E2E/Overridden

#30993 MM-63966 - save pannel not dissapearing after save
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none

#30343 [MM-58163] Jobs paging/offset refactor
  server/channels/app/job.go
  server/channels/app/job_test.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/storetest/job_store.go
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#31097 Automated cherry pick of #30993
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31101 Automated cherry pick of #31096
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#31099 Translations update from Mattermost Weblate
  server/i18n/be.json
  server/i18n/bg.json
  server/i18n/ca.json
  server/i18n/cs.json
  server/i18n/da.json
  server/i18n/de.json
  server/i18n/el.json
  server/i18n/en-AU.json
  server/i18n/es.json
  server/i18n/fa.json
  server/i18n/fi.json
  server/i18n/fr.json
  server/i18n/gl.json
  server/i18n/hi.json
  server/i18n/hr.json
  server/i18n/hu.json
  server/i18n/id.json
  server/i18n/it.json
  server/i18n/ja.json
  server/i18n/ka.json
  server/i18n/ko.json
  server/i18n/lt.json
  server/i18n/mk.json
  server/i18n/ml.json
  server/i18n/nb-NO.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/pt-BR.json
  server/i18n/ro.json
  server/i18n/ru.json
  server/i18n/sl.json
  server/i18n/sr.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/vi.json
  server/i18n/zh-CN.json
  server/i18n/zh-TW.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
Labels: release-note-none, Do Not Merge/Mattermod, E2E/Overridden

#31063 User usage alert in License and System Statistics page
  webapp/channels/src/components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/user_seat_alert_banner.tsx
  webapp/channels/src/components/alert_banner/alert_banner.scss
  webapp/channels/src/components/analytics/activated_users_card/index.tsx
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/index.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#31102 Automated cherry pick of #31063
  webapp/channels/src/components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/user_seat_alert_banner.tsx
  webapp/channels/src/components/alert_banner/alert_banner.scss
  webapp/channels/src/components/analytics/activated_users_card/index.tsx
  webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/index.tsx
  webapp/channels/src/components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31103 MM-64336: simplify doc extractor
  server/platform/services/docextractor/archive.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31067 Prepackage Playbooks 2.2.0
  server/Makefile
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, E2E/Overridden

#31109 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31108 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31104 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31105 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31106 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31107 Automated cherry pick of #31103
  server/platform/services/docextractor/archive.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31111 Automated cherry pick of #31067
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31112 Automated cherry pick of #31067
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31113 Automated cherry pick of #31067
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31114 Automated cherry pick of #31067
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31115 Automated cherry pick of #31067
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30787 [MM-63772] Add LDAP setting to re-add removed members
  server/channels/api4/ldap.go
  server/channels/api4/ldap_test.go
  server/channels/app/group.go
  server/channels/app/ldap.go
  server/channels/app/syncables.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/ldap.go
  server/cmd/mmctl/commands/ldap_test.go
  server/cmd/mmctl/docs/mmctl_ldap_sync.rst
  server/cmd/mmctl/mocks/client_mock.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapInterface.go
  server/public/model/client4.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, E2E/Overridden

#29396 Add end to end tests to the "configReloadCmdF" mmctl command
  server/cmd/mmctl/commands/config_e2e_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#31120 Automated cherry pick of #30787
  server/channels/api4/ldap.go
  server/channels/api4/ldap_test.go
  server/channels/app/group.go
  server/channels/app/ldap.go
  server/channels/app/syncables.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/ldap.go
  server/cmd/mmctl/commands/ldap_test.go
  server/cmd/mmctl/docs/mmctl_ldap_sync.rst
  server/cmd/mmctl/mocks/client_mock.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapInterface.go
  server/public/model/client4.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31004 MM-64226: improved post deduplication
  server/channels/api4/post_create_test.go
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30965 MM-63923/MM-63924/MM-63925 Prevent deadlocks and constraint errors in UpdateSidebarCategories
  server/channels/api4/channel_category.go
  server/channels/api4/channel_category_test.go
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#31126 Automated cherry pick of #30965
  server/channels/api4/channel_category.go
  server/channels/api4/channel_category_test.go
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/storetest/channel_store_categories.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31061 Slightly improve performance of sidebar update APIs
  server/channels/api4/channel_category.go
  server/channels/api4/channel_category_test.go
Labels: 4: Reviews Complete, release-note

#31098 Bump prepackage Jira plugin version to 4.3.0
  server/Makefile
Labels: 2: Dev Review, release-note, E2E/Overridden

#30991 MM-62365: Remove unused field from MetricSample
  server/channels/app/metrics_test.go
  server/public/model/metrics.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31116 MM-63300: Fix flaky test TestBusySet
  server/channels/app/busy_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31130 Automated cherry pick of #31004
  server/channels/api4/post_create_test.go
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31124 [MM-63789] Prepackage Calls v1.8.0
  server/Makefile
Labels: CherryPick/Approved, release-note, E2E/Overridden

#31134 Prepackage Calls v1.8.0 (`release-10.9`)
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#30679 [MM-61099] Fix errcheck issues in server/channels/app/brand.go
  server/.golangci.yml
  server/channels/api4/apitestlib.go
  server/channels/api4/brand_test.go
  server/channels/api4/emoji_test.go
  server/channels/api4/export_test.go
  server/channels/api4/import_test.go
  server/channels/api4/job_test.go
  server/channels/api4/notify_admin_test.go
  server/channels/app/brand.go
  server/channels/app/file_test.go
Labels: 2: Dev Review, release-note-none

#31142 Cherry-pick: Bump prepackage Jira plugin version to 4.3.0
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#30927 MM-62158: group store no select star, part3
  server/channels/store/sqlstore/group_store.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#31007 Fix notification message for posts with no text content
  e2e-tests/cypress/tests/integration/channels/notifications/desktop_notifications_1_spec.js
  webapp/channels/src/actions/notification_actions.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note

#30790 New pluginapi method for syncables
  server/channels/app/plugin_api.go
  server/i18n/en.json
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/group.go
Labels: CherryPick/Approved, release-note-none, E2E/Overridden

#31149 Automated cherry pick of #30790
  server/channels/app/plugin_api.go
  server/i18n/en.json
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/group.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30851 [MM-63884] Move DynamicVirtualizedList to monorepo
  .gitignore
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  webapp/channels/src/components/dynamic_virtualized_list/dynamic_virtualized_list.d.ts
  webapp/channels/src/components/dynamic_virtualized_list/index.jsx
  webapp/channels/src/components/dynamic_virtualized_list/item_measurer.jsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.test.tsx
  webapp/channels/src/components/post_view/post_list_virtualized/post_list_virtualized.tsx
Labels: 4: Reviews Complete, release-note-none

#31146 MM-63923/MM-63924/MM-63925 Prevent deadlocks and constraint errors in UpdateSidebarCategories (#30965) (10.5)
  server/channels/api4/channel_category.go
  server/channels/api4/channel_category_test.go
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/storetest/channel_store_categories.go
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#31151 Automated cherry pick of #31004
  server/channels/api4/post_create_test.go
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31156 Automated cherry pick of #31041
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31157 Automated cherry pick of #31041
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31159 Automated cherry pick of #31041
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31154 Automated cherry pick of #31004
  server/channels/api4/post_create_test.go
  server/channels/app/post.go
  server/channels/app/post_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31148 [MM-64255] Fix height of automatic replies textarea
  webapp/channels/src/components/user_settings/notifications/manage_auto_responder/__snapshots__/manage_auto_responder.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/manage_auto_responder/manage_auto_responder.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31145 Remove unused invalid CSS
  webapp/channels/src/sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note-none

#31002 feat: support SSO while embedded
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/utils/embed.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, kind/feature, release-note-none

#31147 MM-64030/MM-64025/MM-63985/MM-63986/MM-63987/MM-63976/MM-64018/MM-64017/MM-64034/MM-64029 - Various accessibility fixes around User Groups modals
  webapp/channels/src/components/add_users_to_group_modal/__snapshots__/add_users_to_group_modal.test.tsx.snap
  webapp/channels/src/components/add_users_to_group_modal/add_users_to_group_modal.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
  webapp/channels/src/components/user_groups_modal/index.ts
  webapp/channels/src/components/user_groups_modal/user_groups_filter/user_groups_filter.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_list/user_groups_list.test.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_list/user_groups_list.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal.scss
  webapp/channels/src/components/user_groups_modal/user_groups_modal.test.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal_header/__snapshots__/user_groups_modal_header.test.tsx.snap
  webapp/channels/src/components/user_groups_modal/user_groups_modal_header/index.ts
  webapp/channels/src/components/user_groups_modal/user_groups_modal_header/user_groups_modal_header.test.tsx
  webapp/channels/src/components/user_groups_modal/user_groups_modal_header/user_groups_modal_header.tsx
  webapp/channels/src/components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
  webapp/channels/src/components/view_user_group_modal/view_user_group_header_sub_menu/view_user_group_header_sub_menu.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.test.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/components/src/hooks/useFocusTrap.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31175 Automated cherry pick of #31127
  webapp/channels/src/components/admin_console/admin_console.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31184 Automated cherry pick of #30629
  webapp/channels/src/components/admin_console/group_settings/group_details/group_details.test.tsx
  webapp/channels/src/components/admin_console/group_settings/group_details/group_details.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none, E2E/Overridden

#31164 Reject mysql for enterprise advanced
  server/channels/api4/access_control_test.go
  server/channels/api4/channel_test.go
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/channels/app/platform/license.go
  server/channels/app/platform/license_test.go
  server/i18n/en.json
  webapp/channels/src/components/admin_console/license_settings/index.ts
  webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.test.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, QA - Deferred, release-note, E2E/Overridden

#31177 Explicitly list exports from mattermost-redux (10.8)
  webapp/platform/mattermost-redux/package.json
Labels: 2: Dev Review, release-note-none

#30776 Accessibility: Add header tags missing in title sections
  e2e-tests/playwright/specs/visual/common/landing_page.spec.ts-snapshots/landing-page-visual-check-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/landing_page.spec.ts-snapshots/landing-page-visual-check-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/landing_page.spec.ts-snapshots/landing-page-visual-check-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-error-free-edition-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-error-free-edition-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-error-free-edition-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-free-edition-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-free-edition-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/login.spec.ts-snapshots/login-page-visual-check-free-edition-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-error-free-edition-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-error-free-edition-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-error-free-edition-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-free-edition-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-free-edition-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-page-visual-check-free-edition-ipad-linux.png
  webapp/channels/src/components/channel_info_rhs/header.tsx
  webapp/channels/src/components/channel_members_rhs/header.tsx
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/new_search/search_box_suggestions.tsx
  webapp/channels/src/components/new_search/search_hint.tsx
  webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
  webapp/channels/src/components/post_edit_history/post_edit_history.tsx
  webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
  webapp/channels/src/components/signup/signup.scss
  webapp/channels/src/components/signup/signup.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/widgets/modals/components/modal_header.scss
  webapp/channels/src/components/widgets/modals/components/modal_header.tsx
  webapp/channels/src/sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, release-note-none

#31008 MM-63898 Improve Blockquote Style
  webapp/channels/src/components/post_view/show_more/show_more.tsx
  webapp/channels/src/sass/components/_post.scss
  webapp/channels/src/sass/layout/_markdown.scss
  webapp/channels/src/sass/responsive/_tablet.scss
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#31186 Automated cherry pick of #31164
  server/channels/api4/access_control_test.go
  server/channels/api4/channel_test.go
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/channels/app/platform/license.go
  server/channels/app/platform/license_test.go
  server/i18n/en.json
  webapp/channels/src/components/admin_console/license_settings/index.ts
  webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.test.tsx
  webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31122 Deletes CPA values on CPA field type change
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/channels/app/properties/property_field.go
  server/channels/app/properties/property_value.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyValueStore.go
  server/channels/store/storetest/property_value_store.go
  server/channels/store/timerlayer/timerlayer.go
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/users.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none

#31025 Improves the invite mechanism for remote clusters
  server/channels/app/remote_cluster.go
  server/platform/services/remotecluster/invitation.go
  server/platform/services/remotecluster/recv.go
  server/public/model/remote_cluster.go
  server/public/model/remote_cluster_test.go
Labels: 2: Dev Review, QA - Deferred, release-note-none, E2E/Run
