Repository mattermost/mattermost, pull requests merged in 2025-08, with the labels that each got.

#33591 [MM-64685] Show back button on desktop external login redirect page
  webapp/channels/src/components/login/login.tsx
Labels: release-note

#33457 MM-62990 Properly group suggestions in SuggestionList (and various other autocompletes)
  e2e-tests/cypress/tests/integration/channels/channel/channel_mention_autocomplete_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_k_open_gm_with_mouse_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e-tests/playwright/lib/src/ui/components/channels/post_create.ts
  webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
  webapp/channels/src/components/forward_post_modal/forward_post_channel_select.tsx
  webapp/channels/src/components/new_search/extension_suggestions.tsx
  webapp/channels/src/components/new_search/extension_suggestions_provider.test.tsx
  webapp/channels/src/components/new_search/extension_suggestions_provider.tsx
  webapp/channels/src/components/new_search/hooks.tsx
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/components/new_search/search_box_hints.test.tsx
  webapp/channels/src/components/new_search/search_box_hints.tsx
  webapp/channels/src/components/new_search/search_box_input.tsx
  webapp/channels/src/components/new_search/search_box_suggestions.test.tsx
  webapp/channels/src/components/new_search/search_box_suggestions.tsx
  webapp/channels/src/components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
  webapp/channels/src/components/search_bar/search_bar.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_provider.test.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_provider.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  webapp/channels/src/components/suggestion/channel_mention_provider.tsx
  webapp/channels/src/components/suggestion/command_provider/app_provider.tsx
  webapp/channels/src/components/suggestion/command_provider/command_provider.test.tsx
  webapp/channels/src/components/suggestion/command_provider/command_provider.tsx
  webapp/channels/src/components/suggestion/emoticon_provider.test.tsx
  webapp/channels/src/components/suggestion/emoticon_provider.tsx
  webapp/channels/src/components/suggestion/modal_suggestion_list.tsx
  webapp/channels/src/components/suggestion/provider.tsx
  webapp/channels/src/components/suggestion/search_channel_provider.tsx
  webapp/channels/src/components/suggestion/search_suggestion_list.tsx
  webapp/channels/src/components/suggestion/search_user_provider.tsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
  webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.tsx
  webapp/channels/src/components/suggestion/suggestion_date.tsx
  webapp/channels/src/components/suggestion/suggestion_list.tsx
  webapp/channels/src/components/suggestion/suggestion_list_contents.tsx
  webapp/channels/src/components/suggestion/suggestion_results.test.ts
  webapp/channels/src/components/suggestion/suggestion_results.ts
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/textbox/textbox.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_popover.scss
  webapp/channels/src/sass/components/_suggestion-list.scss
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#32192 Bugfix: Fixed the issue of the cancel button behavior in user security tab
  webapp/channels/src/components/new_channel_modal/new_channel_modal.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#33630 Automated cherry pick of #33546
  server/.go-version
  server/build/Dockerfile.buildenv
  server/go.mod
  server/public/go.mod
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33624 [MM-62991] Ensure extra content is also accounted for in the focus order
  webapp/channels/src/components/setting_item_max.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#33633 Automated cherry pick of #33626
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/channels/web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33634 Automated cherry pick of #33626
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/channels/web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33636 Automated cherry pick of #33626
  server/channels/web/oauth.go
  server/channels/web/oauth_test.go
  server/channels/web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33527 [MM-64370] Policy edit page: ask confirmation to discard changes
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#33500 MM-64725 - channel settings modal do not update url automatically
  e2e-tests/cypress/tests/integration/channels/channel/channel_settings_modal_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/channel_settings_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_settings/channel_name_validations_spec.ts
  webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#33625 [MM-63027] Allow results to be read on filter without search term
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap
  webapp/channels/src/components/searchable_channel_list.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#33608 MM-64955 - search user email at issue
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/widgets/inputs/input/input.scss
  webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.ts
Labels: 2: Dev Review, Setup Cloud Test Server, QA - Review Done, release-note-none

#33640 MM-64987: Remove all prepackaged plugins
  server/Makefile
Labels: 2: Dev Review, release-note-none

#33645 Fixing a typo
  server/i18n/en.json
Labels: release-note-none, Contributor, E2E/Overridden

#33666 Automated cherry pick of #33545
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/web/oauth.go
  server/channels/web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33567 MM-64781 Update internal web app dependency versions and add script for future version updates
  webapp/channels/package.json
  webapp/package-lock.json
  webapp/platform/client/package.json
  webapp/platform/mattermost-redux/package.json
  webapp/platform/types/package.json
  webapp/scripts/update-versions.mjs
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#33669 Add script to update web app package versions going forward (10.11)
  webapp/scripts/update-versions.mjs
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#33674 Use chainctl for fips build images
  .github/workflows/build-server-image.yml
  .github/workflows/dispatch-server-builder-image.yml
Labels: release-note-none, E2E/Overridden

#33688 Automated cherry pick of #33624
  webapp/channels/src/components/setting_item_max.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33690 Automated cherry pick of #33411
  server/channels/app/channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33687 Automated cherry pick of #33379
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33686 Automated cherry pick of #33451
  webapp/channels/src/components/common/hooks/useOpenSalesLink.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33685 Automated cherry pick of #33625
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap
  webapp/channels/src/components/searchable_channel_list.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33691 Automated cherry pick of #33494
  server/public/model/cel.go
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/platform/types/src/access_control.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33693 Automated cherry pick of #33591
  webapp/channels/src/components/login/login.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33694 Automated cherry pick of #33476
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33695 Automated cherry pick of #32142
  webapp/channels/src/components/logged_in/index.test.ts
  webapp/channels/src/components/logged_in/index.ts
  webapp/channels/src/components/logged_in/logged_in.test.tsx
  webapp/channels/src/components/logged_in/logged_in.tsx
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/user_settings/general/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33696 Automated cherry pick of #33394
  webapp/channels/src/components/should_verify_email/should_verify_email.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33697 Automated cherry pick of #32771
  server/platform/services/sharedchannel/membership_recv.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33698 Automated cherry pick of #31086
  webapp/channels/src/components/access_history_modal/__snapshots__/access_history_modal.test.tsx.snap
  webapp/channels/src/components/access_history_modal/access_history_modal.scss
  webapp/channels/src/components/access_history_modal/access_history_modal.test.tsx
  webapp/channels/src/components/access_history_modal/access_history_modal.tsx
  webapp/channels/src/components/activity_log_modal/__snapshots__/activity_log_modal.test.tsx.snap
  webapp/channels/src/components/activity_log_modal/activity_log_modal.scss
  webapp/channels/src/components/activity_log_modal/activity_log_modal.test.tsx
  webapp/channels/src/components/activity_log_modal/activity_log_modal.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_archive_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_archive_tab.tsx
  webapp/channels/src/components/confirm_modal.tsx
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/abstract_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/add_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/edit_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/platform/components/src/generic_modal/generic_modal.scss
  webapp/platform/components/src/generic_modal/generic_modal.tsx
  webapp/platform/components/src/hooks/useStackedModal.test.tsx
  webapp/platform/components/src/hooks/useStackedModal.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33704 Automated cherry pick of #33389
  webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap
  webapp/channels/src/components/select_team/select_team.test.tsx
  webapp/channels/src/components/select_team/select_team.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33705 Automated cherry pick of #33562
  server/public/model/slack_attachment.go
  server/public/model/slack_attachment_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33707 Automated cherry pick of #33459
  webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
  webapp/channels/src/utils/paste.test.tsx
  webapp/channels/src/utils/paste.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33713 Automated cherry pick of #33708
  server/build/docker-preview/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33711 Automated cherry pick of #33708
  server/build/docker-preview/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33714 Automated cherry pick of #33708
  server/build/docker-preview/Dockerfile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33715 Automated cherry pick of #33553
  e2e-tests/cypress/tests/integration/channels/integrations/builtin_commands/user_status_spec.js
  e2e-tests/cypress/tests/integration/channels/multi_team_and_dm/check_user_status_spec.js
  webapp/channels/src/components/common/hooks/usePrefixedIds.test.ts
  webapp/channels/src/components/common/hooks/usePrefixedIds.ts
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/new_search/extension_suggestions.test.tsx
  webapp/channels/src/components/new_search/extension_suggestions.tsx
  webapp/channels/src/components/post_profile_picture/post_profile_picture.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/shared_user_indicator.test.tsx
  webapp/channels/src/components/shared_user_indicator.tsx
  webapp/channels/src/components/status_icon.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.test.tsx
  webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  webapp/channels/src/components/suggestion/channel_mention_provider.tsx
  webapp/channels/src/components/suggestion/command_provider/__snapshots__/command_provider.test.tsx.snap
  webapp/channels/src/components/suggestion/command_provider/command_provider.test.tsx
  webapp/channels/src/components/suggestion/command_provider/command_provider.tsx
  webapp/channels/src/components/suggestion/emoticon_provider.tsx
  webapp/channels/src/components/suggestion/generic_channel_provider.tsx
  webapp/channels/src/components/suggestion/generic_user_provider.tsx
  webapp/channels/src/components/suggestion/search_channel_suggestion/__snapshots__/search_channel_suggestion.test.tsx.snap
  webapp/channels/src/components/suggestion/search_channel_suggestion/search_channel_suggestion.test.tsx
  webapp/channels/src/components/suggestion/search_channel_suggestion/search_channel_suggestion.tsx
  webapp/channels/src/components/suggestion/search_channel_with_permissions_provider.tsx
  webapp/channels/src/components/suggestion/search_user_provider.tsx
  webapp/channels/src/components/suggestion/suggestion.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  webapp/channels/src/components/widgets/icons/status_away_icon.tsx
  webapp/channels/src/components/widgets/icons/status_dnd_icon.tsx
  webapp/channels/src/components/widgets/icons/status_offline_icon.tsx
  webapp/channels/src/components/widgets/icons/status_online_icon.tsx
  webapp/channels/src/i18n/en.json
  webapp/patches/dom-accessibility-api+0.5.16.patch
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33651 [MM-63579] Missing status indicator in compact display mode
  webapp/channels/src/components/post_profile_picture/post_profile_picture.tsx
  webapp/channels/src/components/profile_picture/index.tsx
  webapp/channels/src/components/widgets/users/avatar/avatar.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#33717 Automated cherry pick of #33651
  webapp/channels/src/components/post_profile_picture/post_profile_picture.tsx
  webapp/channels/src/components/profile_picture/index.tsx
  webapp/channels/src/components/widgets/users/avatar/avatar.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#33722 Automated cherry pick of #33658
  webapp/channels/src/components/advanced_text_editor/priority_labels/priority_labels.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33728 Automated cherry pick of #33545
  server/channels/app/oauth.go
  server/channels/app/oauth_test.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/channels/web/oauth.go
  server/channels/web/saml.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33525 Flag post UI
  webapp/channels/src/components/dot_menu/dot_menu.scss
  webapp/channels/src/components/dot_menu/dot_menu.test.tsx
  webapp/channels/src/components/dot_menu/dot_menu.tsx
  webapp/channels/src/components/dot_menu/index.ts
  webapp/channels/src/components/flag_message_modal/flag_post_modal.scss
  webapp/channels/src/components/flag_message_modal/flag_post_modal.test.tsx
  webapp/channels/src/components/flag_message_modal/flag_post_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/action_types/index.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/index.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/content_flagging.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/teams.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/content_flagging.ts
  webapp/platform/types/src/store.ts
Labels: 2: Dev Review, release-note-none

#33746 Automated cherry pick of #33528
  api/v4/source/system.yaml
  server/channels/api4/system.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/license_settings/index.ts
  webapp/channels/src/components/admin_console/license_settings/license_settings.scss
  webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition.scss
  webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33671 MM-51230 Remove unused react-contextmenu dependency
  NOTICE.txt
  webapp/channels/package.json
  webapp/channels/src/sass/layout/_markdown.scss
  webapp/channels/src/sass/layout/_sidebar-left.scss
  webapp/package-lock.json
  webapp/package.json
Labels: 4: Reviews Complete, release-note-none

#33678 narrow paths to trigger (server|webapp)-ci
  .github/workflows/server-ci.yml
  .github/workflows/webapp-ci.yml
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#33605 MM-64807: Deprecate format parameter in client config endpoint
  api/v4/source/system.yaml
  e2e-tests/playwright/lib/src/flag.ts
  e2e-tests/playwright/lib/src/global_setup.ts
  server/channels/api4/config.go
  server/channels/api4/config_local.go
  server/channels/api4/config_test.go
  server/cmd/mmctl/client/client.go
  server/cmd/mmctl/commands/import.go
  server/cmd/mmctl/commands/import_test.go
  server/cmd/mmctl/mocks/client_mock.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note

#33756 Fix CI concurrency group evaluation error for master builds
  .github/workflows/server-ci.yml
  .github/workflows/webapp-ci.yml
Labels: release-note-none, E2E/Overridden

#33749 MM-65088: Replace x/crypto/pbkdf2 with crypto/pbkdf2
  server/public/model/remote_cluster.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#33764 Automated cherry pick of #33609
  server/channels/app/slack.go
  server/platform/services/slackimport/slackimport.go
  server/platform/services/slackimport/slackimport_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33767 Automated cherry pick of #33612
  webapp/channels/src/actions/notification_actions.tsx
  webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
  webapp/channels/src/components/post_view/message_attachments/action_menu/action_menu.tsx
  webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx
  webapp/platform/types/src/integration_actions.ts
  webapp/platform/types/src/message_attachments.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33745 Add support for ent adv to Cloud, fix some broken windows
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/cloud_trial_banner.tsx
  webapp/channels/src/components/admin_console/billing/billing_summary/billing_summary.tsx
  webapp/channels/src/components/admin_console/billing/plan_details/feature_list.tsx
  webapp/channels/src/components/admin_console/billing/plan_details/index.tsx
  webapp/channels/src/components/admin_console/billing/plan_details/plan_details.tsx
  webapp/channels/src/components/admin_console/billing/plan_details/plan_pricing.scss
  webapp/channels/src/components/admin_console/billing/plan_details/plan_pricing.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#32170 Mm 64498 - create base code for channel settings modal
  server/channels/api4/access_control.go
  server/channels/api4/access_control_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/channel_settings_modal/__snapshots__/channel_settings_access_rules_tab.test.tsx.snap
  webapp/channels/src/components/channel_settings_modal/channel_settings_access_rules_tab.scss
  webapp/channels/src/components/channel_settings_modal/channel_settings_access_rules_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_access_rules_tab.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/selectors/general.ts
  webapp/platform/types/src/config.ts
Labels: 2: Dev Review, Setup Cloud Test Server, QA - Review Done, release-note-none

#33761 Remove dependency on Axios following Compass removal
  webapp/channels/package.json
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#33760 Prepackage playbooks v2.4.0
  server/Makefile
Labels: 2: Dev Review, release-note

#33776 Automated cherry pick of #31319
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#33607 MM-64978 Implement differentiated page sizes for auto loading vs scroll loading
  webapp/channels/src/actions/views/channel.ts
  webapp/channels/src/components/post_view/post_list/post_list.test.tsx
  webapp/channels/src/components/post_view/post_list/post_list.tsx
Labels: 4: Reviews Complete, QA - Review Done, release-note-none

#33672 [CLD-9487] Support for Entry + updates to Edition & License screen
  server/channels/app/platform/license.go
  server/channels/app/server.go
  server/einterfaces/license.go
  server/einterfaces/mocks/LicenseInterface.go
  server/public/model/feature_flags.go
  server/public/model/license.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.test.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.scss
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/common/hooks/useGetFeatureFlagValue.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/subscription.ts
Labels: Setup Cloud Test Server, release-note-none

#33759 add Node to mattermost-build-server
  .github/workflows/build-server-image.yml
  server/build/Dockerfile.buildenv
  server/build/Dockerfile.buildenv-fips
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#31323 MM-64518: Update Playbooks license requirements from Enterprise to Professional+ and unprepackage playbooks v1
  server/Makefile
  server/channels/api4/plugin_test.go
  server/channels/app/plugin.go
Labels: 4: Reviews Complete, Docs/Needed, QA - Review Done, release-note

#33679 consolidate go version computation
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci.yml
  .github/workflows/server-test-template.yml
  server/Makefile
Labels: release-note-none
