Repository mattermost/mattermost, pull requests merged in 2025-06, with the labels that each got.

#31125 [ABAC - Table Editor] Improvements on table editor and review feedback
  server/channels/api4/access_control.go
  server/channels/app/access_control.go
  server/channels/app/access_control_test.go
  server/channels/app/channel.go
  server/channels/app/channels.go
  server/channels/store/sqlstore/access_control_policy_store.go
  server/channels/store/storetest/access_control_policy_store.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/components/admin_console/access_control/editors/cel_editor/editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/shared.scss
  webapp/channels/src/components/admin_console/access_control/editors/shared.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/attribute_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/multi_value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/operator_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/selector_menus.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/single_value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_row.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/values_editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/values_editor.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/index.ts
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.scss
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.test.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/access_control.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#30899 [MM-63944] fix channel header color
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, AutoMerge, release-note, E2E/Run

#31227 Automated cherry pick of #31178
  e2e-tests/cypress/tests/integration/channels/channel/channel_settings_menu_permissions_spec.ts
  webapp/channels/src/components/channel_header_menu/menu_items/channel_settings_menu.tsx
  webapp/channels/src/selectors/views/channel_settings.test.ts
  webapp/channels/src/selectors/views/channel_settings.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31100 Move to library archives
  NOTICE.txt
  server/go.mod
  server/go.sum
  server/platform/services/docextractor/archive.go
Labels: release-note-none

#31261 Automated cherry pick of #31163
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31262 Bump shared db pool size in store for parallel tests
  server/channels/store/sqlstore/store_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#31253 Automated cherry pick of #31213
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/operator_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/channels/src/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/platform/components/package.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31256 [ABAC - Table Editor] Improvements on table editor and review feedbac…
  server/channels/api4/access_control.go
  server/channels/app/access_control.go
  server/channels/app/access_control_test.go
  server/channels/app/channel.go
  server/channels/app/channels.go
  server/channels/store/sqlstore/access_control_policy_store.go
  server/channels/store/storetest/access_control_policy_store.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/components/admin_console/access_control/editors/cel_editor/editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/shared.scss
  webapp/channels/src/components/admin_console/access_control/editors/shared.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/attribute_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/multi_value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/operator_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/selector_menus.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/single_value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_row.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/value_selector_menu.tsx
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/values_editor.scss
  webapp/channels/src/components/admin_console/access_control/editors/table_editor/values_editor.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
  webapp/channels/src/components/admin_console/access_control/policy_details/index.ts
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.scss
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.test.tsx
  webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/access_control.ts
  webapp/platform/client/src/client4.ts
Labels: release-note-none

#29414 [MM-53650] Add disable emoticon rendering setting to webapp
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  webapp/channels/src/components/post_markdown/index.ts
  webapp/channels/src/components/post_markdown/post_markdown.test.tsx
  webapp/channels/src/components/post_markdown/post_markdown.tsx
  webapp/channels/src/components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  webapp/channels/src/components/user_settings/display/index.ts
  webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/__snapshots__/render_emoticons_as_emoji.test.tsx.snap
  webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/index.ts
  webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.test.tsx
  webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.test.tsx
  webapp/channels/src/components/user_settings/display/user_settings_display.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/preferences.ts
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/emoticons.test.tsx
  webapp/channels/src/utils/emoticons.tsx
  webapp/channels/src/utils/text_formatting.test.ts
  webapp/channels/src/utils/text_formatting.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor, E2E/Overridden

#31274 Automated cherry pick of #31269
  server/public/model/feature_flags.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31187 Remove in-product pricing modal
  server/channels/api4/cloud.go
  server/channels/api4/cloud_test.go
  webapp/channels/src/actions/hosted_customer.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/index.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/limits.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.scss
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.test.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.tsx
  webapp/channels/src/components/admin_console/billing/plan_details/plan_details.tsx
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_export/upgrade_export_data_modal.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_profile.tsx
  webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  webapp/channels/src/components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  webapp/channels/src/components/at_plan_mention/at_plan_mention.test.tsx
  webapp/channels/src/components/at_plan_mention/index.tsx
  webapp/channels/src/components/center_message_lock/index.tsx
  webapp/channels/src/components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  webapp/channels/src/components/common/hooks/useCWSAvailabilityCheck.ts
  webapp/channels/src/components/common/hooks/useGetSelfHostedProducts.ts
  webapp/channels/src/components/common/hooks/useOpenPricingModal.ts
  webapp/channels/src/components/common/hooks/useShowAdminLimitReached.ts
  webapp/channels/src/components/common/hooks/use_external_link.ts
  webapp/channels/src/components/confirm_modal.tsx
  webapp/channels/src/components/feature_restricted_modal/feature_restricted_modal.tsx
  webapp/channels/src/components/file_limit_sticky_banner/index.tsx
  webapp/channels/src/components/global_header/right_controls/plan_upgrade_button/index.tsx
  webapp/channels/src/components/pricing_modal/building.svg.tsx
  webapp/channels/src/components/pricing_modal/card.tsx
  webapp/channels/src/components/pricing_modal/contact_sales_cta.tsx
  webapp/channels/src/components/pricing_modal/content.scss
  webapp/channels/src/components/pricing_modal/content.tsx
  webapp/channels/src/components/pricing_modal/index.tsx
  webapp/channels/src/components/pricing_modal/pricing_modal.scss
  webapp/channels/src/components/pricing_modal/self_hosted_content.tsx
  webapp/channels/src/components/pricing_modal/start_trial_caution.tsx
  webapp/channels/src/components/pricing_modal/starter_disclaimer_cta.tsx
  webapp/channels/src/components/pricing_modal/tada.svg.tsx
  webapp/channels/src/components/search_results/search_limits_banner.tsx
  webapp/channels/src/components/three_days_left_trial_modal/three_days_left_trial_modal.tsx
  webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.tsx
  webapp/channels/src/components/widgets/menu/menu_items/useWords.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/general.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/general.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/hosted_customer.ts
  webapp/channels/src/packages/mattermost-redux/src/store/initial_state.ts
  webapp/channels/src/plugins/export.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/general.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#28122 MM-60200 Fix for Plugin Dialog with wrong channel ID.
  webapp/channels/src/actions/command.ts
  webapp/channels/src/actions/integration_actions.test.ts
  webapp/channels/src/actions/integration_actions.tsx
  webapp/channels/src/components/interactive_dialog/index.ts
  webapp/channels/src/packages/mattermost-redux/src/action_types/integrations.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/integrations.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/integrations.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/integrations.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/integrations.ts
  webapp/platform/types/src/integrations.ts
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#31271 [MM-64402] `release-10.6` cherry-pick
  server/channels/app/import.go
  server/channels/app/import_functions.go
  server/channels/app/import_test.go
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/cmd/mmctl/commands/import_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#31273 [MM-64402] `release-9.11` cherry-pick
  server/channels/app/import.go
  server/channels/app/import_functions.go
  server/channels/app/import_test.go
  server/channels/app/imports/import_validators.go
  server/channels/app/imports/import_validators_test.go
  server/cmd/mmctl/commands/import_test.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#31197 [MM-64405] continously make syntax check
  webapp/channels/src/components/admin_console/access_control/editors/cel_editor/editor.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#31250 MM-63411 Don't focus thread textbox automatically when it has a draft
  e2e-tests/cypress/tests/support/chai.d.ts
  e2e-tests/cypress/tests/support/chai.ts
  e2e-tests/playwright/lib/src/browser_context.ts
  e2e-tests/playwright/lib/src/ui/pages/index.ts
  e2e-tests/playwright/lib/src/ui/pages/threads.ts
  e2e-tests/playwright/specs/functional/channels/threads/threads_list.spec.ts
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31057 Ignored email from client search
  webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note, E2E/Overridden

#31283 Automated cherry pick of #31276
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31284 Automated cherry pick of #31276
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31314 Automated cherry pick of #31068
  server/channels/app/webhook.go
  server/channels/app/webhook_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31132 MM-61450 fix errcheck issue in server/channel/app/permissions_test.go
  server/.golangci.yml
  server/channels/app/permissions_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#31321 Cherry pick on 9.11: bump playbooks 1.41.1 (#31276)
  server/Makefile
Labels: Docs/Not Needed, release-note-none

#31277 MM-64488 Enable from: filter support in cross-team search
  server/channels/store/searchtest/post_layer.go
  server/channels/store/sqlstore/post_store.go
Labels: 2: Dev Review, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#30728 [MM-63760] Only partially sanitize DB datasources for Support Packet
  server/channels/app/config.go
  server/channels/app/platform/config.go
  server/channels/app/platform/support_packet.go
  server/channels/app/platform/support_packet_test.go
  server/config/database.go
  server/config/diff.go
  server/config/diff_test.go
  server/public/model/config.go
  server/public/model/config_test.go
  server/public/utils/sql/sql_utils.go
  server/public/utils/sql/sql_utils_test.go
Labels: QA - Deferred, release-note

#31278 [MM-64296] Help for AI: Respect env overrides for consoleLevel
  server/channels/api4/apitestlib.go
  server/channels/api4/apitestlib_test.go
  server/channels/utils/subpath.go
Labels: 4: Reviews Complete, release-note-none

#30451 S3store/image type
  server/platform/shared/filestore/s3store.go
  server/platform/shared/filestore/s3store_test.go
Labels: 4: Reviews Complete, release-note, Contributor, E2E/Overridden

#31316 Improve claude code to run bash commands
  .github/workflows/claude.yml
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#31348 Translations update from Mattermost Weblate
  server/i18n/de.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, E2E/Overridden

#31165 [MM-64360] Data retention: optionally preserve pinned posts
  server/channels/app/syncables_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_member_history_store.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/sqlstore/thread_store.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_member_history_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelMemberHistoryStore.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/mocks/ThreadStore.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/preference_store.go
  server/channels/store/storetest/reaction_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/public/model/config.go
  server/public/model/data_retention_policy.go
  webapp/channels/src/components/error_page/error_message.tsx
  webapp/channels/src/components/error_page/error_title.tsx
  webapp/channels/src/components/permalink_view/actions.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: release-note-none, E2E/Overridden

#31133 [MM-63578] Fix support packet caching issue
  server/channels/api4/system.go
  server/channels/api4/system_test.go
  server/platform/shared/web/files.go
Labels: 4: Reviews Complete, release-note

#31298 Upgrading board prepackaged version to v9.1.3
  server/Makefile
Labels: 2: Dev Review, release-note-none

#31299 Updated board prepackaged version to 9.1.3
  server/Makefile
Labels: 2: Dev Review, release-note-none

#31300 Upgraded board prepackaged version to 9.1.3
  server/Makefile
Labels: 2: Dev Review, release-note-none

#31366 MM-64544 Fix width of threads textbox at all screen sizes
  webapp/channels/src/components/threading/global_threads/global_threads.scss
Labels: 4: Reviews Complete, release-note

#31035 MM-63285: Add property field methods to plugin API
  server/channels/app/app.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_properties_test.go
  server/public/model/property_field.go
  server/public/model/property_field_test.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/plugintest/api.go
  server/public/pluginapi/client.go
  server/public/pluginapi/property.go
  server/public/pluginapi/property_test.go
Labels: 3: Security Review, release-note, E2E/Overridden

#31377 Automated cherry pick of #31298
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31306 Updated board prepackaged version to v9.1.3
  server/Makefile
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, AutoMerge, release-note-none

#31382 Update go toolchain version in FIPS 10.8
  server/build/Dockerfile.buildenv
  server/go.mod
  server/public/go.mod
Labels: release-note-none

#30866 Automatic channel category sorting
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000138_add_default_category_name_to_channel.down.sql
  server/channels/db/migrations/mysql/000138_add_default_category_name_to_channel.up.sql
  server/channels/db/migrations/postgres/000138_add_default_category_name_to_channel.down.sql
  server/channels/db/migrations/postgres/000138_add_default_category_name_to_channel.up.sql
  server/channels/store/sqlstore/channel_store.go
  server/config/client.go
  server/public/model/channel.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/channels.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31387 [MM-63057][MM-63003] Set aria-hidden on decorative icons
  webapp/channels/src/components/new_search/search_hint.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/widgets/icons/fa_edit_icon.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#31386 [MM-62987] Fix timestamp not actually being read
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#31370 [MM-61562] Ensure emoji picker focus returns to button when not selecting an emoji
  webapp/channels/src/components/advanced_text_editor/use_editor_emoji_picker.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31279 [MM-63041] Convert many inputs to the Input component, replace clientError with more correct client-side validation that conforms to the input
  e2e-tests/cypress/tests/integration/channels/account_settings/account_settings_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/email_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/profile/username_spec.ts
  e2e-tests/cypress/tests/integration/channels/account_settings/security/password_spec.ts
  e2e-tests/playwright/lib/src/ui/components/channels/profile_modal.ts
  e2e-tests/playwright/specs/functional/channels/custom_profile_attributes/user_settings.spec.ts
  webapp/channels/src/components/__snapshots__/setting_item_max.test.tsx.snap
  webapp/channels/src/components/setting_item_max.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/sass/routes/_settings.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note, 1. UX Review, E2E/Overridden

#31383 [MM-64462] `release-10.5` cherry-pick
  server/go.mod
  server/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#31385 [MM-64462] `release-10.8` cherry-pick
  server/go.mod
  server/go.sum
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#31390 [MM-63027] Add status region for the channel filter dropdown
  webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap
  webapp/channels/src/components/searchable_channel_list.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31396 [MM-64425] Add configurable account deletion link
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  webapp/channels/src/components/user_settings/security/index.ts
  webapp/channels/src/components/user_settings/security/user_settings_security.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_settings.scss
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31389 [MM-61623][MM-61632][MM-61635] Remove min-width for the RHS when window size <400px
  webapp/channels/src/sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31353 [MM-63045] Add root component to read arbitrary text globally, ensure thread menu reads its actions on execution
  webapp/channels/src/actions/views/root.ts
  webapp/channels/src/components/readout/readout.test.tsx
  webapp/channels/src/components/readout/readout.tsx
  webapp/channels/src/components/root/root.tsx
  webapp/channels/src/components/threading/global_threads/thread_menu/thread_menu.test.tsx
  webapp/channels/src/components/threading/global_threads/thread_menu/thread_menu.tsx
  webapp/channels/src/hooks/useReadout.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/reducers/views/index.ts
  webapp/channels/src/reducers/views/readout.ts
  webapp/channels/src/types/store/views.ts
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#31403 Adds support for GMs in shared channels
  server/channels/app/channel.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/post_metadata_test.go
  server/channels/app/post_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/channel_layer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/slackimport/slackimport.go
Labels: QA - Deferred, 3: Security Review, release-note, E2E/Overridden

#31415 Automated cherry pick of #31403
  server/channels/app/channel.go
  server/channels/app/import_functions.go
  server/channels/app/import_functions_test.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/post_metadata_test.go
  server/channels/app/post_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/searchlayer/channel_layer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/slackimport/slackimport.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31404 [MM-64501] Upgrade to v5.0.3 version of web-vitals
  webapp/channels/package.json
  webapp/channels/src/utils/performance_telemetry/reporter.ts
  webapp/package-lock.json
Labels: 4: Reviews Complete, QA - Deferred, release-note-none, E2E/Overridden

#31029 [MM-63717] LDAP Wizard skeleton
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/index.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_boolean_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_custom_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_dropdown_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_file_upload_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_jobs_table_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/form_error.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/admin_console_index.test.tsx
Labels: 4: Reviews Complete, release-note-none

#30918 MM-62751: [Shared Channels] Allow remote users to be discoverable in the create DM/GM modal
  server/channels/app/shared_channel_global_user_sync_self_referential_test.go
  server/channels/app/shared_channel_sync_self_referential_utils_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000139_remoteclusters_add_last_global_user_sync_at.down.sql
  server/channels/db/migrations/mysql/000139_remoteclusters_add_last_global_user_sync_at.up.sql
  server/channels/db/migrations/postgres/000139_remoteclusters_add_last_global_user_sync_at.down.sql
  server/channels/db/migrations/postgres/000139_remoteclusters_add_last_global_user_sync_at.up.sql
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/remote_cluster_store.go
  server/channels/store/sqlstore/user_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/RemoteClusterStore.go
  server/channels/store/storetest/shared_channel_store.go
  server/channels/store/storetest/user_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/remotecluster/service.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/config.go
  server/public/model/feature_flags.go
  server/public/model/remote_cluster.go
  server/public/model/user_get.go
Labels: QA - Review Done, 3: Security Review, release-note-none

#31190 [MM-64296] Add test connection for connection settings panel
  api/v4/source/definitions.yaml
  api/v4/source/ldap.yaml
  server/channels/api4/ldap.go
  server/channels/app/ldap.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapDiagnosticInterface.go
  server/i18n/en.json
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_boolean_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_file_upload_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_helpers.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/components/admin_console/request_button/request_button.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note

#31363 Add dispatch build
  .github/workflows/dispatch-server-builder-image.yml
Labels: release-note-none, E2E/Overridden

#31280 [MM-64480] Refactor Admin Definition
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_definition_helpers.tsx
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
Labels: 4: Reviews Complete, release-note-none

#31286 [MM-63765] LDAP Wizard: User filter expandable section
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_expandable_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_helpers.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#31426 Automated cherry pick of #31354
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user.go
  server/channels/app/user_limits_test.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/license.go
  webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31312 [MM-64482] LDAP Wizard - Test User filters
  api/v4/source/definitions.yaml
  api/v4/source/ldap.yaml
  server/channels/api4/ldap.go
  server/channels/app/ldap.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapDiagnosticInterface.go
  server/public/model/ldap.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note-none

#31355 [MM-64512] - Test user filters UI
  api/v4/source/definitions.yaml
  server/public/model/ldap.go
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/admin.ts
Labels: 4: Reviews Complete, release-note

#31373 [MM-64536] LDAP Wizard: Test user attributes
  api/v4/source/definitions.yaml
  api/v4/source/ldap.yaml
  server/channels/api4/ldap.go
  server/channels/app/ldap.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapDiagnosticInterface.go
  server/public/model/ldap.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/admin.ts
Labels: 4: Reviews Complete, release-note-none

#30976 MM-52600: [Shared Channels] Shared channels do not sync channel membership
  server/channels/app/channel.go
  server/channels/app/channel_test.go
  server/channels/app/platform/shared_channel_service_iface.go
  server/channels/app/shared_channel_membership_sync_self_referential_test.go
  server/channels/app/shared_channel_service_iface.go
  server/channels/app/shared_channel_sync_self_referential_utils_test.go
  server/channels/app/shared_channel_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000140_add_lastmemberssyncat_to_sharedchannelremotes.down.sql
  server/channels/db/migrations/mysql/000140_add_lastmemberssyncat_to_sharedchannelremotes.up.sql
  server/channels/db/migrations/postgres/000140_add_lastmemberssyncat_to_sharedchannelremotes.down.sql
  server/channels/db/migrations/postgres/000140_add_lastmemberssyncat_to_sharedchannelremotes.up.sql
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/shared_channel_store.go
  server/channels/store/sqlstore/shared_channel_store_membership.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/storetest/mocks/SharedChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/platform/services/remotecluster/service.go
  server/platform/services/sharedchannel/channelinvite.go
  server/platform/services/sharedchannel/channelinvite_test.go
  server/platform/services/sharedchannel/membership.go
  server/platform/services/sharedchannel/membership_recv.go
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/service_api.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/channel.go
  server/public/model/config.go
  server/public/model/feature_flags.go
  server/public/model/shared_channel.go
Labels: 2: Dev Review, QA - Review Done, 3: Security Review, release-note-none, E2E/Overridden

#31374 [MM-64550] LDAP Wizard: Test user attributes UI
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note

#31375 [MM-64551] LDAP Wizard: Test group attributes
  api/v4/source/ldap.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_guest_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_setting_spec.ts
  e2e-tests/cypress/tests/support/ldap_commands.js
  e2e-tests/cypress/tests/utils/admin_console.js
  server/channels/api4/ldap.go
  server/channels/app/ldap.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapDiagnosticInterface.go
  server/i18n/en.json
  server/public/model/ldap.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_expandable_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, release-note-none

#30736 MM-57326: [Shared Channels] Message priority, acknowledgement and persistent notifications need to be synced
  server/channels/api4/shared_channel_metadata_test.go
  server/channels/api4/shared_channel_test_utils.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/post_acknowledgements_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql
  server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql
  server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql
  server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/post_acknowledgements_store.go
  server/channels/store/sqlstore/post_priority_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostAcknowledgementStore.go
  server/channels/store/storetest/mocks/PostPriorityStore.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/post_acknowledgement.go
  server/public/model/shared_channel.go
Labels: 2: Dev Review, QA - Review Done, 3: Security Review, release-note-none, E2E/Overridden

#30903 MM-61437: [Shared Channels] Disable DM button from profile for shared channel user
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, release-note-none, E2E/Overridden

#31564 Automated cherry pick of #30903
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_other_user_row.tsx
  webapp/channels/src/sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31330 MM-61382 Date/Time Picker Input Fix and Refactor
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_3_spec.ts
  e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_4_spec.ts
  e2e-tests/cypress/tests/integration/channels/status/status_dnd_1_spec.js
  e2e-tests/playwright/lib/src/ui/components/channels/schedule_message_modal.ts
  e2e-tests/playwright/specs/functional/channels/scheduled_messages/scheduled_messages.spec.ts
  webapp/channels/src/components/custom_status/__snapshots__/date_time_input.test.tsx.snap
  webapp/channels/src/components/custom_status/custom_status.scss
  webapp/channels/src/components/custom_status/custom_status_modal.tsx
  webapp/channels/src/components/custom_status/date_time_input.test.tsx
  webapp/channels/src/components/date_picker/date_picker.scss
  webapp/channels/src/components/date_picker/date_picker.tsx
  webapp/channels/src/components/date_time_picker_modal/date_time_picker_modal.tsx
  webapp/channels/src/components/date_time_picker_modal/style.scss
  webapp/channels/src/components/datetime_input/__snapshots__/datetime_input.test.tsx.snap
  webapp/channels/src/components/datetime_input/datetime_input.test.tsx
  webapp/channels/src/components/datetime_input/datetime_input.tsx
  webapp/channels/src/components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  webapp/channels/src/components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  webapp/channels/src/components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_inputs.scss
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#31365 MM-64372 Fix onboarding checklist being rendered behind team sidebar
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_popover.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31398 [MM-62988] Add username prop to multi-avatar component
  webapp/channels/src/components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  webapp/channels/src/components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
  webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  webapp/channels/src/components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  webapp/channels/src/components/widgets/users/avatars/avatars.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#31582 Reduce Codecov spam
  .github/codecov.yml
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31406 [MM-63021] Modify input to have min/max length validation work the same as the validation around required, replace Create Team input with Input component
  webapp/channels/src/components/create_team/components/__snapshots__/display_name.test.tsx.snap
  webapp/channels/src/components/create_team/components/display_name.test.tsx
  webapp/channels/src/components/create_team/components/display_name.tsx
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/__snapshots__/input.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31641 Automated cherry pick of #31362
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/storetest/channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31566 Automated cherry pick of #31425
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
  webapp/channels/src/components/announcement_bar/purchase_link/purchase_link.tsx
  webapp/channels/src/components/announcement_bar/renewal_link/renew_link.scss
  webapp/channels/src/components/announcement_bar/renewal_link/renewal_link.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31644 Automated cherry pick of #30736
  server/channels/api4/shared_channel_metadata_test.go
  server/channels/api4/shared_channel_test_utils.go
  server/channels/app/platform/shared_channel_notifier.go
  server/channels/app/post.go
  server/channels/app/post_acknowledgements.go
  server/channels/app/post_acknowledgements_test.go
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql
  server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql
  server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql
  server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/post_acknowledgements_store.go
  server/channels/store/sqlstore/post_priority_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostAcknowledgementStore.go
  server/channels/store/storetest/mocks/PostPriorityStore.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/platform/services/sharedchannel/mock_AppIface_test.go
  server/platform/services/sharedchannel/service.go
  server/platform/services/sharedchannel/sync_recv.go
  server/platform/services/sharedchannel/sync_send.go
  server/platform/services/sharedchannel/sync_send_remote.go
  server/public/model/post_acknowledgement.go
  server/public/model/shared_channel.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31647 MANUAL CHERRYPICK: Fix getAllChannels api not returning DMs/GMs (#31362)
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/storetest/channel_store.go
Labels: Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#31413 Automated cherry pick of #31002
  webapp/channels/src/components/login/login.tsx
  webapp/channels/src/utils/embed.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31623 Automated cherry pick of #31417
  api/v4/source/definitions.yaml
  api/v4/source/ldap.yaml
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_guest_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_setting_spec.ts
  e2e-tests/cypress/tests/support/ldap_commands.js
  e2e-tests/cypress/tests/utils/admin_console.js
  e2e-tests/playwright/specs/functional/channels/scheduled_messages/scheduled_messages.spec.ts
  server/channels/api4/ldap.go
  server/channels/app/ldap.go
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapDiagnosticInterface.go
  server/i18n/en.json
  server/public/model/ldap.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_definition_helpers.tsx
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/index.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_boolean_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_custom_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_dropdown_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_expandable_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_file_upload_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_helpers.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_jobs_table_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
  webapp/channels/src/components/admin_console/request_button/request_button.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/common/hooks/useSectionNavigation.ts
  webapp/channels/src/components/form_error.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/channels/src/utils/admin_console_index.test.tsx
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/admin.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none, E2E/Overridden

#31651 Fix delete button aria-label on User Groups list modal
  webapp/channels/src/components/view_user_group_modal/view_user_group_list_item/view_user_group_list_item.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note, E2E/Overridden

#31629 feat: Replace 5% grace period with configurable ExtraUsers field
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_limits_test.go
  server/public/model/license.go
Labels: 4: Reviews Complete, CherryPick/Done, QA - Review Not Required, release-note, E2E/Overridden

#31657 Automated cherry pick of #31629
  server/channels/app/limits.go
  server/channels/app/limits_test.go
  server/channels/app/user_limits_test.go
  server/public/model/license.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31409 [MM-63007][MM-63004][MM-63020][MM-63009][MM-63008] More accessibility fixes around Search
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_nav_diff_regions_spec.js
  e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_reaction_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_search_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archived_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/archived_channel/archived_leave_channel_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel/open_rhs_coming_from_system_console_spec.ts
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts
  e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_l_set_message_focus_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/channel_and_posts_links_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/permalink_message_edit_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/post_pre_header_spec.js
  e2e-tests/cypress/tests/integration/channels/search/clear_input_spec.js
  e2e-tests/cypress/tests/integration/channels/search/post_search_display_spec.js
  e2e-tests/cypress/tests/integration/channels/search/results_post_spec.js
  e2e-tests/cypress/tests/integration/channels/search/search_group_message_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/input_spec.js
  e2e-tests/cypress/tests/integration/channels/search_filter/negative_spec.js
  e2e-tests/cypress/tests/support/ui/global_header.js
  e2e-tests/playwright/lib/src/index.ts
  e2e-tests/playwright/lib/src/ui/components/channels/search_box.ts
  e2e-tests/playwright/lib/src/ui/components/index.ts
  e2e-tests/playwright/lib/src/ui/pages/channels.ts
  e2e-tests/playwright/specs/functional/channels/search/search_box_clear_button.spec.ts
  e2e-tests/playwright/specs/functional/channels/search/search_box_suggestions.spec.ts
  webapp/channels/src/components/new_search/new_search.tsx
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/components/new_search/search_box_input.tsx
  webapp/channels/src/components/new_search/search_box_suggestions.tsx
  webapp/channels/src/components/new_search/search_box_type_selector.tsx
  webapp/channels/src/components/quick_input/quick_input.tsx
  webapp/channels/src/components/search/search.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31371 [MM-61626] Replace most uses of <header> with <div> where not needed
  webapp/channels/src/components/admin_console/secure_connections/controls.tsx
  webapp/channels/src/components/admin_console/system_properties/controls.tsx
  webapp/channels/src/components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_header.test.tsx.snap
  webapp/channels/src/components/drafts/panel/panel_header.tsx
  webapp/channels/src/components/sidebar/sidebar_header/sidebar_header.tsx
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
  webapp/channels/src/components/widgets/header/__snapshots__/header.test.tsx.snap
  webapp/channels/src/components/widgets/header/header.tsx
  webapp/channels/src/components/widgets/modals/components/modal_header.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#31047 [MM-63035][MM-63970][MM-63978][MM-64028][MM-64019][MM-64022][MM-64026][MM-64023][MM-61625] Create User Group modal accessibility fixes
  e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.ts
  webapp/channels/src/components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.tsx.snap
  webapp/channels/src/components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.tsx.snap
  webapp/channels/src/components/add_user_to_group_multiselect/__snapshots__/add_user_to_group_multiselect.test.tsx.snap
  webapp/channels/src/components/add_user_to_group_multiselect/add_user_to_group_multiselect.tsx
  webapp/channels/src/components/add_users_to_team_modal/__snapshots__/add_users_to_team_modal.test.tsx.snap
  webapp/channels/src/components/admin_console/billing/company_info_edit.scss
  webapp/channels/src/components/admin_console/system_roles/system_role/add_users_to_role_modal/__snapshots__/add_users_to_role_modal.test.tsx.snap
  webapp/channels/src/components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.scss
  webapp/channels/src/components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  webapp/channels/src/components/create_user_groups_modal/__snapshots__/create_user_groups_modal.test.tsx.snap
  webapp/channels/src/components/create_user_groups_modal/create_user_groups_modal.tsx
  webapp/channels/src/components/multiselect/__snapshots__/multiselect.test.tsx.snap
  webapp/channels/src/components/multiselect/multiselect.tsx
  webapp/channels/src/components/multiselect/multiselect_list.tsx
  webapp/channels/src/components/seats_calculator/seats_calculator.scss
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/team_settings/team_info_tab/team_info_tab.scss
  webapp/channels/src/components/user_groups_modal/user_groups_modal.scss
  webapp/channels/src/components/widgets/inputs/input/__snapshots__/input.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/input.test.tsx
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.test.tsx
  webapp/channels/src/components/widgets/inputs/users_emails_input.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/components/_channel-invite-modal.scss
  webapp/channels/src/sass/components/_multi-select.scss
  webapp/channels/src/sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#31659 MM-64610: Restrict import upload for shared channels feature.
  server/channels/api4/remote_cluster.go
  server/i18n/en.json
Labels: release-note-none

#31654 [MM-61593] Add parameters for icon/dropdown text for the Calls button
  webapp/channels/src/components/channel_header_menu/menu_items/mobile_channel_header_plugins.tsx
  webapp/channels/src/plugins/registry.ts
Labels: 4: Reviews Complete, release-note-none

#31788 Automated cherry pick of #31659
  server/channels/api4/remote_cluster.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30886 MM-60640: [Shared Channels] Display remotes' names in Shared With tooltip
  api/v4/source/channels.yaml
  server/channels/api4/shared_channel.go
  server/channels/api4/shared_channel_remotes_test.go
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/channel_header/channel_header.test.tsx
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/channel_header/channel_header_title.test.tsx
  webapp/channels/src/components/channel_header/channel_header_title.tsx
  webapp/channels/src/components/channel_header/index.ts
  webapp/channels/src/components/shared_channel_indicator.test.tsx
  webapp/channels/src/components/shared_channel_indicator.tsx
  webapp/channels/src/components/shared_user_indicator.test.tsx
  webapp/channels/src/components/shared_user_indicator.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/components/user_profile/index.ts
  webapp/channels/src/components/user_profile/user_profile.test.tsx
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/index.ts
  webapp/channels/src/packages/mattermost-redux/src/action_types/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/index.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/shared_channels.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/shared_channels.ts
  webapp/platform/types/src/store.ts
Labels: 2: Dev Review, QA - Review Done, release-note-none, E2E/Overridden

#31328 [MM-61582][MM-61605][MM-61622][MM-63029][MM-63026][MM-63059] Mobile View accessibility fixes
  webapp/channels/src/components/browse_channels/browse_channels.scss
  webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.scss
  webapp/channels/src/components/new_channel_modal/new_channel_modal.scss
  webapp/channels/src/components/widgets/public-private-selector/public-private-selector.scss
  webapp/channels/src/sass/components/_modal.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/platform/components/src/generic_modal/generic_modal.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note, E2E/Overridden

#31789 Automated cherry pick of #30886
  api/v4/source/channels.yaml
  server/channels/api4/shared_channel.go
  server/channels/api4/shared_channel_remotes_test.go
  webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
  webapp/channels/src/components/channel_header/channel_header.test.tsx
  webapp/channels/src/components/channel_header/channel_header.tsx
  webapp/channels/src/components/channel_header/channel_header_title.test.tsx
  webapp/channels/src/components/channel_header/channel_header_title.tsx
  webapp/channels/src/components/channel_header/index.ts
  webapp/channels/src/components/shared_channel_indicator.test.tsx
  webapp/channels/src/components/shared_channel_indicator.tsx
  webapp/channels/src/components/shared_user_indicator.test.tsx
  webapp/channels/src/components/shared_user_indicator.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  webapp/channels/src/components/user_profile/index.ts
  webapp/channels/src/components/user_profile/user_profile.test.tsx
  webapp/channels/src/components/user_profile/user_profile.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/action_types/index.ts
  webapp/channels/src/packages/mattermost-redux/src/action_types/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/index.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/shared_channels.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/__tests__/shared_channels.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/shared_channels.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/shared_channels.ts
  webapp/platform/types/src/store.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31790 Automated cherry pick of #31659
  server/channels/api4/remote_cluster.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31791 Automated cherry pick of #31659
  server/channels/api4/remote_cluster.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31792 Automated cherry pick of #31659
  server/channels/api4/remote_cluster.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30949 Add server settings to further lock files on mobile
  e2e-tests/playwright/lib/src/server/default_config.ts
  e2e-tests/playwright/lib/src/ui/components/system_console/sections/system_users/mobile_security.ts
  e2e-tests/playwright/specs/functional/system_console/mobile_security.spec.ts
  server/config/client.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, Setup Cloud Test Server, release-note

#28941 Fixed errcheck issues in server/channels/app/file_test.go
  server/.golangci.yml
  server/channels/app/file_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor, E2E/Overridden

#31309 [MM-64502] Fix errcheck linter errors in channel_test.go
  server/.golangci.yml
  server/channels/api4/channel_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#31807 [MM-64639] Fix styling on thread item header
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#31064 MM-63725 Populate multiple sidebar categories at once whenever possible
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/storetest/channel_store.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#31771 Updated board prepackaged version to v9.1.4
  server/Makefile
Labels: 2: Dev Review, QA - Review Done, release-note-none

#31118 [MM-64347] Enable System Console UI for AuditSettings by default
  server/i18n/en.json
  server/public/model/config.go
  server/public/model/config_test.go
  server/public/model/feature_flags.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30848 MM-63728: simplify category store with graphql gone
  server/channels/api4/channel_category.go
  server/channels/api4/channel_category_test.go
  server/channels/app/channel.go
  server/channels/app/channel_category.go
  server/channels/app/channel_test.go
  server/channels/app/team.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/channel_store_categories.go
  server/channels/store/store.go
  server/channels/store/storetest/channel_store_categories.go
  server/channels/store/storetest/mocks/ChannelStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 2: Dev Review, LoadTest, QA - Review Not Required, release-note-none, E2E/Overridden

#31810 Automated cherry pick of #31771
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31811 Automated cherry pick of #31771
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31809 Automated cherry pick of #31771
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31219 MM-64330 - filter abac users in channel invite
  server/channels/api4/user.go
  server/channels/app/channel.go
  server/channels/app/user.go
  server/channels/app/user_test.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/user.go
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
  webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/platform/client/src/client4.ts
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none

#31649 [MM-64603] LDAP Wizard: UX and Copy
  e2e-tests/playwright/specs/functional/channels/threads/threads_list.spec.ts
  webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
  webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
Labels: CherryPick/Approved, release-note-none

#31806 Update Agents plugin to v1.2.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, E2E/Overridden

#31817 Fix tab navigation in theme settings accessibility test
  e2e-tests/playwright/specs/accessibility/channels/theme_settings.spec.ts
Labels: release-note-none, E2E/Overridden

#32071 Automated cherry pick of #31806
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#31783 [CLD-9285] Add server version and edition (team vs ent) to ExternalLink component
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/admin_console/billing/billing_history.test.tsx
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.test.tsx
  webapp/channels/src/components/common/hooks/use_external_link.ts
  webapp/channels/src/components/external_link/__snapshots__/external_link.test.tsx.snap
  webapp/channels/src/components/external_link/external_link.test.tsx
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/installed_outgoing_oauth_connections.test.tsx.snap
  webapp/channels/src/components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/team_settings/team_access_tab/open_invite.test.tsx
  webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
Labels: EETests, release-note-none, E2E/Overridden

#30914 [MM-62888] mmctl: Add compliance export list cmd
  server/cmd/mmctl/commands/compliance_export.go
  server/cmd/mmctl/commands/compliance_export_e2e_test.go
  server/cmd/mmctl/commands/compliance_export_test.go
  server/cmd/mmctl/commands/mmctl_test.go
  server/cmd/mmctl/docs/mmctl.rst
  server/cmd/mmctl/docs/mmctl_compliance_export.rst
  server/cmd/mmctl/docs/mmctl_compliance_export_list.rst
  server/cmd/mmctl/docs/mmctl_compliance_export_show.rst
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30569 [MM-63555] mmctl: Add compliance export show and cancel cmds
  server/cmd/mmctl/commands/compliance_export.go
  server/cmd/mmctl/commands/compliance_export_e2e_test.go
  server/cmd/mmctl/commands/compliance_export_test.go
  server/cmd/mmctl/docs/mmctl.rst
  server/cmd/mmctl/docs/mmctl_compliance-export.rst
  server/cmd/mmctl/docs/mmctl_compliance-export_cancel.rst
  server/cmd/mmctl/docs/mmctl_compliance-export_list.rst
  server/cmd/mmctl/docs/mmctl_compliance-export_show.rst
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#31785 Always require signatures for prepackaged plugins
  server/channels/api4/apitestlib.go
  server/channels/api4/plugin_test.go
  server/channels/app/helper_test.go
  server/channels/app/plugin.go
  server/channels/app/plugin_install.go
  server/channels/app/plugin_prepackaged_test.go
  server/channels/app/plugin_signature.go
  server/channels/app/plugin_test.go
  server/public/plugin/environment.go
Labels: Setup HA Cloud Test Server, QA - Deferred, release-note, E2E/Overridden

#30594 [MM-63557] mmctl: Add compliance export create cmd
  server/channels/api4/job.go
  server/channels/app/job.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/cmd/mmctl/commands/compliance_export.go
  server/cmd/mmctl/commands/compliance_export_e2e_test.go
  server/cmd/mmctl/commands/compliance_export_test.go
  server/cmd/mmctl/commands/export.go
  server/cmd/mmctl/commands/mmctl_test.go
  server/cmd/mmctl/docs/mmctl_compliance-export.rst
  server/cmd/mmctl/docs/mmctl_compliance-export_create.rst
  server/cmd/mmctl/docs/mmctl_compliance-export_download.rst
  server/enterprise/message_export/shared/shared.go
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
Labels: 4: Reviews Complete, release-note

#31822 Fixed styling issues with multiples banners in System Console
  e2e-tests/cypress/tests/integration/channels/enterprise/system_console/about/edition_and_license_spec.js
  webapp/channels/src/components/admin_console/license_settings/license_settings.scss
  webapp/channels/src/components/admin_console/license_settings/renew_license_card/renew_license_card.test.tsx
  webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  webapp/channels/src/components/announcement_bar/contact_sales/contact_us.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#32124 Update Agents plugin to v1.2.1
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#32154 Automated cherry pick of #31221
  server/channels/store/sqlstore/shared_channel_store.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32155 Automated cherry pick of #32124
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32156 Automated cherry pick of #32124
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32158 Automated cherry pick of #32152
  server/channels/app/channel.go
  server/platform/services/sharedchannel/channelinvite.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#31784 [CLD-9238] Direct preview user to proper team based on use case
  server/channels/api4/user.go
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx
  webapp/channels/src/components/announcement_bar/notification_permission_bar/index.tsx
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal_controller.test.tsx
  webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal_controller.tsx
  webapp/channels/src/components/cloud_preview_modal/preview_modal_content_controller.tsx
  webapp/channels/src/components/cloud_preview_modal/preview_modal_content_data.ts
Labels: release-note-none, E2E/Overridden

#32144 MM-64687: Racy tests in TestSharedChannelPostMetadataSync
  server/channels/api4/shared_channel_metadata_test.go
  server/channels/app/shared_channel_membership_sync_self_referential_test.go
Labels: 2: Dev Review, release-note-none

#32133 [MM-64491] Fix system attributes section not appearting w/o a license
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/user_attributes.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#32098 MM-64669 Fix keyboard navigation of settings sidebar
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/playwright/specs/accessibility/channels/account_settings_sidebar.spec.ts
  server/public/model/channel.go
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/sass/routes/_settings.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note

#32081 Increase line height in RHS header
  webapp/channels/src/sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#32166 Automated cherry pick of #32098
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/playwright/specs/accessibility/channels/account_settings_sidebar.spec.ts
  server/public/model/channel.go
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/sass/routes/_settings.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#32157 MM-64690 - fix channel name input label
  webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.scss
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/__snapshots__/input.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/input.scss
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/i18n/en.json
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#32418 Automated cherry pick of #32098
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
  e2e-tests/playwright/specs/accessibility/channels/account_settings_sidebar.spec.ts
  server/public/model/channel.go
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/sass/routes/_settings.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#32481 Update Agents plugin to v1.2.2
  server/Makefile
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, CherryPick/Approved, release-note

#31492 feat(function component migration): migrate QuickInput to a function component
  webapp/channels/src/components/quick_input/quick_input.test.tsx
  webapp/channels/src/components/quick_input/quick_input.tsx
  webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#30957 Fix MM64178
  server/channels/api4/channel_test.go
  server/channels/api4/team_test.go
  server/channels/app/channel.go
  server/channels/app/team.go
  server/i18n/en.json
Labels: 2: Dev Review, 3: QA Review, 3: Security Review, release-note-none
