Repository mattermost/mattermost, pull requests merged in 2025-04, with the labels that each got.

#30603 MM-63311 10.7 cherry-pick
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/group.go
  server/channels/app/plugin_api.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#30623 Automated cherry pick of #30526
  e2e-tests/cypress/tests/integration/channels/enterprise/channel/channel_groups_spec.ts
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/app/syncables.go
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30626 Automated cherry pick of #30470
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/footer.tsx
  webapp/channels/src/components/advanced_text_editor/use_submit.tsx
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/msg_typing/index.ts
  webapp/channels/src/components/msg_typing/msg_typing.test.tsx
  webapp/channels/src/components/msg_typing/msg_typing.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30462 [MM-63421] add openID Authorization API-compliant PDP interface
  server/channels/app/platform/enterprise.go
  server/channels/app/platform/service.go
  server/einterfaces/mocks/PolicyDecisionPointInterface.go
  server/einterfaces/pdp.go
  server/public/model/access_request.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30597 [MM-63428] add access control policy store
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000134_create_access_control_policies.down.sql
  server/channels/db/migrations/mysql/000134_create_access_control_policies.up.sql
  server/channels/db/migrations/postgres/000134_create_access_control_policies.down.sql
  server/channels/db/migrations/postgres/000134_create_access_control_policies.up.sql
  server/channels/store/layer_generators/main.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/retrylayer/retrylayer_test.go
  server/channels/store/sqlstore/access_control_policy_store.go
  server/channels/store/sqlstore/access_control_policy_store_test.go
  server/channels/store/sqlstore/store.go
  server/channels/store/store.go
  server/channels/store/storetest/access_control_policy_store.go
  server/channels/store/storetest/mocks/AccessControlPolicyStore.go
  server/channels/store/storetest/mocks/Store.go
  server/channels/store/storetest/store.go
  server/channels/store/timerlayer/timerlayer.go
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30601 MM-62157: Avoid SELECT * in user_store.go
  server/channels/store/sqlstore/user_store.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none

#30572 MM-62710 Ensure CommentedOn message is never missing due to unloaded data
  webapp/channels/src/components/common/hooks/useEntity.ts
  webapp/channels/src/components/common/hooks/usePost.test.ts
  webapp/channels/src/components/common/hooks/usePost.ts
  webapp/channels/src/components/common/hooks/useUser.test.ts
  webapp/channels/src/components/common/hooks/useUser.ts
  webapp/channels/src/components/post/index.test.tsx
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/post_view/commented_on/__snapshots__/commented_on.test.tsx.snap
  webapp/channels/src/components/post_view/commented_on/commented_on.test.tsx
  webapp/channels/src/components/post_view/commented_on/commented_on.tsx
  webapp/channels/src/components/post_view/commented_on/index.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
  webapp/channels/src/tests/react_testing_utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30605 MM-63620 Upgrade playwright dependencies, server config and client config types for v10.7
  e2e-tests/playwright/lib/package.json
  e2e-tests/playwright/lib/src/server/default_config.ts
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/test/package.json
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30511 MM-62696, MM-62697: CPA Ext. Types & Visibility in System Console
  server/public/model/custom_profile_attributes.go
  webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx
  webapp/channels/src/components/admin_console/system_properties/controls.tsx
  webapp/channels/src/components/admin_console/system_properties/system_properties.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_delete_modal.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.test.ts
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.ts
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.tsx
  webapp/channels/src/components/menu/menu_item_input.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/types/src/properties.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30571 [MM-63480] Remove user cache early when deactivating user
  e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts
  server/channels/app/user.go
Labels: 2: Dev Review, Setup Cloud Test Server, 3: Security Review, release-note-none, E2E/Overridden

#30317 MM-62699 Add additional property types to user profile form
  webapp/channels/src/components/channel_bookmarks/channel_bookmarks_create_modal.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/url.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/properties.ts
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30318 MM-62698 Handles additional property types in the profile popover form.
  webapp/channels/src/components/profile_popover/profile_popover.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover.tsx
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx
  webapp/channels/src/components/profile_popover/profile_popover_phone.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_phone.tsx
  webapp/channels/src/components/profile_popover/profile_popover_select_attribute.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_select_attribute.tsx
  webapp/channels/src/components/profile_popover/profile_popover_text_attribute.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_text_attribute.tsx
  webapp/channels/src/components/profile_popover/profile_popover_url.test.tsx
  webapp/channels/src/components/profile_popover/profile_popover_url.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/platform/types/src/users.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30396 Premium SKU
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/channels/api4/custom_profile_attributes.go
  server/channels/api4/group.go
  server/channels/api4/handlers.go
  server/channels/api4/ip_filtering.go
  server/channels/api4/outgoing_oauth_connection.go
  server/channels/api4/post.go
  server/channels/app/notification.go
  server/channels/app/plugin.go
  server/channels/app/post_permission_utils.go
  server/channels/app/report.go
  server/channels/jobs/post_persistent_notifications/scheduler.go
  server/config/client.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/license.go
  server/public/model/license_test.go
  server/public/pluginapi/license.go
  server/public/pluginapi/license_test.go
  webapp/channels/src/components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_export/index.tsx
  webapp/channels/src/components/admin_console/team_channel_settings/channel/details/index.ts
  webapp/channels/src/components/admin_console/workspace-optimization/dashboard.data.tsx
  webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  webapp/channels/src/selectors/admin_console.jsx
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/license_utils.test.ts
  webapp/channels/src/utils/license_utils.ts
  webapp/channels/src/utils/subscription.ts
Labels: Setup Cloud Test Server, release-note-none, E2E/Overridden

#30641 Automated cherry pick of #30471
  e2e-tests/cypress/tests/support/api/system.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30642 Automated cherry pick of #30471
  e2e-tests/cypress/tests/support/api/system.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30585 MM-63451 Rely on MUI's MenuList to handle focus when opening menus
  e2e-tests/playwright/lib/src/ui/components/global_header.ts
  e2e-tests/playwright/test/specs/accessibility/channels/account_menu_keyboard.spec.ts
  webapp/channels/src/components/menu/menu.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30580 [MM-63280] Forward ref properly through SwitchChannelSuggestion
  webapp/channels/src/components/suggestion/switch_channel_provider.tsx
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30604 MM-61589 Keep Help and Preview links visible on small screen sizes
  webapp/channels/src/sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30430 Input Field: Fix accessibility issues with errors not associated to proper form fields
  webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/__snapshots__/input.test.tsx.snap
  webapp/channels/src/components/widgets/inputs/input/input.tsx
  webapp/channels/src/components/widgets/inputs/password_input/password_input.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Deferred, release-note-none, E2E/Overridden

#30625 [MM-63613] Update `golang-jwt/jwt` dependency to latest
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30628 [MM-63624] Fix potential nil dereference in `app.isChannelArchivedAndHidden`
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30638 Cherrypicked #30470 for 10.5
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/footer.tsx
  webapp/channels/src/components/advanced_text_editor/use_submit.tsx
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/msg_typing/index.ts
  webapp/channels/src/components/msg_typing/msg_typing.test.tsx
  webapp/channels/src/components/msg_typing/msg_typing.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30640 Cherrypicked #30470 for 10.6
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/footer.tsx
  webapp/channels/src/components/advanced_text_editor/use_submit.tsx
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/msg_typing/index.ts
  webapp/channels/src/components/msg_typing/msg_typing.test.tsx
  webapp/channels/src/components/msg_typing/msg_typing.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#30417 MM-63298: [AI assisted] Elasticsearch add a global search prefix
  server/channels/store/searchtest/helper.go
  server/enterprise/elasticsearch/common/common.go
  server/enterprise/elasticsearch/common/test_suite.go
  server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
  server/enterprise/elasticsearch/opensearch/opensearch.go
  server/i18n/en.json
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30514 Show channel banner in channel
  webapp/channels/src/components/channel_banner/channel_banner.test.tsx
  webapp/channels/src/components/channel_banner/index.tsx
  webapp/channels/src/components/channel_banner/style.scss
  webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/with_tooltip/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/theme_utils.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/theme_utils.ts
  webapp/platform/types/src/channels.ts
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30652 [MM-63311] Cherry pick 9.11
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/app_iface.go
  server/channels/app/group.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30646 [MM-63311] 10.5 cherry-pick
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/app_iface.go
  server/channels/app/group.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/plugin_api.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30507 [MM-63455] Fix Link previews with brackets when making the request
  server/channels/app/post_metadata_test.go
  server/public/shared/markdown/autolink.go
  server/public/shared/markdown/autolink_test.go
Labels: 2: Dev Review, 3: QA Review, release-note, Contributor, E2E/Overridden

#30654 Enabld the bidichk linter
  server/.golangci.yml
Labels: release-note-none, E2E/Overridden

#30649 Fixing typo in en.json
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#30662 E2E/Playwright: bump playwright lib to 10.8.0, update dependencies and update snapshots
  e2e-tests/playwright/README.md
  e2e-tests/playwright/lib/package.json
  e2e-tests/playwright/lib/src/server/default_config.ts
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/package.json
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  webapp/platform/types/src/config.ts
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#29940 [MM-59051] : Email notification setting 'Immediately' is unclear given the help text description [Fixed]
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  webapp/channels/src/components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor, E2E/Overridden

#30600 Consistent error wrapping
  server/channels/app/channel.go
  server/channels/app/emoji.go
  server/channels/app/export.go
  server/channels/app/file.go
  server/channels/app/import_functions.go
  server/channels/app/integration_action.go
  server/channels/app/integration_action_test.go
  server/channels/app/oauth.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_commands.go
  server/channels/app/plugin_install.go
  server/channels/app/post.go
  server/channels/app/saml.go
  server/channels/app/scheduled_post.go
  server/channels/app/status.go
  server/channels/app/team.go
  server/channels/app/user.go
  server/channels/app/webhook.go
  server/public/model/client4.go
  server/public/model/config.go
Labels: release-note-none, E2E/Overridden

#30578 [MM-63582] Recent Mentions Not Properly Handling Hyphenated Custom Keywords
  webapp/.gitignore
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/views/rhs.ts
Labels: Setup Cloud Test Server, release-note, E2E/Overridden

#30607 [MM-60797] Fix errcheck issues in support_packet_test.go
  server/.golangci.yml
  server/channels/app/support_packet_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30545 MM-62784 added tooltip to hidden formatting controls button
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/billing/billing_subscriptions/contact_sales_card.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.test.tsx
  webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30350 MM-62703 Implement cpa for ldap/saml in System Console
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.test.tsx
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.scss
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 2: Dev Review, QA - Deferred, 3: Security Review, release-note-none, 1. UX Review, E2E/Overridden

#30459 MM-62767: Add Custom Profile Attributes to the SAML synchronization process
  server/i18n/en.json
Labels: 4: Reviews Complete, QA - Deferred, release-note-none, E2E/Overridden

#30653 Move the sanitization and validation of CPA values to the model
  server/channels/api4/custom_profile_attributes.go
  server/channels/api4/custom_profile_attributes_test.go
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/i18n/en.json
  server/public/model/custom_profile_attributes.go
  server/public/model/custom_profile_attributes_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30427 MM-43598: Bulk export not exporting non-thread DMs from deactivated users
  server/channels/app/export_test.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30568 Unshares a channel when uninviting the last remote
  server/platform/services/sharedchannel/service_api.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none, E2E/Overridden

#30682 [CLD-9052] Make trial form modal-body scrollable for small vertical screens
  webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30688 Update mattermost-govet version to latest SHA
  server/Makefile
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30681 [CLD-8961] Fix typo in trial license error message
  e2e-tests/playwright/lib/src/ui/components/channels/center_view.ts
  e2e-tests/playwright/specs/functional/channels/settings/notifications/highlight_without_notification.spec.ts
  server/i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#30295 MM-63200: unrestricted local admin
  server/channels/api4/bleve.go
  server/channels/api4/cluster.go
  server/channels/api4/config.go
  server/channels/api4/elasticsearch.go
  server/channels/api4/license.go
  server/channels/api4/system.go
  server/channels/app/authorization.go
  server/channels/app/authorization_test.go
  server/channels/app/license.go
  server/channels/app/plugin_api.go
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30697 Fix failing E2E smoketests
  e2e-tests/playwright/lib/src/ui/components/channels/center_view.ts
Labels: 4: Reviews Complete, release-note-none

#29368 Update permissions language to be more explicit
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
  webapp/channels/src/components/admin_console/permission_schemes_settings/strings/permissions.tsx
  webapp/channels/src/i18n/en.json
Labels: release-note-none, E2E/Overridden

#30669 [MM-63693] Don't log PING websocket events
  server/channels/wsapi/websocket_handler.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#30673 [MM-63597] Fix `From:` autocompletion
  e2e-tests/playwright/specs/functional/channels/search/search_box_suggestions.spec.ts
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/components/suggestion/search_user_provider.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#30703 Automated cherry pick of #30669
  server/channels/wsapi/websocket_handler.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30704 Automated cherry pick of #30669
  server/channels/wsapi/websocket_handler.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30544 MM-61891 Fix styles for attachment card overflow issue
  e2e-tests/playwright/lib/src/ui/components/channels/center_view.ts
  e2e-tests/playwright/specs/functional/channels/scheduled_drafts/create_scheduled_draft.spec.ts
  webapp/channels/src/components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
  webapp/channels/src/components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap
  webapp/channels/src/components/file_attachment/file_attachment.tsx
  webapp/channels/src/components/file_attachment/filename_overlay.tsx
  webapp/channels/src/components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
  webapp/channels/src/components/file_search_results/file_search_result_item.scss
  webapp/channels/src/components/file_search_results/file_search_result_item.tsx
  webapp/channels/src/sass/components/_files.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30608 [MM-61461] Fix errcheck error in plugin_test.go
  server/.golangci.yml
  server/channels/app/plugin_test.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#29003 Fixed errcheck issues in server/channels/app/file_bench_test.go
  server/.golangci.yml
  server/channels/app/file_bench_test.go
Labels: 4: Reviews Complete, Hacktoberfest, release-note-none, Contributor, E2E/Overridden

#30611 [MM-61079] Fix error checking in webhook.go
  server/.golangci.yml
  server/channels/web/webhook.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30602 [MM-63618] add abac settings
  server/public/model/config.go
Labels: 4: Reviews Complete, release-note-none

#30579 [MM-63583] Send websocket ping immediately after connecting
  webapp/platform/client/src/websocket.test.ts
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note-none

#30443 MM-62704: Add Custom Profile Attributes to the LDAP synchronization process
  .github/workflows/esrupgrade-common.yml
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/.ci/server.prepare.sh
  server/Makefile
  server/i18n/en.json
  server/tests/custom-schema-cpa.ldif
  server/tests/test-data.ldif
Labels: 2: Dev Review, QA - Deferred, release-note-none

#30101 [MM-62869] Allow users to escape automatic emoticon formatting
  webapp/channels/src/utils/emoticons.test.tsx
  webapp/channels/src/utils/emoticons.tsx
Labels: 4: Reviews Complete, release-note, Contributor, E2E/Overridden

#30650 MM-63590 - validate user has proper permission when updating team pri…
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none

#30692 Abac policy editor
  server/go.mod
  webapp/channels/package.json
  webapp/channels/src/components/admin_console/access_control/cel_editor/editor.scss
  webapp/channels/src/components/admin_console/access_control/cel_editor/editor.tsx
  webapp/channels/src/components/admin_console/access_control/cel_editor/language_provider.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/webpack.config.js
  webapp/package-lock.json
Labels: Do Not Merge, release-note-none

#30617 [MM-61082] Fix errcheck issues in license_test.go
  server/.golangci.yml
  server/channels/utils/license_test.go
Labels: 4: Reviews Complete, release-note-none

#30149 Add e2e tests for revokeToken Command
  server/cmd/mmctl/commands/token_e2e_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#30709 Update mattermost-govet version to latest SHA for vet target
  server/Makefile
Labels: 4: Reviews Complete, 2: Dev Review, release-note-none

#30606 fix: handle error from InvalidateAllCaches in slack.go
  server/.golangci.yml
  server/channels/app/admin.go
  server/channels/app/platform/cluster_handlers.go
  server/channels/app/slack.go
  server/platform/services/slackimport/slackimport.go
Labels: 4: Reviews Complete, release-note-none, Contributor

#28806 MM-57097: Add a toggle to switch between plain and JSON logs format
  webapp/channels/src/components/admin_console/server_logs/logs.tsx
  webapp/channels/src/components/admin_console/server_logs/plain_log_list.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, Hacktoberfest, release-note, Contributor

#30466 MM-63342:Bot accounts OAuth gating
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#30467 MM-63316: Guest access to channel
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/public/model/session.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#30419 MM-62930: Add validation of LDAP attribute values.
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-test-template.yml
  e2e-tests/.ci/server.prepare.sh
  server/Makefile
  server/i18n/en.json
  server/tests/custom-schema-objectID.ldif
  server/tests/test-data.ldif
Labels: 2: Dev Review, 3: Security Review, release-note-none

#30726 Automated cherry pick of #30466
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30458 MM-62156: Avoid SELECT * in retention_policy_store.go
  server/channels/store/sqlstore/retention_policy_store.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#30729 Automated cherry pick of #30467
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/public/model/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30651 flaky test: Avoid team names that start with "A".
  server/channels/app/import_functions_test.go
Labels: 2: Dev Review, QA - Review Not Required, release-note-none, E2E/Overridden

#30731 stop reporting flaky tests
  .github/workflows/server-ci-report.yml
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#30712 [AI assisted]: MM-53739: replace store.NewErrNotFound with errors.Wrap in category queries
  server/channels/store/sqlstore/channel_store_categories.go
Labels: 4: Reviews Complete, release-note-none

#30672 MM-63378: Test and fix permission issues with System Manager team access
  e2e-tests/playwright/specs/functional/system_console/permissions/team_access.spec.ts
  server/public/model/role.go
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permission.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permission.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, release-note

#30663 MM-62005 Remove FloatingFocusManager from PluginLinkTooltip
  webapp/channels/src/components/plugin_link_tooltip/index.test.tsx
  webapp/channels/src/components/plugin_link_tooltip/index.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#30740 Automated cherry pick of #30663
  webapp/channels/src/components/plugin_link_tooltip/index.test.tsx
  webapp/channels/src/components/plugin_link_tooltip/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30748 Automated cherry pick of #30663
  webapp/channels/src/components/plugin_link_tooltip/index.test.tsx
  webapp/channels/src/components/plugin_link_tooltip/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30749 Automated cherry pick of #30663
  webapp/channels/src/components/plugin_link_tooltip/index.test.tsx
  webapp/channels/src/components/plugin_link_tooltip/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30750 Automated cherry pick of #30669
  server/channels/wsapi/websocket_handler.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30752 Automated cherry pick of #30672
  e2e-tests/playwright/specs/functional/system_console/permissions/team_access.spec.ts
  server/public/model/role.go
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permission.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permission.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30684 [MM-61515] Fix errcheck linter issues in webhook_test.go
  server/.golangci.yml
  server/channels/app/webhook_test.go
Labels: 4: Reviews Complete, release-note-none, release-note/none

#30612 [MM-61076] Fix errcheck issues in server/channels/web/saml.go
  server/.golangci.yml
  server/channels/web/saml.go
Labels: 4: Reviews Complete, release-note-none

#30615 [MM-28948] Fix errcheck linter issues in import_functions.go
  server/.golangci.yml
  server/channels/app/import_functions.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30660 Manual cherry pick of #30571 to 9.11
  e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts
  server/channels/app/user.go
Labels: release-note-none

#30637 Automated cherry pick of #30571
  e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30635 Automated cherry pick of #30571
  e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30636 Automated cherry pick of #30571
  e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts
  server/channels/app/user.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30759 Automated cherry pick of #30650
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30763 Automated cherry pick of #30466
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30762 Automated cherry pick of #30650
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30766 Automated cherry pick of #30466
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30768 Automated cherry pick of #30467
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/public/model/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30770 Automated cherry pick of #30672
  e2e-tests/playwright/specs/functional/system_console/permissions/team_access.spec.ts
  server/public/model/role.go
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permission.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permission.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30760 Automated cherry pick of #30650
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30761 Automated cherry pick of #30650
  server/channels/api4/team.go
  server/channels/api4/team_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30764 Automated cherry pick of #30466
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30765 Automated cherry pick of #30466
  server/channels/app/bot.go
  server/channels/app/bot_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30767 Automated cherry pick of #30467
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/public/model/session.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30670 [MM-63436] Update bep/imagemeta to latest v0.11.0
  server/go.mod
  server/go.sum
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30769 Automated cherry pick of #30672
  e2e-tests/playwright/specs/functional/system_console/permissions/team_access.spec.ts
  server/public/model/role.go
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permission.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permission.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30739 fix: allow plugins when embedding mattermost
  webapp/channels/src/plugins/index.ts
Labels: kind/bug, release-note-none, E2E/Overridden

#30742 [MM-63444] Prepackage Calls v1.7.0
  server/Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, E2E/Overridden

#30775 Automated cherry pick of #30742
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30719 MM-59038 Fix markdown inconsistencies in preview mode
  webapp/channels/src/sass/components/_post-right.scss
  webapp/channels/src/sass/layout/_markdown.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note, E2E/Overridden

#30223 Feature/audit certificate upload
  api/Makefile
  api/v4/source/audit_logging.yaml
  api/v4/source/introduction.yaml
  server/channels/api4/api.go
  server/channels/api4/audit_logging.go
  server/channels/app/audit.go
  server/einterfaces/cloud.go
  server/einterfaces/mocks/CloudInterface.go
  server/i18n/en.json
  server/public/model/config.go
  webapp/channels/src/actions/admin_actions.jsx
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/audit_logging/index.tsx
  webapp/channels/src/components/admin_console/file_upload_setting.tsx
  webapp/channels/src/components/admin_console/types.ts
  webapp/channels/src/components/common/hooks/useGetCloudInstallationStatus.ts
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, EETests, QA - Deferred, release-note-none

#30694 Improves validation and sanitization for CPA fields and values
  server/channels/api4/custom_profile_attributes_test.go
  server/public/model/custom_profile_attributes.go
  server/public/model/custom_profile_attributes_test.go
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30699 MM-63719- Custom Profile Attributes CSS fixes
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.scss
  webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.scss
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, release-note-none

#30727 Translations update from Mattermost Weblate
  server/i18n/cs.json
  server/i18n/da.json
  server/i18n/de.json
  server/i18n/es.json
  server/i18n/fi.json
  server/i18n/ja.json
  server/i18n/lt.json
  server/i18n/nl.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/sv.json
  server/i18n/tr.json
  server/i18n/uk.json
  server/i18n/zh-CN.json
  webapp/channels/src/i18n/be.json
  webapp/channels/src/i18n/bg.json
  webapp/channels/src/i18n/cs.json
  webapp/channels/src/i18n/de.json
  webapp/channels/src/i18n/el.json
  webapp/channels/src/i18n/en-AU.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/fa.json
  webapp/channels/src/i18n/fi.json
  webapp/channels/src/i18n/fr.json
  webapp/channels/src/i18n/fy.json
  webapp/channels/src/i18n/hr.json
  webapp/channels/src/i18n/hu.json
  webapp/channels/src/i18n/it.json
  webapp/channels/src/i18n/ja.json
  webapp/channels/src/i18n/ko.json
  webapp/channels/src/i18n/lt.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/ne.json
  webapp/channels/src/i18n/nl.json
  webapp/channels/src/i18n/pl.json
  webapp/channels/src/i18n/pt-BR.json
  webapp/channels/src/i18n/ro.json
  webapp/channels/src/i18n/ru.json
  webapp/channels/src/i18n/sq.json
  webapp/channels/src/i18n/sv.json
  webapp/channels/src/i18n/tr.json
  webapp/channels/src/i18n/uk.json
  webapp/channels/src/i18n/vi.json
  webapp/channels/src/i18n/zh-CN.json
  webapp/channels/src/i18n/zh-TW.json
Labels: release-note-none, E2E/Overridden

#30778 Bump up test runners after Elasticsearch move
  .github/workflows/server-test-template.yml
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30591 Migrate API docs from Redoc to Stoplight
  .github/workflows/api.yml
  api/Makefile
  api/README.md
  api/package.json
  api/v4/html/ssr_template.hbs
  api/v4/source/definitions.yaml
  api/v4/source/introduction.yaml
Labels: release-note-none, E2E/Overridden

#30796 Automated cherry pick of #30778
  .github/workflows/server-test-template.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#29786 [MM-62412] Block login of SAML users if no connected LDAP user is found
  server/einterfaces/ldap.go
  server/einterfaces/mocks/LdapInterface.go
  server/i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#30718 MM-63704 Hide priority label if message is deleted
  webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  webapp/channels/src/components/post/post_component.test.tsx
  webapp/channels/src/components/post/post_component.tsx
  webapp/channels/src/components/post_priority/post_priority_label.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none

#30665 MM-63601 Fields are not shown after initial login through invite
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Review Done, release-note-none, E2E/Overridden

#30584 MM-63313 Make theme setting radio buttons horizontal and update text
  e2e-tests/playwright/lib/src/ui/components/channels/settings/display_settings.ts
  e2e-tests/playwright/lib/src/ui/components/channels/settings/settings_modal.ts
  e2e-tests/playwright/lib/src/ui/components/global_header.ts
  e2e-tests/playwright/lib/src/ui/pages/channels.ts
  e2e-tests/playwright/specs/accessibility/channels/theme_settings.spec.ts
  e2e-tests/playwright/specs/functional/channels/settings/notifications/highlight_without_notification.spec.ts
  webapp/channels/src/components/user_settings/display/user_settings_theme/color_chooser/__snapshots__/color_chooser.test.tsx.snap
  webapp/channels/src/components/user_settings/display/user_settings_theme/color_chooser/color_chooser.tsx
  webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/sass/routes/_settings.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#30777 MM-63587 Custom Profile Attributes E2E Profile Popover Test
  e2e-tests/playwright/specs/functional/channels/custom_profile_attributes/custom_attributes.spec.ts
  e2e-tests/playwright/specs/functional/channels/custom_profile_attributes/helpers.ts
  e2e-tests/playwright/specs/functional/channels/custom_profile_attributes/user_settings.spec.ts
Labels: 2: Dev Review, 3: QA Review, release-note-none, E2E/Overridden

#30700 MM-63728: Add license load metric endpoint and UI indicator
  api/v4/source/system.yaml
  server/channels/api4/license.go
  server/channels/api4/license_test.go
  server/i18n/en.json
  server/public/model/client4.go
  webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
  webapp/channels/src/components/about_build_modal/about_build_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/platform/client/src/client4.ts
Labels: 2: Dev Review, Setup Cloud Test Server, QA - Deferred, release-note

#30741 MM-62158: Group Store, explicit aliases
  server/channels/store/sqlstore/group_store.go
  server/channels/store/storetest/group_store.go
Labels: 2: Dev Review, release-note-none

#30721 Channel banner settings
  e2e-tests/playwright/lib/src/ui/components/channels/center_view.ts
  e2e-tests/playwright/lib/src/ui/components/channels/header.ts
  e2e-tests/playwright/lib/src/ui/components/channels/settings/configuration_settings.ts
  e2e-tests/playwright/lib/src/ui/components/channels/settings/settings_modal.ts
  e2e-tests/playwright/lib/src/ui/pages/channels.ts
  e2e-tests/playwright/lib/src/util.ts
  e2e-tests/playwright/package-lock.json
  e2e-tests/playwright/specs/functional/channels/channel_banner/channel_banner.spec.ts
  e2e-tests/playwright/utils/utils.ts
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/i18n/en.json
  webapp/channels/src/components/channel_banner/channel_banner.test.tsx
  webapp/channels/src/components/channel_banner/channel_banner.tsx
  webapp/channels/src/components/channel_banner/style.scss
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.scss
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.scss
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.test.tsx
  webapp/channels/src/components/channel_settings_modal/channel_settings_modal.tsx
  webapp/channels/src/components/channel_view/channel_view.tsx
  webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
  webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.ts
  webapp/channels/src/sass/base/_structure.scss
  webapp/channels/src/sass/components/_color-input.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, 1. UX Review

#29661 MM-60780: Reject emails within angle brackets
  server/public/model/utils.go
  server/public/model/utils_test.go
Labels: 4: Reviews Complete, release-note

#30818 Automated cherry pick of #30739
  webapp/channels/src/plugins/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30819 Automated cherry pick of #30578
  webapp/.gitignore
  webapp/channels/src/actions/views/rhs.test.ts
  webapp/channels/src/actions/views/rhs.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30772 MM-63276, MM-62707: CPA LDAP/SAML links and Duplicate field
  webapp/channels/src/components/admin_console/blockable_link/blockable_link.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.ts
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.tsx
  webapp/channels/src/components/menu/index.ts
  webapp/channels/src/components/menu/menu_item_link.tsx
  webapp/channels/src/components/new_search/select_team.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA - Deferred, release-note-none

#30824 Automated cherry pick of #30772
  webapp/channels/src/components/admin_console/blockable_link/blockable_link.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_dot_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_table.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_utils.ts
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.scss
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.test.tsx
  webapp/channels/src/components/admin_console/system_properties/user_properties_values.tsx
  webapp/channels/src/components/menu/index.ts
  webapp/channels/src/components/menu/menu_item_link.tsx
  webapp/channels/src/components/new_search/select_team.tsx
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30833 avoid SELECT * in link metadata store
  server/channels/store/sqlstore/link_metadata_store.go
Labels: release-note-none, E2E/Overridden

#30828 avoid SELECT * in channel member history store
  server/channels/store/sqlstore/channel_member_history_store.go
  server/channels/store/storetest/channel_member_history_store.go
Labels: release-note-none

#30743 MM-62382/MM-63615 Remove explicit reference to react-popper and remaining references to popper.js
  webapp/channels/package.json
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
  webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_popover.tsx
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30831 avoid SELECT * in command stores
  server/channels/store/sqlstore/command_store.go
  server/channels/store/sqlstore/command_webhook_store.go
Labels: release-note-none, E2E/Overridden

#30592 [MM-63023] Conditionally make thread item elements focusable based on whether they have an interaction
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/following_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/global_threads_spec.ts
  e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/replies_spec.ts
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
  e2e-tests/cypress/tests/integration/channels/message_forwarding/forward_message_from_public_channel_spec.js
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.test.tsx
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
  webapp/channels/src/i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note, E2E/Overridden

#30834 avoid SELECT * in notify admin store
  server/channels/store/sqlstore/notify_admin_store.go
Labels: release-note-none, E2E/Overridden

#30830 avoid SELECT * in cluster discovery store
  server/channels/store/sqlstore/cluster_discovery_store.go
Labels: release-note-none

#30698 [MM-62517] Improve cross team search UI
  webapp/channels/src/components/new_search/search_box.tsx
  webapp/channels/src/components/new_search/select_team.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none, E2E/Overridden

#30826 Automated cherry pick of #30739
  webapp/channels/src/plugins/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30563 [MM-63685] Virtualize drafts in the drafts list
  e2e-tests/playwright/lib/src/ui/pages/drafts.ts
  e2e-tests/playwright/lib/src/ui/pages/scheduled_draft.ts
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  webapp/channels/package.json
  webapp/channels/src/components/custom_status/custom_status_modal.test.tsx
  webapp/channels/src/components/drafts/__snapshots__/drafts.test.tsx.snap
  webapp/channels/src/components/drafts/draft_list/draft_list.tsx
  webapp/channels/src/components/drafts/draft_list/empty_draft_list.tsx
  webapp/channels/src/components/drafts/draft_list/empty_draft_list_illustration.tsx
  webapp/channels/src/components/drafts/draft_list/index.test.tsx
  webapp/channels/src/components/drafts/draft_list/index.tsx
  webapp/channels/src/components/drafts/draft_list/virtualized_draft_list.tsx
  webapp/channels/src/components/drafts/draft_row.scss
  webapp/channels/src/components/drafts/draft_row.tsx
  webapp/channels/src/components/drafts/drafts.test.tsx
  webapp/channels/src/components/drafts/drafts.tsx
  webapp/channels/src/components/drafts/drafts_and_schedule_posts.scss
  webapp/channels/src/components/drafts/drafts_and_schedule_posts_page_header.tsx
  webapp/channels/src/components/drafts/drafts_and_schedule_posts_tabs.tsx
  webapp/channels/src/components/drafts/index.ts
  webapp/channels/src/components/drafts/index.tsx
  webapp/channels/src/components/drafts/panel/panel.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/empty_scheduled_post_list.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/index.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/non_virtualized_scheduled_post_list.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/scheduled_post_error.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/scheduled_post_list.scss
  webapp/channels/src/components/drafts/scheduled_post_list/scheduled_post_list.tsx
  webapp/channels/src/components/drafts/scheduled_post_list/virtualized_scheduled_post_list.tsx
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_list/__snapshots__/virtualized_thread_list.test.tsx.snap
  webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  webapp/channels/src/selectors/drafts.ts
  webapp/channels/src/utils/constants.tsx
  webapp/channels/src/utils/http_utils.ts
  webapp/channels/src/utils/performance_telemetry/element_identification.test.tsx
  webapp/package-lock.json
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30829 avoid SELECT * in audit store
  server/channels/store/sqlstore/audit_store.go
Labels: release-note-none

#30839 Automated cherry pick of #30789
  server/channels/api4/apitestlib.go
  server/channels/api4/channel_bookmark_test.go
  server/channels/api4/channel_test.go
  server/channels/api4/team.go
  server/channels/api4/team_guest_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30779 [AI assisted]MM-63467: Refactor constLabels to a common initializer
  server/enterprise/metrics/metrics.go
Labels: 4: Reviews Complete, Area/E2E Tests, release-note-none, E2E/Overridden

#30835 MM-62110 avoid SELECT * in preference_store
  server/channels/store/sqlstore/preference_store.go
  server/channels/store/storetest/preference_store.go
Labels: release-note-none, E2E/Overridden

#30724 MM-63756: Added index to sidebarchannels table
  server/channels/db/migrations/migrations.list
  server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.down.sql
  server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.up.sql
  server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.down.sql
  server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.up.sql
Labels: Area/E2E Tests, release-note-none, E2E/Overridden

#30622 Mm 61590 - trap focus in modals
  webapp/channels/src/components/browse_channels/__snapshots__/browse_channels.test.tsx.snap
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  webapp/channels/src/components/drafts/draft_actions/__snapshots__/send_draft_modal.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/abstract_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/add_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/integrations/outgoing_oauth_connections/__snapshots__/edit_outgoing_oauth_connection.test.tsx.snap
  webapp/channels/src/components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
  webapp/channels/src/components/multiselect/multiselect_list.tsx
  webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  webapp/channels/src/components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  webapp/channels/src/components/quick_switch_modal/quick_switch_modal.test.tsx
  webapp/channels/src/components/team_groups_manage_modal/team_groups_manage_modal.test.tsx
  webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
  webapp/platform/components/src/generic_modal/generic_modal.tsx
  webapp/platform/components/src/hooks/useFocusTrap.test.tsx
  webapp/platform/components/src/hooks/useFocusTrap.ts
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30850 MM-63878: Fix INSERT IGNORE in saveChannelT
  server/channels/store/sqlstore/channel_store.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30849 MM-62005 Remove FloatingFocusManager from PluginLinkTooltip (#30663)
  webapp/channels/src/components/plugin_link_tooltip/index.test.tsx
  webapp/channels/src/components/plugin_link_tooltip/index.tsx
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, CherryPick/Done, release-note

#30444 Report a problem
  api/v4/source/definitions.yaml
  e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e-tests/cypress/tests/support/api/cloud_default_config.json
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/lib/src/server/default_config.ts
  server/config/client.go
  server/config/client_test.go
  server/i18n/en.json
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/public/model/config_test.go
  server/tests/test-config.json
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/common/hooks/use_external_link.test.ts
  webapp/channels/src/components/common/hooks/use_external_link.ts
  webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/index.ts
  webapp/channels/src/components/mobile_sidebar_right/mobile_sidebar_right_items/index.tsx
  webapp/channels/src/components/mobile_sidebar_right/mobile_sidebar_right_items/mobile_sidebar_right_items.test.tsx
  webapp/channels/src/components/search/index.tsx
  webapp/channels/src/components/search/search.tsx
  webapp/channels/src/components/search/types.ts
  webapp/channels/src/components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  webapp/channels/src/components/search/user_guide_dropdown/index.ts
  webapp/channels/src/components/search/user_guide_dropdown/user_guide_dropdown.test.tsx
  webapp/channels/src/components/search/user_guide_dropdown/user_guide_dropdown.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/report_a_problem.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/report_a_problem.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/browser_info.test.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/browser_info.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30853 fix missing newline in upgrader.go
  server/platform/services/upgrader/upgrader.go
Labels: 2: Dev Review, QA - Review Not Required, release-note-none, E2E/Overridden

#30747 MM-61611 Fix layout of emoji picker in mobile view
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/__snapshots__/emoji_picker_header.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_category_row.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_header.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_skin.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
  webapp/channels/src/components/gif_picker/components/gif_picker_search.tsx
  webapp/channels/src/components/gif_picker/gif_picker.tsx
  webapp/channels/src/sass/components/_emoji-picker-tabs.scss
  webapp/channels/src/sass/components/_emoticons.scss
  webapp/channels/src/sass/responsive/_mobile.scss
  webapp/channels/src/sass/utils/_variables.scss
  webapp/channels/src/utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, E2E/Overridden

#30799 MM-63800 Add label tag for create account checkbox
  e2e-tests/playwright/specs/visual/channels/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e-tests/playwright/specs/visual/common/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  webapp/channels/src/components/widgets/inputs/check/check.scss
  webapp/channels/src/components/widgets/inputs/check/index.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30689 [MM-61105] Fix errcheck linter errors in config_test.go
  server/.golangci.yml
  server/channels/app/config_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, release-note-none, E2E/Overridden, Bug

#30643 [MM-61087] Fix errcheck linter issues in channels/jobs/helper_test.go
  server/.golangci.yml
  server/channels/jobs/helper_test.go
Labels: 4: Reviews Complete, release-note-none
