Repository mattermost/mattermost, pull requests merged in 2025-03, with the labels that each got.

#30393 [MM-63325, MM-63329] feat: dont register plugins or show the footer if MMEMBED cookie is set to `1`
  webapp/channels/src/components/header_footer_route/footer.tsx
  webapp/channels/src/plugins/index.ts
Labels: kind/feature, release-note

#30366 MM-63301: Use break-word in profile popover fields
  webapp/channels/src/components/profile_popover/profile_popover.scss
Labels: 4: Reviews Complete, QA - Deferred, release-note-none

#30371 [AI assisted] MM-63304: Wrap around dqPtr while unmarshalling
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/websocket_reliable.go
  server/channels/app/platform/websocket_reliable_test.go
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, E2E/Overridden

#30368 MM-63213 Remove background from more modal plus button
  webapp/channels/src/sass/components/_modal.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30405 Automated cherry pick of #30368
  webapp/channels/src/sass/components/_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30400 Automated cherry pick of #30371
  server/channels/app/platform/web_hub.go
  server/channels/app/platform/websocket_reliable.go
  server/channels/app/platform/websocket_reliable_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30409 MM-63327 Config setting for `ServiceSettings.FrameAncestors`
  server/channels/web/handlers.go
  server/channels/web/handlers_test.go
  server/channels/web/oauth.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, release-note

#30410 [MM-63352] Fix incorrect error handling in `api4.downloadJob`
  server/channels/api4/job.go
  server/channels/api4/job_test.go
Labels: 4: Reviews Complete, release-note-none

#30310 MM-53506 Fixed duplicated command response in thread/channel (#23969)
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note, Contributor, E2E/Overridden

#30103 Updates the property service and store method signatures
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/channels/app/properties/property_field.go
  server/channels/app/properties/property_value.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/mocks/PropertyValueStore.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/storetest/property_value_store.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 2: Dev Review, release-note-none

#30262 [MM-61604]: Fixed aria-expanded not correctly announced by screen reader
  webapp/channels/src/components/emoji_picker/components/emoji_picker_skin.tsx
  webapp/channels/src/i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, Contributor

#29813 [MM-61685]: Add described by prop to notifications settings
  webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Labels: 2: Dev Review, Area/Accessibility, release-note-none, Contributor

#30435 Translations update from Mattermost Weblate
  server/i18n/de.json
  server/i18n/nb-NO.json
  server/i18n/pl.json
  server/i18n/ru.json
  server/i18n/uk.json
  webapp/channels/src/i18n/da.json
  webapp/channels/src/i18n/es.json
  webapp/channels/src/i18n/nb-NO.json
  webapp/channels/src/i18n/uk.json
Labels: release-note-none, Do Not Merge/Mattermod, E2E/Overridden

#30436 Prepackage Calls v0.29.8 (v9.11)
  server/Makefile
Labels: 4: Reviews Complete, release-note

#30437 Prepackage Calls v1.5.2
  server/Makefile
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30439 Automated cherry pick of #30437
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30440 Prepackage Calls v1.5.2 (`release-10.4`)
  server/Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#30441 Prepackage Calls v1.5.2 (`release-10.3`)
  server/Makefile
Labels: 4: Reviews Complete, AutoMerge, release-note

#30298 [MM-62360] Fixed width of edit input box
  webapp/channels/src/sass/components/_post.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#30117 feat: Add Client4.createPostEphemeral method
  webapp/platform/client/src/client4.ts
Labels: 4: Reviews Complete, kind/feature, release-note, Contributor, E2E/Overridden

#30438 Automated cherry pick of #30437
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30339 MM-63262 Added missing onClick event on channel header
  webapp/channels/src/components/channel_header/channel_header_text_popover.tsx
Labels: 4: Reviews Complete, QA - Review Done, release-note, Contributor, E2E/Overridden

#30348 [MM-62133] Activate crossteam search by default
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_keyboard_usability_spec.js
  server/public/model/feature_flags.go
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#30369 MM-63271: CPA Sorting in Profile Popover & Profile Settings
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
  webapp/channels/src/components/user_settings/general/user_settings_general.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.test.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none, E2E/Overridden

#30422 MM-62161: Replace SELECT * in session_store.go
  server/channels/store/sqlstore/session_store.go
  server/channels/store/storetest/session_store.go
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#30385 MM-63235-Only prompt on private channels
  webapp/channels/src/components/permalink_view/actions.ts
  webapp/channels/src/components/permalink_view/permalink_view.test.tsx
Labels: 4: Reviews Complete, QA - Review Done, release-note-none

#29928 [MM-61640]: Add descriptive accessible names
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_muting_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/custom_categories_spec.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/helpers.ts
  e2e-tests/cypress/tests/integration/channels/channel_sidebar/sidebar_category_menu_spec.ts
  webapp/channels/src/components/menu/menu.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/index.test.tsx.snap
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/index.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_generic_menu.tsx
  webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu.tsx
  webapp/channels/src/components/sidebar/unread_channels.tsx
  webapp/channels/src/i18n/en.json
Labels: 4: Reviews Complete, Area/Accessibility, release-note-none, Contributor, E2E/Overridden

#30294 MM-61566 - focus first focusable element
  e2e-tests/cypress/package-lock.json
  e2e-tests/cypress/package.json
  e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_sidebar_spec.ts
  e2e-tests/cypress/tests/support/index.js
  e2e-tests/cypress/tsconfig.json
  webapp/channels/src/components/sidebar_right/sidebar_right.tsx
  webapp/channels/src/utils/a11y_utils.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#29606 MM-61707
  api/v4/source/users.yaml
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/user.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/config.go
  server/public/model/report.go
  server/public/model/user.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_reset_failed_attempts_modal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/users.ts
Labels: 2: Dev Review, release-note-none, E2E/Overridden

#28140 MM-55405 only attempt to getGroups if server is licensed.
  webapp/channels/src/packages/mattermost-redux/src/actions/status_profile_polling.test.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/status_profile_polling.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note-none

#30445 Added missed license check for channel banner in patch channel API
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/i18n/en.json
Labels: Setup Cloud Test Server, release-note-none

#30468 Automated cherry pick of #30445
  server/channels/api4/channel.go
  server/channels/api4/channel_test.go
  server/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30411 Add config settings for additional security features on mobile
  server/config/client.go
  server/public/model/config.go
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#30452 Fixed a bug where escape would delete all typed content
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#30233 [MM-61691] Deleting drafts when permanently deleting a user
  server/channels/app/user.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/draft_store.go
  server/channels/store/store.go
  server/channels/store/storetest/draft_store.go
  server/channels/store/storetest/mocks/DraftStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#30320 Plugin groups
  api/v4/source/groups.yaml
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/plugin_api.go
  server/channels/app/syncables.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/storetest/group_store.go
  server/channels/web/saml.go
  server/einterfaces/mocks/SamlInterface.go
  server/einterfaces/saml.go
  server/i18n/en.json
  server/public/go.mod
  server/public/go.sum
  server/public/model/client4.go
  server/public/model/group.go
  server/public/plugin/api.go
  server/public/plugin/api_timer_layer_generated.go
  server/public/plugin/client_rpc_generated.go
  server/public/plugin/hooks.go
  server/public/plugin/hooks_timer_layer_generated.go
  server/public/plugin/interface_generator/main.go
  server/public/plugin/plugintest/api.go
  server/public/plugin/plugintest/hooks.go
  server/public/pluginapi/group.go
  webapp/channels/src/components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
  webapp/channels/src/components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
  webapp/channels/src/components/admin_console/group_settings/__snapshots__/group_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_users.test.tsx.snap
  webapp/channels/src/components/admin_console/group_settings/group_details/group_details.tsx
  webapp/channels/src/components/admin_console/group_settings/group_details/group_users.test.tsx
  webapp/channels/src/components/admin_console/group_settings/group_details/group_users.tsx
  webapp/channels/src/components/admin_console/group_settings/group_settings.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_list_item/view_user_group_list_item.tsx
  webapp/channels/src/components/view_user_group_modal/view_user_group_modal.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/roles.ts
  webapp/channels/src/packages/mattermost-redux/src/utils/group_utils.ts
  webapp/channels/src/plugins/registry.ts
  webapp/channels/src/reducers/plugins/index.ts
  webapp/channels/src/types/store/plugins.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/groups.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30469 Automated cherry pick of #30411
  server/config/client.go
  server/public/model/config.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30471 Add company_country to trial license fetch
  e2e-tests/cypress/tests/support/api/system.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#30406 MM-T360 - search hashtags from mentions
  e2e-tests/cypress/tests/integration/channels/messaging/at_mentions_user_spec.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#30484 Automated cherry pick of #30409
  server/channels/web/handlers.go
  server/channels/web/handlers_test.go
  server/channels/web/oauth.go
  server/public/model/config.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30383 [MM-63314] Fix ClaimJob in HA environments
  server/channels/app/export_test.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/batch_worker.go
  server/channels/jobs/jobs.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/plugins/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/enterprise/elasticsearch/common/indexing_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/aggregation_job_test.go
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#30490 Automated cherry pick of #30383
  server/channels/app/export_test.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/batch_worker.go
  server/channels/jobs/jobs.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/plugins/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/enterprise/elasticsearch/common/indexing_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/aggregation_job_test.go
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none, E2E/Overridden

#30489 Automated cherry pick of #30383
  server/channels/app/export_test.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/batch_worker.go
  server/channels/jobs/jobs.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/plugins/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/opentracinglayer/opentracinglayer.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/enterprise/elasticsearch/common/indexing_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/aggregation_job_test.go
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30492 Automated cherry pick of #30383
  server/channels/app/export_test.go
  server/channels/jobs/base_workers.go
  server/channels/jobs/base_workers_test.go
  server/channels/jobs/batch_worker.go
  server/channels/jobs/jobs.go
  server/channels/jobs/jobs_test.go
  server/channels/jobs/migrations/worker.go
  server/channels/jobs/plugins/worker.go
  server/channels/jobs/s3_path_migration/s3_path_migration.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/job_store.go
  server/channels/store/sqlstore/utils.go
  server/channels/store/store.go
  server/channels/store/storetest/job_store.go
  server/channels/store/storetest/mocks/JobStore.go
  server/channels/store/timerlayer/timerlayer.go
  server/enterprise/elasticsearch/common/indexing_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job.go
  server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go
  server/enterprise/elasticsearch/opensearch/aggregation_job.go
  server/enterprise/elasticsearch/opensearch/aggregation_job_test.go
  server/enterprise/message_export/worker.go
  server/enterprise/message_export/worker_test.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
  server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30455 Bump Go to v1.23.7
  .github/workflows/codeql-analysis.yml
  server/.go-version
  server/Makefile
  server/build/Dockerfile.buildenv
  server/channels/app/authentication.go
  server/channels/app/import_utils.go
  server/channels/app/notification_push.go
  server/channels/app/plugin.go
  server/channels/app/saml.go
  server/channels/app/server.go
  server/channels/store/sqlstore/migrate.go
  server/channels/store/sqlstore/team_store.go
  server/channels/store/sqlstore/user_store.go
  server/cmd/mmctl/commands/docs.go
  server/config/logconfigsrc.go
  server/go.mod
  server/platform/services/searchengine/bleveengine/search.go
  server/platform/shared/mail/inbucket.go
  server/public/go.mod
  server/public/model/client4.go
  server/public/model/user.go
  server/public/model/version.go
  server/public/pluginapi/experimental/bot/logger/test_logger.go
Labels: 2: Dev Review, EETests, release-note-none, E2E/Overridden

#30509 migrate tag-based references to commit SHA-based references for github workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/esrupgrade-common.yml
  .github/workflows/mmctl-test-template.yml
  .github/workflows/server-ci-template.yml
  .github/workflows/server-test-template.yml
  webapp/channels/.github/workflows/performance-benchmarks.yml
Labels: release-note-none, E2E/Overridden

#30470 Thread reply edit file handling bug fix
  e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js
  e2e-tests/playwright/support/ui/components/channels/post_create.ts
  webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
  webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
  webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
  webapp/channels/src/components/advanced_text_editor/footer.tsx
  webapp/channels/src/components/advanced_text_editor/use_submit.tsx
  webapp/channels/src/components/edit_post/edit_post.tsx
  webapp/channels/src/components/msg_typing/index.ts
  webapp/channels/src/components/msg_typing/msg_typing.test.tsx
  webapp/channels/src/components/msg_typing/msg_typing.tsx
Labels: release-note-none

#30214 MM-60790: Prevent stemming in DB search when search term is a fully quoted string
  server/channels/store/searchtest/post_layer.go
  server/channels/store/sqlstore/post_store.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30424 MM-62159: Avoid SELECT * in channel_store_categories.go
  server/channels/store/sqlstore/channel_store.go
  server/channels/store/sqlstore/channel_store_categories.go
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#30407 Fixed RHS opy link icon styling
  webapp/channels/src/components/channel_info_rhs/top_buttons.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#30473 [MM-63442] Fix GET /groups endpoint docs
  api/v4/source/groups.yaml
  server/channels/api4/group_test.go
Labels: 4: Reviews Complete, release-note

#30448 MM-63350 Add tests for inviting guest users to teams
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30517 Automated cherry pick of #30448
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30289 MM-62900: Avoid redundant query for channelID while indexing file
  server/channels/store/searchlayer/file_info_layer.go
Labels: 4: Reviews Complete, LoadTest, release-note-none

#30522 Automated cherry pick of #30448
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30521 Automated cherry pick of #30448
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30520 Automated cherry pick of #30448
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#30180 [MM-62427] Add message attachments validation
  server/channels/api4/integration_action_test.go
  server/channels/api4/post_test.go
  server/channels/app/command.go
  server/channels/app/export_test.go
  server/channels/app/import_functions.go
  server/channels/app/integration_action_test.go
  server/channels/app/mention_parser_standard_test.go
  server/channels/app/notification.go
  server/channels/app/notification_push.go
  server/channels/app/notification_push_test.go
  server/channels/app/notification_test.go
  server/channels/app/plugin_api.go
  server/channels/app/plugin_api_test.go
  server/channels/app/post.go
  server/channels/app/post_metadata.go
  server/channels/app/post_metadata_test.go
  server/channels/app/post_test.go
  server/channels/app/slashcommands/command_test.go
  server/channels/app/webhook.go
  server/channels/app/webhook_test.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/post_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PostStore.go
  server/channels/store/storetest/post_acknowledgements_store.go
  server/channels/store/storetest/post_persistent_notification_store.go
  server/channels/store/storetest/post_priority_store.go
  server/channels/store/storetest/post_store.go
  server/channels/store/storetest/thread_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/enterprise/elasticsearch/common/common.go
  server/enterprise/message_export/global_relay_export/global_relay_export.go
  server/platform/services/slackimport/slackimport.go
  server/public/model/client4_test.go
  server/public/model/integration_action.go
  server/public/model/integration_action_test.go
  server/public/model/post.go
  server/public/model/post_test.go
  server/public/model/slack_attachment.go
  server/public/model/slack_attachment_test.go
  server/public/pluginapi/experimental/bot/poster/default_poster_test.go
  server/public/pluginapi/experimental/flow/handler.go
  server/public/pluginapi/experimental/flow/step.go
  server/public/pluginapi/experimental/panel/settings/bool_setting.go
  server/public/pluginapi/experimental/panel/settings/option_setting.go
  server/public/pluginapi/post.go
  server/public/pluginapi/post_test.go
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30086 [GH-30077] New actions for websocket group member update
  webapp/channels/src/actions/websocket_actions.jsx
  webapp/channels/src/actions/websocket_actions.test.jsx
  webapp/channels/src/packages/mattermost-redux/src/action_types/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/groups.test.ts
  webapp/channels/src/packages/mattermost-redux/src/reducers/entities/groups.ts
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/groups.ts
Labels: 4: Reviews Complete, QA - Review Done, release-note, Contributor, E2E/Overridden

#30516 Update Playbooks plugin to v1.41.0
  server/Makefile
Labels: 2: Dev Review, release-note

#30201 [MM-62695] Extend property types for CPA
  server/channels/api4/custom_profile_attributes.go
  server/channels/api4/custom_profile_attributes_test.go
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/i18n/en.json
  server/public/model/custom_profile_attributes.go
  server/public/model/custom_profile_attributes_test.go
  server/public/model/property_field.go
Labels: 4: Reviews Complete, QA - Deferred, release-note-none, E2E/Overridden

#30529 Prepackage Metrics Plugin v0.6.0
  server/Makefile
Labels: 4: Reviews Complete, Setup HA Cloud Test Server, release-note, E2E/Overridden

#30527 MM-63350 Add tests for inviting guest users to teams (#30448)
  server/channels/api4/apitestlib.go
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/api4/user_test.go
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#30533 Automated cherry pick of #30529
  server/Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30426 MM-63379: Fixing bot showing the local time
  webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.test.tsx
  webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.tsx
Labels: 4: Reviews Complete, QA - Review Done, release-note

#30553 MM-63545: Fix post reminder off-by-one error
  server/channels/store/sqlstore/post_store.go
  server/channels/store/storetest/post_store.go
Labels: release-note-none, E2E/Overridden

#30556 MM-61707 release-10.6
  api/v4/source/users.yaml
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/user.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/config.go
  server/public/model/report.go
  server/public/model/user.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_reset_failed_attempts_modal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30557 MM-61707 release-10.5
  api/v4/source/users.yaml
  e2e-tests/playwright/support/server/default_config.ts
  server/channels/api4/user.go
  server/channels/api4/user_test.go
  server/channels/app/app_iface.go
  server/channels/app/authentication.go
  server/channels/app/authentication_test.go
  server/channels/app/channels.go
  server/channels/app/ldap.go
  server/channels/app/opentracing/opentracing_layer.go
  server/channels/app/user.go
  server/i18n/en.json
  server/public/model/client4.go
  server/public/model/config.go
  server/public/model/report.go
  server/public/model/user.go
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_reset_failed_attempts_modal.tsx
  webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
  webapp/channels/src/utils/constants.tsx
  webapp/platform/client/src/client4.ts
  webapp/platform/types/src/config.ts
  webapp/platform/types/src/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#30534 [MM-63533] Skip flaky TestGetUserStatus/dnd_status_timed_restore_after_time_interval
  server/channels/api4/status_test.go
Labels: 2: Dev Review, release-note-none

#30524 Implement BenchmarkFileStore
  server/platform/shared/filestore/filesstore_test.go
Labels: 4: Reviews Complete, Docs/Needed, release-note-none, E2E/Overridden

#30293 Add WebSocket client ping implementation
  webapp/channels/src/components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  webapp/platform/client/src/websocket.test.ts
  webapp/platform/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note

#30566 Create bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, E2E/Overridden

#26215 [MM-56078] mmctl: assume local mode when no credentials found
  server/cmd/mmctl/commands/completion.go
  server/cmd/mmctl/commands/init.go
Labels: 4: Reviews Complete, Docs/Needed, release-note-none

#30124 [GH-30056] Refactor SELECT statements in compliance_store.go
  server/channels/store/sqlstore/compliance_store.go
  server/channels/store/storetest/compliance_store.go
Labels: Lifecycle/frozen, release-note-none, Contributor, E2E/Overridden

#30518 [MM-63513] Turn Cross team search feature flag into a setting option
  e2e-tests/cypress/tests/support/api/on_prem_default_config.json
  e2e-tests/playwright/support/server/default_config.ts
  e2e-tests/playwright/tests/functional/channels/search/team_selector.spec.ts
  server/config/client.go
  server/platform/services/telemetry/telemetry.go
  server/public/model/config.go
  server/public/model/feature_flags.go
  server/tests/test-config.json
  webapp/channels/src/components/new_search/new_search.tsx
  webapp/channels/src/components/search/index.tsx
  webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
  webapp/platform/types/src/config.ts
Labels: 4: Reviews Complete, Docs/Needed, QA - Deferred, release-note, E2E/Overridden

#30059 Add e2e tests for showCommandCmdF
  server/cmd/mmctl/commands/command_e2e_test.go
Labels: 4: Reviews Complete, release-note-none, Contributor, E2E/Overridden

#30453 Display nickname or fullname in Threads based on settings
  webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.test.tsx
  webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#30535 [MM-63534] Show errors from Support Packet generation in System Console
  webapp/channels/src/components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
  webapp/channels/src/components/commercial_support_modal/commercial_support_modal.scss
  webapp/channels/src/components/commercial_support_modal/commercial_support_modal.test.tsx
  webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx
Labels: 4: Reviews Complete, release-note, E2E/Overridden

#30456 Add system console settings for mobile security
  e2e-tests/cypress/tests/support/api/role.js
  e2e-tests/playwright/support/ui/components/index.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/feature_discovery.ts
  e2e-tests/playwright/support/ui/components/system_console/sections/system_users/mobile_security.ts
  e2e-tests/playwright/support/ui/pages/system_console.ts
  e2e-tests/playwright/tests/functional/system_console/mobile_security.spec.ts
  server/channels/app/permissions_migrations.go
  server/channels/testlib/store.go
  server/public/model/migration.go
  server/public/model/permission.go
  webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_definition.tsx
  webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  webapp/channels/src/components/admin_console/admin_sidebar/admin_sidebar.test.tsx
  webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/images/mobile_security_svg.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/index.ts
  webapp/channels/src/components/admin_console/feature_discovery/features/mobile_security.test.tsx
  webapp/channels/src/components/admin_console/feature_discovery/features/mobile_security.tsx
  webapp/channels/src/components/admin_console/schema_admin_settings.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  webapp/channels/src/components/admin_console/system_roles/system_role/strings.tsx
  webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx
  webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  webapp/channels/src/i18n/en.json
  webapp/channels/src/packages/mattermost-redux/src/constants/permissions.ts
  webapp/channels/src/packages/mattermost-redux/src/constants/permissions_sysconsole.ts
  webapp/channels/src/sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA - Review Done, release-note-none

#30562 MM-58521 Hide emoji categories while searching emoji picker
  webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  webapp/channels/src/components/emoji_picker/components/emoji_picker_categories.tsx
  webapp/channels/src/components/emoji_picker/components/emoji_picker_current_results.tsx
  webapp/channels/src/components/emoji_picker/constants/index.ts
  webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
  webapp/channels/src/components/emoji_picker/emoji_picker.tsx
  webapp/channels/src/sass/components/_emoticons.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, E2E/Overridden

#30575 Return error as last value in BulkImport functions
  server/channels/app/export_test.go
  server/channels/app/import.go
  server/channels/app/import_test.go
  server/channels/jobs/import_process/worker.go
  server/cmd/mattermost/commands/import.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30547 Draft link activation
  webapp/channels/src/components/drafts/drafts_link/__snapshots__/drafts_link.test.tsx.snap
  webapp/channels/src/components/drafts/drafts_link/drafts_link.test.tsx
  webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
Labels: Setup Cloud Test Server, QA - Review Done, release-note-none

#30581 [MM-63586] Fix Jump to recents dismiss icon visibility
  webapp/channels/src/components/scroll_to_bottom_toast/scroll_to_bottom_toast.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA - Review Not Required, release-note-none, E2E/Overridden

#30464 MM-62155: Avoid SELECT * in team_store.go
  server/channels/store/sqlstore/team_store.go
Labels: release-note-none, E2E/Overridden

#30537 [MM-63504] When changing a team to group synced, it doesn't always clear members
  server/channels/api4/team.go
  server/channels/api4/team_test.go
  server/channels/app/syncables.go
  webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
Labels: 4: Reviews Complete, release-note-none

#30583 MM-63577 Enable EnableLocalMode automatically during development
  server/channels/app/platform/service.go
Labels: 4: Reviews Complete, release-note-none

#30423 MM-62160: Avoid SELECT * in user_terms_of_service.go and terms_of_service_store.go
  server/channels/store/sqlstore/terms_of_service_store.go
  server/channels/store/sqlstore/user_terms_of_service.go
Labels: QA - Review Not Required, release-note-none, E2E/Overridden

#30463 MM-62154: Avoid SELECT * in webhook_store.go
  server/channels/store/sqlstore/webhook_store.go
Labels: 4: Reviews Complete, release-note-none, E2E/Overridden

#30574 MM-63387 Check Feature flag before custom field retrieval
  webapp/channels/src/components/root/index.ts
  webapp/channels/src/components/root/root.test.tsx
  webapp/channels/src/components/root/root.tsx
Labels: 4: Reviews Complete, QA - Review Done, release-note-none

#30590 Automated cherry pick of #30547
  webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.test.tsx
  webapp/channels/src/components/drafts/drafts_link/__snapshots__/drafts_link.test.tsx.snap
  webapp/channels/src/components/drafts/drafts_link/drafts_link.test.tsx
  webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
  webapp/channels/src/tests/setup_jest.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#30421 MM-62162: Replace SELECT * in user_access_token_store.go
  server/channels/store/sqlstore/user_access_token_store.go
  server/channels/store/storetest/user_access_token_store.go
Labels: 4: Reviews Complete, QA - Review Not Required, release-note-none, E2E/Overridden

#30420 Adds a groupID filter to the property service methods
  server/channels/api4/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes.go
  server/channels/app/custom_profile_attributes_test.go
  server/channels/app/properties/property_field.go
  server/channels/app/properties/property_value.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/property_field_store.go
  server/channels/store/sqlstore/property_value_store.go
  server/channels/store/store.go
  server/channels/store/storetest/mocks/PropertyFieldStore.go
  server/channels/store/storetest/mocks/PropertyValueStore.go
  server/channels/store/storetest/property_field_store.go
  server/channels/store/storetest/property_value_store.go
  server/channels/store/timerlayer/timerlayer.go
  server/i18n/en.json
  server/public/model/property_field.go
  server/public/model/property_field_test.go
Labels: 4: Reviews Complete, release-note-none

#30387 MM-63311
  server/channels/api4/group.go
  server/channels/api4/group_test.go
  server/channels/app/group.go
  server/channels/app/plugin_api.go
  server/channels/store/retrylayer/retrylayer.go
  server/channels/store/sqlstore/group_store.go
  server/channels/store/store.go
  server/channels/store/storetest/group_store.go
  server/channels/store/storetest/mocks/GroupStore.go
  server/channels/store/timerlayer/timerlayer.go
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, E2E/Overridden
